import type { ProblemComplexityKnowledge } from "../../types"

export const maximumUnitsOnTruckComplexity: ProblemComplexityKnowledge = {
  problemId: "dsa-maximum-units-on-truck",
  leetcodeNumber: 1710,
  slug: "maximum-units-on-a-truck",
  problemTitle: "Maximum Units on a Truck",
  sourceUrl: "https://leetcode.com/problems/maximum-units-on-a-truck/",
  difficulty: "Easy",
  tags: ["Array", "Greedy", "Sorting"],
  approaches: [
    {
      name: "Greedy with Sorting",
      timeComplexity: "O(n log n)",
      spaceComplexity: "O(1)",
      tradeOff: "Sort by units per box descending, greedily fill truck",
      whenToUse: "Standard optimal approach - always prioritize boxes with most units",
      codePattern: "Sort by unitsPerBox desc, iterate and take min(available, remaining capacity)",
      isOptimalTime: true,
      isOptimalSpace: true,
      source: "leetcode-editorial",
    },
    {
      name: "Counting Sort (Constraint-based)",
      timeComplexity: "O(n + M)",
      spaceComplexity: "O(M)",
      tradeOff: "Faster when M (max units) is small - uses bucket counting",
      whenToUse: "When unitsPerBox is bounded (M=1000 in this problem)",
      codePattern: "Count boxes at each unit level, iterate from highest to lowest",
      isOptimalTime: true,
      isOptimalSpace: false,
      source: "algorithm-textbook",
    },
    {
      name: "Brute Force (All Combinations)",
      timeComplexity: "O(2^n)",
      spaceComplexity: "O(n)",
      tradeOff: "Exponential - try all subsets of boxes",
      whenToUse: "Never in practice - only for understanding",
      codePattern: "Generate all subsets, check capacity, find max units",
      isOptimalTime: false,
      isOptimalSpace: false,
      source: "algorithm-textbook",
    },
  ],
  commonMistakes: [
    "Not sorting by units per box (must maximize value per slot)",
    "Taking more boxes than available for a type",
    "Forgetting to stop when truck is full",
    "Using O(n) space for sorting when in-place is possible",
  ],
  keyOperations: [
    { operation: "Sorting", complexity: "O(n log n)" },
    { operation: "Greedy selection loop", complexity: "O(n)" },
    { operation: "Box count comparison", complexity: "O(1)" },
  ],
  verified: true,
  verifiedAt: "2026-01-14",
  verificationSource: "leetcode-editorial",
}
