import type { ProblemComplexityKnowledge } from "../../types"

export const maximumSubarrayComplexity: ProblemComplexityKnowledge = {
  problemId: "dsa-maximum-subarray",
  leetcodeNumber: 53,
  slug: "maximum-subarray",
  problemTitle: "Maximum Subarray",
  sourceUrl: "https://leetcode.com/problems/maximum-subarray/",
  difficulty: "Medium",
  tags: ["Array", "Divide and Conquer", "Dynamic Programming"],
  approaches: [
    {
      name: "Kadane's Algorithm",
      timeComplexity: "O(n)",
      spaceComplexity: "O(1)",
      tradeOff: "Optimal - single pass DP with constant space",
      whenToUse: "Always preferred - the standard optimal solution",
      codePattern: "Track currentMax and globalMax; currentMax = max(num, currentMax + num)",
      isOptimalTime: true,
      isOptimalSpace: true,
      source: "leetcode-editorial",
    },
    {
      name: "Divide and Conquer",
      timeComplexity: "O(n log n)",
      spaceComplexity: "O(log n)",
      tradeOff: "Slower but demonstrates D&C skills - asked as follow-up",
      whenToUse: "When interviewer explicitly asks for D&C or to show recursive thinking",
      codePattern: "Max of left half, right half, or crossing middle",
      isOptimalTime: false,
      isOptimalSpace: false,
      source: "algorithm-textbook",
    },
    {
      name: "Brute Force",
      timeComplexity: "O(n^2)",
      spaceComplexity: "O(1)",
      tradeOff: "Simple but slow - check all subarrays",
      whenToUse: "Only to explain progression to optimal solution",
      codePattern: "Two nested loops: for each start, extend to each end",
      isOptimalTime: false,
      isOptimalSpace: true,
      source: "algorithm-textbook",
    },
  ],
  commonMistakes: [
    "Claiming O(n log n) for Kadane's (it's O(n))",
    "Confusing Kadane's with D&C approach",
    "Not handling all-negative arrays correctly",
    "Returning 0 instead of the largest negative when no positive exists",
    "Not recognizing this as DP (currentMax at each index is a DP state)",
  ],
  keyOperations: [
    {
      operation: "Single element decision",
      complexity: "O(1)",
      note: "Extend or restart subarray",
    },
    { operation: "Array iteration", complexity: "O(n)" },
    { operation: "D&C: Finding crossing max", complexity: "O(n)", note: "Dominates recursion" },
  ],
  verified: true,
  verifiedAt: "2026-01-14",
  verificationSource: "leetcode-editorial",
}
