import type { ProblemComplexityKnowledge } from "../../types"

export const topKFrequentComplexity: ProblemComplexityKnowledge = {
  problemId: "dsa-top-k-frequent",
  leetcodeNumber: 347,
  slug: "top-k-frequent-elements",
  problemTitle: "Top K Frequent Elements",
  sourceUrl: "https://leetcode.com/problems/top-k-frequent-elements/editorial/",
  difficulty: "Medium",
  tags: [
    "Array",
    "Hash Table",
    "Divide and Conquer",
    "Sorting",
    "Heap (Priority Queue)",
    "Bucket Sort",
    "Counting",
    "Quickselect",
  ],
  approaches: [
    {
      name: "Heap",
      timeComplexity: "O(n log k)",
      spaceComplexity: "O(n + k)",
      tradeOff: "Good when k is small compared to n",
      whenToUse: "When k << n and you want guaranteed performance",
      codePattern: "Count frequencies, maintain min-heap of size k",
      isOptimalTime: false,
      isOptimalSpace: false,
      source: "leetcode-editorial",
    },
    {
      name: "Quickselect",
      timeComplexity: "O(n)",
      spaceComplexity: "O(n)",
      tradeOff: "Fastest average case but O(n^2) worst case",
      whenToUse: "When average case performance matters most",
      codePattern: "Partition around kth most frequent element",
      isOptimalTime: true,
      isOptimalSpace: false,
      source: "leetcode-editorial",
    },
    {
      name: "Bucket Sort",
      timeComplexity: "O(n)",
      spaceComplexity: "O(n)",
      tradeOff: "Linear time guaranteed but uses more space",
      whenToUse: "When you need guaranteed O(n) time",
      codePattern: "Buckets by frequency, iterate from highest",
      isOptimalTime: true,
      isOptimalSpace: false,
      source: "algorithm-textbook",
    },
  ],
  commonMistakes: [
    "Using max-heap of size n instead of min-heap of size k",
    "Forgetting the O(n) for counting frequencies",
    "Not considering worst case of quickselect",
  ],
  keyOperations: [
    { operation: "Frequency counting", complexity: "O(n)" },
    { operation: "Heap push/pop", complexity: "O(log k)" },
    { operation: "Quickselect partition", complexity: "O(n) average" },
  ],
  verified: true,
  verifiedAt: "2026-01-13",
  verificationSource: "leetcode-editorial",
}
