/**
 * Problem Complexity Knowledge Base
 *
 * Contains verified complexity data for DSA problems.
 * Data sources:
 * - LeetCode official editorials (primary)
 * - Well-established algorithm textbooks (CLRS, etc.)
 * - NeetCode verified solutions
 *
 * IMPORTANT: All data here has been verified against official sources.
 * Do NOT add data without verification.
 */

import type { ProblemComplexityKnowledge, ProblemApproach, PatternComplexityRules } from "./types"
import type { DSAPattern } from "@/lib/types/dsa-patterns"

/**
 * Problem complexity data - verified from LeetCode editorials and algorithm knowledge
 */
export const PROBLEM_COMPLEXITY_DATA: ProblemComplexityKnowledge[] = [
  // ============================================
  // ARRAYS & HASHING
  // ============================================
  {
    problemId: "dsa-two-sum",
    leetcodeNumber: 1,
    slug: "two-sum",
    problemTitle: "Two Sum",
    sourceUrl: "https://leetcode.com/problems/two-sum/editorial/",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    approaches: [
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but slow - checks all pairs",
        whenToUse: "When space is extremely limited or for very small inputs",
        codePattern: "Nested loops comparing all pairs",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Two-pass Hash Table",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Fast lookup at cost of extra space",
        whenToUse: "Standard approach when return indices are needed",
        codePattern: "First pass builds map, second pass looks up complements",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
      {
        name: "One-pass Hash Table",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Slightly more efficient - single pass",
        whenToUse: "Preferred when you want clean, single-pass code",
        codePattern: "Check and insert in same loop iteration",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Claiming O(1) space when using a hash map",
      "Forgetting hash map operations are O(1) average, O(n) worst case",
      "Not considering that returning indices requires hash map (can't sort)",
    ],
    keyOperations: [
      {
        operation: "Hash map lookup",
        complexity: "O(1) average",
        note: "Can degrade to O(n) with collisions",
      },
      { operation: "Hash map insert", complexity: "O(1) average" },
      { operation: "Array iteration", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-contains-duplicate",
    leetcodeNumber: 217,
    slug: "contains-duplicate",
    problemTitle: "Contains Duplicate",
    sourceUrl: "https://leetcode.com/problems/contains-duplicate/",
    difficulty: "Easy",
    tags: ["Array", "Hash Table", "Sorting"],
    approaches: [
      {
        name: "Hash Set",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Fast lookup at cost of extra space",
        whenToUse: "When you need O(n) time and space is available",
        codePattern: "Add to set, return true if element already exists",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Sorting",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Uses less space but modifies input and slower",
        whenToUse: "When you can modify input and space is limited",
        codePattern: "Sort then check adjacent elements",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "No extra space but very slow",
        whenToUse: "Never in practice - just for understanding",
        codePattern: "Compare each pair of elements",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Forgetting sorting approach modifies the original array",
      "Not considering in-place sorting space is O(log n) for the call stack",
    ],
    keyOperations: [
      { operation: "Set lookup/insert", complexity: "O(1) average" },
      { operation: "Sorting", complexity: "O(n log n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-valid-anagram",
    leetcodeNumber: 242,
    slug: "valid-anagram",
    problemTitle: "Valid Anagram",
    sourceUrl: "https://leetcode.com/problems/valid-anagram/",
    difficulty: "Easy",
    tags: ["Hash Table", "String", "Sorting"],
    approaches: [
      {
        name: "Character Count (Hash Map)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Fast and bounded space (26 letters)",
        whenToUse: "Preferred approach - O(1) space for lowercase letters only",
        codePattern: "Count chars in first string, decrement for second",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Sorting",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(n)",
        tradeOff: "Simple but slower due to sorting",
        whenToUse: "When code simplicity matters more than performance",
        codePattern: "Sort both strings, compare",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Saying O(n) space for hash map when only 26 letters possible (it's O(1))",
      "Not considering Unicode - changes space from O(1) to O(k) where k is charset size",
    ],
    keyOperations: [
      { operation: "Character count array access", complexity: "O(1)" },
      { operation: "String iteration", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-group-anagrams",
    leetcodeNumber: 49,
    slug: "group-anagrams",
    problemTitle: "Group Anagrams",
    sourceUrl: "https://leetcode.com/problems/group-anagrams/",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "String", "Sorting"],
    approaches: [
      {
        name: "Sorted String as Key",
        timeComplexity: "O(n * k log k)",
        spaceComplexity: "O(n * k)",
        tradeOff: "Simple to implement, sorting each string",
        whenToUse: "When strings are short or code clarity is priority",
        codePattern: "Use sorted string as hash map key",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Character Count as Key",
        timeComplexity: "O(n * k)",
        spaceComplexity: "O(n * k)",
        tradeOff: "Faster but more complex key generation",
        whenToUse: "When strings are long - avoids k log k sorting",
        codePattern: "Use character count tuple/string as hash key",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Forgetting the k factor - k is average string length",
      "Not accounting for the space to store all strings in result",
    ],
    keyOperations: [
      { operation: "Sort string of length k", complexity: "O(k log k)" },
      { operation: "Character count of string", complexity: "O(k)" },
      { operation: "Hash map operations", complexity: "O(1) average" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-top-k-frequent",
    leetcodeNumber: 347,
    slug: "top-k-frequent-elements",
    problemTitle: "Top K Frequent Elements",
    sourceUrl: "https://leetcode.com/problems/top-k-frequent-elements/editorial/",
    difficulty: "Medium",
    tags: [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect",
    ],
    approaches: [
      {
        name: "Heap",
        timeComplexity: "O(n log k)",
        spaceComplexity: "O(n + k)",
        tradeOff: "Good when k is small compared to n",
        whenToUse: "When k << n and you want guaranteed performance",
        codePattern: "Count frequencies, maintain min-heap of size k",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
      {
        name: "Quickselect",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Fastest average case but O(n^2) worst case",
        whenToUse: "When average case performance matters most",
        codePattern: "Partition around kth most frequent element",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
      {
        name: "Bucket Sort",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Linear time guaranteed but uses more space",
        whenToUse: "When you need guaranteed O(n) time",
        codePattern: "Buckets by frequency, iterate from highest",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Using max-heap of size n instead of min-heap of size k",
      "Forgetting the O(n) for counting frequencies",
      "Not considering worst case of quickselect",
    ],
    keyOperations: [
      { operation: "Frequency counting", complexity: "O(n)" },
      { operation: "Heap push/pop", complexity: "O(log k)" },
      { operation: "Quickselect partition", complexity: "O(n) average" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-product-except-self",
    leetcodeNumber: 238,
    slug: "product-of-array-except-self",
    problemTitle: "Product of Array Except Self",
    sourceUrl: "https://leetcode.com/problems/product-of-array-except-self/",
    difficulty: "Medium",
    tags: ["Array", "Prefix Sum"],
    approaches: [
      {
        name: "Left and Right Arrays",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Clear to understand but uses extra arrays",
        whenToUse: "When code clarity is priority",
        codePattern: "Build prefix and suffix product arrays separately",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Space Optimized (Output Array)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Uses output array for left products, single var for right",
        whenToUse: "When space optimization is needed (output doesn't count)",
        codePattern: "Two passes: left products in output, then multiply right",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Using division (problem explicitly forbids it)",
      "Forgetting to handle zeros in the array",
      "Not realizing output array doesn't count toward space complexity",
    ],
    keyOperations: [
      { operation: "Prefix product calculation", complexity: "O(n)" },
      { operation: "Suffix product calculation", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-longest-consecutive",
    leetcodeNumber: 128,
    slug: "longest-consecutive-sequence",
    problemTitle: "Longest Consecutive Sequence",
    sourceUrl: "https://leetcode.com/problems/longest-consecutive-sequence/",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Union Find"],
    approaches: [
      {
        name: "Hash Set",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal time with hash set lookups",
        whenToUse: "Standard approach - only start counting from sequence starts",
        codePattern: "Only count from numbers where n-1 doesn't exist",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Sorting",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Uses less space but doesn't meet O(n) requirement",
        whenToUse: "When O(n) time isn't required",
        codePattern: "Sort then iterate checking consecutive pairs",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Union Find",
        timeComplexity: "O(n * α(n))",
        spaceComplexity: "O(n)",
        tradeOff: "Practically O(n) with inverse Ackermann function",
        whenToUse: "When you're comfortable with Union Find",
        codePattern: "Union consecutive numbers, track set sizes",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Starting count from every number (makes it O(n^2))",
      "Not handling duplicates in the array",
      "Forgetting the key insight: only start from sequence beginnings",
    ],
    keyOperations: [
      { operation: "Hash set lookup", complexity: "O(1) average" },
      { operation: "Sequence traversal", complexity: "O(k) where k is sequence length" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // TWO POINTERS
  // ============================================
  {
    problemId: "dsa-valid-palindrome",
    leetcodeNumber: 125,
    slug: "valid-palindrome",
    problemTitle: "Valid Palindrome",
    sourceUrl: "https://leetcode.com/problems/valid-palindrome/",
    difficulty: "Easy",
    tags: ["Two Pointers", "String"],
    approaches: [
      {
        name: "Two Pointers",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal in every way for this problem",
        whenToUse: "Always - this is the standard approach",
        codePattern: "Left and right pointers moving toward center",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Reverse and Compare",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Simple but uses extra space for reversed string",
        whenToUse: "When code simplicity matters more than space",
        codePattern: "Filter alphanumeric, compare with reverse",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Forgetting to skip non-alphanumeric characters",
      "Not handling case insensitivity",
      "Creating new string instead of using pointers (wastes O(n) space)",
    ],
    keyOperations: [
      { operation: "Character comparison", complexity: "O(1)" },
      { operation: "Pointer movement", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-three-sum",
    leetcodeNumber: 15,
    slug: "3sum",
    problemTitle: "3Sum",
    sourceUrl: "https://leetcode.com/problems/3sum/",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    approaches: [
      {
        name: "Sort + Two Pointers",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Best known approach - can't do better than O(n^2)",
        whenToUse: "Standard approach - sort enables two-pointer technique",
        codePattern: "Fix one element, two-pointer search for other two",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Hash Set",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(n)",
        tradeOff: "Same time but uses more space, avoiding sort",
        whenToUse: "When you can't modify the input array",
        codePattern: "For each pair, check if complement exists in set",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling duplicate triplets",
      "Forgetting to skip duplicate values when iterating",
      "Not sorting first (required for two-pointer technique)",
    ],
    keyOperations: [
      { operation: "Sorting", complexity: "O(n log n)" },
      { operation: "Two-pointer search", complexity: "O(n)" },
      { operation: "Overall", complexity: "O(n) * O(n) = O(n^2)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-container-water",
    leetcodeNumber: 11,
    slug: "container-with-most-water",
    problemTitle: "Container With Most Water",
    sourceUrl: "https://leetcode.com/problems/container-with-most-water/",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Greedy"],
    approaches: [
      {
        name: "Two Pointers",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - greedy choice to move shorter line inward",
        whenToUse: "Always - this is the standard approach",
        codePattern: "Start at ends, move pointer with shorter line",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but too slow for large inputs",
        whenToUse: "Only for understanding the problem",
        codePattern: "Check all pairs of lines",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not understanding why moving shorter line is correct (greedy proof)",
      "Calculating area incorrectly (min height * width)",
    ],
    keyOperations: [
      { operation: "Area calculation", complexity: "O(1)" },
      { operation: "Pointer movement", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-trapping-rain-water",
    leetcodeNumber: 42,
    slug: "trapping-rain-water",
    problemTitle: "Trapping Rain Water",
    sourceUrl: "https://leetcode.com/problems/trapping-rain-water/",
    difficulty: "Hard",
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack", "Monotonic Stack"],
    approaches: [
      {
        name: "Two Pointers",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal in both time and space",
        whenToUse: "Best approach when you understand the logic",
        codePattern: "Track left_max and right_max, process shorter side",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Dynamic Programming",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Easier to understand but uses extra space",
        whenToUse: "When two-pointer logic is confusing",
        codePattern: "Precompute left_max and right_max arrays",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Monotonic Stack",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Alternative approach using stack",
        whenToUse: "When you're comfortable with monotonic stacks",
        codePattern: "Maintain decreasing stack, compute water when popping",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Computing water incorrectly - it's min(left_max, right_max) - height",
      "Off-by-one errors at boundaries",
      "Not understanding why two-pointer works (processing shorter side)",
    ],
    keyOperations: [
      { operation: "Water at position", complexity: "O(1)" },
      { operation: "Array traversal", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // SLIDING WINDOW
  // ============================================
  {
    problemId: "dsa-best-time-buy-sell",
    leetcodeNumber: 121,
    slug: "best-time-to-buy-and-sell-stock",
    problemTitle: "Best Time to Buy and Sell Stock",
    sourceUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    approaches: [
      {
        name: "One Pass (Track Minimum)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - simple tracking approach",
        whenToUse: "Always - this is the standard approach",
        codePattern: "Track min price seen, calculate max profit at each point",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but too slow",
        whenToUse: "Only for understanding",
        codePattern: "Check all buy-sell pairs",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not understanding you must buy before selling",
      "Returning negative profit instead of 0",
      "Using max price instead of tracking min price",
    ],
    keyOperations: [
      { operation: "Update minimum", complexity: "O(1)" },
      { operation: "Calculate profit", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-longest-substring",
    leetcodeNumber: 3,
    slug: "longest-substring-without-repeating-characters",
    problemTitle: "Longest Substring Without Repeating Characters",
    sourceUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    approaches: [
      {
        name: "Sliding Window with Hash Map",
        timeComplexity: "O(n)",
        spaceComplexity: "O(min(m, n))",
        tradeOff: "Optimal time, space bounded by charset size",
        whenToUse: "Standard approach for this type of problem",
        codePattern: "Expand right, shrink left when duplicate found",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Sliding Window with Array (ASCII)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Faster constant operations, fixed charset",
        whenToUse: "When input is only ASCII characters",
        codePattern: "Use 128-element array instead of hash map",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not updating the left pointer correctly when duplicate found",
      "Using last occurrence index instead of current window tracking",
      "Forgetting m is charset size in space complexity",
    ],
    keyOperations: [
      { operation: "Hash map/set operations", complexity: "O(1)" },
      { operation: "Window expansion", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-longest-repeating-replacement",
    leetcodeNumber: 424,
    slug: "longest-repeating-character-replacement",
    problemTitle: "Longest Repeating Character Replacement",
    sourceUrl: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    approaches: [
      {
        name: "Sliding Window",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - 26 letters means O(1) space",
        whenToUse: "Standard approach for this problem",
        codePattern: "Window valid when length - maxCount <= k",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Recalculating max frequency from scratch (not needed)",
      "Not understanding the window validity condition",
      "Shrinking window unnecessarily - maxCount only needs to increase",
    ],
    keyOperations: [
      { operation: "Character count update", complexity: "O(1)" },
      { operation: "Window expansion", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-min-window-substring",
    leetcodeNumber: 76,
    slug: "minimum-window-substring",
    problemTitle: "Minimum Window Substring",
    sourceUrl: "https://leetcode.com/problems/minimum-window-substring/",
    difficulty: "Hard",
    tags: ["Hash Table", "String", "Sliding Window"],
    approaches: [
      {
        name: "Sliding Window with Hash Map",
        timeComplexity: "O(n + m)",
        spaceComplexity: "O(m)",
        tradeOff: "Optimal - each character visited at most twice",
        whenToUse: "Standard approach for minimum window problems",
        codePattern: "Expand to find valid window, shrink to minimize",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Optimized with Filtered String",
        timeComplexity: "O(n + m)",
        spaceComplexity: "O(m)",
        tradeOff: "Faster when s has many characters not in t",
        whenToUse: "When most characters in s aren't in t",
        codePattern: "Pre-filter s to only characters in t",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling duplicate characters in t correctly",
      "Off-by-one in window boundaries",
      "Shrinking before finding first valid window",
    ],
    keyOperations: [
      { operation: "Character count check", complexity: "O(1)" },
      { operation: "Window expansion/shrinking", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // STACK
  // ============================================
  {
    problemId: "dsa-valid-parentheses",
    leetcodeNumber: 20,
    slug: "valid-parentheses",
    problemTitle: "Valid Parentheses",
    sourceUrl: "https://leetcode.com/problems/valid-parentheses/",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    approaches: [
      {
        name: "Stack",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal for this type of problem",
        whenToUse: "Always - classic stack application",
        codePattern: "Push opening brackets, pop and match closing",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not checking if stack is empty before popping",
      "Forgetting to check stack is empty at end (unmatched opens)",
      "Using wrong mapping for bracket pairs",
    ],
    keyOperations: [
      { operation: "Stack push/pop", complexity: "O(1)" },
      { operation: "String traversal", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-min-stack",
    leetcodeNumber: 155,
    slug: "min-stack",
    problemTitle: "Min Stack",
    sourceUrl: "https://leetcode.com/problems/min-stack/",
    difficulty: "Medium",
    tags: ["Stack", "Design"],
    approaches: [
      {
        name: "Two Stacks",
        timeComplexity: "O(1)",
        spaceComplexity: "O(n)",
        tradeOff: "O(1) for all operations including getMin",
        whenToUse: "Standard approach - separate stack for minimums",
        codePattern: "Second stack tracks minimum at each level",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Single Stack with Pairs",
        timeComplexity: "O(1)",
        spaceComplexity: "O(n)",
        tradeOff: "Same complexity, stores (value, min) pairs",
        whenToUse: "Alternative if you prefer tuples",
        codePattern: "Each element stores value and current min",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Updating min stack only when new min (wrong - need for each push)",
      "Not handling equal values in min stack correctly",
    ],
    keyOperations: [{ operation: "All operations", complexity: "O(1)" }],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-daily-temperatures",
    leetcodeNumber: 739,
    slug: "daily-temperatures",
    problemTitle: "Daily Temperatures",
    sourceUrl: "https://leetcode.com/problems/daily-temperatures/",
    difficulty: "Medium",
    tags: ["Array", "Stack", "Monotonic Stack"],
    approaches: [
      {
        name: "Monotonic Stack",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Each element pushed and popped at most once",
        whenToUse: "Classic next greater element pattern",
        codePattern: "Maintain decreasing stack of indices",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but slow",
        whenToUse: "Only for understanding",
        codePattern: "For each day, search forward for warmer day",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not understanding monotonic stack invariant",
      "Storing values instead of indices in stack",
      "Not computing days difference correctly",
    ],
    keyOperations: [
      { operation: "Stack push/pop", complexity: "O(1)" },
      { operation: "Each element processed once", complexity: "O(n) total" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-largest-rectangle-histogram",
    leetcodeNumber: 84,
    slug: "largest-rectangle-in-histogram",
    problemTitle: "Largest Rectangle in Histogram",
    sourceUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    difficulty: "Hard",
    tags: ["Array", "Stack", "Monotonic Stack"],
    approaches: [
      {
        name: "Monotonic Stack",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal - each bar pushed and popped once",
        whenToUse: "Standard approach for this problem",
        codePattern: "Maintain increasing stack, compute area when popping",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Divide and Conquer",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(n)",
        tradeOff: "Alternative approach, worse average but intuitive",
        whenToUse: "If monotonic stack is confusing",
        codePattern: "Find min bar, recurse on left and right",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not adding sentinel values (0) at ends",
      "Computing width incorrectly when popping",
      "Not handling equal heights correctly",
    ],
    keyOperations: [
      { operation: "Stack operations", complexity: "O(1)" },
      { operation: "Area calculation", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // BINARY SEARCH
  // ============================================
  {
    problemId: "dsa-binary-search",
    leetcodeNumber: 704,
    slug: "binary-search",
    problemTitle: "Binary Search",
    sourceUrl: "https://leetcode.com/problems/binary-search/editorial/",
    difficulty: "Easy",
    tags: ["Array", "Binary Search"],
    approaches: [
      {
        name: "Standard Binary Search",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal for sorted array search",
        whenToUse: "When array is sorted and you need to find exact value",
        codePattern: "while left <= right, narrow based on mid comparison",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Lower/Upper Bound Variants",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Same complexity, finds boundary positions",
        whenToUse: "When finding insertion point or range boundaries",
        codePattern: "while left < right with asymmetric narrowing",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Off-by-one in loop condition (< vs <=)",
      "Integer overflow in mid calculation (use left + (right - left) / 2)",
      "Infinite loop from wrong pointer update",
    ],
    keyOperations: [
      { operation: "Comparison", complexity: "O(1)" },
      { operation: "Search space halved", complexity: "log n iterations" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-search-rotated-array",
    leetcodeNumber: 33,
    slug: "search-in-rotated-sorted-array",
    problemTitle: "Search in Rotated Sorted Array",
    sourceUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    approaches: [
      {
        name: "Modified Binary Search",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - one pass binary search",
        whenToUse: "Standard approach - determine which half is sorted",
        codePattern: "Check which half is sorted, then narrow search",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Find Pivot + Binary Search",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Two binary searches but easier to understand",
        whenToUse: "If single-pass approach is confusing",
        codePattern: "Find rotation point, then binary search correct half",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling the case where array isn't rotated",
      "Wrong comparison to determine sorted half",
      "Off-by-one when target equals boundary",
    ],
    keyOperations: [
      { operation: "Determine sorted half", complexity: "O(1)" },
      { operation: "Binary search", complexity: "O(log n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-find-min-rotated",
    leetcodeNumber: 153,
    slug: "find-minimum-in-rotated-sorted-array",
    problemTitle: "Find Minimum in Rotated Sorted Array",
    sourceUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    approaches: [
      {
        name: "Binary Search",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal for this problem",
        whenToUse: "Standard approach - compare mid with right",
        codePattern: "If mid > right, min is in right half",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Comparing with wrong element (should compare mid with right, not left)",
      "Not handling non-rotated array case",
      "Wrong pointer update causing infinite loop",
    ],
    keyOperations: [{ operation: "Binary search", complexity: "O(log n)" }],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-median-two-arrays",
    leetcodeNumber: 4,
    slug: "median-of-two-sorted-arrays",
    problemTitle: "Median of Two Sorted Arrays",
    sourceUrl: "https://leetcode.com/problems/median-of-two-sorted-arrays/editorial/",
    difficulty: "Hard",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    approaches: [
      {
        name: "Merge Sort",
        timeComplexity: "O(m + n)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but doesn't meet O(log) requirement",
        whenToUse: "When O(m+n) time is acceptable",
        codePattern: "Two pointers merging until median position",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Binary Search on Partition",
        timeComplexity: "O(log(min(m, n)))",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - meets the O(log) requirement",
        whenToUse: "When you need O(log) time complexity",
        codePattern: "Binary search partition point in smaller array",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Not binary searching on the smaller array",
      "Handling edge cases when partition is at extremes",
      "Off-by-one in median calculation for even/odd total length",
    ],
    keyOperations: [
      { operation: "Partition validation", complexity: "O(1)" },
      { operation: "Binary search iterations", complexity: "O(log min(m,n))" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  // ============================================
  // LINKED LIST
  // ============================================
  {
    problemId: "dsa-reverse-linked-list",
    leetcodeNumber: 206,
    slug: "reverse-linked-list",
    problemTitle: "Reverse Linked List",
    sourceUrl: "https://leetcode.com/problems/reverse-linked-list/",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    approaches: [
      {
        name: "Iterative",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal space, no call stack overhead",
        whenToUse: "Preferred approach for production code",
        codePattern: "Three pointers: prev, curr, next",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Recursive",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Elegant but uses call stack space",
        whenToUse: "When recursion is preferred for clarity",
        codePattern: "Recurse to end, reverse links on way back",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Losing reference to next node before updating link",
      "Not handling empty list or single node",
      "Forgetting to return new head",
    ],
    keyOperations: [
      { operation: "Pointer manipulation", complexity: "O(1)" },
      { operation: "List traversal", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-merge-two-lists",
    leetcodeNumber: 21,
    slug: "merge-two-sorted-lists",
    problemTitle: "Merge Two Sorted Lists",
    sourceUrl: "https://leetcode.com/problems/merge-two-sorted-lists/",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    approaches: [
      {
        name: "Iterative",
        timeComplexity: "O(n + m)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal space with dummy head technique",
        whenToUse: "Preferred for production - no stack overhead",
        codePattern: "Dummy head, append smaller node each step",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Recursive",
        timeComplexity: "O(n + m)",
        spaceComplexity: "O(n + m)",
        tradeOff: "Elegant but uses call stack",
        whenToUse: "When recursion is preferred for clarity",
        codePattern: "Return smaller node with recursive next",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling when one list is empty",
      "Forgetting to advance pointer after appending",
      "Not using dummy head (makes code complex)",
    ],
    keyOperations: [
      { operation: "Comparison", complexity: "O(1)" },
      { operation: "Node append", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-linked-list-cycle",
    leetcodeNumber: 141,
    slug: "linked-list-cycle",
    problemTitle: "Linked List Cycle",
    sourceUrl: "https://leetcode.com/problems/linked-list-cycle/",
    difficulty: "Easy",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    approaches: [
      {
        name: "Floyd's Cycle Detection (Two Pointers)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal in both time and space",
        whenToUse: "Always - this is the standard approach",
        codePattern: "Slow and fast pointers, cycle if they meet",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Hash Set",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Simple but uses extra space",
        whenToUse: "When Floyd's is confusing",
        codePattern: "Store visited nodes, check for revisit",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling empty list or single node",
      "Wrong termination condition for fast pointer",
      "Checking fast.next before checking fast",
    ],
    keyOperations: [
      { operation: "Pointer advancement", complexity: "O(1)" },
      { operation: "Cycle detection", complexity: "O(n) iterations max" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-lru-cache",
    leetcodeNumber: 146,
    slug: "lru-cache",
    problemTitle: "LRU Cache",
    sourceUrl: "https://leetcode.com/problems/lru-cache/",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    approaches: [
      {
        name: "Hash Map + Doubly Linked List",
        timeComplexity: "O(1)",
        spaceComplexity: "O(capacity)",
        tradeOff: "Optimal O(1) for both get and put",
        whenToUse: "Standard approach - required for O(1) operations",
        codePattern: "Map for lookup, DLL for order tracking",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Using singly linked list (can't remove in O(1))",
      "Not updating order on get (only on put)",
      "Off-by-one in capacity checking",
    ],
    keyOperations: [
      { operation: "Get", complexity: "O(1)" },
      { operation: "Put", complexity: "O(1)" },
      { operation: "Move to front", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-merge-k-lists",
    leetcodeNumber: 23,
    slug: "merge-k-sorted-lists",
    problemTitle: "Merge k Sorted Lists",
    sourceUrl: "https://leetcode.com/problems/merge-k-sorted-lists/",
    difficulty: "Hard",
    tags: ["Linked List", "Divide and Conquer", "Heap (Priority Queue)", "Merge Sort"],
    approaches: [
      {
        name: "Min Heap",
        timeComplexity: "O(n log k)",
        spaceComplexity: "O(k)",
        tradeOff: "Optimal - heap always has at most k elements",
        whenToUse: "When you're comfortable with heaps",
        codePattern: "Add heads to heap, pop min and add its next",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Divide and Conquer",
        timeComplexity: "O(n log k)",
        spaceComplexity: "O(log k)",
        tradeOff: "Same time, less space than heap (recursion only)",
        whenToUse: "Alternative approach using merge sort pattern",
        codePattern: "Recursively merge pairs until one list",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Merge One by One",
        timeComplexity: "O(nk)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but slower",
        whenToUse: "When k is small",
        codePattern: "Merge first two, then merge with third, etc.",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Using merge-one-by-one when k is large",
      "Not handling null lists in heap",
      "Heap comparison function wrong for custom nodes",
    ],
    keyOperations: [
      { operation: "Heap push/pop", complexity: "O(log k)" },
      { operation: "Total nodes processed", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // TREES
  // ============================================
  {
    problemId: "dsa-invert-binary-tree",
    leetcodeNumber: 226,
    slug: "invert-binary-tree",
    problemTitle: "Invert Binary Tree",
    sourceUrl: "https://leetcode.com/problems/invert-binary-tree/",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    approaches: [
      {
        name: "Recursive DFS",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "Simple and elegant, stack space for recursion",
        whenToUse: "Preferred for clean code",
        codePattern: "Swap children, recurse on both",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Iterative BFS",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Uses queue, space for widest level",
        whenToUse: "When you want to avoid recursion",
        codePattern: "Queue-based level order, swap each node's children",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: ["Not handling null nodes", "Swapping references wrong (need temp variable)"],
    keyOperations: [
      { operation: "Node swap", complexity: "O(1)" },
      { operation: "Tree traversal", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-max-depth-tree",
    leetcodeNumber: 104,
    slug: "maximum-depth-of-binary-tree",
    problemTitle: "Maximum Depth of Binary Tree",
    sourceUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    approaches: [
      {
        name: "Recursive DFS",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "Clean one-liner, uses call stack",
        whenToUse: "Preferred for simplicity",
        codePattern: "1 + max(left_depth, right_depth)",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Iterative BFS",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Count levels, space for widest level",
        whenToUse: "When avoiding recursion",
        codePattern: "Level order traversal, count levels",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling empty tree (return 0, not error)",
      "Off-by-one in depth counting",
    ],
    keyOperations: [{ operation: "Tree traversal", complexity: "O(n)" }],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-validate-bst",
    leetcodeNumber: 98,
    slug: "validate-binary-search-tree",
    problemTitle: "Validate Binary Search Tree",
    sourceUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    approaches: [
      {
        name: "Recursive with Range",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "Elegant, passes valid range down",
        whenToUse: "Preferred approach",
        codePattern: "Check node in (min, max) range, update for children",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Inorder Traversal",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "BST inorder is sorted - just verify",
        whenToUse: "Alternative approach using BST property",
        codePattern: "Inorder traversal, check strictly increasing",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Only checking immediate children (not subtree property)",
      "Not handling equal values (BST typically requires strict inequality)",
      "Integer overflow with min/max bounds",
    ],
    keyOperations: [
      { operation: "Tree traversal", complexity: "O(n)" },
      { operation: "Range check", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-level-order-traversal",
    leetcodeNumber: 102,
    slug: "binary-tree-level-order-traversal",
    problemTitle: "Binary Tree Level Order Traversal",
    sourceUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    approaches: [
      {
        name: "BFS with Queue",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Standard BFS, space for widest level",
        whenToUse: "Classic approach for level order",
        codePattern: "Process level by level using queue size",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "DFS with Level Tracking",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "Uses recursion stack instead of queue",
        whenToUse: "When you prefer DFS",
        codePattern: "Pass level index, add to correct list",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not processing entire level before moving to next",
      "Using queue.length in loop condition (changes during loop)",
    ],
    keyOperations: [
      { operation: "Queue operations", complexity: "O(1)" },
      { operation: "Process all nodes", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-binary-tree-max-path",
    leetcodeNumber: 124,
    slug: "binary-tree-maximum-path-sum",
    problemTitle: "Binary Tree Maximum Path Sum",
    sourceUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    difficulty: "Hard",
    tags: ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
    approaches: [
      {
        name: "Recursive DFS",
        timeComplexity: "O(n)",
        spaceComplexity: "O(h)",
        tradeOff: "Track max path through each node",
        whenToUse: "Standard approach for this problem",
        codePattern: "At each node, consider path through it vs extending up",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling negative values correctly",
      "Confusing 'path through node' with 'path extending from node'",
      "Not initializing max to negative infinity",
    ],
    keyOperations: [
      { operation: "Postorder traversal", complexity: "O(n)" },
      { operation: "Max calculation at node", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // DYNAMIC PROGRAMMING
  // ============================================
  {
    problemId: "dsa-climbing-stairs",
    leetcodeNumber: 70,
    slug: "climbing-stairs",
    problemTitle: "Climbing Stairs",
    sourceUrl: "https://leetcode.com/problems/climbing-stairs/",
    difficulty: "Easy",
    tags: ["Math", "Dynamic Programming", "Memoization"],
    approaches: [
      {
        name: "Bottom-Up DP (Space Optimized)",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - only need last two values",
        whenToUse: "Preferred production approach",
        codePattern: "Track prev and curr, iterate forward",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Top-Down with Memoization",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Intuitive but uses more space",
        whenToUse: "When top-down thinking is clearer",
        codePattern: "Recursive with memo array",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Matrix Exponentiation",
        timeComplexity: "O(log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Fastest but overkill for interviews",
        whenToUse: "When you want to show off",
        codePattern: "Fibonacci via matrix power",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not recognizing this is Fibonacci",
      "Using full DP array when only need two values",
      "Off-by-one with base cases",
    ],
    keyOperations: [
      { operation: "State transition", complexity: "O(1)" },
      { operation: "Iterations", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-house-robber",
    leetcodeNumber: 198,
    slug: "house-robber",
    problemTitle: "House Robber",
    sourceUrl: "https://leetcode.com/problems/house-robber/",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming"],
    approaches: [
      {
        name: "DP with Space Optimization",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - only track two previous values",
        whenToUse: "Preferred approach",
        codePattern: "dp[i] = max(dp[i-2] + nums[i], dp[i-1])",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "DP with Array",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Easier to understand but uses more space",
        whenToUse: "When explaining the recurrence",
        codePattern: "Full DP array storing max at each house",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not handling base cases (0, 1, 2 houses)",
      "Wrong recurrence - must skip adjacent",
    ],
    keyOperations: [
      { operation: "State transition", complexity: "O(1)" },
      { operation: "Array iteration", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-longest-palindromic",
    leetcodeNumber: 5,
    slug: "longest-palindromic-substring",
    problemTitle: "Longest Palindromic Substring",
    sourceUrl: "https://leetcode.com/problems/longest-palindromic-substring/editorial/",
    difficulty: "Medium",
    tags: ["Two Pointers", "String", "Dynamic Programming"],
    approaches: [
      {
        name: "Expand Around Center",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Best practical approach - optimal space",
        whenToUse: "Preferred for interviews",
        codePattern: "Try each center (odd and even), expand outward",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Dynamic Programming",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(n^2)",
        tradeOff: "Same time, more space, but shows DP skills",
        whenToUse: "When DP approach is requested",
        codePattern: "dp[i][j] = true if s[i:j] is palindrome",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
      {
        name: "Manacher's Algorithm",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal time but complex to implement",
        whenToUse: "When O(n) is strictly required",
        codePattern: "Transform string, use palindrome symmetry",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Forgetting to check both odd and even length palindromes",
      "Not tracking actual substring (just length)",
      "DP table fill order wrong",
    ],
    keyOperations: [
      { operation: "Center expansion", complexity: "O(n) per center" },
      { operation: "n centers", complexity: "O(n) centers" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-coin-change",
    leetcodeNumber: 322,
    slug: "coin-change",
    problemTitle: "Coin Change",
    sourceUrl: "https://leetcode.com/problems/coin-change/",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Breadth-First Search"],
    approaches: [
      {
        name: "Bottom-Up DP",
        timeComplexity: "O(amount * n)",
        spaceComplexity: "O(amount)",
        tradeOff: "Standard unbounded knapsack approach",
        whenToUse: "Preferred approach for this problem",
        codePattern: "dp[i] = min coins to make amount i",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Top-Down with Memoization",
        timeComplexity: "O(amount * n)",
        spaceComplexity: "O(amount)",
        tradeOff: "Same complexity, recursive approach",
        whenToUse: "When top-down is more intuitive",
        codePattern: "Recursive with memo, try each coin",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "BFS",
        timeComplexity: "O(amount * n)",
        spaceComplexity: "O(amount)",
        tradeOff: "Alternative graph-based approach",
        whenToUse: "When thinking of it as shortest path",
        codePattern: "BFS from 0 to amount, edges are coins",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Greedy doesn't work (counterexample: coins [1,3,4], amount 6)",
      "Not initializing dp array to infinity",
      "Not handling impossible case (return -1)",
    ],
    keyOperations: [
      { operation: "DP state transition", complexity: "O(n) per amount" },
      { operation: "Fill dp array", complexity: "O(amount)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-word-break",
    leetcodeNumber: 139,
    slug: "word-break",
    problemTitle: "Word Break",
    sourceUrl: "https://leetcode.com/problems/word-break/editorial/",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "String", "Dynamic Programming", "Trie", "Memoization"],
    approaches: [
      {
        name: "Bottom-Up DP",
        timeComplexity: "O(n * m * k)",
        spaceComplexity: "O(n)",
        tradeOff: "Standard DP approach, k = avg word length",
        whenToUse: "Preferred approach",
        codePattern: "dp[i] = true if s[0:i] can be segmented",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Top-Down with Memoization",
        timeComplexity: "O(n * m * k)",
        spaceComplexity: "O(n)",
        tradeOff: "Same complexity, recursive thinking",
        whenToUse: "When recursion is clearer",
        codePattern: "Try each word at current position",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Trie Optimization",
        timeComplexity: "O(n^2 + m * k)",
        spaceComplexity: "O(n + m * k)",
        tradeOff: "Faster word lookup with trie",
        whenToUse: "When dictionary is large",
        codePattern: "Build trie from dictionary, DP with trie lookup",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Not using set for O(1) word lookup",
      "Wrong substring boundaries",
      "Not handling empty string correctly",
    ],
    keyOperations: [
      { operation: "Word lookup", complexity: "O(k) or O(1) with set" },
      { operation: "DP transitions", complexity: "O(n * m)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-longest-increasing-subseq",
    leetcodeNumber: 300,
    slug: "longest-increasing-subsequence",
    problemTitle: "Longest Increasing Subsequence",
    sourceUrl: "https://leetcode.com/problems/longest-increasing-subsequence/",
    difficulty: "Medium",
    tags: ["Array", "Binary Search", "Dynamic Programming"],
    approaches: [
      {
        name: "DP",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(n)",
        tradeOff: "Simple to understand and implement",
        whenToUse: "When O(n^2) is acceptable",
        codePattern: "dp[i] = max LIS ending at index i",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Binary Search (Patience Sorting)",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal time but trickier to understand",
        whenToUse: "When O(n log n) is required",
        codePattern: "Maintain sorted array, binary search for position",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Binary search approach doesn't give actual LIS, just length",
      "Wrong comparison (strictly increasing)",
      "Not initializing DP array to 1",
    ],
    keyOperations: [
      { operation: "DP inner loop", complexity: "O(n)" },
      { operation: "Binary search", complexity: "O(log n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // BACKTRACKING
  // ============================================
  {
    problemId: "dsa-subsets",
    leetcodeNumber: 78,
    slug: "subsets",
    problemTitle: "Subsets",
    sourceUrl: "https://leetcode.com/problems/subsets/editorial/",
    difficulty: "Medium",
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    approaches: [
      {
        name: "Backtracking",
        timeComplexity: "O(n * 2^n)",
        spaceComplexity: "O(n)",
        tradeOff: "Standard approach, space for recursion stack",
        whenToUse: "Most intuitive for subset generation",
        codePattern: "Include/exclude each element recursively",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Iterative (Cascading)",
        timeComplexity: "O(n * 2^n)",
        spaceComplexity: "O(n * 2^n)",
        tradeOff: "No recursion, but builds all subsets in memory",
        whenToUse: "When avoiding recursion",
        codePattern: "Start empty, add each element to all existing subsets",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
      {
        name: "Bit Manipulation",
        timeComplexity: "O(n * 2^n)",
        spaceComplexity: "O(n)",
        tradeOff: "Elegant but less intuitive",
        whenToUse: "When showing bit manipulation skills",
        codePattern: "Each number 0 to 2^n-1 represents a subset",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Not understanding 2^n subsets exist",
      "Missing empty subset",
      "Modifying list while iterating",
    ],
    keyOperations: [
      { operation: "Generate each subset", complexity: "O(n) to copy" },
      { operation: "Total subsets", complexity: "O(2^n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-combination-sum",
    leetcodeNumber: 39,
    slug: "combination-sum",
    problemTitle: "Combination Sum",
    sourceUrl: "https://leetcode.com/problems/combination-sum/",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    approaches: [
      {
        name: "Backtracking",
        timeComplexity: "O(n^(target/min))",
        spaceComplexity: "O(target/min)",
        tradeOff: "Standard backtracking, depth depends on target",
        whenToUse: "Classic approach for this type of problem",
        codePattern: "Try each candidate, recurse with reduced target",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Generating duplicates by not using start index",
      "Not sorting candidates first (optional optimization)",
      "Wrong base case (target == 0 vs target < 0)",
    ],
    keyOperations: [
      { operation: "Backtracking recursion", complexity: "exponential in worst case" },
      { operation: "Path copy for result", complexity: "O(k) where k is path length" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-permutations",
    leetcodeNumber: 46,
    slug: "permutations",
    problemTitle: "Permutations",
    sourceUrl: "https://leetcode.com/problems/permutations/",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    approaches: [
      {
        name: "Backtracking with Visited Set",
        timeComplexity: "O(n * n!)",
        spaceComplexity: "O(n)",
        tradeOff: "Standard approach using visited tracking",
        whenToUse: "Clear and easy to understand",
        codePattern: "Try each unused element at each position",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Backtracking with Swap",
        timeComplexity: "O(n * n!)",
        spaceComplexity: "O(n)",
        tradeOff: "In-place but harder to understand",
        whenToUse: "When minimizing space usage",
        codePattern: "Swap elements into position, recurse, swap back",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not backtracking (forgetting to undo changes)",
      "Using wrong termination condition",
      "Not understanding n! permutations exist",
    ],
    keyOperations: [
      { operation: "Generate each permutation", complexity: "O(n)" },
      { operation: "Total permutations", complexity: "O(n!)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // GRAPHS
  // ============================================
  {
    problemId: "dsa-number-of-islands",
    leetcodeNumber: 200,
    slug: "number-of-islands",
    problemTitle: "Number of Islands",
    sourceUrl: "https://leetcode.com/problems/number-of-islands/",
    difficulty: "Medium",
    tags: ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"],
    approaches: [
      {
        name: "DFS",
        timeComplexity: "O(m * n)",
        spaceComplexity: "O(m * n)",
        tradeOff: "Simple, stack space for recursion in worst case",
        whenToUse: "Most common approach",
        codePattern: "For each land cell, DFS to mark connected component",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "BFS",
        timeComplexity: "O(m * n)",
        spaceComplexity: "O(min(m, n))",
        tradeOff: "Better space in practice (queue width-bounded)",
        whenToUse: "When avoiding deep recursion",
        codePattern: "For each land cell, BFS to mark connected component",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Union Find",
        timeComplexity: "O(m * n * α(m * n))",
        spaceComplexity: "O(m * n)",
        tradeOff: "Good for dynamic updates, but overkill here",
        whenToUse: "When practicing Union Find",
        codePattern: "Union adjacent land cells, count components",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not marking visited cells (infinite loop)",
      "Checking bounds incorrectly",
      "Counting water cells instead of land",
    ],
    keyOperations: [
      { operation: "DFS/BFS per cell", complexity: "O(1) amortized" },
      { operation: "Total cells", complexity: "O(m * n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  {
    problemId: "dsa-course-schedule",
    leetcodeNumber: 207,
    slug: "course-schedule",
    problemTitle: "Course Schedule",
    sourceUrl: "https://leetcode.com/problems/course-schedule/",
    difficulty: "Medium",
    tags: ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
    approaches: [
      {
        name: "Topological Sort (Kahn's BFS)",
        timeComplexity: "O(V + E)",
        spaceComplexity: "O(V + E)",
        tradeOff: "Iterative, builds topological order",
        whenToUse: "When you need the ordering too",
        codePattern: "Track indegrees, process zero-indegree nodes",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "DFS Cycle Detection",
        timeComplexity: "O(V + E)",
        spaceComplexity: "O(V + E)",
        tradeOff: "Recursive, detects cycle directly",
        whenToUse: "When only checking for cycle",
        codePattern: "Track visiting/visited states, cycle if visiting twice",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Using only visited (need visiting state for cycle detection)",
      "Building graph wrong (prerequisite direction)",
      "Not handling disconnected components",
    ],
    keyOperations: [
      { operation: "Graph traversal", complexity: "O(V + E)" },
      { operation: "Cycle detection", complexity: "O(V + E)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // INTERVALS
  // ============================================
  {
    problemId: "dsa-merge-intervals",
    leetcodeNumber: 56,
    slug: "merge-intervals",
    problemTitle: "Merge Intervals",
    sourceUrl: "https://leetcode.com/problems/merge-intervals/editorial/",
    difficulty: "Medium",
    tags: ["Array", "Sorting"],
    approaches: [
      {
        name: "Sorting",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(log n)",
        tradeOff: "Optimal - sorting dominates",
        whenToUse: "Standard approach for interval merging",
        codePattern: "Sort by start, merge overlapping intervals",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Connected Components",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(n^2)",
        tradeOff: "Graph-based but slower",
        whenToUse: "Only for understanding",
        codePattern: "Build overlap graph, find connected components",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "leetcode-editorial",
      },
    ],
    commonMistakes: [
      "Not sorting first",
      "Wrong merge condition (should be end >= start, not >)",
      "Not updating end correctly (max of both ends)",
    ],
    keyOperations: [
      { operation: "Sorting", complexity: "O(n log n)" },
      { operation: "Merge pass", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-insert-interval",
    leetcodeNumber: 57,
    slug: "insert-interval",
    problemTitle: "Insert Interval",
    sourceUrl: "https://leetcode.com/problems/insert-interval/",
    difficulty: "Medium",
    tags: ["Array"],
    approaches: [
      {
        name: "Linear Scan",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Optimal - single pass through intervals",
        whenToUse: "Standard approach",
        codePattern: "Add non-overlapping before, merge overlapping, add rest",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
      {
        name: "Binary Search + Insert",
        timeComplexity: "O(n)",
        spaceComplexity: "O(n)",
        tradeOff: "Faster to find position but still O(n) for result",
        whenToUse: "When showing binary search skills",
        codePattern: "Binary search for insert position, then merge",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Merging when intervals only touch (depends on problem definition)",
      "Not handling empty input correctly",
      "Wrong merge logic",
    ],
    keyOperations: [
      { operation: "Interval comparison", complexity: "O(1)" },
      { operation: "Single pass", complexity: "O(n)" },
    ],
    verified: true,
    verifiedAt: "2026-01-13",
    verificationSource: "algorithm-textbook",
  },

  // ============================================
  // ROBLOX-SPECIFIC QUESTIONS (Research-based)
  // ============================================
  {
    problemId: "dsa-roman-to-integer",
    leetcodeNumber: 13,
    slug: "roman-to-integer",
    problemTitle: "Roman to Integer",
    sourceUrl: "https://leetcode.com/problems/roman-to-integer/",
    difficulty: "Easy",
    tags: ["Hash Table", "Math", "String"],
    approaches: [
      {
        name: "Left-to-Right with Lookahead",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple iteration comparing current with next character",
        whenToUse: "Standard approach - compare current vs next to decide add/subtract",
        codePattern: "If current < next, subtract; otherwise add",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Right-to-Left Scan",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Process from end, simpler logic for some",
        whenToUse: "Alternative approach - some find this more intuitive",
        codePattern: "Track previous value, add or subtract based on comparison",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Claiming O(n) when max input length is 15 (technically O(1) bounded)",
      "Not handling all six subtraction cases (IV, IX, XL, XC, CD, CM)",
      "Using excessive space for the symbol mapping (should be O(1) fixed 7 elements)",
    ],
    keyOperations: [
      { operation: "Hash map lookup", complexity: "O(1)", note: "Fixed 7 Roman numerals" },
      { operation: "String iteration", complexity: "O(n)", note: "Max 15 chars, so O(1) bounded" },
      { operation: "Comparison", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-14",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-maximum-units-on-truck",
    leetcodeNumber: 1710,
    slug: "maximum-units-on-a-truck",
    problemTitle: "Maximum Units on a Truck",
    sourceUrl: "https://leetcode.com/problems/maximum-units-on-a-truck/",
    difficulty: "Easy",
    tags: ["Array", "Greedy", "Sorting"],
    approaches: [
      {
        name: "Greedy with Sorting",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(1)",
        tradeOff: "Sort by units per box descending, greedily fill truck",
        whenToUse: "Standard optimal approach - always prioritize boxes with most units",
        codePattern:
          "Sort by unitsPerBox desc, iterate and take min(available, remaining capacity)",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Counting Sort (Constraint-based)",
        timeComplexity: "O(n + M)",
        spaceComplexity: "O(M)",
        tradeOff: "Faster when M (max units) is small - uses bucket counting",
        whenToUse: "When unitsPerBox is bounded (M=1000 in this problem)",
        codePattern: "Count boxes at each unit level, iterate from highest to lowest",
        isOptimalTime: true,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force (All Combinations)",
        timeComplexity: "O(2^n)",
        spaceComplexity: "O(n)",
        tradeOff: "Exponential - try all subsets of boxes",
        whenToUse: "Never in practice - only for understanding",
        codePattern: "Generate all subsets, check capacity, find max units",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Not sorting by units per box (must maximize value per slot)",
      "Taking more boxes than available for a type",
      "Forgetting to stop when truck is full",
      "Using O(n) space for sorting when in-place is possible",
    ],
    keyOperations: [
      { operation: "Sorting", complexity: "O(n log n)" },
      { operation: "Greedy selection loop", complexity: "O(n)" },
      { operation: "Box count comparison", complexity: "O(1)" },
    ],
    verified: true,
    verifiedAt: "2026-01-14",
    verificationSource: "leetcode-editorial",
  },

  {
    problemId: "dsa-maximum-subarray",
    leetcodeNumber: 53,
    slug: "maximum-subarray",
    problemTitle: "Maximum Subarray",
    sourceUrl: "https://leetcode.com/problems/maximum-subarray/",
    difficulty: "Medium",
    tags: ["Array", "Divide and Conquer", "Dynamic Programming"],
    approaches: [
      {
        name: "Kadane's Algorithm",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        tradeOff: "Optimal - single pass DP with constant space",
        whenToUse: "Always preferred - the standard optimal solution",
        codePattern: "Track currentMax and globalMax; currentMax = max(num, currentMax + num)",
        isOptimalTime: true,
        isOptimalSpace: true,
        source: "leetcode-editorial",
      },
      {
        name: "Divide and Conquer",
        timeComplexity: "O(n log n)",
        spaceComplexity: "O(log n)",
        tradeOff: "Slower but demonstrates D&C skills - asked as follow-up",
        whenToUse: "When interviewer explicitly asks for D&C or to show recursive thinking",
        codePattern: "Max of left half, right half, or crossing middle",
        isOptimalTime: false,
        isOptimalSpace: false,
        source: "algorithm-textbook",
      },
      {
        name: "Brute Force",
        timeComplexity: "O(n^2)",
        spaceComplexity: "O(1)",
        tradeOff: "Simple but slow - check all subarrays",
        whenToUse: "Only to explain progression to optimal solution",
        codePattern: "Two nested loops: for each start, extend to each end",
        isOptimalTime: false,
        isOptimalSpace: true,
        source: "algorithm-textbook",
      },
    ],
    commonMistakes: [
      "Claiming O(n log n) for Kadane's (it's O(n))",
      "Confusing Kadane's with D&C approach",
      "Not handling all-negative arrays correctly",
      "Returning 0 instead of the largest negative when no positive exists",
      "Not recognizing this as DP (currentMax at each index is a DP state)",
    ],
    keyOperations: [
      {
        operation: "Single element decision",
        complexity: "O(1)",
        note: "Extend or restart subarray",
      },
      { operation: "Array iteration", complexity: "O(n)" },
      { operation: "D&C: Finding crossing max", complexity: "O(n)", note: "Dominates recursion" },
    ],
    verified: true,
    verifiedAt: "2026-01-14",
    verificationSource: "leetcode-editorial",
  },
]

/**
 * Pattern-level complexity rules based on CS fundamentals
 * These provide general guidance for algorithm patterns
 */
export const PATTERN_COMPLEXITY_RULES: PatternComplexityRules[] = [
  {
    pattern: "arrays-hashing",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(n)",
    keyInsight: "Hash maps provide O(1) average lookup, trading space for time",
    source: "CLRS - Hash Tables",
    variations: [
      { name: "Counting elements", time: "O(n)", space: "O(k)", note: "k = unique elements" },
      {
        name: "Two Sum pattern",
        time: "O(n)",
        space: "O(n)",
        note: "Hash map for complement lookup",
      },
    ],
  },
  {
    pattern: "two-pointers",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(1)",
    keyInsight: "Two pointers traverse array once, often after sorting",
    source: "Standard algorithm technique",
    variations: [
      { name: "Sorted array search", time: "O(n)", space: "O(1)", note: "Converging pointers" },
      { name: "With sorting", time: "O(n log n)", space: "O(1)", note: "Sorting dominates" },
    ],
  },
  {
    pattern: "sliding-window",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(1) to O(k)",
    keyInsight: "Each element enters and exits window at most once - amortized O(1) per element",
    source: "Amortized analysis",
    variations: [
      { name: "Fixed size window", time: "O(n)", space: "O(k)", note: "k = window size" },
      {
        name: "Variable window",
        time: "O(n)",
        space: "O(charset)",
        note: "Expand right, shrink left",
      },
    ],
  },
  {
    pattern: "stack",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(n)",
    keyInsight: "Each element pushed and popped at most once",
    source: "Standard data structure",
    variations: [
      {
        name: "Monotonic stack",
        time: "O(n)",
        space: "O(n)",
        note: "Next greater/smaller element",
      },
      { name: "Balanced parentheses", time: "O(n)", space: "O(n)", note: "Match opening/closing" },
    ],
  },
  {
    pattern: "binary-search",
    typicalTimeComplexity: "O(log n)",
    typicalSpaceComplexity: "O(1) iterative, O(log n) recursive",
    keyInsight: "Search space halves each iteration: log₂(n) iterations",
    source: "CLRS - Divide and Conquer",
    variations: [
      { name: "Standard search", time: "O(log n)", space: "O(1)", note: "Sorted array" },
      {
        name: "Search on answer",
        time: "O(log k * f(n))",
        space: "varies",
        note: "Binary search + verification",
      },
    ],
  },
  {
    pattern: "linked-list",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(1)",
    keyInsight: "Single traversal with pointer manipulation",
    source: "Standard data structure",
    variations: [
      { name: "Reverse list", time: "O(n)", space: "O(1)", note: "Three pointers" },
      { name: "Cycle detection", time: "O(n)", space: "O(1)", note: "Floyd's algorithm" },
    ],
  },
  {
    pattern: "trees",
    typicalTimeComplexity: "O(n)",
    typicalSpaceComplexity: "O(h) where h is height",
    keyInsight: "Visit each node once, recursion depth = height",
    source: "CLRS - Binary Search Trees",
    variations: [
      { name: "Balanced tree", time: "O(n)", space: "O(log n)", note: "Height = log n" },
      { name: "Skewed tree", time: "O(n)", space: "O(n)", note: "Height = n (worst case)" },
    ],
  },
  {
    pattern: "heap",
    typicalTimeComplexity: "O(log n) per operation, O(n) to build",
    typicalSpaceComplexity: "O(n)",
    keyInsight: "Complete binary tree, heapify is O(log n)",
    source: "CLRS - Heapsort",
    variations: [
      {
        name: "Top k elements",
        time: "O(n log k)",
        space: "O(k)",
        note: "Maintain heap of size k",
      },
      { name: "Heap sort", time: "O(n log n)", space: "O(1)", note: "In-place sorting" },
    ],
  },
  {
    pattern: "graphs",
    typicalTimeComplexity: "O(V + E)",
    typicalSpaceComplexity: "O(V + E)",
    keyInsight: "Visit each vertex and edge once",
    source: "CLRS - Graph Algorithms",
    variations: [
      { name: "DFS/BFS", time: "O(V + E)", space: "O(V)", note: "Standard traversal" },
      { name: "Topological sort", time: "O(V + E)", space: "O(V)", note: "DAG ordering" },
    ],
  },
  {
    pattern: "dp-1d",
    typicalTimeComplexity: "O(states * transitions)",
    typicalSpaceComplexity: "O(states)",
    keyInsight: "Solve subproblems once, store results",
    source: "CLRS - Dynamic Programming",
    variations: [
      { name: "1D DP", time: "O(n)", space: "O(n) or O(1)", note: "Linear problems" },
      { name: "2D DP", time: "O(n*m)", space: "O(n*m) or O(n)", note: "Two-dimensional problems" },
    ],
  },
  {
    pattern: "backtracking",
    typicalTimeComplexity: "O(k^n) or O(n!)",
    typicalSpaceComplexity: "O(n)",
    keyInsight: "Exponential in nature - explores decision tree",
    source: "Standard algorithm technique",
    variations: [
      {
        name: "Subsets",
        time: "O(n * 2^n)",
        space: "O(n)",
        note: "2^n subsets, O(n) to copy each",
      },
      { name: "Permutations", time: "O(n * n!)", space: "O(n)", note: "n! permutations" },
    ],
  },
  {
    pattern: "greedy",
    typicalTimeComplexity: "O(n) or O(n log n)",
    typicalSpaceComplexity: "O(1)",
    keyInsight: "Local optimal choice leads to global optimal",
    source: "CLRS - Greedy Algorithms",
    variations: [
      { name: "Activity selection", time: "O(n log n)", space: "O(1)", note: "Sort then greedy" },
      { name: "Interval scheduling", time: "O(n log n)", space: "O(1)", note: "Sort by end time" },
    ],
  },
  {
    pattern: "intervals",
    typicalTimeComplexity: "O(n log n)",
    typicalSpaceComplexity: "O(n)",
    keyInsight: "Sort intervals first, then process",
    source: "Standard algorithm technique",
    variations: [
      { name: "Merge intervals", time: "O(n log n)", space: "O(n)", note: "Sort + merge" },
      { name: "Meeting rooms", time: "O(n log n)", space: "O(n)", note: "Sort + heap/sweep line" },
    ],
  },
  {
    pattern: "trie",
    typicalTimeComplexity: "O(m) per operation where m is word length",
    typicalSpaceComplexity: "O(total characters)",
    keyInsight: "Prefix-based lookup in O(word length)",
    source: "Standard data structure",
    variations: [
      { name: "Insert/Search", time: "O(m)", space: "O(1)", note: "m = word length" },
      { name: "Build trie", time: "O(n * m)", space: "O(n * m)", note: "n words, avg length m" },
    ],
  },
  {
    pattern: "bit-manipulation",
    typicalTimeComplexity: "O(n) or O(1)",
    typicalSpaceComplexity: "O(1)",
    keyInsight: "Bit operations are O(1), often replace hash sets",
    source: "Computer architecture fundamentals",
    variations: [
      { name: "Single number (XOR)", time: "O(n)", space: "O(1)", note: "XOR cancels pairs" },
      { name: "Count bits", time: "O(log n)", space: "O(1)", note: "Brian Kernighan's algorithm" },
    ],
  },
]

/**
 * Normalize a problem ID to match knowledge base format
 * Handles variations like:
 * - dsa-longest-consecutive-sequence -> dsa-longest-consecutive
 * - dsa-product-array-except-self -> dsa-product-except-self
 * - dsa-top-k-frequent-elements -> dsa-top-k-frequent
 */
function normalizeId(problemId: string): string[] {
  const variations: string[] = [problemId]

  // Common suffix patterns to try removing
  const suffixesToRemove = [
    "-sequence",
    "-elements",
    "-array",
    "-numbers",
    "-list",
    "-string",
    "-tree",
    "-graph",
  ]

  for (const suffix of suffixesToRemove) {
    if (problemId.endsWith(suffix)) {
      variations.push(problemId.slice(0, -suffix.length))
    }
  }

  // Handle compound removals (e.g., "-array-except" -> "-except")
  const compoundPatterns = [
    { from: "-array-except-self", to: "-except-self" },
    { from: "-binary-search-tree", to: "-bst" },
    { from: "-linked-list", to: "-list" },
    { from: "-without-repeating", to: "" },
  ]

  for (const { from, to } of compoundPatterns) {
    if (problemId.includes(from)) {
      variations.push(problemId.replace(from, to))
    }
  }

  return [...new Set(variations)]
}

/**
 * Get complexity knowledge for a specific problem
 * Uses fuzzy matching to handle ID variations between scenarios and knowledge base
 */
export function getComplexityKnowledge(problemId: string): ProblemComplexityKnowledge | undefined {
  // Try exact match first
  const exactMatch = PROBLEM_COMPLEXITY_DATA.find((p) => p.problemId === problemId)
  if (exactMatch) return exactMatch

  // Try normalized variations
  const variations = normalizeId(problemId)
  for (const variant of variations) {
    const match = PROBLEM_COMPLEXITY_DATA.find((p) => p.problemId === variant)
    if (match) return match
  }

  // Try slug-based matching as last resort
  const slug = problemId.replace("dsa-", "").toLowerCase()
  return PROBLEM_COMPLEXITY_DATA.find(
    (p) => p.slug && p.slug.toLowerCase().replace(/-/g, "") === slug.replace(/-/g, "")
  )
}

/**
 * Get complexity knowledge by LeetCode number
 */
export function getComplexityByLeetCode(
  leetcodeNumber: number
): ProblemComplexityKnowledge | undefined {
  return PROBLEM_COMPLEXITY_DATA.find((p) => p.leetcodeNumber === leetcodeNumber)
}

/**
 * Get pattern complexity rules
 */
export function getPatternComplexityRules(pattern: DSAPattern): PatternComplexityRules | undefined {
  return PATTERN_COMPLEXITY_RULES.find((r) => r.pattern === pattern)
}

/**
 * Check if complexity data exists for a problem
 */
export function hasComplexityData(problemId: string): boolean {
  return PROBLEM_COMPLEXITY_DATA.some((p) => p.problemId === problemId)
}

/**
 * Get all problems with complexity data
 */
export function getProblemsWithComplexityData(): string[] {
  return PROBLEM_COMPLEXITY_DATA.map((p) => p.problemId)
}
