/**
 * System Design Interview Scenarios
 * Type: system-design
 *
 * These scenarios test system design and architecture skills.
 */

import type { SystemDesignScenario } from '../types'

export const systemDesignScenarios: SystemDesignScenario[] = [
  {
    id: 'system-design-url-shortener',
    title: 'Design a URL Shortener',
    type: 'system-design',
    difficulty: 'easy',
    companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
    description: 'Design a scalable URL shortening service like bit.ly or tinyurl.com',
    tags: ['system-design', 'scalability', 'distributed-systems', 'hashing'],
    estimatedTime: 45,
    problemStatement: `Design a URL shortening service that converts long URLs into short, shareable links. Users should be able to create short URLs, and when someone visits a short URL, they should be redirected to the original URL.

The service should handle millions of URL shortenings per day and billions of redirections per month. Consider how you would design the system to be scalable, reliable, and performant.`,
    functionalRequirements: [
      'Users can submit a long URL and get back a shortened URL',
      'When users visit a short URL, they are redirected to the original long URL',
      'Short URLs should be as short as possible (ideally 6-8 characters)',
      'Users should optionally be able to customize their short URL',
      'Short URLs should never expire (or have a configurable expiration)',
      'Analytics: track how many times each short URL has been clicked',
    ],
    nonFunctionalRequirements: [
      'System should be highly available (99.9% uptime)',
      'Redirection should happen with minimal latency (< 100ms)',
      'System should be scalable to handle millions of requests',
      'Short URLs should be unique and not guessable',
      'Service should be resilient to failures',
    ],
    constraints: [
      'Expected 100M new URLs per month',
      'Expected 10B redirections per month',
      'Data should be stored for at least 5 years',
      'Read:Write ratio is 100:1',
      'Traffic is not evenly distributed (some URLs are very popular)',
    ],
    keyComponents: [
      'API Gateway / Load Balancer',
      'Application Servers',
      'Database (SQL or NoSQL)',
      'Cache Layer (Redis/Memcached)',
      'Short URL Generation Service',
      'Analytics Service',
      'Monitoring & Logging',
    ],
    hints: [
      'Start with defining the API endpoints: POST /shorten and GET /{shortUrl}',
      'Consider using a hash function (MD5, Base62) for generating short URLs',
      'Think about how to handle collisions when generating short URLs',
      'A cache layer can significantly reduce database reads for popular URLs',
      'Consider using a NoSQL database for better horizontal scalability',
      'Pre-generate a pool of unique short codes for better performance',
      'Use consistent hashing for distributing cache across multiple servers',
    ],
    evaluationCriteria: [
      {
        category: 'Requirements Gathering',
        description: 'Clarified functional and non-functional requirements',
        weight: 15,
      },
      {
        category: 'High-Level Architecture',
        description: 'Proposed clear architecture with major components',
        weight: 25,
      },
      {
        category: 'Data Model',
        description: 'Designed appropriate database schema',
        weight: 15,
      },
      {
        category: 'API Design',
        description: 'Defined clean and RESTful API endpoints',
        weight: 10,
      },
      {
        category: 'Scalability',
        description: 'Addressed scaling concerns (caching, sharding, CDN)',
        weight: 20,
      },
      {
        category: 'Trade-offs',
        description: 'Discussed trade-offs and alternative approaches',
        weight: 15,
      },
    ],
    exampleSolution: {
      overview: 'A distributed URL shortening service using Base62 encoding for short code generation, Redis for caching popular URLs, and a NoSQL database for persistent storage. The system uses consistent hashing for cache distribution and database sharding for horizontal scalability.',
      architecture: [
        'Load Balancer: Distributes incoming requests across multiple app servers',
        'Application Servers: Stateless servers handling URL creation and redirection',
        'Redis Cache Cluster: Caches popular URLs to reduce database load',
        'Database Cluster: Sharded NoSQL database (Cassandra/DynamoDB) for URL mappings',
        'Analytics Service: Async service for tracking click events',
        'Short Code Generator: Pre-generates unique short codes using Base62',
      ],
      dataModel: [
        'URL Table: { shortCode (PK), longUrl, createdAt, expiresAt, userId, clicks }',
        'Analytics Table: { shortCode, timestamp, userAgent, ipAddress, location }',
        'User Table: { userId, email, createdAt, tier }',
        'Index on shortCode for O(1) lookups',
        'Sharding key: hash(shortCode) for distributing data',
      ],
      apiDesign: [
        'POST /api/v1/shorten - Body: { longUrl, customAlias?, userId? } - Returns: { shortUrl, shortCode }',
        'GET /{shortCode} - Redirects to long URL (302 redirect)',
        'GET /api/v1/analytics/{shortCode} - Returns click statistics',
        'DELETE /api/v1/{shortCode} - Deletes a short URL',
      ],
      scalability: [
        'Horizontal scaling: Add more app servers behind load balancer',
        'Database sharding: Partition data by hash(shortCode) across multiple DB nodes',
        'Caching: Cache popular URLs in Redis (80-20 rule: 20% URLs get 80% traffic)',
        'CDN: Serve static content and potentially cache redirects geographically',
        'Rate limiting: Prevent abuse by limiting requests per user/IP',
        'Async analytics: Use message queue (Kafka) to handle click tracking asynchronously',
      ],
      tradeoffs: [
        'Short code generation: Random generation vs Counter-based vs Hash-based',
        'Database choice: SQL (ACID guarantees) vs NoSQL (better scalability)',
        'Cache eviction: LRU vs LFU vs TTL-based',
        'Redirect type: 301 (permanent, cached by browsers) vs 302 (temporary, always hits server)',
        'Custom aliases: Allow customization but need to handle conflicts',
        'Analytics granularity: Real-time vs batch processing',
      ],
    },
    discussionPoints: [
      'How would you generate unique short codes? What are the pros/cons of different approaches?',
      'How would you handle a short URL that goes viral and gets millions of requests?',
      'What happens if the database goes down? How do you ensure availability?',
      'How would you prevent abuse (e.g., someone creating millions of short URLs)?',
      'How would you implement custom aliases while ensuring uniqueness?',
      'What metrics would you track to monitor system health?',
      'How would you handle URL expiration and cleanup?',
      'What security concerns should you address (malicious URLs, DDoS)?',
    ],
  },
  {
    id: 'system-design-rate-limiter',
    title: 'Design a Rate Limiter',
    type: 'system-design',
    difficulty: 'medium',
    companies: ['Google', 'Amazon', 'Stripe', 'Shopify'],
    description: 'Design a distributed rate limiting system to prevent API abuse',
    tags: ['system-design', 'distributed-systems', 'algorithms', 'redis'],
    estimatedTime: 45,
    problemStatement: `Design a rate limiting system that can be used to limit the number of requests a user can make to an API within a given time window. The system should work in a distributed environment with multiple API servers.

Consider different rate limiting algorithms, how to handle distributed state, and how to make the system efficient and fault-tolerant.`,
    functionalRequirements: [
      'Limit requests per user/IP/API key within a time window',
      'Support multiple rate limit rules (e.g., 100 req/min, 1000 req/hour)',
      'Return meaningful error messages when rate limit is exceeded',
      'Support different rate limits for different user tiers (free, premium)',
      'Provide APIs to check remaining quota',
      'Allow temporary rate limit overrides for specific users',
    ],
    nonFunctionalRequirements: [
      'Low latency: Rate limit check should add < 5ms overhead',
      'High availability: Should work even if some nodes fail',
      'Accurate: Should not allow significantly more requests than the limit',
      'Scalable: Handle millions of requests per second',
      'Distributed: Work across multiple API servers',
    ],
    constraints: [
      'System serves 10,000 API servers',
      'Need to support 1 million unique users',
      'Rate limit decisions must be made in < 10ms',
      'System should handle server failures gracefully',
    ],
    keyComponents: [
      'Rate Limiter Service',
      'Distributed Cache (Redis Cluster)',
      'API Gateway',
      'Configuration Service',
      'Monitoring & Alerting',
    ],
    hints: [
      'Consider different algorithms: Token Bucket, Leaky Bucket, Fixed Window, Sliding Window',
      'Redis is commonly used for distributed rate limiting due to atomic operations',
      'Use Redis INCR and EXPIRE commands with Lua scripts for atomicity',
      'Sliding window log provides accuracy but uses more memory',
      'Consider hybrid approaches for better trade-offs',
      'Cache rate limit rules locally to reduce latency',
      'Handle Redis failures gracefully (fail-open vs fail-closed)',
    ],
    evaluationCriteria: [
      {
        category: 'Algorithm Selection',
        description: 'Chose appropriate rate limiting algorithm(s) and explained trade-offs',
        weight: 25,
      },
      {
        category: 'Distributed Design',
        description: 'Addressed challenges of distributed rate limiting',
        weight: 25,
      },
      {
        category: 'Performance',
        description: 'Optimized for low latency and high throughput',
        weight: 20,
      },
      {
        category: 'Fault Tolerance',
        description: 'Handled failures and edge cases',
        weight: 15,
      },
      {
        category: 'Scalability',
        description: 'System can scale to handle increasing load',
        weight: 15,
      },
    ],
    exampleSolution: {
      overview: 'A distributed rate limiter using Redis cluster with Sliding Window Counter algorithm. The system uses Lua scripts for atomic operations, local caching for rules, and graceful degradation on Redis failures.',
      architecture: [
        'API Gateway: Intercepts all requests and invokes rate limiter',
        'Rate Limiter Service: Embedded in each API server for low latency',
        'Redis Cluster: Stores rate limit counters with sharding for scalability',
        'Config Service: Manages rate limit rules and user tiers',
        'Monitoring: Tracks rate limit violations and system health',
      ],
      dataModel: [
        'Redis Key Pattern: "rate_limit:{userId}:{window_timestamp}" -> counter',
        'Redis TTL: Set to window duration for automatic cleanup',
        'Config Store: { userId/tier -> { limit, windowSize, burstAllowed } }',
        'Example: "rate_limit:user123:1699999800" -> 45 (45 requests in current minute)',
      ],
      apiDesign: [
        'POST /api/check-rate-limit - Body: { userId, resource } - Returns: { allowed: boolean, remaining: number, resetAt: timestamp }',
        'GET /api/rate-limit-status/{userId} - Returns current quota status',
        'POST /api/admin/set-rate-limit - Body: { userId, limit, windowSize } - Admin API to configure limits',
      ],
      scalability: [
        'Redis Cluster: Shard data by userId hash across multiple Redis nodes',
        'Local cache: Cache rate limit rules in-memory to avoid config service calls',
        'Stateless rate limiter: Each API server can check rate limits independently',
        'Batch processing: Use pipelines for multiple rate limit checks',
        'Read replicas: Use Redis replicas for read-heavy workloads',
      ],
      tradeoffs: [
        'Fixed Window: Simple but has burst problem at window boundaries',
        'Sliding Window Log: Accurate but memory-intensive (stores all timestamps)',
        'Sliding Window Counter: Good balance of accuracy and memory efficiency',
        'Token Bucket: Allows controlled bursts, more complex to implement',
        'Fail-open vs Fail-closed: When Redis is down, allow all requests or block all?',
        'Consistency vs Availability: Strict rate limiting vs some over-limit allowance',
      ],
    },
    discussionPoints: [
      'What are the pros and cons of different rate limiting algorithms?',
      'How do you handle clock synchronization issues in a distributed system?',
      'What happens when Redis goes down? How do you ensure availability?',
      'How would you implement different rate limits for different API endpoints?',
      'How would you handle rate limiting for a single user with multiple devices?',
      'How would you implement gradual backoff vs hard limits?',
      'What metrics would you monitor to detect attacks or system issues?',
      'How would you implement IP-based rate limiting vs user-based?',
    ],
  },
  {
    id: 'system-design-instagram',
    title: 'Design Instagram/Photo Sharing Service',
    type: 'system-design',
    difficulty: 'hard',
    companies: ['Meta', 'Google', 'Amazon', 'Netflix'],
    description: 'Design a photo sharing and social networking service like Instagram',
    tags: ['system-design', 'scalability', 'social-network', 'distributed-systems', 'cdn'],
    estimatedTime: 60,
    problemStatement: `Design a photo-sharing social networking service like Instagram. Users should be able to upload photos, follow other users, like and comment on photos, and see a feed of photos from people they follow.

The system should handle hundreds of millions of users and billions of photos. Consider how you would store and serve images efficiently, generate personalized feeds, and handle the massive scale of social interactions.`,
    functionalRequirements: [
      'Users can upload photos with captions and hashtags',
      'Users can follow/unfollow other users',
      'Users can like and comment on photos',
      'Users see a personalized feed of photos from people they follow',
      'Users can search for photos by hashtags or users',
      'Users can view their own profile and others\' profiles',
      'Support stories (photos that disappear after 24 hours)',
      'Send notifications for likes, comments, follows',
    ],
    nonFunctionalRequirements: [
      'System should support 500M daily active users',
      'Low latency: Feed should load in < 2 seconds',
      'High availability: 99.99% uptime',
      'Photos should be uploaded and available quickly',
      'System should be globally distributed',
      'Handle viral posts (photos that get millions of likes)',
    ],
    constraints: [
      '200M photos uploaded per day',
      'Average photo size: 2MB',
      'Average user follows 200 people',
      'Average user has 100 followers',
      'Read:Write ratio is 100:1',
      'Need to store photos for 10+ years',
    ],
    keyComponents: [
      'API Gateway / Load Balancer',
      'Application Servers',
      'Image Upload Service',
      'Image Storage (S3/Blob Storage)',
      'CDN for image delivery',
      'Databases (User, Posts, Relationships)',
      'Feed Generation Service',
      'Search Service',
      'Notification Service',
      'Cache Layer',
    ],
    hints: [
      'Separate image storage from metadata storage',
      'Use object storage (S3) and CDN for serving images globally',
      'Pre-generate feeds asynchronously rather than on-demand',
      'Use graph database or adjacency list for follow relationships',
      'Consider sharding strategies: by userId, by geography',
      'Use message queues for async tasks (notifications, feed updates)',
      'Cache user feeds, popular posts, and user profiles',
      'Consider using a ranking algorithm for feed ordering (chronological vs engagement-based)',
    ],
    evaluationCriteria: [
      {
        category: 'Requirements & Scope',
        description: 'Properly scoped the problem and clarified requirements',
        weight: 10,
      },
      {
        category: 'High-Level Architecture',
        description: 'Designed comprehensive architecture with all major components',
        weight: 25,
      },
      {
        category: 'Data Model & Storage',
        description: 'Designed scalable data model for users, posts, relationships',
        weight: 20,
      },
      {
        category: 'Scalability & Performance',
        description: 'Addressed scalability challenges (sharding, caching, CDN)',
        weight: 25,
      },
      {
        category: 'Trade-offs & Deep Dives',
        description: 'Discussed trade-offs and deep-dived into complex areas',
        weight: 20,
      },
    ],
    exampleSolution: {
      overview: 'A distributed photo-sharing platform using microservices architecture. Images are stored in S3 and served via CDN. User metadata and relationships are stored in sharded databases. Feeds are pre-generated asynchronously and cached. The system uses Kafka for event streaming and async processing.',
      architecture: [
        'Client Apps: iOS, Android, Web',
        'CDN: CloudFront/Cloudflare for serving images globally',
        'Load Balancer: Distributes traffic across API servers',
        'API Gateway: Rate limiting, authentication, routing',
        'Microservices: Upload Service, Feed Service, User Service, Search Service, Notification Service',
        'Message Queue: Kafka for async event processing',
        'Cache Layer: Redis for feeds, user data, popular posts',
        'Databases: PostgreSQL (sharded) for metadata, Cassandra for feeds',
        'Object Storage: S3 for original and processed images',
        'Search: Elasticsearch for hashtag and user search',
      ],
      dataModel: [
        'Users: { userId (PK), username, email, profilePicUrl, bio, followerCount, followingCount, createdAt }',
        'Posts: { postId (PK), userId, imageUrl, caption, hashtags[], createdAt, likeCount, commentCount }',
        'Follows: { followerId, followeeId, createdAt } - Composite PK',
        'Likes: { postId, userId, createdAt } - Composite PK',
        'Comments: { commentId (PK), postId, userId, text, createdAt }',
        'Feed: { userId, postId, score, createdAt } - Pre-computed feeds',
        'Sharding: Shard Users and Posts by userId hash',
        'Indexes: On userId, postId, hashtags, createdAt',
      ],
      apiDesign: [
        'POST /api/v1/posts - Upload photo: { image, caption, hashtags }',
        'GET /api/v1/feed - Get personalized feed: { cursor, limit }',
        'POST /api/v1/posts/{postId}/like - Like a post',
        'POST /api/v1/posts/{postId}/comments - Comment: { text }',
        'POST /api/v1/users/{userId}/follow - Follow a user',
        'GET /api/v1/users/{userId} - Get user profile',
        'GET /api/v1/search?q={query}&type={users|hashtags} - Search',
      ],
      scalability: [
        'Image Upload: Client uploads directly to S3 via pre-signed URLs, reducing server load',
        'Image Processing: Async workers resize images to multiple sizes (thumbnail, medium, full)',
        'Feed Generation: Fanout-on-write for users with few followers, fanout-on-read for celebrities',
        'Database Sharding: Shard by userId for data locality',
        'Cache Strategy: Cache user feeds (Redis), popular posts, user profiles',
        'CDN: Serve images from edge locations for low latency globally',
        'Read Replicas: Multiple DB replicas for read-heavy operations',
        'Async Processing: Use Kafka for feed updates, notifications, analytics',
      ],
      tradeoffs: [
        'Fanout-on-write vs Fanout-on-read: Pre-generate feeds vs generate on-demand',
        'SQL vs NoSQL: PostgreSQL for complex queries vs Cassandra for write-heavy workloads',
        'Chronological vs Ranked feed: Simple timeline vs engagement-based ranking',
        'Normalization: Store like count in Posts table (denormalized) for performance',
        'Consistency: Eventual consistency for like counts vs strong consistency',
        'Celebrity problem: Special handling for users with millions of followers',
      ],
    },
    discussionPoints: [
      'How would you handle a celebrity with 100M followers posting a photo?',
      'How would you generate and rank the personalized feed?',
      'How would you implement the search functionality for hashtags and users?',
      'How would you ensure high availability during region failures?',
      'How would you handle image storage and delivery efficiently?',
      'What metrics would you track to monitor system health and user engagement?',
      'How would you implement stories (disappearing content)?',
      'How would you prevent spam and abusive content?',
      'How would you handle GDPR and user data deletion requests?',
    ],
  },
  {
    id: 'system-design-distributed-cache',
    title: 'Design a Distributed Cache',
    type: 'system-design',
    difficulty: 'medium',
    companies: ['Google', 'Amazon', 'Meta', 'Netflix', 'Microsoft'],
    description: 'Design a distributed caching system like Redis or Memcached',
    tags: ['system-design', 'distributed-systems', 'caching', 'performance'],
    estimatedTime: 45,
    problemStatement: `Design a distributed in-memory caching system similar to Redis or Memcached. The system should allow applications to store and retrieve key-value pairs with very low latency.

Consider how you would distribute data across multiple cache servers, handle server failures, and ensure high performance and availability.`,
    functionalRequirements: [
      'Store and retrieve key-value pairs (strings, integers, objects)',
      'Support TTL (time-to-live) for automatic expiration',
      'Support eviction policies (LRU, LFU, FIFO)',
      'Atomic operations: increment, decrement, compare-and-swap',
      'Support for data structures: lists, sets, sorted sets, hashes',
      'Provide APIs: GET, SET, DELETE, EXISTS, EXPIRE',
    ],
    nonFunctionalRequirements: [
      'Low latency: < 1ms for read/write operations',
      'High throughput: millions of operations per second',
      'High availability: tolerate node failures',
      'Scalability: easily add/remove cache nodes',
      'Consistency: handle concurrent updates correctly',
    ],
    constraints: [
      'Support up to 100 cache nodes in a cluster',
      'Each node can store up to 100GB of data',
      'Network latency between nodes: 1-5ms',
      'Client applications can send millions of requests per second',
    ],
    keyComponents: [
      'Cache Client Library',
      'Cache Servers (Nodes)',
      'Consistent Hashing Ring',
      'Replication Manager',
      'Cluster Manager',
      'Monitoring & Health Checks',
    ],
    hints: [
      'Use consistent hashing to distribute keys across cache nodes',
      'Consistent hashing minimizes data movement when nodes are added/removed',
      'Consider replication for high availability (master-slave or multi-master)',
      'Use virtual nodes to balance load more evenly',
      'Implement client-side caching for frequently accessed keys',
      'Use write-through or write-behind strategies for persistence',
      'Handle network partitions with quorum-based reads/writes',
    ],
    evaluationCriteria: [
      {
        category: 'Core Functionality',
        description: 'Designed basic cache operations and data structures',
        weight: 20,
      },
      {
        category: 'Distribution Strategy',
        description: 'Chose appropriate data distribution mechanism (consistent hashing)',
        weight: 25,
      },
      {
        category: 'High Availability',
        description: 'Addressed replication and failure handling',
        weight: 20,
      },
      {
        category: 'Performance',
        description: 'Optimized for low latency and high throughput',
        weight: 20,
      },
      {
        category: 'Trade-offs',
        description: 'Discussed CAP theorem and consistency trade-offs',
        weight: 15,
      },
    ],
    exampleSolution: {
      overview: 'A distributed cache using consistent hashing for data distribution, master-slave replication for availability, and client-side sharding for performance. The system uses virtual nodes for balanced load distribution and supports automatic failover.',
      architecture: [
        'Cache Clients: Smart clients with embedded hashing logic',
        'Cache Nodes: Multiple cache servers forming a cluster',
        'Consistent Hash Ring: Virtual ring for key distribution',
        'Replication: Each key replicated to N nodes (typically 3)',
        'Cluster Manager: Monitors node health and manages cluster membership',
        'Configuration Service: Stores cluster topology (ZooKeeper/etcd)',
      ],
      dataModel: [
        'In-Memory Hash Table: { key -> value, ttl, lastAccessed }',
        'LRU List: Doubly linked list for eviction policy',
        'Expiration Heap: Min-heap ordered by expiration time',
        'Key Format: string keys, values can be strings, integers, serialized objects',
        'Metadata: Each entry stores size, creation time, access count',
      ],
      apiDesign: [
        'GET key - Retrieve value for key - Returns: value or null',
        'SET key value [EX seconds] - Store key-value with optional TTL',
        'DELETE key - Remove key from cache',
        'EXISTS key - Check if key exists - Returns: boolean',
        'INCR key - Atomically increment integer value',
        'EXPIRE key seconds - Set TTL on existing key',
        'TTL key - Get remaining TTL - Returns: seconds or -1',
      ],
      scalability: [
        'Consistent Hashing: Use hash(key) % ring_size to determine node',
        'Virtual Nodes: Each physical node gets 100-200 virtual nodes for even distribution',
        'Client-Side Sharding: Clients calculate target node, reducing server load',
        'Horizontal Scaling: Add nodes to ring; only 1/N keys need to be redistributed',
        'Connection Pooling: Maintain persistent connections to cache nodes',
        'Pipelining: Batch multiple operations in a single network round trip',
      ],
      tradeoffs: [
        'Consistency vs Availability: CAP theorem - choose AP over CP for caching',
        'Replication: More replicas = higher availability but more memory usage',
        'Eviction Policy: LRU (recency) vs LFU (frequency) vs TTL-based',
        'Write Strategy: Write-through (slower writes, consistent) vs write-behind (faster, risk of data loss)',
        'Data Persistence: In-memory only vs periodic snapshots vs AOF log',
        'Hashing: Simple modulo (simple but poor scaling) vs consistent hashing (complex but better scaling)',
      ],
    },
    discussionPoints: [
      'How does consistent hashing work and why is it better than simple modulo hashing?',
      'What happens when a cache node fails? How do you ensure availability?',
      'How would you handle the thundering herd problem (many clients requesting same expired key)?',
      'How would you implement cache warming (pre-populating cache)?',
      'What eviction policy would you use and why?',
      'How would you handle large objects that don\'t fit in memory?',
      'How would you monitor cache hit rate and optimize it?',
      'How would you handle network partitions in the cluster?',
    ],
  },
  {
    id: 'system-design-chat-system',
    title: 'Design a Real-time Chat System',
    type: 'system-design',
    difficulty: 'medium',
    companies: ['Meta', 'Google', 'Slack', 'Microsoft'],
    description: 'Design a real-time messaging system like WhatsApp or Slack',
    tags: ['system-design', 'real-time', 'websockets', 'distributed-systems', 'messaging'],
    estimatedTime: 50,
    problemStatement: `Design a real-time chat messaging system that supports one-on-one conversations and group chats. Users should be able to send text messages, images, and files. Messages should be delivered in real-time with support for read receipts and online status.

The system should handle millions of concurrent users and ensure messages are delivered reliably even when users are offline.`,
    functionalRequirements: [
      'Users can send and receive text messages in real-time',
      'Support one-on-one and group chats (up to 256 members)',
      'Send images, videos, and files',
      'Show online/offline status of users',
      'Show read receipts (delivered, read)',
      'Show typing indicators',
      'Store message history',
      'Support message search',
      'Send notifications for new messages when user is offline',
    ],
    nonFunctionalRequirements: [
      'Real-time: Messages delivered within 1 second',
      'Highly available: 99.99% uptime',
      'Support 100M daily active users',
      'Support 1M concurrent WebSocket connections per server',
      'Messages should be persisted and never lost',
      'End-to-end encryption for privacy',
    ],
    constraints: [
      '50M messages sent per day',
      'Average message size: 100 bytes (text) to 10MB (files)',
      'Users can be part of up to 100 group chats',
      'Message history stored for 1 year',
      'Global user base across multiple regions',
    ],
    keyComponents: [
      'WebSocket Servers (for real-time connections)',
      'API Gateway / Load Balancer',
      'Chat Service',
      'Message Queue (Kafka/RabbitMQ)',
      'Database (Message Storage)',
      'Presence Service (online/offline status)',
      'Notification Service',
      'Media Storage (S3)',
      'CDN',
    ],
    hints: [
      'Use WebSockets for bidirectional real-time communication',
      'Store messages in a database partitioned by conversation ID',
      'Use message queues to handle message delivery and retries',
      'Maintain user-to-server mapping for routing messages',
      'Consider using Cassandra or similar for message storage (write-heavy)',
      'Use Redis for presence tracking and online status',
      'Implement message acknowledgments to ensure delivery',
      'Use CDN and object storage for media files',
    ],
    evaluationCriteria: [
      {
        category: 'Real-time Architecture',
        description: 'Designed proper WebSocket-based architecture for real-time messaging',
        weight: 25,
      },
      {
        category: 'Message Delivery',
        description: 'Ensured reliable message delivery and ordering',
        weight: 20,
      },
      {
        category: 'Scalability',
        description: 'System can scale to millions of concurrent connections',
        weight: 20,
      },
      {
        category: 'Data Storage',
        description: 'Designed efficient storage for messages and media',
        weight: 15,
      },
      {
        category: 'Additional Features',
        description: 'Covered presence, notifications, encryption',
        weight: 20,
      },
    ],
    exampleSolution: {
      overview: 'A distributed real-time chat system using WebSocket servers for persistent connections, Kafka for message routing, Cassandra for message storage, and Redis for presence tracking. The system uses consistent hashing to route users to servers and supports horizontal scaling.',
      architecture: [
        'Client Apps: Mobile and web clients with WebSocket connections',
        'Load Balancer: Routes WebSocket connections to chat servers',
        'WebSocket Servers: Maintain persistent connections with users',
        'Message Router: Routes messages to appropriate WebSocket servers',
        'Message Queue (Kafka): Ensures reliable message delivery',
        'Chat Service: Business logic for sending/receiving messages',
        'Database (Cassandra): Stores message history',
        'Presence Service (Redis): Tracks user online/offline status',
        'Notification Service: Sends push notifications for offline users',
        'Object Storage (S3): Stores images, videos, files',
      ],
      dataModel: [
        'Messages: { messageId (PK), conversationId, senderId, receiverId, content, timestamp, status, type }',
        'Conversations: { conversationId (PK), participantIds[], type, createdAt, lastMessageAt }',
        'Users: { userId (PK), username, lastSeen, publicKey }',
        'Presence: Redis - { userId -> { status, lastSeen, connectedServerId } }',
        'UserConnections: { userId -> WebSocketServerId } - for message routing',
        'Partition by conversationId for message queries',
      ],
      apiDesign: [
        'WebSocket Events: onConnect, onMessage, onTyping, onReadReceipt, onDisconnect',
        'POST /api/v1/messages - Send message: { conversationId, recipientIds, content, type }',
        'GET /api/v1/messages/{conversationId}?cursor={}&limit={} - Fetch message history',
        'POST /api/v1/conversations - Create group chat: { name, participantIds }',
        'GET /api/v1/conversations - List user\'s conversations',
        'PUT /api/v1/messages/{messageId}/read - Mark message as read',
        'GET /api/v1/users/{userId}/presence - Get online status',
      ],
      scalability: [
        'WebSocket Servers: Horizontal scaling - each server handles 1M connections',
        'Consistent Hashing: Route users to servers based on userId hash',
        'Message Queue: Use Kafka partitions for parallel message processing',
        'Database Sharding: Shard messages by conversationId for data locality',
        'Redis Cluster: Shard presence data by userId',
        'Read Replicas: For message history queries',
        'CDN: Serve media files globally for low latency',
        'Service Discovery: Use ZooKeeper/Consul for tracking server locations',
      ],
      tradeoffs: [
        'WebSockets vs Long Polling: WebSockets for low latency but requires persistent connections',
        'Message Ordering: Guaranteed ordering per conversation vs eventual consistency',
        'Presence Accuracy: Real-time presence vs periodic heartbeats (tradeoff between accuracy and load)',
        'Group Chat Fanout: Send to all members immediately vs batch delivery',
        'Database Choice: Cassandra (write-optimized) vs PostgreSQL (strong consistency)',
        'Encryption: End-to-end (more secure, complex) vs transport-level (simpler, less secure)',
      ],
    },
    discussionPoints: [
      'How would you ensure message ordering in a distributed system?',
      'What happens if a user is connected to multiple devices?',
      'How would you handle offline message delivery?',
      'How would you implement group chat with thousands of members?',
      'How would you scale WebSocket connections to millions of users?',
      'How would you implement end-to-end encryption?',
      'How would you handle message search efficiently?',
      'How would you detect and handle network failures?',
      'How would you implement message reactions and threading?',
    ],
  },
]

export default systemDesignScenarios
