import type { SystemDesignScenario } from "../types"

export const chatSystemScenario: SystemDesignScenario = {
  id: "system-design-chat-system",
  title: "Design a Real-time Chat System",
  type: "system-design",
  difficulty: "medium",
  companies: ["Meta", "Google", "Slack", "Microsoft"],
  description: "Design a real-time messaging system like WhatsApp or Slack",
  tags: ["system-design", "real-time", "websockets", "distributed-systems", "messaging"],
  estimatedTime: 50,
  problemStatement: `Design a real-time chat messaging system that supports one-on-one conversations and group chats. Users should be able to send text messages, images, and files. Messages should be delivered in real-time with support for read receipts and online status.

The system should handle millions of concurrent users and ensure messages are delivered reliably even when users are offline.`,
  functionalRequirements: [
    "Users can send and receive text messages in real-time",
    "Support one-on-one and group chats (up to 256 members)",
    "Send images, videos, and files",
    "Show online/offline status of users",
    "Show read receipts (delivered, read)",
    "Show typing indicators",
    "Store message history",
    "Support message search",
    "Send notifications for new messages when user is offline",
  ],
  nonFunctionalRequirements: [
    "Real-time: Messages delivered within 1 second",
    "Highly available: 99.99% uptime",
    "Support 100M daily active users",
    "Support 1M concurrent WebSocket connections per server",
    "Messages should be persisted and never lost",
    "End-to-end encryption for privacy",
  ],
  constraints: [
    "50M messages sent per day",
    "Average message size: 100 bytes (text) to 10MB (files)",
    "Users can be part of up to 100 group chats",
    "Message history stored for 1 year",
    "Global user base across multiple regions",
  ],
  keyComponents: [
    "WebSocket Servers (for real-time connections)",
    "API Gateway / Load Balancer",
    "Chat Service",
    "Message Queue (Kafka/RabbitMQ)",
    "Database (Message Storage)",
    "Presence Service (online/offline status)",
    "Notification Service",
    "Media Storage (S3)",
    "CDN",
  ],
  hints: [
    "Use WebSockets for bidirectional real-time communication",
    "Store messages in a database partitioned by conversation ID",
    "Use message queues to handle message delivery and retries",
    "Maintain user-to-server mapping for routing messages",
    "Consider using Cassandra or similar for message storage (write-heavy)",
    "Use Redis for presence tracking and online status",
    "Implement message acknowledgments to ensure delivery",
    "Use CDN and object storage for media files",
  ],
  evaluationCriteria: [
    {
      category: "Real-time Architecture",
      description: "Designed proper WebSocket-based architecture for real-time messaging",
      weight: 25,
    },
    {
      category: "Message Delivery",
      description: "Ensured reliable message delivery and ordering",
      weight: 20,
    },
    {
      category: "Scalability",
      description: "System can scale to millions of concurrent connections",
      weight: 20,
    },
    {
      category: "Data Storage",
      description: "Designed efficient storage for messages and media",
      weight: 15,
    },
    {
      category: "Additional Features",
      description: "Covered presence, notifications, encryption",
      weight: 20,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed real-time chat system using WebSocket servers for persistent connections, Kafka for message routing, Cassandra for message storage, and Redis for presence tracking. The system uses consistent hashing to route users to servers and supports horizontal scaling.",
    architecture: [
      "Client Apps: Mobile and web clients with WebSocket connections",
      "Load Balancer: Routes WebSocket connections to chat servers",
      "WebSocket Servers: Maintain persistent connections with users",
      "Message Router: Routes messages to appropriate WebSocket servers",
      "Message Queue (Kafka): Ensures reliable message delivery",
      "Chat Service: Business logic for sending/receiving messages",
      "Database (Cassandra): Stores message history",
      "Presence Service (Redis): Tracks user online/offline status",
      "Notification Service: Sends push notifications for offline users",
      "Object Storage (S3): Stores images, videos, files",
    ],
    dataModel: [
      "Messages: { messageId (PK), conversationId, senderId, receiverId, content, timestamp, status, type }",
      "Conversations: { conversationId (PK), participantIds[], type, createdAt, lastMessageAt }",
      "Users: { userId (PK), username, lastSeen, publicKey }",
      "Presence: Redis - { userId -> { status, lastSeen, connectedServerId } }",
      "UserConnections: { userId -> WebSocketServerId } - for message routing",
      "Partition by conversationId for message queries",
    ],
    apiDesign: [
      "WebSocket Events: onConnect, onMessage, onTyping, onReadReceipt, onDisconnect",
      "POST /api/v1/messages - Send message: { conversationId, recipientIds, content, type }",
      "GET /api/v1/messages/{conversationId}?cursor={}&limit={} - Fetch message history",
      "POST /api/v1/conversations - Create group chat: { name, participantIds }",
      "GET /api/v1/conversations - List user's conversations",
      "PUT /api/v1/messages/{messageId}/read - Mark message as read",
      "GET /api/v1/users/{userId}/presence - Get online status",
    ],
    scalability: [
      "WebSocket Servers: Horizontal scaling - each server handles 1M connections",
      "Consistent Hashing: Route users to servers based on userId hash",
      "Message Queue: Use Kafka partitions for parallel message processing",
      "Database Sharding: Shard messages by conversationId for data locality",
      "Redis Cluster: Shard presence data by userId",
      "Read Replicas: For message history queries",
      "CDN: Serve media files globally for low latency",
      "Service Discovery: Use ZooKeeper/Consul for tracking server locations",
    ],
    tradeoffs: [
      "WebSockets vs Long Polling: WebSockets for low latency but requires persistent connections",
      "Message Ordering: Guaranteed ordering per conversation vs eventual consistency",
      "Presence Accuracy: Real-time presence vs periodic heartbeats (tradeoff between accuracy and load)",
      "Group Chat Fanout: Send to all members immediately vs batch delivery",
      "Database Choice: Cassandra (write-optimized) vs PostgreSQL (strong consistency)",
      "Encryption: End-to-end (more secure, complex) vs transport-level (simpler, less secure)",
    ],
  },
  discussionPoints: [
    "How would you ensure message ordering in a distributed system?",
    "What happens if a user is connected to multiple devices?",
    "How would you handle offline message delivery?",
    "How would you implement group chat with thousands of members?",
    "How would you scale WebSocket connections to millions of users?",
    "How would you implement end-to-end encryption?",
    "How would you handle message search efficiently?",
    "How would you detect and handle network failures?",
    "How would you implement message reactions and threading?",
  ],
}
