import type { SystemDesignScenario } from "../types"

export const ecommerceScenario: SystemDesignScenario = {
  id: "system-design-ecommerce",
  title: "Design E-Commerce Platform",
  type: "system-design",
  difficulty: "medium",
  companies: ["Amazon", "Shopify", "Walmart", "eBay", "Alibaba"],
  description: "Design an e-commerce platform like Amazon with product catalog, cart, and checkout",
  tags: ["system-design", "e-commerce", "payments", "inventory", "scalability"],
  estimatedTime: 50,
  problemStatement: `Design an e-commerce platform like Amazon. Users should be able to browse products, add items to cart, checkout, and track orders.

The system must handle millions of products, high traffic during sales events, ensure accurate inventory management, and process payments securely.`,
  functionalRequirements: [
    "Browse and search products by category, filters, keywords",
    "Product pages with descriptions, images, reviews, ratings",
    "Shopping cart with save for later",
    "Checkout with multiple payment options",
    "Order tracking and history",
    "Inventory management with low-stock alerts",
    "Product recommendations",
    "Customer reviews and ratings",
    "Flash sales and promotional pricing",
  ],
  nonFunctionalRequirements: [
    "Support 100M products in catalog",
    "Handle 10K orders per second during peak (Black Friday)",
    "Page load time < 2 seconds",
    "99.99% uptime during sale events",
    "Payment processing < 3 seconds",
    "Zero overselling of inventory",
  ],
  constraints: [
    "1M orders per day normally, 10M on peak days",
    "100K concurrent shoppers during flash sales",
    "Inventory updates must be atomic",
    "PCI DSS compliance for payments",
    "International shipping and taxes",
  ],
  keyComponents: [
    "Product Catalog Service",
    "Search Service (Elasticsearch)",
    "Cart Service",
    "Order Service",
    "Inventory Service",
    "Payment Service",
    "Shipping Service",
    "Recommendation Engine",
    "Notification Service",
    "CDN for images",
  ],
  hints: [
    "Use eventual consistency for catalog updates, strong consistency for inventory",
    "Implement distributed locking for inventory reservation",
    "Use CQRS pattern to separate read and write models",
    "Cache product data heavily",
    "Use message queues to decouple order processing steps",
    "Implement cart expiration for reserved inventory",
    "Use database transactions for payment and inventory updates",
  ],
  evaluationCriteria: [
    {
      category: "Inventory Management",
      description: "Prevents overselling, handles reservations",
      weight: 25,
    },
    {
      category: "Checkout Flow",
      description: "Reliable payment and order processing",
      weight: 25,
    },
    { category: "Scalability", description: "Handles peak sale events", weight: 20 },
    {
      category: "Search & Discovery",
      description: "Fast product search and filtering",
      weight: 15,
    },
    {
      category: "Data Model",
      description: "Appropriate storage for products, orders",
      weight: 15,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed e-commerce platform using microservices architecture, Elasticsearch for product search, Redis for cart and inventory caching, and event-driven order processing with Kafka.",
    architecture: [
      "API Gateway: Request routing and authentication",
      "Product Catalog: Product information and categories",
      "Search Service: Elasticsearch-based product search",
      "Cart Service: Shopping cart management (Redis-backed)",
      "Inventory Service: Stock management with distributed locking",
      "Order Service: Order lifecycle management",
      "Payment Service: Payment processing integration",
      "Shipping Service: Carrier integration and tracking",
      "Recommendation: Personalized product suggestions",
      "Notification: Order updates via email/SMS/push",
    ],
    dataModel: [
      "Products: { productId, name, description, price, category, images[], sellerId }",
      "Inventory: { productId, warehouseId, quantity, reserved, version }",
      "Carts: { cartId, userId, items: [{ productId, quantity, price }], expiresAt }",
      "Orders: { orderId, userId, items[], totalAmount, status, shippingAddress, paymentId }",
      "Reviews: { reviewId, productId, userId, rating, text, createdAt }",
    ],
    apiDesign: [
      "GET /api/v1/products/search?q={query}&filters={} - Search products",
      "GET /api/v1/products/{id} - Get product details",
      "POST /api/v1/cart/items - Add item to cart",
      "POST /api/v1/orders - Create order from cart",
      "POST /api/v1/orders/{id}/pay - Process payment",
      "GET /api/v1/orders/{id}/track - Track order status",
    ],
    scalability: [
      "Product Cache: CDN for images, Redis for product data",
      "Search Scaling: Elasticsearch cluster with sharding",
      "Inventory Locking: Redis-based distributed locks",
      "Order Processing: Kafka for async, event-driven processing",
      "Read Replicas: Multiple DB replicas for product reads",
      "Flash Sale Handling: Queue-based checkout, inventory pre-warming",
    ],
    tradeoffs: [
      "Consistency vs Availability: Strong consistency for inventory, eventual for catalog",
      "Reservation Timeout: Longer = better UX but higher cart abandonment risk",
      "Pre-compute vs Real-time: Pre-compute recommendations vs real-time personalization",
      "Monolith vs Microservices: Complexity vs scalability",
    ],
  },
  discussionPoints: [
    "How would you prevent overselling during flash sales?",
    "How would you implement cart reservation with timeout?",
    "How would you handle a failed payment after inventory is reserved?",
    "How would you design the order processing pipeline?",
    "How would you implement real-time inventory updates across services?",
    "How would you handle international pricing and taxes?",
  ],
}
