import type { SystemDesignScenario } from "../types"

export const notificationScenario: SystemDesignScenario = {
  id: "system-design-notification",
  title: "Design a Notification System",
  type: "system-design",
  difficulty: "medium",
  companies: ["Amazon", "Meta", "Google", "Apple", "Netflix"],
  description:
    "Design a scalable notification system supporting push, email, SMS, and in-app notifications",
  tags: ["system-design", "notifications", "messaging", "distributed-systems"],
  estimatedTime: 45,
  problemStatement: `Design a notification system that can send notifications to users through multiple channels: push notifications, email, SMS, and in-app notifications.

The system should handle millions of notifications per day, support user preferences, ensure reliable delivery, and provide analytics on notification engagement.`,
  functionalRequirements: [
    "Send notifications via multiple channels (push, email, SMS, in-app)",
    "Support user notification preferences (channels, frequency, quiet hours)",
    "Template-based notifications with personalization",
    "Priority levels (critical, high, normal, low)",
    "Batch notifications for non-urgent messages",
    "Delivery tracking and retry logic",
    "Rate limiting to prevent spam",
    "Analytics: open rates, click rates, delivery rates",
  ],
  nonFunctionalRequirements: [
    "Handle 10M notifications per hour",
    "Delivery within 30 seconds for high-priority",
    "99.9% delivery success rate",
    "Support 100M registered users",
    "Low latency for real-time notifications",
    "Handle provider failures gracefully",
  ],
  constraints: [
    "100M notifications per day",
    "Multiple third-party providers (Firebase, APNS, Twilio, SendGrid)",
    "User preferences must be respected",
    "Duplicate notifications must be prevented",
    "Audit trail for all notifications",
  ],
  keyComponents: [
    "API Gateway",
    "Notification Service",
    "Template Service",
    "User Preferences Service",
    "Channel Adapters (Push, Email, SMS)",
    "Message Queue (Kafka/RabbitMQ)",
    "Delivery Tracker",
    "Rate Limiter",
    "Analytics Service",
  ],
  hints: [
    "Use message queues to decouple notification generation from delivery",
    "Implement circuit breaker pattern for third-party provider failures",
    "Use separate queues for different priorities",
    "Batch low-priority notifications to reduce costs",
    "Cache user preferences for quick lookup",
    "Use idempotency keys to prevent duplicates",
    "Implement exponential backoff for retries",
  ],
  evaluationCriteria: [
    {
      category: "Multi-channel Architecture",
      description: "Clean separation of notification channels",
      weight: 25,
    },
    { category: "Reliability", description: "Delivery guarantees and retry logic", weight: 25 },
    { category: "Scalability", description: "Handles high throughput", weight: 20 },
    {
      category: "User Preferences",
      description: "Respects user settings and rate limits",
      weight: 15,
    },
    { category: "Extensibility", description: "Easy to add new channels", weight: 15 },
  ],
  exampleSolution: {
    overview:
      "A distributed notification system using Kafka for message queuing, channel-specific adapters for different notification types, Redis for user preferences caching, and circuit breakers for provider resilience.",
    architecture: [
      "API Gateway: Receives notification requests",
      "Notification Service: Orchestrates notification flow",
      "Priority Router: Routes to appropriate queues based on priority",
      "Template Engine: Renders notification content",
      "Channel Adapters: Push (Firebase/APNS), Email (SendGrid), SMS (Twilio)",
      "Preference Service: Manages user notification settings",
      "Delivery Tracker: Tracks delivery status and retries",
      "Analytics Service: Aggregates engagement metrics",
    ],
    dataModel: [
      "Notifications: { id, userId, type, channel, content, status, priority, createdAt, sentAt }",
      "Templates: { id, name, channel, subject, body, variables[] }",
      "Preferences: { userId, channels: { push, email, sms }, quietHours, frequency }",
      "DeliveryLog: { notificationId, channel, status, attempts, lastError, providerId }",
      "Analytics: { templateId, channel, sent, delivered, opened, clicked, date }",
    ],
    apiDesign: [
      "POST /api/v1/notifications - Send notification: { userId, templateId, data, priority, channels }",
      "POST /api/v1/notifications/batch - Batch notifications: { userIds[], templateId, data }",
      "GET /api/v1/users/{id}/preferences - Get notification preferences",
      "PUT /api/v1/users/{id}/preferences - Update preferences",
      "GET /api/v1/notifications/{id}/status - Get delivery status",
      "GET /api/v1/analytics/notifications - Get notification analytics",
    ],
    scalability: [
      "Priority Queues: Separate Kafka topics for critical, high, normal, low",
      "Horizontal Scaling: Scale channel adapters independently",
      "Batching: Aggregate low-priority notifications",
      "Caching: Cache user preferences in Redis",
      "Provider Failover: Multiple providers per channel with automatic failover",
      "Sharding: Partition by userId for user-specific operations",
    ],
    tradeoffs: [
      "Push vs Pull: Push for real-time, poll for less critical",
      "Delivery Speed vs Cost: Batching reduces cost but increases latency",
      "Reliability vs Latency: More retries = higher reliability but slower",
      "Personalization vs Performance: More personalization = more computation",
      "Single vs Multiple Providers: Resilience vs complexity",
    ],
  },
  discussionPoints: [
    "How would you handle a provider outage?",
    "How would you prevent notification fatigue for users?",
    "How would you implement quiet hours across different time zones?",
    "How would you handle a sudden spike in notifications (e.g., Black Friday)?",
    "How would you track and analyze notification effectiveness?",
    "How would you implement notification grouping/bundling?",
  ],
}
