import type { SystemDesignScenario } from "../types"

export const instagramScenario: SystemDesignScenario = {
  id: "system-design-instagram",
  title: "Design Instagram/Photo Sharing Service",
  type: "system-design",
  difficulty: "hard",
  companies: ["Meta", "Google", "Amazon", "Netflix"],
  description: "Design a photo sharing and social networking service like Instagram",
  tags: ["system-design", "scalability", "social-network", "distributed-systems", "cdn"],
  estimatedTime: 60,
  problemStatement: `Design a photo-sharing social networking service like Instagram. Users should be able to upload photos, follow other users, like and comment on photos, and see a feed of photos from people they follow.

The system should handle hundreds of millions of users and billions of photos. Consider how you would store and serve images efficiently, generate personalized feeds, and handle the massive scale of social interactions.`,
  functionalRequirements: [
    "Users can upload photos with captions and hashtags",
    "Users can follow/unfollow other users",
    "Users can like and comment on photos",
    "Users see a personalized feed of photos from people they follow",
    "Users can search for photos by hashtags or users",
    "Users can view their own profile and others' profiles",
    "Support stories (photos that disappear after 24 hours)",
    "Send notifications for likes, comments, follows",
  ],
  nonFunctionalRequirements: [
    "System should support 500M daily active users",
    "Low latency: Feed should load in < 2 seconds",
    "High availability: 99.99% uptime",
    "Photos should be uploaded and available quickly",
    "System should be globally distributed",
    "Handle viral posts (photos that get millions of likes)",
  ],
  constraints: [
    "200M photos uploaded per day",
    "Average photo size: 2MB",
    "Average user follows 200 people",
    "Average user has 100 followers",
    "Read:Write ratio is 100:1",
    "Need to store photos for 10+ years",
  ],
  keyComponents: [
    "API Gateway / Load Balancer",
    "Application Servers",
    "Image Upload Service",
    "Image Storage (S3/Blob Storage)",
    "CDN for image delivery",
    "Databases (User, Posts, Relationships)",
    "Feed Generation Service",
    "Search Service",
    "Notification Service",
    "Cache Layer",
  ],
  hints: [
    "Separate image storage from metadata storage",
    "Use object storage (S3) and CDN for serving images globally",
    "Pre-generate feeds asynchronously rather than on-demand",
    "Use graph database or adjacency list for follow relationships",
    "Consider sharding strategies: by userId, by geography",
    "Use message queues for async tasks (notifications, feed updates)",
    "Cache user feeds, popular posts, and user profiles",
    "Consider using a ranking algorithm for feed ordering (chronological vs engagement-based)",
  ],
  evaluationCriteria: [
    {
      category: "Requirements & Scope",
      description: "Properly scoped the problem and clarified requirements",
      weight: 10,
    },
    {
      category: "High-Level Architecture",
      description: "Designed comprehensive architecture with all major components",
      weight: 25,
    },
    {
      category: "Data Model & Storage",
      description: "Designed scalable data model for users, posts, relationships",
      weight: 20,
    },
    {
      category: "Scalability & Performance",
      description: "Addressed scalability challenges (sharding, caching, CDN)",
      weight: 25,
    },
    {
      category: "Trade-offs & Deep Dives",
      description: "Discussed trade-offs and deep-dived into complex areas",
      weight: 20,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed photo-sharing platform using microservices architecture. Images are stored in S3 and served via CDN. User metadata and relationships are stored in sharded databases. Feeds are pre-generated asynchronously and cached. The system uses Kafka for event streaming and async processing.",
    architecture: [
      "Client Apps: iOS, Android, Web",
      "CDN: CloudFront/Cloudflare for serving images globally",
      "Load Balancer: Distributes traffic across API servers",
      "API Gateway: Rate limiting, authentication, routing",
      "Microservices: Upload Service, Feed Service, User Service, Search Service, Notification Service",
      "Message Queue: Kafka for async event processing",
      "Cache Layer: Redis for feeds, user data, popular posts",
      "Databases: PostgreSQL (sharded) for metadata, Cassandra for feeds",
      "Object Storage: S3 for original and processed images",
      "Search: Elasticsearch for hashtag and user search",
    ],
    dataModel: [
      "Users: { userId (PK), username, email, profilePicUrl, bio, followerCount, followingCount, createdAt }",
      "Posts: { postId (PK), userId, imageUrl, caption, hashtags[], createdAt, likeCount, commentCount }",
      "Follows: { followerId, followeeId, createdAt } - Composite PK",
      "Likes: { postId, userId, createdAt } - Composite PK",
      "Comments: { commentId (PK), postId, userId, text, createdAt }",
      "Feed: { userId, postId, score, createdAt } - Pre-computed feeds",
      "Sharding: Shard Users and Posts by userId hash",
      "Indexes: On userId, postId, hashtags, createdAt",
    ],
    apiDesign: [
      "POST /api/v1/posts - Upload photo: { image, caption, hashtags }",
      "GET /api/v1/feed - Get personalized feed: { cursor, limit }",
      "POST /api/v1/posts/{postId}/like - Like a post",
      "POST /api/v1/posts/{postId}/comments - Comment: { text }",
      "POST /api/v1/users/{userId}/follow - Follow a user",
      "GET /api/v1/users/{userId} - Get user profile",
      "GET /api/v1/search?q={query}&type={users|hashtags} - Search",
    ],
    scalability: [
      "Image Upload: Client uploads directly to S3 via pre-signed URLs, reducing server load",
      "Image Processing: Async workers resize images to multiple sizes (thumbnail, medium, full)",
      "Feed Generation: Fanout-on-write for users with few followers, fanout-on-read for celebrities",
      "Database Sharding: Shard by userId for data locality",
      "Cache Strategy: Cache user feeds (Redis), popular posts, user profiles",
      "CDN: Serve images from edge locations for low latency globally",
      "Read Replicas: Multiple DB replicas for read-heavy operations",
      "Async Processing: Use Kafka for feed updates, notifications, analytics",
    ],
    tradeoffs: [
      "Fanout-on-write vs Fanout-on-read: Pre-generate feeds vs generate on-demand",
      "SQL vs NoSQL: PostgreSQL for complex queries vs Cassandra for write-heavy workloads",
      "Chronological vs Ranked feed: Simple timeline vs engagement-based ranking",
      "Normalization: Store like count in Posts table (denormalized) for performance",
      "Consistency: Eventual consistency for like counts vs strong consistency",
      "Celebrity problem: Special handling for users with millions of followers",
    ],
  },
  discussionPoints: [
    "How would you handle a celebrity with 100M followers posting a photo?",
    "How would you generate and rank the personalized feed?",
    "How would you implement the search functionality for hashtags and users?",
    "How would you ensure high availability during region failures?",
    "How would you handle image storage and delivery efficiently?",
    "What metrics would you track to monitor system health and user engagement?",
    "How would you implement stories (disappearing content)?",
    "How would you prevent spam and abusive content?",
    "How would you handle GDPR and user data deletion requests?",
  ],
}
