import type { SystemDesignScenario } from "../types"

export const distributedCacheScenario: SystemDesignScenario = {
  id: "system-design-distributed-cache",
  title: "Design a Distributed Cache",
  type: "system-design",
  difficulty: "medium",
  companies: ["Google", "Amazon", "Meta", "Netflix", "Microsoft"],
  description: "Design a distributed caching system like Redis or Memcached",
  tags: ["system-design", "distributed-systems", "caching", "performance"],
  estimatedTime: 45,
  problemStatement: `Design a distributed in-memory caching system similar to Redis or Memcached. The system should allow applications to store and retrieve key-value pairs with very low latency.

Consider how you would distribute data across multiple cache servers, handle server failures, and ensure high performance and availability.`,
  functionalRequirements: [
    "Store and retrieve key-value pairs (strings, integers, objects)",
    "Support TTL (time-to-live) for automatic expiration",
    "Support eviction policies (LRU, LFU, FIFO)",
    "Atomic operations: increment, decrement, compare-and-swap",
    "Support for data structures: lists, sets, sorted sets, hashes",
    "Provide APIs: GET, SET, DELETE, EXISTS, EXPIRE",
  ],
  nonFunctionalRequirements: [
    "Low latency: < 1ms for read/write operations",
    "High throughput: millions of operations per second",
    "High availability: tolerate node failures",
    "Scalability: easily add/remove cache nodes",
    "Consistency: handle concurrent updates correctly",
  ],
  constraints: [
    "Support up to 100 cache nodes in a cluster",
    "Each node can store up to 100GB of data",
    "Network latency between nodes: 1-5ms",
    "Client applications can send millions of requests per second",
  ],
  keyComponents: [
    "Cache Client Library",
    "Cache Servers (Nodes)",
    "Consistent Hashing Ring",
    "Replication Manager",
    "Cluster Manager",
    "Monitoring & Health Checks",
  ],
  hints: [
    "Use consistent hashing to distribute keys across cache nodes",
    "Consistent hashing minimizes data movement when nodes are added/removed",
    "Consider replication for high availability (master-slave or multi-master)",
    "Use virtual nodes to balance load more evenly",
    "Implement client-side caching for frequently accessed keys",
    "Use write-through or write-behind strategies for persistence",
    "Handle network partitions with quorum-based reads/writes",
  ],
  evaluationCriteria: [
    {
      category: "Core Functionality",
      description: "Designed basic cache operations and data structures",
      weight: 20,
    },
    {
      category: "Distribution Strategy",
      description: "Chose appropriate data distribution mechanism (consistent hashing)",
      weight: 25,
    },
    {
      category: "High Availability",
      description: "Addressed replication and failure handling",
      weight: 20,
    },
    {
      category: "Performance",
      description: "Optimized for low latency and high throughput",
      weight: 20,
    },
    {
      category: "Trade-offs",
      description: "Discussed CAP theorem and consistency trade-offs",
      weight: 15,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed cache using consistent hashing for data distribution, master-slave replication for availability, and client-side sharding for performance. The system uses virtual nodes for balanced load distribution and supports automatic failover.",
    architecture: [
      "Cache Clients: Smart clients with embedded hashing logic",
      "Cache Nodes: Multiple cache servers forming a cluster",
      "Consistent Hash Ring: Virtual ring for key distribution",
      "Replication: Each key replicated to N nodes (typically 3)",
      "Cluster Manager: Monitors node health and manages cluster membership",
      "Configuration Service: Stores cluster topology (ZooKeeper/etcd)",
    ],
    dataModel: [
      "In-Memory Hash Table: { key -> value, ttl, lastAccessed }",
      "LRU List: Doubly linked list for eviction policy",
      "Expiration Heap: Min-heap ordered by expiration time",
      "Key Format: string keys, values can be strings, integers, serialized objects",
      "Metadata: Each entry stores size, creation time, access count",
    ],
    apiDesign: [
      "GET key - Retrieve value for key - Returns: value or null",
      "SET key value [EX seconds] - Store key-value with optional TTL",
      "DELETE key - Remove key from cache",
      "EXISTS key - Check if key exists - Returns: boolean",
      "INCR key - Atomically increment integer value",
      "EXPIRE key seconds - Set TTL on existing key",
      "TTL key - Get remaining TTL - Returns: seconds or -1",
    ],
    scalability: [
      "Consistent Hashing: Use hash(key) % ring_size to determine node",
      "Virtual Nodes: Each physical node gets 100-200 virtual nodes for even distribution",
      "Client-Side Sharding: Clients calculate target node, reducing server load",
      "Horizontal Scaling: Add nodes to ring; only 1/N keys need to be redistributed",
      "Connection Pooling: Maintain persistent connections to cache nodes",
      "Pipelining: Batch multiple operations in a single network round trip",
    ],
    tradeoffs: [
      "Consistency vs Availability: CAP theorem - choose AP over CP for caching",
      "Replication: More replicas = higher availability but more memory usage",
      "Eviction Policy: LRU (recency) vs LFU (frequency) vs TTL-based",
      "Write Strategy: Write-through (slower writes, consistent) vs write-behind (faster, risk of data loss)",
      "Data Persistence: In-memory only vs periodic snapshots vs AOF log",
      "Hashing: Simple modulo (simple but poor scaling) vs consistent hashing (complex but better scaling)",
    ],
  },
  discussionPoints: [
    "How does consistent hashing work and why is it better than simple modulo hashing?",
    "What happens when a cache node fails? How do you ensure availability?",
    "How would you handle the thundering herd problem (many clients requesting same expired key)?",
    "How would you implement cache warming (pre-populating cache)?",
    "What eviction policy would you use and why?",
    "How would you handle large objects that don't fit in memory?",
    "How would you monitor cache hit rate and optimize it?",
    "How would you handle network partitions in the cluster?",
  ],
}
