import type { SystemDesignScenario } from "../types"

export const fileStorageScenario: SystemDesignScenario = {
  id: "system-design-file-storage",
  title: "Design Cloud File Storage (Dropbox)",
  type: "system-design",
  difficulty: "medium",
  companies: ["Dropbox", "Google", "Microsoft", "Box", "Apple"],
  description: "Design a cloud file storage and sync service like Dropbox or Google Drive",
  tags: ["system-design", "file-storage", "sync", "distributed-systems"],
  estimatedTime: 50,
  problemStatement: `Design a cloud file storage service like Dropbox or Google Drive. Users should be able to upload, download, and sync files across devices, share files with others, and access previous versions.

The system must handle large files, provide efficient synchronization, ensure data durability, and support real-time collaboration.`,
  functionalRequirements: [
    "Upload and download files of any type",
    "Automatic sync across all user devices",
    "Share files/folders with other users (view, edit permissions)",
    "File versioning - access and restore previous versions",
    "Conflict resolution for concurrent edits",
    "Folder organization and management",
    "Search files by name and content",
    "Offline access with sync when online",
    "File preview for common formats",
  ],
  nonFunctionalRequirements: [
    "Support files up to 50GB",
    "99.99% durability (no data loss)",
    "Sync latency < 10 seconds for small files",
    "Support 100M users with 10GB average storage each",
    "Resume interrupted uploads/downloads",
    "Efficient bandwidth usage (delta sync)",
  ],
  constraints: [
    "1 billion files uploaded per day",
    "Average file size: 1MB",
    "Large files (100MB+): 1% of uploads",
    "Same file stored by multiple users (deduplication opportunity)",
    "Peak sync during work hours",
  ],
  keyComponents: [
    "Upload/Download Service",
    "Metadata Service",
    "Sync Service",
    "Block Storage Service",
    "Notification Service",
    "Sharing Service",
    "Search Service",
    "Object Storage (S3)",
    "Message Queue",
    "CDN",
  ],
  hints: [
    "Use chunked upload for large files with resumable capability",
    "Implement content-addressable storage for deduplication",
    "Use delta sync - only transfer changed blocks",
    "Separate metadata from file content for faster sync",
    "Use WebSockets or long polling for real-time sync notifications",
    "Implement optimistic locking for conflict resolution",
    "Use consistent hashing for file distribution",
  ],
  evaluationCriteria: [
    {
      category: "Sync Architecture",
      description: "Efficient, reliable file synchronization",
      weight: 25,
    },
    {
      category: "Storage Design",
      description: "Chunking, deduplication, versioning",
      weight: 25,
    },
    {
      category: "Scalability",
      description: "Handles large files and high user count",
      weight: 20,
    },
    {
      category: "Conflict Resolution",
      description: "Handles concurrent edits gracefully",
      weight: 15,
    },
    { category: "Reliability", description: "Data durability and availability", weight: 15 },
  ],
  exampleSolution: {
    overview:
      "A distributed file storage system using chunked, content-addressable storage for deduplication, delta sync for bandwidth efficiency, and a metadata service for fast sync operations. Files are split into 4MB chunks, each stored with its content hash for deduplication.",
    architecture: [
      "Upload Service: Handles chunked file uploads",
      "Download Service: Serves file downloads from nearest location",
      "Metadata Service: Stores file/folder structure, permissions",
      "Sync Service: Coordinates sync across devices",
      "Block Server: Stores file chunks with deduplication",
      "Notification Service: Real-time sync notifications",
      "Sharing Service: Manages permissions and shared links",
      "Search Service: Full-text search in documents",
      "Object Storage: S3 for actual file chunks",
    ],
    dataModel: [
      "Files: { fileId, userId, name, path, size, checksum, versions[], createdAt, modifiedAt }",
      "Chunks: { chunkHash, size, refCount } - Content-addressable",
      "FileChunks: { fileId, version, chunkHashes[], order }",
      "Folders: { folderId, userId, name, path, parentId }",
      "Shares: { shareId, resourceId, resourceType, ownerId, sharedWith[], permissions }",
      "SyncState: { userId, deviceId, lastSyncTimestamp, pendingChanges[] }",
    ],
    apiDesign: [
      "POST /api/v1/files/upload/init - Initialize chunked upload",
      "PUT /api/v1/files/upload/{uploadId}/chunk/{n} - Upload chunk",
      "POST /api/v1/files/upload/{uploadId}/complete - Complete upload",
      "GET /api/v1/files/{id}/download - Download file",
      "GET /api/v1/sync/changes?since={timestamp} - Get changes since last sync",
      "POST /api/v1/files/{id}/share - Share file with users",
      "GET /api/v1/files/{id}/versions - Get file version history",
    ],
    scalability: [
      "Chunked Storage: 4MB chunks for efficient transfer and deduplication",
      "Deduplication: Content-addressable storage saves 50%+ storage",
      "Delta Sync: Only sync changed chunks, not entire files",
      "Metadata Sharding: Shard by userId for user-specific operations",
      "CDN: Serve files from edge locations",
      "Async Processing: Queue-based for indexing, thumbnail generation",
    ],
    tradeoffs: [
      "Chunk Size: Larger = less overhead, Smaller = better dedup/delta sync",
      "Sync Frequency: More frequent = lower latency, higher battery/bandwidth",
      "Deduplication Scope: Per-user vs global (privacy vs storage savings)",
      "Version Retention: More versions = more storage cost",
      "Consistency: Strong for metadata, eventual for sync state",
    ],
  },
  discussionPoints: [
    "How would you implement resumable uploads for large files?",
    "How would you handle conflicts when two users edit the same file?",
    "How would you implement efficient delta sync?",
    "How would you ensure data durability (no data loss)?",
    "How would you implement file deduplication?",
    "How would you design the sync protocol for offline-first clients?",
  ],
}
