import type { SystemDesignScenario } from "../types"

export const videoStreamingScenario: SystemDesignScenario = {
  id: "system-design-video-streaming",
  title: "Design Video Streaming (Netflix/YouTube)",
  type: "system-design",
  difficulty: "hard",
  companies: ["Netflix", "Google", "Amazon", "Meta", "Apple"],
  description: "Design a video streaming platform like Netflix or YouTube",
  tags: ["system-design", "streaming", "cdn", "video", "scalability"],
  estimatedTime: 60,
  problemStatement: `Design a video streaming platform like Netflix or YouTube. Users should be able to upload videos (YouTube) or stream content (Netflix), with support for different video qualities, adaptive bitrate streaming, and personalized recommendations.

The system must handle millions of concurrent viewers, efficiently deliver video content globally, and provide a seamless viewing experience across devices.`,
  functionalRequirements: [
    "Video upload with automatic transcoding to multiple formats/qualities",
    "Adaptive bitrate streaming based on network conditions",
    "Video playback with seek, pause, resume functionality",
    "Continue watching from where you left off",
    "Personalized recommendations",
    "Search for videos/shows",
    "User watchlist and favorites",
    "Multiple device support with account sharing limits",
    "Subtitles and multiple audio tracks",
  ],
  nonFunctionalRequirements: [
    "Support 100M concurrent viewers",
    "Video start time < 2 seconds",
    "No buffering for 99% of streams",
    "Global availability with low latency",
    "99.99% uptime",
    "Support 4K HDR streaming",
  ],
  constraints: [
    "1 billion hours of video watched per day",
    "Average video length: 45 minutes (Netflix), 10 minutes (YouTube)",
    "Video storage: petabytes of content",
    "Peak viewing: 2x average during evenings",
    "Support 8K future-proofing",
  ],
  keyComponents: [
    "Video Upload Service",
    "Transcoding Pipeline",
    "Content Delivery Network (CDN)",
    "Video Streaming Service",
    "Recommendation Engine",
    "User Service",
    "Search Service",
    "Analytics Service",
    "Object Storage (S3)",
    "Metadata Database",
  ],
  hints: [
    "Use adaptive bitrate streaming (HLS/DASH) for quality adjustment",
    "Pre-position popular content at edge locations",
    "Transcode videos into multiple resolutions and codecs",
    "Use chunk-based streaming for efficient seeking",
    "Cache video metadata and thumbnails aggressively",
    "Implement predictive buffering based on user behavior",
    "Use ML for personalized recommendations",
  ],
  evaluationCriteria: [
    {
      category: "Video Delivery",
      description: "CDN strategy and streaming protocol",
      weight: 25,
    },
    { category: "Transcoding Pipeline", description: "Efficient video processing", weight: 20 },
    {
      category: "Scalability",
      description: "Handles millions of concurrent streams",
      weight: 25,
    },
    { category: "User Experience", description: "Low latency, adaptive quality", weight: 15 },
    { category: "Recommendations", description: "Personalization approach", weight: 15 },
  ],
  exampleSolution: {
    overview:
      "A distributed video streaming platform using a global CDN for content delivery, adaptive bitrate streaming (HLS), a distributed transcoding pipeline, and ML-based recommendations. Content is pre-positioned at edge locations based on popularity predictions.",
    architecture: [
      "Upload Service: Handles video ingestion and validation",
      "Transcoding Pipeline: Distributed workers for video processing",
      "Object Storage: S3 for original and transcoded videos",
      "CDN: Global edge network for video delivery",
      "Streaming Service: Manages playback sessions",
      "Recommendation Engine: ML-based content suggestions",
      "Search Service: Elasticsearch for video search",
      "User Service: Profiles, watchlists, history",
      "Analytics: Viewing metrics and content performance",
    ],
    dataModel: [
      "Videos: { videoId, title, description, duration, uploadedAt, transcodingStatus }",
      "VideoVersions: { videoId, quality, codec, url, fileSize, bitrate }",
      "Users: { userId, email, plan, profiles[], devices[] }",
      "WatchHistory: { userId, videoId, progress, lastWatched }",
      "Recommendations: { userId, videoIds[], scores[], algorithm }",
      "CDNContent: { videoId, edgeLocations[], popularity, lastAccessed }",
    ],
    apiDesign: [
      "POST /api/v1/videos/upload - Initiate video upload",
      "GET /api/v1/videos/{id}/manifest - Get streaming manifest (HLS/DASH)",
      "GET /api/v1/videos/{id}/stream/{quality} - Stream video chunks",
      "POST /api/v1/videos/{id}/progress - Update watch progress",
      "GET /api/v1/recommendations - Get personalized recommendations",
      "GET /api/v1/search?q={query} - Search videos",
      "GET /api/v1/users/watchlist - Get user watchlist",
    ],
    scalability: [
      "CDN Edge Caching: Cache popular content at 100+ edge locations",
      "Adaptive Bitrate: HLS with multiple quality levels (360p to 4K)",
      "Chunk-based Streaming: 2-10 second chunks for efficient seeking",
      "Predictive Positioning: Pre-cache likely-to-watch content at edges",
      "Load Balancing: Direct users to nearest, least-loaded edge server",
      "Transcoding: Distributed workers with auto-scaling",
    ],
    tradeoffs: [
      "Quality vs Bandwidth: Higher quality = more bandwidth cost",
      "Storage vs Compute: More pre-transcoded versions vs on-the-fly",
      "Edge Caching: More edge copies = faster delivery but higher storage",
      "Recommendations: Personalization depth vs computation cost",
      "Codec Choice: Newer codecs (AV1) = better compression but less device support",
    ],
  },
  discussionPoints: [
    "How would you handle a new show release watched by millions simultaneously?",
    "How would you implement adaptive bitrate streaming?",
    "How would you design the transcoding pipeline for efficiency?",
    "How would you decide which content to cache at edge locations?",
    "How would you implement the recommendation system?",
    "How would you handle users on slow/unstable networks?",
  ],
}
