import type { SystemDesignScenario } from "../types"

export const twitterScenario: SystemDesignScenario = {
  id: "system-design-twitter",
  title: "Design Twitter/X News Feed",
  type: "system-design",
  difficulty: "hard",
  companies: ["Meta", "Google", "Twitter", "LinkedIn"],
  description: "Design a social media platform with real-time news feed like Twitter/X",
  tags: ["system-design", "social-network", "feed-generation", "real-time", "scalability"],
  estimatedTime: 60,
  problemStatement: `Design a social media platform like Twitter where users can post tweets, follow other users, and see a personalized timeline of tweets from people they follow.

The system should handle hundreds of millions of users, support real-time updates, and generate personalized feeds efficiently. Consider how you would handle viral tweets, celebrity accounts with millions of followers, and real-time trending topics.`,
  functionalRequirements: [
    "Users can post tweets (text, images, videos) up to 280 characters",
    "Users can follow/unfollow other users",
    "Users can like, retweet, and reply to tweets",
    "Users see a personalized timeline of tweets from followed users",
    "Support hashtags and @mentions",
    "Show trending topics and hashtags",
    "Real-time notifications for mentions, likes, retweets",
    "Search for tweets, users, and hashtags",
  ],
  nonFunctionalRequirements: [
    "Support 500M daily active users",
    "Timeline should load in < 2 seconds",
    "99.99% availability",
    "Handle 100K tweets per second at peak",
    "Real-time updates for new tweets",
    "Global distribution for low latency",
  ],
  constraints: [
    "500M tweets posted per day",
    "Average user follows 200 accounts",
    "Some celebrities have 100M+ followers",
    "Read:Write ratio is 1000:1",
    "Tweets should never be lost",
  ],
  keyComponents: [
    "API Gateway / Load Balancer",
    "Tweet Service",
    "Timeline Service",
    "Fan-out Service",
    "User Service",
    "Search Service (Elasticsearch)",
    "Notification Service",
    "Cache Layer (Redis)",
    "Message Queue (Kafka)",
    "Object Storage (S3)",
    "CDN",
  ],
  hints: [
    "Fan-out on write for normal users, fan-out on read for celebrities",
    "Pre-compute timelines and cache them",
    "Use message queues to handle async fan-out",
    "Consider hybrid approach: cache recent tweets, fetch older from DB",
    "Use consistent hashing for timeline cache distribution",
    "Separate hot data (recent tweets) from cold data (old tweets)",
    "Use Elasticsearch for tweet and user search",
  ],
  evaluationCriteria: [
    {
      category: "Requirements & Scope",
      description: "Properly scoped and prioritized features",
      weight: 10,
    },
    {
      category: "Feed Generation",
      description: "Efficient timeline generation strategy",
      weight: 25,
    },
    {
      category: "Scalability",
      description: "Handles celebrity problem and viral tweets",
      weight: 25,
    },
    {
      category: "Data Model",
      description: "Appropriate storage for tweets, relationships",
      weight: 20,
    },
    {
      category: "Trade-offs",
      description: "Discussed consistency, latency trade-offs",
      weight: 20,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed social platform using hybrid fan-out strategy, Redis for timeline caching, Kafka for async processing, and Elasticsearch for search. Celebrity tweets use fan-out on read, while normal users use fan-out on write.",
    architecture: [
      "Load Balancer: Distributes traffic globally",
      "API Gateway: Rate limiting, authentication",
      "Tweet Service: Handles tweet creation and storage",
      "Timeline Service: Generates and serves user timelines",
      "Fan-out Service: Distributes tweets to follower timelines",
      "Search Service: Elasticsearch for tweet/user/hashtag search",
      "Trending Service: Computes trending topics in real-time",
      "Notification Service: Push notifications via Firebase/APNS",
      "Cache: Redis cluster for timeline and hot tweet caching",
      "Storage: Cassandra for tweets, Neo4j for social graph",
    ],
    dataModel: [
      "Tweets: { tweetId, userId, content, mediaUrls[], createdAt, likeCount, retweetCount }",
      "Users: { userId, username, followerCount, followingCount, verified }",
      "Follows: { followerId, followeeId, createdAt } - Graph structure",
      "Timeline: { userId, tweetId, score, timestamp } - Pre-computed",
      "Likes: { userId, tweetId, timestamp }",
      "Hashtags: { tag, tweetIds[], count, trending }",
    ],
    apiDesign: [
      "POST /api/v1/tweets - Create tweet",
      "GET /api/v1/timeline - Get personalized timeline",
      "POST /api/v1/tweets/{id}/like - Like tweet",
      "POST /api/v1/tweets/{id}/retweet - Retweet",
      "POST /api/v1/users/{id}/follow - Follow user",
      "GET /api/v1/search?q={query}&type={tweets|users|hashtags}",
      "GET /api/v1/trending - Get trending topics",
    ],
    scalability: [
      "Hybrid Fan-out: Fan-out on write for < 10K followers, on read for celebrities",
      "Timeline Caching: Cache last 800 tweets per user in Redis",
      "Sharding: Shard tweets by tweetId, users by userId",
      "Celebrity Optimization: Merge celebrity tweets at read time",
      "Hot Spot Handling: Replicate viral tweets across multiple cache nodes",
      "Geographic Distribution: Multiple data centers with eventual consistency",
    ],
    tradeoffs: [
      "Fan-out on write vs read: Latency vs storage trade-off",
      "Consistency: Eventual consistency for likes/retweets acceptable",
      "Timeline Ranking: Chronological vs algorithmic (engagement-based)",
      "Real-time vs Batch: Real-time trending vs periodic computation",
      "Storage: Normalized (joins) vs denormalized (duplication)",
    ],
  },
  discussionPoints: [
    "How would you handle a tweet going viral with millions of retweets?",
    "How would you generate the trending topics in real-time?",
    "What happens when a celebrity with 100M followers posts a tweet?",
    "How would you implement the algorithmic timeline ranking?",
    "How would you handle tweet deletion and its propagation?",
    "How would you implement the search typeahead feature?",
  ],
}
