import type { SystemDesignScenario } from "../types"

export const uberScenario: SystemDesignScenario = {
  id: "system-design-uber",
  title: "Design Uber/Ride-Sharing Service",
  type: "system-design",
  difficulty: "hard",
  companies: ["Uber", "Lyft", "DoorDash", "Instacart", "Google"],
  description: "Design a ride-sharing platform that matches drivers with riders in real-time",
  tags: ["system-design", "geolocation", "real-time", "matching", "maps"],
  estimatedTime: 60,
  problemStatement: `Design a ride-sharing service like Uber or Lyft. Users should be able to request rides, get matched with nearby drivers, track their ride in real-time, and pay seamlessly.

The system must handle millions of concurrent users, provide real-time location updates, efficiently match riders with drivers, and calculate optimal routes and pricing.`,
  functionalRequirements: [
    "Riders can request rides with pickup and dropoff locations",
    "Match riders with nearby available drivers",
    "Real-time location tracking for both rider and driver",
    "Calculate ETA and fare estimate before ride",
    "Support different ride types (UberX, UberXL, Uber Black)",
    "In-app payments and receipts",
    "Rating system for drivers and riders",
    "Surge pricing during high demand",
    "Driver can accept/decline ride requests",
  ],
  nonFunctionalRequirements: [
    "Match rider with driver within 30 seconds",
    "Location updates every 3-5 seconds",
    "99.99% availability",
    "Support 10M concurrent users globally",
    "Low latency matching (< 5 seconds)",
    "Accurate ETA predictions (within 5 minutes)",
  ],
  constraints: [
    "10M rides per day globally",
    "1M active drivers at any time",
    "Location data for all active users updated every 4 seconds",
    "Average ride lasts 15 minutes",
    "Peak hours have 3x normal demand",
  ],
  keyComponents: [
    "API Gateway",
    "Ride Matching Service",
    "Location Service",
    "Map/Routing Service",
    "Pricing Service",
    "Payment Service",
    "Notification Service",
    "Driver/Rider Apps",
    "Real-time Database (Redis)",
    "Geospatial Index",
    "Message Queue",
  ],
  hints: [
    "Use geospatial indexing (Geohash, S2, H3) for efficient nearby search",
    "Separate read and write paths for location data",
    "Use WebSockets or Server-Sent Events for real-time updates",
    "Consider using a supply-demand prediction model for surge pricing",
    "Partition location data by geographic region",
    "Use Redis with geospatial commands for nearby driver queries",
    "Implement circuit breakers for external service calls (maps, payments)",
  ],
  evaluationCriteria: [
    {
      category: "Matching Algorithm",
      description: "Efficient driver-rider matching",
      weight: 25,
    },
    {
      category: "Real-time Location",
      description: "Scalable location tracking system",
      weight: 25,
    },
    {
      category: "Scalability",
      description: "Handles peak load and geographic distribution",
      weight: 20,
    },
    {
      category: "Data Model",
      description: "Appropriate storage for rides, locations",
      weight: 15,
    },
    {
      category: "Trade-offs",
      description: "Discussed latency, consistency trade-offs",
      weight: 15,
    },
  ],
  exampleSolution: {
    overview:
      "A distributed ride-sharing platform using geospatial indexing for nearby driver search, Kafka for location streaming, Redis for real-time state, and WebSockets for live updates. The matching algorithm uses a weighted scoring system considering distance, ETA, driver rating, and vehicle type.",
    architecture: [
      "Mobile Apps: Rider and Driver apps with real-time location",
      "API Gateway: Request routing, rate limiting, auth",
      "Ride Service: Manages ride lifecycle",
      "Matching Service: Matches riders with optimal drivers",
      "Location Service: Ingests and indexes driver locations",
      "Pricing Service: Calculates fares and surge pricing",
      "Map Service: Integration with Google Maps/OSM",
      "Payment Service: Handles payments via Stripe/Braintree",
      "Notification Service: Push notifications, SMS",
      "Analytics: Demand prediction, driver positioning",
    ],
    dataModel: [
      "Rides: { rideId, riderId, driverId, status, pickupLoc, dropoffLoc, fare, startTime, endTime }",
      "Drivers: { driverId, name, vehicleInfo, rating, isOnline, currentLocation, currentRideId }",
      "Riders: { riderId, name, paymentMethods, rating, homeAddress, workAddress }",
      "Locations: { driverId, lat, lng, timestamp, geohash } - Time-series data",
      "Geospatial Index: Redis GEO or PostGIS for nearby queries",
      "Pricing: { regionId, baseRate, perMile, perMinute, surgeMultiplier }",
    ],
    apiDesign: [
      "POST /api/v1/rides/estimate - Get fare estimate: { pickup, dropoff, rideType }",
      "POST /api/v1/rides - Request ride: { pickup, dropoff, rideType, paymentMethod }",
      "PUT /api/v1/rides/{id}/accept - Driver accepts ride",
      "PUT /api/v1/rides/{id}/start - Start ride",
      "PUT /api/v1/rides/{id}/complete - Complete ride",
      "PUT /api/v1/drivers/location - Update driver location",
      "GET /api/v1/rides/{id}/track - Get real-time ride location (WebSocket)",
    ],
    scalability: [
      "Geospatial Sharding: Partition data by city/region",
      "Location Streaming: Kafka for high-throughput location updates",
      "Caching: Redis for driver locations with TTL for stale data cleanup",
      "Read Replicas: Multiple replicas for location queries",
      "Regional Deployment: Deploy services in each major city",
      "Load Shedding: Graceful degradation during extreme peaks",
    ],
    tradeoffs: [
      "Matching Speed vs Optimality: Faster matching vs finding best driver",
      "Location Precision: More frequent updates vs battery/bandwidth cost",
      "Consistency: Eventual consistency for non-critical data",
      "Surge Pricing: Revenue vs user experience",
      "Driver Assignment: Nearest driver vs best overall experience",
    ],
  },
  discussionPoints: [
    "How would you efficiently find the nearest available drivers?",
    "How would you handle the case where multiple riders request the same driver?",
    "How would you implement surge pricing based on supply and demand?",
    "How would you handle network issues during a ride?",
    "How would you predict driver demand in different areas?",
    "How would you ensure fair driver earnings while optimizing rider wait times?",
  ],
}
