/**
 * Data Engineering Level 11, Module 11.3 — Data Quality for AI.
 *
 * Training-data curation taught as the funnel it is, shaped after NVIDIA's NeMo Curator stage
 * order (extract, language ID, heuristic filters, dedup, quality classifier, PII redaction,
 * benchmark decontamination). Three stages of that funnel are pinned as three lessons because
 * each one grades a different SQL muscle and none of them can share a device: 11.3.1 dedups a
 * crawled corpus by exact content hash (the ROW_NUMBER keep-one with a composite tiebreaker that
 * research finding 1 calls the single most-cited SQL interview task, here wearing an AI costume),
 * 11.3.2 drives a redact-or-drop decision off a two-detector PII scan table and finds what one
 * detector misses, and 11.3.3 monitors per-stage acceptance rates and catches the night a stage
 * silently started eating the corpus while every status stayed green.
 *
 * Devices: single-file SELECTs over simulated curation artifacts named after the real thing
 * (`web_documents`, `pii_scan_results`, `corpus_docs`, `curation_runs`), plus one workspace script
 * that materializes the deduplicated corpus and has to survive being run twice. Vendors (NeMo
 * Curator, Presidio, MinHash/LSH) are named in prose only; the seed tables stay generic per the
 * vendor-churn rule.
 *
 * Deliberate deviations from CURRICULUM-MAP.md, each also flagged at its point of use below:
 *  - 11.3.3's live demo pivots acceptance by stage across ALL THREE runs rather than showing "the
 *    latest run's funnel in stage order". The map's demo is byte for byte the answer to 11.3.3's
 *    apply, so shipping it would hand the graded query away before the learner attempts it. The
 *    pivot is a different query shape and it makes the collapse more visible, not less.
 *  - 11.3.1's corpus is deliberately duplicate-dense (6 of 17 rows are copies, 35.3%, against the
 *    20-30% the research reports for real web crawls). At 25% a 17-row sample yields hash groups
 *    too small for the composite tiebreaker or the 3-plus-copies drill to be load-bearing. The
 *    corpus total is 17 rather than a round 16 so that 6/17 is NOT a terminating decimal. At 15
 *    rows the rate was exactly 40 and at 16 it would be exactly 37.5, and an integral or
 *    half-integral rate is reproduced by the very mistakes drill 1 exists to reject: integer
 *    division (the trap its second hint names), a missing ROUND, and ROUND to 0 places. At 35.3
 *    all three are rejected.
 *  - 11.3.2's `pii_scan_results` puts one SSN behind the NER detector only, and one EMAIL behind
 *    BOTH detectors. Without the first, a learner can grade green filtering `detector = 'regex'`;
 *    without the second, the blind-spot anti-join reduces to "every NER row".
 *  - 11.3.1's second drill filters on 3-or-more COPIES rather than the map's "3+ crawls". Filtering
 *    on distinct crawl dates leaves a one-row answer and hides the distinction the drill teaches,
 *    that a hash captured three times can span only two crawl days; the drill returns both counts
 *    side by side so the difference is the lesson.
 *  - 11.3.3's first drill measures survival from stage 2's input rather than the map's "end-to-end
 *    survival of the earliest run". Measured from stage 1, `MAX(docs_in)` and `MIN(docs_out)` land
 *    on exactly the first and last stages because the seeded funnel is monotonically decreasing, so
 *    a plain MIN/MAX pair grades green and the pin-a-row-to-a-column pattern the drill teaches is
 *    never exercised. Starting at stage 2 makes `MAX(docs_in)` return stage 1's number and fail,
 *    and the post-extraction rate is the one a curation owner actually watches.
 *  - 11.3.3's `curation_runs` plants a SECOND acceptance drop (lang_id, 83.5 to 62.0 on the middle
 *    run) plus a 15.7-point drop that must NOT be reported. One anomaly makes a one-row expected
 *    set that a hardcoded stage name reproduces, and with no near-miss the 20-point threshold is
 *    decoration.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and the
 * workspace reference was executed against its own assertions including the idempotency double-run.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable; practice
 * never ships a referenceSolution.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"
import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 11.3.1 seeds — the post-extract corpus table NeMo Curator dedups, one row per crawled
// document. Four content hashes repeat across different URLs and crawl dates, and the repeats are
// engineered so that every part of the keep rule is load-bearing:
//   '3f1c9a7d55b0e28a' x3  the earliest copy (doc_014) has the LARGEST doc_id in its group, so
//                          ordering by doc_id alone picks the wrong survivor
//   '8b24e6c0119fa7d3' x3  two copies share the earliest crawl_dt, so the doc_id tiebreaker is the
//                          only thing that decides between doc_002 and doc_011
//   'c05e71ab3d9f4820' x2  the smallest doc_id (doc_005) is NOT the earliest crawl, so ordering by
//                          crawl_dt is load-bearing in the other direction
//   'd7a3f0928c1b6e45' x2  the same forum thread reachable at two URLs, the ordinary case
// Byte-identical content necessarily shares a word_count, which is why the duplicates carry the
// same number: an exact-hash match means the bytes are the same, not merely similar.
//
// doc_016 and doc_017 carry hashes nobody else does. They exist only to move the corpus to 17 rows
// with 11 distinct hashes, which is what makes drill 1's duplicate rate 35.3 rather than a value an
// integer division or a missing ROUND would also produce. They touch no hash group above.
//
// Rows are listed in CRAWL order, not doc_id order, and inside the tied pair doc_011 is listed
// AHEAD of doc_002 deliberately. sql.js resolves a ROW_NUMBER tie by table scan order, so a
// learner who writes `ORDER BY crawl_dt` without the doc_id tiebreaker keeps doc_011 and fails.
// Listed in doc_id order the engine's arbitrary choice would happen to be the right one and the
// tiebreaker half of the keep rule would grade green while missing.
// ---------------------------------------------------------------------------

const WEB_DOCUMENTS_SEED = `CREATE TABLE web_documents (
  doc_id         TEXT,
  url            TEXT,
  content_sha256 TEXT,     -- first 16 hex chars of the document's content hash
  word_count     INTEGER,  -- byte-identical copies necessarily share a word count
  crawl_dt       TEXT      -- YYYY-MM-DD, the crawl that captured this copy
);
INSERT INTO web_documents (doc_id, url, content_sha256, word_count, crawl_dt) VALUES
  ('doc_001', 'https://research.example.edu/papers/vectors',      '1a4d7e02b93c58f6', 4120, '2026-01-03'),
  ('doc_014', 'https://news.example.com/ai-policy',               '3f1c9a7d55b0e28a', 1970, '2026-01-05'),
  ('doc_012', 'https://scrape.example.co/spark-tuning',           'c05e71ab3d9f4820', 3310, '2026-01-09'),
  ('doc_011', 'https://mirror.example.org/parquet-guide',         '8b24e6c0119fa7d3', 2380, '2026-01-18'),
  ('doc_002', 'https://blog.example.com/parquet-guide',           '8b24e6c0119fa7d3', 2380, '2026-01-18'),
  ('doc_006', 'https://news.example.com/quarterly-earnings',      '62f8d1c4470ae9b3',  880, '2026-01-27'),
  ('doc_005', 'https://docs.example.io/spark-tuning',             'c05e71ab3d9f4820', 3310, '2026-02-02'),
  ('doc_008', 'https://wiki.example.org/wiki/Data_lake',          '4e90ba61f2d8c073', 5450, '2026-02-06'),
  ('doc_003', 'https://mirror.example.org/ai-policy',             '3f1c9a7d55b0e28a', 1970, '2026-02-11'),
  ('doc_016', 'https://standards.example.org/spec/json-lines',    '9e0c4b7a2f38d156', 2960, '2026-02-15'),
  ('doc_007', 'https://cdn.example.net/cache/parquet-guide',      '8b24e6c0119fa7d3', 2380, '2026-02-20'),
  ('doc_013', 'https://journal.example.edu/issue/44/etl-history', 'ab182f6c4d70e935', 7240, '2026-02-25'),
  ('doc_009', 'https://aggregator.example.net/p/ai-policy',       '3f1c9a7d55b0e28a', 1970, '2026-03-02'),
  ('doc_017', 'https://blog.example.dev/posts/orc-vs-parquet',    '5c8a3e14d6b09f27', 1840, '2026-03-05'),
  ('doc_010', 'https://help.example.com/kb/billing',              '77c3e5d089ab146f',  510, '2026-03-09'),
  ('doc_004', 'https://forum.example.com/thread/9912',            'd7a3f0928c1b6e45',  640, '2026-03-14'),
  ('doc_015', 'https://forum.example.com/thread/9912?page=1',     'd7a3f0928c1b6e45',  640, '2026-03-20');`

// The workspace practice writes into a sink that already exists and starts empty, exactly like the
// materialized dedup table a real curation job writes. It carries NO uniqueness constraint on
// purpose: a naive append-only script must be allowed to actually duplicate on the second run so
// the idempotency check is the thing that catches it, rather than a constraint error the learner
// never has to reason about.
const WEB_DOCUMENTS_DEDUP_SEED = `${WEB_DOCUMENTS_SEED}

CREATE TABLE web_documents_dedup (
  doc_id         TEXT,
  url            TEXT,
  content_sha256 TEXT,
  word_count     INTEGER,
  crawl_dt       TEXT
);`

// ---------------------------------------------------------------------------
// Lesson 11.3.1 — Deduplicating a Training Corpus with Hashes
// ---------------------------------------------------------------------------

const exactDedup: SqlLesson = {
  id: "de-l11-exact-dedup",
  title: "Deduplicating a Training Corpus with Hashes",
  summary:
    "Exact-hash dedup strips 20 to 30 percent of a crawled corpus, and the ROW_NUMBER keep rule is only safe once its tiebreaker is deterministic.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "exact-hash deduplication",
    "ROW_NUMBER with tiebreakers",
    "MinHash and LSH",
    "dedup at read vs materialized dedup",
    "window functions",
    "workspace scripts",
    "idempotency",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The first real stage of a training pipeline is throwing things away

**Exact deduplication removes the documents whose content is byte-for-byte identical, and the standard approach is three steps: hash each document's normalized content, group the rows by that hash, and keep exactly one row per group.** The hash is the easy part. Which copy survives is a rule you have to choose and then make deterministic, and that is what the rest of this lesson is about.

A training corpus starts as a crawl, and a crawl of the open web is mostly the same pages over and over: mirrors, syndication feeds, CDN caches, aggregators republishing an article verbatim, and the same forum thread reachable at four different URLs. **Deduplication removes 20 to 30 percent of raw web data**, before any other quality work happens. Falcon's RefinedWeb pipeline took roughly 1 billion crawled pages down to 2.8 TB of clean text, and dedup did a large share of that reduction.

The reason this matters is not disk space. A document that appears four times is seen four times during training, which quietly reweights the corpus toward whatever happens to be mirrored the most. And a duplicate is one of the ways evaluation text sneaks into training data, which is how a benchmark score stops meaning anything.

## Exact dedup is a hash plus a keep rule

An exact duplicate is not "two documents that look alike". It is two documents whose **bytes are identical**, which the pipeline knows because the extract stage already stamped every document with a content hash. Two rows with the same \`content_sha256\` hold the same content, full stop, no matter how different their URLs look.

So exact dedup in SQL is two decisions and nothing else:

1. **Group by the hash.** That is the duplicate set.
2. **Pick one survivor per group.** That is the keep rule, and it is a business decision, not a technical one.

The keep rule needs to be **deterministic**, which means it must break every tie it can hit. "Keep the earliest crawl" is not enough on its own, because two mirrors can be captured on the same day, and if two rows tie on the ordering column then which one survives depends on how the engine happened to scan the table. That is why the canonical form carries a second ordering column:

\`\`\`sql
ROW_NUMBER() OVER (
  PARTITION BY content_sha256      -- the duplicate set
  ORDER BY crawl_dt, doc_id        -- the keep rule, plus the tiebreaker
) AS rn
\`\`\`

Then \`WHERE rn = 1\` keeps exactly one row per hash. Every row gets a number inside its own hash group, the lowest number goes to the earliest crawl, and \`doc_id\` settles the days where two copies arrived together.

**You have written this query before.** SQL Level 4 graded it on a customer staging table, keeping one latest row per email, and this course has graded the same keep-one twice since: Level 8's append-only bronze ranks redeliveries and keeps \`rn = 1\` in the read view, and Level 9's read-side dedup does it again over an at-least-once stream. It is the single most-cited SQL task in the interview corpus behind this course: windowed dedup with ROW_NUMBER and a composite tiebreaker. Nothing about it changes because the rows are now web pages destined for a model. That is the whole point of this level: the AI-era stage is the pattern you already own, pointed at a new table.

## Fuzzy and semantic dedup are the same idea, at higher cost

Exact hashing only catches byte-identical copies. Change one timestamp in a footer and the hash changes completely, so the two curation stages that follow relax the definition of "same":

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["stage", "what counts as a duplicate", "how it is computed", "cost"],
  "rows": [
    ["exact", "identical bytes", "GROUP BY a content hash, keep one", "one pass, cheap enough to always run"],
    ["fuzzy", "mostly the same words", "MinHash signatures, LSH buckets, then Jaccard overlap inside a bucket", "many hashes per document plus a bucketed comparison"],
    ["semantic", "the same meaning in different words", "embed every document, cluster the vectors, keep one per cluster", "an embedding call per document plus a clustering pass"]
  ],
  "highlightCols": ["stage"],
  "caption": "Three definitions of duplicate at increasing cost. Every pipeline runs exact dedup; fuzzy is common; semantic is a budget decision."
}
\`\`\`

Fuzzy dedup (MinHash plus LSH plus a Jaccard threshold) is the workhorse of the three: MinHash turns each document into a small signature, LSH puts similar signatures in the same bucket so you never compare every pair, and Jaccard overlap makes the final call inside a bucket. None of that is expressible in a graded SQL exercise, and it does not need to be. What an interviewer wants to hear is the ladder: exact first because it is nearly free, fuzzy next because near-duplicates are the bulk of the remaining waste, semantic only if the corpus and the budget justify it.

## Materialized dedup versus dedup at read

Level 9 already made you choose between absorbing duplicates at the write and absorbing them at the read, and Level 8 graded the read-side half of it directly, so you know both sides of this tradeoff. What curation adds is a reason the choice is not close: **read amplification**. A training job scans the corpus tens of times, so materializing the survivors into their own table means paying the window function once at build time instead of paying it on every scan. Dedup at read would charge that cost to every reader, forever, on a table whose contents stop changing the moment the crawl is processed.

So curation pipelines materialize. The practice below writes exactly that table, and it has to survive being run twice, which is the part that catches people: a dedup job that duplicates its own output on a rerun is a joke that writes itself.

**Common mistake:** deduplicating on the URL instead of on the content hash. The URL is the one thing every mirror changes. \`https://blog.example.com/parquet-guide\` and \`https://cdn.example.net/cache/parquet-guide\` are different strings holding the same bytes, and a URL-keyed dedup keeps both while a hash-keyed dedup keeps one.

**Interview nuance:** when you write the ROW_NUMBER, say the tiebreaker out loud. "I partition by the content hash and order by crawl date, then doc_id, so the result is deterministic even when two copies land on the same day" is the sentence that separates someone who has run this in production from someone who has seen it on a slide. Then add where the output goes, materialized table or view, and why.

> **On a real platform this differs.** Here the corpus is 17 rows in SQLite and the hash is a column somebody already filled in. NVIDIA's NeMo Curator runs this stage over JSONL or Parquet shards on object storage with the hashing done in the extract stage, and at that scale the dedup is distributed: hash, shuffle rows that share a hash to the same worker, keep one per group. Spark's \`dropDuplicates\` makes the first decision, group by the hash, and skips the second: it keeps whichever copy the engine happened to hold, and you get no say. That is why production jobs write the \`row_number\` window over a Delta table instead, exactly as you did here. Of the two it is the only one that lets you name the keep rule.`,
    demoSeedSql: WEB_DOCUMENTS_SEED,
    demoCode: `-- Every content hash that shows up more than once, with how many copies the crawl captured and
-- the window of dates they arrived over. These four groups are what the dedup stage collapses.
SELECT content_sha256,
       COUNT(*) AS copies,
       COUNT(DISTINCT crawl_dt) AS crawl_days,
       MIN(crawl_dt) AS first_crawled,
       MAX(crawl_dt) AS last_crawled
FROM web_documents
GROUP BY content_sha256
HAVING COUNT(*) > 1
ORDER BY copies DESC, content_sha256;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l11-exact-dedup-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the surviving document for each content hash, as \`(doc_id, content_sha256, crawl_dt)\`, sorted by \`doc_id\`, over \`web_documents(doc_id, url, content_sha256, word_count, crawl_dt)\`.

The survivor is the copy with the earliest \`crawl_dt\`, and when two copies share that date the lower \`doc_id\` wins. Return exactly one row per \`content_sha256\`.`,
    starterCode: `-- One survivor per content hash: earliest crawl, doc_id breaks the tie.
WITH ranked AS (
  SELECT doc_id, content_sha256, crawl_dt
         -- number the copies inside each hash group here
  FROM web_documents
)
SELECT doc_id, content_sha256, crawl_dt
FROM ranked
;`,
    hints: [
      "`PARTITION BY content_sha256` is what makes the numbering restart inside each duplicate set.",
      "`ORDER BY crawl_dt, doc_id` inside the window puts the earliest copy first and lets `doc_id` settle a shared date.",
      "`WHERE rn = 1` in the outer query keeps the survivor. A window function cannot be filtered in the same SELECT that computes it, which is why the ranking lives in a CTE.",
    ],
    referenceSolution: `WITH ranked AS (
  SELECT doc_id, content_sha256, crawl_dt,
         ROW_NUMBER() OVER (
           PARTITION BY content_sha256
           ORDER BY crawl_dt, doc_id
         ) AS rn
  FROM web_documents
)
SELECT doc_id, content_sha256, crawl_dt
FROM ranked
WHERE rn = 1
ORDER BY doc_id;`,
    singleFile: {
      seedSql: WEB_DOCUMENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["doc_id", "content_sha256", "crawl_dt"],
        rows: [
          ["doc_001", "1a4d7e02b93c58f6", "2026-01-03"],
          ["doc_002", "8b24e6c0119fa7d3", "2026-01-18"],
          ["doc_004", "d7a3f0928c1b6e45", "2026-03-14"],
          ["doc_006", "62f8d1c4470ae9b3", "2026-01-27"],
          ["doc_008", "4e90ba61f2d8c073", "2026-02-06"],
          ["doc_010", "77c3e5d089ab146f", "2026-03-09"],
          ["doc_012", "c05e71ab3d9f4820", "2026-01-09"],
          ["doc_013", "ab182f6c4d70e935", "2026-02-25"],
          ["doc_014", "3f1c9a7d55b0e28a", "2026-01-05"],
          ["doc_016", "9e0c4b7a2f38d156", "2026-02-15"],
          ["doc_017", "5c8a3e14d6b09f27", "2026-03-05"],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l11-exact-dedup-practice",
    prompt: `Write a script that fills \`web_documents_dedup\` with exactly one row per \`content_sha256\`, using the same keep rule as the apply: earliest \`crawl_dt\` wins, and the lower \`doc_id\` breaks a shared date.

\`web_documents_dedup\` already exists with the same five columns as \`web_documents\` and starts empty. Carry the survivor's \`url\` and \`word_count\` across unchanged, and leave \`web_documents\` itself untouched.

The curation job reruns whenever the week's crawl is re-processed, so your script is graded twice against the same corpus. After the second run \`web_documents_dedup\` must still hold exactly one row per content hash.`,
    starterCode: `-- Materialize the deduplicated corpus into web_documents_dedup.
-- The job reruns on the same corpus, so think about what the sink looks like the second time.

`,
    hints: [
      "Reuse the apply's ranking: a `ROW_NUMBER() OVER (PARTITION BY content_sha256 ORDER BY crawl_dt, doc_id)` subquery filtered to `rn = 1` is the row set you insert.",
      "`INSERT INTO web_documents_dedup (...) SELECT ...` writes the survivors. Select all five columns so `url` and `word_count` travel with the row.",
      "A bare INSERT is correct on the first run and wrong on the second, because the same nine survivors land again. Clear the sink first with `DELETE FROM web_documents_dedup;` so the script describes the end state rather than adding to it. That is the delete-and-insert idempotency shape Level 8 graded, scoped here to the whole table because the whole table is rebuilt.",
    ],
    seedSql: WEB_DOCUMENTS_DEDUP_SEED,
    checkIdempotency: true,
    // The sink is fully rebuilt on every run, so nothing here legitimately grows: naming it
    // explicitly keeps the double-run comparison on the graded table even if a learner leaves a
    // scratch table behind.
    idempotencyTables: ["web_documents_dedup"],
    assertions: [
      {
        suite: "dedup",
        name: "web_documents_dedup holds exactly one row per content hash",
        sql: `SELECT content_sha256
FROM web_documents_dedup
GROUP BY content_sha256
HAVING COUNT(*) > 1`,
      },
      {
        suite: "dedup",
        name: "every content hash in the corpus survived, and nothing was invented",
        sql: `SELECT * FROM (
  SELECT DISTINCT content_sha256 FROM web_documents
  EXCEPT
  SELECT content_sha256 FROM web_documents_dedup
)
UNION ALL
SELECT * FROM (
  SELECT content_sha256 FROM web_documents_dedup
  EXCEPT
  SELECT DISTINCT content_sha256 FROM web_documents
)`,
      },
      {
        suite: "dedup",
        name: "the survivor is the earliest crawl, with doc_id breaking a shared date",
        isHidden: true,
        sql: `WITH expected(doc_id, content_sha256, crawl_dt) AS (
  VALUES ('doc_001', '1a4d7e02b93c58f6', '2026-01-03'),
         ('doc_002', '8b24e6c0119fa7d3', '2026-01-18'),
         ('doc_004', 'd7a3f0928c1b6e45', '2026-03-14'),
         ('doc_006', '62f8d1c4470ae9b3', '2026-01-27'),
         ('doc_008', '4e90ba61f2d8c073', '2026-02-06'),
         ('doc_010', '77c3e5d089ab146f', '2026-03-09'),
         ('doc_012', 'c05e71ab3d9f4820', '2026-01-09'),
         ('doc_013', 'ab182f6c4d70e935', '2026-02-25'),
         ('doc_014', '3f1c9a7d55b0e28a', '2026-01-05'),
         ('doc_016', '9e0c4b7a2f38d156', '2026-02-15'),
         ('doc_017', '5c8a3e14d6b09f27', '2026-03-05')
)
SELECT * FROM (
  SELECT doc_id, content_sha256, crawl_dt FROM web_documents_dedup
  EXCEPT
  SELECT * FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT * FROM expected
  EXCEPT
  SELECT doc_id, content_sha256, crawl_dt FROM web_documents_dedup
)`,
      },
      {
        suite: "dedup",
        name: "every surviving row kept its own url and word_count",
        isHidden: true,
        sql: `SELECT d.doc_id
FROM web_documents_dedup d
LEFT JOIN web_documents w
  ON w.doc_id = d.doc_id
 AND w.url = d.url
 AND w.content_sha256 = d.content_sha256
 AND w.word_count = d.word_count
 AND w.crawl_dt = d.crawl_dt
WHERE w.doc_id IS NULL`,
      },
      {
        suite: "dedup",
        name: "the raw corpus was left untouched",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM web_documents) <> 17`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l11-exact-dedup-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns how much of the corpus is duplicate content, as \`(total_docs, unique_hashes, duplicate_pct)\`, over \`web_documents\`.

\`duplicate_pct\` is the share of rows the dedup stage would remove, rounded to 1 decimal. Alias every column exactly.`,
      starterCode: `-- How much would exact dedup remove from this crawl?
SELECT
FROM web_documents;`,
      hints: [
        "`COUNT(*)` is every crawled row and `COUNT(DISTINCT content_sha256)` is how many survive.",
        "The removed rows are the difference between those two. Multiply by 100.0 before dividing so the division is not integer division.",
      ],
      referenceSolution: `SELECT COUNT(*) AS total_docs,
       COUNT(DISTINCT content_sha256) AS unique_hashes,
       ROUND(100.0 * (COUNT(*) - COUNT(DISTINCT content_sha256)) / COUNT(*), 1) AS duplicate_pct
FROM web_documents;`,
      singleFile: {
        seedSql: WEB_DOCUMENTS_SEED,
        assertColumnNames: true,
        expected: {
          columns: ["total_docs", "unique_hashes", "duplicate_pct"],
          rows: [[17, 11, 35.3]],
        },
      },
    },
    // Deviation from the map's "hash groups appearing in 3+ crawls": the filter counts copies, and
    // both counts ship in the output, so the 3-copies-over-2-days group is the drill's whole point.
    {
      id: "de-l11-exact-dedup-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the content hashes the crawl captured 3 or more times, as \`(content_sha256, copies, crawl_days)\`, most copies first and then by hash, over \`web_documents\`.

\`copies\` is how many rows carry that hash and \`crawl_days\` is how many distinct \`crawl_dt\` values they arrived on. Alias every column exactly.`,
      starterCode: `-- The most heavily mirrored content in the crawl.
SELECT content_sha256
FROM web_documents
GROUP BY content_sha256
;`,
      hints: [
        "`HAVING COUNT(*) >= 3` filters the groups after aggregation. A `WHERE` clause cannot see a count.",
        "`crawl_days` is `COUNT(DISTINCT crawl_dt)`, which is not the same number as `copies` when two mirrors were captured on the same day.",
      ],
      referenceSolution: `SELECT content_sha256,
       COUNT(*) AS copies,
       COUNT(DISTINCT crawl_dt) AS crawl_days
FROM web_documents
GROUP BY content_sha256
HAVING COUNT(*) >= 3
ORDER BY copies DESC, content_sha256;`,
      singleFile: {
        seedSql: WEB_DOCUMENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["content_sha256", "copies", "crawl_days"],
          rows: [
            ["3f1c9a7d55b0e28a", 3, 3],
            ["8b24e6c0119fa7d3", 3, 2],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 11.3.2 seeds — a Presidio-style scan-output table (vendor named in prose only) plus the
// corpus it was run over. A row exists only where a detector found something, which is what makes
// the clean-document drill a genuine anti-join rather than a filter.
//
// The planted cases, each one load-bearing:
//   doc_104  EMAIL found by BOTH detectors, so the blind-spot anti-join has to match on
//            (doc_id, entity_type) rather than just returning every NER row
//   doc_105  SSN found by NER ONLY, so a disposition query filtered to `detector = 'regex'`
//            misses a document that must be dropped, and it is the SMALLEST total in the set so
//            "large totals get dropped" is not a shortcut either
//   doc_102  the largest total_matches in the set and only a redact, so the sort order carries no
//            information about the disposition
//   doc_109, doc_110, doc_111  present in corpus_docs with no scan rows at all
// ---------------------------------------------------------------------------

const PII_SCAN_SEED = `CREATE TABLE corpus_docs (
  doc_id     TEXT,
  word_count INTEGER
);
INSERT INTO corpus_docs (doc_id, word_count) VALUES
  ('doc_101', 3120),
  ('doc_102',  890),
  ('doc_103', 5640),
  ('doc_104', 2210),
  ('doc_105',  760),
  ('doc_106', 4480),
  ('doc_107', 1530),
  ('doc_108', 6910),
  ('doc_109', 2740),
  ('doc_110',  980),
  ('doc_111', 8350);

CREATE TABLE pii_scan_results (
  doc_id      TEXT,
  detector    TEXT,     -- regex | ner, the two detectors the stage runs in series
  entity_type TEXT,     -- EMAIL | PHONE | SSN | PERSON_NAME
  match_count INTEGER   -- spans this detector found of this type; a row exists only on a hit
);
INSERT INTO pii_scan_results (doc_id, detector, entity_type, match_count) VALUES
  ('doc_101', 'regex', 'SSN',          2),
  ('doc_101', 'regex', 'EMAIL',        5),
  ('doc_101', 'ner',   'PERSON_NAME',  7),
  ('doc_102', 'regex', 'EMAIL',        9),
  ('doc_102', 'ner',   'PERSON_NAME', 12),
  ('doc_103', 'regex', 'EMAIL',        3),
  ('doc_103', 'ner',   'PHONE',        4),
  ('doc_103', 'ner',   'PERSON_NAME',  6),
  ('doc_104', 'regex', 'EMAIL',        4),
  ('doc_104', 'ner',   'EMAIL',        4),
  ('doc_104', 'ner',   'PERSON_NAME',  2),
  ('doc_105', 'regex', 'PHONE',        2),
  ('doc_105', 'ner',   'SSN',          1),
  ('doc_106', 'regex', 'PHONE',        8),
  ('doc_107', 'regex', 'SSN',          1),
  ('doc_107', 'regex', 'EMAIL',        1),
  ('doc_107', 'ner',   'PERSON_NAME',  3),
  ('doc_108', 'ner',   'PERSON_NAME',  4);`

// ---------------------------------------------------------------------------
// Lesson 11.3.2 — PII Scrubbing Funnels Before Training
// ---------------------------------------------------------------------------

const piiScrubbing: SqlLesson = {
  id: "de-l11-pii-scrubbing",
  title: "PII Scrubbing Funnels Before Training",
  summary:
    "Why a PII scrubbing stage runs regex and NER in series, and how to drive the redact-or-drop call from severity rather than from volume.",
  estimatedMinutes: 27,
  difficulty: "medium",
  skills: [
    "PII redaction funnels",
    "regex vs NER detectors",
    "severity-based disposition",
    "benchmark decontamination",
    "anti-join blind-spot detection",
    "CASE",
    "conditional aggregation",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Two detectors, because one kind of PII has a shape and the other does not

The PII stage of a curation pipeline is the point where somebody's phone number stops being a data-quality curiosity and starts being a legal problem, because a model that memorized it will happily repeat it. NVIDIA's NeMo Curator runs the stage as **regex plus NER in series**, and the reason there are two detectors is the reason the whole stage is interesting:

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["detector", "what it is good at", "why", "typical entity types"],
  "rows": [
    ["regex", "structured PII", "the value has a fixed shape you can write down as a pattern", "SSN, credit card, email, most phone formats"],
    ["ner", "unstructured PII", "the value has no shape, only a role in a sentence", "person name, organization, address, location"],
    ["both, in series", "the union of the two", "each one is blind to what the other sees", "the full entity list, with overlap on the shaped types"]
  ],
  "highlightCols": ["detector"],
  "caption": "The two-detector design in one table. Regex cannot recognize a name; a model can, and a model is also expensive and occasionally wrong about a number it could have matched exactly."
}
\`\`\`

A social security number is \`123-45-6789\`. That is a pattern, and a regex matches it exactly, every time, for free. A person's name is "Dana Whitfield", which is not a pattern at all: it is a sequence of tokens that a named-entity-recognition model classifies from context. No regex catches it, and no amount of regex tuning ever will.

They overlap in the middle. A good NER model will also flag an email or an SSN, because those entity types are in its label set too. That overlap is worth having, and the gaps in it are worth querying, which is what the practice does.

## Data engineers own the funnel even when a machine-learning team owns the models

The detectors themselves are somebody else's problem. The pipeline around them is yours. What a data engineer owns here is the funnel:

1. **Scan.** Each detector runs over each document and writes a row per entity type it found, with a count. That table is the artifact you query, and it is the seed below.
2. **Decide.** Every scanned document gets a **disposition**, and the disposition comes from severity, not from volume.
3. **Act.** Redacted documents continue down the funnel with their spans masked. Dropped documents leave the corpus entirely and their doc_ids go on a list somebody can audit.

Severity is the part with real judgment in it, and the industry line is roughly this:

- A **social security number or a credit card number anywhere in the document means drop the whole document.** These values are unambiguously sensitive, redacting them still leaves the surrounding context that identified the person, and a corpus is cheap compared to that risk.
- **Emails and person names mean redact and keep.** They are common enough that dropping every document containing one would take a large bite out of the corpus for very little safety gained.

Notice that this rule is about entity *type*, never about match *count*. A document with one SSN is dropped. A document with twenty person names is redacted and kept. Any query that ranks documents by total matches and drops the top of the list is implementing a rule nobody agreed to.

## The stage right after this one is why benchmarks lie

Decontamination follows PII redaction in the NeMo Curator order, and it deserves a sentence because it explains a headline you have read. Decontamination searches the training corpus for **n-gram overlap with published evaluation sets** and removes what it finds. Without it, the eval questions are sitting inside the training data, the model has effectively seen the answer key, and "our model aced the benchmark" is a data bug rather than a result. It is the same failure mode as a leaked label in a machine-learning feature table, and it is data-engineering work: a join between two corpora on shingles of text.

**Common mistake:** treating the absence of a scan row as "the detector ran and found nothing" when it actually means "there is no hit here". A scan-results table only records hits, so a document that is genuinely clean has zero rows, not a row with a count of zero. That is why finding the clean documents is an anti-join against the corpus table and not a \`WHERE match_count = 0\`.

**Interview nuance:** the one-sentence version that lands is "regex catches structured PII like SSNs and emails, NER catches unstructured PII like names, and you run both because each is blind to the other's category." Follow it with the disposition rule, drop on the unambiguous identifiers and redact the rest, and you have said everything a junior is expected to know about this stage.

> **On a real platform this differs.** The table below is a scan output; the scan itself is a service. Microsoft Presidio is the common open-source implementation of exactly this two-detector design, and the managed clouds sell the same shape (Amazon Comprehend PII detection, Google Cloud DLP). Governance pressure is why this stage keeps getting more attention rather than less: Gartner projects 70 percent of organizations will have adopted modern data-quality solutions by 2027, driven substantially by AI data requirements. Whichever detector you run, the artifact it hands you is a table of hits, and the funnel over it is the query you just wrote.`,
    demoSeedSql: PII_SCAN_SEED,
    demoCode: `-- What each detector actually contributed. The zero in the regex column for PERSON_NAME is the
-- whole argument for running two detectors, and the EMAIL row shows where they overlap.
SELECT entity_type,
       SUM(CASE WHEN detector = 'regex' THEN match_count ELSE 0 END) AS regex_matches,
       SUM(CASE WHEN detector = 'ner'   THEN match_count ELSE 0 END) AS ner_matches,
       COUNT(DISTINCT doc_id) AS docs_flagged
FROM pii_scan_results
GROUP BY entity_type
ORDER BY entity_type;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l11-pii-scrubbing-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each scanned document's disposition, as \`(doc_id, total_matches, disposition)\`, most matches first and then by \`doc_id\`, over \`pii_scan_results(doc_id, detector, entity_type, match_count)\`.

\`total_matches\` is the document's summed \`match_count\` across every detector and entity type. \`disposition\` is \`'drop'\` when the document has any \`'SSN'\` match at all and \`'redact'\` otherwise. Alias every column exactly.`,
    starterCode: `-- One row per scanned document: how much PII it carries, and what happens to it.
SELECT doc_id
FROM pii_scan_results
GROUP BY doc_id
;`,
    hints: [
      "`SUM(match_count)` per `doc_id` is the total. The disposition needs a second aggregate over the same group.",
      "Conditional aggregation asks the severity question: `SUM(CASE WHEN entity_type = 'SSN' THEN 1 ELSE 0 END)` counts the SSN rows in the group, and the disposition is a CASE over whether that is above zero.",
      "Do not filter on `detector`. An SSN can be found by either detector, and one document in this corpus was flagged only by the NER model.",
    ],
    referenceSolution: `SELECT doc_id,
       SUM(match_count) AS total_matches,
       CASE WHEN SUM(CASE WHEN entity_type = 'SSN' THEN 1 ELSE 0 END) > 0
            THEN 'drop' ELSE 'redact' END AS disposition
FROM pii_scan_results
GROUP BY doc_id
ORDER BY total_matches DESC, doc_id;`,
    singleFile: {
      seedSql: PII_SCAN_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["doc_id", "total_matches", "disposition"],
        rows: [
          ["doc_102", 21, "redact"],
          ["doc_101", 14, "drop"],
          ["doc_103", 13, "redact"],
          ["doc_104", 10, "redact"],
          ["doc_106", 8, "redact"],
          ["doc_107", 5, "drop"],
          ["doc_108", 4, "redact"],
          ["doc_105", 3, "drop"],
        ],
      },
    },
  },
  practice: {
    id: "de-l11-pii-scrubbing-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the detector blind spots, as \`(doc_id, entity_type)\`, sorted by \`doc_id\` and then \`entity_type\`, over \`pii_scan_results\`.

A blind spot is an entity type the \`'ner'\` detector found in a document where the \`'regex'\` detector recorded no match of that same type in that same document. Return one row per blind spot.`,
    starterCode: `-- What the NER model found that the regex pass missed entirely.
SELECT n.doc_id, n.entity_type
FROM pii_scan_results n
WHERE n.detector = 'ner'
;`,
    hints: [
      "The blind-spot test is an anti-join, so `NOT EXISTS (SELECT 1 FROM pii_scan_results r WHERE r.detector = 'regex' AND ...)` is the shape.",
      "Match the correlated subquery on BOTH `doc_id` and `entity_type`. One document in this corpus had its email found by both detectors, and matching on `doc_id` alone would wrongly hide every other finding in that document.",
    ],
    singleFile: {
      seedSql: PII_SCAN_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["doc_id", "entity_type"],
        rows: [
          ["doc_101", "PERSON_NAME"],
          ["doc_102", "PERSON_NAME"],
          ["doc_103", "PERSON_NAME"],
          ["doc_103", "PHONE"],
          ["doc_104", "PERSON_NAME"],
          ["doc_105", "SSN"],
          ["doc_107", "PERSON_NAME"],
          ["doc_108", "PERSON_NAME"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l11-pii-scrubbing-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the total matches per entity type, as \`(entity_type, total_matches)\`, most matches first, over \`pii_scan_results\`.

Alias the summed column exactly \`total_matches\`.`,
      starterCode: `-- Which kind of PII dominates this corpus?
SELECT
FROM pii_scan_results;`,
      hints: [
        "Group by `entity_type` and sum `match_count` inside each group.",
        "`ORDER BY total_matches DESC` puts the most common entity type first.",
      ],
      referenceSolution: `SELECT entity_type, SUM(match_count) AS total_matches
FROM pii_scan_results
GROUP BY entity_type
ORDER BY total_matches DESC;`,
      singleFile: {
        seedSql: PII_SCAN_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["entity_type", "total_matches"],
          rows: [
            ["PERSON_NAME", 34],
            ["EMAIL", 26],
            ["PHONE", 14],
            ["SSN", 4],
          ],
        },
      },
    },
    {
      id: "de-l11-pii-scrubbing-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the documents neither detector flagged, as \`(doc_id, word_count)\`, longest document first, over \`corpus_docs(doc_id, word_count)\` and \`pii_scan_results\`.

A clean document is one that appears in \`corpus_docs\` with no row of any kind in \`pii_scan_results\`. Alias every column exactly.`,
      starterCode: `-- The documents that pass the PII stage untouched.
SELECT c.doc_id, c.word_count
FROM corpus_docs c
;`,
      hints: [
        "A scan-results row only exists on a hit, so a clean document is one with no rows at all. That is an anti-join against `corpus_docs`, not a filter on `match_count`.",
        "`WHERE NOT EXISTS (SELECT 1 FROM pii_scan_results p WHERE p.doc_id = c.doc_id)` keeps only the unmatched documents. A `LEFT JOIN ... WHERE p.doc_id IS NULL` reaches the same answer.",
      ],
      referenceSolution: `SELECT c.doc_id, c.word_count
FROM corpus_docs c
WHERE NOT EXISTS (
        SELECT 1 FROM pii_scan_results p WHERE p.doc_id = c.doc_id
      )
ORDER BY c.word_count DESC;`,
      singleFile: {
        seedSql: PII_SCAN_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["doc_id", "word_count"],
          rows: [
            ["doc_111", 8350],
            ["doc_109", 2740],
            ["doc_110", 980],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 11.3.3 seeds — a NeMo Curator run-log export: 3 weekly runs across the 7 stages, in the
// real stage order. Every run "succeeded"; the run log has no status column at all, which is the
// point of the lesson, because acceptance rate is the only signal that anything went wrong.
//
// The numbers echo reality (dedup removes about 25 percent every week) and plant three cases the
// practice has to separate:
//   2026-07-22 lang_id            83.5 -> 62.0   a real 21.5-point drop, must be reported
//   2026-07-22 heuristic_filter   79.7 -> 64.0   a 15.7-point drop, must NOT be reported
//   2026-07-29 quality_classifier 61.1 ->  8.9   the headline collapse, a fat-fingered threshold
// The lang_id and heuristic_filter rates both recover on 2026-07-29, so a query that looks at
// rises as well as drops returns extra rows and fails.
// ---------------------------------------------------------------------------

const CURATION_RUNS_SEED = `CREATE TABLE curation_runs (
  run_dt      TEXT,     -- YYYY-MM-DD, one full curation pass over that week's crawl
  stage       TEXT,     -- the curation stage name
  stage_order INTEGER,  -- 1..7, the order the stages run in
  docs_in     INTEGER,
  docs_out    INTEGER
);
INSERT INTO curation_runs (run_dt, stage, stage_order, docs_in, docs_out) VALUES
  ('2026-07-15', 'extract',            1, 1000000, 962000),
  ('2026-07-15', 'lang_id',            2,  962000, 803000),
  ('2026-07-15', 'heuristic_filter',   3,  803000, 640000),
  ('2026-07-15', 'dedup',              4,  640000, 480000),
  ('2026-07-15', 'quality_classifier', 5,  480000, 293000),
  ('2026-07-15', 'pii_redaction',      6,  293000, 290000),
  ('2026-07-15', 'decontamination',    7,  290000, 286000),
  ('2026-07-22', 'extract',            1, 1040000, 1000000),
  ('2026-07-22', 'lang_id',            2, 1000000, 620000),
  ('2026-07-22', 'heuristic_filter',   3,  620000, 397000),
  ('2026-07-22', 'dedup',              4,  397000, 298000),
  ('2026-07-22', 'quality_classifier', 5,  298000, 182000),
  ('2026-07-22', 'pii_redaction',      6,  182000, 180000),
  ('2026-07-22', 'decontamination',    7,  180000, 178000),
  ('2026-07-29', 'extract',            1, 1020000, 981000),
  ('2026-07-29', 'lang_id',            2,  981000, 822000),
  ('2026-07-29', 'heuristic_filter',   3,  822000, 656000),
  ('2026-07-29', 'dedup',              4,  656000, 492000),
  ('2026-07-29', 'quality_classifier', 5,  492000,  44000),
  ('2026-07-29', 'pii_redaction',      6,   44000,  43600),
  ('2026-07-29', 'decontamination',    7,   43600,  43000);`

// ---------------------------------------------------------------------------
// Lesson 11.3.3 — The Curation Funnel and Acceptance-Rate Monitoring
// ---------------------------------------------------------------------------

const curationFunnel: SqlLesson = {
  id: "de-l11-curation-funnel",
  title: "The Curation Funnel and Acceptance-Rate Monitoring",
  summary:
    "Read a seven-stage curation funnel as acceptance rates and catch the stage that silently ate the corpus while every job still reported success.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "curation stage order",
    "acceptance-rate monitoring",
    "funnel analysis",
    "silent failure detection",
    "day-over-day anomaly detection",
    "LAG",
    "window functions",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Seven stages, and every one of them is allowed to delete your data

The two previous lessons each took one stage of a curation pipeline. Here is the whole thing, in the order NVIDIA's NeMo Curator runs it, which is the reference architecture worth being able to recite:

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "extract", "note": "raw crawl to text, about 96% accepted" },
    { "label": "lang_id", "note": "keep the target languages, about 84%" },
    { "label": "heuristic_filter", "note": "word count, boilerplate, repetition, about 80%" },
    { "label": "dedup", "note": "exact then fuzzy, about 75%" },
    { "label": "quality_classifier", "note": "a model scores each doc, about 61%" },
    { "label": "pii_redaction", "note": "regex plus NER, about 99%" },
    { "label": "decontamination", "note": "remove eval-set overlap, about 99%" }
  ],
  "caption": "The curation funnel, with each stage's healthy acceptance rate. A little under 29 percent of the crawl survives end to end, and every percentage here is a thing that can silently move."
}
\`\`\`

Read it as a funnel, because that is what it is. A million extracted documents become fewer than three hundred thousand training documents, and the losses are intentional at every step. Which raises the operational question this lesson exists for: if every stage is supposed to delete data, how do you notice when one of them starts deleting the wrong amount?

## Acceptance rate is the health metric of a stage

Every stage has exactly one number that describes its behaviour, and it is not a runtime and not a row count:

\`\`\`sql
acceptance_pct = 100.0 * docs_out / docs_in
\`\`\`

A raw output count cannot tell you anything, because a stage that emitted fewer documents this week might simply have been handed fewer. The ratio is comparable across weeks of different sizes, which is exactly what makes it monitorable. Multiply by \`100.0\` rather than \`100\`, because \`docs_out / docs_in\` in integer arithmetic is 0 for every stage that accepts less than everything.

Healthy acceptance rates are remarkably stable week over week, and that stability is the whole basis of the monitor. Dedup removes about a quarter of what it is given, every single week, because the web does not suddenly stop mirroring things. When dedup accepts 95 percent one week, the crawl did not get cleaner, your hashing broke.

## The worst failure is a successful run

Level 10's observability module named the failure mode: **silent success**. A job that crashes gets a red status, a page, and somebody looking at it within minutes. A job that finishes cleanly while quietly destroying the corpus gets a green tick and nobody looks at it for a month, by which time you have trained on it.

The run log below has no status column at all, deliberately, because every one of these runs succeeded. The engine had nothing to complain about. Somebody edited the quality classifier's score threshold, fat-fingered a decimal, and the stage now rejects almost everything it sees. It reports success on every run, because rejecting documents is literally its job.

So the monitor cannot watch statuses. It has to watch the rates, and the comparison it makes is against **that stage's own recent history**, not against a global constant. Every stage has a different healthy rate, so a single threshold like "alert below 50 percent acceptance" would page you every week for the quality classifier at a perfectly normal 61 percent while missing a redaction stage that fell from 99 to 80.

\`LAG\` is the natural tool: partition by stage, order by run date, and each row can see what the same stage did last time.

\`\`\`sql
LAG(acceptance_pct) OVER (PARTITION BY stage ORDER BY run_dt) AS prior_pct
\`\`\`

Then the alert condition is a comparison between two columns of the same row, and the threshold is expressed in **percentage points**, not percent. A fall from 61 to 8.9 is a drop of 52.1 points. Calling it "an 85 percent decrease" is also true and much harder to reason about when you are setting the alerting threshold at three in the morning.

**Common mistake:** alerting on the change in \`docs_out\`. Output counts move for a completely innocent reason all the time, which is that the stage above moved. When the language filter has a bad week, every stage below it emits fewer documents and every one of them fires. The acceptance rate is immune to that, because it divides the stage's output by its own input, so a stage whose upstream shrank keeps reporting the same healthy ratio. That is exactly what happens on the middle run in the seed below.

**Interview nuance:** "how would you know your pipeline silently broke" is a stock reliability question, and the strong answer has three beats. Name the metric that is invariant to volume (a rate, not a count). Say what you compare it against (the same stage's own trailing history, not a global constant). Say what the threshold is expressed in (percentage points, with a floor on the input volume so a tiny run does not produce a noisy ratio). The pattern transfers directly: the same LAG-against-your-own-history shape is how you monitor conversion funnels, null rates, and job durations.

> **On a real platform this differs.** This run log is 21 rows you can read at a glance. A real curation pipeline emits these counters per stage per shard into a metrics store or a run-log table in the warehouse, and the monitor is a scheduled query with the alert wired to a channel rather than a query you run by hand. Some teams go further and put a data test on the rate itself so a bad run blocks the publish instead of merely reporting itself, which is the write-audit-publish gate from SQL Level 5 pointed at a percentage. The shape of the query does not change.`,
    demoSeedSql: CURATION_RUNS_SEED,
    // Deviation from the map, which asked for "the latest run's funnel in stage order": that is
    // byte for byte the answer to this lesson's apply. The pivot across all three runs is a
    // different query shape and shows the collapse against its own history, which is the point.
    demoCode: `-- Every stage's acceptance rate across the three weekly runs, side by side. Six of the seven
-- rows barely move, which is what makes the seventh readable at a glance.
SELECT stage,
       MAX(CASE WHEN run_dt = '2026-07-15' THEN ROUND(100.0 * docs_out / docs_in, 1) END) AS pct_jul_15,
       MAX(CASE WHEN run_dt = '2026-07-22' THEN ROUND(100.0 * docs_out / docs_in, 1) END) AS pct_jul_22,
       MAX(CASE WHEN run_dt = '2026-07-29' THEN ROUND(100.0 * docs_out / docs_in, 1) END) AS pct_jul_29
FROM curation_runs
GROUP BY stage, stage_order
ORDER BY stage_order;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l11-curation-funnel-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the most recent run's funnel, as \`(stage, docs_in, docs_out, acceptance_pct)\`, in stage order, over \`curation_runs(run_dt, stage, stage_order, docs_in, docs_out)\`.

\`acceptance_pct\` is \`docs_out\` as a percentage of \`docs_in\`, rounded to 1 decimal. Find the most recent \`run_dt\` from the table rather than typing a date. Alias every column exactly.`,
    starterCode: `-- The latest curation run, stage by stage, as a funnel.
SELECT stage, docs_in, docs_out
FROM curation_runs
;`,
    hints: [
      "`WHERE run_dt = (SELECT MAX(run_dt) FROM curation_runs)` keeps the latest run without hardcoding a date.",
      "`100.0 * docs_out / docs_in` forces real division. Writing `100 *` gives integer arithmetic and every rate collapses toward 0.",
      "`ORDER BY stage_order` is what makes the output read as a funnel. Ordering by `stage` alphabetically scrambles the pipeline.",
    ],
    referenceSolution: `SELECT stage,
       docs_in,
       docs_out,
       ROUND(100.0 * docs_out / docs_in, 1) AS acceptance_pct
FROM curation_runs
WHERE run_dt = (SELECT MAX(run_dt) FROM curation_runs)
ORDER BY stage_order;`,
    singleFile: {
      seedSql: CURATION_RUNS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["stage", "docs_in", "docs_out", "acceptance_pct"],
        rows: [
          ["extract", 1020000, 981000, 96.2],
          ["lang_id", 981000, 822000, 83.8],
          ["heuristic_filter", 822000, 656000, 79.8],
          ["dedup", 656000, 492000, 75],
          ["quality_classifier", 492000, 44000, 8.9],
          ["pii_redaction", 44000, 43600, 99.1],
          ["decontamination", 43600, 43000, 98.6],
        ],
      },
    },
  },
  practice: {
    id: "de-l11-curation-funnel-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every stage whose acceptance rate fell by more than 20 percentage points against that same stage's previous run, as \`(run_dt, stage, prior_pct, current_pct)\`, oldest run first and then in stage order, over \`curation_runs\`.

Both percentages are \`docs_out\` as a percentage of \`docs_in\`, rounded to 1 decimal. Compare each stage only against itself, and report only falls, never rises.`,
    starterCode: `-- Which stage silently started eating the corpus, and on which run?
SELECT run_dt, stage
FROM curation_runs
;`,
    hints: [],
    singleFile: {
      seedSql: CURATION_RUNS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["run_dt", "stage", "prior_pct", "current_pct"],
        rows: [
          ["2026-07-22", "lang_id", 83.5, 62],
          ["2026-07-29", "quality_classifier", 61.1, 8.9],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l11-curation-funnel-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the earliest run's survival rate measured from the language-ID stage onward, as \`(run_dt, docs_in, docs_out, survival_pct)\`, over \`curation_runs\`.

\`docs_in\` is what entered stage 2 and \`docs_out\` is what left stage 7, so extraction losses are excluded and the number describes only the curation stages themselves. \`survival_pct\` is the second as a percentage of the first, rounded to 1 decimal. Find the earliest \`run_dt\` from the table rather than typing a date. Alias every column exactly.`,
      starterCode: `-- Of everything that survived extraction, how much became training data?
SELECT run_dt
FROM curation_runs
WHERE run_dt = (SELECT MIN(run_dt) FROM curation_runs)
;`,
      hints: [
        "The two numbers live on different rows, so pull them into one row with conditional aggregation: `MAX(CASE WHEN stage_order = 2 THEN docs_in END)` and `MAX(CASE WHEN stage_order = 7 THEN docs_out END)`.",
        "`MAX(docs_in)` is not a shortcut for the first number. The largest `docs_in` in the run belongs to stage 1, which is exactly the stage this rate excludes, so the stage has to be pinned by `stage_order`.",
        "Group by `run_dt` so the whole run collapses to a single row, then divide, remembering the `100.0`.",
      ],
      referenceSolution: `SELECT run_dt,
       MAX(CASE WHEN stage_order = 2 THEN docs_in END) AS docs_in,
       MAX(CASE WHEN stage_order = 7 THEN docs_out END) AS docs_out,
       ROUND(100.0 * MAX(CASE WHEN stage_order = 7 THEN docs_out END)
                   / MAX(CASE WHEN stage_order = 2 THEN docs_in END), 1) AS survival_pct
FROM curation_runs
WHERE run_dt = (SELECT MIN(run_dt) FROM curation_runs)
GROUP BY run_dt;`,
      singleFile: {
        seedSql: CURATION_RUNS_SEED,
        assertColumnNames: true,
        expected: {
          columns: ["run_dt", "docs_in", "docs_out", "survival_pct"],
          rows: [["2026-07-15", 962000, 286000, 29.7]],
        },
      },
    },
    {
      id: "de-l11-curation-funnel-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the stage that lost the most documents in each run, as \`(run_dt, stage, docs_lost)\`, oldest run first, over \`curation_runs\`.

\`docs_lost\` is \`docs_in\` minus \`docs_out\`, and you want the single largest loser per \`run_dt\`. Alias every column exactly.`,
      starterCode: `-- The biggest single drop in each run, which is not the same stage every week.
SELECT run_dt, stage, docs_in - docs_out AS docs_lost
FROM curation_runs
;`,
      hints: [
        "Rank inside each run: `ROW_NUMBER() OVER (PARTITION BY run_dt ORDER BY docs_in - docs_out DESC)` in a CTE, then keep the rows numbered 1.",
        "A plain `MAX(docs_in - docs_out)` grouped by `run_dt` gives you the number but not the stage name, which is the part the question asks for.",
      ],
      referenceSolution: `WITH losses AS (
  SELECT run_dt,
         stage,
         docs_in - docs_out AS docs_lost,
         ROW_NUMBER() OVER (PARTITION BY run_dt ORDER BY docs_in - docs_out DESC) AS rn
  FROM curation_runs
)
SELECT run_dt, stage, docs_lost
FROM losses
WHERE rn = 1
ORDER BY run_dt;`,
      singleFile: {
        seedSql: CURATION_RUNS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["run_dt", "stage", "docs_lost"],
          rows: [
            ["2026-07-15", "quality_classifier", 187000],
            ["2026-07-22", "lang_id", 380000],
            ["2026-07-29", "quality_classifier", 448000],
          ],
        },
      },
    },
  ],
}

export const level11Module3: SqlModule = {
  id: "de-l11-ai-data-quality",
  title: "Module 11.1: Data Quality for AI",
  description:
    "Training-data curation as a funnel of graded SQL stages shaped after NVIDIA's NeMo Curator: exact-hash deduplication with the ROW_NUMBER keep-one every SQL interview asks for, a two-detector PII scrubbing funnel whose disposition comes from severity rather than volume, and per-stage acceptance-rate monitoring that catches the run where a classifier silently started eating the corpus while every job still reported success.",
  lessons: [exactDedup, piiScrubbing, curationFunnel],
}
