/**
 * Data Engineering Level 7 — Warehouses, Lakehouse & Dimensional Modeling.
 *
 * Level 6 taught the lake: files on object storage, columnar formats, partitioning, and the engines
 * that scan them. Level 7 is the systems the lake feeds. Module 7.1 goes inside an MPP warehouse
 * (nodes and slices, distribution and sort keys read off simulated table stats and query plans, and
 * the loading and billing models that decide what a query costs). Module 7.2 turns the dimensional
 * modeling that SQL levels 3 to 5 already teach into interview rehearsal and adds the one modeling
 * debate none of them covers, Kimball versus one big table. Module 7.3 is Iceberg: snapshots and
 * manifests queried as tables, merge semantics, time travel, and compaction. Module 7.4 is the
 * cross-cloud translation layer, the warehouse-versus-lakehouse decision, and what each platform
 * actually bills for.
 *
 * Split one file per module because four authors wrote them in parallel and a single 4,000 line
 * level file is not reviewable. Each module owns its own seed constants, exactly as `level6.ts`
 * scopes seeds per module, so a seed change can never silently move another module's expected set.
 *
 * Every single-file `expected` set here was GENERATED by running the reference SELECT through the
 * same self-hosted sql.js WASM the app ships, never hand-typed, and every workspace reference was
 * executed against its own hidden assertions (including the idempotency double-run). See
 * docs/data-engineering-curriculum/CURRICULUM-MAP.md for the lesson-by-lesson design.
 */
import type { SqlLevel } from "@/lib/tutorials/types"
import { level7Module1 } from "./module1"
import { level7Module2 } from "./module2"
import { level7Module3 } from "./module3"
import { level7Module4 } from "./module4"

export const sqlLevel7: SqlLevel = {
  id: 7,
  slug: "warehouses-lakehouse",
  title: "Level 7 — Warehouses, Lakehouse & Dimensional Modeling",
  tagline:
    "Go inside the systems the lake feeds: how a warehouse places and prices your data, how to answer the dimensional modeling questions interviews actually ask, and how Iceberg turns files into transactional tables.",
  defaultExecutionMode: "single-file",
  estimatedHours: 6,
  modules: [level7Module1, level7Module2, level7Module3, level7Module4],
}
