/**
 * Data Engineering curriculum Level 7, Module 7.1 — Inside the Cloud Warehouse.
 *
 * L6 taught the lake: files on object storage, a catalog over them, and an engine that
 * assigns splits at read time. This module goes inside the MPP warehouse the lake feeds,
 * where placement is decided at LOAD time instead: nodes and slices, distribution and sort
 * keys read off simulated table stats and query plans, and the loading and billing models
 * that decide what a query costs. Grounded in RESEARCH.md §3.5 (Redshift appears in 76% of
 * AWS-flavored loops and sort/dist-key reasoning is the archetypal question) and §3.1/§3.4
 * (the DEA-C01 cost-model phrasing, Athena's $5.00 per TB scanned with a 10 MB minimum).
 *
 * Device: the same one Level 6 proved. Every lesson teaches the concept in `teach`, then
 * grades ordinary SQL over a simulated version of the warehouse's own system views
 * (`warehouse_slices` for STV_SLICES, `warehouse_table_stats` for SVV_TABLE_INFO,
 * `query_plan_steps` for EXPLAIN output, `load_history` for STL_LOAD_COMMITS,
 * `query_billing` for a cost-and-usage extract). No new execution wiring.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable;
 * `referenceSolution` ships on apply and drills, never on practice.
 *
 * Two deliberate deviations from CURRICULUM-MAP.md, both because the map's shape did not
 * survive contact with the real artifact it names:
 *  - The map's `skew_rows > 4 * tbl_rows/slice-count` drill treats `skew_rows` as a row
 *    count. In SVV_TABLE_INFO it is a RATIO (fullest slice over emptiest slice), so the
 *    drill is a ratio threshold instead; the seed comment states the real meaning.
 *  - `query_plan_steps` carries `outer_table`/`inner_table` beyond the map's column list,
 *    because the map's "join steps pairing tables with different dist keys" drill needs the
 *    two sides to be joinable back to the stats table rather than buried in prose.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Shared simulated system-view seeds for Module 7.1. Named after the real Redshift views so
// a learner who later runs `SELECT * FROM svv_table_info` recognizes the shape.
// The cluster is 2 compute nodes, 2 slices each, holding one ride-share warehouse.
// ---------------------------------------------------------------------------

const WAREHOUSE_SLICES_SEED = `CREATE TABLE warehouse_slices (
  node_id       INTEGER,
  slice_id      INTEGER,   -- each compute node owns a fixed set of slices
  table_name    TEXT,
  rows_on_slice INTEGER,   -- rows of that table physically stored on this slice
  mb_on_slice   REAL       -- megabytes on this slice; a distributed table's slices sum to its size, an ALL table keeps a full copy per slice
);
INSERT INTO warehouse_slices (node_id, slice_id, table_name, rows_on_slice, mb_on_slice) VALUES
  (1, 0, 'fact_trips',    4200000, 22276.0),   -- one very busy driver_id hashed to this slice
  (1, 1, 'fact_trips',     980000,  5198.0),
  (2, 2, 'fact_trips',    1010000,  5357.0),
  (2, 3, 'fact_trips',    1050000,  5569.0),
  (1, 0, 'fact_payments', 1500000,  3200.0),   -- EVEN: round-robin, so the slices match
  (1, 1, 'fact_payments', 1498000,  3196.0),
  (2, 2, 'fact_payments', 1502000,  3204.0),
  (2, 3, 'fact_payments', 1500000,  3200.0),
  (1, 0, 'fact_sessions', 2400000,  4266.0),
  (1, 1, 'fact_sessions',  900000,  1600.0),
  (2, 2, 'fact_sessions', 1100000,  1956.0),
  (2, 3, 'fact_sessions', 1000000,  1778.0),
  (1, 0, 'fact_promos',   1850000,  1850.0),   -- one heavily redeemed promo, skewed but still inside the 2x rule
  (1, 1, 'fact_promos',   1000000,  1000.0),
  (2, 2, 'fact_promos',   1050000,  1050.0),
  (2, 3, 'fact_promos',   1100000,  1100.0),
  (1, 0, 'dim_driver',      42000,   120.0),   -- ALL: a full copy of the table on every slice
  (1, 1, 'dim_driver',      42000,   120.0),
  (2, 2, 'dim_driver',      42000,   120.0),
  (2, 3, 'dim_driver',      42000,   120.0);`

const WAREHOUSE_TABLES_SEED = `CREATE TABLE warehouse_tables (
  table_name TEXT,
  diststyle  TEXT,      -- how the loader placed the rows across the slices
  tbl_rows   INTEGER    -- logical rows in the table, not counting ALL-style copies
);
INSERT INTO warehouse_tables (table_name, diststyle, tbl_rows) VALUES
  ('fact_trips',    'KEY(driver_id)', 7240000),
  ('fact_payments', 'EVEN',           6000000),
  ('fact_sessions', 'KEY(driver_id)', 5400000),
  ('fact_promos',   'KEY(promo_id)',  5000000),
  ('dim_driver',    'ALL',              42000);`

const SLICES_AND_TABLES_SEED = WAREHOUSE_SLICES_SEED + "\n" + WAREHOUSE_TABLES_SEED

const WAREHOUSE_TABLE_STATS_SEED = `CREATE TABLE warehouse_table_stats (
  table_name TEXT,
  diststyle  TEXT,      -- KEY | ALL | EVEN
  dist_key   TEXT,      -- the distribution column, '' when the style is not KEY
  sortkey1   TEXT,      -- the first sort-key column, '' when the table has no sort key
  tbl_rows   INTEGER,
  skew_rows  REAL,      -- rows on the fullest slice divided by rows on the emptiest slice
  size_mb    INTEGER    -- logical size of the table, not multiplied by the copies an ALL table keeps
);
INSERT INTO warehouse_table_stats (table_name, diststyle, dist_key, sortkey1, tbl_rows, skew_rows, size_mb) VALUES
  ('fact_trips',        'KEY',  'driver_id',  'completed_at', 7240000, 4.29, 38400),
  ('fact_payments',     'EVEN', '',           'paid_at',      6000000, 1.00, 12800),
  ('fact_sessions',     'KEY',  'driver_id',  '',             5400000, 2.67,  9600),
  ('fact_promos',       'KEY',  'promo_id',   'issued_at',    5000000, 1.85,  5000),
  ('fact_ratings',      'KEY',  'trip_id',    'rated_at',     4800000, 1.04, 15200),
  ('dim_driver',        'ALL',  '',           'driver_id',      42000, 1.00,   120),
  ('dim_vehicle',       'ALL',  '',           '',              180000, 1.01,    60),
  ('dim_city',          'EVEN', '',           'city_id',          320, 1.00,     4),
  ('stg_trip_events',   'EVEN', '',           '',             9100000, 1.03, 44000),
  ('stg_payment_events','EVEN', '',           '',              700000, 1.02,  3100);`

const QUERY_PLAN_STEPS_SEED = `CREATE TABLE query_plan_steps (
  query_id    INTEGER,
  step_no     INTEGER,
  operation   TEXT,
  outer_table TEXT,   -- the streamed side of a join, '' on non-join steps
  inner_table TEXT,   -- the built side of a join, '' on non-join steps
  dist_type   TEXT,   -- DS_DIST_NONE | DS_DIST_ALL_NONE | DS_BCAST_INNER | DS_DIST_BOTH, '' on non-join steps
  rows_out    INTEGER,
  mb_moved    INTEGER -- megabytes the step pushed across the network
);
INSERT INTO query_plan_steps (query_id, step_no, operation, outer_table, inner_table, dist_type, rows_out, mb_moved) VALUES
  (101, 1, 'seq scan',       'fact_trips',    '',              '',                   5200000,     0),
  (101, 2, 'hash join',      'fact_trips',    'dim_driver',    'DS_DIST_ALL_NONE',   5200000,     0),
  (101, 3, 'hash aggregate', '',              '',              '',                       120,     0),
  (102, 1, 'seq scan',       'fact_payments', '',              '',                   3100000,     0),
  (102, 2, 'hash join',      'fact_payments', 'dim_city',      'DS_BCAST_INNER',     3100000,     4),
  (102, 3, 'hash aggregate', '',              '',              '',                        40,     0),
  (103, 1, 'seq scan',       'fact_trips',    '',              '',                   5200000,     0),
  (103, 2, 'hash join',      'fact_trips',    'fact_payments', 'DS_DIST_BOTH',       5200000, 41200),
  (103, 3, 'hash aggregate', '',              '',              '',                       900,     0),
  (104, 1, 'seq scan',       'fact_sessions', '',              '',                   2600000,     0),
  (104, 2, 'hash join',      'fact_sessions', 'fact_ratings',  'DS_DIST_BOTH',       2600000,  9800),
  (104, 3, 'sort',           '',              '',              '',                   2600000,     0),
  (105, 1, 'seq scan',       'fact_trips',    '',              '',                   4800000,     0),
  (105, 2, 'hash join',      'fact_trips',    'fact_sessions', 'DS_DIST_NONE',       3900000,     0),   -- both sides KEY on driver_id, so nothing moves
  (105, 3, 'hash aggregate', '',              '',              '',                      1400,     0);`

const STATS_AND_PLAN_SEED = WAREHOUSE_TABLE_STATS_SEED + "\n" + QUERY_PLAN_STEPS_SEED

const LOAD_HISTORY_SEED = `CREATE TABLE load_history (
  load_id      INTEGER,
  target_table TEXT,
  load_method  TEXT,      -- copy_from_stage | single_row_insert
  files_loaded INTEGER,   -- files in the stage prefix, 0 when the load was row by row
  rows_loaded  INTEGER,
  mb_loaded    INTEGER,
  duration_s   REAL
);
INSERT INTO load_history (load_id, target_table, load_method, files_loaded, rows_loaded, mb_loaded, duration_s) VALUES
  (1, 'fact_trips',    'copy_from_stage',   16, 5200000, 3840, 42.0),
  (2, 'fact_payments', 'copy_from_stage',   16, 3100000, 1280, 27.5),
  (3, 'fact_ratings',  'copy_from_stage',    8, 4800000, 1520, 39.0),
  (4, 'dim_driver',    'copy_from_stage',    4,   42000,   12,  2.5),
  (5, 'fact_sessions', 'copy_from_stage',   16, 2600000,  960, 21.0),
  (6, 'fact_trips',    'single_row_insert',  0,   12000,    9, 10.5),   -- 12,000 separate INSERTs
  (7, 'fact_payments', 'single_row_insert',  0,    8000,    4,  6.5),
  (8, 'dim_driver',    'single_row_insert',  0,    3000,    1,  2.5);`

const QUERY_BILLING_SEED = `CREATE TABLE query_billing (
  query_id        INTEGER,
  tb_scanned      REAL,   -- terabytes the engine read, what a per-scan model bills
  compute_seconds REAL    -- warehouse seconds the query held, what a per-second model bills
);
INSERT INTO query_billing (query_id, tb_scanned, compute_seconds) VALUES
  (2001, 0.800000,  120.0),
  (2002, 0.002100,  310.0),
  (2003, 12.400000, 640.0),
  (2004, 0.000004,   45.0),   -- 4 MB, under the 10 MB minimum
  (2005, 3.100000, 1800.0),
  (2006, 0.000002,   25.0),   -- 2 MB, under the 10 MB minimum
  (2007, 0.000900,  900.0),
  (2008, 0.260000,   60.0);`

// ---------------------------------------------------------------------------
// Module 7.1 — Inside the Cloud Warehouse
// ---------------------------------------------------------------------------

const mppArchitecture: SqlLesson = {
  id: "de-l7-mpp-architecture",
  title: "Inside an MPP Warehouse: Nodes, Slices, and the Slowest Slice",
  summary:
    "A leader node plans, compute nodes execute, and every distributed table is sharded across every slice. The query runs on all of them at once and finishes at the speed of the slowest one, which is why skew in slice-level row counts is a performance bug.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "MPP architecture",
    "leader vs compute nodes",
    "slices",
    "columnar storage in a warehouse",
    "data skew",
    "GROUP BY",
    "MIN and MAX",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## What MPP means

A cloud warehouse is not one big database server. It is a cluster running **massively parallel processing (MPP)**: many machines each holding a slice of the data, each running the same query over its own slice, with the results combined at the end.

The cluster has two kinds of machine, and the split matters:

- The **leader node** takes your SQL, parses it, builds the plan, and hands compiled steps to the compute nodes. It also collects their partial results and returns the final answer. It stores no user table data.
- **Compute nodes** hold the data and do the work. Each compute node is divided into **slices**, and a slice is the real unit of parallelism: it owns a portion of every distributed table and its own share of the node's memory and disk.

So a four-slice cluster running one query is really running four copies of the same scan at once, each over roughly a quarter of the rows.

\`\`\`csdiagram
{
  "type": "topology",
  "title": "One query, four slices",
  "layout": "tb",
  "nodes": [
    { "id": "leader", "label": "Leader node (plans, no data)", "kind": "service" },
    { "id": "n1", "label": "Compute node 1", "kind": "service" },
    { "id": "n2", "label": "Compute node 2", "kind": "service" },
    { "id": "s0", "label": "slice 0: 4,200,000 trips", "kind": "db" },
    { "id": "s1", "label": "slice 1: 980,000 trips", "kind": "db" },
    { "id": "s2", "label": "slice 2: 1,010,000 trips", "kind": "db" },
    { "id": "s3", "label": "slice 3: 1,050,000 trips", "kind": "db" }
  ],
  "edges": [
    { "from": "leader", "to": "n1", "label": "compiled steps" },
    { "from": "leader", "to": "n2", "label": "compiled steps" },
    { "from": "n1", "to": "s0" },
    { "from": "n1", "to": "s1" },
    { "from": "n2", "to": "s2" },
    { "from": "n2", "to": "s3" }
  ],
  "stages": [
    { "adds": ["leader"], "note": "The leader parses the SQL and builds one plan for the whole cluster." },
    { "adds": ["n1", "n2"], "note": "Compute nodes receive the compiled steps and execute them locally." },
    { "adds": ["s0", "s1", "s2", "s3"], "note": "Every slice scans its own rows in parallel. Slice 0 holds over four times what slice 1 holds, so the whole query waits on it." }
  ],
  "caption": "fact_trips distributed by driver_id across four slices. The query finishes when slice 0 finishes."
}
\`\`\`

## Placement is a design decision here, not a runtime one

This is the sharpest difference from the file engine in Level 6. In \`sql-l6-distributed-execution\` the engine looked at a folder of Parquet files at read time and handed each task a split. Nothing about the data's arrangement was fixed in advance, so the engine paid a shuffle whenever a query needed rows to co-locate.

A warehouse decides earlier. When you **load** a table you choose how its rows are spread across the slices, and they stay there. That buys you joins with no data movement at all, and it costs you the chance to be wrong: a bad choice is baked into the table until you reload it. Lesson two is about making that choice well.

Storage inside a warehouse is columnar for the same reason Parquet is: a query that names three columns reads three columns' worth of blocks and skips the rest. Slices and columns are orthogonal. Slices divide the rows, columnar blocks divide the columns.

## Why one crowded slice ruins a query

A parallel query is only as fast as its slowest participant. If four slices hold 1,000,000 rows each, all four finish together. If one holds 4,200,000 and the others hold about 1,000,000, three slices sit idle while the fourth grinds through more than four times the work of any neighbor. Spread evenly, those same 7,240,000 rows would be 1,810,000 per slice, so the skew costs you roughly 2.3 times the wall clock you would otherwise have had. This is **data skew**, and it is the warehouse version of the straggler task from \`sql-l6-skew-and-joins\`.

Skew comes from the distribution choice. Spreading \`fact_trips\` by \`driver_id\` sounds sensible until one fleet account is responsible for a third of all trips: every one of its rows hashes to the same slice.

You detect it by reading slice-level row counts, which is exactly what the exercises do.

**Common mistake:** reading the cluster's average CPU and concluding it is idle. During a skewed query the average looks fine because most slices genuinely are idle. The number that matters is the spread between the busiest and the quietest slice, not the mean.

**Interview nuance:** "an MPP query finishes at the slowest slice" is the one-sentence answer that shows systems understanding. Say it, then name the cause (a skewed distribution key) and the check (compare rows per slice). That progression from symptom to cause to diagnostic is what separates a memorized answer from an operational one.

> **On a real platform this differs.** Redshift exposes this through \`STV_SLICES\` (which slice lives on which node) and \`SVV_TABLE_INFO\` (per-table size and skew), and you would join them rather than read one flat table. Snowflake hides placement entirely behind automatically managed micro-partitions, so you tune clustering keys instead of distribution keys, but the failure mode is the same: uneven work makes the slowest unit set your runtime.`,
    demoSeedSql: SLICES_AND_TABLES_SEED,
    demoCode: `-- Slice-level row counts. fact_trips is spread badly; fact_payments is spread evenly.
SELECT s.node_id, s.slice_id, s.table_name, s.rows_on_slice, t.diststyle
FROM warehouse_slices s
JOIN warehouse_tables t ON t.table_name = s.table_name
ORDER BY s.table_name, s.slice_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-mpp-architecture-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each table's slice spread as \`(table_name, min_rows, max_rows)\`, widest spread first, over \`warehouse_slices(node_id, slice_id, table_name, rows_on_slice, mb_on_slice)\`.

Group the slices by \`table_name\`, then report the smallest and largest \`rows_on_slice\` for that table. Alias the columns exactly \`min_rows\` and \`max_rows\`, ordered by the spread (\`max_rows\` minus \`min_rows\`) descending.`,
    starterCode: `-- Each table's lightest and heaviest slice, widest spread first.
SELECT table_name
  -- the smallest and largest per-slice row count for this table
FROM warehouse_slices
GROUP BY table_name;`,
    hints: [
      "Group by `table_name` so each table collapses to one row across its slices.",
      "`MIN(rows_on_slice) AS min_rows` and `MAX(rows_on_slice) AS max_rows`.",
      "You can order by an expression: `ORDER BY MAX(rows_on_slice) - MIN(rows_on_slice) DESC`.",
    ],
    referenceSolution: `SELECT table_name,
       MIN(rows_on_slice) AS min_rows,
       MAX(rows_on_slice) AS max_rows
FROM warehouse_slices
GROUP BY table_name
ORDER BY MAX(rows_on_slice) - MIN(rows_on_slice) DESC;`,
    singleFile: {
      seedSql: WAREHOUSE_SLICES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "min_rows", "max_rows"],
        rows: [
          ["fact_trips", 980000, 4200000],
          ["fact_sessions", 900000, 2400000],
          ["fact_promos", 1000000, 1850000],
          ["fact_payments", 1498000, 1502000],
          ["dim_driver", 42000, 42000],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-mpp-architecture-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the tables where the busiest slice holds more than twice the rows of the quietest, as \`(table_name, skew_ratio)\` rounded to 2 decimals, most skewed first, over the same \`warehouse_slices\` table.

\`skew_ratio\` is the largest \`rows_on_slice\` divided by the smallest. Keep only tables whose ratio is strictly greater than 2, and order by \`skew_ratio\` descending.`,
    starterCode: `-- Tables whose busiest slice holds more than twice the rows of the quietest.
SELECT table_name
  -- the ratio of the heaviest slice to the lightest, for tables that fail the 2x rule
FROM warehouse_slices
GROUP BY table_name;`,
    hints: [
      "Group by `table_name`, then divide `MAX(rows_on_slice)` by `MIN(rows_on_slice)`.",
      "Multiply by 1.0 before dividing so SQLite does not do integer division, then `ROUND(..., 2)`.",
      "`HAVING MAX(rows_on_slice) > 2 * MIN(rows_on_slice)` filters after the grouping; order by `skew_ratio` descending.",
    ],
    singleFile: {
      seedSql: WAREHOUSE_SLICES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "skew_ratio"],
        rows: [
          ["fact_trips", 4.29],
          ["fact_sessions", 2.67],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-mpp-architecture-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the total rows stored on each compute node as \`(node_id, total_rows)\`, in node order, over \`warehouse_slices\`.`,
      starterCode: `-- Rows held by each compute node, across all its slices and all tables.
SELECT node_id
FROM warehouse_slices
GROUP BY node_id;`,
      hints: [
        "`SUM(rows_on_slice)` adds up every slice on the node.",
        "Alias it `total_rows` and `ORDER BY node_id`.",
      ],
      referenceSolution: `SELECT node_id, SUM(rows_on_slice) AS total_rows
FROM warehouse_slices
GROUP BY node_id
ORDER BY node_id;`,
      singleFile: {
        seedSql: WAREHOUSE_SLICES_SEED,
        orderMatters: true,
        expected: {
          columns: ["node_id", "total_rows"],
          rows: [
            [1, 14412000],
            [2, 9396000],
          ],
        },
      },
    },
    {
      id: "de-l7-mpp-architecture-drill-2",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many slices each compute node owns as \`(node_id, slice_count)\`, in node order, over \`warehouse_slices\`.`,
      starterCode: `-- Slices per compute node. Each slice appears once per table it holds.
SELECT node_id
FROM warehouse_slices
GROUP BY node_id;`,
      hints: [
        "Every slice appears once per table, so a plain `COUNT(*)` overcounts.",
        "`COUNT(DISTINCT slice_id) AS slice_count` counts each slice once.",
      ],
      referenceSolution: `SELECT node_id, COUNT(DISTINCT slice_id) AS slice_count
FROM warehouse_slices
GROUP BY node_id
ORDER BY node_id;`,
      singleFile: {
        seedSql: WAREHOUSE_SLICES_SEED,
        orderMatters: true,
        expected: {
          columns: ["node_id", "slice_count"],
          rows: [
            [1, 2],
            [2, 2],
          ],
        },
      },
    },
    {
      id: "de-l7-mpp-architecture-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns what percent of each table's rows sit on its hottest slice, as \`(table_name, hottest_slice_pct)\` rounded to 2 decimals, most concentrated first, over \`warehouse_slices\`. On this four-slice cluster an evenly spread table lands near 25 percent.`,
      starterCode: `-- Share of a table's rows held by its single busiest slice.
SELECT table_name
FROM warehouse_slices
GROUP BY table_name;`,
      hints: [
        "The hottest slice is `MAX(rows_on_slice)`; the whole table is `SUM(rows_on_slice)`.",
        "`ROUND(100.0 * MAX(rows_on_slice) / SUM(rows_on_slice), 2)`, ordered descending.",
      ],
      referenceSolution: `SELECT table_name,
       ROUND(100.0 * MAX(rows_on_slice) / SUM(rows_on_slice), 2) AS hottest_slice_pct
FROM warehouse_slices
GROUP BY table_name
ORDER BY hottest_slice_pct DESC;`,
      singleFile: {
        seedSql: WAREHOUSE_SLICES_SEED,
        orderMatters: true,
        expected: {
          columns: ["table_name", "hottest_slice_pct"],
          rows: [
            ["fact_trips", 58.01],
            ["fact_sessions", 44.44],
            ["fact_promos", 37],
            ["fact_payments", 25.03],
            ["dim_driver", 25],
          ],
        },
      },
    },
  ],
}

const distSortKeys: SqlLesson = {
  id: "de-l7-dist-sort-keys",
  title: "Distribution Styles, Sort Keys, and Reading the Query Plan",
  summary:
    "KEY co-locates joins, ALL copies small dimensions everywhere, EVEN round-robins facts nobody joins on. The plan tells you when you chose wrong, and DS_DIST_BOTH is the step interviewers ask you to spot.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "DISTSTYLE KEY, ALL, and EVEN",
    "sort keys",
    "zone maps",
    "skew detection",
    "query-plan reading",
    "joins",
    "CASE classification",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Distribution decides where rows live before any query runs

When you create a warehouse table you pick a **distribution style**, and the loader honors it forever after. There are three you need cold:

- **KEY**: hash one column and send each row to the slice that column maps to. Two tables distributed by the same key have their matching rows on the same slice, so joining them moves nothing.
- **ALL**: put a complete copy of the table on every slice. Every join against it is local by construction. You pay for it in storage, once per slice, so it is only sane for small dimensions.
- **EVEN**: round-robin the rows across slices with no regard for content. Perfectly balanced, and useless for co-location, which is right for a staging table nobody joins on.

The tradeoffs line up cleanly:

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["diststyle", "where rows go", "join against it", "the cost"],
  "rows": [
    ["KEY", "hash of the chosen column", "free when both sides share the key", "skew if the key has hot values"],
    ["ALL", "a full copy on every slice", "always free", "storage multiplied by the slice count"],
    ["EVEN", "round-robin, ignores content", "always redistributed", "network traffic on every join"]
  ],
  "highlightCols": ["the cost"],
  "caption": "Three distribution styles. KEY buys co-location and risks skew; ALL buys co-location and costs storage; EVEN buys balance and costs network."
}
\`\`\`

## The plan tells you when you chose wrong

Run \`EXPLAIN\` on a join and the planner labels each join step with what it has to move. Four labels carry the whole story:

- **DS_DIST_NONE**: nothing moves, because both sides are already distributed on the join column. This is the outcome you designed for.
- **DS_DIST_ALL_NONE**: nothing moves either, but for the other reason. The inner table is DISTSTYLE ALL, so every slice already holds a full copy of it and there is nothing to redistribute. Redshift gives this case its own label, so do not call it DS_DIST_NONE in an interview.
- **DS_BCAST_INNER**: the inner (smaller) table is broadcast, meaning a copy is sent to every node. Fine when that table is genuinely small. It is the same broadcast-join decision you met in \`sql-l6-skew-and-joins\`, made by the warehouse planner instead of Spark.
- **DS_DIST_BOTH**: both sides are redistributed across the cluster before the join. This is the expensive one, and it is the red flag interviewers name by name. It happens when neither side is distributed on the join column, so the planner has no co-located option at all.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Scan both tables", "note": "each slice reads its own rows" },
    { "label": "DS_DIST_BOTH", "note": "both sides reshuffled across the network" },
    { "label": "Hash join", "note": "only now can matching rows meet" },
    { "label": "Aggregate", "note": "partial results per slice" },
    { "label": "Leader combines", "note": "final answer" }
  ],
  "highlight": ["DS_DIST_BOTH"],
  "caption": "A join between two facts distributed on different keys. Everything before the join is cheap; the redistribution is the bill."
}
\`\`\`

Compare that with the co-located version: same scan, same hash join, same aggregate, and the redistribution step simply is not there.

## Sort keys are the warehouse's zone maps

Distribution decides *which slice* a row lives on. The **sort key** decides *what order* the rows sit in inside that slice, and the warehouse records the minimum and maximum value of every column per block. A query filtering on \`completed_at\` reads the block headers, sees that a block's range cannot contain the requested dates, and skips it without reading it.

That is the same min/max skipping you learned as Parquet row-group statistics in \`sql-l6-row-groups-pushdown\`, now built into the warehouse's own storage. The sort key is what makes those ranges narrow enough to be useful: on an unsorted column the values are scattered, so nearly every block's range overlaps your filter and nothing gets skipped.

The practical rule: sort on the column you filter by, which for a fact table is almost always the date column, and distribute on the column you join by.

**Common mistake:** choosing the primary key as the distribution key because it is unique and therefore perfectly balanced. It is balanced, and it is also useless, because nobody joins on it. Distribute on the column that appears in your join predicates, then check the skew.

**Interview nuance:** "join on the dist key, or broadcast the small table" is the expected sentence. If you can add "and if I see DS_DIST_BOTH in the plan, neither side is distributed on the join column," you have answered the Redshift question the way a practitioner answers it.

> **On a real platform this differs.** Redshift's \`SVV_TABLE_INFO\` carries these columns for real (\`diststyle\`, \`sortkey1\`, \`skew_rows\`, \`unsorted\`, \`size\`) and the plan comes from \`EXPLAIN\` as indented text rather than a table you can join to. Redshift also offers \`DISTSTYLE AUTO\`, which starts a small table as ALL and converts it to EVEN or KEY as it grows. Snowflake and BigQuery hide distribution altogether, so the same reasoning shows up as clustering keys and partition pruning instead.`,
    demoSeedSql: STATS_AND_PLAN_SEED,
    demoCode: `-- Three joins, three verdicts. 101 is local because dim_driver is ALL, 105 because both sides
-- share a dist key, and 103 pays for a full redistribution.
SELECT query_id, step_no, operation, outer_table, inner_table, dist_type, mb_moved
FROM query_plan_steps
WHERE query_id IN (101, 103, 105)
ORDER BY query_id, step_no;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-dist-sort-keys-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every query whose plan contains a DS_DIST_BOTH step, as \`(query_id, mb_moved)\`, most data moved first, over \`query_plan_steps(query_id, step_no, operation, outer_table, inner_table, dist_type, rows_out, mb_moved)\`.

Keep only the steps whose \`dist_type\` is exactly \`'DS_DIST_BOTH'\` and report that step's \`mb_moved\`, ordered descending.`,
    starterCode: `-- Queries that paid for a full redistribution, worst first.
SELECT query_id, mb_moved
FROM query_plan_steps
;`,
    hints: [
      "Only join steps carry a `dist_type`; the others hold an empty string.",
      "`WHERE dist_type = 'DS_DIST_BOTH'` keeps the redistributing steps.",
      "`ORDER BY mb_moved DESC` puts the most expensive one first.",
    ],
    referenceSolution: `SELECT query_id, mb_moved
FROM query_plan_steps
WHERE dist_type = 'DS_DIST_BOTH'
ORDER BY mb_moved DESC;`,
    singleFile: {
      seedSql: QUERY_PLAN_STEPS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["query_id", "mb_moved"],
        rows: [
          [103, 41200],
          [104, 9800],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-dist-sort-keys-practice",
    executionMode: "single-file",
    prompt: `Write a query that recommends a distribution style for each table as \`(table_name, recommended_diststyle)\`, in table-name order, over \`warehouse_table_stats(table_name, diststyle, dist_key, sortkey1, tbl_rows, skew_rows, size_mb)\`.

Apply these rules in order, first match wins: \`'ALL'\` when \`tbl_rows\` is under 500000, otherwise \`'KEY'\` when \`dist_key\` is not the empty string, otherwise \`'EVEN'\`.`,
    starterCode: `-- One recommended distribution style per table, rules applied in order.
SELECT table_name
FROM warehouse_table_stats
ORDER BY table_name;`,
    hints: [
      "A `CASE` expression tests its `WHEN` branches top to bottom and stops at the first match, which is exactly the rule order you need.",
      "The empty-string test is `dist_key <> ''`.",
      "Alias the expression exactly `recommended_diststyle`.",
    ],
    singleFile: {
      seedSql: WAREHOUSE_TABLE_STATS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "recommended_diststyle"],
        rows: [
          ["dim_city", "ALL"],
          ["dim_driver", "ALL"],
          ["dim_vehicle", "ALL"],
          ["fact_payments", "EVEN"],
          ["fact_promos", "KEY"],
          ["fact_ratings", "KEY"],
          ["fact_sessions", "KEY"],
          ["fact_trips", "KEY"],
          ["stg_payment_events", "EVEN"],
          ["stg_trip_events", "EVEN"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-dist-sort-keys-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the largest table with no sort key as \`(table_name, size_mb)\`, over \`warehouse_table_stats\`. A table with no sort key stores \`''\` in \`sortkey1\`.`,
      starterCode: `-- The biggest table that cannot skip a single block on a range filter.
SELECT table_name, size_mb
FROM warehouse_table_stats
;`,
      hints: [
        "`WHERE sortkey1 = ''` finds the unsorted tables.",
        "`ORDER BY size_mb DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `SELECT table_name, size_mb
FROM warehouse_table_stats
WHERE sortkey1 = ''
ORDER BY size_mb DESC
LIMIT 1;`,
      singleFile: {
        seedSql: WAREHOUSE_TABLE_STATS_SEED,
        orderMatters: true,
        expected: { columns: ["table_name", "size_mb"], rows: [["stg_trip_events", 44000]] },
      },
    },
    {
      id: "de-l7-dist-sort-keys-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the tables whose \`skew_rows\` ratio is above 2.0, as \`(table_name, diststyle, skew_rows)\`, most skewed first, over \`warehouse_table_stats\`. \`skew_rows\` is the rows on the fullest slice divided by the rows on the emptiest, so 1.0 is perfectly balanced.`,
      starterCode: `-- Tables whose fullest slice holds more than twice the emptiest slice.
SELECT table_name, diststyle, skew_rows
FROM warehouse_table_stats
;`,
      hints: [
        "`WHERE skew_rows > 2.0` keeps the badly distributed tables.",
        "`ORDER BY skew_rows DESC`.",
      ],
      referenceSolution: `SELECT table_name, diststyle, skew_rows
FROM warehouse_table_stats
WHERE skew_rows > 2.0
ORDER BY skew_rows DESC;`,
      singleFile: {
        seedSql: WAREHOUSE_TABLE_STATS_SEED,
        orderMatters: true,
        expected: {
          columns: ["table_name", "diststyle", "skew_rows"],
          rows: [
            ["fact_trips", "KEY", 4.29],
            ["fact_sessions", "KEY", 2.67],
          ],
        },
      },
    },
    {
      id: "de-l7-dist-sort-keys-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the join steps where both sides are KEY-distributed on different columns, as \`(query_id, outer_table, outer_dist_key, inner_table, inner_dist_key)\`, in query order, over \`query_plan_steps\` joined to \`warehouse_table_stats\`. Be strict about both halves of the condition: a step that redistributes is not automatically a match, and neither is a pair of KEY tables that happen to share a key.`,
      starterCode: `-- Join steps whose two sides are KEY-distributed on different columns.
SELECT p.query_id, p.outer_table, p.inner_table
FROM query_plan_steps p
JOIN warehouse_table_stats o ON o.table_name = p.outer_table
;`,
      hints: [
        "Join `warehouse_table_stats` twice, once for `outer_table` and once for `inner_table`, with different aliases.",
        "Keep rows where both aliases have `diststyle = 'KEY'` and their `dist_key` values differ.",
        "Alias the two key columns exactly `outer_dist_key` and `inner_dist_key`, ordered by `query_id`.",
      ],
      referenceSolution: `SELECT p.query_id,
       p.outer_table,
       o.dist_key AS outer_dist_key,
       p.inner_table,
       i.dist_key AS inner_dist_key
FROM query_plan_steps p
JOIN warehouse_table_stats o ON o.table_name = p.outer_table
JOIN warehouse_table_stats i ON i.table_name = p.inner_table
WHERE o.diststyle = 'KEY' AND i.diststyle = 'KEY' AND o.dist_key <> i.dist_key
ORDER BY p.query_id;`,
      singleFile: {
        seedSql: STATS_AND_PLAN_SEED,
        orderMatters: true,
        expected: {
          columns: ["query_id", "outer_table", "outer_dist_key", "inner_table", "inner_dist_key"],
          rows: [[104, "fact_sessions", "driver_id", "fact_ratings", "trip_id"]],
        },
      },
    },
  ],
}

const loadingAndCost: SqlLesson = {
  id: "de-l7-loading-and-cost",
  title: "COPY from Stage, Never Row Inserts, and the Two Billing Models",
  summary:
    "Warehouses ingest by pointing COPY at a stage of files in object storage and loading them in parallel across slices. Then the money: per-TB-scanned and per-second-compute price the same workload very differently.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "COPY from stage",
    "bulk vs row-by-row loading",
    "commit overhead",
    "per-TB-scanned pricing",
    "per-second compute pricing",
    "aggregation",
    "SQL cost arithmetic",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## How data actually gets into a warehouse

You do not stream rows into a warehouse one at a time. You write files to object storage, point the warehouse at that prefix, and issue one bulk load command. Redshift calls it \`COPY\`, Snowflake calls it \`COPY INTO\` from a stage, and the shape is the same everywhere:

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Producer writes files", "note": "compressed Parquet or CSV into a stage prefix" },
    { "label": "COPY command", "note": "one statement names the prefix, not the rows" },
    { "label": "Slices read in parallel", "note": "roughly one file per slice at a time" },
    { "label": "Columnar blocks written", "note": "one commit for the whole load" },
    { "label": "Table is queryable", "note": "loaded and sorted in place" }
  ],
  "highlight": ["Slices read in parallel"],
  "caption": "A bulk load moves the parallelism problem to the file layout. More files than slices keeps every slice busy."
}
\`\`\`

The heuristic worth remembering: **give the load at least as many files as the cluster has slices.** A single enormous compressed file cannot be split across slices, so one 40 GB gzip or Parquet file loads on one slice while the rest idle. Uncompressed delimited files are the exception, because Redshift can split those across slices, and that exception is a good detail to have ready when an interviewer pushes on the rule. Many evenly sized files, ideally a multiple of the slice count, keep everyone working either way.

## Why row-by-row INSERT is the classic anti-pattern

Ten thousand separate \`INSERT\` statements do not just cost ten thousand round trips. Each statement is its own transaction, so the warehouse pays a commit per row, and each commit has to write columnar blocks. Columnar storage is built to be written in large sorted batches, so a one-row write touches every column's block structure to add a single value. The result is a load that runs orders of magnitude slower than the same rows delivered as files, and leaves the table fragmented on top of it.

The exercises measure that gap directly from a load log.

## The two billing models

Warehouse pricing splits into two families, and the same workload can be cheap on one and ruinous on the other.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["billing model", "you pay for", "cheap when", "expensive when"],
  "rows": [
    ["per TB scanned", "bytes the query reads", "narrow, partitioned, pruned queries", "a dashboard rescans a huge table hourly"],
    ["per compute second", "seconds a warehouse runs", "short bursts on an idle-suspending cluster", "a cluster left running while nobody queries"]
  ],
  "highlightCols": ["expensive when"],
  "caption": "Scan-priced engines punish wide reads. Compute-priced engines punish idle time."
}
\`\`\`

**Per TB scanned** is Athena's model: $5.00 per terabyte read, with a 10 MB minimum charged per query. You pay for bytes touched, not rows returned, which is why converting to Parquet and partitioning is the single most repeated cost fix in this field. The 10 MB minimum also means thousands of tiny queries are not free, they are 10 MB each.

**Per compute second** is the Snowflake and Redshift Serverless model: you rent a sized cluster and pay for the time it is awake, regardless of how much or little it reads. Here the lever is not bytes, it is idleness and concurrency. An auto-suspend setting saves more money than any query rewrite. That family has its own floor to match the scan model's: a warehouse that resumes bills a 60-second minimum even if the query takes two seconds, which is why a trickle of tiny queries against an auto-suspending warehouse costs far more than the work implies.

The interview version of this is a two-part answer: name which model the engine uses, then name the lever that model responds to.

**Common mistake:** assuming a query that returns three rows is cheap. On a scan-priced engine \`SELECT COUNT(*)\` over an unpartitioned CSV table reads every byte in the table and bills for all of it. The result size has nothing to do with the bill.

**Interview nuance:** "why is inserting 10,000 rows one at a time slow in a warehouse" is a favorite trap, and the answer is commit-per-statement plus a columnar rewrite per commit, versus one parallel bulk load with a single commit. Follow it with "so I would stage the rows as files and COPY them" and you have given the fix as well as the diagnosis.

> **On a real platform this differs.** The seeds here flatten two real logs: Redshift's \`STL_LOAD_COMMITS\` (one row per file per slice, with the actual load timings) and Snowflake's \`COPY_HISTORY\` view. Billing comes from a cost-and-usage export rather than a tidy per-query table, and real per-TB pricing varies by region. The arithmetic you practice is the arithmetic those exports need.`,
    demoSeedSql: LOAD_HISTORY_SEED,
    demoCode: `-- Every load, fastest first. Notice which method never gets above a few thousand rows a second.
SELECT load_id, target_table, load_method, files_loaded, rows_loaded, duration_s,
       ROUND(rows_loaded / duration_s, 0) AS rows_per_second
FROM load_history
ORDER BY rows_per_second DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-loading-and-cost-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each load method's throughput as \`(load_method, rows_per_second)\`, fastest first, over \`load_history(load_id, target_table, load_method, files_loaded, rows_loaded, mb_loaded, duration_s)\`.

Combine all the loads of a method: total \`rows_loaded\` divided by total \`duration_s\`, rounded to 2 decimals, ordered descending.`,
    starterCode: `-- Rows per second by load method, combining every load of that method.
SELECT load_method
  -- total rows divided by total seconds for this method
FROM load_history
GROUP BY load_method;`,
    hints: [
      "Group by `load_method` and sum both `rows_loaded` and `duration_s` before dividing.",
      "Multiply the numerator by 1.0 so SQLite does not do integer division.",
      "Alias the result exactly `rows_per_second`, round to 2 decimals, and order descending.",
    ],
    referenceSolution: `SELECT load_method,
       ROUND(SUM(rows_loaded) * 1.0 / SUM(duration_s), 2) AS rows_per_second
FROM load_history
GROUP BY load_method
ORDER BY rows_per_second DESC;`,
    singleFile: {
      seedSql: LOAD_HISTORY_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["load_method", "rows_per_second"],
        rows: [
          ["copy_from_stage", 119257.58],
          ["single_row_insert", 1179.49],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-loading-and-cost-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each query's cost under both billing models as \`(query_id, scan_cost_usd, compute_cost_usd, cheaper_model)\`, in query order, over \`query_billing(query_id, tb_scanned, compute_seconds)\`.

Price the scan model at $5.00 per TB scanned and the compute model at $0.0004 per compute second, both rounded to 4 decimals. \`cheaper_model\` is the string \`'scan'\` when the scan cost is strictly lower, otherwise \`'compute'\`. Ignore the 10 MB minimum here; the medium drill below is where you apply it.`,
    starterCode: `-- Module boss: no scaffold. Price the same workload under both billing models.
`,
    hints: [
      "Both costs are plain arithmetic on the two columns you already have; no grouping is involved.",
      "`cheaper_model` is a `CASE` comparing the two unrounded costs.",
    ],
    singleFile: {
      seedSql: QUERY_BILLING_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["query_id", "scan_cost_usd", "compute_cost_usd", "cheaper_model"],
        rows: [
          [2001, 4, 0.048, "compute"],
          [2002, 0.0105, 0.124, "scan"],
          [2003, 62, 0.256, "compute"],
          [2004, 0, 0.018, "scan"],
          [2005, 15.5, 0.72, "compute"],
          [2006, 0, 0.01, "scan"],
          [2007, 0.0045, 0.36, "scan"],
          [2008, 1.3, 0.024, "compute"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-loading-and-cost-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the whole workload's bill under each model as \`(scan_bill_usd, compute_bill_usd)\`, rounded to 2 decimals, over \`query_billing\`. Use $5.00 per TB scanned and $0.0004 per compute second.`,
      starterCode: `-- One row: what this workload costs on a scan-priced engine and on a compute-priced one.
SELECT COUNT(*) AS queries
  -- replace this count with the two bills
FROM query_billing;`,
      hints: [
        "`SUM(tb_scanned) * 5.0` is the scan bill; `SUM(compute_seconds) * 0.0004` is the compute bill.",
        "Round both to 2 decimals and alias them `scan_bill_usd` and `compute_bill_usd`.",
      ],
      referenceSolution: `SELECT ROUND(SUM(tb_scanned) * 5.0, 2) AS scan_bill_usd,
       ROUND(SUM(compute_seconds) * 0.0004, 2) AS compute_bill_usd
FROM query_billing;`,
      singleFile: {
        seedSql: QUERY_BILLING_SEED,
        expected: { columns: ["scan_bill_usd", "compute_bill_usd"], rows: [[82.82, 1.56]] },
      },
    },
    {
      id: "de-l7-loading-and-cost-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the queries whose bill is set by the 10 MB minimum scan, as \`(query_id, raw_scan_cost_usd, billed_scan_cost_usd)\`, cheapest raw cost first, over \`query_billing\`. A query scanning less than 10 MB is billed as if it scanned 10 MB. Treat 10 MB as 0.00001 TB, price at $5.00 per TB, and round both costs to 6 decimals.`,
      starterCode: `-- Queries too small to reach the 10 MB minimum, raw cost next to billed cost.
SELECT query_id
FROM query_billing
;`,
      hints: [
        "`WHERE tb_scanned < 0.00001` keeps the queries under the minimum.",
        "SQLite's two-argument `MAX(tb_scanned, 0.00001)` returns the larger of the two values, which is the billed size.",
        "Round both costs to 6 decimals and order by `raw_scan_cost_usd` ascending.",
      ],
      referenceSolution: `SELECT query_id,
       ROUND(tb_scanned * 5.0, 6) AS raw_scan_cost_usd,
       ROUND(MAX(tb_scanned, 0.00001) * 5.0, 6) AS billed_scan_cost_usd
FROM query_billing
WHERE tb_scanned < 0.00001
ORDER BY raw_scan_cost_usd;`,
      singleFile: {
        seedSql: QUERY_BILLING_SEED,
        orderMatters: true,
        expected: {
          columns: ["query_id", "raw_scan_cost_usd", "billed_scan_cost_usd"],
          rows: [
            [2006, 0.00001, 0.00005],
            [2004, 0.00002, 0.00005],
          ],
        },
      },
    },
  ],
}

export const level7Module1: SqlModule = {
  id: "de-l7-warehouse-internals",
  title: "Module 7.1: Inside the Cloud Warehouse",
  description:
    "The MPP warehouse from the inside: nodes and slices and why a query finishes at the slowest slice, distribution and sort keys read off simulated table stats and query plans (including the DS_DIST_BOTH step interviewers ask you to spot), and the loading and billing models that decide what a query costs.",
  lessons: [mppArchitecture, distSortKeys, loadingAndCost],
}
