/**
 * Data Engineering Level 7, Module 7.3 — The Lakehouse and Open Table Formats.
 *
 * Level 6 ended at "files plus a catalog equals a table" and left the bill unpaid: no
 * transactions, no safe concurrent writers, a frozen partition layout, and no way to ask
 * what the table looked like yesterday. This module is the answer: Apache Iceberg, taught
 * the way a junior interview asks about it (the problem, not the spec).
 *
 * The device is the same one L6 proved — query the platform's own metadata. Every seed is
 * named after a real Iceberg metadata table (`snapshots`, `files`), so a learner who later
 * runs `SELECT * FROM db.orders.snapshots` in Spark or Athena recognizes the shape. The
 * seeds are a TEACHING SIMPLIFICATION of those tables, not a copy: the real `snapshots` keeps
 * added/deleted file counts inside its `summary` map, the real `files` exposes `partition` as a
 * struct, and the adding snapshot lives in `entries`. Each lesson's closing blockquote spells
 * out exactly which columns transfer verbatim and which do not; keep those two in sync. The
 * upsert lesson uses the workspace runner: the learner writes a multi-statement script and
 * the grader runs it TWICE, which is the whole point of an idempotent merge.
 *
 * Binding platform note (docs/data-engineering-curriculum/RESEARCH.md §5.3): SQLite has no
 * MERGE keyword, so MERGE is taught as semantics with the real syntax shown in prose and
 * graded through `INSERT ... ON CONFLICT(key) DO UPDATE SET ...`.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 7.3.1 seeds — a simulated Iceberg catalog for the table `analytics.orders`.
// Named after Iceberg's real metadata tables so the file/record/size columns transfer verbatim.
// Snapshot ids are sequential here so "as of snapshot N" is readable; real ids are large
// random longs. The four deliberate simplifications (sequential ids, flat added_files /
// deleted_files instead of the summary map, flat partition_dt instead of a partition struct,
// and a deleted_snapshot_id column instead of the entries table) are disclosed to the learner
// in the teach's closing blockquote.
// ---------------------------------------------------------------------------

const ICEBERG_CATALOG_SEED = `CREATE TABLE snapshots (
  snapshot_id   INTEGER,
  parent_id     INTEGER,   -- the snapshot this commit was built on; NULL for the first commit
  committed_at  TEXT,
  operation     TEXT,      -- append | overwrite | delete | replace
  added_files   INTEGER,   -- data files this commit added
  deleted_files INTEGER    -- data files this commit stopped pointing at
);
INSERT INTO snapshots (snapshot_id, parent_id, committed_at, operation, added_files, deleted_files) VALUES
  (1001, NULL, '2026-06-28 02:10:00', 'append',    4, 0),
  (1002, 1001, '2026-06-29 02:10:00', 'append',    3, 0),
  (1003, 1002, '2026-06-30 02:12:00', 'append',    3, 0),
  (1004, 1003, '2026-07-01 02:11:00', 'append',    4, 0),
  (1005, 1004, '2026-07-01 09:40:00', 'overwrite', 2, 3),
  (1006, 1005, '2026-07-02 02:10:00', 'delete',    0, 2),
  (1007, 1006, '2026-07-02 11:05:00', 'append',    2, 0),
  -- rewrite_manifests: a real commit that reorganizes metadata only, so no data file
  -- was added and none was dropped. It is still a snapshot you can time travel to.
  (1008, 1007, '2026-07-02 11:40:00', 'replace',   0, 0);

CREATE TABLE files (
  file_path           TEXT,
  partition_dt        TEXT,     -- the hidden-partition value Iceberg derived from the event date
  record_count        INTEGER,
  file_size_in_bytes  INTEGER,
  added_snapshot_id   INTEGER,  -- the commit that first pointed at this file
  deleted_snapshot_id INTEGER   -- the commit that stopped pointing at it; NULL means still live
);
INSERT INTO files (file_path, partition_dt, record_count, file_size_in_bytes, added_snapshot_id, deleted_snapshot_id) VALUES
  ('s3://lake/warehouse/orders/data/dt=2026-06-28/00001-1-4b2e.parquet', '2026-06-28', 520000, 134217728, 1001, 1006),
  ('s3://lake/warehouse/orders/data/dt=2026-06-28/00002-1-91af.parquet', '2026-06-28', 548000, 141557760, 1001, 1006),
  ('s3://lake/warehouse/orders/data/dt=2026-06-28/00003-1-c0d7.parquet', '2026-06-28', 502000, 129761280, 1001, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-28/00004-1-e83b.parquet', '2026-06-28', 460000, 118489088, 1001, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-29/00001-2-7a19.parquet', '2026-06-29', 588000, 151257088, 1002, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-29/00002-2-2f6c.parquet', '2026-06-29', 561000, 144703488, 1002, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-29/00003-2-b451.parquet', '2026-06-29', 512000, 132120576, 1002, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-30/00001-3-d20a.parquet', '2026-06-30', 623000, 160432128, 1003, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-30/00002-3-5e77.parquet', '2026-06-30', 582000, 149946368, 1003, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-06-30/00003-3-a3c8.parquet', '2026-06-30', 537000, 138412032, 1003, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00001-4-6b90.parquet', '2026-07-01', 602000, 155189248, 1004, 1005),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00002-4-f17d.parquet', '2026-07-01', 574000, 147849216, 1004, 1005),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00003-4-8c25.parquet', '2026-07-01', 529000, 136314880, 1004, 1005),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00004-4-3ed1.parquet', '2026-07-01', 472000, 121634816, 1004, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00005-5-9ba4.parquet', '2026-07-01', 782000, 201326592, 1005, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-07-01/00006-5-c5e2.parquet', '2026-07-01', 655000, 168820736, 1005, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-07-02/00001-7-e91f.parquet', '2026-07-02', 436000, 112197632, 1007, NULL),
  ('s3://lake/warehouse/orders/data/dt=2026-07-02/00002-7-40ab.parquet', '2026-07-02', 407000, 104857600, 1007, NULL);`

// ---------------------------------------------------------------------------
// Lesson 7.3.2 seeds — a warehouse upsert target and the batch a nightly load hands it.
// The batch deliberately carries changed rows, brand-new rows, and one exact duplicate
// redelivery, which is what an at-least-once source actually looks like.
// ---------------------------------------------------------------------------

const ORDERS_MERGE_SEED = `CREATE TABLE orders (
  order_id   INTEGER PRIMARY KEY,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT          -- ISO timestamp of the last change the warehouse has seen
);
INSERT INTO orders (order_id, status, amount_usd, updated_at) VALUES
  (5001, 'placed',  120.0,  '2026-07-01 08:15:00'),
  (5002, 'placed',   64.5,  '2026-07-01 08:22:00'),
  (5003, 'shipped', 310.75, '2026-07-01 09:05:00');

CREATE TABLE orders_batch (
  order_id   INTEGER,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT
);
INSERT INTO orders_batch (order_id, status, amount_usd, updated_at) VALUES
  (5002, 'shipped',    64.5,  '2026-07-02 07:40:00'),
  (5003, 'delivered', 310.75, '2026-07-02 08:02:00'),
  (5004, 'placed',     88.25, '2026-07-02 08:30:00'),
  (5005, 'placed',    205.0,  '2026-07-02 08:31:00'),
  (5005, 'placed',    205.0,  '2026-07-02 08:31:00');   -- exact duplicate redelivery`

const ORDERS_MESSY_BATCH_SEED = `CREATE TABLE orders (
  order_id   INTEGER PRIMARY KEY,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT
);
INSERT INTO orders (order_id, status, amount_usd, updated_at) VALUES
  (6001, 'placed',   49.0,  '2026-07-05 06:10:00'),
  (6002, 'placed',  130.0,  '2026-07-05 06:12:00'),
  (6003, 'shipped', 275.5,  '2026-07-05 06:20:00');

CREATE TABLE orders_batch (
  order_id   INTEGER,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT
);
-- Rows arrive out of order: the newest change for 6002 is listed before the older one.
INSERT INTO orders_batch (order_id, status, amount_usd, updated_at) VALUES
  (6002, 'delivered', 130.0,  '2026-07-06 11:45:00'),
  (6002, 'shipped',   130.0,  '2026-07-06 08:30:00'),
  (6004, 'placed',     72.25, '2026-07-06 09:15:00'),
  (6003, 'delivered', 275.5,  '2026-07-06 10:05:00'),
  (6004, 'shipped',    72.25, '2026-07-06 12:00:00'),
  (6004, 'placed',     72.25, '2026-07-06 09:15:00'),
  (6005, 'placed',    410.0,  '2026-07-06 07:55:00');`

const ORDERS_STALE_BATCH_SEED = `CREATE TABLE orders (
  order_id   INTEGER PRIMARY KEY,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT
);
INSERT INTO orders (order_id, status, amount_usd, updated_at) VALUES
  (7001, 'shipped',  95.0,  '2026-07-08 14:00:00'),
  (7002, 'placed',  180.0,  '2026-07-08 09:30:00');

CREATE TABLE orders_batch (
  order_id   INTEGER,
  status     TEXT,
  amount_usd REAL,
  updated_at TEXT
);
INSERT INTO orders_batch (order_id, status, amount_usd, updated_at) VALUES
  (7001, 'placed',   95.0,  '2026-07-08 10:00:00'),   -- STALE: older than the warehouse already holds
  (7002, 'shipped', 180.0,  '2026-07-08 15:20:00'),
  (7003, 'placed',   42.75, '2026-07-08 16:05:00');`

// ---------------------------------------------------------------------------
// Lesson 7.3.3 seeds — the same `snapshots`/`files` metadata for the table
// `analytics.events`, extended with the file layout streaming commits actually produce:
// two hot partitions full of 2 to 8 MB files, older partitions holding a few large ones.
//
// Every predicate the graded queries need is load-bearing here, by construction:
//   - dt=2026-06-20 holds NINE live large files (map deviation: the map said "2 files of
//     ~256 MB"). Over the file-count threshold, healthy on size, so a COUNT(*)-only
//     compaction plan wrongly flags it.
//   - dt=2026-06-25 holds THREE live files of ~5 MB. Under the count threshold, tiny on
//     size, so an average-size-only plan wrongly flags it.
//   - dt=2026-05-19 holds ten dead 4 MB backfill files that snapshot 1003 compacted into
//     two live ~145 MB files. Live it is healthy; counting the dead files drags the average
//     under 32 MB, so a plan missing `deleted_snapshot_id IS NULL` wrongly flags it.
//   - one dt=2026-06-20 file is added AFTER snapshot 1004 (by 1006) and deleted AFTER it
//     (by 1010), which is the only case an un-parenthesized time-travel filter admits.
// ---------------------------------------------------------------------------

const ICEBERG_TIMELINE_SEED = `CREATE TABLE snapshots (
  snapshot_id   INTEGER,
  parent_id     INTEGER,
  committed_at  TEXT,
  operation     TEXT,
  added_files   INTEGER,
  deleted_files INTEGER
);
INSERT INTO snapshots (snapshot_id, parent_id, committed_at, operation, added_files, deleted_files) VALUES
  (1001, NULL, '2026-05-21 02:05:00', 'append',    12, 0),   -- 2 files for dt=2026-05-20 plus a 10-file backfill of dt=2026-05-19
  (1002, 1001, '2026-05-22 02:05:00', 'append',     2, 0),
  (1003, 1002, '2026-05-23 02:06:00', 'overwrite',  4, 12),  -- rewrote dt=2026-05-20 and compacted the dt=2026-05-19 backfill
  (1004, 1003, '2026-06-16 02:05:00', 'append',     2, 0),
  (1005, 1004, '2026-06-17 02:05:00', 'overwrite',  1, 2),
  (1006, 1005, '2026-06-21 02:05:00', 'append',    10, 0),
  (1007, 1006, '2026-07-01 09:00:00', 'append',     8, 0),   -- 5 files for dt=2026-07-01 plus 3 late events routed to dt=2026-06-25
  (1008, 1007, '2026-07-01 09:30:00', 'append',     5, 0),
  (1009, 1008, '2026-07-02 09:00:00', 'append',    12, 0),
  (1010, 1009, '2026-07-02 10:15:00', 'delete',     0, 1);   -- dropped one bad dt=2026-06-20 file

CREATE TABLE files (
  file_path           TEXT,
  partition_dt        TEXT,
  record_count        INTEGER,
  file_size_in_bytes  INTEGER,
  added_snapshot_id   INTEGER,
  deleted_snapshot_id INTEGER   -- NULL means the file is still live in the current snapshot
);
INSERT INTO files (file_path, partition_dt, record_count, file_size_in_bytes, added_snapshot_id, deleted_snapshot_id) VALUES
  -- dt=2026-05-19: a ten-file backfill that snapshot 1003 compacted into two healthy files.
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00001-1-1001.parquet', '2026-05-19',   16400,   4194304, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00002-1-1002.parquet', '2026-05-19',   12300,   3145728, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00003-1-1003.parquet', '2026-05-19',   20500,   5242880, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00004-1-1004.parquet', '2026-05-19',   16300,   4194304, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00005-1-1005.parquet', '2026-05-19',   14350,   3670016, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00006-1-1006.parquet', '2026-05-19',   18450,   4718592, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00007-1-1007.parquet', '2026-05-19',   16350,   4194304, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00008-1-1008.parquet', '2026-05-19',   12250,   3145728, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00009-1-1009.parquet', '2026-05-19',   20450,   5242880, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00010-1-1010.parquet', '2026-05-19',   16250,   4194304, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00011-3-2001.parquet', '2026-05-19',  875000, 157286400, 1003, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-05-19/00012-3-2002.parquet', '2026-05-19',  838000, 150994944, 1003, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-05-20/00001-1-a1c4.parquet', '2026-05-20', 1040000, 268435456, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-20/00002-1-b7e0.parquet', '2026-05-20', 1015000, 268435456, 1001, 1003),
  ('s3://lake/warehouse/events/data/dt=2026-05-20/00003-3-c9d2.parquet', '2026-05-20', 1060000, 271581184, 1003, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-05-20/00004-3-d5f8.parquet', '2026-05-20',  995000, 260046848, 1003, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-05-21/00001-2-e2a7.parquet', '2026-05-21', 1120000, 279969792, 1002, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-05-21/00002-2-f6b3.parquet', '2026-05-21', 1048000, 265289728, 1002, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-15/00001-4-a8c1.parquet', '2026-06-15',  640000, 167772160, 1004, 1005),
  ('s3://lake/warehouse/events/data/dt=2026-06-15/00002-4-b3d9.parquet', '2026-06-15',  612000, 160432128, 1004, 1005),
  ('s3://lake/warehouse/events/data/dt=2026-06-15/00003-5-c1e6.parquet', '2026-06-15', 1252000, 328204288, 1005, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00001-6-11aa.parquet', '2026-06-20',  815000, 209715200, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00002-6-22bb.parquet', '2026-06-20',  766000, 197132288, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00003-6-33cc.parquet', '2026-06-20',  848000, 218103808, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00004-6-44dd.parquet', '2026-06-20',  734000, 188743680, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00005-6-55ee.parquet', '2026-06-20',  880000, 226492416, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00006-6-66ff.parquet', '2026-06-20',  782000, 201326592, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00007-6-7700.parquet', '2026-06-20',  750000, 192937984, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00008-6-8811.parquet', '2026-06-20',  835000, 214958080, 1006, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00009-6-9922.parquet', '2026-06-20',  799000, 205520896, 1006, NULL),
  -- Added after snapshot 1004 and dropped after it too, by the delete commit 1010.
  ('s3://lake/warehouse/events/data/dt=2026-06-20/00010-6-aa33.parquet', '2026-06-20',  748000, 192937984, 1006, 1010),
  -- dt=2026-06-25: a quiet day whose three small files are not worth rewriting.
  ('s3://lake/warehouse/events/data/dt=2026-06-25/00001-7-c101.parquet', '2026-06-25',   19600,   5242880, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-25/00002-7-c202.parquet', '2026-06-25',   15700,   4194304, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-06-25/00003-7-c303.parquet', '2026-06-25',   23500,   6291456, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00001-7-1a2b.parquet', '2026-07-01',   11800,   3145728, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00002-7-2c3d.parquet', '2026-07-01',   19600,   5242880, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00003-7-3e4f.parquet', '2026-07-01',    7900,   2097152, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00004-7-4a5b.parquet', '2026-07-01',   27400,   7340032, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00005-7-5c6d.parquet', '2026-07-01',   15700,   4194304, 1007, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00006-8-6e7f.parquet', '2026-07-01',   23500,   6291456, 1008, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00007-8-7a8b.parquet', '2026-07-01',   11200,   3145728, 1008, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00008-8-8c9d.parquet', '2026-07-01',   19100,   5242880, 1008, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00009-8-9e0f.parquet', '2026-07-01',   31300,   8388608, 1008, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-01/00010-8-0a1b.parquet', '2026-07-01',   15400,   4194304, 1008, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00001-9-a100.parquet', '2026-07-02',    7800,   2097152, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00002-9-a200.parquet', '2026-07-02',   15500,   4194304, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00003-9-a300.parquet', '2026-07-02',   23200,   6291456, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00004-9-a400.parquet', '2026-07-02',   11500,   3145728, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00005-9-a500.parquet', '2026-07-02',   19400,   5242880, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00006-9-a600.parquet', '2026-07-02',   27100,   7340032, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00007-9-a700.parquet', '2026-07-02',    7600,   2097152, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00008-9-a800.parquet', '2026-07-02',   31000,   8388608, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00009-9-a900.parquet', '2026-07-02',   15300,   4194304, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00010-9-b000.parquet', '2026-07-02',   23000,   6291456, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00011-9-b100.parquet', '2026-07-02',   11300,   3145728, 1009, NULL),
  ('s3://lake/warehouse/events/data/dt=2026-07-02/00012-9-b200.parquet', '2026-07-02',   19200,   5242880, 1009, NULL);`

// ---------------------------------------------------------------------------
// Module 7.3 — The Lakehouse and Open Table Formats
// ---------------------------------------------------------------------------

const icebergMetadata: SqlLesson = {
  id: "de-l7-iceberg-metadata",
  title: "Iceberg Snapshots, Manifests, and the Metadata Tree",
  summary:
    "What an open table format adds on top of raw Parquet, and how Iceberg's snapshot and manifest metadata reveals which files a query will scan.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "open table formats",
    "ACID on object storage",
    "snapshots",
    "manifests",
    "metadata tables",
    "hidden partitioning",
    "NULL filtering",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Where "files plus a catalog" runs out

Level 6 built a table out of two things: Parquet files in a bucket, and a catalog entry saying where they live and what the columns are. That gets you a queryable table for almost nothing, and it is genuinely how a lake starts. It also has three holes that show up the first week a second person touches the data.

- **No transactions.** A job that rewrites a partition deletes some files and writes others. A reader that lands in the middle sees half the old data and half the new. There is no commit, so there is nothing to be atomic about.
- **No safe concurrent writers.** Two jobs writing the same table race on the same prefix. The catalog has no idea a write is in progress, so last-writer-wins silently destroys work.
- **A frozen layout, and no way back.** The partition scheme is baked into the folder paths, so changing from daily to hourly means rewriting every path in the table. And once a file is overwritten, yesterday's answer is gone. You cannot reproduce the number you put in a dashboard last Tuesday.

An **open table format** fixes exactly these. Files stay Parquet in object storage, and any engine can still read them, but a layer of metadata turns the pile of files into a table with commits.

## The metadata tree

Iceberg's whole idea is that a table is defined by metadata, not by whatever happens to be sitting under a prefix. The catalog stores one pointer: the current metadata file. Everything else hangs off it.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Catalog", "note": "one pointer: current metadata file" },
    { "label": "Snapshot", "note": "one commit; schema + partition spec" },
    { "label": "Manifest list", "note": "the manifests in this snapshot" },
    { "label": "Manifest", "note": "data files + per-file stats" },
    { "label": "Data files", "note": "ordinary Parquet in the bucket" }
  ],
  "highlight": ["Snapshot", "Manifest"],
  "caption": "A read starts at the catalog pointer and walks down. Nothing in this path lists the bucket."
}
\`\`\`

Read it top down and the properties fall out:

- A **snapshot** is one commit: the complete set of data files that made up the table at that instant. Committing means writing new metadata and then swapping the catalog pointer to it in a single atomic operation. That swap is the transaction. Readers already holding the old pointer keep reading a consistent older snapshot, so a writer never tears a reader in half.
- A **manifest** lists data files together with per-file statistics: row count, file size, and column lower and upper bounds. Those stats are the reason a planner can throw away files before opening any of them.
- **Readers never list the bucket.** On a plain lake, planning a query means asking object storage for every key under a prefix, which is slow and gets slower as the table grows. Iceberg reads a manifest instead, so planning cost tracks the number of files in the metadata, not the number of objects in the bucket.

## Hidden partitioning and schema evolution

Two features come up constantly and each is one paragraph of understanding.

**Hidden partitioning.** On a Hive-style lake the partition value is part of the path, so the query has to filter on the partition column by hand (\`WHERE dt = '2026-07-01'\`), and a user who filters on the raw timestamp instead gets a full scan. Iceberg stores the partition rule as a **transform** of a real column (for example \`days(event_ts)\`), records the derived value in the manifest, and applies it for you. You filter on \`event_ts\` and pruning still happens. Because the rule lives in metadata rather than in paths, you can also change it later (**partition evolution**): new data is written under the new scheme, old data keeps the old one, and both are still readable.

**Schema evolution by field id.** Every column carries a numeric field id, and data files reference ids, not names. Renaming a column is a metadata edit. Adding, dropping, and reordering columns never require rewriting files, and a dropped-then-re-added column cannot resurrect old values, because the new column gets a new id.

## Delta, Hudi, and who won

Iceberg is the de facto open standard: vendor-neutral governance and the broadest engine support (Spark, Flink, Trino, Snowflake, BigQuery, DuckDB, AWS S3 Tables). The v3 spec was ratified in mid-2025, adding deletion vectors, a variant type, and geospatial types. **Delta Lake** remains strong inside Databricks, and its UniForm feature emits Iceberg-readable metadata beside Delta's own. **Hudi** holds a streaming and CDC niche. The pattern worth naming in an interview is the consumption gravity: every non-Iceberg format now ships an Iceberg-readable surface, and the reverse investment does not exist.

Worth keeping in proportion: in the 2026 State of Data Engineering Survey (n = 1,101), **43.8% of teams run a cloud warehouse, 26.8% a lakehouse, and 11.7% a hybrid**. The warehouse still dominates entry-level work. Lakehouse literacy is expected, not lakehouse everywhere.

## Reading it with SQL

The payoff for this level is that Iceberg exposes its own metadata as ordinary tables you can query. \`snapshots\` gives you the commit history. \`files\` gives you every data file, the snapshot that added it, and the snapshot that stopped pointing at it. A file with **no** deleting snapshot is live right now, which makes "what would this query scan" a plain \`WHERE\` clause.

**Common mistake:** reading the \`files\` table without filtering \`deleted_snapshot_id IS NULL\` and reporting the result as the table's size. That set includes every file the table ever wrote, including the ones replaced by later commits, so the number can be several times the live footprint.

**Interview nuance:** the junior bar for "what does Iceberg actually solve" is the problem statement, not the spec. One sentence covers it: ACID transactions, schema evolution, and time travel over Parquet files in object storage, with a catalog pointer telling engines which files are current. Catalog wars and manifest internals are senior awareness, and volunteering them before the one-sentence answer reads as memorized.

> **On a real platform this differs.** These seeds mirror Iceberg's real metadata tables. In Spark or Athena you query them directly with \`SELECT * FROM analytics.orders.snapshots\` and \`SELECT * FROM analytics.orders.files\`, and \`snapshot_id\`, \`parent_id\`, \`committed_at\`, \`operation\`, \`file_path\`, \`record_count\`, and \`file_size_in_bytes\` carry exactly these names. Four columns here are a teaching simplification, and knowing which ones saves you a column-not-found error on your first real query. Real snapshot ids are large random longs, so production code walks the \`parent_id\` chain or compares \`committed_at\` rather than using \`<\`. The real \`snapshots\` table has no \`added_files\` or \`deleted_files\` column; those counts are string entries in its \`summary\` map, read as \`summary['added-data-files']\` and \`summary['deleted-data-files']\`. The real \`files\` table exposes \`partition\` as a struct of the partition-spec fields rather than a flat \`partition_dt\`. And it carries no \`added_snapshot_id\` or \`deleted_snapshot_id\` at all: it shows one snapshot's live files at a time, and the commit that added or dropped a file is reachable through the \`entries\` and \`all_entries\` metadata tables.`,
    demoSeedSql: ICEBERG_CATALOG_SEED,
    demoCode: `-- The live file set: every data file the current snapshot still points at.
-- A NULL deleted_snapshot_id is the whole test.
SELECT file_path, partition_dt, record_count, file_size_in_bytes
FROM files
WHERE deleted_snapshot_id IS NULL
ORDER BY partition_dt, file_path;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-iceberg-metadata-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the live data files a query on partition \`dt = '2026-07-01'\` would scan, as \`(file_path, file_size_in_bytes)\`, largest file first, over \`files(file_path, partition_dt, record_count, file_size_in_bytes, added_snapshot_id, deleted_snapshot_id)\`.

A file is live when \`deleted_snapshot_id\` is NULL. Keep only \`partition_dt = '2026-07-01'\` and order by \`file_size_in_bytes\` descending.`,
    starterCode: `-- Live files a query on partition dt = '2026-07-01' would scan, largest first.
SELECT file_path, file_size_in_bytes
FROM files
;`,
    hints: [
      "Two filters: `partition_dt = '2026-07-01'` and `deleted_snapshot_id IS NULL`.",
      "`deleted_snapshot_id IS NULL` is the live test; `= NULL` never matches anything in SQL.",
      "Order by `file_size_in_bytes` descending so the largest file is first.",
    ],
    referenceSolution: `SELECT file_path, file_size_in_bytes
FROM files
WHERE partition_dt = '2026-07-01'
  AND deleted_snapshot_id IS NULL
ORDER BY file_size_in_bytes DESC;`,
    singleFile: {
      seedSql: ICEBERG_CATALOG_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["file_path", "file_size_in_bytes"],
        rows: [
          ["s3://lake/warehouse/orders/data/dt=2026-07-01/00005-5-9ba4.parquet", 201326592],
          ["s3://lake/warehouse/orders/data/dt=2026-07-01/00006-5-c5e2.parquet", 168820736],
          ["s3://lake/warehouse/orders/data/dt=2026-07-01/00004-4-3ed1.parquet", 121634816],
        ],
      },
    },
  },
  // Map deviation: the map's commit-history practice is a bare projection of five columns, which
  // grades nothing the apply did not. Adding net_files and dropping the metadata-only commit keeps
  // the same subject while forcing the learner to reason about what a snapshot did to the file set.
  practice: {
    id: "de-l7-iceberg-metadata-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the table's commit history as \`(snapshot_id, operation, added_files, deleted_files, net_files, committed_at)\`, oldest commit first, over \`snapshots(snapshot_id, parent_id, committed_at, operation, added_files, deleted_files)\`, where \`net_files\` is the net change that commit made to the count of live data files.

Keep only the commits that actually changed the live file set, so a commit that added nothing and deleted nothing is left out. Order by \`committed_at\` and alias the columns exactly as listed.`,
    starterCode: `-- The commit history of the table, oldest first, with each commit's net effect
-- on the number of live data files. Metadata-only commits do not belong here.
SELECT
  -- id, operation, files added, files deleted, net change, commit time
FROM snapshots;`,
    hints: [
      "A commit's net effect on the live file count is `added_files - deleted_files`, aliased `net_files`.",
      "A commit that changed the live file set is one where `added_files > 0 OR deleted_files > 0`.",
      "`net_files` can be negative: a delete commit removes files without adding any.",
      "`ORDER BY committed_at` puts the oldest commit first.",
    ],
    singleFile: {
      seedSql: ICEBERG_CATALOG_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: [
          "snapshot_id",
          "operation",
          "added_files",
          "deleted_files",
          "net_files",
          "committed_at",
        ],
        rows: [
          [1001, "append", 4, 0, 4, "2026-06-28 02:10:00"],
          [1002, "append", 3, 0, 3, "2026-06-29 02:10:00"],
          [1003, "append", 3, 0, 3, "2026-06-30 02:12:00"],
          [1004, "append", 4, 0, 4, "2026-07-01 02:11:00"],
          [1005, "overwrite", 2, 3, -1, "2026-07-01 09:40:00"],
          [1006, "delete", 0, 2, -2, "2026-07-02 02:10:00"],
          [1007, "append", 2, 0, 2, "2026-07-02 11:05:00"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-iceberg-metadata-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the single commit that stopped pointing at the most data files, as \`(snapshot_id, operation, deleted_files)\`, over \`snapshots\`.`,
      starterCode: `-- The commit that deleted the most data files.
SELECT snapshot_id, operation, deleted_files
FROM snapshots
;`,
      hints: ["Order by `deleted_files` descending.", "`LIMIT 1` keeps only the top commit."],
      referenceSolution: `SELECT snapshot_id, operation, deleted_files
FROM snapshots
ORDER BY deleted_files DESC, snapshot_id
LIMIT 1;`,
      singleFile: {
        seedSql: ICEBERG_CATALOG_SEED,
        orderMatters: true,
        expected: {
          columns: ["snapshot_id", "operation", "deleted_files"],
          rows: [[1005, "overwrite", 3]],
        },
      },
    },
    {
      id: "de-l7-iceberg-metadata-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that compares the table's live footprint with everything it has ever written, as \`(live_bytes, ever_written_bytes)\`, over \`files\`. \`live_bytes\` sums only files with a NULL \`deleted_snapshot_id\`; \`ever_written_bytes\` sums every row.`,
      starterCode: `-- Live bytes vs total bytes ever written by this table.
SELECT
FROM files;`,
      hints: [
        "A conditional sum gives the live half: `SUM(CASE WHEN deleted_snapshot_id IS NULL THEN file_size_in_bytes ELSE 0 END)`.",
        "The second column is a plain `SUM(file_size_in_bytes)` over every row.",
        "Alias them exactly `live_bytes` and `ever_written_bytes`.",
      ],
      referenceSolution: `SELECT SUM(CASE WHEN deleted_snapshot_id IS NULL THEN file_size_in_bytes ELSE 0 END) AS live_bytes,
       SUM(file_size_in_bytes) AS ever_written_bytes
FROM files;`,
      singleFile: {
        seedSql: ICEBERG_CATALOG_SEED,
        assertColumnNames: true,
        expected: {
          columns: ["live_bytes", "ever_written_bytes"],
          rows: [[1833959424, 2549088256]],
        },
      },
    },
  ],
}

const upsertMergeSemantics: SqlLesson = {
  id: "de-l7-upsert-merge-semantics",
  title: "MERGE Semantics: Upserts That Survive a Rerun",
  summary:
    "How to write a MERGE-style upsert that survives a rerun, guarding against late-arriving old rows and collapsing a redelivered batch to one row per key.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "MERGE INTO semantics",
    "upsert",
    "ON CONFLICT DO UPDATE",
    "late-arriving data guards",
    "natural keys",
    "windowed dedup",
    "idempotent sinks",
    "copy-on-write vs merge-on-read",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## MERGE in one shape

Every warehouse spells it slightly differently, and every version is the same three-part sentence: **match** target rows to source rows on a key, **update** the ones that matched, **insert** the ones that did not.

\`\`\`sql
MERGE INTO orders t
USING orders_batch s
   ON t.order_id = s.order_id
WHEN MATCHED THEN UPDATE SET
  status = s.status, amount_usd = s.amount_usd, updated_at = s.updated_at
WHEN NOT MATCHED THEN INSERT (order_id, status, amount_usd, updated_at)
  VALUES (s.order_id, s.status, s.amount_usd, s.updated_at);
\`\`\`

That is the real syntax, and it is what Snowflake, BigQuery, Redshift, Databricks, and Iceberg through Spark or Athena all accept. \`MERGE\` is also the standard form: it entered ISO SQL in SQL:2003, which is why every warehouse spells it the same way. SQLite has no \`MERGE\` keyword, so this level grades the identical semantics through SQLite's upsert clause, the Postgres-style \`INSERT ... ON CONFLICT DO UPDATE\`:

\`\`\`sql
INSERT INTO orders (order_id, status, amount_usd, updated_at)
SELECT order_id, status, amount_usd, updated_at
FROM orders_batch
WHERE 1 = 1
ON CONFLICT(order_id) DO UPDATE SET
  status     = excluded.status,
  amount_usd = excluded.amount_usd,
  updated_at = excluded.updated_at;
\`\`\`

Worth getting right if it comes up: \`ON CONFLICT DO UPDATE\` is a PostgreSQL extension that SQLite adopted, not standard SQL. It is the portable stand-in you reach for on Postgres and SQLite, and the standard upsert is the \`MERGE\` above. Saying it the other way round in an interview is the kind of confident inversion an interviewer remembers.

Read it as the same three parts. The conflict target \`ON CONFLICT(order_id)\` is the join key, and it only works because \`order_id\` carries a primary key or unique constraint. \`excluded\` is the pseudo-table holding the row that was about to be inserted, so \`excluded.status\` is the source value and a bare \`status\` is the target value. The \`WHERE 1 = 1\` is a SQLite parsing requirement, not a filter: when the values come from a \`SELECT\`, the parser cannot tell whether \`ON\` is starting the upsert clause or a join, so the \`SELECT\` needs a \`WHERE\` before it.

## Why an upsert is the load you want

Here is the failure that makes this the most-asked pipeline question there is. A nightly job appends its batch to a table, the run half-fails, an operator retries it, and now every order in the batch exists twice. Every downstream count, sum, and dashboard is wrong, and nothing errored.

An upsert sink cannot double count. Rerunning it re-matches the same keys and rewrites the same values, so the table after two runs is byte for byte the table after one. That property has a name and it is the spine of this whole course: **idempotency**. Level 6 introduced it as a pipeline habit. Here it becomes a property of the table itself, enforced by a key.

That is why the grader for this lesson runs your script **twice** and compares. A script that passes once and drifts on the second run has not solved the problem.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["sink", "after run 1", "after retry (run 2)", "safe to retry"],
  "rows": [
    ["append only", "N rows", "2N rows", "no"],
    ["delete partition + insert", "N rows", "N rows", "yes, per partition"],
    ["upsert on a key", "N rows", "N rows", "yes, per row"]
  ],
  "highlightCols": ["after retry (run 2)"],
  "caption": "Three sinks, one retry. Only the bottom two survive it, and only the upsert survives a partial batch."
}
\`\`\`

## Dedupe before you merge

There is a trap sitting inside the source. Real batches arrive from an at-least-once system, so the same key can appear several times, out of order, sometimes as an exact duplicate redelivery. If you merge that batch directly, the row that wins is whichever one the engine happened to apply last, which is not a guarantee you can build on. Most warehouses will not even let you try: \`MERGE\` raises an error when more than one source row matches the same target row.

The fix is one window function, and it is the single most-cited SQL interview task in this space. You have written it before: Level 5's CDC changelog apply used exactly this window to collapse an insert, update, and delete stream to the latest version per key. Same window, same job, this time standing in front of a table-format MERGE instead of a warehouse table:

\`\`\`sql
WITH latest AS (
  SELECT order_id, status, amount_usd, updated_at,
         ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC) AS rn
  FROM orders_batch
)
SELECT order_id, status, amount_usd, updated_at FROM latest WHERE rn = 1
\`\`\`

Partition by the natural key, order by the change timestamp descending, keep rank 1. That collapses the batch to one row per key, newest wins, and only then do you merge.

## Copy-on-write vs merge-on-read

Object storage cannot edit a file in place, so "update three rows" has to become "rewrite something." Iceberg gives you two strategies and expects you to pick per table.

- **Copy-on-write** rewrites every data file that contains a changed row and commits the replacements. Writes are expensive, reads are as fast as a fresh table. Right for a table written once a night and read all day.
- **Merge-on-read** writes a small delete file (a deletion vector, in the v3 spec) beside the data instead of rewriting it, and readers apply the deletes on the fly. Writes are cheap, reads pay a growing tax until compaction folds the deletes in. Right for frequent small updates and streaming CDC.

The judgment sentence: copy-on-write when reads dominate, merge-on-read when writes dominate, and compaction is what stops merge-on-read from degrading. The next lesson is that compaction.

**Common mistake:** merging a batch that still contains duplicate keys. It passes on clean data, then produces a nondeterministic winner or a hard error the first night the source redelivers, which is exactly the night you are asleep.

**Interview nuance:** "how do you get exactly-once?" has one correct answer and it is not a technology. True exactly-once delivery is impossible; **at-least-once delivery plus an idempotent sink equals effectively exactly-once**. Say that sentence, then name the sink you would build (an upsert on the natural key), and the follow-up about retries answers itself.

> **On a real platform this differs.** You would write \`MERGE INTO\` and the engine would decide how to rewrite files, then log the whole thing as one Iceberg snapshot you can roll back to. Two more things change at scale: the merge key is usually a surrogate key resolved from the natural key, and a production loader guards the update with a condition like \`WHEN MATCHED AND s.updated_at > t.updated_at\` so a late-arriving old row can never overwrite a newer one. That guard is what you build in the apply.`,
    demoSeedSql: ORDERS_MERGE_SEED,
    demoCode: `-- What a MERGE would do with this batch, before running it:
-- rows whose key already exists are UPDATEs, the rest are INSERTs.
SELECT b.order_id,
       CASE WHEN o.order_id IS NULL THEN 'INSERT' ELSE 'UPDATE' END AS merge_action,
       o.status AS target_status,
       b.status AS batch_status
FROM orders_batch b
LEFT JOIN orders o ON o.order_id = b.order_id
ORDER BY b.order_id, b.updated_at;`,
    showDemoInput: false,
  },
  // Map deviation: the map puts the unguarded merge in the apply and the freshness guard in a
  // medium drill. They are swapped here. An unguarded upsert is idempotent on a rerun but still
  // wrong on a late-arriving old row, so the guard is the graded skill and the plain form is the
  // drill; the map's apply seed and prompt survive verbatim as drill 2.
  apply: scriptExercise({
    id: "de-l7-upsert-merge-semantics-apply",
    prompt: `Write a script that merges \`orders_batch\` into \`orders\` without ever letting an older change overwrite a newer one: insert an \`order_id\` the table does not hold, and overwrite \`status\`, \`amount_usd\`, and \`updated_at\` only when the batch row's \`updated_at\` is strictly newer than the one already stored.

\`orders(order_id PRIMARY KEY, status, amount_usd, updated_at)\` and \`orders_batch(order_id, status, amount_usd, updated_at)\` are already seeded. Order 7001 is a stale redelivery and must keep its current \`shipped\` state, order 7002 is a genuine newer change, and order 7003 is new. Use \`INSERT ... ON CONFLICT(order_id) DO UPDATE SET ...\`, and remember the grader runs your script twice: the table after two runs must equal the table after one.`,
    starterCode: `-- Merge orders_batch into orders, but never let an older change overwrite a newer one.
-- The WHERE 1 = 1 is required by SQLite before an ON CONFLICT clause that follows a SELECT.
INSERT INTO orders (order_id, status, amount_usd, updated_at)
SELECT order_id, status, amount_usd, updated_at
FROM orders_batch
WHERE 1 = 1
;`,
    hints: [
      "The conflict target is the key you match on: `ON CONFLICT(order_id)`.",
      "`excluded` holds the row that was about to be inserted, so the update is `status = excluded.status, amount_usd = excluded.amount_usd, updated_at = excluded.updated_at`.",
      "The guard is a second `WHERE`, at the end of the `DO UPDATE SET` clause rather than on the `SELECT`.",
      "Inside that guard, `excluded.updated_at` is the incoming row and `orders.updated_at` is what the table already holds.",
      "A guarded upsert that skips the update is still a successful statement, so nothing errors on the stale row for 7001.",
    ],
    referenceSolution: `INSERT INTO orders (order_id, status, amount_usd, updated_at)
SELECT order_id, status, amount_usd, updated_at
FROM orders_batch
WHERE 1 = 1
ON CONFLICT(order_id) DO UPDATE SET
  status     = excluded.status,
  amount_usd = excluded.amount_usd,
  updated_at = excluded.updated_at
WHERE excluded.updated_at > orders.updated_at;`,
    seedSql: ORDERS_STALE_BATCH_SEED,
    checkIdempotency: true,
    idempotencyTables: ["orders"],
    assertions: [
      {
        suite: "shape",
        name: "orders holds exactly three rows",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders) <> 3`,
      },
      {
        suite: "grain",
        name: "one row per order_id",
        sql: `SELECT order_id FROM orders GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "guard",
        name: "the stale row for order 7001 was rejected",
        sql: `SELECT order_id FROM orders
WHERE order_id = 7001 AND (status <> 'shipped' OR updated_at <> '2026-07-08 14:00:00')`,
      },
      {
        suite: "endstate",
        name: "every order matches the guarded merge end state",
        isHidden: true,
        sql: `WITH expected(order_id, status, amount_usd, updated_at) AS (
  VALUES (7001, 'shipped',  95.0,  '2026-07-08 14:00:00'),
         (7002, 'shipped', 180.0,  '2026-07-08 15:20:00'),
         (7003, 'placed',   42.75, '2026-07-08 16:05:00')
)
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM orders EXCEPT SELECT order_id, status, amount_usd, updated_at FROM expected)
UNION ALL
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM expected EXCEPT SELECT order_id, status, amount_usd, updated_at FROM orders)`,
      },
      {
        suite: "endstate",
        name: "the genuinely newer change for order 7002 was applied",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders
  WHERE order_id = 7002 AND status = 'shipped' AND updated_at = '2026-07-08 15:20:00') <> 1`,
      },
    ],
  }),
  practice: scriptExercise({
    id: "de-l7-upsert-merge-semantics-practice",
    prompt: `Write a script that merges a messier \`orders_batch\` into \`orders\`, where the same \`order_id\` appears several times out of order, in two visible steps: first materialize the collapsed batch as a table \`orders_batch_latest(order_id, status, amount_usd, updated_at)\` holding exactly the latest row per \`order_id\` by \`updated_at\`, then merge \`orders_batch_latest\` into \`orders\`.

\`orders(order_id PRIMARY KEY, status, amount_usd, updated_at)\` and \`orders_batch(order_id, status, amount_usd, updated_at)\` are seeded. An order absent from the batch must keep its current values. The grader runs your script twice and grades both tables, so rebuild \`orders_batch_latest\` from scratch on every run instead of appending to it.`,
    starterCode: `-- Step 1: collapse orders_batch to one row per order_id, newest updated_at wins,
-- into a table named orders_batch_latest. The DROP keeps the second run working.
DROP TABLE IF EXISTS orders_batch_latest;

-- Step 2: merge orders_batch_latest into orders.
`,
    hints: [
      "`ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC)` ranks each key's rows newest first.",
      "`CREATE TABLE orders_batch_latest AS SELECT ... FROM (that ranked subquery) WHERE rn = 1` materializes the collapse, and the `DROP TABLE IF EXISTS` above it is what makes the rerun safe.",
      "Then upsert the survivors with `ON CONFLICT(order_id) DO UPDATE SET status = excluded.status, amount_usd = excluded.amount_usd, updated_at = excluded.updated_at`, remembering SQLite wants a `WHERE` before `ON CONFLICT` when the values come from a `SELECT`.",
      "Order 6002 has an older `shipped` row listed after its newer `delivered` row, and order 6004 has three rows; the dedup is what stops the stale ones from winning.",
    ],
    seedSql: ORDERS_MESSY_BATCH_SEED,
    checkIdempotency: true,
    idempotencyTables: ["orders"],
    assertions: [
      {
        suite: "shape",
        name: "orders holds exactly five rows",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders) <> 5`,
      },
      {
        suite: "grain",
        name: "one row per order_id",
        sql: `SELECT order_id FROM orders GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "dedup",
        name: "orders_batch_latest holds one row per distinct batch key",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders_batch_latest)
  <> (SELECT COUNT(DISTINCT order_id) FROM orders_batch)`,
      },
      {
        suite: "dedup",
        name: "orders_batch_latest has no duplicate order_id",
        sql: `SELECT order_id FROM orders_batch_latest GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "dedup",
        name: "the collapsed row for order 6004 is its newest, not its first",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders_batch_latest
  WHERE order_id = 6004 AND updated_at = '2026-07-06 12:00:00') <> 1`,
      },
      {
        suite: "endstate",
        name: "every order matches the deduped merge end state",
        isHidden: true,
        sql: `WITH expected(order_id, status, amount_usd, updated_at) AS (
  VALUES (6001, 'placed',     49.0,  '2026-07-05 06:10:00'),
         (6002, 'delivered', 130.0,  '2026-07-06 11:45:00'),
         (6003, 'delivered', 275.5,  '2026-07-06 10:05:00'),
         (6004, 'shipped',    72.25, '2026-07-06 12:00:00'),
         (6005, 'placed',    410.0,  '2026-07-06 07:55:00')
)
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM orders EXCEPT SELECT order_id, status, amount_usd, updated_at FROM expected)
UNION ALL
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM expected EXCEPT SELECT order_id, status, amount_usd, updated_at FROM orders)`,
      },
      {
        suite: "dedup",
        name: "the stale 08:30 row for order 6002 did not win",
        isHidden: true,
        sql: `SELECT order_id FROM orders WHERE order_id = 6002 AND updated_at = '2026-07-06 08:30:00'`,
      },
      {
        suite: "endstate",
        name: "order 6001 was absent from the batch and stayed untouched",
        isHidden: true,
        sql: `SELECT order_id FROM orders
WHERE order_id = 6001 AND (status <> 'placed' OR updated_at <> '2026-07-05 06:10:00')`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l7-upsert-merge-semantics-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many distinct \`order_id\` values in \`orders_batch\` would be updates and how many would be inserts, as \`(updates, inserts)\`, over \`orders\` and \`orders_batch\`. An id already present in \`orders\` is an update; the rest are inserts.`,
      starterCode: `-- Split the batch's distinct keys into updates (already in orders) and inserts (new).
SELECT
FROM (SELECT DISTINCT order_id FROM orders_batch) b
LEFT JOIN orders o ON o.order_id = b.order_id;`,
      hints: [
        "Start from `SELECT DISTINCT order_id FROM orders_batch` so the redelivered duplicate is counted once.",
        "`LEFT JOIN orders` and count the matched versus unmatched keys with two conditional sums.",
        "Alias the two counts exactly `updates` and `inserts`.",
      ],
      referenceSolution: `SELECT SUM(CASE WHEN o.order_id IS NOT NULL THEN 1 ELSE 0 END) AS updates,
       SUM(CASE WHEN o.order_id IS NULL THEN 1 ELSE 0 END) AS inserts
FROM (SELECT DISTINCT order_id FROM orders_batch) b
LEFT JOIN orders o ON o.order_id = b.order_id;`,
      singleFile: {
        seedSql: ORDERS_MERGE_SEED,
        assertColumnNames: true,
        expected: { columns: ["updates", "inserts"], rows: [[2, 2]] },
      },
    },
    scriptExercise({
      id: "de-l7-upsert-merge-semantics-drill-2",
      prompt: `**Medium.** Write a script that merges \`orders_batch\` into \`orders\` with no freshness guard at all: for an \`order_id\` that already exists, overwrite \`status\`, \`amount_usd\`, and \`updated_at\` with the batch values; for an \`order_id\` that does not, insert it.

This batch is clean enough for the unguarded form: it carries two changed orders, two new ones, and one exact duplicate redelivery. Order 5001 is absent from the batch and nothing should touch it, and the grader runs your script twice.`,
      starterCode: `-- Merge orders_batch into orders: update on a key match, insert otherwise.
-- The WHERE 1 = 1 is required by SQLite before an ON CONFLICT clause that follows a SELECT.
INSERT INTO orders (order_id, status, amount_usd, updated_at)
SELECT order_id, status, amount_usd, updated_at
FROM orders_batch
WHERE 1 = 1
;`,
      hints: [
        "The conflict target is the key you match on: `ON CONFLICT(order_id)`.",
        "`excluded` holds the row that was about to be inserted, so the update is `status = excluded.status, amount_usd = excluded.amount_usd, updated_at = excluded.updated_at`.",
        "The duplicate row for 5005 conflicts with the row inserted a moment earlier and updates it, which is why the final table still holds exactly one 5005.",
      ],
      referenceSolution: `INSERT INTO orders (order_id, status, amount_usd, updated_at)
SELECT order_id, status, amount_usd, updated_at
FROM orders_batch
WHERE 1 = 1
ON CONFLICT(order_id) DO UPDATE SET
  status     = excluded.status,
  amount_usd = excluded.amount_usd,
  updated_at = excluded.updated_at;`,
      seedSql: ORDERS_MERGE_SEED,
      checkIdempotency: true,
      idempotencyTables: ["orders"],
      assertions: [
        {
          suite: "shape",
          name: "orders holds exactly five rows",
          sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders) <> 5`,
        },
        {
          suite: "grain",
          name: "one row per order_id",
          sql: `SELECT order_id FROM orders GROUP BY order_id HAVING COUNT(*) > 1`,
        },
        {
          suite: "endstate",
          name: "every order matches the merged end state",
          isHidden: true,
          sql: `WITH expected(order_id, status, amount_usd, updated_at) AS (
  VALUES (5001, 'placed',    120.0,  '2026-07-01 08:15:00'),
         (5002, 'shipped',    64.5,  '2026-07-02 07:40:00'),
         (5003, 'delivered', 310.75, '2026-07-02 08:02:00'),
         (5004, 'placed',     88.25, '2026-07-02 08:30:00'),
         (5005, 'placed',    205.0,  '2026-07-02 08:31:00')
)
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM orders EXCEPT SELECT order_id, status, amount_usd, updated_at FROM expected)
UNION ALL
SELECT * FROM (SELECT order_id, status, amount_usd, updated_at FROM expected EXCEPT SELECT order_id, status, amount_usd, updated_at FROM orders)`,
        },
        {
          suite: "endstate",
          name: "order 5001 was absent from the batch and stayed untouched",
          isHidden: true,
          sql: `SELECT order_id FROM orders
WHERE order_id = 5001 AND (status <> 'placed' OR updated_at <> '2026-07-01 08:15:00')`,
        },
        {
          suite: "endstate",
          name: "the redelivered duplicate did not create a second row for 5005",
          isHidden: true,
          sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM orders WHERE order_id = 5005) <> 1`,
        },
      ],
    }),
  ],
}

const timeTravelCompaction: SqlLesson = {
  id: "de-l7-time-travel-compaction",
  title: "Time Travel, Snapshot Expiry, and the Compaction Plan",
  summary:
    "Reconstruct a table as of an earlier snapshot from metadata alone, then pick the compaction candidates that fix streaming's small-files problem.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "time travel",
    "snapshot expiry",
    "compaction",
    "small files problem",
    "target file sizes",
    "aggregation",
    "HAVING",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Time travel is just a WHERE clause

Once a table is a chain of snapshots, reading the past stops being a feature and becomes arithmetic. The file set as of snapshot **S** is every file that was **added at or before S** and **not deleted at or before S**:

\`\`\`sql
WHERE added_snapshot_id <= S
  AND (deleted_snapshot_id IS NULL OR deleted_snapshot_id > S)
\`\`\`

That is the whole mechanism. No copies were kept, nothing was backed up. The old files are still in the bucket because a later commit only stopped pointing at them, and the metadata still records which snapshot did that.

Two uses pay for the feature:

- **Debugging a bad deploy.** A model change lands, the numbers move, and nobody can tell whether the data or the logic changed. Querying the table as of yesterday's snapshot answers it in one query, and if the data is the problem you can roll the table back to that snapshot instead of rebuilding it.
- **Reproducing a number.** A report published last Tuesday can be regenerated exactly, because the table as it stood last Tuesday still exists. This is what auditors and finance teams mean by reproducibility.

The tension is the bill and the law. Every retained snapshot pins the files it references, so a table that never expires snapshots keeps paying storage for data it replaced months ago. **Snapshot expiry** is the maintenance operation that drops old snapshots and physically deletes the files no surviving snapshot references. That also means a deleted row is not really gone until every snapshot that contained it expires, which matters when the deletion was a GDPR erasure request. The standard answer is a retention window short enough to satisfy the policy, typically days, not years.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["file added at", "file deleted at", "live now?", "in snapshot 1004?"],
  "rows": [
    ["1001", "1003", "no", "no, deleted before 1004"],
    ["1003", "(null)", "yes", "yes"],
    ["1004", "1005", "no", "yes, deleted after 1004"],
    ["1005", "(null)", "yes", "no, added after 1004"]
  ],
  "highlightCols": ["in snapshot 1004?"],
  "caption": "The two rows in the middle are the ones that separate a correct time-travel query from a wrong one."
}
\`\`\`

## The small-files problem, and the fix that lives in the table

A streaming writer commits every few minutes. Each commit writes at least one file per partition, so a day of five-minute micro-batches leaves hundreds of tiny files in a single partition. Level 6 taught why that hurts on the read side: per-file overhead, a request to object storage for every one of them, and row groups too small for compression or statistics to do anything useful. A partition of 200 files at 3 MB each is strictly worse than the same bytes in two files.

The table format is what fixes it **in place**. **Compaction** (in Iceberg, the \`rewrite_data_files\` procedure) reads the small files in a partition, writes a few large ones, and commits the swap as one snapshot. Readers never see a partial state, and no path changes, so nothing downstream needs to know it happened. The same operation folds merge-on-read delete files into the data, which is what keeps that write mode from degrading over time.

One unit note first, because the switch is silent otherwise. Iceberg's \`target-file-size-bytes\` is a binary size, so this lesson counts **1 MB as 1048576 bytes**, where Level 6's storage inventory counted it as 1,000,000. The two conventions land within 5% of each other and neither target moves because of it, but an \`avg_file_mb\` computed here is not directly comparable to one you computed a level ago. Whichever you use, say which one you used.

The number to carry into an interview is the target: **128 MB to 1 GB per file**. That range is not arbitrary. It is large enough that per-file overhead disappears and row groups are big enough for statistics to prune well, and small enough that a single file does not become one enormous unsplittable task. On AWS, S3 Tables runs this compaction for you as a managed feature and bills for it, which tells you how routinely it is needed.

So a compaction plan is a metadata query. Group the live files by partition, count them, average their size, and keep the partitions where the count is high **and** the average is small. Both halves matter, and that is the part people get wrong.

## Reading the plan honestly

A partition with many files is not automatically broken. A genuinely busy day can hold nine files of 200 MB each, which is a healthy layout and rewriting it would burn compute for nothing. The signal is many files **and** a small average size. Filtering on the count alone schedules pointless work; filtering on average size alone flags a quiet day that only ever held three small files, where rewriting three into one saves nothing and costs a commit. The seed you are about to query has one of each, so a plan that drops either half returns the wrong list.

The third half-filter is easy to forget: the live test. If you group before filtering out the files a later commit already replaced, a partition that was compacted months ago still looks like a swarm of small files, and you schedule a rewrite of data that no longer exists. Filter on \`deleted_snapshot_id IS NULL\` first, then group.

**Common mistake:** running the time-travel filter as \`deleted_snapshot_id IS NULL AND added_snapshot_id <= S\`. That answers "which files are live today and existed by S," which is not the same question. It silently drops every file that was live at S and deleted afterwards, which is usually most of what you were looking for.

**Interview nuance:** "you have millions of small files, what do you do?" is looking for compaction plus the numbers, not "delete it and reload." A complete answer names the cause (frequent commits or an over-granular partition key), the fix (compaction to a 128 MB to 1 GB target, scheduled as table maintenance), and the prevention (fewer, larger commits, or a coarser partition key). Mentioning that the format lets you do it without changing any downstream path is the detail that lands.

> **On a real platform this differs.** You would time travel with \`SELECT ... FOR SYSTEM_VERSION AS OF 1004\` or \`FOR SYSTEM_TIME AS OF '2026-06-16'\`, and compact with \`CALL catalog.system.rewrite_data_files(table => 'analytics.events', options => map('target-file-size-bytes','536870912'))\`, then \`expire_snapshots\` to reclaim the storage. The planning query you are about to write is what the engine runs internally to decide which partitions are worth rewriting, and it is also what you write by hand when you are deciding whether the maintenance job is configured correctly.`,
    demoSeedSql: ICEBERG_TIMELINE_SEED,
    demoCode: `-- The layout the table is actually in right now: live files per partition and their average size.
-- The streaming partitions stand out immediately.
SELECT partition_dt,
       COUNT(*) AS live_files,
       ROUND(AVG(file_size_in_bytes) / 1048576.0, 1) AS avg_file_mb
FROM files
WHERE deleted_snapshot_id IS NULL
GROUP BY partition_dt
ORDER BY partition_dt;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-time-travel-compaction-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the table's file set as of snapshot \`1004\`, as \`(file_path, record_count)\`, in \`file_path\` order, over \`files(file_path, partition_dt, record_count, file_size_in_bytes, added_snapshot_id, deleted_snapshot_id)\`.

A file belonged to snapshot 1004 when it was added at or before 1004 and was not yet deleted at 1004. A file deleted by a later snapshot still counts, and a file added by a later snapshot does not.`,
    starterCode: `-- The file set as of snapshot 1004, in path order.
SELECT file_path, record_count
FROM files
;`,
    hints: [
      "The first half is `added_snapshot_id <= 1004`.",
      "The second half has two cases: the file was never deleted, or it was deleted by a snapshot after 1004. Write it as `(deleted_snapshot_id IS NULL OR deleted_snapshot_id > 1004)`.",
      "Keep the two cases in parentheses, otherwise `AND` binds tighter than `OR` and the filter falls apart.",
      "`ORDER BY file_path` gives the requested path order.",
    ],
    referenceSolution: `SELECT file_path, record_count
FROM files
WHERE added_snapshot_id <= 1004
  AND (deleted_snapshot_id IS NULL OR deleted_snapshot_id > 1004)
ORDER BY file_path;`,
    singleFile: {
      seedSql: ICEBERG_TIMELINE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["file_path", "record_count"],
        rows: [
          ["s3://lake/warehouse/events/data/dt=2026-05-19/00011-3-2001.parquet", 875000],
          ["s3://lake/warehouse/events/data/dt=2026-05-19/00012-3-2002.parquet", 838000],
          ["s3://lake/warehouse/events/data/dt=2026-05-20/00003-3-c9d2.parquet", 1060000],
          ["s3://lake/warehouse/events/data/dt=2026-05-20/00004-3-d5f8.parquet", 995000],
          ["s3://lake/warehouse/events/data/dt=2026-05-21/00001-2-e2a7.parquet", 1120000],
          ["s3://lake/warehouse/events/data/dt=2026-05-21/00002-2-f6b3.parquet", 1048000],
          ["s3://lake/warehouse/events/data/dt=2026-06-15/00001-4-a8c1.parquet", 640000],
          ["s3://lake/warehouse/events/data/dt=2026-06-15/00002-4-b3d9.parquet", 612000],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-time-travel-compaction-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the compaction plan as \`(partition_dt, file_count, avg_file_mb, total_mb)\` over \`files\`: among live files only, keep the partitions holding more than 8 files whose average file is under 32 MB, worst first.

Treat 1 MB as 1048576 bytes, and round \`avg_file_mb\` and \`total_mb\` to 2 decimals. Worst first means the most files first, breaking ties by the smaller average file. Alias the columns exactly as listed.`,
    starterCode: `-- The compaction plan: live partitions with too many files that are too small.
`,
    hints: [
      "Live files only: `WHERE deleted_snapshot_id IS NULL`, before any grouping.",
      "Group by `partition_dt`, then `COUNT(*)`, `AVG(file_size_in_bytes)`, and `SUM(file_size_in_bytes)`.",
      "Both thresholds are conditions on aggregates, so they belong in `HAVING`: more than 8 files and an average under `32 * 1048576` bytes.",
      "Convert to MB by dividing by `1048576.0` (the decimal point keeps it real division), then `ROUND(..., 2)`.",
      "`ORDER BY file_count DESC, avg_file_mb` puts the worst partition first.",
    ],
    singleFile: {
      seedSql: ICEBERG_TIMELINE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["partition_dt", "file_count", "avg_file_mb", "total_mb"],
        rows: [
          ["2026-07-02", 12, 4.58, 55],
          ["2026-07-01", 10, 4.7, 47],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-time-travel-compaction-drill-1",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns how many bytes could be physically deleted from object storage if every snapshot committed before \`'2026-06-01'\` expires, as \`(reclaimable_bytes)\`, over \`files\` and \`snapshots\`.

A data file becomes deletable once no surviving snapshot references it, which is true exactly when the snapshot that stopped pointing at it committed before the expiry cutoff.`,
      starterCode: `-- Bytes reclaimable when snapshots committed before 2026-06-01 expire.
SELECT
FROM files f
JOIN snapshots s ON s.snapshot_id = f.deleted_snapshot_id
;`,
      hints: [
        "Only files with a non-NULL `deleted_snapshot_id` can ever be reclaimed, and the join to `snapshots` enforces that for you.",
        "Join on `s.snapshot_id = f.deleted_snapshot_id` to reach the commit time of the deletion.",
        "Keep `s.committed_at < '2026-06-01'`, then `SUM(f.file_size_in_bytes) AS reclaimable_bytes`.",
        "A file deleted by a snapshot that survives the expiry is still referenced by that snapshot, so it does not count.",
      ],
      referenceSolution: `SELECT SUM(f.file_size_in_bytes) AS reclaimable_bytes
FROM files f
JOIN snapshots s ON s.snapshot_id = f.deleted_snapshot_id
WHERE s.committed_at < '2026-06-01';`,
      singleFile: {
        seedSql: ICEBERG_TIMELINE_SEED,
        assertColumnNames: true,
        expected: { columns: ["reclaimable_bytes"], rows: [[578813952]] },
      },
    },
  ],
}

export const level7Module3: SqlModule = {
  id: "de-l7-lakehouse-iceberg",
  title: "Module 7.3: The Lakehouse and Open Table Formats",
  description:
    "What Iceberg adds on top of the files-plus-catalog world Level 6 built: transactions and a metadata tree of snapshots and manifests, MERGE semantics that survive a rerun, time travel straight out of the metadata, and the compaction plan that fixes the small files streaming writes leave behind.",
  lessons: [icebergMetadata, upsertMergeSemantics, timeTravelCompaction],
}
