/**
 * Level 7, Module 7.2 — Dimensional Modeling: Rehearsal and the Missing Debate.
 *
 * Deliberately NOT a reteach. SQL Module 3.5 already owns declared grain, facts, and
 * dimensions; SQL Module 4.3b owns star vs snowflake, fact types, measure additivity, and
 * SCD Type 2 through its loader capstone; SQL Level 5 already grades the point-in-time
 * (as-of) join. This module compresses that canon into one review screen per lesson and
 * then grades only what is NEW: an executable grain audit, the wrong-sum/right-sum
 * side-by-side that makes a semi-additive trap visible, a timed SCD2 change-batch applier,
 * and the one modeling decision no earlier level teaches — Kimball vs One Big Table with
 * the ~10 GB join-side heuristic (RESEARCH.md §2.4, implication 3).
 *
 * Device: the same "query the platform's own metadata" device Level 6 proved, staged on the
 * verbatim interview scenario the research cites (a ride-share warehouse where a driver
 * moves cities, RESEARCH.md §6.5). The SCD2 lesson uses the workspace script runner
 * (multi-statement script + hidden assertion queries + an idempotency double-run) because
 * "apply the change batch cleanly, twice" is the thing candidates actually fail.
 *
 * Grading policy for the module: every money-bearing output column states an explicit
 * ROUND(..., 2) so a result never depends on floating-point summation order.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"
import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Seeds for Module 7.2. One ride-share warehouse, carried across all four lessons, so the
// learner rehearses on the scenario the interview corpus actually uses.
// ---------------------------------------------------------------------------

/** A raw extract straight off the source system: wide, undeduplicated, three re-emitted rows. */
const STAGING_TRIPS_SEED = `CREATE TABLE staging_trips (
  trip_id      TEXT,
  rider_id     TEXT,
  driver_id    INTEGER,
  driver_name  TEXT,
  driver_city  TEXT,    -- the driver's home city, repeated on every one of their trip rows
  city         TEXT,    -- the city the trip was requested in
  requested_at TEXT,
  completed_at TEXT,    -- a corrected re-emission of a trip carries a LATER completed_at
  fare_usd     REAL,    -- a correction can move the fare DOWN, so latest-wins <> highest-wins
  tip_usd      REAL
);
INSERT INTO staging_trips (trip_id, rider_id, driver_id, driver_name, driver_city, city, requested_at, completed_at, fare_usd, tip_usd) VALUES
  ('T-1001', 'R-501', 42, 'Maya Okafor', 'Detroit',   'Detroit',   '2026-06-01 08:12:00', '2026-06-01 08:31:00', 18.40, 3.00),
  ('T-1002', 'R-502', 42, 'Maya Okafor', 'Detroit',   'Detroit',   '2026-06-01 09:02:00', '2026-06-01 09:20:00', 22.10, 0.00),
  ('T-1002', 'R-502', 42, 'Maya Okafor', 'Detroit',   'Detroit',   '2026-06-01 09:02:00', '2026-06-01 09:25:00', 24.60, 0.00),
  ('T-1003', 'R-503', 51, 'Ivan Petrov', 'Ann Arbor', 'Ann Arbor', '2026-06-01 10:05:00', '2026-06-01 10:19:00', 12.75, 2.50),
  ('T-1004', 'R-504', 51, 'Ivan Petrov', 'Ann Arbor', 'Ann Arbor', '2026-06-01 11:40:00', '2026-06-01 12:02:00', 31.20, 5.00),
  ('T-1005', 'R-505', 63, 'Lena Diaz',   'Chicago',   'Chicago',   '2026-06-01 13:11:00', '2026-06-01 13:29:00', 27.90, 4.00),
  ('T-1005', 'R-505', 63, 'Lena Diaz',   'Chicago',   'Chicago',   '2026-06-01 13:11:00', '2026-06-01 13:34:00', 29.40, 4.00),
  ('T-1005', 'R-505', 63, 'Lena Diaz',   'Chicago',   'Chicago',   '2026-06-01 13:11:00', '2026-06-01 13:41:00', 26.40, 4.00),
  ('T-1006', 'R-506', 63, 'Lena Diaz',   'Chicago',   'Chicago',   '2026-06-01 14:20:00', '2026-06-01 14:47:00', 44.05, 6.50),
  ('T-1007', 'R-507', 42, 'Maya Okafor', 'Detroit',   'Detroit',   '2026-06-01 15:30:00', '2026-06-01 15:52:00', 16.85, 0.00),
  ('T-1008', 'R-508', 74, 'Sam Byrne',   'Detroit',   'Detroit',   '2026-06-01 16:02:00', '2026-06-01 16:24:00', 19.95, 3.25),
  ('T-1009', 'R-509', 74, 'Sam Byrne',   'Detroit',   'Detroit',   '2026-06-01 17:15:00', '2026-06-01 17:44:00', 38.60, 7.00);`

/**
 * A periodic snapshot fact: one row per driver per snapshot date, three dates per month, with
 * one deliberate hole (driver 85 has no 2026-07-31 row) so a hard-coded month-end equality
 * filter grades differently from the ranked latest-in-the-period answer.
 */
const WALLET_SNAPSHOT_SEED = `CREATE TABLE fact_wallet_snapshot (
  driver_id   INTEGER,
  as_of_date  TEXT,    -- the snapshot date; the last one in a month is the month-end balance
  balance_usd REAL     -- the wallet balance AS OF that date, not a change during it
);
INSERT INTO fact_wallet_snapshot (driver_id, as_of_date, balance_usd) VALUES
  (42, '2026-06-10',  980.00), (42, '2026-06-20', 1105.75), (42, '2026-06-30', 1240.50),
  (51, '2026-06-10', 1520.00), (51, '2026-06-20', 1810.30), (51, '2026-06-30', 1975.40),
  (63, '2026-06-10',  890.15), (63, '2026-06-20',  805.60), (63, '2026-06-30',  720.80),
  (74, '2026-06-10',  640.60), (74, '2026-06-20',  715.40), (74, '2026-06-30',  860.25),
  (85, '2026-06-10',  300.55), (85, '2026-06-20',  375.20), (85, '2026-06-30',  430.10),
  (96, '2026-06-10', 1240.00), (96, '2026-06-20', 1455.85), (96, '2026-06-30', 1610.95),
  (42, '2026-07-10', 1310.20), (42, '2026-07-20', 1402.65), (42, '2026-07-31', 1520.00),
  (51, '2026-07-10', 2050.75), (51, '2026-07-20', 1990.40), (51, '2026-07-31', 2115.60),
  (63, '2026-07-10',  760.25), (63, '2026-07-20',  815.70), (63, '2026-07-31',  402.40),
  (74, '2026-07-10',  905.35), (74, '2026-07-20',  980.10), (74, '2026-07-31', 1044.75),
  -- driver 85 has NO 2026-07-31 row on purpose: an equality filter on the month-end date
  -- drops them from July entirely, which is the failure the lesson warns about.
  (85, '2026-07-10',  470.90), (85, '2026-07-20',  512.30),
  (96, '2026-07-10', 1700.10), (96, '2026-07-20', 1655.25), (96, '2026-07-31', 1788.30);`

/** A transaction fact beside the snapshot: fully additive, and uneven per day on purpose. */
const PAYOUTS_SEED = `CREATE TABLE fact_payouts (
  payout_id  TEXT,
  driver_id  INTEGER,
  paid_at    TEXT,
  amount_usd REAL
);
INSERT INTO fact_payouts (payout_id, driver_id, paid_at, amount_usd) VALUES
  ('P-1',  42, '2026-06-05',  500.00),
  ('P-2',  51, '2026-06-05',  300.00),
  ('P-3',  63, '2026-06-05',  250.00),
  ('P-4',  74, '2026-06-12',  900.00),
  ('P-5',  85, '2026-06-19',  150.00),
  ('P-6',  96, '2026-06-19',  450.00),
  ('P-7',  42, '2026-06-26',  600.00),
  ('P-8',  51, '2026-06-26',  200.00),
  ('P-9',  63, '2026-06-26',  700.00),
  ('P-10', 96, '2026-07-03', 1000.00);`

const DIM_DRIVER_SEED = `CREATE TABLE dim_driver (
  driver_id INTEGER,
  home_city TEXT
);
INSERT INTO dim_driver (driver_id, home_city) VALUES
  (42, 'Detroit'),
  (51, 'Ann Arbor'),
  (63, 'Chicago'),
  (74, 'Detroit'),
  (85, 'Ann Arbor'),
  (96, 'Chicago');`

const WALLET_LESSON_SEED = WALLET_SNAPSHOT_SEED + "\n" + PAYOUTS_SEED + "\n" + DIM_DRIVER_SEED

/**
 * A Type 2 dimension mid-history: driver 42 has already moved Detroit to Ann Arbor on
 * 2026-03-01, so the review demo has two version rows to join across. Everyone else is on a
 * single open version, waiting for the change batch.
 */
const DIM_DRIVER_SCD_SEED = `CREATE TABLE dim_driver_scd (
  driver_key  INTEGER PRIMARY KEY,   -- surrogate key: one per VERSION row, not per driver
  driver_id   INTEGER,               -- the natural key from the source system
  driver_name TEXT,
  home_city   TEXT,
  valid_from  TEXT,
  valid_to    TEXT,                  -- '9999-12-31' on the open (current) version
  is_current  INTEGER
);
INSERT INTO dim_driver_scd (driver_key, driver_id, driver_name, home_city, valid_from, valid_to, is_current) VALUES
  (1, 42, 'Maya Okafor', 'Detroit',   '2025-09-01', '2026-03-01', 0),
  (2, 42, 'Maya Okafor', 'Ann Arbor', '2026-03-01', '9999-12-31', 1),
  (3, 51, 'Ivan Petrov', 'Ann Arbor', '2025-10-15', '9999-12-31', 1),
  (4, 63, 'Lena Diaz',   'Chicago',   '2025-11-02', '9999-12-31', 1),
  (5, 74, 'Sam Byrne',   'Detroit',   '2026-01-20', '9999-12-31', 1),
  (6, 85, 'Priya Raman', 'Ann Arbor', '2026-02-08', '9999-12-31', 1);`

/** Trips straddling driver 42's move, so an as-of join splits their revenue across two cities. */
const FACT_TRIPS_SEED = `CREATE TABLE fact_trips (
  trip_id      TEXT,
  driver_id    INTEGER,
  completed_at TEXT,
  fare_usd     REAL
);
INSERT INTO fact_trips (trip_id, driver_id, completed_at, fare_usd) VALUES
  ('T-2001', 42, '2026-01-15', 24.50),
  ('T-2002', 42, '2026-02-20', 31.00),
  ('T-2003', 42, '2026-04-05', 18.75),
  ('T-2004', 42, '2026-05-11', 27.25),
  ('T-2005', 51, '2026-02-02', 15.60),
  ('T-2006', 63, '2026-03-18', 42.10),
  ('T-2007', 74, '2026-04-22', 33.40),
  ('T-2008', 85, '2026-05-30', 21.05),
  ('T-2009', 63, '2026-05-09', 29.90);`

/** The incoming change batch: two genuine moves plus one no-op that must not create a version. */
const DRIVER_UPDATES_SEED = `CREATE TABLE driver_updates (
  driver_id      INTEGER,
  new_city       TEXT,
  effective_date TEXT
);
INSERT INTO driver_updates (driver_id, new_city, effective_date) VALUES
  (51, 'Detroit',   '2026-06-01'),
  (63, 'Ann Arbor', '2026-06-01'),
  (74, 'Detroit',   '2026-06-01');`

const SCD2_TEACH_SEED = DIM_DRIVER_SCD_SEED + "\n" + FACT_TRIPS_SEED
const SCD2_APPLY_SEED = DIM_DRIVER_SCD_SEED + "\n" + DRIVER_UPDATES_SEED

/** A second batch where one driver moves twice, so the versions have to chain in date order. */
const SCD2_PRACTICE_SEED = `CREATE TABLE dim_driver_scd (
  driver_key  INTEGER PRIMARY KEY,
  driver_id   INTEGER,
  driver_name TEXT,
  home_city   TEXT,
  valid_from  TEXT,
  valid_to    TEXT,
  is_current  INTEGER
);
INSERT INTO dim_driver_scd (driver_key, driver_id, driver_name, home_city, valid_from, valid_to, is_current) VALUES
  (1, 42, 'Maya Okafor', 'Ann Arbor', '2026-03-01', '9999-12-31', 1),
  (2, 51, 'Ivan Petrov', 'Ann Arbor', '2025-10-15', '9999-12-31', 1),
  (3, 63, 'Lena Diaz',   'Chicago',   '2025-11-02', '9999-12-31', 1),
  (4, 74, 'Sam Byrne',   'Detroit',   '2026-01-20', '9999-12-31', 1);

CREATE TABLE driver_updates (
  driver_id      INTEGER,
  new_city       TEXT,
  effective_date TEXT
);
INSERT INTO driver_updates (driver_id, new_city, effective_date) VALUES
  (51, 'Detroit',   '2026-06-01'),
  (51, 'Chicago',   '2026-09-15'),
  (63, 'Ann Arbor', '2026-07-10');`

/** The same dimension with one broken driver planted: driver 96's two windows overlap. */
const DIM_DRIVER_SCD_OVERLAP_SEED = `CREATE TABLE dim_driver_scd (
  driver_key  INTEGER PRIMARY KEY,
  driver_id   INTEGER,
  driver_name TEXT,
  home_city   TEXT,
  valid_from  TEXT,
  valid_to    TEXT,
  is_current  INTEGER
);
INSERT INTO dim_driver_scd (driver_key, driver_id, driver_name, home_city, valid_from, valid_to, is_current) VALUES
  (1, 42, 'Maya Okafor', 'Detroit',   '2025-09-01', '2026-03-01', 0),
  (2, 42, 'Maya Okafor', 'Ann Arbor', '2026-03-01', '9999-12-31', 1),
  (3, 51, 'Ivan Petrov', 'Ann Arbor', '2025-10-15', '9999-12-31', 1),
  (4, 63, 'Lena Diaz',   'Chicago',   '2025-11-02', '9999-12-31', 1),
  (5, 96, 'Omar Haddad', 'Detroit',   '2025-08-01', '2026-02-15', 0),
  (6, 96, 'Omar Haddad', 'Chicago',   '2026-01-10', '9999-12-31', 1);`

/**
 * Per-mart warehouse metadata for the Kimball-vs-OBT decision. `total_dim_gb` is the JOIN
 * SIDE, the number the ~10 GB heuristic is about; the marts straddle both sides of the line.
 *
 * Map deviation: two marts sit in the 5-10 GB band on purpose. The map's "recommendation
 * flips at a 5 GB threshold" drill has no output at all unless some join side falls between
 * the two thresholds, so `support_tickets` (7.3) and `fleet_maintenance` (6.1) carry it.
 */
const MART_PROFILES_SEED = `CREATE TABLE mart_profiles (
  mart                  TEXT,
  fact_rows             INTEGER,
  fact_row_bytes        INTEGER,  -- bytes per fact row in the star (narrow: measures + keys)
  denorm_extra_bytes    INTEGER,  -- bytes per row ADDED by pre-joining the dimensions in
  fact_gb               REAL,     -- fact_rows * fact_row_bytes, in GB (1 GB = 1e9 bytes)
  total_dim_gb          REAL,     -- the join side: every dimension this fact joins to
  dims_reused_elsewhere INTEGER,  -- 1 when other facts conform to these same dimensions
  dim_change_rate_pct   REAL,     -- percent of dimension attributes that change per cycle
  bi_only               INTEGER   -- 1 when a BI tool is the only consumer of this mart
);
INSERT INTO mart_profiles (mart, fact_rows, fact_row_bytes, denorm_extra_bytes, fact_gb, total_dim_gb, dims_reused_elsewhere, dim_change_rate_pct, bi_only) VALUES
  ('ride_share_trips',      2400000000,  96, 140, 230.4,  3.2, 1, 6.0, 0),
  ('marketing_attribution',  180000000, 120, 210,  21.6, 14.5, 0, 1.5, 1),
  ('finance_gl',              90000000, 140, 160,  12.6,  6.4, 1, 2.0, 0),
  ('support_tickets',         40000000, 110, 180,   4.4,  7.3, 0, 1.0, 1),
  ('driver_payouts',         300000000,  90, 130,  27.0, 11.8, 0, 9.0, 0),
  ('app_events',            5000000000,  72, 190, 360.0, 18.7, 0, 0.5, 1),
  ('fleet_maintenance',       12000000, 125, 160,   1.5,  6.1, 0, 3.0, 1),
  ('rider_ltv',              260000000, 100, 240,  26.0, 12.4, 1, 4.0, 1);`

// ---------------------------------------------------------------------------
// Module 7.2 — Dimensional Modeling: Rehearsal and the Missing Debate
// ---------------------------------------------------------------------------

const grainAudit: SqlLesson = {
  id: "de-l7-grain-audit",
  title: "Grain Rehearsal: Say the Sentence, Then Prove It in SQL",
  summary:
    "How to prove a table's declared grain with executable SQL, on a raw ride-share extract, before you build a star schema on top of it.",
  estimatedMinutes: 22,
  difficulty: "medium",
  skills: [
    "grain declaration",
    "grain-violation auditing",
    "GROUP BY",
    "HAVING",
    "ROW_NUMBER dedup",
    "interview rehearsal",
  ],
  teach: {
    estimatedMinutes: 10,
    markdown: `## The review screen (you already learned this)

Level 3's lesson "Facts, Dimensions, and Grain" taught the whole idea, so this is a pointer, not a reteach:

- The **grain** is the sentence that says what one row of a fact table means. "One row per completed trip." "One row per order line." "One row per driver per day."
- Declare it **before** you draw a single table. Every later decision, which measures are allowed, which dimensions can attach, which duplicates are bugs, falls out of that sentence.
- Facts stay **narrow** (keys plus measures). Dimensions get **wide** (descriptive attributes).
- Saying the grain out loud, first, is a named strong-candidate signal in modeling interviews.

That is the part you already have. Here is the part this lesson adds.

## The follow-up that separates rehearsed candidates

You say "one row per completed trip." A good interviewer does not say "great." They say: **prove the data respects it.**

The proof is a query, and it is short. Group the raw extract by the key your grain sentence names, count the rows in each group, and keep only the groups holding more than one. If that query returns nothing, the extract honors the declared grain. If it returns rows, you found duplicates before they inflated a single number.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Staging extract", "note": "raw rows, grain unproven" },
    { "label": "Declare grain", "note": "one row per completed trip" },
    { "label": "Grain audit", "note": "GROUP BY key HAVING COUNT(*) > 1" },
    { "label": "Dedup", "note": "keep the latest row per key" },
    { "label": "Clean fact", "note": "grain now guaranteed" }
  ],
  "caption": "The grain audit sits between the extract and the fact table. It converts the grain sentence from a claim into evidence."
}
\`\`\`

## The scenario

A ride-share company hands you \`staging_trips\`, a raw extract from the trips service. It is wide: it carries the driver's name and home city on every trip row, which is normal for an extract and wrong for a fact table. It also re-emits corrected rows: when a fare is adjusted, the service sends the whole trip again with a later \`completed_at\` instead of updating in place.

So the extract has more rows than trips. Run the audit and you can say which trips, and how badly, in one query.

## Repairing the grain

Once the audit finds duplicates, the repair is the windowed-dedup pattern you already know: number the rows inside each key, newest first, and keep number one.

\`\`\`sql
WITH latest AS (
  SELECT trip_id, fare_usd,
         ROW_NUMBER() OVER (PARTITION BY trip_id ORDER BY completed_at DESC) AS rn
  FROM staging_trips
)
SELECT ROUND(SUM(fare_usd), 2) AS clean_revenue
FROM latest
WHERE rn = 1;
\`\`\`

\`PARTITION BY trip_id\` restarts the numbering inside each trip. \`ORDER BY completed_at DESC\` decides which version wins. \`WHERE rn = 1\` keeps exactly one row per trip, which is the declared grain, restored.

**Common mistake:** deduplicating with \`SELECT DISTINCT\` on the whole row. The corrected rows differ in \`fare_usd\` and \`completed_at\`, so \`DISTINCT\` keeps every one of them and reports success. Dedup by the **grain key**, then pick a winner by a rule you can defend.

**Interview nuance:** in a take-home, running the grain audit before you build anything is a 60-second move that reviewers notice. It is the difference between "I assumed the extract was clean" and "I checked, and two trips were re-emitted, so I kept the latest version of each." Narrate the rule you chose for picking the winner. That rule is the actual judgment call.

> **On a real platform this differs.** Here the audit is an ad-hoc query you run by hand. In a warehouse it becomes a scheduled test: dbt's \`unique\` test on the grain key, or Great Expectations' \`expect_compound_columns_to_be_unique\`, both of which fail the build instead of the dashboard. The SQL underneath is the same \`GROUP BY key HAVING COUNT(*) > 1\` you are about to write.`,
    demoSeedSql: STAGING_TRIPS_SEED,
    demoCode: `-- The grain check itself: how many rows does the extract hold per trip?
SELECT trip_id, COUNT(*) AS row_count
FROM staging_trips
GROUP BY trip_id
ORDER BY row_count DESC, trip_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-grain-audit-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every trip violating the declared grain of one row per completed trip, as \`(trip_id, row_count)\`, worst first, over \`staging_trips(trip_id, rider_id, driver_id, driver_name, driver_city, city, requested_at, completed_at, fare_usd, tip_usd)\`.

Group by \`trip_id\`, count the rows in each group, and keep only groups holding more than one row. Alias the count exactly \`row_count\`, ordered by \`row_count\` descending then \`trip_id\`.`,
    starterCode: `-- Grain audit: which trip_ids appear more than once in the extract?
SELECT
  -- one row per offending trip, with how many rows the extract holds for it
FROM staging_trips;`,
    hints: [
      "Group by `trip_id` so each trip collapses to one group.",
      "`COUNT(*) AS row_count` is how many rows the extract holds for that trip.",
      "`HAVING COUNT(*) > 1` filters groups after aggregation. A plain `WHERE` cannot see the count.",
      "Order by `row_count DESC, trip_id` so the worst offender is first and ties are stable.",
    ],
    referenceSolution: `SELECT trip_id, COUNT(*) AS row_count
FROM staging_trips
GROUP BY trip_id
HAVING COUNT(*) > 1
ORDER BY row_count DESC, trip_id;`,
    singleFile: {
      seedSql: STAGING_TRIPS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["trip_id", "row_count"],
        rows: [
          ["T-1005", 3],
          ["T-1002", 2],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-grain-audit-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the true total fare revenue as \`(clean_revenue)\` rounded to 2 decimals, over the same \`staging_trips\` table.

Keep one row per \`trip_id\` before summing, and when a trip has several rows the one with the latest \`completed_at\` wins. Sum \`fare_usd\` over those surviving rows only, and alias the result exactly \`clean_revenue\`.`,
    starterCode: `-- Revenue at the declared grain: one row per trip, latest completed_at wins.
WITH latest AS (
  -- number the rows inside each trip, newest first
  SELECT
  FROM staging_trips
)
SELECT
FROM latest;`,
    hints: [
      "Number the rows inside each trip: `ROW_NUMBER() OVER (PARTITION BY trip_id ORDER BY completed_at DESC) AS rn`.",
      "`PARTITION BY trip_id` restarts the numbering per trip; `ORDER BY completed_at DESC` puts the newest version at 1.",
      "Filter the CTE with `WHERE rn = 1` so exactly one row per trip survives.",
      "`ROUND(SUM(fare_usd), 2) AS clean_revenue` finishes it. Sum the fare only, not the tip.",
    ],
    singleFile: {
      seedSql: STAGING_TRIPS_SEED,
      assertColumnNames: true,
      expected: { columns: ["clean_revenue"], rows: [[232.8]] },
    },
  },
  extraPractice: [
    {
      id: "de-l7-grain-audit-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the raw row count next to the number of distinct grain keys as \`(raw_rows, distinct_trips)\`, in one row, over \`staging_trips\`.`,
      starterCode: `-- One row: how many rows the extract holds, and how many trips it actually describes.
SELECT
FROM staging_trips;`,
      hints: [
        "`COUNT(*)` counts rows; `COUNT(DISTINCT trip_id)` counts grain keys.",
        "Alias them exactly `raw_rows` and `distinct_trips`.",
      ],
      referenceSolution: `SELECT COUNT(*) AS raw_rows,
       COUNT(DISTINCT trip_id) AS distinct_trips
FROM staging_trips;`,
      singleFile: {
        seedSql: STAGING_TRIPS_SEED,
        assertColumnNames: true,
        expected: { columns: ["raw_rows", "distinct_trips"], rows: [[12, 9]] },
      },
    },
    {
      id: "de-l7-grain-audit-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns how much the duplicate rows inflate fare revenue, as \`(inflation_pct)\` rounded to 1 decimal, over \`staging_trips\`.

Inflation percent is the raw fare total minus the clean fare total (latest row per \`trip_id\`), divided by the clean total, times 100.`,
      starterCode: `-- How wrong would the naive SUM(fare_usd) be?
WITH latest AS (
  SELECT
  FROM staging_trips
)
SELECT
FROM latest;`,
      hints: [
        "Build the clean total first with `ROW_NUMBER() OVER (PARTITION BY trip_id ORDER BY completed_at DESC)` and `WHERE rn = 1`.",
        "The raw total is a plain `SUM(fare_usd)` over `staging_trips`.",
        "Multiply by `100.0`, not `100`, so the division stays real-valued.",
        "`ROUND(..., 1)` and alias exactly `inflation_pct`.",
      ],
      referenceSolution: `WITH latest AS (
  SELECT trip_id, fare_usd,
         ROW_NUMBER() OVER (PARTITION BY trip_id ORDER BY completed_at DESC) AS rn
  FROM staging_trips
),
clean AS (
  SELECT SUM(fare_usd) AS clean_revenue FROM latest WHERE rn = 1
),
raw AS (
  SELECT SUM(fare_usd) AS raw_revenue FROM staging_trips
)
SELECT ROUND((raw.raw_revenue - clean.clean_revenue) * 100.0 / clean.clean_revenue, 1) AS inflation_pct
FROM raw, clean;`,
      singleFile: {
        seedSql: STAGING_TRIPS_SEED,
        assertColumnNames: true,
        expected: { columns: ["inflation_pct"], rows: [[34.1]] },
      },
    },
  ],
}

const semiAdditiveAudit: SqlLesson = {
  id: "de-l7-semi-additive-audit",
  title: "Semi-Additive Measures: The Wrong Sum and the Right Sum",
  summary:
    "Why summing a balance across days gives the wrong answer, and how one query can show the naive SUM beside the correct as-of total.",
  estimatedMinutes: 24,
  difficulty: "medium",
  skills: [
    "additive vs semi-additive measures",
    "non-additive ratios",
    "periodic snapshot facts",
    "ROW_NUMBER as-of aggregation",
    "side-by-side proof queries",
    "GROUP BY",
  ],
  teach: {
    estimatedMinutes: 11,
    markdown: `## The review screen (you already learned this)

Level 4's lesson "Fact Table Types and Measure Additivity" owns the first teaching of this, so here is the compressed version:

- A **transaction fact** stores events. One row per thing that happened, and its measures are **additive**: they sum across every dimension including time. A payout of $500 plus a payout of $300 is $800, on any day, in any city.
- A **periodic snapshot fact** stores state on a schedule. One row per entity per date, and its measures are **semi-additive**: they sum across entities on a single date, and never across dates. Six drivers' wallet balances on June 30 add up to a real number. One driver's balances on June 10, June 20, and June 30 add up to nothing at all.
- **Ratios and percentages are non-additive.** You never sum them and you never average an average. Recompute from the parts: \`SUM(numerator) / SUM(denominator)\`.

That is the ladder. Naming it is table stakes.

## What this lesson adds

Naming the trap is a knowledge answer. Interviewers get that answer from most candidates. What they rarely get is the **demonstration**: one result set holding the wrong number and the right number side by side, so the size of the error is visible instead of asserted.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["driver_id", "as_of_date", "balance_usd", "counted by the naive SUM", "counted by the as-of SUM"],
  "rows": [
    [42, "2026-06-10", 980.00, "yes", "no"],
    [42, "2026-06-20", 1105.75, "yes", "no"],
    [42, "2026-06-30", 1240.50, "yes", "yes"],
    [74, "2026-06-10", 640.60, "yes", "no"],
    [74, "2026-06-20", 715.40, "yes", "no"],
    [74, "2026-06-30", 860.25, "yes", "yes"]
  ],
  "highlightCols": ["counted by the as-of SUM"],
  "caption": "Two Detroit drivers, three June snapshots each. The naive SUM adds all six rows. The correct month-end total adds only the two rows in the highlighted column."
}
\`\`\`

The correct total for Detroit is $2,100.75, the two June 30 balances. The naive total counts every snapshot and lands on $5,542.50, about two and a half times the real figure, which is not a wallet balance, not a revenue figure, and not any quantity that exists in the business. The multiple is close to the three snapshots per month but not equal to it, because the balances grow across those snapshots rather than repeating.

## Getting to the as-of total

The pattern is the one you used for grain repair, pointed at time instead of duplicates: number each driver's snapshots newest first, keep number one, then sum across drivers.

\`\`\`sql
WITH ranked AS (
  SELECT driver_id, balance_usd,
         ROW_NUMBER() OVER (PARTITION BY driver_id ORDER BY as_of_date DESC) AS rn
  FROM fact_wallet_snapshot
  WHERE as_of_date BETWEEN '2026-06-01' AND '2026-06-30'
)
SELECT ROUND(SUM(CASE WHEN rn = 1 THEN balance_usd ELSE 0 END), 2) AS correct_total
FROM ranked;
\`\`\`

Putting both numbers in one query is what makes it a proof. \`SUM(balance_usd)\` over the same CTE gives the naive figure; \`SUM(CASE WHEN rn = 1 THEN balance_usd ELSE 0 END)\` gives the correct one. Same rows, same scan, two answers, and the interviewer can see which one the dashboard has been showing.

**Common mistake:** filtering the snapshot to a single hard-coded date (\`WHERE as_of_date = '2026-06-30'\`) and calling it solved. That works until a driver has no row on the month-end date, and then they silently vanish from the total. Ranking per driver and keeping the latest row **in the window** survives a missing snapshot; an equality filter does not.

**Interview nuance:** "which measures on your fact table are semi-additive" is the standard follow-up to any star-schema answer. The strong version of the answer is three sentences: name the measure, name the dimension it will not sum across (almost always time), and say how you aggregate it instead (latest in the period, or an average-of-day-balances if finance asks for that). Then show the side-by-side if you have a keyboard.

> **On a real platform this differs.** Bank and wallet warehouses run exactly this daily-balance snapshot, and it is usually the biggest table they own. Warehouse dialects add conveniences here: Snowflake and BigQuery let you reach for \`LAST_VALUE(...) OVER (... ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)\`, and a semantic layer lets you declare the rule once instead of re-deriving it per query: dbt's Semantic Layer (MetricFlow) declares the measure with \`non_additive_dimension: { name: metric_time, window_choice: max }\`, which is exactly "do not sum this across time, take the latest", so no analyst can sum it by accident. \`ROW_NUMBER\` is the portable version that works everywhere, including here.`,
    demoSeedSql: WALLET_SNAPSHOT_SEED,
    demoCode: `-- The wrong number and the right number for June, in one result set.
WITH ranked AS (
  SELECT driver_id, balance_usd,
         ROW_NUMBER() OVER (PARTITION BY driver_id ORDER BY as_of_date DESC) AS rn
  FROM fact_wallet_snapshot
  WHERE as_of_date BETWEEN '2026-06-01' AND '2026-06-30'
)
SELECT ROUND(SUM(balance_usd), 2) AS naive_total,
       ROUND(SUM(CASE WHEN rn = 1 THEN balance_usd ELSE 0 END), 2) AS correct_total
FROM ranked;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-semi-additive-audit-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns, per home city for June 2026, both the wrong naive sum and the correct month-end total as \`(home_city, naive_total, correct_total)\`, each rounded to 2 decimals, over \`fact_wallet_snapshot(driver_id, as_of_date, balance_usd)\` joined to \`dim_driver(driver_id, home_city)\`.

\`naive_total\` sums every June snapshot row. \`correct_total\` keeps only each driver's latest June snapshot, then sums those. Restrict to \`as_of_date\` between \`'2026-06-01'\` and \`'2026-06-30'\`, alias the columns exactly, and order by \`correct_total\` descending.`,
    starterCode: `-- The semi-additive proof: the wrong total beside the right one, per city.
WITH june AS (
  -- June snapshots, numbered per driver newest first
  SELECT
  FROM fact_wallet_snapshot
)
SELECT
FROM june
JOIN dim_driver d ON d.driver_id = june.driver_id;`,
    hints: [
      "Filter to June inside the CTE: `WHERE as_of_date BETWEEN '2026-06-01' AND '2026-06-30'`.",
      "Number each driver's June rows: `ROW_NUMBER() OVER (PARTITION BY driver_id ORDER BY as_of_date DESC) AS rn`.",
      "`ROUND(SUM(balance_usd), 2) AS naive_total` counts every row, which is the number you are proving wrong.",
      "`ROUND(SUM(CASE WHEN rn = 1 THEN balance_usd ELSE 0 END), 2) AS correct_total` counts only the latest row per driver.",
      "Join to `dim_driver` for `home_city`, group by it, and order by `correct_total DESC`.",
    ],
    referenceSolution: `WITH june AS (
  SELECT driver_id, as_of_date, balance_usd,
         ROW_NUMBER() OVER (PARTITION BY driver_id ORDER BY as_of_date DESC) AS rn
  FROM fact_wallet_snapshot
  WHERE as_of_date BETWEEN '2026-06-01' AND '2026-06-30'
)
SELECT d.home_city,
       ROUND(SUM(j.balance_usd), 2) AS naive_total,
       ROUND(SUM(CASE WHEN j.rn = 1 THEN j.balance_usd ELSE 0 END), 2) AS correct_total
FROM june j
JOIN dim_driver d ON d.driver_id = j.driver_id
GROUP BY d.home_city
ORDER BY correct_total DESC;`,
    singleFile: {
      seedSql: WALLET_LESSON_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["home_city", "naive_total", "correct_total"],
        rows: [
          ["Ann Arbor", 6411.55, 2405.5],
          ["Chicago", 6723.35, 2331.75],
          ["Detroit", 5542.5, 2100.75],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-semi-additive-audit-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the correct month-end balance per city for both month-ends as \`(home_city, month_end, correct_total)\` rounded to 2 decimals, over the same \`fact_wallet_snapshot\` and \`dim_driver\` tables.

Inside each calendar month, keep only each driver's latest snapshot, then sum those balances per city. \`month_end\` is the last snapshot date in that calendar month, which is not always the date of the row you kept: one driver has no snapshot on the July month-end and still belongs in the July total. Order by \`month_end\` then \`home_city\`.`,
    starterCode: `-- Month-end balances per city, for every month in the snapshot.
WITH ranked AS (
  -- number each driver's snapshots newest first, restarting every calendar month,
  -- and label every row with the last snapshot date its month holds
  SELECT
  FROM fact_wallet_snapshot
)
SELECT
FROM ranked;`,
    hints: [
      "`strftime('%Y-%m', as_of_date)` gives the calendar month of a snapshot date.",
      "Partition by BOTH the driver and that month so the numbering restarts every month.",
      "`MAX(as_of_date) OVER (PARTITION BY strftime('%Y-%m', as_of_date))` labels every row with its month's last snapshot date, whether or not that driver has a row on it.",
      "`WHERE rn = 1` keeps each driver's last snapshot in each month.",
      "Group by `home_city` and that month-end label, alias it `month_end`, and `ROUND(SUM(balance_usd), 2)`.",
    ],
    singleFile: {
      seedSql: WALLET_LESSON_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["home_city", "month_end", "correct_total"],
        rows: [
          ["Ann Arbor", "2026-06-30", 2405.5],
          ["Chicago", "2026-06-30", 2331.75],
          ["Detroit", "2026-06-30", 2100.75],
          ["Ann Arbor", "2026-07-31", 2627.9],
          ["Chicago", "2026-07-31", 2190.7],
          ["Detroit", "2026-07-31", 2564.75],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-semi-additive-audit-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the average payout computed two ways as \`(naive_avg, correct_avg)\`, each rounded to 2 decimals, over \`fact_payouts(payout_id, driver_id, paid_at, amount_usd)\`.

\`naive_avg\` averages the per-day averages. \`correct_avg\` recomputes from the parts: total amount divided by total payout count.`,
      starterCode: `-- Averaging an average is non-additive. Show both numbers.
WITH daily AS (
  SELECT paid_at, AVG(amount_usd) AS day_avg
  FROM fact_payouts
  GROUP BY paid_at
)
SELECT
;`,
      hints: [
        "The naive figure is `AVG(day_avg)` over the `daily` CTE, which weights a 1-payout day the same as a 3-payout day.",
        "The correct figure is `SUM(amount_usd) * 1.0 / COUNT(*)` over the raw table.",
        "Both can be scalar subqueries in a single `SELECT` with no `FROM` clause.",
      ],
      referenceSolution: `WITH daily AS (
  SELECT paid_at, AVG(amount_usd) AS day_avg
  FROM fact_payouts
  GROUP BY paid_at
)
SELECT ROUND((SELECT AVG(day_avg) FROM daily), 2) AS naive_avg,
       ROUND((SELECT SUM(amount_usd) * 1.0 / COUNT(*) FROM fact_payouts), 2) AS correct_avg;`,
      singleFile: {
        seedSql: WALLET_LESSON_SEED,
        assertColumnNames: true,
        expected: { columns: ["naive_avg", "correct_avg"], rows: [[610, 505]] },
      },
    },
    {
      id: "de-l7-semi-additive-audit-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the single driver whose wallet balance moved the most between the two months, as \`(driver_id, balance_change)\` rounded to 2 decimals, over \`fact_wallet_snapshot\`.

Use each driver's latest snapshot in each month, not a hard-coded month-end date, because one driver has no row on the July month-end. \`balance_change\` is that July balance minus that June balance, and "moved the most" means the largest absolute change, up or down.`,
      starterCode: `-- Which driver's month-end balance moved furthest, in either direction?
WITH ranked AS (
  -- each driver's latest snapshot in each calendar month
  SELECT
  FROM fact_wallet_snapshot
)
SELECT
FROM ranked;`,
      hints: [
        "Rank inside the month: `ROW_NUMBER() OVER (PARTITION BY driver_id, strftime('%Y-%m', as_of_date) ORDER BY as_of_date DESC)`, then keep `rn = 1`.",
        "`SUM(CASE WHEN strftime('%Y-%m', as_of_date) = '2026-07' THEN balance_usd ELSE 0 END)` pivots one month into a column.",
        "Subtract the June column from the July column, then `ROUND(..., 2) AS balance_change`.",
        "The winner is a decline, so `ORDER BY balance_change DESC` picks the wrong driver. Order by `ABS(balance_change) DESC` and `LIMIT 1`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT driver_id, as_of_date, balance_usd,
         ROW_NUMBER() OVER (
           PARTITION BY driver_id, strftime('%Y-%m', as_of_date)
           ORDER BY as_of_date DESC
         ) AS rn
  FROM fact_wallet_snapshot
)
SELECT driver_id,
       ROUND(SUM(CASE WHEN strftime('%Y-%m', as_of_date) = '2026-07' THEN balance_usd ELSE 0 END)
           - SUM(CASE WHEN strftime('%Y-%m', as_of_date) = '2026-06' THEN balance_usd ELSE 0 END), 2) AS balance_change
FROM ranked
WHERE rn = 1
GROUP BY driver_id
ORDER BY ABS(balance_change) DESC, driver_id
LIMIT 1;`,
      singleFile: {
        seedSql: WALLET_LESSON_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["driver_id", "balance_change"], rows: [[63, -318.4]] },
      },
    },
  ],
}

// Map deviation: the map asks for a "timeline" csdiagram of driver 42's two version rows.
// The diagram schema has no timeline type, so the same content ships as a `table` spec with
// the validity windows highlighted and the trip that lands in each window named on its row.
const scd2Rehearsal: SqlLesson = {
  id: "de-l7-scd2-rehearsal",
  title: "SCD2 Under the Clock: Apply the Change Batch",
  summary:
    "A timed rehearsal of the stock interview modeling task: apply a multi-driver change batch to a Type 2 dimension with a script that is safe to run twice.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "SCD Type 2",
    "change-batch application",
    "change-detection guards",
    "close-and-insert scripts",
    "idempotent scripts",
    "as-of joins",
    "timed rehearsal",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## The review screen (you already learned this)

Level 4's "SCD Type 2" lesson and its loader capstone built the mechanism, and Level 5's "Point-in-Time (As-Of) Joins Against an SCD2 Dimension" graded the join predicate. Neither is retaught here. The compressed version:

- A **Type 2** dimension keeps history by adding a **version row** instead of overwriting. One driver, several rows, each with \`valid_from\`, \`valid_to\`, and \`is_current\`.
- The surrogate \`driver_key\` identifies a **version**, not a driver. The natural \`driver_id\` identifies the driver.
- Applying a change is two statements: **close** the open row by setting its \`valid_to\` to the effective date and \`is_current = 0\`, then **insert** the new open row starting at that same date.
- The as-of join predicate is \`fact_date >= valid_from AND fact_date < valid_to\`. Half-open on purpose: the closed row's \`valid_to\` equals the new row's \`valid_from\`, so a fact landing exactly on the change date belongs to exactly one version.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["driver_key", "driver_id", "home_city", "valid_from", "valid_to", "is_current", "trip landing in this window"],
  "rows": [
    [1, 42, "Detroit", "2025-09-01", "2026-03-01", 0, "T-2002 on 2026-02-20 ($31.00)"],
    [2, 42, "Ann Arbor", "2026-03-01", "9999-12-31", 1, "T-2003 on 2026-04-05 ($18.75)"]
  ],
  "highlightCols": ["valid_from", "valid_to"],
  "caption": "Driver 42's two version rows. The windows touch but never overlap, so every trip attributes to exactly one city."
}
\`\`\`

## What this lesson adds: the batch, under the clock

Interviewers do not hand you one change. They hand you a **batch**, and roughly 25 minutes, and they watch you narrate. The batch is where candidates who know the concept still lose the round, for three reasons:

1. **No change detection.** The batch contains a row for a driver whose city did not actually change. Apply it blindly and you create a version row that says the driver moved from Detroit to Detroit. History is now a lie.
2. **Rows that should not be touched.** Drivers with no row in the batch must come out byte-identical. A \`WHERE is_current = 1\` with no batch predicate closes everybody.
3. **Not safe to run twice.** Pipelines retry. If your script doubles the versions when it runs again, it is not a loader, it is a one-shot.

## The shape that survives all three

\`\`\`sql
-- 1. Close the open version, but ONLY where the incoming city actually differs.
UPDATE dim_driver_scd
SET valid_to = (SELECT u.effective_date FROM driver_updates u
                WHERE u.driver_id = dim_driver_scd.driver_id),
    is_current = 0
WHERE is_current = 1
  AND EXISTS (SELECT 1 FROM driver_updates u
              WHERE u.driver_id = dim_driver_scd.driver_id
                AND u.new_city <> dim_driver_scd.home_city);

-- 2. Open the new version, skipping any driver that already has it.
INSERT INTO dim_driver_scd (driver_id, driver_name, home_city, valid_from, valid_to, is_current)
SELECT u.driver_id, d.driver_name, u.new_city, u.effective_date, '9999-12-31', 1
FROM driver_updates u
JOIN dim_driver_scd d
  ON d.driver_id = u.driver_id AND d.valid_to = u.effective_date
WHERE NOT EXISTS (
  SELECT 1 FROM dim_driver_scd c
  WHERE c.driver_id = u.driver_id
    AND c.home_city = u.new_city
    AND c.valid_from = u.effective_date
);
\`\`\`

The \`EXISTS ... AND u.new_city <> home_city\` in step 1 is the change-detection guard: a no-op row never closes anything. The \`NOT EXISTS\` in step 2 is the idempotency guard: on a second run the version already exists, so nothing is inserted. Step 2 joins on \`d.valid_to = u.effective_date\`, which is exactly the row step 1 just closed, so a driver whose row never closed never gets a new version either.

This shape assumes at most one change per driver in the batch. When a batch carries two changes for the same driver, that scalar subquery in step 1 has no defined answer, and the close date has to be the earliest effective date while the new versions chain between the rest. That is the practice exercise.

**Common mistake:** closing the old row by deleting it. That is a Type 1 overwrite wearing Type 2 columns. Every historical fact that joined to that version now joins to nothing, and last quarter's revenue by city silently changes. The old row stays forever; only its \`valid_to\` and \`is_current\` move.

**Interview nuance:** most candidates answer "which SCD type?" with the number and stop. The complete answer is the number **plus the join predicate**: "Type 2, so each trip joins on \`driver_id\` with \`completed_at >= valid_from AND completed_at < valid_to\`, which attributes revenue to the city the driver lived in that day." Say the predicate. It is the sentence that proves you have built one.

**Forward pointer:** where does the change batch come from on a real platform? A CDC stream off the source database's write-ahead log. Level 9 builds that producer; this lesson is its consumer.

> **On a real platform this differs.** A warehouse writes both statements as a single \`MERGE INTO dim_driver_scd USING driver_updates ON ... WHEN MATCHED AND target.home_city <> source.new_city THEN UPDATE SET ... WHEN NOT MATCHED THEN INSERT ...\`, which is atomic and is what Snowflake, BigQuery, Databricks, and Redshift all expect to see. SQLite has no \`MERGE\`, so you write the same semantics as an explicit close-then-insert (or \`INSERT ... ON CONFLICT(key) DO UPDATE SET ...\` for a Type 1 upsert). The guards you are writing here are exactly the \`WHEN MATCHED AND ...\` conditions of the real statement.`,
    demoSeedSql: SCD2_TEACH_SEED,
    demoCode: `-- Review (Level 5 graded this): the as-of join splits driver 42's revenue across both cities.
SELECT d.home_city, d.valid_from, d.valid_to,
       COUNT(f.trip_id) AS trips,
       ROUND(SUM(f.fare_usd), 2) AS revenue
FROM dim_driver_scd d
LEFT JOIN fact_trips f
  ON f.driver_id = d.driver_id
 AND f.completed_at >= d.valid_from
 AND f.completed_at <  d.valid_to
WHERE d.driver_id = 42
GROUP BY d.home_city, d.valid_from, d.valid_to
ORDER BY d.valid_from;`,
    showDemoInput: false,
  },
  apply: scriptExercise({
    id: "de-l7-scd2-rehearsal-apply",
    prompt: `Write a script that applies \`driver_updates\` to \`dim_driver_scd\` as Type 2 changes. Give yourself a 25-minute target and narrate as you go, the way you would in the room.

\`dim_driver_scd(driver_key, driver_id, driver_name, home_city, valid_from, valid_to, is_current)\` is seeded with six version rows (driver 42 already moved on 2026-03-01). \`driver_updates(driver_id, new_city, effective_date)\` holds the incoming batch.

For each driver whose city genuinely changes: close the current row by setting \`valid_to\` to the effective date and \`is_current = 0\`, then insert a new row starting at that date with \`valid_to = '9999-12-31'\` and \`is_current = 1\`. Leave unchanged drivers and no-op updates (same city) completely untouched, and make the script safe to run twice.`,
    starterCode: `-- dim_driver_scd and driver_updates are seeded. Apply the batch as Type 2 changes.
-- Target: 25 minutes, narrating each step.

-- 1. Close the open version of every driver whose city ACTUALLY changes.
--    The change-detection guard is what keeps the no-op row from creating a fake version.
-- UPDATE dim_driver_scd SET valid_to = ..., is_current = 0 WHERE ...

-- 2. Open the new version for those same drivers, and only if it is not already there
--    (a retried pipeline must not double the history).
-- INSERT INTO dim_driver_scd (driver_id, driver_name, home_city, valid_from, valid_to, is_current) ...`,
    hints: [
      "Close first, insert second. Step 2 can then find the row it needs by matching `valid_to = effective_date`.",
      "Guard the close with `EXISTS (SELECT 1 FROM driver_updates u WHERE u.driver_id = dim_driver_scd.driver_id AND u.new_city <> dim_driver_scd.home_city)` so the no-op row changes nothing.",
      "Set `valid_to` with a scalar subquery reading `effective_date` from `driver_updates` for that driver.",
      "Guard the insert with `NOT EXISTS (SELECT 1 FROM dim_driver_scd c WHERE c.driver_id = u.driver_id AND c.home_city = u.new_city AND c.valid_from = u.effective_date)` so a second run inserts nothing.",
      "Never insert `driver_key` yourself. It is `INTEGER PRIMARY KEY`, so SQLite assigns the next one.",
    ],
    referenceSolution: `UPDATE dim_driver_scd
SET valid_to = (SELECT u.effective_date FROM driver_updates u
                WHERE u.driver_id = dim_driver_scd.driver_id),
    is_current = 0
WHERE is_current = 1
  AND EXISTS (SELECT 1 FROM driver_updates u
              WHERE u.driver_id = dim_driver_scd.driver_id
                AND u.new_city <> dim_driver_scd.home_city);

INSERT INTO dim_driver_scd (driver_id, driver_name, home_city, valid_from, valid_to, is_current)
SELECT u.driver_id, d.driver_name, u.new_city, u.effective_date, '9999-12-31', 1
FROM driver_updates u
JOIN dim_driver_scd d
  ON d.driver_id = u.driver_id AND d.valid_to = u.effective_date
WHERE NOT EXISTS (
  SELECT 1 FROM dim_driver_scd c
  WHERE c.driver_id = u.driver_id
    AND c.home_city = u.new_city
    AND c.valid_from = u.effective_date
);`,
    seedSql: SCD2_APPLY_SEED,
    checkIdempotency: true,
    idempotencyTables: ["dim_driver_scd"],
    assertions: [
      {
        suite: "versions",
        name: "the dimension holds exactly eight version rows (six seeded plus two new)",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM dim_driver_scd) <> 8`,
      },
      {
        suite: "versions",
        name: "every driver has exactly one current version",
        sql: `SELECT driver_id FROM dim_driver_scd GROUP BY driver_id HAVING SUM(is_current) <> 1`,
      },
      {
        suite: "versions",
        name: "every version row carries the driver's name forward",
        isHidden: true,
        sql: `SELECT driver_key FROM dim_driver_scd
          WHERE driver_name IS NULL OR TRIM(driver_name) = ''`,
      },
      {
        suite: "change",
        name: "driver 51 closed Ann Arbor on 2026-06-01 and opened Detroit the same day",
        sql: `SELECT 1 WHERE (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 51 AND home_city = 'Ann Arbor'
              AND valid_to = '2026-06-01' AND is_current = 0
          ) <> 1
          OR (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 51 AND home_city = 'Detroit'
              AND valid_from = '2026-06-01' AND valid_to = '9999-12-31' AND is_current = 1
          ) <> 1`,
      },
      {
        suite: "change",
        name: "driver 63 opened an Ann Arbor version on 2026-06-01",
        isHidden: true,
        sql: `SELECT 1 WHERE (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 63 AND home_city = 'Ann Arbor'
              AND valid_from = '2026-06-01' AND is_current = 1
          ) <> 1`,
      },
      {
        suite: "no-op",
        name: "the no-op update left driver 74 on a single untouched version",
        isHidden: true,
        sql: `SELECT 1 WHERE (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 74 AND home_city = 'Detroit'
              AND valid_from = '2026-01-20' AND valid_to = '9999-12-31' AND is_current = 1
          ) <> 1
          OR (SELECT COUNT(*) FROM dim_driver_scd WHERE driver_id = 74) <> 1`,
      },
      {
        suite: "no-op",
        name: "drivers absent from the batch keep their exact seeded rows",
        isHidden: true,
        sql: `SELECT driver_id FROM dim_driver_scd
          WHERE driver_id IN (42, 85)
            AND NOT (
              (driver_id = 42 AND driver_name = 'Maya Okafor' AND home_city = 'Detroit'
                 AND valid_from = '2025-09-01' AND valid_to = '2026-03-01' AND is_current = 0)
              OR (driver_id = 42 AND driver_name = 'Maya Okafor' AND home_city = 'Ann Arbor'
                 AND valid_from = '2026-03-01' AND valid_to = '9999-12-31' AND is_current = 1)
              OR (driver_id = 85 AND driver_name = 'Priya Raman' AND home_city = 'Ann Arbor'
                 AND valid_from = '2026-02-08' AND valid_to = '9999-12-31' AND is_current = 1)
            )
          UNION ALL
          SELECT 0 WHERE (SELECT COUNT(*) FROM dim_driver_scd WHERE driver_id IN (42, 85)) <> 3`,
      },
      {
        suite: "continuity",
        name: "each closed window ends exactly where the next one begins",
        isHidden: true,
        sql: `WITH chained AS (
            SELECT driver_id, valid_from, valid_to,
                   LEAD(valid_from) OVER (PARTITION BY driver_id ORDER BY valid_from) AS next_from
            FROM dim_driver_scd
          )
          SELECT driver_id FROM chained
          WHERE next_from IS NOT NULL AND next_from <> valid_to`,
      },
    ],
  }),
  practice: scriptExercise({
    id: "de-l7-scd2-rehearsal-practice",
    prompt: `Write a script that applies a harder batch: one driver changes cities twice, with two different effective dates. Same 25-minute target, no starter scaffold this time.

\`dim_driver_scd\` holds one open version per driver. \`driver_updates(driver_id, new_city, effective_date)\` holds three rows, two of them for the same driver.

The finished dimension must chain that driver's versions in effective-date order with continuous windows (each version's \`valid_to\` equals the next version's \`valid_from\`), leave exactly one \`is_current = 1\` row per driver, leave drivers absent from the batch untouched, and produce the same result when the script runs a second time.`,
    starterCode: `-- dim_driver_scd and driver_updates are seeded. Apply the batch as Type 2 changes.
-- One driver moves twice, so the new versions have to chain in effective-date order.
`,
    hints: [
      "Work out the target state on paper first: a driver with two updates ends with three version rows, and each new version's end date is the next update's start date.",
      "The order of your two statements matters, because one of them reads a row the other one changes.",
      "Only the last version in a driver's chain is current, and a rerun must not insert a version that is already there.",
    ],
    seedSql: SCD2_PRACTICE_SEED,
    checkIdempotency: true,
    idempotencyTables: ["dim_driver_scd"],
    assertions: [
      {
        suite: "versions",
        name: "the dimension holds exactly seven version rows (four seeded plus three new)",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM dim_driver_scd) <> 7`,
      },
      {
        suite: "versions",
        name: "every driver has exactly one current version",
        sql: `SELECT driver_id FROM dim_driver_scd GROUP BY driver_id HAVING SUM(is_current) <> 1`,
      },
      {
        suite: "versions",
        name: "every version row carries the driver's name forward",
        isHidden: true,
        sql: `SELECT driver_key FROM dim_driver_scd
          WHERE driver_name IS NULL OR TRIM(driver_name) = ''`,
      },
      {
        suite: "chaining",
        name: "driver 51 has three versions in Ann Arbor, Detroit, Chicago order",
        sql: `SELECT 1 WHERE (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 51 AND home_city = 'Ann Arbor'
              AND valid_from = '2025-10-15' AND valid_to = '2026-06-01' AND is_current = 0
          ) <> 1
          OR (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 51 AND home_city = 'Detroit'
              AND valid_from = '2026-06-01' AND valid_to = '2026-09-15' AND is_current = 0
          ) <> 1
          OR (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 51 AND home_city = 'Chicago'
              AND valid_from = '2026-09-15' AND valid_to = '9999-12-31' AND is_current = 1
          ) <> 1`,
      },
      {
        suite: "chaining",
        name: "driver 63 closed Chicago on 2026-07-10 and opened Ann Arbor the same day",
        isHidden: true,
        sql: `SELECT 1 WHERE (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 63 AND home_city = 'Chicago'
              AND valid_to = '2026-07-10' AND is_current = 0
          ) <> 1
          OR (
            SELECT COUNT(*) FROM dim_driver_scd
            WHERE driver_id = 63 AND home_city = 'Ann Arbor'
              AND valid_from = '2026-07-10' AND valid_to = '9999-12-31' AND is_current = 1
          ) <> 1`,
      },
      {
        suite: "continuity",
        name: "each closed window ends exactly where the next one begins",
        isHidden: true,
        sql: `WITH chained AS (
            SELECT driver_id, valid_from, valid_to,
                   LEAD(valid_from) OVER (PARTITION BY driver_id ORDER BY valid_from) AS next_from
            FROM dim_driver_scd
          )
          SELECT driver_id FROM chained
          WHERE next_from IS NOT NULL AND next_from <> valid_to`,
      },
      {
        suite: "continuity",
        name: "no version starts on or after the day it ends",
        isHidden: true,
        sql: `SELECT driver_key FROM dim_driver_scd WHERE valid_from >= valid_to`,
      },
      {
        suite: "no-op",
        name: "drivers absent from the batch are untouched",
        isHidden: true,
        sql: `SELECT driver_id FROM dim_driver_scd
          WHERE driver_id IN (42, 74) AND (is_current <> 1 OR valid_to <> '9999-12-31')`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l7-scd2-rehearsal-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Review drill from Level 5. Write a query that returns revenue by home city as \`(home_city, revenue)\` rounded to 2 decimals, highest first, attributing each trip to the city the driver lived in when it completed.

Join \`fact_trips(trip_id, driver_id, completed_at, fare_usd)\` to \`dim_driver_scd\` on \`driver_id\` with the as-of predicate.`,
      starterCode: `-- As-of join: each trip lands in the version whose window contains completed_at.
SELECT d.home_city
FROM fact_trips f
JOIN dim_driver_scd d
  ON d.driver_id = f.driver_id
 -- and the as-of window predicate
;`,
      hints: [
        "The predicate is `f.completed_at >= d.valid_from AND f.completed_at < d.valid_to`.",
        "Half-open on the right is what stops a trip on the change date from matching two versions.",
        "Group by `d.home_city` and `ROUND(SUM(f.fare_usd), 2) AS revenue`, ordered descending.",
      ],
      referenceSolution: `SELECT d.home_city,
       ROUND(SUM(f.fare_usd), 2) AS revenue
FROM fact_trips f
JOIN dim_driver_scd d
  ON d.driver_id = f.driver_id
 AND f.completed_at >= d.valid_from
 AND f.completed_at <  d.valid_to
GROUP BY d.home_city
ORDER BY revenue DESC;`,
      singleFile: {
        seedSql: SCD2_TEACH_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["home_city", "revenue"],
          rows: [
            ["Detroit", 88.9],
            ["Ann Arbor", 82.65],
            ["Chicago", 72],
          ],
        },
      },
    },
    {
      id: "de-l7-scd2-rehearsal-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every driver whose validity windows overlap, as \`(driver_id, closed_valid_to, next_valid_from)\` ordered by \`driver_id\`, over a \`dim_driver_scd\` that one bad loader run has already damaged.

A window overlaps when a version's \`valid_to\` falls after the next version's \`valid_from\`.`,
      starterCode: `-- Quality check: a Type 2 dimension whose windows overlap double-counts every fact.
WITH chained AS (
  -- pair each version with the one that starts after it
  SELECT
  FROM dim_driver_scd
)
SELECT
FROM chained;`,
      hints: [
        "`LEAD(valid_from) OVER (PARTITION BY driver_id ORDER BY valid_from)` gives the next version's start date.",
        "Rows where that value is NULL are the newest version and cannot overlap forward.",
        "The violation is `next_valid_from < valid_to`. Equality is correct, not a bug.",
        "Alias the columns exactly `closed_valid_to` and `next_valid_from`.",
      ],
      referenceSolution: `WITH chained AS (
  SELECT driver_id, valid_from, valid_to,
         LEAD(valid_from) OVER (PARTITION BY driver_id ORDER BY valid_from) AS next_valid_from
  FROM dim_driver_scd
)
SELECT driver_id,
       valid_to AS closed_valid_to,
       next_valid_from
FROM chained
WHERE next_valid_from IS NOT NULL
  AND next_valid_from < valid_to
ORDER BY driver_id;`,
      singleFile: {
        seedSql: DIM_DRIVER_SCD_OVERLAP_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["driver_id", "closed_valid_to", "next_valid_from"],
          rows: [[96, "2026-02-15", "2026-01-10"]],
        },
      },
    },
  ],
}

const kimballVsObt: SqlLesson = {
  id: "de-l7-kimball-vs-obt",
  title: "Kimball vs One Big Table: The 10 GB Join-Side Heuristic",
  summary:
    "When to choose a star schema over One Big Table, using consumer needs and the 10 GB join-side heuristic instead of dogma.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "One Big Table pattern",
    "denormalization tradeoffs",
    "join-side sizing",
    "conformed dimensions",
    "storage cost arithmetic",
    "CASE classification",
    "decision frameworks",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The debate the canon skips

Everything you have rehearsed in this module is Kimball: a narrow fact surrounded by dimensions you join to. It is still the junior interview canon and it is still the right default. But it is not the only live answer in 2026, and the follow-up question is coming.

**One Big Table (OBT)** is the alternative: pre-join the dimensions into the fact once, at load time, and ship one very wide table. Every query becomes a single-table scan with no joins at all. Columnar engines make this viable in a way row stores never did, because a query that selects 4 columns out of 300 reads only those 4. BI teams love it: no join grammar to teach, no fan-out to explain, and dashboards get faster.

Adoption says it is a minority position and a real one. Practitioner surveys put mixed approaches at 36.8%, Kimball at 27.8%, ad-hoc at 17.4%, semantic models at 5.4%, One Big Table at 3.8%, and Data Vault at 3.3%. So Kimball is the default you should be able to build, and OBT is the tradeoff you should be able to argue.

\`\`\`csdiagram
{
  "type": "er",
  "tables": [
    {
      "name": "dim_driver",
      "columns": [
        { "name": "driver_key", "key": "pk" },
        { "name": "home_city" },
        { "name": "vehicle_class" }
      ]
    },
    {
      "name": "fact_trips (star)",
      "columns": [
        { "name": "trip_id", "key": "pk" },
        { "name": "driver_key", "key": "fk" },
        { "name": "fare_usd" }
      ]
    },
    {
      "name": "obt_trips (one big table)",
      "columns": [
        { "name": "trip_id", "key": "pk" },
        { "name": "driver_key" },
        { "name": "home_city" },
        { "name": "vehicle_class" },
        { "name": "fare_usd" }
      ]
    }
  ],
  "relations": [
    { "from": "fact_trips (star)", "to": "dim_driver", "kind": "n-1", "label": "joined at query time" }
  ],
  "caption": "Same data, two shapes. The star joins at read time and stores each driver attribute once. The OBT joins at load time and stores those attributes on every single trip row."
}
\`\`\`

## The heuristic that makes the answer sound experienced

The working rule from the modeling community: **stay with Kimball while the join side is under roughly 10 GB.** Under that, the engine can broadcast the dimension to every worker and the star join costs almost nothing. Past it, the dimension has to be shuffled across the network alongside the fact, and shuffle cost can run 10x to 100x the broadcast case. That is when pre-joining into an OBT starts earning its storage bill.

You have seen this physics before. In Module 7.1, \`DS_BCAST_INNER\` versus \`DS_DIST_BOTH\` in a query plan is the same fork, read off a plan after the fact. Here you are making the same call at design time, before anyone runs anything. Choosing a distribution key that co-locates the join is the third option in the same family.

## When Kimball wins anyway, regardless of size

Three conditions override the size heuristic:

1. **Conformed dimensions.** If \`dim_driver\` is joined by trips, payouts, and support tickets, an OBT means maintaining three copies of every driver attribute and hoping they agree. The whole point of a conformed dimension is that "home city" means one thing across the warehouse.
2. **History has to version.** The SCD2 machinery from the last lesson has nowhere to live in an OBT. There is no dimension row to close and reopen, so a driver's move either rewrites history everywhere or is lost.
3. **Dimension attributes change often.** In an OBT, changing one attribute on one driver rewrites every fact row that driver ever appeared in. On a billion-row table that is not an update, it is a rebuild.

**Common mistake:** treating the storage growth as the whole cost and stopping there. Storage is the cheap part. The expensive part is that an OBT converts a small dimension update into a large fact rewrite, and it converts one shared definition into several private copies that drift.

**Interview nuance:** "would you just make one big table?" is a real follow-up to any star-schema answer, and it is a judgment probe, not a knowledge probe. Answering "no, Kimball is correct" reads as dogma. Answering "OBT, it is faster" reads as inexperience. The strong answer names the number and one cost of each path: "I would keep the star while the dimension side stays under about 10 GB, since the engine broadcasts it and the join is nearly free. Past that I would pre-join into a wide table, and I would accept that a dimension change now rewrites the fact and that these attributes stop being conformed."

> **On a real platform this differs.** Real OBTs usually are not flat. Snowflake, BigQuery, and Databricks all support nested \`ARRAY<STRUCT>\` columns, so a trips table can carry the driver's attributes as one nested struct and the trip's waypoints as an array, keeping the single-table scan without exploding the row count. And the decision is rarely permanent: teams often keep the Kimball star as the modeled layer and materialize an OBT on top of it for BI, which buys the fast dashboards without giving up the conformed dimensions or the version history.`,
    demoSeedSql: MART_PROFILES_SEED,
    demoCode: `-- The join side is the number the heuristic is about. Which marts are over the line?
SELECT mart, fact_gb, total_dim_gb,
       CASE WHEN total_dim_gb > 10 THEN 'over 10 GB: shuffle territory'
            ELSE 'under 10 GB: broadcast territory' END AS join_side
FROM mart_profiles
ORDER BY total_dim_gb DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l7-kimball-vs-obt-apply",
    executionMode: "single-file",
    prompt: `Write a query that classifies each mart as \`(mart, recommendation)\` over \`mart_profiles(mart, fact_rows, fact_row_bytes, denorm_extra_bytes, fact_gb, total_dim_gb, dims_reused_elsewhere, dim_change_rate_pct, bi_only)\`, ordered by \`mart\`.

Apply these rules in this order:

1. \`'obt'\` when \`total_dim_gb > 10\` and \`bi_only = 1\` and \`dims_reused_elsewhere = 0\`.
2. \`'star'\` when \`dims_reused_elsewhere = 1\` or \`dim_change_rate_pct > 5\`.
3. \`'either'\` otherwise.

Alias the classification exactly \`recommendation\`.`,
    starterCode: `-- Per-mart modeling recommendation from the 10 GB join-side heuristic.
SELECT mart,
       CASE
         -- rule 1: the join side is big, BI is the only consumer, nothing else reuses the dims
         -- rule 2: conformed dimensions or churning attributes
         -- rule 3: no strong signal either way
       END AS recommendation
FROM mart_profiles
ORDER BY mart;`,
    hints: [
      "A single `CASE` expression evaluates its `WHEN` branches top to bottom and stops at the first true one, which is why rule order matters.",
      "Rule 1 needs all three conditions joined with `AND`.",
      "Rule 2 needs the two conditions joined with `OR`.",
      "`ELSE 'either'` covers rule 3, and alias the whole expression `recommendation`.",
    ],
    referenceSolution: `SELECT mart,
       CASE
         WHEN total_dim_gb > 10 AND bi_only = 1 AND dims_reused_elsewhere = 0 THEN 'obt'
         WHEN dims_reused_elsewhere = 1 OR dim_change_rate_pct > 5 THEN 'star'
         ELSE 'either'
       END AS recommendation
FROM mart_profiles
ORDER BY mart;`,
    singleFile: {
      seedSql: MART_PROFILES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["mart", "recommendation"],
        rows: [
          ["app_events", "obt"],
          ["driver_payouts", "star"],
          ["finance_gl", "star"],
          ["fleet_maintenance", "either"],
          ["marketing_attribution", "obt"],
          ["ride_share_trips", "star"],
          ["rider_ltv", "star"],
          ["support_tickets", "either"],
        ],
      },
    },
  },
  practice: {
    id: "de-l7-kimball-vs-obt-practice",
    executionMode: "single-file",
    prompt: `Write a query that prices the denormalization for every mart as \`(mart, star_gb, obt_gb, growth_factor)\` over the same \`mart_profiles\` table.

\`star_gb\` is the stored \`fact_gb\`. \`obt_gb\` is \`fact_rows\` times \`(fact_row_bytes + denorm_extra_bytes)\`, converted to GB at 1 GB = 1,000,000,000 bytes. \`growth_factor\` is \`(fact_row_bytes + denorm_extra_bytes)\` divided by \`fact_row_bytes\`. Round all three to 1 decimal, and order by \`growth_factor\` descending then \`mart\`.`,
    starterCode: `-- What the wide table costs: the star's fact size, the OBT's fact size, and the multiple.
SELECT mart
FROM mart_profiles
;`,
    hints: [
      "`fact_rows * (fact_row_bytes + denorm_extra_bytes)` is total bytes; divide by `1000000000.0` for GB.",
      "Use a decimal divisor (`1000000000.0`, `* 1.0`) so integer division does not truncate the answer to zero.",
      "`growth_factor` needs no row count at all: it is the per-row byte ratio.",
      "`ROUND(..., 1)` on all three, then `ORDER BY growth_factor DESC, mart`.",
    ],
    singleFile: {
      seedSql: MART_PROFILES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["mart", "star_gb", "obt_gb", "growth_factor"],
        rows: [
          ["app_events", 360, 1310, 3.6],
          ["rider_ltv", 26, 88.4, 3.4],
          ["marketing_attribution", 21.6, 59.4, 2.8],
          ["support_tickets", 4.4, 11.6, 2.6],
          ["ride_share_trips", 230.4, 566.4, 2.5],
          ["driver_payouts", 27, 66, 2.4],
          ["fleet_maintenance", 1.5, 3.4, 2.3],
          ["finance_gl", 12.6, 27, 2.1],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l7-kimball-vs-obt-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the marts whose recommendation flips when the heuristic threshold drops from 10 GB to 5 GB, as \`(mart, at_10gb, at_5gb)\` ordered by \`mart\`, over \`mart_profiles\`.

Use the same three rules as the apply exercise, changing only the \`total_dim_gb\` threshold in rule 1.`,
      starterCode: `-- How sensitive is the recommendation to the threshold you picked?
WITH scored AS (
  SELECT mart
  FROM mart_profiles
)
SELECT
FROM scored;`,
      hints: [
        "Compute both classifications as two `CASE` expressions inside one CTE.",
        "Only the number in rule 1 changes; rules 2 and 3 stay identical.",
        "Filter the CTE with `WHERE at_10gb <> at_5gb`.",
      ],
      referenceSolution: `WITH scored AS (
  SELECT mart,
         CASE
           WHEN total_dim_gb > 10 AND bi_only = 1 AND dims_reused_elsewhere = 0 THEN 'obt'
           WHEN dims_reused_elsewhere = 1 OR dim_change_rate_pct > 5 THEN 'star'
           ELSE 'either'
         END AS at_10gb,
         CASE
           WHEN total_dim_gb > 5 AND bi_only = 1 AND dims_reused_elsewhere = 0 THEN 'obt'
           WHEN dims_reused_elsewhere = 1 OR dim_change_rate_pct > 5 THEN 'star'
           ELSE 'either'
         END AS at_5gb
  FROM mart_profiles
)
SELECT mart, at_10gb, at_5gb
FROM scored
WHERE at_10gb <> at_5gb
ORDER BY mart;`,
      singleFile: {
        seedSql: MART_PROFILES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["mart", "at_10gb", "at_5gb"],
          rows: [
            ["fleet_maintenance", "either", "obt"],
            ["support_tickets", "either", "obt"],
          ],
        },
      },
    },
    {
      id: "de-l7-kimball-vs-obt-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the single mart that pays the largest rewrite when its dimension attributes change, as \`(mart, rewritten_gb)\` rounded to 1 decimal, over \`mart_profiles\`.

Rewritten GB is the mart's OBT size (\`fact_rows\` times \`(fact_row_bytes + denorm_extra_bytes)\`, in GB) multiplied by \`dim_change_rate_pct\` divided by 100.`,
      starterCode: `-- In an OBT, a dimension change rewrites fact rows. Who pays the most?
SELECT mart
FROM mart_profiles
;`,
      hints: [
        "Reuse the `obt_gb` expression from the practice exercise, then scale it by the change rate.",
        "`dim_change_rate_pct / 100.0` converts the percent to a fraction. Keep the divisor decimal.",
        "`ORDER BY rewritten_gb DESC, mart` then `LIMIT 1`.",
        "The biggest table is not the answer. A huge mart whose dimensions almost never change is cheap to maintain.",
      ],
      referenceSolution: `SELECT mart,
       ROUND(fact_rows * (fact_row_bytes + denorm_extra_bytes) / 1000000000.0
             * dim_change_rate_pct / 100.0, 1) AS rewritten_gb
FROM mart_profiles
ORDER BY rewritten_gb DESC, mart
LIMIT 1;`,
      singleFile: {
        seedSql: MART_PROFILES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["mart", "rewritten_gb"], rows: [["ride_share_trips", 34]] },
      },
    },
  ],
}

export const level7Module2: SqlModule = {
  id: "de-l7-dimensional-modeling",
  title: "Module 7.2: Dimensional Modeling Rehearsal and the Missing Debate",
  description:
    "Review-plus-extension, not a reteach. SQL Levels 3 to 5 already taught grain, additivity, and SCD Type 2; this module compresses each into one review screen and grades what interviews actually separate on: an executable grain audit, the wrong-sum beside the right-sum, a timed SCD2 change-batch applier, and the Kimball versus One Big Table decision with its 10 GB join-side heuristic.",
  lessons: [grainAudit, semiAdditiveAudit, scd2Rehearsal, kimballVsObt],
}
