import type React from "react"
import type { Metadata, Viewport } from "next"
import { Geist, Geist_Mono, Work_Sans, Open_Sans } from "next/font/google"
import { Toaster } from "sonner"
import { AuthProvider } from "@/lib/auth-context"
import { ThemeProvider } from "@/components/theme-provider"
import { RateLimitProvider } from "@/lib/contexts/rate-limit-context"
import { ErrorBoundaryProvider } from "@/components/providers/error-boundary-provider"
import { AnnouncementProvider } from "@/components/announcements"
import { CookieConsent } from "@/components/CookieConsent"
import { ConsentAnalytics } from "@/components/ConsentAnalytics"
import { PerformancePolyfill } from "@/components/performance-polyfill"
import { ReferralCapture } from "@/components/ReferralCapture"
import { AttributionCapture } from "@/components/AttributionCapture"
import { ClientErrorReporter } from "@/components/monitoring/ClientErrorReporter"
import {
  OrganizationJsonLd,
  SoftwareApplicationJsonLd,
  WebSiteJsonLd,
  FounderPersonJsonLd,
} from "@/components/seo/JsonLd"
import { SITE_ORIGIN } from "@/lib/seo/site"
import "./globals.css"

const workSans = Work_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-work-sans",
})

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
})

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist",
})

// Geist Mono — used for the code workspace chrome (file tabs, filenames,
// console) so the bug-fix surface reads like a real IDE, not a web template.
const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
})

const siteConfig = {
  name: "CodeSparring",
  tagline: "AI Technical Interview Practice for Coding, System Design, and Real-World Rounds",
  description:
    "Practice technical interviews with an AI interviewer. CodeSparring helps engineers prepare for coding, system design, bug-fix, and real-world interview rounds, plus free Python, SQL, and System Design courses, with feedback, hints, and performance tracking.",
  // One origin for the whole app, from lib/seo/site.ts. This was a fourth private copy of the apex
  // literal, and the copies are what let the site publish canonicals against a redirecting host.
  url: SITE_ORIGIN,
  // OG images are now dynamically generated via app/opengraph-image.tsx
}

// Viewport configuration for mobile responsiveness
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1917" },
  ],
}

export const metadata: Metadata = {
  // Core metadata
  title: {
    default: `${siteConfig.name} | ${siteConfig.tagline}`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    // Primary keywords - differentiation focus
    "coding interview prep",
    "mock interview",
    "AI interviewer",
    "interview performance training",
    "LeetCode alternative",
    // Competitive positioning keywords
    "better than LeetCode",
    "LeetCode vs CodeSparring",
    "cheap mock interviews",
    "Interviewing.io alternative",
    "voice coding interview practice",
    // Long-tail keywords
    "tech interview preparation",
    "software engineering interview",
    "FAANG interview prep",
    "Google interview prep",
    "Amazon interview questions",
    "Meta coding interview",
    // Problem keywords
    "why I fail coding interviews",
    "LeetCode not enough",
    "interview anxiety practice",
    "practice thinking out loud coding",
    // Feature keywords
    "voice mock interview",
    "AI coding tutor",
    "spaced repetition coding",
    "interview practice app",
    "24/7 mock interviews",
    // Algorithm keywords
    "DSA practice",
    "algorithm practice",
    "data structures practice",
    "coding interview questions",
    // Related searches
    "how to pass coding interview",
    "coding interview tips",
    "technical interview practice",
    "software engineer interview questions",
  ],
  authors: [{ name: "Nikayel Ali Jamal" }],
  creator: siteConfig.name,
  publisher: siteConfig.name,

  // Favicon: the Sparra mark (design/brand). SVG scales to every tab size;
  // the PNG apple-touch-icon is generated by app/apple-icon.tsx (file
  // convention injects its <link> automatically — do not duplicate it here).
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    shortcut: "/favicon.svg",
  },

  // Canonical URL
  // metadataBase lets child pages declare relative self-referencing canonicals.
  // The root layout intentionally does NOT set alternates.canonical: a root
  // canonical is inherited by every page and would point them all at the
  // homepage. The homepage sets its own canonical in app/page.tsx.
  //
  // Audited: this is the apex, it carries no trailing slash (SITE_ORIGIN strips
  // one), and it is now the SAME value the sitemap, robots.txt, and every
  // JSON-LD node resolve against. A relative canonical on a Learn lesson page
  // therefore resolves to the exact URL the sitemap submitted, which is the
  // condition Google needs to treat the two as one document.
  metadataBase: new URL(SITE_ORIGIN),

  // Open Graph - for social sharing
  // Images are auto-generated via app/opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: `${siteConfig.name} | ${siteConfig.tagline}`,
    description: siteConfig.description,
  },

  // Twitter Card
  // Images are auto-generated via app/twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} | ${siteConfig.tagline}`,
    description: siteConfig.description,
    creator: "@codesparring",
  },

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Search Engine Verification
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    // yandex: "your-yandex-verification-code",
    // bing: "your-bing-verification-code",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* JSON-LD Structured Data for SEO */}
        <WebSiteJsonLd />
        <OrganizationJsonLd />
        <SoftwareApplicationJsonLd />
        <FounderPersonJsonLd />
        <style>{`
html {
  font-family: ${openSans.style.fontFamily};
}
        `}</style>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined' && window.performance && window.performance.measure) {
                const originalMeasure = window.performance.measure.bind(window.performance);
                window.performance.measure = function(name, startMark, endMark) {
                  try {
                    return originalMeasure(name, startMark, endMark);
                  } catch (error) {
                    if (error instanceof TypeError && 
                        (error.message.includes('cannot have a negative time stamp') ||
                         error.message.includes('Slot.SlotClone'))) {
                      // Suppress harmless development error
                      return;
                    }
                    throw error;
                  }
                };
              }
            `,
          }}
        />
      </head>
      <body
        className={`${workSans.variable} ${openSans.variable} ${geist.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Skip link for keyboard accessibility - hidden until focused */}
        <a
          href="#main-content"
          className="focus:bg-accent focus:text-accent-foreground focus:ring-ring sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[100] focus:rounded-md focus:px-4 focus:py-2 focus:ring-2 focus:outline-none"
        >
          Skip to main content
        </a>
        <PerformancePolyfill />
        <ReferralCapture />
        <AttributionCapture />
        <ClientErrorReporter />
        {/* disableTransitionOnChange intentionally omitted. The light↔dark
            crossfade is handled by the View Transitions API in
            components/ThemeToggle.tsx, not a per-element CSS transition. */}
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          <ErrorBoundaryProvider>
            <AuthProvider>
              <RateLimitProvider>
                <AnnouncementProvider>
                  <div id="main-content">{children}</div>
                  <Toaster position="top-right" richColors closeButton duration={4000} />
                  <CookieConsent />
                  <ConsentAnalytics />
                </AnnouncementProvider>
              </RateLimitProvider>
            </AuthProvider>
          </ErrorBoundaryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
