/**
 * Data Engineering curriculum Level 8, Module 8.1 — Orchestration Fundamentals.
 *
 * `sql-l6-pipelines-orchestration` introduced DAG vocabulary over one flat `pipeline_runs`
 * log. This module deepens it into the two-table runs-versus-task-instances model a real
 * scheduler actually exposes, and grades the reasoning an on-call data engineer does with
 * it: which runs and tasks are healthy, why a run is responsible for a TIME RANGE rather
 * than for "when it ran", what a mid-DAG failure freezes downstream, and which of the
 * night's alerts actually deserved a page.
 *
 * Device: the Level 6 device, unchanged. Every lesson teaches the concept in `teach`, then
 * grades ordinary SQL over a simulated copy of the scheduler's own metadata database
 * (`orchestrator_runs` for Airflow's `dag_run`, `task_instances` for `task_instance`,
 * `task_dependencies` for the serialized DAG edges, `sensor_waits`, `alerts`). Names are
 * deliberately GENERIC rather than Airflow-specific: RESEARCH.md §5.1 resolves that
 * orchestration is interview-tested as concepts and almost never as vendor code, and
 * finding 10 warns that vendor APIs churn. Airflow 3 specifics (logical date + data
 * interval, `execution_date` removed) appear in prose callouts only.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable;
 * `referenceSolution` ships on apply and drills, never on practice.
 *
 * Five deliberate deviations from CURRICULUM-MAP.md:
 *  - 8.1.3's apply is one result set with an `outcome` column ('exhausted' | 'retry_save')
 *    rather than the map's "rows plus a separately counted column", which is not a single
 *    result set. The graded skill (the transient-versus-exhausted split) is identical.
 *  - 8.1.2's `task_dependencies` carries one `weekly_digest` edge beyond the map's
 *    daily_sales-plus-hourly_events list, so the apply's one-hop propagation returns three
 *    distinct blocked tasks instead of two rows that look near-identical. It also carries a
 *    `load_facts -> notify_sales` cross edge (so the practice's shortest-depth dedup is
 *    load-bearing) and a `clean_orders -> archive_orders` edge with no task instance (so
 *    the apply's downstream join is load-bearing).
 *  - 8.1.3's "success needed a retry more than once" drill counts a TASK's retry-rescued
 *    runs (`HAVING COUNT(...) > 1`), because a per-instance reading (`try_number > 2`)
 *    returns zero rows against a seed whose `max_tries` is the canonical 2 (§5.2).
 *  - 8.1.2 reseeds with its OWN run ids rather than reusing 8.1.1's. It is a different
 *    incident window, and sharing ids would have had two lessons assert different outcomes
 *    for the same run.
 *  - `max_tries` here is the TOTAL attempt budget, not Airflow's retry count, so the
 *    exhausted test stays the plain `try_number = max_tries`. 8.1.3's teach flags the real
 *    Airflow convention explicitly so the learner does not carry an off-by-one out.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Shared simulated scheduler-metadata seeds for Module 8.1. Named after what a real
// scheduler stores (Airflow's `dag_run` / `task_instance` tables) so a learner who later
// opens the metadata database recognizes the shape. Three DAGs run here: `daily_sales`
// (daily), `hourly_events` (hourly), `weekly_digest` (weekly).
//
// Every run in `orchestrator_runs` has its task instances in `task_instances`, so the two
// tables join without holes. `ds_2026_03_11` is the boundary case the lag practice needs: a
// scheduled run that sat in the queue and started exactly one calendar day late, which is
// normal operations rather than a catchup.
// ---------------------------------------------------------------------------

const ORCHESTRATOR_RUNS_SEED = `CREATE TABLE orchestrator_runs (
  run_id              TEXT,
  dag_id              TEXT,
  logical_date        TEXT,   -- the interval this run is FOR; equals data_interval_start on a scheduled run
  data_interval_start TEXT,   -- inclusive start of the time range the run owns
  data_interval_end   TEXT,   -- exclusive end; a daily run for 2026-03-13 owns [03-13, 03-14)
  run_type            TEXT,   -- scheduled | backfill | manual
  state               TEXT,   -- success | failed (a real dag_run also holds queued and running)
  started_at          TEXT,   -- wall-clock start; far from data_interval_end on a backfill
  ended_at            TEXT
);
INSERT INTO orchestrator_runs (run_id, dag_id, logical_date, data_interval_start, data_interval_end, run_type, state, started_at, ended_at) VALUES
  ('ds_2026_03_11',    'daily_sales',   '2026-03-11 00:00:00', '2026-03-11 00:00:00', '2026-03-12 00:00:00', 'scheduled', 'success', '2026-03-13 01:40:00', '2026-03-13 01:58:00'),
  ('ds_2026_03_13',    'daily_sales',   '2026-03-13 00:00:00', '2026-03-13 00:00:00', '2026-03-14 00:00:00', 'scheduled', 'success', '2026-03-14 02:05:00', '2026-03-14 02:24:00'),
  ('ds_2026_03_14',    'daily_sales',   '2026-03-14 00:00:00', '2026-03-14 00:00:00', '2026-03-15 00:00:00', 'scheduled', 'failed',  '2026-03-15 02:05:00', '2026-03-15 02:19:00'),
  ('ds_2026_03_15',    'daily_sales',   '2026-03-15 00:00:00', '2026-03-15 00:00:00', '2026-03-16 00:00:00', 'scheduled', 'success', '2026-03-16 02:06:00', '2026-03-16 02:27:00'),
  ('ds_2026_03_09',    'daily_sales',   '2026-03-09 00:00:00', '2026-03-09 00:00:00', '2026-03-10 00:00:00', 'manual',    'success', '2026-03-16 11:00:00', '2026-03-16 11:18:00'),
  ('ds_2026_02_01',    'daily_sales',   '2026-02-01 00:00:00', '2026-02-01 00:00:00', '2026-02-02 00:00:00', 'backfill',  'success', '2026-03-16 09:00:00', '2026-03-16 09:21:00'),
  ('he_2026_03_15_08', 'hourly_events', '2026-03-15 08:00:00', '2026-03-15 08:00:00', '2026-03-15 09:00:00', 'scheduled', 'success', '2026-03-15 09:00:30', '2026-03-15 09:04:30'),
  ('he_2026_03_15_09', 'hourly_events', '2026-03-15 09:00:00', '2026-03-15 09:00:00', '2026-03-15 10:00:00', 'scheduled', 'success', '2026-03-15 10:00:30', '2026-03-15 10:04:30'),
  ('he_2026_03_15_10', 'hourly_events', '2026-03-15 10:00:00', '2026-03-15 10:00:00', '2026-03-15 11:00:00', 'scheduled', 'failed',  '2026-03-15 11:00:30', '2026-03-15 11:05:20'),
  ('he_2026_03_15_11', 'hourly_events', '2026-03-15 11:00:00', '2026-03-15 11:00:00', '2026-03-15 12:00:00', 'scheduled', 'failed',  '2026-03-15 12:00:30', '2026-03-15 12:05:10'),
  ('he_2026_01_20_03', 'hourly_events', '2026-01-20 03:00:00', '2026-01-20 03:00:00', '2026-01-20 04:00:00', 'backfill',  'success', '2026-03-16 09:30:00', '2026-03-16 09:34:00'),
  ('wd_2026_03_02',    'weekly_digest', '2026-03-02 00:00:00', '2026-03-02 00:00:00', '2026-03-09 00:00:00', 'scheduled', 'success', '2026-03-09 03:00:00', '2026-03-09 03:17:00'),
  ('wd_2026_03_09',    'weekly_digest', '2026-03-09 00:00:00', '2026-03-09 00:00:00', '2026-03-16 00:00:00', 'scheduled', 'failed',  '2026-03-16 03:00:00', '2026-03-16 03:18:00');`

const TASK_INSTANCES_SEED = `CREATE TABLE task_instances (
  run_id      TEXT,
  task_id     TEXT,
  state       TEXT,      -- success | failed | upstream_failed | skipped (queued and running are transient)
  try_number  INTEGER,   -- 1 on the first attempt; higher means a retry ran
  duration_sec INTEGER   -- 0 on a task that never actually executed
);
INSERT INTO task_instances (run_id, task_id, state, try_number, duration_sec) VALUES
  ('ds_2026_03_11',    'extract_orders',  'success',         1, 231),
  ('ds_2026_03_11',    'clean_orders',    'success',         1, 494),
  ('ds_2026_03_11',    'load_facts',      'success',         1, 358),
  ('ds_2026_03_11',    'publish_metrics', 'success',         1,  88),
  ('ds_2026_03_13',    'extract_orders',  'success',         1, 212),
  ('ds_2026_03_13',    'clean_orders',    'success',         1, 486),
  ('ds_2026_03_13',    'load_facts',      'success',         1, 351),
  ('ds_2026_03_13',    'publish_metrics', 'success',         1,  94),
  ('ds_2026_03_14',    'extract_orders',  'success',         1, 205),
  ('ds_2026_03_14',    'clean_orders',    'failed',          2, 618),
  ('ds_2026_03_14',    'load_facts',      'upstream_failed', 1,   0),
  ('ds_2026_03_14',    'publish_metrics', 'upstream_failed', 1,   0),
  ('ds_2026_03_15',    'extract_orders',  'success',         1, 221),
  ('ds_2026_03_15',    'clean_orders',    'success',         2, 502),
  ('ds_2026_03_15',    'load_facts',      'success',         1, 366),
  ('ds_2026_03_15',    'publish_metrics', 'skipped',         1,   0),
  ('ds_2026_03_09',    'extract_orders',  'success',         1, 198),
  ('ds_2026_03_09',    'clean_orders',    'success',         1, 470),
  ('ds_2026_03_09',    'load_facts',      'success',         1, 340),
  ('ds_2026_03_09',    'publish_metrics', 'success',         1,  91),
  ('ds_2026_02_01',    'extract_orders',  'success',         1, 260),
  ('ds_2026_02_01',    'clean_orders',    'success',         1, 505),
  ('ds_2026_02_01',    'load_facts',      'success',         1, 372),
  ('ds_2026_02_01',    'publish_metrics', 'success',         1,  99),
  ('he_2026_03_15_08', 'ingest_events',   'success',         1, 141),
  ('he_2026_03_15_08', 'rollup_events',   'success',         1,  96),
  ('he_2026_03_15_09', 'ingest_events',   'success',         1, 138),
  ('he_2026_03_15_09', 'rollup_events',   'success',         1, 101),
  ('he_2026_03_15_10', 'ingest_events',   'failed',          2, 275),
  ('he_2026_03_15_10', 'rollup_events',   'upstream_failed', 1,   0),
  ('he_2026_03_15_11', 'ingest_events',   'failed',          2, 269),
  ('he_2026_03_15_11', 'rollup_events',   'upstream_failed', 1,   0),
  ('he_2026_01_20_03', 'ingest_events',   'success',         1, 132),
  ('he_2026_01_20_03', 'rollup_events',   'success',         1,  89),
  ('wd_2026_03_02',    'build_digest',    'success',         1, 930),
  ('wd_2026_03_02',    'send_digest',     'success',         1,  47),
  ('wd_2026_03_09',    'build_digest',    'success',         1, 962),
  ('wd_2026_03_09',    'send_digest',     'failed',          2,  58);`

const RUNS_AND_TASKS_SEED = ORCHESTRATOR_RUNS_SEED + "\n" + TASK_INSTANCES_SEED

// ---------------------------------------------------------------------------
// Module 8.1 — Orchestration Fundamentals
// ---------------------------------------------------------------------------

const dagsAndTaskStates: SqlLesson = {
  id: "de-l8-dags-and-task-states",
  title: "Runs, Task States, and the Data Interval",
  summary:
    "Read an orchestrator's own metadata to tell which runs and tasks are healthy, and explain why a run is responsible for a time range rather than for the moment it happened to execute.",
  estimatedMinutes: 26,
  difficulty: "easy",
  skills: [
    "DAG runs",
    "task states",
    "logical date and data interval",
    "backfill vs scheduled runs",
    "GROUP BY",
    "conditional counting",
    "date functions",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## A run owns a time range, not a moment

An orchestrator stores two things about every execution, and the interview answer lives in the difference between them.

A **DAG run** is one execution of the whole graph. It is bound to an immutable **data interval**: a half-open time range \`[data_interval_start, data_interval_end)\` that the run is responsible for. A daily \`daily_sales\` run for 2026-03-13 owns everything that happened between 2026-03-13 00:00 and 2026-03-14 00:00. That is the run's identity. It does not change if the run is retried at midnight, re-run by hand a week later, or backfilled next quarter.

Separately, the run has a **wall clock**: \`started_at\` and \`ended_at\`, when the machine actually did the work. A scheduled daily run starts just after its interval closes, so the two look almost the same and beginners conclude they are the same thing. A **backfill** proves they are not. A backfill run for 2026-02-01 that you launch on 2026-03-16 has a \`data_interval_end\` six weeks before its \`started_at\`.

The whole reason this matters is that your pipeline logic must filter on the interval, never on the clock. A job whose SQL says "yesterday" computed from the current time produces a different answer every time you run it, so it can never be safely re-run or backfilled. Research §5.2 names this the number one DAG anti-pattern: **never use \`datetime.now()\` in pipeline logic**. Take the date range from the run, not from the machine.

## The task instance lifecycle

Inside a run, each task gets one **task instance** row, and that row carries a state. The states are the vocabulary you answer failure questions with.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["state", "what happened", "did it consume compute", "what you do about it"],
  "rows": [
    ["queued", "the scheduler accepted it, no worker has picked it up", "no", "nothing, unless it sits there (starved pool)"],
    ["running", "a worker is executing it right now", "yes", "watch the duration against its SLA"],
    ["success", "it finished and reported no error", "yes", "check the rows it wrote before you believe it"],
    ["failed", "it raised, and it has no retries left", "yes", "this is the incident"],
    ["upstream_failed", "it never ran because something it depends on failed", "no", "fix the upstream, not this task"],
    ["skipped", "a branch or condition told the scheduler not to run it", "no", "confirm the branch logic was right"]
  ],
  "highlightCols": ["what you do about it"],
  "caption": "Six task-instance states. Only failed is an incident. upstream_failed is a symptom, and it is the state that makes a single failure look like ten."
}
\`\`\`

One failure at the top of a graph writes one \`failed\` row and a pile of \`upstream_failed\` rows. Counting raw failures without splitting those two states is how a one-task outage gets reported as a ten-task outage.

**Common mistake:** reading \`started_at\` as the answer to "what data is this?". It is the answer to "when did the machine work". A catchup or backfill run makes the two disagree by weeks, and a query that groups by \`started_at\` instead of the interval silently attributes February's data to March.

**Interview nuance:** "what happens when a task fails mid-DAG?" is answered with states, not with vendor names. The failing task goes to \`failed\`, everything downstream of it goes to \`upstream_failed\`, independent branches keep running, and the run itself is marked failed. Say that and you have answered the question for Airflow, Dagster, Prefect, and Step Functions at once.

> **On a real platform this differs.** Airflow 3.0 (GA April 2025) removed \`execution_date\` entirely: the concepts are now **logical date plus data interval**, and backfills are scheduler-managed and first class. Prep material written before 2025 still says \`execution_date\`, so saying it dates you. The tables here are named generically because the reasoning transfers: Dagster tracks the same idea as asset partitions, and Step Functions carries it as execution input.`,
    demoSeedSql: RUNS_AND_TASKS_SEED,
    demoCode: `-- The first thing you look at on call: the state of every task in the run that broke.
SELECT task_id,
       state,
       try_number,
       duration_sec
FROM task_instances
WHERE run_id = 'ds_2026_03_14'
ORDER BY task_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l8-dags-and-task-states-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each DAG's run health next to the damage inside its runs, as \`(dag_id, runs, failed_runs, success_pct, real_failures, blocked_tasks)\`, least healthy first, over \`orchestrator_runs(run_id, dag_id, logical_date, data_interval_start, data_interval_end, run_type, state, started_at, ended_at)\` joined to \`task_instances(run_id, task_id, state, try_number, duration_sec)\` on \`run_id\`.

\`runs\` is that DAG's number of runs and \`failed_runs\` its number of runs in state \`'failed'\`, so neither may be inflated by the join. \`success_pct\` is the percentage of its runs that succeeded, rounded to 2 decimals. \`real_failures\` counts task instances in state \`'failed'\` and \`blocked_tasks\` counts task instances in state \`'upstream_failed'\`, which are the incidents and the symptoms respectively. Alias the columns exactly, ordered by \`success_pct\` ascending and then \`dag_id\`.`,
    starterCode: `-- Per-DAG health: run-level reliability, plus the incidents and symptoms inside the runs.
SELECT r.dag_id
  -- count runs without letting the join multiply them, then count the two task states
FROM orchestrator_runs r
JOIN task_instances t ON t.run_id = r.run_id
GROUP BY r.dag_id
ORDER BY success_pct ASC, r.dag_id;`,
    hints: [
      "The join repeats each run once per task instance, so a plain `COUNT(*)` counts tasks, not runs. `COUNT(DISTINCT r.run_id) AS runs` is the fix.",
      "The same trap hits the failure count: `COUNT(DISTINCT CASE WHEN r.state = 'failed' THEN r.run_id END) AS failed_runs`. A `CASE` with no `ELSE` yields NULL, and `COUNT` ignores NULLs.",
      "The task-level columns are ordinary conditional sums over `t.state`, because there every row already is one task instance.",
    ],
    referenceSolution: `SELECT r.dag_id,
       COUNT(DISTINCT r.run_id) AS runs,
       COUNT(DISTINCT CASE WHEN r.state = 'failed' THEN r.run_id END) AS failed_runs,
       ROUND(100.0 * COUNT(DISTINCT CASE WHEN r.state = 'success' THEN r.run_id END) / COUNT(DISTINCT r.run_id), 2) AS success_pct,
       SUM(CASE WHEN t.state = 'failed' THEN 1 ELSE 0 END) AS real_failures,
       SUM(CASE WHEN t.state = 'upstream_failed' THEN 1 ELSE 0 END) AS blocked_tasks
FROM orchestrator_runs r
JOIN task_instances t ON t.run_id = r.run_id
GROUP BY r.dag_id
ORDER BY success_pct ASC, r.dag_id;`,
    singleFile: {
      seedSql: RUNS_AND_TASKS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["dag_id", "runs", "failed_runs", "success_pct", "real_failures", "blocked_tasks"],
        rows: [
          ["weekly_digest", 2, 1, 50, 1, 0],
          ["hourly_events", 5, 2, 60, 2, 2],
          ["daily_sales", 6, 1, 83.33, 1, 2],
        ],
      },
    },
  },
  practice: {
    id: "de-l8-dags-and-task-states-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every run that processed a data interval more than 1 day older than the day it started, as \`(run_id, dag_id, data_interval_end, started_at, lag_days)\`, biggest lag first, over \`orchestrator_runs\`.

\`lag_days\` is the whole number of days from the calendar date of \`data_interval_end\` to the calendar date of \`started_at\`. Keep only rows where \`lag_days\` is greater than 1, so a scheduled run that merely started a day late does not count as a catchup. Alias the columns exactly, ordered by \`lag_days\` descending and then \`run_id\`.`,
    starterCode: `-- Runs whose data interval is far older than the day the machine actually ran them.
SELECT run_id,
       dag_id,
       data_interval_end,
       started_at
  -- add lag_days, then keep only the runs with a lag above 1 day
FROM orchestrator_runs;`,
    hints: [
      "`date(started_at)` and `date(data_interval_end)` strip the time part so you compare calendar days.",
      "`julianday(a) - julianday(b)` is a day count as a real number; wrap it in `CAST(... AS INTEGER)` for a whole number of days.",
      "Filter in `WHERE` by repeating the expression, or compute it in a CTE and filter the CTE.",
    ],
    singleFile: {
      seedSql: ORCHESTRATOR_RUNS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["run_id", "dag_id", "data_interval_end", "started_at", "lag_days"],
        rows: [
          ["he_2026_01_20_03", "hourly_events", "2026-01-20 04:00:00", "2026-03-16 09:30:00", 55],
          ["ds_2026_02_01", "daily_sales", "2026-02-02 00:00:00", "2026-03-16 09:00:00", 42],
          ["ds_2026_03_09", "daily_sales", "2026-03-10 00:00:00", "2026-03-16 11:00:00", 6],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l8-dags-and-task-states-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many task instances are in each state, as \`(state, instances)\`, most common first, over \`task_instances(run_id, task_id, state, try_number, duration_sec)\`. Break ties by \`state\` alphabetically.`,
      starterCode: `-- One row per task-instance state with its count.
SELECT
FROM task_instances;`,
      hints: [
        "`GROUP BY state` with `COUNT(*) AS instances`.",
        "`ORDER BY instances DESC, state` makes the tie between two equally common states deterministic.",
      ],
      referenceSolution: `SELECT state, COUNT(*) AS instances
FROM task_instances
GROUP BY state
ORDER BY instances DESC, state;`,
      singleFile: {
        seedSql: TASK_INSTANCES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["state", "instances"],
          rows: [
            ["success", 29],
            ["failed", 4],
            ["upstream_failed", 4],
            ["skipped", 1],
          ],
        },
      },
    },
    {
      id: "de-l8-dags-and-task-states-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the longest-running task instance in each DAG, as \`(dag_id, task_id, duration_sec)\`, ordered by \`dag_id\`, over \`task_instances\` joined to \`orchestrator_runs\`.

\`task_instances\` has no \`dag_id\`, so join it to \`orchestrator_runs\` on \`run_id\` to find out which DAG each instance belongs to. Use \`ROW_NUMBER()\` to pick the one longest instance per DAG.`,
      starterCode: `-- Per DAG, the single task instance that ran longest.
WITH ranked AS (
  SELECT r.dag_id, t.task_id, t.duration_sec
    -- number the instances within each dag_id, longest first
  FROM task_instances t
  JOIN orchestrator_runs r ON r.run_id = t.run_id
)
SELECT dag_id, task_id, duration_sec
FROM ranked
;`,
      hints: [
        "`ROW_NUMBER() OVER (PARTITION BY r.dag_id ORDER BY t.duration_sec DESC) AS rn` inside the CTE.",
        "Filter the CTE with `WHERE rn = 1`, then `ORDER BY dag_id`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT r.dag_id,
         t.task_id,
         t.duration_sec,
         ROW_NUMBER() OVER (PARTITION BY r.dag_id ORDER BY t.duration_sec DESC) AS rn
  FROM task_instances t
  JOIN orchestrator_runs r ON r.run_id = t.run_id
)
SELECT dag_id, task_id, duration_sec
FROM ranked
WHERE rn = 1
ORDER BY dag_id;`,
      singleFile: {
        seedSql: RUNS_AND_TASKS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dag_id", "task_id", "duration_sec"],
          rows: [
            ["daily_sales", "clean_orders", 618],
            ["hourly_events", "ingest_events", 275],
            ["weekly_digest", "build_digest", 962],
          ],
        },
      },
    },
    {
      id: "de-l8-dags-and-task-states-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns, for each DAG in one row, the mean duration of its successful task instances and the mean duration of its failed ones, as \`(dag_id, avg_success_sec, avg_failed_sec)\`, ordered by \`dag_id\`.

Round both averages to 1 decimal. Instances in any other state (\`upstream_failed\`, \`skipped\`) must not pull either average down.`,
      starterCode: `-- Per DAG: mean duration of successes and of failures, side by side.
SELECT r.dag_id
  -- one averaged column per state, both in the same row
FROM task_instances t
JOIN orchestrator_runs r ON r.run_id = t.run_id
GROUP BY r.dag_id
ORDER BY r.dag_id;`,
      hints: [
        "`AVG(CASE WHEN t.state = 'success' THEN t.duration_sec END)` with no `ELSE`: the non-matching rows become NULL and `AVG` ignores NULLs.",
        "Writing `ELSE 0` instead would fold every skipped and upstream_failed instance in as a zero and wreck the average.",
        "Wrap each average in `ROUND(..., 1)`.",
      ],
      referenceSolution: `SELECT r.dag_id,
       ROUND(AVG(CASE WHEN t.state = 'success' THEN t.duration_sec END), 1) AS avg_success_sec,
       ROUND(AVG(CASE WHEN t.state = 'failed' THEN t.duration_sec END), 1) AS avg_failed_sec
FROM task_instances t
JOIN orchestrator_runs r ON r.run_id = t.run_id
GROUP BY r.dag_id
ORDER BY r.dag_id;`,
      singleFile: {
        seedSql: RUNS_AND_TASKS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dag_id", "avg_success_sec", "avg_failed_sec"],
          rows: [
            ["daily_sales", 297.1, 618],
            ["hourly_events", 116.2, 272],
            ["weekly_digest", 646.3, 58],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.1.2 seeds. The scheduler serializes a DAG into an edge table; sensors are
// ordinary tasks that happen to wait on something outside the graph.
//
// DELIBERATE RESEED: this lesson uses its own run ids (`ds_2026_04_01`, `ds_2026_04_02`,
// `he_2026_04_02_07`, `wd_2026_03_30`) rather than reusing 8.1.1's. It is a separate
// incident window with a different failure story, and sharing 8.1.1's run ids would have
// meant two lessons asserting different outcomes for the same run.
//
// `archive_orders` is a real edge with no task instance in either run: it was added to the
// DAG file after these runs finished, so the scheduler never created an instance for it.
// That is why the propagation query has to join the DOWNSTREAM end too rather than trusting
// the edge table alone.
//
// `sensor_waits` covers a wider window than `task_instances`: `ds_2026_03_31` is the night
// the payments partition never landed, which is the run where the sensor timed out.
// ---------------------------------------------------------------------------

const TASK_DEPENDENCIES_SEED = `CREATE TABLE task_dependencies (
  dag_id             TEXT,
  upstream_task_id   TEXT,
  downstream_task_id TEXT   -- one row per edge; this is the whole graph, nothing else is stored
);
INSERT INTO task_dependencies (dag_id, upstream_task_id, downstream_task_id) VALUES
  ('daily_sales',   'extract_orders',     'clean_orders'),
  ('daily_sales',   'clean_orders',       'load_facts'),
  ('daily_sales',   'clean_orders',       'archive_orders'),
  ('daily_sales',   'wait_for_payments',  'load_facts'),
  ('daily_sales',   'load_facts',         'publish_metrics'),
  ('daily_sales',   'load_facts',         'export_crm'),
  ('daily_sales',   'load_facts',         'notify_sales'),
  ('daily_sales',   'publish_metrics',    'notify_finance'),
  ('daily_sales',   'export_crm',         'notify_sales'),
  ('hourly_events', 'wait_for_partition', 'ingest_events'),
  ('hourly_events', 'ingest_events',      'rollup_events'),
  ('hourly_events', 'rollup_events',      'refresh_cache'),
  ('weekly_digest', 'build_digest',       'send_digest');`

const TASK_STATES_SEED = `CREATE TABLE task_instances (
  run_id     TEXT,
  dag_id     TEXT,     -- a real task_instance is keyed by (dag_id, run_id, task_id)
  task_id    TEXT,
  state      TEXT,
  try_number INTEGER
);
INSERT INTO task_instances (run_id, dag_id, task_id, state, try_number) VALUES
  ('ds_2026_04_01',    'daily_sales',   'extract_orders',     'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'wait_for_payments',  'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'clean_orders',       'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'load_facts',         'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'publish_metrics',    'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'export_crm',         'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'notify_finance',     'success',         1),
  ('ds_2026_04_01',    'daily_sales',   'notify_sales',       'success',         1),
  ('ds_2026_04_02',    'daily_sales',   'extract_orders',     'success',         1),
  ('ds_2026_04_02',    'daily_sales',   'wait_for_payments',  'success',         1),
  ('ds_2026_04_02',    'daily_sales',   'clean_orders',       'failed',          2),
  ('ds_2026_04_02',    'daily_sales',   'load_facts',         'upstream_failed', 1),
  ('ds_2026_04_02',    'daily_sales',   'publish_metrics',    'upstream_failed', 1),
  ('ds_2026_04_02',    'daily_sales',   'export_crm',         'upstream_failed', 1),
  ('ds_2026_04_02',    'daily_sales',   'notify_finance',     'upstream_failed', 1),
  ('ds_2026_04_02',    'daily_sales',   'notify_sales',       'upstream_failed', 1),
  ('he_2026_04_02_07', 'hourly_events', 'wait_for_partition', 'failed',          1),
  ('he_2026_04_02_07', 'hourly_events', 'ingest_events',      'upstream_failed', 1),
  ('he_2026_04_02_07', 'hourly_events', 'rollup_events',      'upstream_failed', 1),
  ('he_2026_04_02_07', 'hourly_events', 'refresh_cache',      'upstream_failed', 1),
  ('wd_2026_03_30',    'weekly_digest', 'build_digest',       'failed',          2),
  ('wd_2026_03_30',    'weekly_digest', 'send_digest',        'upstream_failed', 1);`

const SENSOR_WAITS_SEED = `CREATE TABLE sensor_waits (
  run_id            TEXT,
  task_id           TEXT,
  waits_for         TEXT,      -- the external thing the sensor pokes for
  poke_interval_sec INTEGER,   -- how often it re-checks
  timeout_sec       INTEGER,   -- how long it waits before giving up
  -- the WAIT's outcome; either way the sensor's own task instance ends up failed
  state             TEXT       -- success | failed | timed_out
);
INSERT INTO sensor_waits (run_id, task_id, waits_for, poke_interval_sec, timeout_sec, state) VALUES
  ('ds_2026_03_31',    'wait_for_payments',  'payments.settlement partition dt=2026-03-31',        60, 3600, 'timed_out'),
  ('ds_2026_04_01',    'wait_for_payments',  'payments.settlement partition dt=2026-04-01',        60, 3600, 'success'),
  ('ds_2026_04_02',    'wait_for_payments',  'payments.settlement partition dt=2026-04-02',        60, 3600, 'success'),
  ('he_2026_04_02_06', 'wait_for_partition', 's3://lake/raw/events/dt=2026-04-02/hour=06/_SUCCESS', 30,  900, 'success'),
  ('he_2026_04_02_07', 'wait_for_partition', 's3://lake/raw/events/dt=2026-04-02/hour=07/_SUCCESS', 30,  900, 'failed');`

const DAG_GRAPH_SEED = TASK_DEPENDENCIES_SEED + "\n" + TASK_STATES_SEED

const dependenciesAndSensors: SqlLesson = {
  id: "de-l8-dependencies-and-sensors",
  title: "Dependencies, Blocked Tasks, and Sensors",
  summary:
    "Trace why a task did not run by walking the scheduler's dependency edges to whatever blocked it, and read sensor waits as first-class tasks that can time out.",
  estimatedMinutes: 27,
  difficulty: "medium",
  skills: [
    "dependency edges",
    "upstream_failed propagation",
    "sensors and timeouts",
    "blast-radius analysis",
    "self join",
    "recursive CTE",
    "LEFT JOIN anti-join",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The graph is a table of edges

A DAG looks like a picture and is stored as rows. When the scheduler serializes your pipeline it writes one row per **edge**: a \`dag_id\`, an upstream task, and a downstream task. That is the entire graph. There is no separate "shape" object, which is exactly why every graph question about a pipeline is answerable in SQL.

\`\`\`csdiagram
{
  "type": "topology",
  "title": "daily_sales, run ds_2026_04_02",
  "layout": "lr",
  "nodes": [
    { "id": "extract", "label": "extract_orders", "kind": "service" },
    { "id": "sensor", "label": "wait_for_payments", "kind": "external" },
    { "id": "clean", "label": "clean_orders", "kind": "service" },
    { "id": "load", "label": "load_facts", "kind": "db" },
    { "id": "metrics", "label": "publish_metrics", "kind": "service" },
    { "id": "crm", "label": "export_crm", "kind": "service" }
  ],
  "edges": [
    { "from": "extract", "to": "clean" },
    { "from": "clean", "to": "load" },
    { "from": "sensor", "to": "load", "label": "waits on payments" },
    { "from": "load", "to": "metrics" },
    { "from": "load", "to": "crm" }
  ],
  "stages": [
    { "adds": ["extract", "sensor"], "note": "Two roots, both green. extract_orders is state success, and the sensor wait_for_payments is state success because its partition landed." },
    { "adds": ["clean"], "note": "clean_orders raised on its last allowed try and is state failed. It is the one real incident in this run." },
    { "adds": ["load"], "note": "load_facts is state upstream_failed. Its sensor was green, but one of its two upstreams was not, so the scheduler never attempted it." },
    { "adds": ["metrics", "crm"], "note": "publish_metrics and export_crm are upstream_failed too. Both branches inherit the block: one failure, three idle tasks." }
  ],
  "caption": "One failed task and the closure it froze, drawn down to the first fan-out. Only clean_orders is an incident; everything to its right is upstream_failed."
}
\`\`\`

## Failure propagates, it does not multiply

A task runs when every one of its upstreams succeeded. When one upstream fails, the scheduler does not attempt the downstream at all: it marks it \`upstream_failed\` and moves on, and the same happens to that task's downstreams, all the way to the leaves. The set of tasks reachable from the failure is its **blast radius**, and that is what your stakeholders actually care about. "clean_orders failed" means nothing to the finance team. "the CRM export and the finance metrics for 2026-03-14 are stale" means everything.

One hop is a self join: join the edge table to the task instances twice, once for each end of the edge, and keep the edges whose upstream end failed. The full closure is a recursive CTE over the same edge table, which is the same technique Level 4 used on an org chart, pointed at operational metadata instead.

## Sensors are tasks that wait

A **sensor** is an ordinary task whose job is to wait for something outside the graph: a partition landing in the lake, a file arriving in a bucket, an upstream table's row count crossing a threshold. It **pokes** on an interval, and it has a **timeout**. If the thing never shows up, the sensor gives up and fails, and everything downstream of it goes \`upstream_failed\` exactly like any other failure.

That timeout is a design decision, not a detail. Set it too short and a slow but healthy upstream pages you. Set it longer than the schedule interval and yesterday's sensor is still holding a worker slot when today's run starts, which is how a pool starves and every DAG on the cluster stalls behind one waiting task.

**Common mistake:** paging on the \`upstream_failed\` count. Those tasks did not break, they were never attempted, and they will clear themselves the moment the real failure is fixed and the run is cleared. Alert on \`failed\`, report on \`upstream_failed\`.

**Interview nuance:** "this task failed, what is stale?" is a graph question, and answering it with a recursive walk of the dependency edges is the answer that separates a candidate who has operated a pipeline from one who has only drawn one. Say blast radius out loud, and name the two ways a task can fail to run: it failed, or something it waited on did.

> **On a real platform this differs.** Airflow 3 adds event-driven scheduling and **Assets**, which invert the framing: instead of "run task B after task A", you declare "this asset is produced from those assets" and the scheduler derives the edges. Dagster made that the core model from the start. The stored shape is still a graph, and this query still works; what changes is who wrote the edges.`,
    demoSeedSql: DAG_GRAPH_SEED,
    demoCode: `-- One hop of propagation: every failed task and what it directly froze.
SELECT up.run_id,
       up.task_id AS failed_task,
       dn.task_id AS blocked_task,
       dn.state   AS blocked_state
FROM task_instances up
JOIN task_dependencies td
  ON td.dag_id = up.dag_id AND td.upstream_task_id = up.task_id
JOIN task_instances dn
  ON dn.dag_id = up.dag_id AND dn.run_id = up.run_id AND dn.task_id = td.downstream_task_id
WHERE up.state = 'failed'
ORDER BY up.run_id, blocked_task;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l8-dependencies-and-sensors-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every task instance blocked by a directly failed upstream, as \`(task_id, upstream_task_id, upstream_state)\`, ordered by \`task_id\`, over \`task_dependencies(dag_id, upstream_task_id, downstream_task_id)\` and \`task_instances(run_id, dag_id, task_id, state, try_number)\`.

Join the edge table to \`task_instances\` twice, once for the upstream end of the edge and once for the downstream end, matching on the same \`dag_id\` and the same \`run_id\`. Keep only the edges whose upstream instance is in state \`'failed'\`. Alias the columns exactly.`,
    starterCode: `-- Tasks that never started because a task feeding them failed.
SELECT dn.task_id AS task_id,
       td.upstream_task_id AS upstream_task_id
  -- add the upstream's state, and keep only the failed upstreams
FROM task_dependencies td
JOIN task_instances up
  ON up.dag_id = td.dag_id AND up.task_id = td.upstream_task_id
ORDER BY task_id;`,
    hints: [
      "The edge table is the driver: each row already names both ends, so you need one join per end.",
      "The second join has three conditions: `dn.dag_id = td.dag_id`, `dn.run_id = up.run_id`, and `dn.task_id = td.downstream_task_id`. Dropping the `run_id` condition pairs tasks from different runs.",
      "`WHERE up.state = 'failed'` keeps the real failures and excludes the `upstream_failed` ones, which are symptoms rather than causes.",
    ],
    referenceSolution: `SELECT dn.task_id AS task_id,
       td.upstream_task_id AS upstream_task_id,
       up.state AS upstream_state
FROM task_dependencies td
JOIN task_instances up
  ON up.dag_id = td.dag_id AND up.task_id = td.upstream_task_id
JOIN task_instances dn
  ON dn.dag_id = td.dag_id AND dn.run_id = up.run_id AND dn.task_id = td.downstream_task_id
WHERE up.state = 'failed'
ORDER BY task_id;`,
    singleFile: {
      seedSql: DAG_GRAPH_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["task_id", "upstream_task_id", "upstream_state"],
        rows: [
          ["ingest_events", "wait_for_partition", "failed"],
          ["load_facts", "clean_orders", "failed"],
          ["send_digest", "build_digest", "failed"],
        ],
      },
    },
  },
  practice: {
    id: "de-l8-dependencies-and-sensors-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the full downstream closure of the failed \`clean_orders\` task in the \`daily_sales\` DAG, as \`(task_id, depth)\`, nearest first, over \`task_dependencies\`.

\`depth\` is the number of edges from \`clean_orders\` to that task, so its direct downstreams are depth 1. A task reachable by more than one path appears once, at its shortest depth. Alias the columns exactly, ordered by \`depth\` ascending and then \`task_id\`.`,
    starterCode: `-- Blast radius: everything downstream of the failed clean_orders task.
WITH RECURSIVE downstream(task_id, depth) AS (
  -- anchor: the direct downstreams of clean_orders, at depth 1

  -- recursive step: follow each edge one more hop
)
SELECT task_id, depth
FROM downstream;`,
    hints: [
      "The anchor selects `downstream_task_id, 1` from `task_dependencies` where `dag_id = 'daily_sales'` and `upstream_task_id = 'clean_orders'`.",
      "The recursive step joins `task_dependencies` back to the CTE on `upstream_task_id = downstream.task_id` and adds 1 to `depth`.",
      "Collapse repeated paths with `GROUP BY task_id` and `MIN(depth)` in the final SELECT.",
    ],
    singleFile: {
      seedSql: TASK_DEPENDENCIES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["task_id", "depth"],
        rows: [
          ["archive_orders", 1],
          ["load_facts", 1],
          ["export_crm", 2],
          ["notify_sales", 2],
          ["publish_metrics", 2],
          ["notify_finance", 3],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l8-dependencies-and-sensors-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns every DAG root, meaning a task that no other task feeds, as \`(dag_id, task_id)\`, ordered by \`dag_id\` then \`task_id\`, over \`task_dependencies\`.

A root is a task that appears as an \`upstream_task_id\` but never as a \`downstream_task_id\` in the same DAG. List each root once.`,
      starterCode: `-- Tasks with nothing upstream of them: where every run begins.
SELECT DISTINCT td.dag_id, td.upstream_task_id AS task_id
FROM task_dependencies td
  -- left join the edge table back to itself, then keep the non-matches
ORDER BY td.dag_id, task_id;`,
      hints: [
        "`LEFT JOIN task_dependencies up ON up.dag_id = td.dag_id AND up.downstream_task_id = td.upstream_task_id`.",
        "`WHERE up.downstream_task_id IS NULL` is the anti-join: it keeps the rows that found no upstream edge.",
      ],
      referenceSolution: `SELECT DISTINCT td.dag_id, td.upstream_task_id AS task_id
FROM task_dependencies td
LEFT JOIN task_dependencies up
  ON up.dag_id = td.dag_id AND up.downstream_task_id = td.upstream_task_id
WHERE up.downstream_task_id IS NULL
ORDER BY td.dag_id, task_id;`,
      singleFile: {
        seedSql: TASK_DEPENDENCIES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dag_id", "task_id"],
          rows: [
            ["daily_sales", "extract_orders"],
            ["daily_sales", "wait_for_payments"],
            ["hourly_events", "wait_for_partition"],
            ["weekly_digest", "build_digest"],
          ],
        },
      },
    },
    {
      id: "de-l8-dependencies-and-sensors-drill-2",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the sensor that gave up waiting, with what it was waiting on and how long it waited before quitting, as \`(run_id, task_id, waits_for, timeout_sec)\`, over \`sensor_waits(run_id, task_id, waits_for, poke_interval_sec, timeout_sec, state)\`.

A sensor that gave up is in state \`'timed_out'\`.`,
      starterCode: `-- The sensor whose external dependency never showed up.
SELECT run_id, task_id, waits_for, timeout_sec
FROM sensor_waits
;`,
      hints: [
        "One `WHERE` on `state`.",
        "`'timed_out'` is not the same as `'failed'`: a timeout means nothing arrived, a failure means the poke itself broke.",
      ],
      referenceSolution: `SELECT run_id, task_id, waits_for, timeout_sec
FROM sensor_waits
WHERE state = 'timed_out';`,
      singleFile: {
        seedSql: SENSOR_WAITS_SEED,
        assertColumnNames: true,
        expected: {
          columns: ["run_id", "task_id", "waits_for", "timeout_sec"],
          rows: [
            [
              "ds_2026_03_31",
              "wait_for_payments",
              "payments.settlement partition dt=2026-03-31",
              3600,
            ],
          ],
        },
      },
    },
    {
      id: "de-l8-dependencies-and-sensors-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns each task's direct downstream fan-out, as \`(dag_id, task_id, downstream_count)\`, widest first, over \`task_dependencies\`. Break ties by \`task_id\` alphabetically.

A task's fan-out is how many tasks it feeds directly. Tasks that feed nothing do not appear.`,
      starterCode: `-- How many tasks each task directly unblocks.
SELECT dag_id,
       upstream_task_id AS task_id
  -- count the edges leaving each task
FROM task_dependencies
;`,
      hints: [
        "Group by `dag_id, upstream_task_id` and `COUNT(*) AS downstream_count`.",
        "`ORDER BY downstream_count DESC, task_id`. The widest fan-out is the task whose failure hurts most.",
      ],
      referenceSolution: `SELECT dag_id,
       upstream_task_id AS task_id,
       COUNT(*) AS downstream_count
FROM task_dependencies
GROUP BY dag_id, upstream_task_id
ORDER BY downstream_count DESC, task_id;`,
      singleFile: {
        seedSql: TASK_DEPENDENCIES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dag_id", "task_id", "downstream_count"],
          rows: [
            ["daily_sales", "load_facts", 3],
            ["daily_sales", "clean_orders", 2],
            ["weekly_digest", "build_digest", 1],
            ["daily_sales", "export_crm", 1],
            ["daily_sales", "extract_orders", 1],
            ["hourly_events", "ingest_events", 1],
            ["daily_sales", "publish_metrics", 1],
            ["hourly_events", "rollup_events", 1],
            ["hourly_events", "wait_for_partition", 1],
            ["daily_sales", "wait_for_payments", 1],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.1.3 seeds. Seven consecutive daily_sales runs (logical dates 2026-03-10 through
// 2026-03-16, each executed the following morning) plus the scheduler's alert outbox.
// `sla_sec` is the freshness promise for that task: exceeding it is an SLA miss even when
// the task eventually succeeds.
//
// Three details in this seed exist to make the graded predicates load-bearing:
//  - `load_facts` carries `max_tries = 3` (one retry more than the others), and on
//    ds_2026_03_10 it failed at try 2 of 3 by raising a fail-fast error. That row is a
//    failure that is NOT exhausted, so `try_number = max_tries` has a negative control.
//  - `run_checks` is a data-quality task that legitimately writes no rows, so its average
//    `rows_written` is 0 and the silent-success query needs its `avg_rows > 0` guard.
//  - clean_orders on ds_2026_03_14 blew its SLA AND failed, so counting SLA misses only
//    among successes gives the wrong answer.
// ---------------------------------------------------------------------------

const TRIAGE_TASK_INSTANCES_SEED = `CREATE TABLE task_instances (
  run_id       TEXT,
  task_id      TEXT,
  state        TEXT,
  try_number   INTEGER,   -- attempt number that produced this final state
  max_tries    INTEGER,   -- total attempts allowed; try_number = max_tries on a failure means it is exhausted
  duration_sec INTEGER,
  rows_written INTEGER,   -- the number that tells you whether a green task did any work
  sla_sec      INTEGER    -- the task's promised maximum duration
);
INSERT INTO task_instances (run_id, task_id, state, try_number, max_tries, duration_sec, rows_written, sla_sec) VALUES
  ('ds_2026_03_10', 'extract_orders',  'success',         1, 2, 236, 51100, 300),
  ('ds_2026_03_10', 'clean_orders',    'success',         1, 2, 505, 50700, 600),
  ('ds_2026_03_10', 'load_facts',      'failed',          2, 3, 190,     0, 480),
  ('ds_2026_03_10', 'publish_metrics', 'upstream_failed', 1, 2,   0,     0, 180),
  ('ds_2026_03_10', 'run_checks',      'upstream_failed', 1, 2,   0,     0, 120),
  ('ds_2026_03_11', 'extract_orders',  'success',         1, 2, 241, 52310, 300),
  ('ds_2026_03_11', 'clean_orders',    'success',         1, 2, 512, 51880, 600),
  ('ds_2026_03_11', 'load_facts',      'success',         2, 3, 402, 50420, 480),
  ('ds_2026_03_11', 'publish_metrics', 'success',         1, 2,  96,   128, 180),
  ('ds_2026_03_11', 'run_checks',      'success',         1, 2,  63,     0, 120),
  ('ds_2026_03_12', 'extract_orders',  'success',         2, 2, 268, 51940, 300),
  ('ds_2026_03_12', 'clean_orders',    'success',         1, 2, 498, 51500, 600),
  ('ds_2026_03_12', 'load_facts',      'success',         1, 3, 411, 50110, 480),
  ('ds_2026_03_12', 'publish_metrics', 'success',         1, 2, 101,   131, 180),
  ('ds_2026_03_12', 'run_checks',      'success',         1, 2,  58,     0, 120),
  ('ds_2026_03_13', 'extract_orders',  'success',         1, 2, 250, 52760, 300),
  ('ds_2026_03_13', 'clean_orders',    'success',         1, 2, 690, 52300, 600),
  ('ds_2026_03_13', 'load_facts',      'success',         1, 3, 455, 50880, 480),
  ('ds_2026_03_13', 'publish_metrics', 'failed',          2, 2,  78,     0, 180),
  ('ds_2026_03_13', 'run_checks',      'upstream_failed', 1, 2,   0,     0, 120),
  ('ds_2026_03_14', 'extract_orders',  'success',         1, 2, 244, 51230, 300),
  ('ds_2026_03_14', 'clean_orders',    'failed',          2, 2, 640,     0, 600),
  ('ds_2026_03_14', 'load_facts',      'upstream_failed', 1, 3,   0,     0, 480),
  ('ds_2026_03_14', 'publish_metrics', 'upstream_failed', 1, 2,   0,     0, 180),
  ('ds_2026_03_14', 'run_checks',      'upstream_failed', 1, 2,   0,     0, 120),
  ('ds_2026_03_15', 'extract_orders',  'success',         1, 2, 239, 52050, 300),
  ('ds_2026_03_15', 'clean_orders',    'success',         2, 2, 575, 51700, 600),
  ('ds_2026_03_15', 'load_facts',      'success',         1, 3, 468, 50260, 480),
  ('ds_2026_03_15', 'publish_metrics', 'success',         1, 2, 105,   133, 180),
  ('ds_2026_03_15', 'run_checks',      'success',         1, 2,  61,     0, 120),
  ('ds_2026_03_16', 'extract_orders',  'success',         2, 2, 289, 51600, 300),
  ('ds_2026_03_16', 'clean_orders',    'success',         1, 2, 505, 51100, 600),
  ('ds_2026_03_16', 'load_facts',      'success',         1, 3, 402,     0, 480),
  ('ds_2026_03_16', 'publish_metrics', 'success',         1, 2, 214,   129, 180),
  ('ds_2026_03_16', 'run_checks',      'success',         1, 2,  66,     0, 120);`

const ALERTS_SEED = `CREATE TABLE alerts (
  alert_id   INTEGER,
  dag_id     TEXT,
  task_id    TEXT,
  alert_type TEXT,   -- failure | sla_miss
  sent_at    TEXT    -- one row per notification actually delivered, retries included
);
INSERT INTO alerts (alert_id, dag_id, task_id, alert_type, sent_at) VALUES
  (1, 'daily_sales', 'extract_orders',  'failure',  '2026-03-13 02:06:00'),
  (2, 'daily_sales', 'clean_orders',    'sla_miss', '2026-03-14 02:18:00'),
  (3, 'daily_sales', 'publish_metrics', 'failure',  '2026-03-14 02:20:00'),
  (4, 'daily_sales', 'publish_metrics', 'failure',  '2026-03-14 02:22:00'),
  (5, 'daily_sales', 'clean_orders',    'failure',  '2026-03-15 02:10:00'),
  (6, 'daily_sales', 'clean_orders',    'failure',  '2026-03-15 02:15:00'),
  (7, 'daily_sales', 'clean_orders',    'failure',  '2026-03-16 02:09:00'),
  (8, 'daily_sales', 'extract_orders',  'failure',  '2026-03-17 02:06:00'),
  (9, 'daily_sales', 'publish_metrics', 'sla_miss', '2026-03-17 02:11:00');`

const retriesSlasAlerting: SqlLesson = {
  id: "de-l8-retries-slas-alerting",
  title: "Retries, SLAs, and the Alert You Page On",
  summary:
    "Decide what deserves a page: separate the transient failures a retry absorbed from exhausted retries and SLA misses, then build the on-call triage report unaided.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "retry policy",
    "try_number vs max_tries",
    "SLA miss",
    "alert fatigue",
    "silent success",
    "conditional aggregation",
    "HAVING",
    "multi-metric reporting",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## A retry that worked is not an incident

Every task carries a retry budget. Two fields hold it: \`try_number\`, the attempt that produced the row's final state, and \`max_tries\`, how many attempts the task was allowed. The canonical setting is about **2** (Research §5.2), and the number is deliberately small. Retries exist to absorb the transient stuff, a network blip, a briefly locked table, a rate limit. They do not exist to hide a bug. Ten retries turn a five-minute failure into an hour of the pipeline quietly re-running broken code before anyone hears about it.

One arithmetic warning before you write the SQL. Real Airflow stores \`max_tries\` as the number of RETRIES, not the number of attempts, so a task configured with \`retries=2\` runs as try 1, try 2, try 3 and lands its terminal failure at \`try_number = max_tries + 1\`. This lesson's table uses \`max_tries\` as the total attempt budget instead, so the exhausted test is the plain \`try_number = max_tries\` and you can spend your attention on the reasoning rather than on an off-by-one. When you query a real metadata database, check which convention that version uses before you trust the comparison. In the seed here every task is allowed 2 attempts except \`load_facts\`, which is allowed 3 because it writes to a remote warehouse.

That gives you two very different events sharing one word:

- **A retry save.** \`state = 'success'\` and \`try_number > 1\`. Something hiccuped and the machine handled it. This is the system working. It belongs in a weekly report, not on a phone at 3am.
- **An exhausted retry.** \`state = 'failed'\` and \`try_number = max_tries\`. Every attempt was used and the task is still broken. This is the incident.

Not every red task spent its budget, which is why that second condition is not decoration. A task that raises a fail-fast error, Airflow's \`AirflowFailException\`, or that an operator marks failed by hand, stops with attempts still on the clock: \`state = 'failed'\` and \`try_number\` below \`max_tries\`. It is a real failure, but the retry policy is not the thing to argue about, because retrying was never going to help.

Alert fatigue is what happens when you treat them the same. Fire on every attempt and the person on call learns that the pipeline channel is noise, and then they miss the one page that mattered.

## The SLA miss is a separate failure

A **service level agreement** on a task is a freshness promise: "load_facts finishes within 8 minutes". Missing it is its own kind of failure, and the thing that makes it worth teaching is that **the task can succeed and still miss**. A green run that took three times as long still means the dashboard was stale when the business opened. Alerting only on failures misses this entirely.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["signal", "how you detect it", "does it page", "why"],
  "rows": [
    ["retry save", "state = 'success' AND try_number > 1", "no", "the system already recovered; it belongs in a trend, not a page"],
    ["exhausted retry", "state = 'failed' AND try_number = max_tries", "yes", "every attempt was spent and the data did not land"],
    ["SLA miss", "duration_sec > sla_sec", "yes", "the data is late even though the run is green"],
    ["silent success", "state = 'success' AND rows_written far below normal", "yes", "nothing is red and the data is missing anyway"]
  ],
  "highlightCols": ["does it page"],
  "caption": "Four signals from the same task_instances table. Two are noise-adjacent, two are incidents, and only one of the four is visible on a status dashboard."
}
\`\`\`

## Silent success: green pipeline, empty dashboard

The most-missed production failure has no red anywhere (Research §5.7). Every task returns \`success\`, the run is green, and the table is empty or a tenth of its normal size. An upstream API returned an empty page, a filter got tightened, a partition path changed and the read matched nothing. Nothing raised, so nothing alerted.

The only defense is to check the work, not the status. Compare each task's \`rows_written\` against what that same task normally writes, and treat a collapse as a failure whatever the state column says. That is the bridge into Module 8.4: a test is a query that returns violating rows, and it passes when it returns none.

\`\`\`cswidget
{
  "type": "check",
  "kind": "predict",
  "id": "green-pipeline-empty-dashboard",
  "prompt": "You are on call. The daily_sales DAG is green for last night, every task is 'success', and the finance dashboard is empty. What is the FIRST thing you check?",
  "options": [
    {
      "label": "The rows_written for each task in that run, compared against what those tasks normally write",
      "correct": true,
      "feedback": "Right. The run state already told you everything it knows and it said nothing is wrong, so the next signal is volume. Comparing this run's rows_written to the task's own history is what turns an invisible failure into a visible one, and it points at the first task in the chain that broke."
    },
    {
      "label": "The scheduler logs for exceptions",
      "feedback": "Reasonable instinct, and it is where you will end up. But a silent success has no exception by definition, so starting in the logs costs you the twenty minutes it takes to conclude they are clean."
    },
    {
      "label": "Re-run the DAG and see if it fixes itself",
      "feedback": "This is the most common wrong move. A deterministic empty read reproduces exactly, so you learn nothing, and if the source has since refilled you have destroyed the evidence of what actually happened."
    },
    {
      "label": "Page the dashboard owner, since the pipeline reports success",
      "feedback": "Handing it back on the strength of a green status is exactly the trap this lesson exists to break. Green means the code did not raise, not that the data arrived."
    }
  ],
  "reveal": "The four-beat triage answer, in order. 1) Check rows written for the run, not just the run state. 2) Compare that count to the task's own historical volume, because 'zero' and 'a tenth of normal' are the same class of failure. 3) Walk upstream to the first task whose output volume broke, since everything after it is only propagating the emptiness. 4) Ask whether the source itself went empty or a filter or partition path changed, which is the difference between an incident you own and one you escalate."
}
\`\`\`

**Common mistake:** counting failures without splitting exhausted ones from rescued ones. That single number cannot tell you whether your platform is flaky and self-healing or actually broken, and it is the number most junior dashboards show.

**Interview nuance:** "how many retries would you configure and why" has a real answer: around two, because retries are for transient faults, and anything that survives two attempts needs a human rather than a third attempt. And "the DAG is green but the dashboard is empty" is the silent-success story. Answer it with rows written, compared against that task's own history, walked upstream to the first task whose volume broke.

> **On a real platform this differs.** The detection queries are the same everywhere; the delivery is not. Real alert routing lives in the orchestrator's callbacks and a pager tool such as PagerDuty or Opsgenie, with severity, escalation policies, and on-call rotations attached. The \`alerts\` table here is the outbox those callbacks write to, and querying the outbox is how you prove to yourself that your alerting is signal rather than noise. One vendor detail is worth flagging because pre-2025 material gets it wrong: **Airflow 3.0 removed task SLAs outright**, the \`sla\` parameter, \`sla_miss_callback\`, and the \`sla_miss\` table with it, and Airflow 3.1 replaced them with Deadline Alerts (AIP-86), which fix the old ambiguity about when the clock starts by letting you anchor the deadline to the queue time or the run's start explicitly. Configure an \`sla=\` on Airflow 3 and nothing happens. The \`duration_sec > sla_sec\` reasoning below is unchanged; only the vendor mechanism moved.`,
    demoSeedSql: TRIAGE_TASK_INSTANCES_SEED,
    demoCode: `-- The retries that saved you: succeeded, but not on the first attempt.
SELECT run_id, task_id, try_number, max_tries, duration_sec
FROM task_instances
WHERE state = 'success' AND try_number > 1
ORDER BY run_id, task_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l8-retries-slas-alerting-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every task instance whose retry budget mattered, as \`(run_id, task_id, try_number, max_tries, outcome)\`, over \`task_instances(run_id, task_id, state, try_number, max_tries, duration_sec, rows_written, sla_sec)\`.

Include two kinds of row and label each one in \`outcome\`: \`'exhausted'\` when the instance failed on its last allowed attempt (\`state = 'failed'\` and \`try_number = max_tries\`), and \`'retry_save'\` when it succeeded but not on the first attempt (\`state = 'success'\` and \`try_number > 1\`). Alias the columns exactly, ordered by \`outcome\`, then \`run_id\`, then \`task_id\`.`,
    starterCode: `-- Exhausted retries and retry saves, labelled so on-call can tell them apart.
SELECT run_id,
       task_id,
       try_number,
       max_tries
  -- add the outcome label, then keep only the two kinds of row
FROM task_instances
ORDER BY outcome, run_id, task_id;`,
    hints: [
      "A `CASE` expression builds the label: `CASE WHEN state = 'failed' AND try_number = max_tries THEN 'exhausted' ELSE 'retry_save' END AS outcome`.",
      "The `WHERE` keeps exactly the two shapes: `(state = 'failed' AND try_number = max_tries) OR (state = 'success' AND try_number > 1)`.",
      "An `upstream_failed` instance is neither. It never spent an attempt, so it must not appear.",
    ],
    referenceSolution: `SELECT run_id,
       task_id,
       try_number,
       max_tries,
       CASE WHEN state = 'failed' AND try_number = max_tries THEN 'exhausted' ELSE 'retry_save' END AS outcome
FROM task_instances
WHERE (state = 'failed' AND try_number = max_tries)
   OR (state = 'success' AND try_number > 1)
ORDER BY outcome, run_id, task_id;`,
    singleFile: {
      seedSql: TRIAGE_TASK_INSTANCES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["run_id", "task_id", "try_number", "max_tries", "outcome"],
        rows: [
          ["ds_2026_03_13", "publish_metrics", 2, 2, "exhausted"],
          ["ds_2026_03_14", "clean_orders", 2, 2, "exhausted"],
          ["ds_2026_03_11", "load_facts", 2, 3, "retry_save"],
          ["ds_2026_03_12", "extract_orders", 2, 2, "retry_save"],
          ["ds_2026_03_15", "clean_orders", 2, 2, "retry_save"],
          ["ds_2026_03_16", "extract_orders", 2, 2, "retry_save"],
        ],
      },
    },
  },
  practice: {
    id: "de-l8-retries-slas-alerting-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the on-call triage report, as \`(task_id, runs, exhausted_failures, sla_misses, retry_saves, zero_row_successes)\`, worst first, over \`task_instances(run_id, task_id, state, try_number, max_tries, duration_sec, rows_written, sla_sec)\`.

One row per task. \`runs\` is how many instances of that task exist. \`exhausted_failures\` counts instances with \`state = 'failed'\` and \`try_number = max_tries\`. \`sla_misses\` counts instances whose \`duration_sec\` exceeds their \`sla_sec\`, whatever their state. \`retry_saves\` counts instances with \`state = 'success'\` and \`try_number > 1\`. \`zero_row_successes\` counts instances with \`state = 'success'\` and \`rows_written = 0\`. Alias the columns exactly, ordered by \`exhausted_failures\` descending, then \`sla_misses\` descending, then \`task_id\`.`,
    starterCode: `SELECT
FROM task_instances;`,
    hints: [],
    singleFile: {
      seedSql: TRIAGE_TASK_INSTANCES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: [
          "task_id",
          "runs",
          "exhausted_failures",
          "sla_misses",
          "retry_saves",
          "zero_row_successes",
        ],
        rows: [
          ["clean_orders", 7, 1, 2, 1, 0],
          ["publish_metrics", 7, 1, 1, 0, 0],
          ["extract_orders", 7, 0, 0, 2, 0],
          ["load_facts", 7, 0, 0, 1, 1],
          ["run_checks", 7, 0, 0, 0, 4],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l8-retries-slas-alerting-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many alerts of each type were sent, as \`(alert_type, alerts)\`, most first, over \`alerts(alert_id, dag_id, task_id, alert_type, sent_at)\`.`,
      starterCode: `-- The alert outbox, summarized by type.
SELECT
FROM alerts;`,
      hints: [
        "`GROUP BY alert_type` with `COUNT(*) AS alerts`.",
        "`ORDER BY alerts DESC`. The gap between this total and the number of real incidents is your alert-fatigue problem.",
      ],
      referenceSolution: `SELECT alert_type, COUNT(*) AS alerts
FROM alerts
GROUP BY alert_type
ORDER BY alerts DESC, alert_type;`,
      singleFile: {
        seedSql: ALERTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["alert_type", "alerts"],
          rows: [
            ["failure", 7],
            ["sla_miss", 2],
          ],
        },
      },
    },
    {
      id: "de-l8-retries-slas-alerting-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns each task that needed a retry to succeed on more than one of its runs, as \`(task_id, retry_saves)\`, most first, over \`task_instances\`.

A retry save is an instance with \`state = 'success'\` and \`try_number > 1\`. Keep only tasks with more than one of them: a single flaky run is noise, a repeat offender is a bug.`,
      starterCode: `-- Tasks that keep needing a second attempt.
SELECT task_id
  -- count this task's retry saves, then drop the tasks with at most one
FROM task_instances
GROUP BY task_id;`,
      hints: [
        "`SUM(CASE WHEN state = 'success' AND try_number > 1 THEN 1 ELSE 0 END) AS retry_saves`.",
        "`HAVING` filters groups after aggregation, so repeat the conditional sum there with `> 1`.",
      ],
      referenceSolution: `SELECT task_id,
       SUM(CASE WHEN state = 'success' AND try_number > 1 THEN 1 ELSE 0 END) AS retry_saves
FROM task_instances
GROUP BY task_id
HAVING SUM(CASE WHEN state = 'success' AND try_number > 1 THEN 1 ELSE 0 END) > 1
ORDER BY retry_saves DESC, task_id;`,
      singleFile: {
        seedSql: TRIAGE_TASK_INSTANCES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["task_id", "retry_saves"], rows: [["extract_orders", 2]] },
      },
    },
    {
      id: "de-l8-retries-slas-alerting-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the silent success, meaning a green instance that wrote nothing while that same task normally writes plenty, as \`(run_id, task_id, rows_written, avg_rows_written)\`, ordered by \`run_id\`, over \`task_instances\`.

\`avg_rows_written\` is the mean \`rows_written\` across that task's successful instances, rounded to 1 decimal. Keep the instances that succeeded, wrote 0 rows, and belong to a task whose average is above 0.`,
      starterCode: `-- Green, and yet nothing was written. Compare each task to its own history.
WITH task_avg AS (
  -- per task: the mean rows_written across its successful instances
)
SELECT
FROM task_instances ti
JOIN task_avg a ON a.task_id = ti.task_id
;`,
      hints: [
        "The CTE is `SELECT task_id, AVG(rows_written) AS avg_rows FROM task_instances WHERE state = 'success' GROUP BY task_id`.",
        "The outer filter is `ti.state = 'success' AND ti.rows_written = 0 AND a.avg_rows > 0`.",
        "A task that legitimately writes nothing has an average of 0, which is why the `avg_rows > 0` condition is what keeps this from crying wolf.",
      ],
      referenceSolution: `WITH task_avg AS (
  SELECT task_id, AVG(rows_written) AS avg_rows
  FROM task_instances
  WHERE state = 'success'
  GROUP BY task_id
)
SELECT ti.run_id,
       ti.task_id,
       ti.rows_written,
       ROUND(a.avg_rows, 1) AS avg_rows_written
FROM task_instances ti
JOIN task_avg a ON a.task_id = ti.task_id
WHERE ti.state = 'success' AND ti.rows_written = 0 AND a.avg_rows > 0
ORDER BY ti.run_id;`,
      singleFile: {
        seedSql: TRIAGE_TASK_INSTANCES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["run_id", "task_id", "rows_written", "avg_rows_written"],
          rows: [["ds_2026_03_16", "load_facts", 0, 40334]],
        },
      },
    },
  ],
}

export const level8Module1: SqlModule = {
  id: "de-l8-orchestration-fundamentals",
  title: "Module 8.1: Orchestration Fundamentals",
  description:
    "What an orchestrator actually stores and why the order matters: runs bound to an immutable data interval, the task-instance lifecycle, the dependency edges that turn one failure into a blast radius, sensors that wait and time out, and the retry-versus-SLA-versus-silent-success split that decides what deserves a page. All read with SQL over a simulated scheduler metadata catalog.",
  lessons: [dagsAndTaskStates, dependenciesAndSensors, retriesSlasAlerting],
}
