/**
 * Data Engineering Level 8, Module 8.3 — Incremental Loads, Late Data & Backfills.
 *
 * The shipped SQL section already owns most of the incremental loop: `sql-l5-incremental-watermark-
 * backfill` ships the control table, the strict `>` boundary, the lookback, and the single-partition
 * overwrite, and `sql-l4-idempotent-merge` already explains why a strict high-water mark drops late
 * rows. So the loop itself is a short REVIEW here (8.3.1, whose one piece of new prose is the dual
 * cloud label: this exact shape is Azure Data Factory's signature watermark scenario and AWS Glue's
 * job bookmarks), and the module's real contributions are the three things no shipped lesson does:
 * the anti-join audit that QUANTIFIES silent loss before proposing a fix (8.3.2), the manifest-driven
 * multi-partition backfill and its downstream-aggregate trap (8.3.3), and the end-to-end daily
 * pipeline build plus the written design rehearsal for the stock "design a daily pipeline" question
 * (8.3.4).
 *
 * Devices: single-file SELECTs for the read-and-reason halves (which boundary, how much was lost,
 * how late), and the workspace script runner for every write, because the grader runs the learner's
 * script TWICE and that double run IS the idempotency lesson. Every workspace exercise names its
 * graded tables in `idempotencyTables`; the bare fallback sums row counts across all user tables,
 * which both misses a value-only drift (a watermark that keeps advancing) and fails the 8.3.4 build,
 * whose audit log grows one row per run on purpose.
 *
 * Binding platform note (docs/data-engineering-curriculum/RESEARCH.md §5.3): SQLite has no MERGE
 * keyword, so merge semantics are graded through `INSERT ... ON CONFLICT(key) DO UPDATE SET ...` or
 * delete-then-insert, and real `MERGE INTO` syntax appears in prose callouts only.
 *
 * Scaffolding fades across the module in BOTH exercise slots, not just one: apply hints run 4/3/2/2
 * and practice hints run 2/1/1/0, so by 8.3.4 the learner composes the whole pipeline from the
 * prompt alone. Where a teach body already prints the statements an apply needs, its hints carry the
 * decision (ordering, scoping, join form) rather than repeating the code.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and every
 * workspace reference was executed against its own assertions including the idempotency double run.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 8.3.1 seeds — a control table serving four pipelines at once.
// `etl_watermarks` is keyed by pipeline name, which is exactly the shape ADF's watermark control
// table and Glue's job bookmark store take: one row per pipeline, one stored last-loaded value.
// The orders row sits at '2026-03-13 22:00:00' and there is deliberately NO shipments row, because
// a first run has to create its own bookmark. `etl_run_params` holds the run's fixed "now" so no
// exercise ever calls a wall-clock function (the #1 pipeline anti-pattern, RESEARCH.md §5.2). It is
// deliberately NOT named `run_config`: 8.3.4 ships `run_config(pipeline, run_date)` as the canonical
// scheduler-parameter table, and one name must not mean two shapes inside one module.
// ---------------------------------------------------------------------------

const WATERMARK_CONTROL_SEED = `CREATE TABLE etl_watermarks (
  pipeline   TEXT PRIMARY KEY,  -- one control row per pipeline, so one table serves them all
  last_value TEXT               -- the newest source timestamp this pipeline has loaded
);
INSERT INTO etl_watermarks (pipeline, last_value) VALUES
  ('orders_incremental',    '2026-03-13 22:00:00'),
  ('customers_incremental', '2026-03-14 03:30:00'),
  ('events_incremental',    '2026-03-14 05:45:00'),
  ('invoices_incremental',  '2026-03-11 23:15:00');

CREATE TABLE etl_run_params (
  param_name  TEXT,
  param_value TEXT   -- the run's injected parameters; the pipeline never reads a wall clock
);
INSERT INTO etl_run_params (param_name, param_value) VALUES
  ('run_started_at', '2026-03-14 18:00:00');

CREATE TABLE source_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  amount_usd  REAL,
  updated_at  TEXT    -- the source's change timestamp; this is the watermark column
);
INSERT INTO source_orders (order_id, customer_id, amount_usd, updated_at) VALUES
  (5101, 301, 120.00, '2026-03-12 07:15:00'),
  (5102, 302,  75.50, '2026-03-12 11:40:00'),
  (5103, 303, 240.00, '2026-03-12 16:05:00'),
  (5104, 304,  59.90, '2026-03-12 20:55:00'),
  -- the two rows that sit inside a 1 day lookback and are already loaded
  (5105, 305, 310.25, '2026-03-13 20:35:00'),
  (5106, 306,  88.00, '2026-03-13 21:50:00'),
  -- strictly newer than the stored watermark: genuinely new work
  (5107, 307, 145.75, '2026-03-14 02:20:00'),
  (5108, 308,  62.40, '2026-03-14 05:35:00'),
  (5109, 309, 199.00, '2026-03-14 08:50:00'),
  (5110, 310, 130.00, '2026-03-14 12:05:00'),
  (5111, 311,  95.60, '2026-03-14 15:30:00'),
  (5112, 312, 275.00, '2026-03-14 17:25:00');

CREATE TABLE ods_orders (
  order_id    INTEGER PRIMARY KEY,
  customer_id INTEGER,
  amount_usd  REAL,
  updated_at  TEXT
);
INSERT INTO ods_orders (order_id, customer_id, amount_usd, updated_at) VALUES
  (5101, 301, 120.00, '2026-03-12 07:15:00'),
  (5102, 302,  75.50, '2026-03-12 11:40:00'),
  (5103, 303, 240.00, '2026-03-12 16:05:00'),
  (5104, 304,  59.90, '2026-03-12 20:55:00'),
  (5105, 305, 310.25, '2026-03-13 20:35:00'),
  (5106, 306,  88.00, '2026-03-13 21:50:00');`

const SHIPMENTS_INCREMENTAL_SEED = `${WATERMARK_CONTROL_SEED}

CREATE TABLE source_shipments (
  shipment_id INTEGER,
  order_id    INTEGER,
  carrier     TEXT,
  updated_at  TEXT
);
INSERT INTO source_shipments (shipment_id, order_id, carrier, updated_at) VALUES
  (9201, 5101, 'roadrunner', '2026-03-13 09:10:00'),
  (9202, 5102, 'blue-freight', '2026-03-13 13:25:00'),
  (9203, 5103, 'roadrunner', '2026-03-13 19:40:00'),
  (9204, 5104, 'northline',  '2026-03-14 04:15:00'),
  (9205, 5105, 'blue-freight', '2026-03-14 08:05:00'),
  (9206, 5106, 'roadrunner', '2026-03-14 13:50:00'),
  (9207, 5107, 'northline',  '2026-03-14 18:35:00');

CREATE TABLE ods_shipments (
  shipment_id INTEGER PRIMARY KEY,
  order_id    INTEGER,
  carrier     TEXT,
  updated_at  TEXT
);`

const watermarkControlTableReview: SqlLesson = {
  id: "de-l8-watermark-control-table-review",
  title: "Watermark Review: The Control Table as ADF Bookmark",
  summary:
    "Re-run the incremental loop you already know against a control table keyed by pipeline, and name the pattern in the two cloud vocabularies interviewers use.",
  estimatedMinutes: 18,
  difficulty: "easy",
  skills: [
    "high-water mark review",
    "multi-pipeline control table",
    "create-watermark-if-missing",
    "upsert as safety net",
    "ADF and Glue vocabulary",
    "date arithmetic",
  ],
  teach: {
    estimatedMinutes: 8,
    markdown: `## You have already built this

This is a review lesson and it says so up front. You wrote the whole incremental loop in \`sql-l5-incremental-watermark-backfill\`: read a stored value, pull only what is newer, upsert it, advance the value. This lesson restates the chain, adds two small production details, and then spends its remaining minutes on the one thing that is genuinely new, which is what the pattern is called in each cloud.

The causal chain, one sentence per link:

1. **Filter by \`> watermark\`.** Around 80 percent of incremental loads are exactly this: keep the last-loaded timestamp, pull only source rows newer than it.
2. **Add an overlap margin.** A transaction that was in flight when the last run read the source commits afterwards but carries an earlier timestamp, so a strict boundary steps right over it. Subtracting a lookback from the stored value is what catches those rows.
3. **The overlap creates duplicates.** Anything inside the lookback window gets read a second time, by design.
4. **So the sink must merge.** Because step 3 re-reads rows you already have, the write has to be an upsert on the business key (or a partition replacement). An append here doubles rows on every run.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "read control row", "note": "SELECT last_value WHERE pipeline = ..." },
    { "label": "filter source", "note": "updated_at > last_value minus lookback" },
    { "label": "upsert sink", "note": "ON CONFLICT(key) DO UPDATE" },
    { "label": "advance control row", "note": "store the newest value loaded" }
  ],
  "highlight": ["upsert sink"],
  "caption": "The incremental loop. The overlap in step 2 is what forces the merge in step 3, which is why the highlighted step is not optional."
}
\`\`\`

## The two production details

**The control table is keyed by pipeline, not by table.** One \`etl_watermarks(pipeline, last_value)\` table serves every loader on the platform, one row each. That means a brand new pipeline has **no row at all** on its first run, so a correct loader creates its bookmark before it reads it. A loader that assumes the row exists works fine for a year and then fails the first time someone adds a pipeline.

**The double-run contract now covers the control row too.** When this course grades a script by running it twice, it compares the contents of the tables you name. For an incremental load you must name both the sink and the control table, because a watermark that advances a second time is a value change with no row-count change, and a row-count comparison cannot see it.

## Two clouds, one pattern

This is the piece worth memorizing. The shape you just reviewed is not a course invention:

- **Azure Data Factory** calls it the watermark pattern: a watermark column in the source, a control table holding the last-loaded value, a filtered source query, and an upsert for changed rows. Across every published ADF question bank it is the single most-repeated interview scenario.
- **AWS Glue** calls the same idea **job bookmarks**: Glue stores the high-water mark for you between runs instead of making you keep the table.
- **dbt** spells the overlap margin \`lookback\` on an incremental model.

**Common mistake:** advancing the watermark to the run's clock time instead of to the newest value actually loaded. If the load fails halfway, the clock still moved and everything in the gap is lost forever. Advance to \`MAX(updated_at)\` of what landed in the sink.

**Interview nuance:** recite the chain end to end (watermark, overlap, duplicates, idempotent merge) and then name it in whichever vocabulary the interviewer opened with. Saying "this is the watermark control table, which is what Glue automates as a job bookmark" in an ADF interview, or the reverse, is the sentence that reads as platform experience rather than tutorial recall.

> **On a real platform this differs.** The control table lives in a metadata database, not next to your data, and the loader writes it inside the same transaction that commits the load so a crash cannot leave the bookmark ahead of the data. ADF stores it in a SQL Database and updates it with a stored procedure activity; Glue stores it in the job's own bookmark state and you never see the table.`,
    demoSeedSql: WATERMARK_CONTROL_SEED,
    demoCode: `-- One control row per pipeline. The orders loader reads its own row, then every source
-- row falls into one of three buckets against the strict boundary and the 1 day lookback.
SELECT o.order_id, o.updated_at,
       CASE
         WHEN o.updated_at > w.last_value THEN 'new (strictly after the watermark)'
         WHEN o.updated_at > datetime(w.last_value, '-1 day') THEN 're-read (inside the lookback)'
         ELSE 'skipped (older than the lookback)'
       END AS load_decision
FROM source_orders o
CROSS JOIN etl_watermarks w
WHERE w.pipeline = 'orders_incremental'
ORDER BY o.updated_at;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l8-watermark-control-table-review-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the rows the next \`orders_incremental\` run will load given the stored watermark and a 1 day lookback, as \`(order_id, updated_at, already_in_target)\`, oldest first, over \`source_orders\`, \`etl_watermarks\`, and \`ods_orders\`.

A row is in scope when its \`updated_at\` is strictly greater than the pipeline's \`last_value\` minus one day. Set \`already_in_target\` to \`1\` when that \`order_id\` is already in \`ods_orders\` and \`0\` when it is not, so the overlap is visible. Alias the columns exactly \`order_id\`, \`updated_at\`, and \`already_in_target\`.`,
    starterCode: `-- The next run's input slice: everything newer than (watermark minus 1 day).
SELECT
  -- order_id, updated_at, and whether ods_orders already holds this key
FROM source_orders o
ORDER BY o.updated_at;`,
    hints: [
      "Read the boundary once with a scalar subquery: `(SELECT last_value FROM etl_watermarks WHERE pipeline = 'orders_incremental')`.",
      "`datetime(last_value, '-1 day')` shifts the boundary back by the lookback, and the filter stays a strict `>`.",
      "`CASE WHEN EXISTS (SELECT 1 FROM ods_orders t WHERE t.order_id = o.order_id) THEN 1 ELSE 0 END AS already_in_target` marks the overlap rows.",
      "Order by `updated_at` so the two overlap rows appear first.",
    ],
    referenceSolution: `SELECT o.order_id,
       o.updated_at,
       CASE WHEN EXISTS (SELECT 1 FROM ods_orders t WHERE t.order_id = o.order_id)
            THEN 1 ELSE 0 END AS already_in_target
FROM source_orders o
WHERE o.updated_at > datetime(
        (SELECT last_value FROM etl_watermarks WHERE pipeline = 'orders_incremental'),
        '-1 day')
ORDER BY o.updated_at;`,
    singleFile: {
      seedSql: WATERMARK_CONTROL_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["order_id", "updated_at", "already_in_target"],
        rows: [
          [5105, "2026-03-13 20:35:00", 1],
          [5106, "2026-03-13 21:50:00", 1],
          [5107, "2026-03-14 02:20:00", 0],
          [5108, "2026-03-14 05:35:00", 0],
          [5109, "2026-03-14 08:50:00", 0],
          [5110, "2026-03-14 12:05:00", 0],
          [5111, "2026-03-14 15:30:00", 0],
          [5112, "2026-03-14 17:25:00", 0],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l8-watermark-control-table-review-practice",
    prompt: `Write a script that runs the incremental load for \`source_shipments\` into \`ods_shipments\` keyed on \`shipment_id\`, creating the \`shipments_incremental\` watermark row if it is missing, and changes nothing when it is rerun.

\`etl_watermarks(pipeline, last_value)\` already serves four other pipelines and has no \`shipments_incremental\` row yet, so create one before you read it. Load the source rows strictly newer than that stored value, upsert them into \`ods_shipments\`, then advance the row to the newest \`updated_at\` now in \`ods_shipments\`. The grader runs your script twice and compares the contents of both \`ods_shipments\` and \`etl_watermarks\`, so the watermark must not drift on the second run.`,
    starterCode: `-- Step 1: create the shipments_incremental control row only if it does not exist yet.

-- Step 2: load source_shipments rows newer than that watermark, upserting on shipment_id.

-- Step 3: advance the control row to the newest updated_at now in ods_shipments.
`,
    hints: [
      "`INSERT INTO etl_watermarks (pipeline, last_value) SELECT 'shipments_incremental', '1970-01-01 00:00:00' WHERE NOT EXISTS (SELECT 1 FROM etl_watermarks WHERE pipeline = 'shipments_incremental');` creates the bookmark once and is a no-op on every later run.",
      "The load is `INSERT INTO ods_shipments (...) SELECT ... FROM source_shipments WHERE updated_at > (SELECT last_value FROM etl_watermarks WHERE pipeline = 'shipments_incremental') ON CONFLICT(shipment_id) DO UPDATE SET ...` where `excluded` holds the incoming row, and the last statement is `UPDATE etl_watermarks SET last_value = (SELECT MAX(updated_at) FROM ods_shipments) WHERE pipeline = 'shipments_incremental'`, guarded so an empty sink cannot write a NULL over the bookmark.",
    ],
    seedSql: SHIPMENTS_INCREMENTAL_SEED,
    checkIdempotency: true,
    idempotencyTables: ["ods_shipments", "etl_watermarks"],
    assertions: [
      {
        suite: "load",
        name: "ods_shipments holds exactly the source rows",
        sql: `SELECT shipment_id FROM (
  SELECT shipment_id, order_id, carrier, updated_at FROM source_shipments
  EXCEPT
  SELECT shipment_id, order_id, carrier, updated_at FROM ods_shipments
)
UNION ALL
SELECT shipment_id FROM (
  SELECT shipment_id, order_id, carrier, updated_at FROM ods_shipments
  EXCEPT
  SELECT shipment_id, order_id, carrier, updated_at FROM source_shipments
)`,
      },
      {
        suite: "grain",
        name: "one row per shipment_id",
        sql: `SELECT shipment_id FROM ods_shipments GROUP BY shipment_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "control",
        name: "the shipments_incremental control row was created",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM etl_watermarks WHERE pipeline = 'shipments_incremental') <> 1`,
      },
      {
        suite: "control",
        name: "the watermark equals the newest loaded updated_at",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT last_value FROM etl_watermarks WHERE pipeline = 'shipments_incremental')
  <> (SELECT MAX(updated_at) FROM source_shipments)`,
      },
      {
        suite: "control",
        name: "the other pipelines' control rows were left alone",
        isHidden: true,
        sql: `WITH untouched(pipeline, last_value) AS (
  VALUES ('orders_incremental',    '2026-03-13 22:00:00'),
         ('customers_incremental', '2026-03-14 03:30:00'),
         ('events_incremental',    '2026-03-14 05:45:00'),
         ('invoices_incremental',  '2026-03-11 23:15:00')
)
SELECT u.pipeline FROM untouched u
LEFT JOIN etl_watermarks w ON w.pipeline = u.pipeline
WHERE w.last_value IS NULL OR w.last_value <> u.last_value`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-watermark-control-table-review-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns every pipeline's watermark age in whole hours measured against the fixed run timestamp in \`etl_run_params\`, as \`(pipeline, watermark_age_hours)\`, oldest watermark first, over \`etl_watermarks\` and \`etl_run_params\`.

The run timestamp is the \`etl_run_params\` row whose \`param_name\` is \`'run_started_at'\`. Alias the computed column exactly \`watermark_age_hours\` and truncate it to whole hours.`,
      starterCode: `-- How stale is each pipeline's bookmark, measured against the run's injected "now"?
SELECT
FROM etl_watermarks w
ORDER BY watermark_age_hours DESC;`,
      hints: [
        "`strftime('%s', ts)` gives seconds since the epoch, which subtracts cleanly with no floating point drift.",
        "Whole hours is `(CAST(strftime('%s', now) AS INTEGER) - CAST(strftime('%s', w.last_value) AS INTEGER)) / 3600`, and SQLite's integer division truncates for you.",
        "Pull the run timestamp with `(SELECT param_value FROM etl_run_params WHERE param_name = 'run_started_at')`.",
      ],
      referenceSolution: `SELECT w.pipeline,
       (CAST(strftime('%s', (SELECT param_value FROM etl_run_params WHERE param_name = 'run_started_at')) AS INTEGER)
        - CAST(strftime('%s', w.last_value) AS INTEGER)) / 3600 AS watermark_age_hours
FROM etl_watermarks w
ORDER BY watermark_age_hours DESC;`,
      singleFile: {
        seedSql: WATERMARK_CONTROL_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["pipeline", "watermark_age_hours"],
          rows: [
            ["invoices_incremental", 66],
            ["orders_incremental", 20],
            ["customers_incremental", 14],
            ["events_incremental", 12],
          ],
        },
      },
    },
    {
      id: "de-l8-watermark-control-table-review-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the \`source_orders\` rows the 1 day lookback will load for a second time, as \`(order_id, updated_at)\`, oldest first, over \`source_orders\`, \`etl_watermarks\`, and \`ods_orders\`.

A row loads twice when it sits inside the lookback window (newer than the \`orders_incremental\` \`last_value\` minus one day, but not newer than \`last_value\` itself) and \`ods_orders\` already holds its \`order_id\`. These rows are why the sink has to merge.`,
      starterCode: `-- The overlap: rows the lookback re-reads that the target already holds.
SELECT
FROM source_orders o
ORDER BY o.updated_at;`,
      hints: [
        "The window is bounded on both sides: `updated_at > datetime(last_value, '-1 day') AND updated_at <= last_value`.",
        "Add `AND EXISTS (SELECT 1 FROM ods_orders t WHERE t.order_id = o.order_id)` to keep only the rows already loaded.",
      ],
      referenceSolution: `SELECT o.order_id, o.updated_at
FROM source_orders o
WHERE o.updated_at > datetime(
        (SELECT last_value FROM etl_watermarks WHERE pipeline = 'orders_incremental'), '-1 day')
  AND o.updated_at <= (SELECT last_value FROM etl_watermarks WHERE pipeline = 'orders_incremental')
  AND EXISTS (SELECT 1 FROM ods_orders t WHERE t.order_id = o.order_id)
ORDER BY o.updated_at;`,
      singleFile: {
        seedSql: WATERMARK_CONTROL_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["order_id", "updated_at"],
          rows: [
            [5105, "2026-03-13 20:35:00"],
            [5106, "2026-03-13 21:50:00"],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.3.2 seeds — the post-incident state an on-call DE walks into.
// `source_events` carries BOTH clocks: `event_ts` (when it happened) and `ingested_at` (when the
// row became visible to the loader). Three rows have an `event_ts` at or below the watermark and an
// `ingested_at` above it, which is exactly the shape a strict boundary drops with no error. One more
// row (9007) is late but still arrived before the watermark, so it was loaded: late is not the same
// as lost, and the drills make the learner separate the two.
// `fct_events` was loaded strictly, so it is missing the three late rows, and `fct_daily_totals` is
// the aggregate that silently inherited the gap.
// `source_events` has a retention window and the fact does not, so event 9000 on 2026-03-10 exists
// ONLY in `fct_events`. That is the realistic shape, and it is also what makes the practice's bound
// gradeable: an unbounded "rebuild the whole fact from source" answer destroys 2026-03-10, while a
// correctly bounded 3 day window never touches it.
// ---------------------------------------------------------------------------

const LATE_DATA_SEED = `CREATE TABLE etl_watermarks (
  pipeline   TEXT PRIMARY KEY,
  last_value TEXT
);
INSERT INTO etl_watermarks (pipeline, last_value) VALUES
  ('events_incremental', '2026-03-14 06:00:00');

CREATE TABLE source_events (
  event_id    INTEGER,
  event_ts    TEXT,     -- event time: when the thing actually happened
  ingested_at TEXT,     -- processing time: when the loader could first see the row
  user_id     INTEGER,
  amount_usd  REAL
);
INSERT INTO source_events (event_id, event_ts, ingested_at, user_id, amount_usd) VALUES
  (9001, '2026-03-11 08:10:00', '2026-03-11 08:12:00', 501,  42.00),
  (9002, '2026-03-11 19:40:00', '2026-03-11 19:43:00', 502,  88.50),
  (9003, '2026-03-12 07:25:00', '2026-03-12 07:28:00', 503, 120.00),
  (9004, '2026-03-12 13:50:00', '2026-03-12 13:52:00', 504,  65.25),
  -- late AND lost: happened on the 12th, arrived after the watermark had moved past it
  (9005, '2026-03-12 22:15:00', '2026-03-14 07:40:00', 505, 149.00),
  (9006, '2026-03-13 06:30:00', '2026-03-13 06:33:00', 506, 210.75),
  -- late but NOT lost: three hours behind, still inside the window the loader read
  (9007, '2026-03-13 11:05:00', '2026-03-13 14:05:00', 507,  33.40),
  (9008, '2026-03-13 18:20:00', '2026-03-13 18:24:00', 508,  97.60),
  (9009, '2026-03-13 23:45:00', '2026-03-14 09:15:00', 509, 175.20),
  (9010, '2026-03-14 01:10:00', '2026-03-14 01:14:00', 510,  58.00),
  (9011, '2026-03-14 03:55:00', '2026-03-14 03:58:00', 511, 143.30),
  (9012, '2026-03-14 05:20:00', '2026-03-14 11:50:00', 512,  82.90),
  -- not late, simply not yet due: event time is above the watermark
  (9013, '2026-03-14 09:35:00', '2026-03-14 09:38:00', 513,  66.45),
  (9014, '2026-03-14 14:00:00', '2026-03-14 14:05:00', 514, 191.80);

CREATE TABLE fct_events (
  event_id   INTEGER PRIMARY KEY,
  dt         TEXT,   -- the event-time date this row is partitioned under
  event_ts   TEXT,
  user_id    INTEGER,
  amount_usd REAL
);
INSERT INTO fct_events (event_id, dt, event_ts, user_id, amount_usd) VALUES
  -- older than the source's retention window: this partition exists only here now
  (9000, '2026-03-10', '2026-03-10 12:00:00', 500,  55.00),
  (9001, '2026-03-11', '2026-03-11 08:10:00', 501,  42.00),
  (9002, '2026-03-11', '2026-03-11 19:40:00', 502,  88.50),
  (9003, '2026-03-12', '2026-03-12 07:25:00', 503, 120.00),
  (9004, '2026-03-12', '2026-03-12 13:50:00', 504,  65.25),
  (9006, '2026-03-13', '2026-03-13 06:30:00', 506, 210.75),
  (9007, '2026-03-13', '2026-03-13 11:05:00', 507,  33.40),
  (9008, '2026-03-13', '2026-03-13 18:20:00', 508,  97.60),
  (9010, '2026-03-14', '2026-03-14 01:10:00', 510,  58.00),
  (9011, '2026-03-14', '2026-03-14 03:55:00', 511, 143.30);

CREATE TABLE fct_daily_totals (
  dt          TEXT PRIMARY KEY,
  events      INTEGER,
  revenue_usd REAL
);
INSERT INTO fct_daily_totals (dt, events, revenue_usd) VALUES
  ('2026-03-10', 1,  55.00),
  ('2026-03-11', 2, 130.50),
  ('2026-03-12', 2, 185.25),
  ('2026-03-13', 3, 341.75),
  ('2026-03-14', 2, 201.30);`

const lateDataAudit: SqlLesson = {
  id: "de-l8-late-data-audit",
  title: "Late Data: Quantify the Silent Loss, Then Heal It",
  summary:
    "Measure how many rows a strict watermark load dropped without raising an error, then heal it with a rolling reprocessing window.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "late-arriving data",
    "event time vs processing time",
    "silent data loss",
    "anti-join auditing",
    "lateness distribution",
    "rolling window recompute",
    "NOT EXISTS",
  ],
  // Map deviation: the map asked for a csdiagram TIMELINE of event_ts vs ingested_at with the
  // dropped row highlighted. This ships a `table` instead because the lesson's whole point is
  // comparing TWO clocks per row against a third value (the watermark), and three values per row
  // read as columns, not as positions on one axis. The dropped rows are still the highlight, via
  // `highlightCols` on the arrival and outcome columns.
  teach: {
    estimatedMinutes: 12,
    markdown: `## This lesson is not about the fix

You already know the fix. \`sql-l4-idempotent-merge\` told you a strict high-water mark drops late rows and that a lookback catches them, and the previous lesson restated it. What no lesson has made you do is the part an on-call engineer actually gets paged for: **finding the damage and putting a number on it**. An unquantified fix is a guess, and a guess is not something you write in an incident report.

## Two clocks, and only one of them is yours

Every event row carries two timestamps and they are not the same thing.

- **Event time** is when the thing happened. A payment at 02:00 has an event time of 02:00 forever.
- **Processing time** is when your loader could first see the row. That is a property of the network, the queue, the mobile client that was offline, and the source system's commit order.

Event time versus processing time is the single most transferable idea in streaming, and it bites batch first. Here is the whole failure in one line: a row **events** at 22:15 on the 12th and **arrives** at 07:40 on the 14th, by which point the 06:00 load has already advanced the watermark past it. The next run filters on \`event_ts > watermark\`, the row is below the boundary, and it is skipped. Forever. No error, no retry, no alert. The run is green.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["event_id", "event_ts (happened)", "ingested_at (arrived)", "vs watermark 06:00 on the 14th", "in fct_events?"],
  "rows": [
    ["9004", "12th 13:50", "12th 13:52", "arrived long before", "yes"],
    ["9005", "12th 22:15", "14th 07:40", "arrived AFTER, event time below", "no, silently dropped"],
    ["9007", "13th 11:05", "13th 14:05", "3h late, still arrived before", "yes"],
    ["9009", "13th 23:45", "14th 09:15", "arrived AFTER, event time below", "no, silently dropped"],
    ["9012", "14th 05:20", "14th 11:50", "arrived AFTER, event time below", "no, silently dropped"],
    ["9013", "14th 09:35", "14th 09:38", "event time above, not yet due", "no, correctly"]
  ],
  "highlightCols": ["ingested_at (arrived)", "in fct_events?"],
  "caption": "Late is not the same as lost. 9007 was three hours late and still made it. 9005, 9009 and 9012 all crossed the watermark while in flight, and nothing raised an error."
}
\`\`\`

Read that last column carefully. Row 9013 is also missing from the fact, and that is **correct**: its event time is above the watermark, so the next run will pick it up. Only rows whose event time is at or below the watermark and that never landed are losses. Your audit has to make that distinction or it will report a number that is not real.

## The audit is an anti-join

The query is small and you should be able to write it from memory:

\`\`\`sql
SELECT e.event_id, e.event_ts, e.ingested_at
FROM source_events e
WHERE e.event_ts <= (SELECT last_value FROM etl_watermarks WHERE pipeline = 'events_incremental')
  AND NOT EXISTS (SELECT 1 FROM fct_events f WHERE f.event_id = e.event_id)
\`\`\`

Below the boundary, absent from the target. That count, and the revenue attached to it, is the number that goes in the write-up. Add the arrival delay per row and you also get the input for the next decision: how wide the healing window has to be.

## Then heal it with a rolling window

The production fix is a **bounded rolling reprocessing window**: every run rebuilds the last few days (three is a common default) from source instead of only the slice above the watermark. Late arrivals then self-heal on the next run, because the day they belong to is rebuilt anyway.

That only works because the write is idempotent. Reprocessing the same three days every single run would triple your data with an append; with partition replacement (delete the day, reinsert the day) it converges to the same rows no matter how many times it runs. Module 8.2 is the prerequisite for this lesson, and this is where you cash it in.

Two things a strong answer adds. First, the window is **bounded**: three days, not the whole table, because cost is a design constraint and an unbounded recompute is how a nightly job becomes a six hour job. Second, the downstream aggregate has to be rebuilt in the same script, because a repaired fact under a stale total is still a wrong dashboard.

**Common mistake:** counting every row missing from the target as a loss. Rows whose event time is above the watermark are not lost, they are simply not due yet, and including them inflates the incident number and destroys your credibility in the review.

**Interview nuance:** "how do you handle late-arriving data" is a stock question, and almost every candidate jumps straight to "I would add a lookback window." The stronger answer is two steps: first quantify what was already lost with an anti-join below the watermark, then size the window from the observed arrival delays rather than picking three days because it sounds right. Naming the measurement before the remedy is the difference between an engineer and someone reciting a pattern.

> **On a real platform this differs.** Streaming engines make this tradeoff explicit rather than accidental, but not to the same degree. Flink states it fully with a **watermark plus an allowed lateness**, and events past the allowance can be routed to a side output instead of vanishing. Spark Structured Streaming gives you only the watermark delay threshold in \`withWatermark\`, and anything later than that threshold is dropped with no error and no side channel, which is much closer to the batch failure you just audited. Batch has the same tradeoff with none of the instrumentation, which is why you have to build the audit yourself.`,
    demoSeedSql: LATE_DATA_SEED,
    demoCode: `-- The two clocks side by side, and what the strict watermark did with each row.
SELECT e.event_id, e.event_ts, e.ingested_at,
       CASE
         WHEN e.event_ts > (SELECT last_value FROM etl_watermarks WHERE pipeline = 'events_incremental')
           THEN 'not due yet (event time above the watermark)'
         WHEN EXISTS (SELECT 1 FROM fct_events f WHERE f.event_id = e.event_id)
           THEN 'loaded'
         ELSE 'SILENTLY DROPPED (arrived after the watermark moved)'
       END AS load_outcome
FROM source_events e
ORDER BY e.event_ts;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l8-late-data-audit-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the rows the strict watermark load silently dropped, as \`(event_id, event_ts, ingested_at, minutes_late)\`, oldest event first, over \`source_events\`, \`etl_watermarks\`, and \`fct_events\`.

A row was dropped when its \`event_ts\` is at or below the \`events_incremental\` \`last_value\` and no row with that \`event_id\` exists in \`fct_events\`. Rows whose \`event_ts\` is above the watermark are not losses, they are simply not due yet, so leave them out. Report \`minutes_late\` as the whole minutes between \`event_ts\` and \`ingested_at\`, and alias the columns exactly.`,
    starterCode: `-- The silent loss: below the watermark, absent from the target.
SELECT
FROM source_events e
ORDER BY e.event_ts;`,
    hints: [
      "The boundary is `e.event_ts <= (SELECT last_value FROM etl_watermarks WHERE pipeline = 'events_incremental')`, and the `<=` matters because a row exactly on the boundary was also in scope for the load.",
      "The anti-join is `NOT EXISTS (SELECT 1 FROM fct_events f WHERE f.event_id = e.event_id)`.",
      "Arrival delay in whole minutes is `(CAST(strftime('%s', e.ingested_at) AS INTEGER) - CAST(strftime('%s', e.event_ts) AS INTEGER)) / 60`.",
    ],
    referenceSolution: `SELECT e.event_id,
       e.event_ts,
       e.ingested_at,
       (CAST(strftime('%s', e.ingested_at) AS INTEGER)
        - CAST(strftime('%s', e.event_ts) AS INTEGER)) / 60 AS minutes_late
FROM source_events e
WHERE e.event_ts <= (SELECT last_value FROM etl_watermarks WHERE pipeline = 'events_incremental')
  AND NOT EXISTS (SELECT 1 FROM fct_events f WHERE f.event_id = e.event_id)
ORDER BY e.event_ts;`,
    singleFile: {
      seedSql: LATE_DATA_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["event_id", "event_ts", "ingested_at", "minutes_late"],
        rows: [
          [9005, "2026-03-12 22:15:00", "2026-03-14 07:40:00", 2005],
          [9009, "2026-03-13 23:45:00", "2026-03-14 09:15:00", 570],
          [9012, "2026-03-14 05:20:00", "2026-03-14 11:50:00", 390],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l8-late-data-audit-practice",
    prompt: `Write a script that repairs \`fct_events\` and \`fct_daily_totals\` by reprocessing the last 3 days from \`source_events\` with partition replacement, healing the late rows, and that is safe to rerun.

The window is the watermark's date and the two days before it, so \`dt >= date(last_value, '-2 days')\` for the \`events_incremental\` row. Replace those partitions of \`fct_events(event_id, dt, event_ts, user_id, amount_usd)\` from \`source_events\`, partitioning on the event-time date, then rebuild \`fct_daily_totals(dt, events, revenue_usd)\` for the same window from the repaired fact. Days outside the window must be left exactly as they are, and that is not a formality: \`source_events\` has a retention window and the fact does not, so an older partition the source can no longer reproduce is sitting in \`fct_events\` and a rebuild that is not bounded will delete it. The grader runs your script twice and compares the contents of both tables.`,
    starterCode: `-- Rolling 3 day reprocess. The window is derived from the stored watermark, never from a clock.
-- Step 1: replace the fct_events partitions inside the window from source_events.

-- Step 2: rebuild fct_daily_totals for the same window from the repaired fct_events.
`,
    hints: [
      "Compute the window boundary once as `date((SELECT last_value FROM etl_watermarks WHERE pipeline = 'events_incremental'), '-2 days')`, then delete and reinsert every partition at or above it in both tables; the delete before the insert is what makes the second run a no-op instead of a doubling.",
    ],
    seedSql: LATE_DATA_SEED,
    checkIdempotency: true,
    idempotencyTables: ["fct_events", "fct_daily_totals"],
    assertions: [
      {
        suite: "heal",
        name: "the three dropped events are now in the fact",
        sql: `WITH late(event_id) AS (VALUES (9005), (9009), (9012))
SELECT event_id FROM late WHERE event_id NOT IN (SELECT event_id FROM fct_events)`,
      },
      {
        suite: "grain",
        name: "one row per event_id",
        sql: `SELECT event_id FROM fct_events GROUP BY event_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "window",
        name: "the reprocessed window matches source_events exactly",
        sql: `SELECT event_id FROM (
  SELECT event_id, date(event_ts) AS dt, event_ts, user_id, amount_usd
  FROM source_events WHERE date(event_ts) >= '2026-03-12'
  EXCEPT
  SELECT event_id, dt, event_ts, user_id, amount_usd
  FROM fct_events WHERE dt >= '2026-03-12'
)
UNION ALL
SELECT event_id FROM (
  SELECT event_id, dt, event_ts, user_id, amount_usd
  FROM fct_events WHERE dt >= '2026-03-12'
  EXCEPT
  SELECT event_id, date(event_ts) AS dt, event_ts, user_id, amount_usd
  FROM source_events WHERE date(event_ts) >= '2026-03-12'
)`,
      },
      {
        suite: "window",
        name: "the 2026-03-10 partition the source no longer holds still exists",
        isHidden: true,
        sql: `WITH retained(event_id, dt, event_ts, user_id, amount_usd) AS (
  VALUES (9000, '2026-03-10', '2026-03-10 12:00:00', 500, 55.00)
)
SELECT * FROM (SELECT event_id, dt, event_ts, user_id, amount_usd FROM fct_events WHERE dt = '2026-03-10' EXCEPT SELECT * FROM retained)
UNION ALL
SELECT * FROM (SELECT * FROM retained EXCEPT SELECT event_id, dt, event_ts, user_id, amount_usd FROM fct_events WHERE dt = '2026-03-10')`,
      },
      {
        suite: "window",
        name: "the days before the window were left untouched",
        isHidden: true,
        sql: `WITH untouched(event_id, dt, event_ts, user_id, amount_usd) AS (
  VALUES (9000, '2026-03-10', '2026-03-10 12:00:00', 500, 55.00),
         (9001, '2026-03-11', '2026-03-11 08:10:00', 501, 42.00),
         (9002, '2026-03-11', '2026-03-11 19:40:00', 502, 88.50)
)
SELECT * FROM (SELECT event_id, dt, event_ts, user_id, amount_usd FROM fct_events WHERE dt < '2026-03-12' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT event_id, dt, event_ts, user_id, amount_usd FROM fct_events WHERE dt < '2026-03-12')`,
      },
      {
        suite: "downstream",
        name: "every daily total agrees with the repaired fact",
        isHidden: true,
        sql: `SELECT t.dt FROM fct_daily_totals t
LEFT JOIN (
  SELECT dt, COUNT(*) AS events, SUM(amount_usd) AS revenue_usd FROM fct_events GROUP BY dt
) f ON f.dt = t.dt
WHERE f.dt IS NULL OR f.events <> t.events OR ROUND(f.revenue_usd, 2) <> ROUND(t.revenue_usd, 2)`,
      },
      {
        suite: "downstream",
        name: "the aggregate covers every day the fact holds",
        isHidden: true,
        sql: `SELECT DISTINCT dt FROM fct_events WHERE dt NOT IN (SELECT dt FROM fct_daily_totals)`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-late-data-audit-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns how many late rows landed on each event-time day, as \`(dt, late_rows)\`, oldest day first, over \`source_events\`.

A row is late when its \`ingested_at\` is more than 2 hours after its \`event_ts\`, whether or not the load caught it. Group by the event-time date, alias the columns exactly \`dt\` and \`late_rows\`, and return only days that have at least one late row.`,
      starterCode: `-- Lateness by event-time day. Note that late does not mean lost.
SELECT
FROM source_events
GROUP BY dt
ORDER BY dt;`,
      hints: [
        "`date(event_ts)` is the event-time day, and it is what the fact is partitioned on.",
        "More than two hours late is `ingested_at > datetime(event_ts, '+2 hours')`.",
        "Filter in the `WHERE` clause so the days with no late rows never form a group at all.",
      ],
      referenceSolution: `SELECT date(event_ts) AS dt, COUNT(*) AS late_rows
FROM source_events
WHERE ingested_at > datetime(event_ts, '+2 hours')
GROUP BY dt
ORDER BY dt;`,
      singleFile: {
        seedSql: LATE_DATA_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dt", "late_rows"],
          rows: [
            ["2026-03-12", 1],
            ["2026-03-13", 2],
            ["2026-03-14", 1],
          ],
        },
      },
    },
    {
      id: "de-l8-late-data-audit-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the arrival-delay distribution per event-time day, as \`(dt, max_delay_minutes, avg_delay_minutes)\`, worst maximum delay first, over \`source_events\`.

The delay of a row is the whole minutes between \`event_ts\` and \`ingested_at\`. Report the maximum and the average of that delay for every day, rounding the average to one decimal place. This is the query that sizes the reprocessing window: the window has to be wider than the delays you actually observe.`,
      starterCode: `-- Sizing the lookback: how far behind does this source really run?
SELECT
FROM source_events
GROUP BY dt
ORDER BY max_delay_minutes DESC;`,
      hints: [
        "Compute the per-row delay once with `(CAST(strftime('%s', ingested_at) AS INTEGER) - CAST(strftime('%s', event_ts) AS INTEGER)) / 60`, most readably inside a CTE.",
        "Then aggregate that column with `MAX(...)` and `ROUND(AVG(...), 1)`.",
        "Group by `date(event_ts)`, not by `date(ingested_at)`, because the partition you would rebuild is an event-time partition.",
      ],
      referenceSolution: `WITH delays AS (
  SELECT date(event_ts) AS dt,
         (CAST(strftime('%s', ingested_at) AS INTEGER)
          - CAST(strftime('%s', event_ts) AS INTEGER)) / 60 AS delay_minutes
  FROM source_events
)
SELECT dt,
       MAX(delay_minutes) AS max_delay_minutes,
       ROUND(AVG(delay_minutes), 1) AS avg_delay_minutes
FROM delays
GROUP BY dt
ORDER BY max_delay_minutes DESC;`,
      singleFile: {
        seedSql: LATE_DATA_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dt", "max_delay_minutes", "avg_delay_minutes"],
          rows: [
            ["2026-03-12", 2005, 670],
            ["2026-03-13", 570, 189.3],
            ["2026-03-14", 390, 81],
            ["2026-03-11", 3, 2.5],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.3.3 seeds — a scheduler-issued backfill over a partitioned fact and its downstream mart.
// The bug: the transformation excluded refunds (the negative `amount_usd` rows), so `fct_daily_sales`
// overstates revenue on every date that had one. `backfill_manifest` holds the DEPLOY window
// (2026-02-08 through 2026-02-12), not the dates that actually broke, which is how a real incident
// ticket is written: you rerun the window the bad code was live, and two of those dates turn out to
// have been fine all along. 2026-02-08 is a Sunday, so the manifest also straddles two ISO weeks,
// which is what makes the downstream week recompute non-trivial.
// Two deliberate traps for graders: 2026-02-05 exists only in the fact (raw retention has aged it
// out), so an unbounded rebuild destroys it; and 2026-02-09 has a refund yet is already correct
// (hand-repaired during the incident), so "this date had a refund" is NOT a valid stand-in for
// "this date disagrees with raw", which is what drill 3 grades.
// ---------------------------------------------------------------------------

const BACKFILL_SEED = `CREATE TABLE raw_sales (
  sale_id    INTEGER,
  dt         TEXT,     -- the sale's date partition
  store_id   INTEGER,
  amount_usd REAL      -- negative on a refund, which is exactly what the buggy job excluded
);
INSERT INTO raw_sales (sale_id, dt, store_id, amount_usd) VALUES
  (7001, '2026-02-08', 1, 120.00),
  (7002, '2026-02-08', 2,  95.50),
  (7003, '2026-02-09', 1, 210.00),
  (7004, '2026-02-09', 2,  64.25),
  -- 02-09 also had a refund, but the on-call engineer already reran that date by hand during the
  -- incident, so the fact below is ALREADY net of it. "has a refund" and "the fact is wrong" are
  -- deliberately not the same set of dates.
  (7019, '2026-02-09', 2, -18.75),
  (7005, '2026-02-10', 1, 180.00),
  (7006, '2026-02-10', 2, 140.00),
  (7007, '2026-02-10', 1, -45.00),
  (7008, '2026-02-11', 1, 260.50),
  (7009, '2026-02-11', 2,  88.00),
  (7010, '2026-02-11', 2, -30.25),
  (7011, '2026-02-12', 1, 150.00),
  (7012, '2026-02-12', 2, 175.75),
  (7013, '2026-02-12', 1, -60.00),
  (7014, '2026-02-13', 1, 199.00),
  (7015, '2026-02-13', 2, 120.40),
  (7016, '2026-02-14', 1, 310.00),
  (7017, '2026-02-14', 2,  45.60),
  (7018, '2026-02-14', 1,  78.25);

CREATE TABLE fct_daily_sales (
  dt          TEXT,
  store_id    INTEGER,
  sales       INTEGER,   -- rows counted by the buggy job
  revenue_usd REAL       -- overstated on 02-10, 02-11, and 02-12: refunds were excluded
);
INSERT INTO fct_daily_sales (dt, store_id, sales, revenue_usd) VALUES
  -- raw_sales has a retention window and the fact does not, so 2026-02-05 lives ONLY here and
  -- nothing can reproduce it. A backfill that deletes more than the manifest destroys it, which is
  -- what makes "leaves all other dates untouched" a graded property rather than a hope.
  ('2026-02-05', 1, 3, 402.10),
  ('2026-02-05', 2, 2, 118.75),
  ('2026-02-08', 1, 1, 120.00),
  ('2026-02-08', 2, 1,  95.50),
  ('2026-02-09', 1, 1, 210.00),
  -- already net of the 02-09 refund: this date is queued in the manifest but is not broken
  ('2026-02-09', 2, 2,  45.50),
  ('2026-02-10', 1, 1, 180.00),
  ('2026-02-10', 2, 1, 140.00),
  ('2026-02-11', 1, 1, 260.50),
  ('2026-02-11', 2, 1,  88.00),
  ('2026-02-12', 1, 1, 150.00),
  ('2026-02-12', 2, 1, 175.75),
  ('2026-02-13', 1, 1, 199.00),
  ('2026-02-13', 2, 1, 120.40),
  ('2026-02-14', 1, 2, 388.25),
  ('2026-02-14', 2, 1,  45.60);

CREATE TABLE backfill_manifest (
  run_date TEXT   -- one row per date the scheduler was asked to rerun
);
INSERT INTO backfill_manifest (run_date) VALUES
  ('2026-02-08'),
  ('2026-02-09'),
  ('2026-02-10'),
  ('2026-02-11'),
  ('2026-02-12');`

// This is the SECOND stage of the same incident: the fact backfill has already run. It is scoped to
// the two weeks the manifest touches, so unlike BACKFILL_SEED it carries no retention-only partition.
const BACKFILL_MART_SEED = `CREATE TABLE fct_daily_sales (
  dt          TEXT,
  store_id    INTEGER,
  sales       INTEGER,
  revenue_usd REAL   -- already repaired by the fact backfill; the mart has not caught up
);
INSERT INTO fct_daily_sales (dt, store_id, sales, revenue_usd) VALUES
  ('2026-02-08', 1, 1, 120.00),
  ('2026-02-08', 2, 1,  95.50),
  ('2026-02-09', 1, 1, 210.00),
  ('2026-02-09', 2, 2,  45.50),
  ('2026-02-10', 1, 2, 135.00),
  ('2026-02-10', 2, 1, 140.00),
  ('2026-02-11', 1, 1, 260.50),
  ('2026-02-11', 2, 2,  57.75),
  ('2026-02-12', 1, 2,  90.00),
  ('2026-02-12', 2, 1, 175.75),
  ('2026-02-13', 1, 1, 199.00),
  ('2026-02-13', 2, 1, 120.40),
  ('2026-02-14', 1, 2, 388.25),
  ('2026-02-14', 2, 1,  45.60);

CREATE TABLE backfill_manifest (
  run_date TEXT
);
INSERT INTO backfill_manifest (run_date) VALUES
  ('2026-02-08'),
  ('2026-02-09'),
  ('2026-02-10'),
  ('2026-02-11'),
  ('2026-02-12');

CREATE TABLE mart_weekly_sales (
  week_start  TEXT,   -- the Monday of the ISO week
  revenue_usd REAL    -- still holds the pre-backfill numbers for the weeks the manifest touches
);
INSERT INTO mart_weekly_sales (week_start, revenue_usd) VALUES
  ('2026-01-26', 980.00),
  ('2026-02-02', 215.50),
  ('2026-02-09', 2021.75),
  ('2026-02-16', 1450.00);`

const backfills: SqlLesson = {
  id: "de-l8-backfills",
  title: "Backfills: Manifest-Driven Reruns and the Downstream Trap",
  summary:
    "Reprocess a date range from a backfill manifest, then rebuild the downstream aggregate for exactly the affected weeks so the mart stops lying.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "backfill",
    "manifest-driven multi-partition rerun",
    "downstream recomputation",
    "bounded reprocessing cost",
    "date-range joins",
    "INSERT SELECT over joined ranges",
    "script composition",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Backfillable means parameterized

A job is backfillable when it accepts the date it is responsible for as a parameter and hardcodes nothing about "today". That single property is what lets a scheduler point the same code at last Tuesday. The moment a transformation calls the wall clock, or filters on a literal date someone typed during an incident, the job can only ever produce today's answer and a backfill is impossible without editing code.

You already know how to rebuild **one** partition: delete the date, reinsert the date, which is idempotent because the delete runs first. \`sql-l5-incremental-watermark-backfill\` taught that. This lesson starts one step past it.

## The manifest drives the loop

A real backfill is not one date, it is a set of them, and the set lives in a table. A **manifest** is one row per date the scheduler was asked to rerun, and the job joins to it rather than repeating a statement per date:

\`\`\`sql
DELETE FROM fct_daily_sales WHERE dt IN (SELECT run_date FROM backfill_manifest);

INSERT INTO fct_daily_sales (dt, store_id, sales, revenue_usd)
SELECT s.dt, s.store_id, COUNT(*), SUM(s.amount_usd)
FROM raw_sales s
JOIN backfill_manifest m ON m.run_date = s.dt
GROUP BY s.dt, s.store_id
\`\`\`

Two statements handle five dates or five hundred. Nothing about the SQL changes when the manifest grows, which is the whole point: the dates are data, not code. Notice also that the manifest here holds the **deploy window** rather than the dates you believe broke. That is how incident tickets are actually written, and it is the safer instinct: rerun the range the bad code was live, and accept that some of those dates were fine.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "backfill_manifest", "note": "one row per date to rerun" },
    { "label": "delete partitions", "note": "only the dates in the manifest" },
    { "label": "insert from raw", "note": "joined to the manifest, not hardcoded" },
    { "label": "recompute mart", "note": "the weeks those dates fall in" }
  ],
  "highlight": ["recompute mart"],
  "caption": "The manifest drives every step. The highlighted one is where most candidates stop, and it is where the interviewer's follow-up lives."
}
\`\`\`

## The trap: the fact is repaired and the mart still lies

Here is the part that earns this lesson its slot. You rerun the fact table, every assertion passes, the numbers reconcile against raw. And the weekly mart built on top of that fact still holds the old totals, because **nothing downstream knows it is stale**. There is no error, no failed run, no alert. Somebody opens the dashboard next Monday and the revenue is wrong, four days after you closed the incident.

Anything derived from a partition you rewrote is stale until you rebuild it. That means the backfill script has one more step than people expect, and the step is bounded the same way: recompute exactly the weeks that contain a manifest date, not the whole mart. Cost is a design constraint. Rebuilding three broken days plus the two weeks they fall in is a minute of compute; a full-history recompute on every incident is how a backfill turns into its own outage.

## Cost, and why unbounded catchup blows up

The other half of the cost story is the scheduler. If you enable catchup on a daily pipeline whose start date is two years back, the scheduler will happily queue seven hundred runs and try to execute them with whatever parallelism it has. That is the classic self-inflicted outage: your own backfill saturates the warehouse and takes production down with it. Bound the range, and bound the concurrency.

**Common mistake:** repairing the fact and stopping there. The fact is the table you were paged about; the mart is the table the business actually reads.

**Interview nuance:** "your transformation logic had a bug for two weeks, walk me through the fix" is a standard scenario, and the expected answer has an order: build a manifest of the affected dates, rerun the job per date with a partition-scoped idempotent write, then recompute the downstream aggregates for the affected windows, all bounded to the broken range. Candidates who stop after the fact table get the follow-up "and what about everything built on top of it", which is a question you would rather answer before it is asked.

> **On a real platform this differs.** Airflow 3 made backfills scheduler-managed and first class, so the manifest is the set of logical dates you hand the scheduler rather than a table you maintain, and dbt would express the downstream recompute as a selector over the model graph (\`dbt run --select fct_daily_sales+\`) because the lineage already knows what depends on what. The reasoning is identical: bounded set of partitions, idempotent write, downstream refreshed.`,
    demoSeedSql: BACKFILL_MART_SEED,
    demoCode: `-- The trap, live. The fact table has ALREADY been repaired by the backfill. This is what the
-- weekly mart built on top of it still reports, and nothing anywhere raised an error about it.
SELECT w.week_start,
       ROUND(w.revenue_usd, 2) AS mart_revenue,
       (SELECT ROUND(SUM(f.revenue_usd), 2) FROM fct_daily_sales f
        WHERE date(f.dt, 'weekday 0', '-6 days') = w.week_start) AS recomputed_revenue,
       CASE
         WHEN (SELECT COUNT(*) FROM fct_daily_sales f
               WHERE date(f.dt, 'weekday 0', '-6 days') = w.week_start) = 0
           THEN 'no fact rows for this week'
         WHEN ROUND(w.revenue_usd, 2) <> (SELECT ROUND(SUM(f.revenue_usd), 2) FROM fct_daily_sales f
                                          WHERE date(f.dt, 'weekday 0', '-6 days') = w.week_start)
           THEN 'STALE: still the pre-backfill total'
         ELSE 'agrees with the repaired fact'
       END AS mart_status
FROM mart_weekly_sales w
ORDER BY w.week_start;`,
    showDemoInput: true,
  },
  // Map deviation: the map wanted "a hidden assertion that adds a fourth manifest row" to punish a
  // hardcoded date list. An assertion in this engine is a single read-only SELECT that must return
  // zero rows, so it cannot mutate the manifest. Instead the manifest ships FIVE dates straddling
  // two ISO weeks, the assertions verify every manifest date against raw truth and every
  // non-manifest date byte for byte, and the starter code plus hints teach the join form. The
  // untouched-date assertion also moves from 2026-02-08 (now a manifest row) to 2026-02-14.
  // The scope assertions are what make an UNBOUNDED answer fail: 2026-02-05 has no raw_sales rows
  // at all, so `DELETE FROM fct_daily_sales` followed by a full recompute cannot bring it back.
  apply: scriptExercise({
    id: "de-l8-backfills-apply",
    prompt: `Write a script that rebuilds \`fct_daily_sales\` for every date in \`backfill_manifest\` from \`raw_sales\`, leaves all other dates untouched, and changes nothing when it is rerun.

\`raw_sales(sale_id, dt, store_id, amount_usd)\` is the truth, including the negative refund rows the buggy job excluded. \`fct_daily_sales(dt, store_id, sales, revenue_usd)\` is at the date and store grain, where \`sales\` is the row count and \`revenue_usd\` is the summed amount. Drive both the delete and the insert from \`backfill_manifest\` rather than naming dates in your SQL, so the same script still works when the manifest grows.`,
    starterCode: `-- Manifest-driven partition replacement. The dates are data, not code.
-- Step 1: delete exactly the manifest's partitions from fct_daily_sales.

-- Step 2: reinsert them from raw_sales at the (dt, store_id) grain.
`,
    hints: [
      "The teach body already prints both statements, so the work here is the decisions: the delete has to run before the insert, or the rerun doubles every date you just repaired, and it has to be scoped to the manifest, because the fact holds partitions `raw_sales` can no longer reproduce.",
      "Join `raw_sales` to `backfill_manifest` on the date instead of filtering with a literal list, and group at the `(dt, store_id)` grain so the fact keeps its shape.",
    ],
    referenceSolution: `DELETE FROM fct_daily_sales
WHERE dt IN (SELECT run_date FROM backfill_manifest);

INSERT INTO fct_daily_sales (dt, store_id, sales, revenue_usd)
SELECT s.dt, s.store_id, COUNT(*), SUM(s.amount_usd)
FROM raw_sales s
JOIN backfill_manifest m ON m.run_date = s.dt
GROUP BY s.dt, s.store_id;`,
    seedSql: BACKFILL_SEED,
    checkIdempotency: true,
    idempotencyTables: ["fct_daily_sales"],
    assertions: [
      {
        suite: "grain",
        name: "one row per date and store",
        sql: `SELECT dt FROM fct_daily_sales GROUP BY dt, store_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "backfill",
        name: "every manifest date now matches raw_sales",
        sql: `SELECT s.dt FROM (
  SELECT s.dt, s.store_id, COUNT(*) AS sales, ROUND(SUM(s.amount_usd), 2) AS revenue_usd
  FROM raw_sales s JOIN backfill_manifest m ON m.run_date = s.dt
  GROUP BY s.dt, s.store_id
) s
LEFT JOIN fct_daily_sales f ON f.dt = s.dt AND f.store_id = s.store_id
WHERE f.dt IS NULL OR f.sales <> s.sales OR ROUND(f.revenue_usd, 2) <> s.revenue_usd`,
      },
      {
        suite: "backfill",
        name: "no manifest date carries an extra store row",
        isHidden: true,
        sql: `SELECT f.dt FROM fct_daily_sales f
JOIN backfill_manifest m ON m.run_date = f.dt
WHERE NOT EXISTS (SELECT 1 FROM raw_sales s WHERE s.dt = f.dt AND s.store_id = f.store_id)`,
      },
      {
        suite: "scope",
        name: "2026-02-14 was left exactly as it was",
        isHidden: true,
        sql: `WITH untouched(dt, store_id, sales, revenue_usd) AS (
  VALUES ('2026-02-14', 1, 2, 388.25), ('2026-02-14', 2, 1, 45.60)
)
SELECT * FROM (SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-14' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-14')`,
      },
      {
        suite: "scope",
        name: "2026-02-05, which raw_sales can no longer reproduce, still holds its rows",
        isHidden: true,
        sql: `WITH untouched(dt, store_id, sales, revenue_usd) AS (
  VALUES ('2026-02-05', 1, 3, 402.10), ('2026-02-05', 2, 2, 118.75)
)
SELECT * FROM (SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-05' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-05')`,
      },
      {
        suite: "scope",
        name: "2026-02-13 still holds its pre-backfill values",
        isHidden: true,
        sql: `WITH untouched(dt, store_id, sales, revenue_usd) AS (
  VALUES ('2026-02-13', 1, 1, 199.00), ('2026-02-13', 2, 1, 120.40)
)
SELECT * FROM (SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-13' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT dt, store_id, sales, revenue_usd FROM fct_daily_sales WHERE dt = '2026-02-13')`,
      },
      {
        suite: "backfill",
        name: "the refund on 2026-02-10 is now inside store 1's revenue",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT ROUND(revenue_usd, 2) FROM fct_daily_sales WHERE dt = '2026-02-10' AND store_id = 1) <> 135.00`,
      },
    ],
  }),
  practice: scriptExercise({
    id: "de-l8-backfills-practice",
    prompt: `Write a script that recomputes \`mart_weekly_sales\` for exactly the weeks containing the \`backfill_manifest\` dates, leaving other weeks untouched, and that is safe to rerun.

\`fct_daily_sales\` has already been repaired, so it is your source of truth. \`mart_weekly_sales(week_start, revenue_usd)\` still holds the pre-backfill totals, and \`week_start\` is the Monday of the ISO week, which SQLite gives you as \`date(dt, 'weekday 0', '-6 days')\`. The manifest straddles two weeks, so the affected set is not one row, and the weeks it does not touch must keep their current values exactly.`,
    starterCode: `-- The downstream half of the backfill. The fact is fixed; the mart still lies.
-- Step 1: delete only the weeks that contain a manifest date.

-- Step 2: recompute those weeks from the repaired fct_daily_sales.
`,
    hints: [
      "`date(dt, 'weekday 0', '-6 days')` maps any date to the Monday of its ISO week, so `SELECT DISTINCT date(run_date, 'weekday 0', '-6 days') FROM backfill_manifest` is the set of affected weeks, and both the delete and the insert filter on that set.",
    ],
    seedSql: BACKFILL_MART_SEED,
    checkIdempotency: true,
    idempotencyTables: ["mart_weekly_sales"],
    assertions: [
      {
        suite: "grain",
        name: "one row per week_start",
        sql: `SELECT week_start FROM mart_weekly_sales GROUP BY week_start HAVING COUNT(*) > 1`,
      },
      {
        suite: "downstream",
        name: "every affected week now agrees with the repaired fact",
        sql: `SELECT w.week_start FROM (
  SELECT date(dt, 'weekday 0', '-6 days') AS week_start, ROUND(SUM(revenue_usd), 2) AS revenue_usd
  FROM fct_daily_sales
  WHERE date(dt, 'weekday 0', '-6 days') IN (
    SELECT date(run_date, 'weekday 0', '-6 days') FROM backfill_manifest
  )
  GROUP BY week_start
) w
LEFT JOIN mart_weekly_sales m ON m.week_start = w.week_start
WHERE m.week_start IS NULL OR ROUND(m.revenue_usd, 2) <> w.revenue_usd`,
      },
      {
        suite: "scope",
        name: "the weeks outside the manifest kept their values",
        isHidden: true,
        sql: `WITH untouched(week_start, revenue_usd) AS (
  VALUES ('2026-01-26', 980.00), ('2026-02-16', 1450.00)
)
SELECT * FROM (SELECT week_start, revenue_usd FROM mart_weekly_sales WHERE week_start IN ('2026-01-26', '2026-02-16') EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT week_start, revenue_usd FROM mart_weekly_sales WHERE week_start IN ('2026-01-26', '2026-02-16'))`,
      },
      {
        suite: "scope",
        name: "the mart still holds exactly four weeks",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM mart_weekly_sales) <> 4`,
      },
      {
        suite: "downstream",
        name: "the stale total for the week of 2026-02-09 is gone",
        isHidden: true,
        sql: `SELECT week_start FROM mart_weekly_sales
WHERE week_start = '2026-02-09' AND ROUND(revenue_usd, 2) = 2021.75`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-backfills-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns each manifest date with what the fact currently reports and what raw truth says, as \`(run_date, current_revenue, recomputed_revenue, revenue_delta)\`, oldest date first, over \`backfill_manifest\`, \`fct_daily_sales\`, and \`raw_sales\`.

\`current_revenue\` is the fact's summed \`revenue_usd\` for that date, \`recomputed_revenue\` is the summed \`amount_usd\` in \`raw_sales\` for that date, and \`revenue_delta\` is the recomputed value minus the current one. Round every money column to 2 decimal places and alias the columns exactly.`,
      starterCode: `-- Sizing the damage before the backfill runs: what does each queued date actually owe?
SELECT
FROM backfill_manifest m
ORDER BY m.run_date;`,
      hints: [
        "Two correlated scalar subqueries keep this readable: one over `fct_daily_sales` and one over `raw_sales`, both filtered to `m.run_date`.",
        "Round each aggregate with `ROUND(..., 2)` so the summed floats compare cleanly.",
        "The delta is `recomputed minus current`, so the broken dates come back negative: the fact was overstating revenue.",
      ],
      referenceSolution: `SELECT m.run_date,
       ROUND((SELECT SUM(f.revenue_usd) FROM fct_daily_sales f WHERE f.dt = m.run_date), 2) AS current_revenue,
       ROUND((SELECT SUM(s.amount_usd) FROM raw_sales s WHERE s.dt = m.run_date), 2) AS recomputed_revenue,
       ROUND((SELECT SUM(s.amount_usd) FROM raw_sales s WHERE s.dt = m.run_date)
             - (SELECT SUM(f.revenue_usd) FROM fct_daily_sales f WHERE f.dt = m.run_date), 2) AS revenue_delta
FROM backfill_manifest m
ORDER BY m.run_date;`,
      singleFile: {
        seedSql: BACKFILL_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["run_date", "current_revenue", "recomputed_revenue", "revenue_delta"],
          rows: [
            ["2026-02-08", 215.5, 215.5, 0],
            ["2026-02-09", 255.5, 255.5, 0],
            ["2026-02-10", 320, 275, -45],
            ["2026-02-11", 348.5, 318.25, -30.25],
            ["2026-02-12", 325.75, 265.75, -60],
          ],
        },
      },
    },
    {
      id: "de-l8-backfills-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the \`mart_weekly_sales\` rows a manifest date falls inside, as \`(week_start, revenue_usd, affected_dates)\`, oldest week first, over \`mart_weekly_sales\` and \`backfill_manifest\`.

Join each mart week to the manifest with a date-range condition: a week covers \`week_start\` through six days later. \`affected_dates\` is how many manifest dates land in that week. Return only weeks with at least one, and alias the columns exactly.`,
      starterCode: `-- Which downstream rows did the fact backfill just invalidate?
SELECT
FROM mart_weekly_sales w
JOIN backfill_manifest m
  ON -- the range condition goes here
GROUP BY w.week_start
ORDER BY w.week_start;`,
      hints: [
        "The range condition is `m.run_date BETWEEN w.week_start AND date(w.week_start, '+6 days')`, which needs no weekday arithmetic at all.",
        "An inner join already drops the weeks with no manifest date, so no `HAVING` is required.",
        "`COUNT(*)` after grouping by `w.week_start` is the affected-date count.",
      ],
      referenceSolution: `SELECT w.week_start, w.revenue_usd, COUNT(*) AS affected_dates
FROM mart_weekly_sales w
JOIN backfill_manifest m
  ON m.run_date BETWEEN w.week_start AND date(w.week_start, '+6 days')
GROUP BY w.week_start, w.revenue_usd
ORDER BY w.week_start;`,
      singleFile: {
        seedSql: BACKFILL_MART_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["week_start", "revenue_usd", "affected_dates"],
          rows: [
            ["2026-02-02", 215.5, 1],
            ["2026-02-09", 2021.75, 4],
          ],
        },
      },
    },
    {
      id: "de-l8-backfills-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the manifest dates the backfill could safely skip, as \`(run_date, store_rows)\`, oldest date first, over \`backfill_manifest\`, \`fct_daily_sales\`, and \`raw_sales\`.

A date is skippable when the fact already agrees with raw truth at the \`(dt, store_id)\` grain: same set of stores, same row counts, same summed revenue rounded to 2 decimal places. \`store_rows\` is how many store rows that date holds in the fact. This is the query that turns a five date manifest into the three dates that actually need compute.`,
      starterCode: `-- Which queued dates were never broken? Every one you skip is compute you do not spend.
SELECT
FROM backfill_manifest m
ORDER BY m.run_date;`,
      hints: [
        "Build the raw truth at the same grain first, in a CTE: `SELECT dt, store_id, COUNT(*) AS sales, ROUND(SUM(amount_usd), 2) AS revenue_usd FROM raw_sales GROUP BY dt, store_id`.",
        "A date disagrees when `EXCEPT` in either direction returns a row for it, so `NOT EXISTS` over a two-way `EXCEPT` restricted to that date is the cleanest test.",
        "Remember to round the fact's `revenue_usd` the same way before comparing, or two equal amounts can differ in the last bit.",
        "Two of the five dates survive. Do not shortcut this by looking for refund rows: one date has a refund and is still correct, because it was already rerun by hand during the incident.",
      ],
      referenceSolution: `WITH truth AS (
  SELECT dt, store_id, COUNT(*) AS sales, ROUND(SUM(amount_usd), 2) AS revenue_usd
  FROM raw_sales
  GROUP BY dt, store_id
),
current AS (
  SELECT dt, store_id, sales, ROUND(revenue_usd, 2) AS revenue_usd
  FROM fct_daily_sales
)
SELECT m.run_date,
       (SELECT COUNT(*) FROM current c WHERE c.dt = m.run_date) AS store_rows
FROM backfill_manifest m
WHERE NOT EXISTS (
  SELECT dt, store_id, sales, revenue_usd FROM truth WHERE dt = m.run_date
  EXCEPT
  SELECT dt, store_id, sales, revenue_usd FROM current WHERE dt = m.run_date
)
AND NOT EXISTS (
  SELECT dt, store_id, sales, revenue_usd FROM current WHERE dt = m.run_date
  EXCEPT
  SELECT dt, store_id, sales, revenue_usd FROM truth WHERE dt = m.run_date
)
ORDER BY m.run_date;`,
      singleFile: {
        seedSql: BACKFILL_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["run_date", "store_rows"],
          rows: [
            ["2026-02-08", 2],
            ["2026-02-09", 2],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.3.4 seeds — the whole daily pipeline in one database.
// `run_config` injects the run's date exactly the way a scheduler passes a logical date, so nothing
// in the graded SQL is allowed to reach for a clock. `src_orders` carries the two dirt patterns a
// staging layer exists to absorb: cancelled rows that must not reach the fact, and one order_id
// redelivered twice by a partial extract. `pipeline_audit_log` is append-only BY DESIGN, which is
// why every workspace exercise here names only the staging and fact tables in `idempotencyTables`.
// ---------------------------------------------------------------------------

const DAILY_PIPELINE_SEED = `CREATE TABLE run_config (
  pipeline TEXT,
  run_date TEXT   -- the scheduler's logical date; the pipeline is responsible for this day only
);
INSERT INTO run_config (pipeline, run_date) VALUES
  ('orders_daily', '2026-03-14');

CREATE TABLE src_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  amount_usd  REAL,
  status      TEXT,    -- placed | shipped | delivered | cancelled
  updated_at  TEXT
);
INSERT INTO src_orders (order_id, customer_id, amount_usd, status, updated_at) VALUES
  (8101, 401, 120.00, 'placed',    '2026-03-12 08:10:00'),
  (8102, 402,  75.50, 'shipped',   '2026-03-12 12:35:00'),
  (8103, 403, 240.00, 'placed',    '2026-03-12 17:20:00'),
  (8104, 404,  59.90, 'delivered', '2026-03-12 21:05:00'),
  (8105, 405, 310.25, 'placed',    '2026-03-13 07:45:00'),
  (8106, 406,  88.00, 'shipped',   '2026-03-13 10:15:00'),
  (8107, 407, 145.75, 'placed',    '2026-03-13 14:50:00'),
  (8108, 408,  62.40, 'delivered', '2026-03-13 18:30:00'),
  (8109, 409, 199.00, 'placed',    '2026-03-13 22:40:00'),
  (8110, 410, 130.00, 'placed',    '2026-03-14 06:20:00'),
  (8111, 411,  95.60, 'cancelled', '2026-03-14 07:55:00'),
  (8112, 412, 275.00, 'shipped',   '2026-03-14 09:30:00'),
  (8113, 413,  48.25, 'placed',    '2026-03-14 11:10:00'),
  (8114, 414, 162.80, 'cancelled', '2026-03-14 13:45:00'),
  (8115, 415, 210.50, 'placed',    '2026-03-14 15:05:00'),
  -- the same order redelivered by a partial extract; only the newest row may survive staging
  (8115, 415, 210.50, 'shipped',   '2026-03-14 16:40:00');

CREATE TABLE stg_orders_daily (
  order_id    INTEGER,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);

CREATE TABLE fct_orders_daily (
  order_id    INTEGER,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO fct_orders_daily (order_id, dt, customer_id, amount_usd) VALUES
  (8105, '2026-03-13', 405, 310.25),
  (8106, '2026-03-13', 406,  88.00),
  (8107, '2026-03-13', 407, 145.75),
  (8108, '2026-03-13', 408,  62.40),
  (8109, '2026-03-13', 409, 199.00),
  -- two rows a half-finished earlier run left behind on the current partition
  (8110, '2026-03-14', 410, 999.00),
  (8111, '2026-03-14', 411,  95.60);

CREATE TABLE pipeline_audit_log (
  pipeline    TEXT,
  run_date    TEXT,
  table_name  TEXT,
  rows_loaded INTEGER   -- append-only: one row per run, on purpose
);`

const DAILY_PIPELINE_REDELIVERY_SEED = `CREATE TABLE run_config (
  pipeline TEXT,
  run_date TEXT
);
INSERT INTO run_config (pipeline, run_date) VALUES
  ('orders_daily', '2026-03-15');

CREATE TABLE src_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  amount_usd  REAL,
  status      TEXT,
  updated_at  TEXT
);
INSERT INTO src_orders (order_id, customer_id, amount_usd, status, updated_at) VALUES
  -- the extract redelivered the whole previous day alongside the new one
  (8110, 410, 130.00, 'placed',    '2026-03-14 06:20:00'),
  (8112, 412, 275.00, 'shipped',   '2026-03-14 09:30:00'),
  (8113, 413,  48.25, 'placed',    '2026-03-14 11:10:00'),
  (8115, 415, 210.50, 'shipped',   '2026-03-14 16:40:00'),
  (8116, 416,  84.00, 'placed',    '2026-03-15 05:40:00'),
  (8117, 417, 156.25, 'cancelled', '2026-03-15 08:15:00'),
  (8118, 418, 302.00, 'shipped',   '2026-03-15 10:50:00'),
  (8119, 419,  67.75, 'placed',    '2026-03-15 12:30:00'),
  (8120, 420, 143.40, 'placed',    '2026-03-15 14:05:00'),
  (8120, 420, 143.40, 'delivered', '2026-03-15 19:20:00'),
  (8121, 421,  91.10, 'cancelled', '2026-03-15 20:45:00'),
  (8122, 422, 228.60, 'shipped',   '2026-03-15 22:10:00');

CREATE TABLE stg_orders_daily (
  order_id    INTEGER,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO stg_orders_daily (order_id, dt, customer_id, amount_usd) VALUES
  -- left over from yesterday's run: staging is not cleared for you
  (8110, '2026-03-14', 410, 130.00),
  (8112, '2026-03-14', 412, 275.00),
  (8113, '2026-03-14', 413,  48.25),
  (8115, '2026-03-14', 415, 210.50);

CREATE TABLE fct_orders_daily (
  order_id    INTEGER,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO fct_orders_daily (order_id, dt, customer_id, amount_usd) VALUES
  (8110, '2026-03-14', 410, 130.00),
  (8112, '2026-03-14', 412, 275.00),
  (8113, '2026-03-14', 413,  48.25),
  (8115, '2026-03-14', 415, 210.50);

CREATE TABLE pipeline_audit_log (
  pipeline    TEXT,
  run_date    TEXT,
  table_name  TEXT,
  rows_loaded INTEGER
);
INSERT INTO pipeline_audit_log (pipeline, run_date, table_name, rows_loaded) VALUES
  ('orders_daily', '2026-03-14', 'fct_orders_daily', 4);`

const AUDIT_HISTORY_SEED = `CREATE TABLE pipeline_audit_log (
  pipeline    TEXT,
  run_date    TEXT,
  table_name  TEXT,
  rows_loaded INTEGER
);
INSERT INTO pipeline_audit_log (pipeline, run_date, table_name, rows_loaded) VALUES
  ('orders_daily', '2026-03-08', 'fct_orders_daily', 412),
  ('orders_daily', '2026-03-09', 'fct_orders_daily', 455),
  ('orders_daily', '2026-03-10', 'fct_orders_daily', 431),
  ('orders_daily', '2026-03-11', 'fct_orders_daily', 498),
  -- the silent success: the run was green and wrote nothing
  ('orders_daily', '2026-03-12', 'fct_orders_daily',   0),
  ('orders_daily', '2026-03-13', 'fct_orders_daily', 507),
  ('orders_daily', '2026-03-14', 'fct_orders_daily', 486);

CREATE TABLE fct_orders_daily (
  order_id    INTEGER,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO fct_orders_daily (order_id, dt, customer_id, amount_usd) VALUES
  -- 2026-03-07 and 2026-03-15 were loaded by hand during an incident, with no audit row
  (8001, '2026-03-07', 401, 120.00),
  (8002, '2026-03-08', 402,  95.50),
  (8003, '2026-03-09', 403, 210.00),
  (8004, '2026-03-10', 404,  64.25),
  (8005, '2026-03-11', 405, 180.00),
  (8006, '2026-03-13', 406, 140.00),
  (8007, '2026-03-14', 407, 260.50),
  (8008, '2026-03-15', 408,  88.00);`

const dailyPipelineRehearsal: SqlLesson = {
  id: "de-l8-daily-pipeline-rehearsal",
  title: "The Daily Ingestion Pipeline, End to End",
  summary:
    "Build the whole daily pipeline in one script, stage then load then audit, and rehearse the spoken design answer against a written model answer.",
  estimatedMinutes: 32,
  difficulty: "hard",
  skills: [
    "end-to-end pipeline composition",
    "staging layer",
    "idempotent partition load",
    "run audit log",
    "scoped idempotency contract",
    "design articulation",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Composing the parts

Every component in this level has been built on its own: the parameterized run date, the deduplicated batch, the partition replacement, the manifest, the audit. This lesson puts them in one script, in the shape the most common pipeline-design question asks for.

Three stages, and the boundaries between them are the point.

1. **Stage.** Land the run's slice of the extract into \`stg_orders_daily\`, rebuilt from scratch every run. Staging is where dirt is absorbed: the cancelled orders are filtered out here, and the order the extract redelivered twice is collapsed to one row here. Nothing downstream should ever have to know those problems existed.
2. **Load.** Replace the run's partition in \`fct_orders_daily\` from staging. Delete the day, insert the day. This is the idempotent write, and it is the reason a retry is boring.
3. **Audit.** Append one row to \`pipeline_audit_log\` recording what this run loaded. That is how you answer "did it run, and what did it write" without opening the orchestrator, and it is the table that catches a green run that wrote zero rows.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "run_config", "note": "the injected run_date, never a clock" },
    { "label": "stage", "note": "filter cancelled, dedupe the redelivery" },
    { "label": "load", "note": "replace the run_date partition" },
    { "label": "audit", "note": "append one row per run" }
  ],
  "highlight": ["stage"],
  "caption": "The daily pipeline. The highlighted stage is the one people skip, and it is where every dirty-data rule belongs."
}
\`\`\`

## The contract the audit log forces

Notice what the third stage does to the grading. Staging and the fact must be **byte for byte identical** after two runs. The audit log must **grow** after two runs, because that is what a ledger does. So the idempotency contract has to name the tables it covers: staging and the fact, not the log.

That is not a grading trick, it is the production distinction. Some tables are a projection of the current truth and you promise they are stable. Others are an append-only record of history and their whole value is that they keep growing. Confusing the two is how people end up truncating their own audit trail to make a check pass.

## Design rehearsal

Attempt the build before you read the next part. The written model answer below is worth much more after you have tried to compose the script yourself, and reading it first will cost you the retrieval practice that makes it stick.

\`\`\`cswidget
{
  "type": "check",
  "kind": "predict",
  "id": "daily-pipeline-first-beat",
  "prompt": "An interviewer says: design a daily pipeline that moves orders from a Postgres database into the warehouse. What is the first thing your answer should establish?",
  "options": [
    {
      "label": "The full source schema, column by column, so nothing is ambiguous later",
      "feedback": "Schema detail is cheap to add on request and burns the minutes where the interviewer is deciding whether you have a run model at all."
    },
    {
      "label": "A scheduled run that is responsible for one date, with that date injected as a parameter rather than read from the clock",
      "correct": true,
      "feedback": "Right. Establishing that a run owns a data interval, and that the date is a parameter, is what makes everything after it (reruns, backfills, idempotency) sayable."
    },
    {
      "label": "The exact warehouse you would use and why it beats the alternatives",
      "feedback": "Tool choice is the least portable part of the answer and the interviewer usually has one already; lead with the run model instead."
    },
    {
      "label": "Whether the pipeline should be streaming instead, since streaming is more modern",
      "feedback": "Defaulting to streaming because it sounds impressive is a named junior mistake. Batch is correct until a decision needs lower latency than batch provides."
    }
  ],
  "reveal": "Beat one is the run model. Everything else in the answer hangs off it."
}
\`\`\`

Here is the full model answer to "design the daily pipeline from Postgres, an API, or CSV drops to the warehouse", in five beats. Say them in this order.

1. **Orchestrator.** A scheduled DAG with a daily data interval. Each run is responsible for exactly one date, and that date arrives as a parameter: an Airflow logical date, an ADF trigger window, a Glue job parameter. Never \`datetime.now()\`, because a job that reads the clock can only ever produce today's answer and can never be rerun.
2. **Extraction with a watermark plus lookback.** Pull rows newer than the stored watermark minus a lookback sized to the lateness you have actually measured. From an API, page through and land the raw payload before you parse it. From CSV drops, land the file as it arrived and key rows on filename plus row number so a redelivered file is recognizable.
3. **Idempotent sink.** For a partitioned fact, delete the run's partition and insert it. For a dimension, upsert on the business key. Then say the sentence out loud: **at-least-once delivery plus an idempotent sink is effectively exactly-once**. True exactly-once delivery does not exist, and knowing that is the point.
4. **Backfill story.** The same job, run once per date from a manifest, with the downstream aggregates recomputed for the affected windows. Bounded to the broken range. Never an unbounded catchup, which is how a backfill takes production down.
5. **Two failure modes, raised before you are asked.** Silent success: the run is green and wrote zero rows, caught by comparing this run's volume against the task's own history in the audit log. And late data below the watermark, caught by an anti-join audit and healed by a rolling reprocessing window.

**Common mistake:** describing the happy path beautifully and stopping. The flow is the junior bar; every prepared candidate has it.

**Interview nuance:** the junior bar is a sensible end-to-end flow with the right vocabulary. The separator is beat five. Naming the failure modes before the interviewer asks is the single clearest senior signal in a pipeline-design question, and it costs you two sentences.

> **On a real platform this differs.** The audit log is your orchestrator's own run-results table, or dbt's \`run_results.json\` loaded into the warehouse after every invocation, and the staging layer is a schema (or a database) rather than a table-name prefix. The three stages usually become three tasks in the DAG so each one can be retried on its own, which is the atomic-task rule: separate extract, transform, and load so a failure restarts the smallest possible unit.`,
    demoSeedSql: DAILY_PIPELINE_SEED,
    demoCode: `-- What staging must absorb before anything reaches the fact: the run's own day only,
-- cancelled orders dropped, and the redelivered order collapsed to its newest row.
SELECT s.order_id, s.status, s.updated_at,
       CASE
         WHEN date(s.updated_at) <> (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily')
           THEN 'other partition (not this run)'
         WHEN s.status = 'cancelled' THEN 'filtered by staging (cancelled)'
         WHEN s.updated_at < (SELECT MAX(s2.updated_at) FROM src_orders s2 WHERE s2.order_id = s.order_id)
           THEN 'superseded redelivery (older row for the same order)'
         ELSE 'stages'
       END AS staging_decision
FROM src_orders s
ORDER BY s.updated_at;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "de-l8-daily-pipeline-rehearsal-apply",
    prompt: `Write a script that stages the \`run_date\` rows from \`src_orders\` into \`stg_orders_daily\` excluding cancelled orders and keeping one row per \`order_id\`, replaces the \`run_date\` partition of \`fct_orders_daily\` from staging, and appends one \`pipeline_audit_log\` row recording the rows loaded.

The run's date is the \`run_config\` row for \`'orders_daily'\`, so read it rather than typing a date. A row belongs to the run when \`date(updated_at)\` equals that date; where an \`order_id\` appears twice, keep the newest \`updated_at\`. Staging holds \`(order_id, dt, customer_id, amount_usd)\` and must be rebuilt from scratch every run. The audit row is \`('orders_daily', run_date, 'fct_orders_daily', rows loaded)\`. The grader runs your script twice and compares the contents of \`stg_orders_daily\` and \`fct_orders_daily\` only, because the audit log grows one row per run by design.`,
    starterCode: `-- Stage, load, audit. The run_date comes from run_config; nothing here reads a clock.
-- Step 1: rebuild stg_orders_daily for the run_date (no cancelled rows, one row per order_id).

-- Step 2: replace the run_date partition of fct_orders_daily from staging.

-- Step 3: append one audit row recording what this run loaded.
`,
    hints: [
      "Staging is rebuilt every run rather than appended to, and the fact's partition is replaced rather than inserted into, so two of your five statements are deletes that run before their inserts.",
      "Collapsing a redelivered `order_id` to its newest row is `ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC)` filtered to `rn = 1`, and every date in the script is read from `run_config`, never typed.",
    ],
    referenceSolution: `DELETE FROM stg_orders_daily;

INSERT INTO stg_orders_daily (order_id, dt, customer_id, amount_usd)
SELECT order_id, dt, customer_id, amount_usd
FROM (
  SELECT s.order_id,
         date(s.updated_at) AS dt,
         s.customer_id,
         s.amount_usd,
         ROW_NUMBER() OVER (PARTITION BY s.order_id ORDER BY s.updated_at DESC) AS rn
  FROM src_orders s
  WHERE date(s.updated_at) = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily')
    AND s.status <> 'cancelled'
)
WHERE rn = 1;

DELETE FROM fct_orders_daily
WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily');

INSERT INTO fct_orders_daily (order_id, dt, customer_id, amount_usd)
SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily;

INSERT INTO pipeline_audit_log (pipeline, run_date, table_name, rows_loaded)
SELECT 'orders_daily',
       (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily'),
       'fct_orders_daily',
       (SELECT COUNT(*) FROM stg_orders_daily);`,
    seedSql: DAILY_PIPELINE_SEED,
    checkIdempotency: true,
    idempotencyTables: ["stg_orders_daily", "fct_orders_daily"],
    assertions: [
      {
        suite: "stage",
        name: "staging holds exactly the deduped non-cancelled run_date rows",
        sql: `WITH expected(order_id, dt, customer_id, amount_usd) AS (
  VALUES (8110, '2026-03-14', 410, 130.00),
         (8112, '2026-03-14', 412, 275.00),
         (8113, '2026-03-14', 413,  48.25),
         (8115, '2026-03-14', 415, 210.50)
)
SELECT * FROM (SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily)`,
      },
      {
        suite: "stage",
        name: "staging has no duplicate order_id",
        sql: `SELECT order_id FROM stg_orders_daily GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "load",
        name: "the run_date partition of the fact equals staging",
        sql: `SELECT order_id FROM (
  SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily
  EXCEPT
  SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-14'
)
UNION ALL
SELECT order_id FROM (
  SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-14'
  EXCEPT
  SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily
)`,
      },
      {
        suite: "load",
        name: "the 2026-03-13 partition was left untouched",
        isHidden: true,
        sql: `WITH untouched(order_id, dt, customer_id, amount_usd) AS (
  VALUES (8105, '2026-03-13', 405, 310.25),
         (8106, '2026-03-13', 406,  88.00),
         (8107, '2026-03-13', 407, 145.75),
         (8108, '2026-03-13', 408,  62.40),
         (8109, '2026-03-13', 409, 199.00)
)
SELECT * FROM (SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-13' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-13')`,
      },
      {
        suite: "load",
        name: "the stale 999.00 row and the cancelled order are gone from the fact",
        isHidden: true,
        sql: `SELECT order_id FROM fct_orders_daily
WHERE (order_id = 8110 AND amount_usd = 999.00) OR order_id = 8111`,
      },
      {
        suite: "audit",
        name: "every audit row records the same run and the right rows_loaded",
        sql: `SELECT 1 WHERE (
  SELECT COUNT(DISTINCT pipeline || '|' || run_date || '|' || table_name || '|' || rows_loaded)
  FROM pipeline_audit_log
) <> 1`,
      },
      {
        suite: "audit",
        name: "the audit row names this run and counts what was loaded",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM pipeline_audit_log
  WHERE pipeline = 'orders_daily' AND run_date = '2026-03-14'
    AND table_name = 'fct_orders_daily' AND rows_loaded = 4) < 1`,
      },
    ],
  }),
  practice: scriptExercise({
    id: "de-l8-daily-pipeline-rehearsal-practice",
    prompt: `Write a script that leaves \`stg_orders_daily\` and \`fct_orders_daily\` correct for the \`run_config\` run date and appends one \`pipeline_audit_log\` row, given a source extract that redelivers the previous run's rows.

No steps are given this time. The goal state is: staging holds exactly the run date's non-cancelled orders, one row per \`order_id\` with the newest \`updated_at\` winning; the fact's run-date partition matches staging; every other partition of the fact is unchanged; and the audit log gains one row naming this run and the number of rows loaded. The grader checks that goal state, then runs your script a second time and checks that \`stg_orders_daily\` and \`fct_orders_daily\` are unchanged.`,
    starterCode: `-- Leave the goal state correct, twice.
`,
    hints: [],
    seedSql: DAILY_PIPELINE_REDELIVERY_SEED,
    checkIdempotency: true,
    idempotencyTables: ["stg_orders_daily", "fct_orders_daily"],
    assertions: [
      {
        suite: "stage",
        name: "staging holds exactly the run date's deduped non-cancelled orders",
        sql: `WITH expected(order_id, dt, customer_id, amount_usd) AS (
  VALUES (8116, '2026-03-15', 416,  84.00),
         (8118, '2026-03-15', 418, 302.00),
         (8119, '2026-03-15', 419,  67.75),
         (8120, '2026-03-15', 420, 143.40),
         (8122, '2026-03-15', 422, 228.60)
)
SELECT * FROM (SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily)`,
      },
      {
        suite: "stage",
        name: "staging has no duplicate order_id",
        sql: `SELECT order_id FROM stg_orders_daily GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "stage",
        name: "the redelivered previous day did not leak into staging",
        isHidden: true,
        sql: `SELECT order_id FROM stg_orders_daily WHERE dt <> '2026-03-15'`,
      },
      {
        suite: "load",
        name: "the run date partition of the fact equals staging",
        sql: `SELECT order_id FROM (
  SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily
  EXCEPT
  SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-15'
)
UNION ALL
SELECT order_id FROM (
  SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-15'
  EXCEPT
  SELECT order_id, dt, customer_id, amount_usd FROM stg_orders_daily
)`,
      },
      {
        suite: "load",
        name: "the previous day's partition is unchanged",
        isHidden: true,
        sql: `WITH untouched(order_id, dt, customer_id, amount_usd) AS (
  VALUES (8110, '2026-03-14', 410, 130.00),
         (8112, '2026-03-14', 412, 275.00),
         (8113, '2026-03-14', 413,  48.25),
         (8115, '2026-03-14', 415, 210.50)
)
SELECT * FROM (SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-14' EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT order_id, dt, customer_id, amount_usd FROM fct_orders_daily WHERE dt = '2026-03-14')`,
      },
      {
        suite: "audit",
        name: "the previous run's audit row survived and this run added its own",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM pipeline_audit_log
  WHERE pipeline = 'orders_daily' AND run_date = '2026-03-14' AND rows_loaded = 4) <> 1
UNION ALL
SELECT 1 WHERE (SELECT COUNT(*) FROM pipeline_audit_log
  WHERE pipeline = 'orders_daily' AND run_date = '2026-03-15'
    AND table_name = 'fct_orders_daily' AND rows_loaded = 5) < 1`,
      },
      {
        suite: "audit",
        name: "no audit row reports a count that disagrees with the run it names",
        isHidden: true,
        sql: `SELECT run_date FROM pipeline_audit_log a
WHERE a.rows_loaded <> (SELECT COUNT(*) FROM fct_orders_daily f WHERE f.dt = a.run_date)`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-daily-pipeline-rehearsal-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every run in the audit log with what it loaded and how that compares to the run before it, as \`(run_date, rows_loaded, delta_vs_previous)\`, newest run first, over \`pipeline_audit_log\`.

\`delta_vs_previous\` is this run's \`rows_loaded\` minus the previous run's, ordered by \`run_date\`, and it is NULL for the oldest run. This is the volume check that catches a green run which wrote nothing.`,
      starterCode: `-- Volume against the task's own history: the cheapest silent-success detector there is.
SELECT
FROM pipeline_audit_log
ORDER BY run_date DESC;`,
      hints: [
        "`LAG(rows_loaded) OVER (ORDER BY run_date)` gives the previous run's count in run order.",
        "Subtract it from `rows_loaded`; the oldest row has no previous value, so the delta is NULL there, which is correct.",
        "Compute the window in run order, then sort the output newest first.",
      ],
      referenceSolution: `SELECT run_date,
       rows_loaded,
       rows_loaded - LAG(rows_loaded) OVER (ORDER BY run_date) AS delta_vs_previous
FROM pipeline_audit_log
ORDER BY run_date DESC;`,
      singleFile: {
        seedSql: AUDIT_HISTORY_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["run_date", "rows_loaded", "delta_vs_previous"],
          rows: [
            ["2026-03-14", 486, -21],
            ["2026-03-13", 507, 507],
            ["2026-03-12", 0, -498],
            ["2026-03-11", 498, 67],
            ["2026-03-10", 431, -24],
            ["2026-03-09", 455, 43],
            ["2026-03-08", 412, null],
          ],
        },
      },
    },
    {
      id: "de-l8-daily-pipeline-rehearsal-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the fact partitions no tracked run ever claimed, as \`(dt, fact_rows)\`, oldest first, over \`fct_orders_daily\` and \`pipeline_audit_log\`.

A partition is unclaimed when a \`dt\` exists in \`fct_orders_daily\` but no \`pipeline_audit_log\` row has that \`run_date\`. \`fact_rows\` is how many rows the fact holds for it. This reconciliation is how you find data that arrived through someone's hand-run script during an incident.`,
      starterCode: `-- Did every partition in the fact come from a run we can account for?
SELECT
FROM fct_orders_daily f
GROUP BY f.dt
ORDER BY f.dt;`,
      hints: [
        "Group the fact by `dt` first so each partition is one row with its own count.",
        "The anti-join is `NOT EXISTS (SELECT 1 FROM pipeline_audit_log a WHERE a.run_date = f.dt)`, which reads better here than `NOT IN` because the audit log could hold a NULL run_date.",
        "Two partitions survive, one at each end of the tracked range.",
      ],
      referenceSolution: `SELECT f.dt, COUNT(*) AS fact_rows
FROM fct_orders_daily f
WHERE NOT EXISTS (SELECT 1 FROM pipeline_audit_log a WHERE a.run_date = f.dt)
GROUP BY f.dt
ORDER BY f.dt;`,
      singleFile: {
        seedSql: AUDIT_HISTORY_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dt", "fact_rows"],
          rows: [
            ["2026-03-07", 1],
            ["2026-03-15", 1],
          ],
        },
      },
    },
  ],
}

export const level8Module3: SqlModule = {
  id: "de-l8-incremental-backfills",
  title: "Module 8.3: Incremental Loads, Late Data & Backfills",
  description:
    "The half of incremental loading the shipped SQL lessons stop short of: quantifying the rows a strict watermark silently dropped before you fix anything, healing them with a bounded rolling window, running a manifest-driven backfill that also rebuilds the downstream aggregate it invalidated, and composing the whole daily pipeline into one script you can defend out loud.",
  lessons: [watermarkControlTableReview, lateDataAudit, backfills, dailyPipelineRehearsal],
}
