/**
 * Data Engineering Level 8, Module 8.2 — Idempotency, the Core Property.
 *
 * The spine of the level (RESEARCH.md finding 6 / §5.3). Every 2025-2026 source converges on
 * the same three idempotent-write implementations, and this module grades all three the only
 * honest way: by literally running the learner's script twice and asserting the promised tables
 * are unchanged (`checkIdempotency: true` with `idempotencyTables` naming exactly what must be
 * byte-stable).
 *
 * Deliberately NOT a reteach. `sql-l4-idempotent-merge` already taught the upsert and the
 * run-twice test, `sql-l5-cdc-changelog-apply` already taught the latest-per-key merge with
 * tombstones, and `sql-l5-incremental-watermark-backfill` already taught partition overwrite.
 * Each lesson names that prior art out loud in its first paragraph and then grades only what is
 * new: the run parameter injected by the orchestrator instead of the wall clock (8.2.1), the
 * in-batch duplicate whose ordering column TIES plus at-least-once redelivery of an
 * already-applied batch (8.2.2), and the append-only Bronze whose idempotency contract is scoped
 * to the projection rather than the raw table (8.2.3).
 *
 * Runtime constraint (binding): all grading runs on sql.js SQLite, which has no `MERGE` keyword.
 * Merge semantics are graded with `INSERT ... ON CONFLICT(key) DO UPDATE` plus a keyed `DELETE`;
 * real `MERGE INTO` appears in prose callouts only.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and every
 * workspace reference was executed against its own hidden assertions including the idempotency
 * double-run. Content rules: no em dashes in learner prose; every prompt leads with the
 * deliverable.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"
import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 8.2.1 seeds — a partitioned warehouse fact plus the run parameter the orchestrator
// injects. `run_config` stands in for the logical date Airflow hands a task; nothing in the
// graded script may read a wall clock.
// ---------------------------------------------------------------------------

/** The day's extract off the source system. One partition date per run, by contract. */
const BATCH_ORDERS_SEED = `CREATE TABLE batch_orders (
  order_id    TEXT,
  dt          TEXT,     -- the partition date this extract is FOR, not when it was pulled
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO batch_orders (order_id, dt, customer_id, amount_usd) VALUES
  ('O-3141', '2026-03-14', 501,  84.50),
  ('O-3142', '2026-03-14', 502, 129.95),
  ('O-3143', '2026-03-14', 503,  46.20),
  ('O-3144', '2026-03-14', 501,  73.10),
  ('O-3145', '2026-03-14', 504, 218.40),
  ('O-3146', '2026-03-14', 505,  61.75);`

/**
 * The target fact, holding a clean 2026-03-13 partition, wreckage from a partial 2026-03-14 run
 * (O-3141 carries a stale amount, and O-3199 was cancelled at the source, so a correct
 * replacement has to remove a row the batch never mentions), and an already-loaded 2026-03-15.
 *
 * MAP DEVIATION: the map specifies only the 2026-03-13 and stale 2026-03-14 rows. The later
 * 2026-03-15 partition is added because without it the over-wide `dt >= run_date` delete the
 * teach text warns about produces a correct table and the exercise would grade nothing.
 */
const FCT_ORDERS_SEED = `CREATE TABLE fct_orders (
  order_id    TEXT,
  dt          TEXT,     -- the partition column; a run owns exactly one value of it
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO fct_orders (order_id, dt, customer_id, amount_usd) VALUES
  ('O-3101', '2026-03-13', 501,  55.00),
  ('O-3102', '2026-03-13', 502, 140.25),
  ('O-3103', '2026-03-13', 503,  22.80),
  ('O-3104', '2026-03-13', 506,  97.60),
  ('O-3105', '2026-03-13', 507,  33.15),
  ('O-3141', '2026-03-14', 501,  80.00),
  ('O-3199', '2026-03-14', 509,  12.00),
  ('O-3181', '2026-03-15', 502, 112.30),
  ('O-3182', '2026-03-15', 508,  59.45),
  ('O-3183', '2026-03-15', 503, 174.00);`

/** The parameter row. On a real platform this is the orchestrator's logical date, not a table. */
const RUN_CONFIG_SEED = `CREATE TABLE run_config (
  pipeline TEXT,
  run_date TEXT      -- the data interval the orchestrator injected for THIS run
);
INSERT INTO run_config (pipeline, run_date) VALUES
  ('orders_daily', '2026-03-14');`

/** The same fact after 2026-03-14 loaded correctly, used as the source for the rollup rebuild. */
const FCT_ORDERS_LOADED_SEED = `CREATE TABLE fct_orders (
  order_id    TEXT,
  dt          TEXT,
  customer_id INTEGER,
  amount_usd  REAL
);
INSERT INTO fct_orders (order_id, dt, customer_id, amount_usd) VALUES
  ('O-3101', '2026-03-13', 501,  55.00),
  ('O-3102', '2026-03-13', 502, 140.25),
  ('O-3103', '2026-03-13', 503,  22.80),
  ('O-3104', '2026-03-13', 506,  97.60),
  ('O-3105', '2026-03-13', 507,  33.15),
  ('O-3141', '2026-03-14', 501,  84.50),
  ('O-3142', '2026-03-14', 502, 129.95),
  ('O-3143', '2026-03-14', 503,  46.20),
  ('O-3144', '2026-03-14', 501,  73.10),
  ('O-3145', '2026-03-14', 504, 218.40),
  ('O-3146', '2026-03-14', 505,  61.75),
  ('O-3181', '2026-03-15', 502, 112.30),
  ('O-3182', '2026-03-15', 508,  59.45),
  ('O-3183', '2026-03-15', 503, 174.00);`

/**
 * The downstream rollup. No primary key on `dt` on purpose: a blind INSERT must be able to
 * duplicate the day, otherwise the exercise would grade the schema instead of the loader. The
 * 2026-03-15 row is already correct and sits AFTER the run's date, so an over-wide delete range
 * destroys it.
 *
 * The 2026-03-12 row is the one a full rebuild cannot fake: its order rows have already aged out
 * of `fct_orders` retention, so recomputing every date from the fact drops it. Without that row,
 * `DELETE FROM fct_daily_revenue;` plus a full recompute reproduces the other dates exactly and
 * the "leave every other date alone" requirement would grade nothing.
 */
const FCT_DAILY_REVENUE_SEED = `CREATE TABLE fct_daily_revenue (
  dt          TEXT,
  order_count INTEGER,
  revenue_usd REAL
);
INSERT INTO fct_daily_revenue (dt, order_count, revenue_usd) VALUES
  ('2026-03-12', 4, 201.40),
  ('2026-03-13', 5, 348.80),
  ('2026-03-14', 2,  92.00),
  ('2026-03-15', 3, 345.75);`

/** The broken loader's output: a blind append ran twice, so 2026-03-14 is in there twice. */
const FCT_ORDERS_APPENDED_SEED = `CREATE TABLE fct_orders_appended (
  order_id   TEXT,
  dt         TEXT,
  amount_usd REAL
);
INSERT INTO fct_orders_appended (order_id, dt, amount_usd) VALUES
  ('O-3101', '2026-03-13',  55.00),
  ('O-3102', '2026-03-13', 140.25),
  ('O-3103', '2026-03-13',  22.80),
  ('O-3104', '2026-03-13',  97.60),
  ('O-3105', '2026-03-13',  33.15),
  ('O-3141', '2026-03-14',  84.50),
  ('O-3142', '2026-03-14', 129.95),
  ('O-3143', '2026-03-14',  46.20),
  ('O-3144', '2026-03-14',  73.10),
  ('O-3145', '2026-03-14', 218.40),
  ('O-3146', '2026-03-14',  61.75),
  ('O-3141', '2026-03-14',  84.50),
  ('O-3142', '2026-03-14', 129.95),
  ('O-3143', '2026-03-14',  46.20),
  ('O-3144', '2026-03-14',  73.10),
  ('O-3145', '2026-03-14', 218.40),
  ('O-3146', '2026-03-14',  61.75);`

/** A two-column partition key. The batch carries other regions this run does not own. */
const REGION_ORDERS_SEED = `CREATE TABLE batch_region_orders (
  order_id   TEXT,
  dt         TEXT,
  region     TEXT,     -- the second partition column; a run owns one (dt, region) cell
  amount_usd REAL
);
INSERT INTO batch_region_orders (order_id, dt, region, amount_usd) VALUES
  ('R-7001', '2026-03-14', 'us-east', 120.00),
  ('R-7002', '2026-03-14', 'us-east',  64.40),
  ('R-7003', '2026-03-14', 'us-east', 210.75),
  ('R-7004', '2026-03-14', 'us-east',  38.90),
  ('R-7101', '2026-03-14', 'eu-west',  99.00),
  ('R-7102', '2026-03-14', 'eu-west', 150.50);

CREATE TABLE fct_region_orders (
  order_id   TEXT,
  dt         TEXT,
  region     TEXT,
  amount_usd REAL
);
INSERT INTO fct_region_orders (order_id, dt, region, amount_usd) VALUES
  ('R-6901', '2026-03-13', 'us-east',  45.00),
  ('R-6902', '2026-03-13', 'us-east',  88.25),
  ('R-7001', '2026-03-14', 'us-east', 100.00),
  ('R-7099', '2026-03-14', 'us-east',  17.50),
  ('R-7051', '2026-03-14', 'eu-west',  70.00),
  ('R-7052', '2026-03-14', 'eu-west', 133.30),
  ('R-7201', '2026-03-15', 'us-east',  52.65),
  ('R-7202', '2026-03-15', 'us-east', 143.80);

CREATE TABLE run_config_region (
  pipeline TEXT,
  run_date TEXT,
  region   TEXT
);
INSERT INTO run_config_region (pipeline, run_date, region) VALUES
  ('region_orders_daily', '2026-03-14', 'us-east');`

// ---------------------------------------------------------------------------
// Lesson 8.2.2 seeds — a CDC-fed dimension under at-least-once redelivery. The ordering column
// only has second resolution, so it ties, and the previous batch arrives again alongside the new
// rows. Both pressures are the point of the lesson.
// ---------------------------------------------------------------------------

const CUSTOMER_CHANGES_SEED = `CREATE TABLE stg_customer_changes (
  change_id   INTEGER,  -- monotonic within the feed; the tiebreaker when changed_at repeats
  customer_id INTEGER,
  op          TEXT,     -- 'c' create, 'u' update, 'd' delete (the CDC envelope shape)
  name        TEXT,
  tier        TEXT,
  changed_at  TEXT      -- source commit time at SECOND resolution, so two changes can tie
);
-- The file arrives in delivery order, which is NOT change_id order (104 lands before 103, 111
-- before 110), so nothing may lean on the row order you happen to see. Three traps are seeded on
-- purpose: customer 42's tie is stored oldest-first, so an ordering without change_id picks the
-- wrong row; customer 88 is deleted and then re-created, so "this key has a 'd' in the batch" is
-- the wrong delete test; and customer 22 has a tie (114, 115) that is NOT their latest change,
-- because 116 lands later, so "shares a timestamp with anyone" and "shares the LATEST timestamp"
-- give different answers.
--
-- MAP DEVIATION: the map specifies 11 rows. Customer 88's delete-then-recreate pair (112, 113)
-- is added because with the map's rows exactly, a no-dedup upsert plus a delete-on-any-'d'
-- produces the correct dimension by luck and passes every assertion. Customer 22's (114, 115,
-- 116) run is added because without a tie that loses to a later change, drill 2 is solvable with
-- a plain GROUP BY customer_id, changed_at and never needs a window function.
INSERT INTO stg_customer_changes (change_id, customer_id, op, name, tier, changed_at) VALUES
  (101, 11, 'u', 'Ada Lovelace',      'gold',     '2026-03-13 09:00:00'),
  (102, 22, 'u', 'Grace Hopper',      'silver',   '2026-03-13 09:05:00'),
  (104, 55, 'c', 'Jean Bartik',       'bronze',   '2026-03-13 09:20:00'),
  (103, 33, 'c', 'Alan Turing',       'bronze',   '2026-03-13 09:10:00'),
  (105, 42, 'u', 'Katherine Johnson', 'gold',     '2026-03-14 08:30:00'),
  (106, 42, 'u', 'Katherine Johnson', 'platinum', '2026-03-14 08:30:00'),
  (108, 66, 'c', 'Dorothy Vaughan',   'silver',   '2026-03-14 08:45:00'),
  (107, 77, 'c', 'Mary Jackson',      'bronze',   '2026-03-14 08:40:00'),
  (109, 55, 'u', 'Jean Bartik',       'silver',   '2026-03-14 08:50:00'),
  (111, 33, 'd', NULL,                NULL,       '2026-03-14 09:00:00'),
  (110, 77, 'd', NULL,                NULL,       '2026-03-14 08:55:00'),
  (112, 88, 'd', NULL,                NULL,       '2026-03-14 09:05:00'),
  (113, 88, 'c', 'Annie Easley',      'gold',     '2026-03-14 09:10:00'),
  (114, 22, 'u', 'Grace Hopper',      'gold',     '2026-03-14 09:15:00'),
  (115, 22, 'u', 'Grace Hopper',      'platinum', '2026-03-14 09:15:00'),
  (116, 22, 'u', 'Grace Hopper',      'silver',   '2026-03-14 09:20:00');

CREATE TABLE dim_customer (
  customer_id INTEGER PRIMARY KEY,
  name        TEXT,
  tier        TEXT,
  updated_at  TEXT
);
-- Customer 99 has no row anywhere in the change batch. A merge touches only the keys the batch
-- carries, so 99 has to come out exactly as it went in. Truncating the dimension and reloading
-- the deduped winners loses this customer, which is the difference between an upsert and a
-- replace and the reason this row exists.
INSERT INTO dim_customer (customer_id, name, tier, updated_at) VALUES
  (11, 'Ada Lovelace',      'gold',   '2026-03-13 09:00:00'),
  (22, 'Grace Hopper',      'silver', '2026-03-13 09:05:00'),
  (33, 'Alan Turing',       'bronze', '2026-03-13 09:10:00'),
  (42, 'Katherine Johnson', 'silver', '2026-03-13 09:15:00'),
  (55, 'Jean Bartik',       'bronze', '2026-03-13 09:20:00'),
  (88, 'Annie Easley',      'bronze', '2026-03-13 09:25:00'),
  (99, 'Radia Perlman',     'silver', '2026-03-12 11:00:00');`

const PRODUCT_FEED_SEED = `CREATE TABLE stg_product_prices (
  feed_id      INTEGER,  -- position in the feed file; the tiebreaker when feed_ts repeats
  sku          TEXT,
  op           TEXT,     -- 'c' create, 'u' update, 'd' discontinue
  product_name TEXT,
  price_usd    REAL,
  feed_ts      TEXT      -- vendor feed timestamp; the vendor stamps a whole batch identically
);
-- Delivery order, not feed_id order (203 lands before 202). SKU-100's tie is stored oldest-first
-- and SKU-500 is discontinued and then relisted, so both traps from the apply are here too.
INSERT INTO stg_product_prices (feed_id, sku, op, product_name, price_usd, feed_ts) VALUES
  (201, 'SKU-100', 'c', 'Cold Brew 1L',          14.99, '2026-03-13 06:00:00'),
  (203, 'SKU-300', 'c', 'Filter Papers',          6.25, '2026-03-13 06:00:00'),
  (202, 'SKU-200', 'c', 'Espresso Beans',        22.50, '2026-03-13 06:00:00'),
  (204, 'SKU-100', 'u', 'Cold Brew 1L',          19.99, '2026-03-14 06:00:00'),
  (205, 'SKU-100', 'u', 'Cold Brew 1L',          17.49, '2026-03-14 06:00:00'),
  (206, 'SKU-400', 'c', 'Travel Mug',            28.00, '2026-03-14 06:05:00'),
  (207, 'SKU-200', 'd', NULL,                    NULL,  '2026-03-14 06:10:00'),
  (208, 'SKU-500', 'd', NULL,                    NULL,  '2026-03-14 06:15:00'),
  (209, 'SKU-500', 'c', 'Pour Over Kettle 1.2L', 47.50, '2026-03-14 06:20:00');

CREATE TABLE dim_product (
  sku          TEXT PRIMARY KEY,
  product_name TEXT,
  price_usd    REAL,
  updated_at   TEXT
);
-- SKU-700 is not in the feed at all. The vendor sends only the SKUs that changed, so a merge has
-- to leave it exactly as it is; a wipe-and-reload of the deduped winners silently delists it.
INSERT INTO dim_product (sku, product_name, price_usd, updated_at) VALUES
  ('SKU-100', 'Cold Brew 1L',     14.99, '2026-03-13 06:00:00'),
  ('SKU-200', 'Espresso Beans',   22.50, '2026-03-13 06:00:00'),
  ('SKU-300', 'Filter Papers',     6.25, '2026-03-13 06:00:00'),
  ('SKU-500', 'Pour Over Kettle', 42.00, '2026-03-13 06:00:00'),
  ('SKU-700', 'Burr Grinder',     89.00, '2026-03-12 06:00:00');`

// ---------------------------------------------------------------------------
// Lesson 8.2.3 seeds — an append-only landing zone fed by an at-least-once delivery, plus the
// deduped projection built on top of it. Bronze grows on every run by design, which is exactly
// why the idempotency contract has to be scoped to the projection.
// ---------------------------------------------------------------------------

const EVENTS_BRONZE_SEED = `CREATE TABLE events_bronze (
  event_id     TEXT,
  event_ts     TEXT,
  ingested_at  TEXT,   -- when the loader landed THIS copy; a redelivery lands later
  source_file  TEXT,   -- the delivery file, which the producer can send more than once
  payload_json TEXT
);
-- E-1003 arrives twice inside the SAME load, in two files the loader stamped with one
-- ingested_at, and the two copies disagree on ms. That is a genuine tie: ORDER BY ingested_at
-- DESC alone can return either payload, so only the source_file tiebreaker decides it. The
-- losing copy is stored first, the same oldest-first trap the merge lesson uses, so an ordering
-- without the tiebreaker picks the wrong row rather than the right one by accident.
INSERT INTO events_bronze (event_id, event_ts, ingested_at, source_file, payload_json) VALUES
  ('E-1001', '2026-03-14 00:05:00', '2026-03-14 01:00:00', 'events-0140.json', '{"page":"/home","ms":120}'),
  ('E-1002', '2026-03-14 00:07:00', '2026-03-14 01:00:00', 'events-0140.json', '{"page":"/pricing","ms":90}'),
  ('E-1003', '2026-03-14 01:02:00', '2026-03-14 02:00:00', 'events-0141.json', '{"page":"/docs","ms":200}'),
  ('E-1003', '2026-03-14 01:02:00', '2026-03-14 02:00:00', 'events-0141b.json', '{"page":"/docs","ms":215}'),
  ('E-1004', '2026-03-14 01:06:00', '2026-03-14 02:00:00', 'events-0141.json', '{"page":"/signup","ms":300}'),
  ('E-1005', '2026-03-14 02:03:00', '2026-03-14 03:00:00', 'events-0142.json', '{"page":"/home","ms":95}'),
  ('E-1006', '2026-03-14 02:08:00', '2026-03-14 03:00:00', 'events-0142.json', '{"page":"/docs","ms":0}'),
  ('E-1007', '2026-03-14 02:11:00', '2026-03-14 03:00:00', 'events-0142.json', '{"page":"/pricing","ms":260}'),
  ('E-1005', '2026-03-14 02:03:00', '2026-03-14 04:30:00', 'events-0142.json', '{"page":"/home","ms":95}'),
  ('E-1006', '2026-03-14 02:08:00', '2026-03-14 04:30:00', 'events-0142.json', '{"page":"/docs","ms":150}'),
  ('E-1007', '2026-03-14 02:11:00', '2026-03-14 04:30:00', 'events-0142.json', '{"page":"/pricing","ms":260}');`

const EVENTS_BATCH_SEED = `CREATE TABLE events_batch (
  event_id     TEXT,
  event_ts     TEXT,
  ingested_at  TEXT,
  source_file  TEXT,
  payload_json TEXT
);
INSERT INTO events_batch (event_id, event_ts, ingested_at, source_file, payload_json) VALUES
  ('E-1007', '2026-03-14 02:11:00', '2026-03-14 05:00:00', 'events-0143.json', '{"page":"/pricing","ms":240}'),
  ('E-1008', '2026-03-14 04:12:00', '2026-03-14 05:00:00', 'events-0143.json', '{"page":"/home","ms":115}'),
  ('E-1009', '2026-03-14 04:20:00', '2026-03-14 05:00:00', 'events-0143.json', '{"page":"/docs","ms":180}'),
  ('E-1010', '2026-03-14 04:31:00', '2026-03-14 05:00:00', 'events-0143.json', '{"page":"/blog","ms":75}');

CREATE TABLE events_silver (
  event_id     TEXT,
  event_ts     TEXT,
  payload_json TEXT
);`

const PAGE_VIEWS_SEED = `CREATE TABLE raw_page_views (
  view_id     TEXT,
  viewed_at   TEXT,
  ingested_at TEXT,   -- a corrected redelivery of the same view_id lands later
  source_file TEXT,
  path        TEXT
);
-- V-2004 lands twice inside one load, from two files stamped with the same ingested_at and
-- disagreeing on path. The losing copy is stored first, so an ordering without the source_file
-- tiebreaker resolves the tie the wrong way instead of getting lucky.
INSERT INTO raw_page_views (view_id, viewed_at, ingested_at, source_file, path) VALUES
  ('V-2001', '2026-03-14 00:10:00', '2026-03-14 01:00:00', 'pv-0071.json', '/home'),
  ('V-2002', '2026-03-14 00:14:00', '2026-03-14 01:00:00', 'pv-0071.json', '/pricing'),
  ('V-2003', '2026-03-14 00:22:00', '2026-03-14 01:00:00', 'pv-0071.json', '/docs'),
  ('V-2004', '2026-03-14 01:05:00', '2026-03-14 02:00:00', 'pv-0072.json', '/home'),
  ('V-2004', '2026-03-14 01:05:00', '2026-03-14 02:00:00', 'pv-0072b.json', '/home/spring-sale'),
  ('V-2005', '2026-03-14 01:19:00', '2026-03-14 02:00:00', 'pv-0072.json', '/blog'),
  ('V-2006', '2026-03-14 01:31:00', '2026-03-14 02:00:00', 'pv-0072.json', '/docs'),
  ('V-2005', '2026-03-14 01:19:00', '2026-03-14 03:30:00', 'pv-0072.json', '/blog/launch'),
  ('V-2006', '2026-03-14 01:31:00', '2026-03-14 03:30:00', 'pv-0072.json', '/docs');

CREATE TABLE page_view_batch (
  view_id     TEXT,
  viewed_at   TEXT,
  ingested_at TEXT,
  source_file TEXT,
  path        TEXT
);
INSERT INTO page_view_batch (view_id, viewed_at, ingested_at, source_file, path) VALUES
  ('V-2006', '2026-03-14 01:31:00', '2026-03-14 04:00:00', 'pv-0073.json', '/docs/intro'),
  ('V-2007', '2026-03-14 02:40:00', '2026-03-14 04:00:00', 'pv-0073.json', '/home'),
  ('V-2008', '2026-03-14 02:55:00', '2026-03-14 04:00:00', 'pv-0073.json', '/pricing'),
  ('V-2003', '2026-03-14 00:22:00', '2026-03-14 04:00:00', 'pv-0073.json', '/docs');

CREATE TABLE fct_page_views (
  view_id   TEXT,
  viewed_at TEXT,
  path      TEXT
);`

// ---------------------------------------------------------------------------
// Module 8.2 — Idempotency, the Core Property
// ---------------------------------------------------------------------------

const partitionReplacement: SqlLesson = {
  id: "de-l8-partition-replacement",
  title: "Delete + Insert: Replacing the Run's Partition",
  summary:
    "Write a batch load that owns exactly one date partition, driven by a run parameter instead of the wall clock, and prove it survives a rerun.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "idempotency",
    "partition replacement",
    "run parameterization",
    "immutable data interval",
    "DELETE scoped by predicate",
    "INSERT...SELECT",
    "multi-statement scripts",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The property, and the sentence that carries it

A load is **idempotent** when running it twice leaves the table exactly as running it once did. That single property is what makes retries, backfills, and late-data reconciliation safe, and it is why every distributed-systems answer in a data interview eventually lands on the same sentence:

> True exactly-once delivery is impossible. **At-least-once delivery plus an idempotent sink equals effectively exactly-once.**

You cannot stop a queue, a scheduler, or an on-call engineer from delivering the same batch twice. You can make the sink not care. There are exactly three implementations, and this module grades all three. The first one is the one you reach for first.

## Implementation 1: delete the partition, then insert it

The simplest idempotent pattern that works on every engine ever built:

1. \`DELETE\` every row of the target belonging to this run's partition.
2. \`INSERT ... SELECT\` that partition fresh from the batch.

The run **owns** the partition. Whatever was there before is gone, whether it was correct, half-written, or stale. Two runs of the same script land the same rows because the delete wipes the first run's output before the second one writes.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "run_config", "note": "run_date = 2026-03-14, injected" },
    { "label": "DELETE dt", "note": "wipe the run's partition" },
    { "label": "INSERT dt", "note": "write it fresh from the batch" },
    { "label": "fct_orders", "note": "the partition is owned, not appended to" }
  ],
  "caption": "Delete-then-insert makes the run own its partition, so a second run overwrites the first instead of stacking on it."
}
\`\`\`

You have written this mechanic before. In \`sql-l5-incremental-watermark-backfill\` you deleted a \`load_date\` range and reinserted it, and the partition date was typed into the SQL as a literal. That is the part this lesson replaces.

## The date is a parameter, never a clock

The single most damaging anti-pattern in pipeline code is reading the wall clock. \`datetime.now()\`, \`CURRENT_DATE\`, or a hardcoded \`'today'\` inside pipeline logic means:

- A **rerun** of yesterday's failed job processes today instead, silently.
- A **backfill** of March cannot work at all, because every run computes June.
- The same code produces a different answer depending on when it happened to execute.

The fix is that the run's date is an input. The orchestrator computes the data interval for the run and injects it, and the job reads it from there. In this lesson that injection is a \`run_config(pipeline, run_date)\` row, and your script reads \`run_date\` out of it. In Airflow it is the logical date passed into the task. In a warehouse job it is a bound parameter. The shape is always the same: **the run is responsible for a time range, and something outside the job tells it which one.**

That is also what makes the load re-runnable at all. A run bound to an immutable data interval produces the same output every time you run it, which is the precondition idempotency is built on.

Nothing can catch this failure for you by looking at output. A script with the date typed into it returns the correct partition on the day it was written, and on every rerun of that same day, which is why the exercises below cannot detect a literal either. The bug only surfaces the first time the run's date is not the date you typed, and by then it is a backfill that silently wrote the wrong day. Reading the parameter is a habit, not a test you can pass.

## Atomicity, and where the boundaries go

The delete and the insert are one logical unit. If the delete lands and the insert fails, the partition is empty, which is worse than stale. Warehouses give you a transaction or an atomic \`INSERT OVERWRITE\` for this. The task boundary rule that goes with it is to keep extract, transform, and load in **separate, independently re-runnable tasks**, so a failure in one does not force you to redo the expensive ones.

**Common mistake:** deleting by a filter that is wider than what you insert. \`DELETE FROM fct_orders WHERE dt >= '2026-03-14'\` followed by an insert of one day quietly destroys every later partition. The delete predicate and the insert predicate must describe the same partition, which is why both should read the same parameter.

**Interview nuance:** when an interviewer says "make this backfill safe to rerun," lead with the sentence, then name delete-plus-insert as the implementation you reach for first, then say the date comes from the orchestrator and never from the clock. The delete itself is table stakes. The parameter is the detail that reads as production experience.

\`\`\`cswidget
{
  "type": "check",
  "kind": "predict",
  "id": "double-run-triage",
  "prompt": "Your daily orders job double-ran last night: the scheduler retried a task that had actually succeeded. This morning revenue for 2026-03-14 is exactly double. What do you do first?",
  "options": [
    {
      "label": "Write a one-off DELETE that removes the extra copies by hand, then move on.",
      "feedback": "Tempting under pressure, and it is how partitions get silently corrupted. A hand-written delete has no test, no record, and no way to tell an original row from its copy when the rows are identical."
    },
    {
      "label": "Re-run the idempotent load for the 2026-03-14 partition and let it replace the day, then fix the loader so a double run cannot double the data.",
      "correct": true,
      "feedback": "Right. The replacement is the repair: it deletes the partition and rewrites it from the batch, so one run of it produces the correct day whatever state the table was in. Then fix the real bug, because a job that cannot survive being run twice is the defect, not the retry."
    },
    {
      "label": "Turn off retries on that task so it can never run twice again.",
      "feedback": "This trades a data bug for an availability bug. Retries exist because transient failures are normal, and at-least-once delivery is a property of the world, not a setting you can switch off."
    },
    {
      "label": "Restore the whole table from last week's backup.",
      "feedback": "Enormously expensive and it throws away six days of correct partitions to fix one. Partition replacement is scoped to the day that is wrong."
    }
  ],
  "reveal": "The four-beat answer interviewers listen for: the blind append doubled the partition; do not repair by hand; re-run the idempotent load for that partition and let it replace the day; then fix the loader, because a job that cannot double-run safely is the bug."
}
\`\`\`

> **On a real platform this differs.** Here you write a \`DELETE\` and an \`INSERT ... SELECT\` against SQLite. Hive, Spark SQL, and Databricks spell the same thing \`INSERT OVERWRITE\` on a partition, Delta Lake spells it \`replaceWhere\`, BigQuery replaces a partition with a WRITE_TRUNCATE load or query against a \`table$YYYYMMDD\` decorator (it has no \`INSERT OVERWRITE\` statement, so the alternative there is \`MERGE\`), Oracle can exchange a prepared partition in as a metadata operation, and Iceberg does it as a snapshot commit. Snowflake is the odd one out: its micro-partitions are automatic and not addressable, so there is nothing to swap at partition level and you replace a whole table with \`CREATE OR REPLACE TABLE ... SWAP WITH\` instead. All of them are delete-plus-insert with the atomicity handled for you. Airflow supplies the \`run_date\` this \`run_config\` row stands in for, as the run's logical date.`,
    demoSeedSql: `CREATE TABLE blind_append (order_id TEXT, dt TEXT, amount_usd REAL);
INSERT INTO blind_append (order_id, dt, amount_usd) VALUES
  ('O-3141', '2026-03-14',  84.50), ('O-3142', '2026-03-14', 129.95), ('O-3143', '2026-03-14', 46.20),
  ('O-3141', '2026-03-14',  84.50), ('O-3142', '2026-03-14', 129.95), ('O-3143', '2026-03-14', 46.20);

CREATE TABLE replaced_partition (order_id TEXT, dt TEXT, amount_usd REAL);
INSERT INTO replaced_partition (order_id, dt, amount_usd) VALUES
  ('O-3141', '2026-03-14',  84.50), ('O-3142', '2026-03-14', 129.95), ('O-3143', '2026-03-14', 46.20);`,
    demoCode: `-- The same three-row batch, loaded twice by each loader. Only one of them is idempotent.
SELECT 'blind append (INSERT only)' AS loader,
       COUNT(*) AS rows_after_two_runs,
       ROUND(SUM(amount_usd), 2) AS revenue_usd
FROM blind_append
UNION ALL
SELECT 'delete + insert the partition',
       COUNT(*),
       ROUND(SUM(amount_usd), 2)
FROM replaced_partition;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "de-l8-partition-replacement-apply",
    prompt: `Write a script that loads \`batch_orders\` into \`fct_orders\` so the run's partition is fully replaced and rerunning the script changes nothing, over \`batch_orders(order_id, dt, customer_id, amount_usd)\`, \`fct_orders(order_id, dt, customer_id, amount_usd)\`, and \`run_config(pipeline, run_date)\`.

Read the partition date from \`run_config\` where \`pipeline = 'orders_daily'\` rather than typing \`'2026-03-14'\`. The grader reseeds the same date on every run, so it cannot see a literal in your script, but in production a hardcoded date is exactly the wall-clock leak this lesson is about: the rerun of a failed job and the backfill of March both silently process the wrong day. Delete that partition from \`fct_orders\`, then insert it fresh from \`batch_orders\`. This is a backfill, so \`fct_orders\` already holds a later \`2026-03-15\` partition as well as \`2026-03-13\`, and both must come out untouched.`,
    starterCode: `-- Replace the run's partition in fct_orders. The date comes from run_config, never a literal.
DELETE FROM fct_orders
WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily');

-- then insert the same partition fresh from batch_orders
`,
    hints: [
      "The parameter lookup is a scalar subquery you can reuse in both statements: `(SELECT run_date FROM run_config WHERE pipeline = 'orders_daily')`.",
      "The insert filters the batch by the SAME predicate the delete used: `INSERT INTO fct_orders (order_id, dt, customer_id, amount_usd) SELECT order_id, dt, customer_id, amount_usd FROM batch_orders WHERE dt = (...)`.",
      "Delete first, insert second. Reversing them leaves you with nothing, because the delete would wipe the rows you just wrote.",
    ],
    referenceSolution: `DELETE FROM fct_orders
WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily');

INSERT INTO fct_orders (order_id, dt, customer_id, amount_usd)
SELECT order_id, dt, customer_id, amount_usd
FROM batch_orders
WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily');`,
    seedSql: FCT_ORDERS_SEED + "\n\n" + BATCH_ORDERS_SEED + "\n\n" + RUN_CONFIG_SEED,
    assertions: [
      {
        suite: "partition",
        name: "run_partition_equals_the_batch",
        sql: `WITH p AS (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily'),
target AS (SELECT order_id, dt, customer_id, amount_usd FROM fct_orders WHERE dt = (SELECT run_date FROM p)),
batch AS (SELECT order_id, dt, customer_id, amount_usd FROM batch_orders WHERE dt = (SELECT run_date FROM p))
SELECT * FROM (SELECT * FROM target EXCEPT SELECT * FROM batch)
UNION ALL
SELECT * FROM (SELECT * FROM batch EXCEPT SELECT * FROM target)`,
      },
      {
        suite: "partition",
        name: "no_duplicate_orders_in_the_partition",
        sql: `SELECT order_id FROM fct_orders
WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily')
GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "isolation",
        name: "other_partitions_untouched",
        sql: `WITH untouched(order_id, dt, customer_id, amount_usd) AS (VALUES
  ('O-3101', '2026-03-13', 501,  55.00),
  ('O-3102', '2026-03-13', 502, 140.25),
  ('O-3103', '2026-03-13', 503,  22.80),
  ('O-3104', '2026-03-13', 506,  97.60),
  ('O-3105', '2026-03-13', 507,  33.15),
  ('O-3181', '2026-03-15', 502, 112.30),
  ('O-3182', '2026-03-15', 508,  59.45),
  ('O-3183', '2026-03-15', 503, 174.00)),
actual AS (SELECT order_id, dt, customer_id, amount_usd FROM fct_orders WHERE dt <> '2026-03-14')
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT * FROM actual)`,
      },
      {
        suite: "isolation",
        name: "no_partitions_invented",
        sql: `SELECT DISTINCT dt FROM fct_orders WHERE dt NOT IN ('2026-03-13', '2026-03-14', '2026-03-15')`,
      },
    ],
    checkIdempotency: true,
    // Nothing here grows by design, but naming the graded table keeps a learner's scratch or
    // staging table from perturbing the double-run comparison.
    idempotencyTables: ["fct_orders"],
  }),
  practice: scriptExercise({
    id: "de-l8-partition-replacement-practice",
    prompt: `Write a script that rebuilds the daily rollup \`fct_daily_revenue(dt, order_count, revenue_usd)\` for the run's date only, leaving every other date alone and staying safe to rerun, over \`fct_orders(order_id, dt, customer_id, amount_usd)\` and \`run_config(pipeline, run_date)\`.

\`order_count\` is the number of orders in that date's partition and \`revenue_usd\` is their summed \`amount_usd\` rounded to 2 decimals. The stale \`2026-03-14\` row currently in \`fct_daily_revenue\` must be replaced, not added to, and the \`2026-03-12\`, \`2026-03-13\`, and \`2026-03-15\` rows must survive exactly as they are. Rebuilding the whole rollup is not an option: \`2026-03-12\` is older than \`fct_orders\` retention, so a full recompute would quietly delete a day nothing can recreate.`,
    starterCode: `-- Rebuild only the run's date in fct_daily_revenue. Read the date from run_config.
`,
    hints: [
      "Same two-statement shape as the apply: delete the run's date from the rollup, then insert it recomputed from `fct_orders`.",
      "The recompute is `SELECT dt, COUNT(*), ROUND(SUM(amount_usd), 2) FROM fct_orders WHERE dt = (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily') GROUP BY dt`.",
    ],
    seedSql: FCT_ORDERS_LOADED_SEED + "\n\n" + FCT_DAILY_REVENUE_SEED + "\n\n" + RUN_CONFIG_SEED,
    assertions: [
      {
        suite: "rollup",
        name: "run_date_row_matches_the_recompute",
        sql: `WITH p AS (SELECT run_date FROM run_config WHERE pipeline = 'orders_daily'),
expected AS (
  SELECT dt, COUNT(*) AS order_count, ROUND(SUM(amount_usd), 2) AS revenue_usd
  FROM fct_orders WHERE dt = (SELECT run_date FROM p) GROUP BY dt
),
actual AS (
  SELECT dt, order_count, ROUND(revenue_usd, 2) AS revenue_usd
  FROM fct_daily_revenue WHERE dt = (SELECT run_date FROM p)
)
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT * FROM actual)`,
      },
      {
        suite: "rollup",
        name: "one_row_per_date",
        sql: `SELECT dt FROM fct_daily_revenue GROUP BY dt HAVING COUNT(*) > 1`,
      },
      {
        suite: "isolation",
        name: "other_dates_untouched",
        sql: `WITH untouched(dt, order_count, revenue_usd) AS (VALUES
  ('2026-03-12', 4, 201.40),
  ('2026-03-13', 5, 348.80),
  ('2026-03-15', 3, 345.75)),
actual AS (SELECT dt, order_count, ROUND(revenue_usd, 2) AS revenue_usd FROM fct_daily_revenue WHERE dt <> '2026-03-14')
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT * FROM actual)`,
      },
    ],
    checkIdempotency: true,
    idempotencyTables: ["fct_daily_revenue"],
  }),
  extraPractice: [
    {
      id: "de-l8-partition-replacement-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns what a blind append left behind after running twice, as \`(dt, row_count, distinct_orders)\`, earliest date first, over \`fct_orders_appended(order_id, dt, amount_usd)\`.

A date whose \`row_count\` is larger than its \`distinct_orders\` is a partition the loader duplicated.`,
      starterCode: `-- Per date: how many rows are there, and how many distinct orders should there be?
SELECT dt
FROM fct_orders_appended
;`,
      hints: [
        "Group by `dt`, then `COUNT(*)` and `COUNT(DISTINCT order_id)`.",
        "Alias them exactly `row_count` and `distinct_orders`, and order by `dt`.",
      ],
      referenceSolution: `SELECT dt,
       COUNT(*) AS row_count,
       COUNT(DISTINCT order_id) AS distinct_orders
FROM fct_orders_appended
GROUP BY dt
ORDER BY dt;`,
      singleFile: {
        seedSql: FCT_ORDERS_APPENDED_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["dt", "row_count", "distinct_orders"],
          rows: [
            ["2026-03-13", 5, 5],
            ["2026-03-14", 12, 6],
          ],
        },
      },
    },
    scriptExercise({
      id: "de-l8-partition-replacement-drill-2",
      prompt: `**Medium.** Write a script that replaces the one \`(dt, region)\` cell this run owns in \`fct_region_orders\`, over \`batch_region_orders(order_id, dt, region, amount_usd)\`, \`fct_region_orders(order_id, dt, region, amount_usd)\`, and \`run_config_region(pipeline, run_date, region)\`.

The batch carries rows for regions this run does not own, and the target already holds another region's rows for the same date. Both partition columns have to appear in the delete predicate and in the insert filter, and rerunning the script must change nothing.`,
      starterCode: `-- Replace only the (run_date, region) cell named in run_config_region.
`,
      hints: [
        "Both predicates need both columns: `WHERE dt = (SELECT run_date FROM run_config_region WHERE pipeline = 'region_orders_daily') AND region = (SELECT region FROM run_config_region WHERE pipeline = 'region_orders_daily')`.",
        "Deleting by `dt` alone wipes the eu-west rows this run does not own, and inserting by `dt` alone loads eu-west rows it was never given.",
      ],
      referenceSolution: `DELETE FROM fct_region_orders
WHERE dt = (SELECT run_date FROM run_config_region WHERE pipeline = 'region_orders_daily')
  AND region = (SELECT region FROM run_config_region WHERE pipeline = 'region_orders_daily');

INSERT INTO fct_region_orders (order_id, dt, region, amount_usd)
SELECT order_id, dt, region, amount_usd
FROM batch_region_orders
WHERE dt = (SELECT run_date FROM run_config_region WHERE pipeline = 'region_orders_daily')
  AND region = (SELECT region FROM run_config_region WHERE pipeline = 'region_orders_daily');`,
      seedSql: REGION_ORDERS_SEED,
      assertions: [
        {
          suite: "cell",
          name: "owned_cell_equals_the_batch",
          sql: `WITH p AS (SELECT run_date, region FROM run_config_region WHERE pipeline = 'region_orders_daily'),
target AS (SELECT order_id, dt, region, amount_usd FROM fct_region_orders
           WHERE dt = (SELECT run_date FROM p) AND region = (SELECT region FROM p)),
batch AS (SELECT order_id, dt, region, amount_usd FROM batch_region_orders
          WHERE dt = (SELECT run_date FROM p) AND region = (SELECT region FROM p))
SELECT * FROM (SELECT * FROM target EXCEPT SELECT * FROM batch)
UNION ALL
SELECT * FROM (SELECT * FROM batch EXCEPT SELECT * FROM target)`,
        },
        {
          suite: "isolation",
          name: "unowned_cells_untouched",
          sql: `WITH untouched(order_id, dt, region, amount_usd) AS (VALUES
  ('R-6901', '2026-03-13', 'us-east',  45.00),
  ('R-6902', '2026-03-13', 'us-east',  88.25),
  ('R-7051', '2026-03-14', 'eu-west',  70.00),
  ('R-7052', '2026-03-14', 'eu-west', 133.30),
  ('R-7201', '2026-03-15', 'us-east',  52.65),
  ('R-7202', '2026-03-15', 'us-east', 143.80)),
actual AS (SELECT order_id, dt, region, amount_usd FROM fct_region_orders
           WHERE NOT (dt = '2026-03-14' AND region = 'us-east'))
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM untouched)
UNION ALL
SELECT * FROM (SELECT * FROM untouched EXCEPT SELECT * FROM actual)`,
        },
        {
          suite: "cell",
          name: "no_duplicate_orders",
          sql: `SELECT order_id FROM fct_region_orders GROUP BY order_id HAVING COUNT(*) > 1`,
        },
      ],
      checkIdempotency: true,
      idempotencyTables: ["fct_region_orders"],
    }),
  ],
}

const changeBatchMerge: SqlLesson = {
  id: "de-l8-change-batch-merge",
  title: "Merge Semantics: In-Batch Duplicates, Tied Versions, and Redelivery",
  summary:
    "Apply a redelivered change batch to a dimension when two changes for one key carry the same timestamp, and keep the merge idempotent.",
  estimatedMinutes: 26,
  difficulty: "hard",
  skills: [
    "merge on a business key",
    "dedup before merge",
    "ROW_NUMBER composite tiebreaker",
    "at-least-once redelivery",
    "tombstone delete",
    "INSERT...ON CONFLICT DO UPDATE",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## You have built this before, and that is deliberate

Implementation 2 is the keyed merge: collapse the change batch to one row per business key, upsert the survivors, delete the tombstones. You already wrote exactly that in \`sql-l5-cdc-changelog-apply\`, where a monotonic \`version\` column ordered the changes and \`ROW_NUMBER() OVER (PARTITION BY pk ORDER BY version DESC) = 1\` picked the winner.

The mechanic is not new. This lesson exists because the two things that break it in production were both engineered out of that seed, and both of them are what the interview follow-up probes.

## Pressure 1: the ordering column ties

Real ordering columns are timestamps, and real timestamps have finite resolution. A source that commits at second resolution can emit two changes for one customer inside the same second. Now this is nondeterministic:

\`\`\`sql
ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC)
\`\`\`

Two rows tie for rank 1. The engine may return either. Which means your dimension can hold the newer tier on Monday and the older one on Tuesday, from the same input, with no error anywhere. The fix is a **composite tiebreaker**: a second, strictly unique column appended to the ordering.

\`\`\`sql
ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC)
\`\`\`

\`change_id\` is monotonic within the feed, so the pair \`(changed_at, change_id)\` is unique and the winner is decided. Windowed dedup with ROW_NUMBER is the single most-cited SQL task in data interviews, and the tiebreaker is the half that separates a candidate who has shipped one from a candidate who has read about one.

## Pressure 2: the batch redelivers what you already applied

At-least-once delivery means the producer will resend. A batch does not politely contain only new rows; it can contain the whole previous batch again, plus today's changes. Your merge has to be correct on a **superset** of what it already applied.

Keyed upsert survives this for free. Reapplying a change that is already in the dimension writes the same values over themselves, which is a no-op. That is the canonical sentence made concrete: at-least-once delivery plus an idempotent sink equals effectively exactly-once.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["what the batch contains", "what a blind apply does", "what the keyed merge does"],
  "rows": [
    ["a verbatim redelivery of yesterday's rows", "rewrites the same values, or duplicates them if the sink is an append", "writes identical values over themselves, a no-op"],
    ["two changes for one key, tied on changed_at", "picks either one, differently on different runs", "picks the higher change_id, the same one every run"],
    ["a key created and deleted inside the batch", "inserts a row that should never exist", "the delete wins the dedup, so the key never lands"],
    ["a key deleted and then re-created inside the batch", "deletes it, because the batch contains a 'd' for that key", "the create wins the dedup, so the key survives"]
  ],
  "highlightCols": ["what the keyed merge does"],
  "caption": "The four things a real change batch throws at a merge. Dedup with a composite tiebreaker, then upsert, then delete the tombstones."
}
\`\`\`

## The apply, in three moves

1. **Dedup to one winner per key** with \`ROW_NUMBER() OVER (PARTITION BY key ORDER BY changed_at DESC, change_id DESC) = 1\`.
2. **Upsert the winners whose op is a create or an update** with \`INSERT ... ON CONFLICT(key) DO UPDATE SET ...\`.
3. **Delete the winners whose op is a delete.** Note the word winners. "This key has a \`'d'\` somewhere in the batch" is not the same test: a key that was deleted and then re-created has a \`'d'\` in the batch and must survive. A delete that lost the dedup to a later change never fires, and an insert that lost to a later delete never lands.

**Common mistake:** upserting the raw batch without collapsing it first. It appears to work whenever the input happens to arrive in order, and it corrupts silently the first time a key shows up twice. A real \`MERGE\` will not even let you: Snowflake, BigQuery, and Iceberg all raise a nondeterministic-merge error when two source rows match one target row.

**Interview nuance:** the follow-up that filters candidates is "what breaks if the batch contains the same key twice?" The complete answer names **both** failures: the duplicate itself, which a real MERGE rejects outright, and the tie inside it, which no engine will warn you about because it is not an error, just a coin flip.

> **On a real platform this differs.** A warehouse writes all three moves as one statement: \`MERGE INTO dim_customer USING deduped_changes ON ... WHEN MATCHED AND op = 'd' THEN DELETE WHEN MATCHED THEN UPDATE SET ... WHEN NOT MATCHED THEN INSERT ...\`, available in Snowflake, BigQuery, Databricks, and Iceberg. SQLite has no \`MERGE\` keyword, so the grading here is \`INSERT ... ON CONFLICT DO UPDATE\` plus a keyed \`DELETE\`, which is precisely what a MERGE compiles down to. The dedup step transfers unchanged, because those engines require it.`,
    demoSeedSql: `CREATE TABLE demo_changes (change_id INTEGER, customer_id INTEGER, tier TEXT, changed_at TEXT);
INSERT INTO demo_changes (change_id, customer_id, tier, changed_at) VALUES
  (105, 42, 'gold',     '2026-03-14 08:30:00'),
  (106, 42, 'platinum', '2026-03-14 08:30:00'),
  (108, 66, 'silver',   '2026-03-14 08:45:00');`,
    demoCode: `-- Customer 42 changed twice in the same second. One ordering is a coin flip, the other is not.
SELECT change_id, customer_id, tier, changed_at,
       ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC) AS rank_ambiguous,
       ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rank_decided
FROM demo_changes
ORDER BY customer_id, change_id;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "de-l8-change-batch-merge-apply",
    prompt: `Write a script that applies \`stg_customer_changes\` to \`dim_customer\` so the highest \`change_id\` wins each tie, \`op = 'd'\` removes the row, redelivered rows change nothing, and rerunning the script changes nothing, over \`stg_customer_changes(change_id, customer_id, op, name, tier, changed_at)\` and \`dim_customer(customer_id PRIMARY KEY, name, tier, updated_at)\`.

Dedup to one winner per \`customer_id\` ordered by \`changed_at DESC, change_id DESC\`, upsert the \`'c'\` and \`'u'\` winners with \`ON CONFLICT(customer_id) DO UPDATE\` setting \`updated_at\` to the winner's \`changed_at\`, then delete the keys whose winner is a \`'d'\`. Customer 42 has two changes stamped at the same second, rows 101 to 104 are a verbatim redelivery of a batch the dimension already holds, customer 77 is created and then deleted inside this batch, and customer 88 is deleted and then re-created inside it. Customer 99 is in the dimension and nowhere in the batch, so it must come out untouched: a merge owns the keys the batch carries and nothing else. The file arrives in delivery order, so you cannot lean on the row order you see.`,
    starterCode: `-- Dedup with a composite tiebreaker, upsert the c/u winners, delete the d winners.
WITH latest AS (
  -- rank each customer's changes so exactly one wins, and expose that rank as rn;
  -- a timestamp alone is not enough to decide it
)
INSERT INTO dim_customer (customer_id, name, tier, updated_at)
SELECT customer_id, name, tier, changed_at FROM latest WHERE rn = 1 AND op IN ('c', 'u')
ON CONFLICT(customer_id) DO UPDATE SET name = excluded.name, tier = excluded.tier, updated_at = excluded.updated_at;

-- then DELETE the customer_ids whose winning op is 'd'
`,
    hints: [
      "Two of customer 42's changes carry the same `changed_at`, so an ordering that stops there leaves the engine free to hand back either one, differently on different runs. Append a second column that is never equal for two rows of this feed and the winner stops being a coin flip.",
      "The delete repeats the same dedup: `DELETE FROM dim_customer WHERE customer_id IN (SELECT customer_id FROM (SELECT customer_id, op, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn FROM stg_customer_changes) WHERE rn = 1 AND op = 'd')`.",
      "The delete has to be driven by the WINNER's op, not by \"this key has a 'd' somewhere in the batch\". Customer 77's winner is a delete so it must vanish, while customer 88 was deleted and then re-created, so its winner is the create and it must stay.",
    ],
    referenceSolution: `WITH latest AS (
  SELECT change_id, customer_id, op, name, tier, changed_at,
         ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn
  FROM stg_customer_changes
)
INSERT INTO dim_customer (customer_id, name, tier, updated_at)
SELECT customer_id, name, tier, changed_at FROM latest WHERE rn = 1 AND op IN ('c', 'u')
ON CONFLICT(customer_id) DO UPDATE SET name = excluded.name, tier = excluded.tier, updated_at = excluded.updated_at;

DELETE FROM dim_customer WHERE customer_id IN (
  SELECT customer_id FROM (
    SELECT customer_id, op,
           ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn
    FROM stg_customer_changes
  ) WHERE rn = 1 AND op = 'd'
);`,
    seedSql: CUSTOMER_CHANGES_SEED,
    assertions: [
      {
        suite: "endstate",
        name: "dimension_matches_the_deduped_batch",
        sql: `WITH latest AS (
  SELECT customer_id, op, name, tier, changed_at,
         ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn
  FROM stg_customer_changes
),
winners AS (SELECT customer_id, name, tier, changed_at AS updated_at FROM latest WHERE rn = 1 AND op IN ('c', 'u')),
untouched(customer_id, name, tier, updated_at) AS (VALUES
  (99, 'Radia Perlman', 'silver', '2026-03-12 11:00:00')),
expected AS (SELECT * FROM winners UNION ALL SELECT * FROM untouched)
SELECT * FROM (SELECT customer_id, name, tier, updated_at FROM dim_customer EXCEPT SELECT customer_id, name, tier, updated_at FROM expected)
UNION ALL
SELECT * FROM (SELECT customer_id, name, tier, updated_at FROM expected EXCEPT SELECT customer_id, name, tier, updated_at FROM dim_customer)`,
      },
      {
        suite: "tiebreak",
        name: "highest_change_id_won_the_tie",
        sql: `SELECT customer_id FROM dim_customer
WHERE customer_id = 42 AND (tier <> 'platinum' OR updated_at <> '2026-03-14 08:30:00')`,
      },
      {
        suite: "deletes",
        name: "no_surviving_tombstones",
        sql: `SELECT customer_id FROM dim_customer WHERE customer_id IN (
  SELECT customer_id FROM (
    SELECT customer_id, op,
           ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn
    FROM stg_customer_changes
  ) WHERE rn = 1 AND op = 'd')`,
      },
      {
        suite: "redelivery",
        name: "redelivered_rows_changed_nothing",
        sql: `SELECT customer_id FROM dim_customer
WHERE customer_id = 11 AND (name <> 'Ada Lovelace' OR tier <> 'gold' OR updated_at <> '2026-03-13 09:00:00')`,
      },
      {
        suite: "grain",
        name: "one_row_per_customer",
        sql: `SELECT customer_id FROM dim_customer GROUP BY customer_id HAVING COUNT(*) > 1`,
      },
    ],
    checkIdempotency: true,
    idempotencyTables: ["dim_customer"],
  }),
  practice: scriptExercise({
    id: "de-l8-change-batch-merge-practice",
    prompt: `Write a script that merges the product price feed into \`dim_product\` keyed on \`sku\`, over \`stg_product_prices(feed_id, sku, op, product_name, price_usd, feed_ts)\` and \`dim_product(sku PRIMARY KEY, product_name, price_usd, updated_at)\`.

The feed redelivers yesterday's rows alongside today's, two rows for \`SKU-100\` share a \`feed_ts\`, \`op = 'd'\` discontinues a product, and \`SKU-500\` is discontinued and then relisted inside the same feed. \`SKU-700\` is in \`dim_product\` and nowhere in the feed, so it has to survive exactly as it is. The higher \`feed_id\` wins a tie, \`updated_at\` takes the winner's \`feed_ts\`, and rerunning the script must change nothing.`,
    starterCode: `-- Merge the feed into dim_product: dedup on sku, upsert the c/u winners, delete the d winners.
`,
    hints: [
      "The ordering that decides a winner is `ORDER BY feed_ts DESC, feed_id DESC`; without `feed_id` the two SKU-100 rows are a coin flip.",
    ],
    seedSql: PRODUCT_FEED_SEED,
    assertions: [
      {
        suite: "endstate",
        name: "dimension_matches_the_deduped_feed",
        sql: `WITH latest AS (
  SELECT sku, op, product_name, price_usd, feed_ts,
         ROW_NUMBER() OVER (PARTITION BY sku ORDER BY feed_ts DESC, feed_id DESC) AS rn
  FROM stg_product_prices
),
winners AS (SELECT sku, product_name, price_usd, feed_ts AS updated_at FROM latest WHERE rn = 1 AND op IN ('c', 'u')),
untouched(sku, product_name, price_usd, updated_at) AS (VALUES
  ('SKU-700', 'Burr Grinder', 89.00, '2026-03-12 06:00:00')),
expected AS (SELECT * FROM winners UNION ALL SELECT * FROM untouched)
SELECT * FROM (SELECT sku, product_name, price_usd, updated_at FROM dim_product EXCEPT SELECT sku, product_name, price_usd, updated_at FROM expected)
UNION ALL
SELECT * FROM (SELECT sku, product_name, price_usd, updated_at FROM expected EXCEPT SELECT sku, product_name, price_usd, updated_at FROM dim_product)`,
      },
      {
        suite: "tiebreak",
        name: "highest_feed_id_won_the_tie",
        sql: `SELECT sku FROM dim_product
WHERE sku = 'SKU-100' AND (ROUND(price_usd, 2) <> 17.49 OR updated_at <> '2026-03-14 06:00:00')`,
      },
      {
        suite: "deletes",
        name: "no_surviving_tombstones",
        sql: `SELECT sku FROM dim_product WHERE sku IN (
  SELECT sku FROM (
    SELECT sku, op, ROW_NUMBER() OVER (PARTITION BY sku ORDER BY feed_ts DESC, feed_id DESC) AS rn
    FROM stg_product_prices
  ) WHERE rn = 1 AND op = 'd')`,
      },
      {
        suite: "redelivery",
        name: "redelivered_row_changed_nothing",
        sql: `SELECT sku FROM dim_product
WHERE sku = 'SKU-300' AND (product_name <> 'Filter Papers' OR ROUND(price_usd, 2) <> 6.25 OR updated_at <> '2026-03-13 06:00:00')`,
      },
      {
        suite: "grain",
        name: "one_row_per_sku",
        sql: `SELECT sku FROM dim_product GROUP BY sku HAVING COUNT(*) > 1`,
      },
    ],
    checkIdempotency: true,
    idempotencyTables: ["dim_product"],
  }),
  extraPractice: [
    {
      id: "de-l8-change-batch-merge-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the winning change for every customer as \`(customer_id, change_id, op, changed_at)\`, lowest \`customer_id\` first, over \`stg_customer_changes(change_id, customer_id, op, name, tier, changed_at)\`.

The winner is the latest \`changed_at\`, and when two changes tie on it the higher \`change_id\` wins.`,
      starterCode: `-- One winning change per customer, decided by (changed_at, change_id).
SELECT customer_id, change_id, op, changed_at
FROM stg_customer_changes
;`,
      hints: [
        "Rank inside a subquery: `ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn`.",
        "Keep `rn = 1` in the outer query and order by `customer_id`.",
      ],
      referenceSolution: `SELECT customer_id, change_id, op, changed_at
FROM (
  SELECT customer_id, change_id, op, changed_at,
         ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY changed_at DESC, change_id DESC) AS rn
  FROM stg_customer_changes
)
WHERE rn = 1
ORDER BY customer_id;`,
      singleFile: {
        seedSql: CUSTOMER_CHANGES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["customer_id", "change_id", "op", "changed_at"],
          rows: [
            [11, 101, "u", "2026-03-13 09:00:00"],
            [22, 116, "u", "2026-03-14 09:20:00"],
            [33, 111, "d", "2026-03-14 09:00:00"],
            [42, 106, "u", "2026-03-14 08:30:00"],
            [55, 109, "u", "2026-03-14 08:50:00"],
            [66, 108, "c", "2026-03-14 08:45:00"],
            [77, 110, "d", "2026-03-14 08:55:00"],
            [88, 113, "c", "2026-03-14 09:10:00"],
          ],
        },
      },
    },
    {
      // MAP DEVIATION: the map briefs this drill as "the customer_ids whose winner would differ
      // between ORDER BY changed_at DESC and ORDER BY changed_at DESC, change_id DESC". That
      // question is not gradeable, because the winner under the ambiguous ordering is whatever the
      // engine happens to return, so the answer set is nondeterministic by definition. It is
      // reframed to the property that actually decides it: which customers have more than one
      // change sitting at their own LATEST changed_at.
      id: "de-l8-change-batch-merge-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every customer whose winner is undecided without the tiebreaker, as \`(customer_id, tied_rows)\`, lowest \`customer_id\` first, over \`stg_customer_changes\`.

A customer is undecided when more than one of their changes shares their latest \`changed_at\`, because \`ORDER BY changed_at DESC\` alone can then return either row. \`tied_rows\` is how many changes share that latest timestamp.`,
      starterCode: `-- Customers with more than one change sitting at their own latest changed_at.
SELECT customer_id
FROM stg_customer_changes
;`,
      hints: [
        "`RANK()` is the right window here, not `ROW_NUMBER()`: tied rows share rank 1, so counting them is the whole answer.",
        "Rank with `RANK() OVER (PARTITION BY customer_id ORDER BY changed_at DESC)`, keep rank 1, then `GROUP BY customer_id HAVING COUNT(*) > 1`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT customer_id, changed_at,
         RANK() OVER (PARTITION BY customer_id ORDER BY changed_at DESC) AS rk
  FROM stg_customer_changes
)
SELECT customer_id, COUNT(*) AS tied_rows
FROM ranked
WHERE rk = 1
GROUP BY customer_id
HAVING COUNT(*) > 1
ORDER BY customer_id;`,
      singleFile: {
        seedSql: CUSTOMER_CHANGES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["customer_id", "tied_rows"], rows: [[42, 2]] },
      },
    },
  ],
}

const appendDedupAtRead: SqlLesson = {
  id: "de-l8-append-dedup-at-read",
  title: "Append-Only Bronze, Dedup at Read",
  summary:
    "Keep the write path a blind append and make the read path idempotent instead, then choose between all three idempotency patterns without guidance.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "append-only tables",
    "dedup at read",
    "ROW_NUMBER over ingestion metadata",
    "medallion bronze and silver",
    "rebuildable projections",
    "idempotency pattern selection",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Sometimes you cannot make the writer idempotent

Implementations 1 and 2 both assume you control the write. Often you do not. Several producers write into the same landing prefix, an at-least-once queue resends whatever it is not sure landed, and a vendor drops the same file twice with a new name. Coordinating a keyed merge across all of that costs more than it is worth, and every merge you add to the hot ingest path is latency the producers pay for.

Implementation 3 gives up on an idempotent writer and moves the property to the reader:

- **Bronze is append-only and immutable.** Every delivery lands, duplicates included, with its ingestion metadata attached: when it was ingested and which file it came from. Nothing is ever updated or deleted in place, so the raw record of what arrived is intact and auditable.
- **Silver is a projection you rebuild.** One row per business key, chosen from Bronze by \`ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC)\`, rebuilt from scratch on every run. Because it is derived, it is disposable: drop it and rebuild it and you get the same table.

Bronze grows on a rerun. Silver does not change. That is the whole design.

## The idempotency contract is scoped

This is the first place in the course where "is this idempotent?" needs a qualifier, because the honest answer is **it depends which table you ask about**. Bronze legitimately gains rows on every run, by design. Silver is byte-identical after one run or ten.

So the grader for this lesson names its scope: \`idempotencyTables: ['events_silver']\`. The double run compares the content of the projection only, and it deliberately ignores Bronze. That is not a grading convenience, it is how a production data contract is written: you promise stability for the tables downstream consumers read, and you say out loud which ones those are. A contract that claimed every table was stable would be false the first time an append landed.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["pattern", "reach for it when", "what the run owns", "what stays stable on a rerun"],
  "rows": [
    ["delete + insert", "a partitioned batch fact, one date per run", "one partition of the target", "the whole target"],
    ["merge on a key", "a keyed dimension fed by changes or CDC", "the keys present in the batch", "the whole dimension"],
    ["append + dedup at read", "untrusted or multiple producers, at-least-once queues", "nothing, the write is blind", "the projection only, never the raw table"]
  ],
  "highlightCols": ["reach for it when"],
  "caption": "The three idempotent-write implementations. Naming WHEN each applies is the senior-signal answer; knowing only one is not."
}
\`\`\`

## Picking the winner needs a tiebreaker too

The dedup here has the same trap the merge lesson had. If two copies of an event share an \`ingested_at\`, \`ORDER BY ingested_at DESC\` alone is a coin flip. Add a second ordering column so the choice is decided: the source file name, an ingestion sequence, or a load id.

The tie is not hypothetical here. One load stamps every row it lands with the same \`ingested_at\`, so any event that arrives in two files of the same load ties by construction, and Bronze below holds exactly that case with two copies that disagree on their payload. When tied copies happen to be byte-identical the choice does not matter to the output, but writing the tiebreaker anyway means you never have to prove that they were.

**Common mistake:** treating Bronze as the table to clean up. Deleting duplicates out of Bronze destroys the audit trail (you can no longer answer "did we receive that file twice?"), reintroduces the write coordination you just avoided, and is not even necessary, because the projection already hides them. Bronze is immutable. Silver is where correctness lives.

**Interview nuance:** interviewers do not ask "how do you make a pipeline idempotent?" once and stop. They ask you to choose under constraints: multiple producers, a queue that resends, a source with no reliable key, a partition that must land atomically. Naming which of the three patterns fits and why is the senior-signal answer. Knowing exactly one of them and forcing it onto every problem is the junior one.

> **On a real platform this differs.** This is the lakehouse posture, and the vocabulary is medallion: Bronze raw, Silver conformed, Gold aggregated. The projection is a dbt incremental or table model rebuilt from Bronze, or an Iceberg or Delta \`MERGE INTO\` that maintains it in place. The ingestion metadata that decides the winner is real: Databricks Auto Loader and Snowpipe both stamp a file name and a load time on every row for exactly this reason.`,
    demoSeedSql: `CREATE TABLE demo_bronze (event_id TEXT, ingested_at TEXT, source_file TEXT, duration_ms INTEGER);
INSERT INTO demo_bronze (event_id, ingested_at, source_file, duration_ms) VALUES
  ('E-1006', '2026-03-14 03:00:00', 'events-0142.json',   0),
  ('E-1006', '2026-03-14 04:30:00', 'events-0142.json', 150),
  ('E-1007', '2026-03-14 03:00:00', 'events-0142.json', 260),
  ('E-1007', '2026-03-14 04:30:00', 'events-0142.json', 260);`,
    demoCode: `-- Bronze keeps every copy. The read decides which one Silver gets, and says so out loud.
SELECT event_id, ingested_at, source_file, duration_ms,
       CASE WHEN ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC) = 1
            THEN 'kept in silver'
            ELSE 'superseded copy, stays in bronze' END AS read_verdict
FROM demo_bronze
ORDER BY event_id, ingested_at DESC;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "de-l8-append-dedup-at-read-apply",
    prompt: `Write a script that appends \`events_batch\` to \`events_bronze\` unconditionally, then rebuilds \`events_silver\` as exactly one row per \`event_id\` keeping the copy with the latest \`ingested_at\`, over \`events_bronze(event_id, event_ts, ingested_at, source_file, payload_json)\`, \`events_batch\` with the same columns, and \`events_silver(event_id, event_ts, payload_json)\`.

Do not filter the append: Bronze takes every delivery, duplicates included, and it will legitimately be larger after a rerun. \`events_silver\` is the table that must be identical after one run or two, so rebuild it from scratch rather than adding to it. One event landed twice inside a single load, so its two copies share an \`ingested_at\` and disagree on the payload: break that tie with \`source_file DESC\`.`,
    starterCode: `-- 1. Blind append into bronze. 2. Rebuild silver as one row per event_id, latest copy wins.
INSERT INTO events_bronze (event_id, event_ts, ingested_at, source_file, payload_json)
SELECT event_id, event_ts, ingested_at, source_file, payload_json FROM events_batch;

-- then rebuild events_silver from events_bronze
`,
    hints: [
      "Rebuild means clear it first: `DELETE FROM events_silver;` before the insert, so a second run does not stack a second copy of the projection.",
      "The winner per key comes from a ranked subquery: `SELECT event_id, event_ts, payload_json FROM (SELECT event_id, event_ts, payload_json, ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC) AS rn FROM events_bronze) WHERE rn = 1`.",
      "Bronze growing on the second run is expected and is not a failure. Only `events_silver` is compared across the two runs.",
    ],
    referenceSolution: `INSERT INTO events_bronze (event_id, event_ts, ingested_at, source_file, payload_json)
SELECT event_id, event_ts, ingested_at, source_file, payload_json FROM events_batch;

DELETE FROM events_silver;

INSERT INTO events_silver (event_id, event_ts, payload_json)
SELECT event_id, event_ts, payload_json
FROM (
  SELECT event_id, event_ts, payload_json,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC) AS rn
  FROM events_bronze
)
WHERE rn = 1;`,
    seedSql: EVENTS_BRONZE_SEED + "\n\n" + EVENTS_BATCH_SEED,
    assertions: [
      {
        suite: "bronze",
        name: "every_batch_row_landed_in_bronze",
        sql: `SELECT b.event_id FROM events_batch b
WHERE NOT EXISTS (
  SELECT 1 FROM events_bronze z
  WHERE z.event_id = b.event_id AND z.ingested_at = b.ingested_at
    AND z.source_file = b.source_file AND z.payload_json = b.payload_json)`,
      },
      {
        suite: "bronze",
        name: "bronze_history_not_deleted",
        sql: `SELECT '2026-03-14 03:00:00' WHERE (
  SELECT COUNT(*) FROM events_bronze WHERE ingested_at = '2026-03-14 03:00:00') <> 3`,
      },
      {
        suite: "silver",
        name: "one_row_per_event_id",
        sql: `SELECT event_id FROM events_silver GROUP BY event_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "silver",
        name: "silver_holds_the_latest_copy",
        sql: `WITH latest AS (
  SELECT event_id, event_ts, payload_json,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC) AS rn
  FROM events_bronze
),
expected AS (SELECT event_id, event_ts, payload_json FROM latest WHERE rn = 1)
SELECT * FROM (SELECT event_id, event_ts, payload_json FROM events_silver EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT event_id, event_ts, payload_json FROM events_silver)`,
      },
    ],
    checkIdempotency: true,
    // REQUIRED, not optional: events_bronze grows by design on every run, so the row-count
    // fallback would fail every correct solution. Only the projection is promised stable.
    idempotencyTables: ["events_silver"],
  }),
  practice: scriptExercise({
    id: "de-l8-append-dedup-at-read-practice",
    prompt: `Write a script that leaves \`fct_page_views(view_id, viewed_at, path)\` holding exactly one row per \`view_id\`, carrying the values from the copy with the latest \`ingested_at\`, over \`raw_page_views(view_id, viewed_at, ingested_at, source_file, path)\` and \`page_view_batch\` with the same columns.

\`page_view_batch\` redelivers rows \`raw_page_views\` already holds, and \`raw_page_views\` is the append-only landing zone, so every row it starts with must still be there when your script finishes. One view landed twice inside a single load, so its two copies share an \`ingested_at\` and disagree on \`path\`: the later \`source_file\` wins that tie. Choose the idempotency pattern yourself. The grader only checks the goal state, twice.`,
    starterCode: `-- Goal state: fct_page_views holds one row per view_id, the latest copy wins, and running
-- this script a second time leaves fct_page_views exactly as the first run left it.
`,
    hints: [],
    seedSql: PAGE_VIEWS_SEED,
    assertions: [
      {
        suite: "goal",
        name: "one_row_per_view_id",
        sql: `SELECT view_id FROM fct_page_views GROUP BY view_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "goal",
        name: "fact_holds_the_latest_copy_of_every_view",
        sql: `WITH allrows AS (
  SELECT view_id, viewed_at, ingested_at, source_file, path FROM raw_page_views
  UNION ALL
  SELECT view_id, viewed_at, ingested_at, source_file, path FROM page_view_batch
),
latest AS (
  SELECT view_id, viewed_at, path,
         ROW_NUMBER() OVER (PARTITION BY view_id ORDER BY ingested_at DESC, source_file DESC) AS rn
  FROM allrows
),
expected AS (SELECT view_id, viewed_at, path FROM latest WHERE rn = 1)
SELECT * FROM (SELECT view_id, viewed_at, path FROM fct_page_views EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT view_id, viewed_at, path FROM fct_page_views)`,
      },
      {
        suite: "landing-zone",
        name: "raw_landing_zone_kept_every_original_row",
        sql: `SELECT v.id FROM (
  SELECT 'V-2001' AS id UNION ALL SELECT 'V-2002' UNION ALL SELECT 'V-2003'
  UNION ALL SELECT 'V-2004' UNION ALL SELECT 'V-2005' UNION ALL SELECT 'V-2006') v
WHERE NOT EXISTS (SELECT 1 FROM raw_page_views r WHERE r.view_id = v.id)
UNION ALL
SELECT 'row-count' WHERE (SELECT COUNT(*) FROM raw_page_views) < 9`,
      },
    ],
    checkIdempotency: true,
    // REQUIRED: appending the batch into raw_page_views is one of the legitimate solutions, so the
    // landing zone has to stay outside the comparison or the exercise punishes a correct answer.
    idempotencyTables: ["fct_page_views"],
  }),
  extraPractice: [
    {
      id: "de-l8-append-dedup-at-read-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the event ids Bronze holds more than one copy of, as \`(event_id, copies)\`, lowest \`event_id\` first, over \`events_bronze(event_id, event_ts, ingested_at, source_file, payload_json)\`.`,
      starterCode: `-- Which event ids arrived more than once?
SELECT event_id
FROM events_bronze
;`,
      hints: [
        "Group by `event_id` and count the rows in each group.",
        "`HAVING COUNT(*) > 1` keeps only the duplicated ids; alias the count exactly `copies`.",
      ],
      referenceSolution: `SELECT event_id, COUNT(*) AS copies
FROM events_bronze
GROUP BY event_id
HAVING COUNT(*) > 1
ORDER BY event_id;`,
      singleFile: {
        seedSql: EVENTS_BRONZE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["event_id", "copies"],
          rows: [
            ["E-1003", 2],
            ["E-1005", 2],
            ["E-1006", 2],
            ["E-1007", 2],
          ],
        },
      },
    },
    {
      id: "de-l8-append-dedup-at-read-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the surviving copy of every event, as \`(event_id, event_ts, ingested_at, payload_json)\`, lowest \`event_id\` first, over \`events_bronze\`.

The survivor is the copy with the latest \`ingested_at\`, and a tie on it is broken by the later \`source_file\`.`,
      starterCode: `-- One row per event_id: the copy a dedup-at-read projection would keep.
SELECT event_id, event_ts, ingested_at, payload_json
FROM events_bronze
;`,
      hints: [
        "Rank inside a subquery with `ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC)`.",
        "Keep `rn = 1` in the outer query and order by `event_id`.",
      ],
      referenceSolution: `SELECT event_id, event_ts, ingested_at, payload_json
FROM (
  SELECT event_id, event_ts, ingested_at, payload_json,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingested_at DESC, source_file DESC) AS rn
  FROM events_bronze
)
WHERE rn = 1
ORDER BY event_id;`,
      singleFile: {
        seedSql: EVENTS_BRONZE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["event_id", "event_ts", "ingested_at", "payload_json"],
          rows: [
            ["E-1001", "2026-03-14 00:05:00", "2026-03-14 01:00:00", '{"page":"/home","ms":120}'],
            ["E-1002", "2026-03-14 00:07:00", "2026-03-14 01:00:00", '{"page":"/pricing","ms":90}'],
            ["E-1003", "2026-03-14 01:02:00", "2026-03-14 02:00:00", '{"page":"/docs","ms":215}'],
            ["E-1004", "2026-03-14 01:06:00", "2026-03-14 02:00:00", '{"page":"/signup","ms":300}'],
            ["E-1005", "2026-03-14 02:03:00", "2026-03-14 04:30:00", '{"page":"/home","ms":95}'],
            ["E-1006", "2026-03-14 02:08:00", "2026-03-14 04:30:00", '{"page":"/docs","ms":150}'],
            [
              "E-1007",
              "2026-03-14 02:11:00",
              "2026-03-14 04:30:00",
              '{"page":"/pricing","ms":260}',
            ],
          ],
        },
      },
    },
  ],
}

export const level8Module2: SqlModule = {
  id: "de-l8-idempotency",
  title: "Module 8.2: Idempotency, the Core Property",
  description:
    "The spine of the level: the three idempotent-write implementations every 2025-2026 source converges on, each graded by literally running your script twice. Partition replacement driven by an injected run parameter instead of the wall clock, a keyed merge that survives in-batch duplicates whose timestamps tie and a batch that redelivers what you already applied, and an append-only landing zone whose idempotency contract is scoped to the projection built on top of it.",
  lessons: [partitionReplacement, changeBatchMerge, appendDedupAtRead],
}
