/**
 * Data Engineering Level 8, Module 8.4 — The Transformation Workflow.
 *
 * The analytics-engineering workflow RESEARCH.md §2.6 calls stable regardless of vendor
 * churn: models are SELECTs materialized in dependency order, data tests are queries that
 * return violating rows and pass at zero rows, lineage is the ref graph read forwards and
 * backwards, and dev and prod are two targets for the same model SQL. dbt, the Fusion
 * engine, and the Fivetran merger stay in prose callouts (finding 10, vendor churn); the
 * workflow itself is what a junior posting means by "dbt experience", so the learner IS the
 * tool here, materializing the graph by hand.
 *
 * Ownership boundary (CURRICULUM-MAP.md, Level 8 revision notes). `sql-l4-data-quality`
 * owns the four generic tests and the zero-rows-pass convention, `sql-l5-data-quality-gates`
 * owns write-audit-publish and its freshness/volume/null-rate gates, and Level 10 owns the
 * check-suite ledger with warn-vs-error severity. This module owns the vocabulary layer on
 * top (the curtain pull, the violation list as one artifact, unit test vs data test) and
 * spends the per-row quarantine gate exactly once, in the level capstone.
 *
 * Device: the same simulated-metadata seeds Level 6 proved. `model_refs` stands in for the
 * ref graph dbt compiles into its manifest and `model_runs` for run-results across
 * environments, so a learner who later reads a real manifest recognizes the shape. The two
 * build lessons use the workspace runner (multi-statement script, hidden assertion queries,
 * idempotency double-run) because DROP-and-rebuild materialization is only provable by
 * running the script twice.
 *
 * Gradability deviations, deliberate. 8.4.1's `model_refs` carries a fourth model,
 * `mart_customer_health`, that the Apply does not build: it reads the fact AND `stg_customers`,
 * which is the only reason any model in the graph is reachable at two different depths and
 * therefore the only reason the practice's MAX collapse can be graded (MIN scored identically
 * without it). 8.4.2's `orders` carries one NULL key so NOT IN and NOT EXISTS actually
 * disagree, and its duplicated payment carries an invalid method so the violation list
 * contains two IDENTICAL rows, which is the only shape that separates UNION ALL from UNION
 * (two rows with different violation labels survive plain UNION untouched).
 *
 * Map deviation, deliberate: 8.4.3's `model_refs` keeps `fct_customer_revenue` from 8.4.1 as
 * a live model, but the capstone builds only the seven `prod_` tables the map names in
 * `idempotencyTables`. Keeping `fct_customer_revenue` out of the capstone's build set (no
 * mart depends on it) is what makes that set closed under dependency, and it doubles as the
 * point of the Apply: an impact closure is a reachable set, not "every model in the graph".
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed,
 * and every workspace reference was executed against its own hidden assertions including the
 * idempotency double-run. Content rules: no em dashes in learner prose; every prompt leads
 * with the deliverable; every money column states an explicit ROUND so grading never depends
 * on summation order.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 8.4.1 seeds — two raw sources plus the ref graph a transformation tool compiles
// into its manifest. Amounts are all halves and quarters so a REAL sum is exact in binary
// and the expected sets never depend on summation order.
// ---------------------------------------------------------------------------

const RAW_SOURCES_SEED = `CREATE TABLE raw_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  status      TEXT,   -- placed | shipped | delivered | cancelled
  amount_usd  REAL,
  ordered_at  TEXT
);
INSERT INTO raw_orders (order_id, customer_id, status, amount_usd, ordered_at) VALUES
  (1001, 101, 'delivered', 120.00, '2026-06-01'),
  (1002, 101, 'shipped',    80.50, '2026-06-03'),
  (1003, 102, 'cancelled',  45.00, '2026-06-03'),
  (1004, 102, 'delivered', 210.25, '2026-06-05'),
  (1005, 103, 'placed',     35.75, '2026-06-06'),
  (1006, 103, 'delivered', 149.00, '2026-06-07'),
  (1007, 104, 'cancelled', 300.00, '2026-06-08'),
  (1008, 104, 'shipped',    60.00, '2026-06-09'),
  (1009, 105, 'delivered',  95.50, '2026-06-10'),
  (1010, 101, 'placed',     40.00, '2026-06-11');

CREATE TABLE raw_customers (
  customer_id INTEGER,
  name        TEXT,
  region      TEXT
);
INSERT INTO raw_customers (customer_id, name, region) VALUES
  (101, 'Ada Lovelace',      'us-east'),
  (102, 'Grace Hopper',      'us-west'),
  (103, 'Alan Turing',       'eu-west'),
  (104, 'Katherine Johnson', 'us-east'),
  (105, 'Jean Bartik',       'eu-west');`

// One row per ref() edge: `model` reads `ref_model`. This is the whole manifest a
// transformation tool topologically sorts before it builds anything.
//
// `mart_customer_health` is the graph's diamond and it is deliberate: it reads the fact AND
// `stg_customers` directly, so it is reachable from the sources at depth 2 and at depth 3.
// Without it, no model has parents at two different depths and the practice's MAX collapse
// would be a rule the data never exercises (MIN would score identically).
const MODEL_REFS_SEED = `CREATE TABLE model_refs (
  model     TEXT,   -- the model being built
  ref_model TEXT    -- the model or source it reads
);
INSERT INTO model_refs (model, ref_model) VALUES
  ('stg_orders',           'raw_orders'),
  ('stg_customers',        'raw_customers'),
  ('fct_customer_revenue', 'stg_orders'),
  ('fct_customer_revenue', 'stg_customers'),
  ('mart_customer_health', 'fct_customer_revenue'),
  ('mart_customer_health', 'stg_customers');`

const BUILD_ORDER_SEED = RAW_SOURCES_SEED + "\n\n" + MODEL_REFS_SEED

// The same graph with a proposed mart added, so "what would we have to build first" is a
// query instead of an argument. The proposed mart reads the fact and `stg_customers`, so
// `stg_customers` is reachable by two paths and a closure written without DISTINCT repeats it.
const MODEL_REFS_PROPOSED_SEED = `CREATE TABLE model_refs_proposed (
  model     TEXT,
  ref_model TEXT
);
INSERT INTO model_refs_proposed (model, ref_model) VALUES
  ('stg_orders',            'raw_orders'),
  ('stg_customers',         'raw_customers'),
  ('fct_customer_revenue',  'stg_orders'),
  ('fct_customer_revenue',  'stg_customers'),
  ('mart_customer_health',  'fct_customer_revenue'),
  ('mart_customer_health',  'stg_customers'),
  ('mart_regional_revenue', 'fct_customer_revenue'),
  ('mart_regional_revenue', 'stg_customers');`

// ---------------------------------------------------------------------------
// Module 8.4 — The Transformation Workflow
// ---------------------------------------------------------------------------

const modelsInDependencyOrder: SqlLesson = {
  id: "de-l8-models-in-dependency-order",
  title: "Models Are SELECTs, Built in Ref Order",
  summary:
    "Materialize a staging-to-mart model chain in the order its ref graph dictates, and derive that order from the graph itself with a recursive CTE.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "models as SELECTs",
    "ref dependencies",
    "materialization",
    "CREATE TABLE AS",
    "DROP-and-rebuild idempotency",
    "recursive CTE",
    "topological reasoning",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## A model is a SELECT with a name

Every junior data engineering posting that says "dbt experience" is asking about one workflow, and the workflow is simpler than the tool. A **model** is a single \`SELECT\` statement saved in a file. The file name is the table name. That is the whole idea.

\`\`\`sql
-- models/staging/stg_orders.sql
{{ config(materialized='table') }}

SELECT order_id, customer_id, status, amount_usd, ordered_at
FROM {{ source('shop', 'raw_orders') }}
WHERE status <> 'cancelled'
\`\`\`

You never write \`CREATE TABLE\` in that file. The tool wraps your \`SELECT\` in the right DDL and runs it. That wrapping is called **materialization**. The four built-in ones are \`view\` (the default), \`table\`, \`incremental\`, and \`ephemeral\`. The \`table\` materialization is a full refresh: drop whatever is there, create the table from the query, and it is the one you write by hand in this module.

## ref() is the edge, and the tool reads the graph

A model that reads another model does not name the table. It calls \`ref()\`:

\`\`\`sql
-- models/marts/fct_customer_revenue.sql
SELECT
  c.customer_id, c.name, c.region,
  COUNT(o.order_id)             AS orders,
  ROUND(SUM(o.amount_usd), 2)   AS revenue_usd
FROM {{ ref('stg_customers') }} c
JOIN {{ ref('stg_orders') }} o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name, c.region
\`\`\`

Each \`ref()\` is one **edge** in a dependency graph. The tool parses every model, collects the edges into a graph, sorts it topologically, and builds in that order. That is the honest one-line answer to "what does dbt actually do": **it materializes SELECTs in dependency order and runs tests.** Nothing about the answer is vendor-specific.

The naming canon is worth memorizing because reviewers read it as a signal:

- \`stg_*\` (staging) is one model per source table. Rename, cast, filter out garbage. No joins.
- \`int_*\` (intermediate) is optional glue when one mart needs several messy steps.
- \`fct_*\` and \`dim_*\` (marts) are the business-facing tables people query.

One more model rounds out this lesson's graph, and it is the interesting one. \`mart_customer_health\` reads \`fct_customer_revenue\`, and because that fact joins orders and so loses every customer who has never ordered, it also reads \`stg_customers\` directly. Its two parents therefore sit at different distances from the sources, which is the case a build-order query has to get right.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "raw_orders / raw_customers", "note": "sources, landed by ingestion" },
    { "label": "stg_orders / stg_customers", "note": "one SELECT per source: filter, rename, cast" },
    { "label": "fct_customer_revenue", "note": "joins both staging models, one row per customer" },
    { "label": "mart_customer_health", "note": "reads the fact and stg_customers, so its parents sit at two different depths" }
  ],
  "caption": "The ref graph for this lesson. Nothing at a later stage can be built before the stage it reads."
}
\`\`\`

## Full refresh is idempotent by construction

In this module you are the tool, so you write the DDL yourself, and the shape is always the same pair:

\`\`\`sql
DROP TABLE IF EXISTS stg_orders;
CREATE TABLE stg_orders AS
SELECT order_id, customer_id, status, amount_usd, ordered_at
FROM raw_orders
WHERE status <> 'cancelled';
\`\`\`

Module 8.2 proved idempotency by running a script twice and demanding the same end state. A full refresh passes that test for free: the \`DROP\` throws away the previous run before the \`CREATE\` rebuilds it, so run two lands on exactly what run one produced.

**Common mistake:** dropping the \`DROP TABLE IF EXISTS\` line. It looks harmless because a rebuild without it does not duplicate rows the way a naive \`INSERT\` does. What it does instead is error with "table stg_orders already exists" and abort the rest of your script, leaving the marts holding yesterday's data while the job log says the failure was in staging. Same root cause as a duplicating load (the script assumed a clean slate), different and more confusing symptom.

**Interview nuance:** "what does dbt actually do" is answered in one sentence: it compiles your \`SELECT\` files into DDL, resolves \`ref()\` into a dependency graph, builds in topological order, and runs the tests. Candidates who reach for the CLI flags first, and candidates who cannot say it without the tool's name in the sentence, both read as tool users rather than engineers.

> **On a real platform this differs.** Here you write the \`DROP\` and \`CREATE TABLE AS\` yourself and read the graph out of a \`model_refs\` table. On a real project you write only the \`SELECT\`, the edges come from \`ref()\` calls the parser finds in your SQL, and the graph lives in a compiled \`manifest.json\` that also drives docs, lineage, and \`--select state:modified+\`. dbt Labs rebuilt that parser in Rust for the Fusion engine (roughly 30x faster parsing, plus column-level lineage) and Fivetran and dbt Labs merged in June 2026. The workflow in this lesson did not change.`,
    demoSeedSql: MODEL_REFS_SEED,
    demoCode: `-- The manifest, one row per ref() edge: 'model' reads 'ref_model'.
-- A model whose name never appears in the model column is a source, so it is built first.
SELECT model, ref_model
FROM model_refs
ORDER BY model, ref_model;`,
    showDemoInput: false,
  },
  apply: scriptExercise({
    id: "de-l8-models-in-dependency-order-apply",
    prompt: `Write a script that builds three tables from \`raw_orders\` and \`raw_customers\`, in an order that satisfies the \`model_refs\` edges between them, and that is safe to run twice:

- \`stg_orders(order_id, customer_id, status, amount_usd, ordered_at)\`, every \`raw_orders\` row whose \`status\` is not \`'cancelled'\`.
- \`stg_customers(customer_id, name, region)\`, every \`raw_customers\` row.
- \`fct_customer_revenue(customer_id, name, region, orders, revenue_usd)\`, one row per customer, joining the two staging models: \`orders\` is that customer's count of staged orders and \`revenue_usd\` is \`ROUND(SUM(amount_usd), 2)\` over them.

Use \`DROP TABLE IF EXISTS x;\` followed by \`CREATE TABLE x AS SELECT ...\` for each model, which is the \`table\` materialization. \`model_refs\` says \`fct_customer_revenue\` reads both staging models, so it cannot be built first. The graph's fourth model, \`mart_customer_health\`, is not part of this build. The grader runs your script twice and compares all three tables.`,
    starterCode: `-- You are the transformation tool. Build the three models in ref order.
-- model_refs holds the edges: stg_orders <- raw_orders, stg_customers <- raw_customers,
-- fct_customer_revenue <- stg_orders and stg_customers. The mart_customer_health rows are
-- the rest of the graph and are not built here.

DROP TABLE IF EXISTS stg_orders;
CREATE TABLE stg_orders AS
-- the non-cancelled raw_orders rows
;

-- stg_customers next, then fct_customer_revenue on top of both.
`,
    hints: [
      "Each model is the same two statements: `DROP TABLE IF EXISTS name;` then `CREATE TABLE name AS SELECT ...;`.",
      "`stg_orders` is a filter, not an aggregate: `SELECT order_id, customer_id, status, amount_usd, ordered_at FROM raw_orders WHERE status <> 'cancelled'`.",
      "`stg_customers` is a straight passthrough of `customer_id, name, region`.",
      "The mart joins the two staging tables, never the raw ones: `FROM stg_customers c JOIN stg_orders o ON o.customer_id = c.customer_id`.",
      "Alias the aggregates exactly `orders` and `revenue_usd`, and group by `c.customer_id, c.name, c.region`.",
    ],
    referenceSolution: `DROP TABLE IF EXISTS stg_orders;
CREATE TABLE stg_orders AS
SELECT order_id, customer_id, status, amount_usd, ordered_at
FROM raw_orders
WHERE status <> 'cancelled';

DROP TABLE IF EXISTS stg_customers;
CREATE TABLE stg_customers AS
SELECT customer_id, name, region
FROM raw_customers;

DROP TABLE IF EXISTS fct_customer_revenue;
CREATE TABLE fct_customer_revenue AS
SELECT
  c.customer_id,
  c.name,
  c.region,
  COUNT(o.order_id)           AS orders,
  ROUND(SUM(o.amount_usd), 2) AS revenue_usd
FROM stg_customers c
JOIN stg_orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name, c.region;`,
    seedSql: BUILD_ORDER_SEED,
    checkIdempotency: true,
    idempotencyTables: ["stg_orders", "stg_customers", "fct_customer_revenue"],
    assertions: [
      {
        suite: "staging",
        name: "stg_orders holds exactly the eight non-cancelled orders",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM stg_orders) <> 8`,
      },
      {
        suite: "staging",
        name: "no cancelled order survived staging",
        sql: `SELECT order_id FROM stg_orders WHERE status = 'cancelled'`,
      },
      {
        suite: "staging",
        name: "stg_customers passes all five customers through",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM stg_customers) <> 5`,
      },
      {
        suite: "grain",
        name: "fct_customer_revenue holds one row per customer",
        sql: `SELECT customer_id FROM fct_customer_revenue GROUP BY customer_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "endstate",
        name: "the mart matches the ref-ordered build exactly",
        isHidden: true,
        sql: `WITH expected(customer_id, name, region, orders, revenue_usd) AS (
  VALUES (101, 'Ada Lovelace',      'us-east', 3, 240.50),
         (102, 'Grace Hopper',      'us-west', 1, 210.25),
         (103, 'Alan Turing',       'eu-west', 2, 184.75),
         (104, 'Katherine Johnson', 'us-east', 1,  60.00),
         (105, 'Jean Bartik',       'eu-west', 1,  95.50)
)
SELECT * FROM (
  SELECT customer_id, name, region, orders, revenue_usd FROM fct_customer_revenue
  EXCEPT
  SELECT customer_id, name, region, orders, revenue_usd FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT customer_id, name, region, orders, revenue_usd FROM expected
  EXCEPT
  SELECT customer_id, name, region, orders, revenue_usd FROM fct_customer_revenue
)`,
      },
      {
        suite: "endstate",
        name: "cancelled money never reached the mart",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT ROUND(SUM(revenue_usd), 2) FROM fct_customer_revenue) <> 791.00`,
      },
    ],
  }),
  practice: {
    id: "de-l8-models-in-dependency-order-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every model in \`model_refs\` with its build depth, as \`(model, depth)\`, shallowest first, over \`model_refs(model, ref_model)\`.

A model that nothing else feeds is a source and sits at depth 0. Any other model sits one level deeper than the deepest thing it reads, so a model with two parents at different depths takes the larger one. Alias the columns exactly \`model\` and \`depth\`, and break ties within a depth by \`model\` ascending. This is the topological sort the tool does for you before it builds anything.`,
    starterCode: `-- Build depth per model: sources are 0, everything else is one past its deepest parent.
WITH RECURSIVE depths(model, depth) AS (
  -- anchor: the sources, the ref_model values that are never themselves a model
  SELECT
  -- recursive step: every model that reads something already placed
)
SELECT model, depth
FROM depths;`,
    hints: [
      "The anchor is `SELECT DISTINCT ref_model, 0 FROM model_refs r WHERE NOT EXISTS (SELECT 1 FROM model_refs x WHERE x.model = r.ref_model)`.",
      "The recursive step walks an edge forward: `SELECT r.model, d.depth + 1 FROM depths d JOIN model_refs r ON r.ref_model = d.model`.",
      "A model reached by two paths appears twice with different depths, so finish with `SELECT model, MAX(depth) AS depth ... GROUP BY model`.",
      "`ORDER BY depth, model` gives the shallowest-first order with a deterministic tiebreak.",
    ],
    singleFile: {
      seedSql: MODEL_REFS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["model", "depth"],
        rows: [
          ["raw_customers", 0],
          ["raw_orders", 0],
          ["stg_customers", 1],
          ["stg_orders", 1],
          ["fct_customer_revenue", 2],
          ["mart_customer_health", 3],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l8-models-in-dependency-order-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns every model that reads more than one ref, with how many it reads, as \`(model, ref_count)\`, over \`model_refs(model, ref_model)\`.`,
      starterCode: `-- Models with more than one incoming ref edge.
SELECT model
FROM model_refs
;`,
      hints: [
        "Group by `model` and count the edges: `COUNT(*) AS ref_count`.",
        "`HAVING COUNT(*) > 1` keeps only the multi-parent models.",
      ],
      referenceSolution: `SELECT model, COUNT(*) AS ref_count
FROM model_refs
GROUP BY model
HAVING COUNT(*) > 1
ORDER BY model;`,
      singleFile: {
        seedSql: MODEL_REFS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["model", "ref_count"],
          rows: [
            ["fct_customer_revenue", 2],
            ["mart_customer_health", 2],
          ],
        },
      },
    },
    {
      id: "de-l8-models-in-dependency-order-drill-2",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the rows \`stg_orders\` would hold, as \`(order_id, customer_id, status, amount_usd, ordered_at)\`, ordered by \`order_id\`, over \`raw_orders\`. A staging model drops cancelled orders and changes nothing else.`,
      starterCode: `-- The SELECT behind stg_orders, written standalone.
SELECT order_id, customer_id, status, amount_usd, ordered_at
FROM raw_orders
;`,
      hints: [
        "The only filter is `WHERE status <> 'cancelled'`.",
        "Add `ORDER BY order_id` so the rows come back in a stable order.",
      ],
      referenceSolution: `SELECT order_id, customer_id, status, amount_usd, ordered_at
FROM raw_orders
WHERE status <> 'cancelled'
ORDER BY order_id;`,
      singleFile: {
        seedSql: RAW_SOURCES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["order_id", "customer_id", "status", "amount_usd", "ordered_at"],
          rows: [
            [1001, 101, "delivered", 120, "2026-06-01"],
            [1002, 101, "shipped", 80.5, "2026-06-03"],
            [1004, 102, "delivered", 210.25, "2026-06-05"],
            [1005, 103, "placed", 35.75, "2026-06-06"],
            [1006, 103, "delivered", 149, "2026-06-07"],
            [1008, 104, "shipped", 60, "2026-06-09"],
            [1009, 105, "delivered", 95.5, "2026-06-10"],
            [1010, 101, "placed", 40, "2026-06-11"],
          ],
        },
      },
    },
    {
      id: "de-l8-models-in-dependency-order-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every model and source that must already be built before \`mart_regional_revenue\` can be built, as \`(model)\`, alphabetically, over \`model_refs_proposed(model, ref_model)\`.

A teammate proposes \`mart_regional_revenue\`, which reads \`fct_customer_revenue\` and also reads \`stg_customers\` directly, and both edges are already in the table. This walk goes the opposite way from the build-depth query: start at the new mart and follow \`ref_model\` backwards until you run out of parents. Report each name once, however many paths reach it, and leave out anything the mart does not depend on.`,
      starterCode: `-- Everything mart_regional_revenue needs before it can build.
WITH RECURSIVE upstream(model) AS (
  -- anchor: what the new mart reads directly
  SELECT
  -- recursive step: what those models read, and so on back to the sources
)
SELECT model
FROM upstream;`,
      hints: [
        "The anchor reads the edge list in the ref_model direction: `SELECT ref_model FROM model_refs_proposed WHERE model = 'mart_regional_revenue'`.",
        "The recursive step walks one edge further back: `SELECT r.ref_model FROM upstream u JOIN model_refs_proposed r ON r.model = u.model`.",
        "`stg_customers` is reached both directly and through `fct_customer_revenue`, so finish with `SELECT DISTINCT model ... ORDER BY model` or the same name comes back twice.",
        "`mart_customer_health` reads the same fact, but nothing the new mart needs, so it must not appear.",
      ],
      referenceSolution: `WITH RECURSIVE upstream(model) AS (
  SELECT ref_model
  FROM model_refs_proposed
  WHERE model = 'mart_regional_revenue'
  UNION ALL
  SELECT r.ref_model
  FROM upstream u
  JOIN model_refs_proposed r ON r.model = u.model
)
SELECT DISTINCT model
FROM upstream
ORDER BY model;`,
      singleFile: {
        seedSql: MODEL_REFS_PROPOSED_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["model"],
          rows: [
            ["fct_customer_revenue"],
            ["raw_customers"],
            ["raw_orders"],
            ["stg_customers"],
            ["stg_orders"],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.4.2 seeds — a staging model under test plus a CI fixture pair.
//
// stg_payments carries one deterministic violation of each generic test, and the invalid
// methods appear at different frequencies so the accepted-values drill has an unambiguous
// order. Two shapes make the violation list's rules gradable rather than decorative:
//   - Payment 9010 breaks TWO different tests (invalid method AND missing parent order), so
//     the list carries one row per violation rather than per payment, and the ordering has to
//     be (payment_id, violation) rather than payment_id alone.
//   - The duplicated payment 9004 also carries an invalid method, so the accepted-values test
//     emits the SAME (payment_id, violation) pair twice. That is the only shape that separates
//     UNION ALL from UNION: two rows with different violations survive UNION untouched
//     (verified against the shipped sql.js WASM), two identical rows do not.
//
// `orders` carries one NULL order_id on purpose. That single NULL is what makes the
// NOT IN versus NOT EXISTS trap real: NOT IN against this parent returns no rows at all,
// so a learner who reaches for it fails the relationships test instead of passing it silently.
// ---------------------------------------------------------------------------

const ORDERS_SEED = `CREATE TABLE orders (
  order_id    INTEGER,   -- one row carries a NULL key, which is what breaks NOT IN
  customer_id INTEGER,
  status      TEXT,
  amount_usd  REAL,
  ordered_at  TEXT
);
INSERT INTO orders (order_id, customer_id, status, amount_usd, ordered_at) VALUES
  (1001, 101, 'delivered', 120.00, '2026-06-01'),
  (1002, 104, 'shipped',    80.50, '2026-06-03'),
  (1003, 102, 'cancelled',  45.00, '2026-06-03'),
  (1004, 102, 'delivered', 210.25, '2026-06-05'),
  (1005, 103, 'placed',     35.75, '2026-06-06'),
  (1006, 105, 'delivered', 149.00, '2026-06-07'),
  (1007, 104, 'cancelled', 300.00, '2026-06-08'),
  (1008, 103, 'shipped',    60.00, '2026-06-09'),
  (NULL, 106, 'placed',      0.00, '2026-06-12');`

const STG_PAYMENTS_SEED = `CREATE TABLE stg_payments (
  payment_id INTEGER,   -- should be unique; 9004 is deliberately duplicated, method and all
  order_id   INTEGER,   -- should exist in orders; two deliberately do not, and 9010 also has a bad method
  method     TEXT,      -- accepted values: card | cash | transfer
  amount_usd REAL       -- should never be NULL
);
INSERT INTO stg_payments (payment_id, order_id, method, amount_usd) VALUES
  (9001, 1001, 'card',         120.00),
  (9002, 1002, 'cash',          80.50),
  (9003, 1003, 'transfer',      45.00),
  (9004, 1004, 'store_credit', 210.25),
  (9004, 1004, 'store_credit', 210.25),
  (9006, 1005, 'card',           NULL),
  (9007, 1006, 'IOU',          149.00),
  (9008, 9999, 'card',          60.00),
  (9009, 1007, 'IOU',           95.50),
  (9010, 9998, 'store_credit',  40.00),
  (9011, 1001, 'card',          15.00),
  (9012, 1002, 'transfer',      22.50);`

const PAYMENTS_TEST_SEED = STG_PAYMENTS_SEED + "\n\n" + ORDERS_SEED

// The CI fixture pair: hand-written input plus the hand-checked correct output. The two
// 2026-06-30 rows are the trap. A filter written as `ordered_at <= '2026-06-30'` compares a
// timestamp against a bare date and silently drops both, which no amount of clean production
// data would ever reveal.
const FIXTURE_SEED = `CREATE TABLE fixture_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  status      TEXT,     -- delivered | cancelled | refunded
  amount_usd  REAL,     -- negative on a refund, zero on a fully discounted order
  ordered_at  TEXT      -- full timestamp, not a bare date
);
INSERT INTO fixture_orders (order_id, customer_id, status, amount_usd, ordered_at) VALUES
  (5001, 201, 'delivered', 100.00, '2026-06-01 00:00:00'),
  (5002, 201, 'cancelled', 250.00, '2026-06-10 09:15:00'),
  (5003, 201, 'delivered',   0.00, '2026-06-12 11:00:00'),
  (5004, 202, 'refunded',  -40.00, '2026-06-18 16:30:00'),
  (5005, 202, 'delivered',  75.50, '2026-06-30 18:45:00'),
  (5006, 203, 'delivered',  60.25, '2026-06-30 23:59:59'),
  (5007, 203, 'delivered',  90.00, '2026-07-01 08:00:00');

CREATE TABLE fixture_expected_order_totals (
  customer_id INTEGER,
  orders      INTEGER,
  revenue_usd REAL
);
INSERT INTO fixture_expected_order_totals (customer_id, orders, revenue_usd) VALUES
  (201, 2, 100.00),
  (202, 2,  35.50),
  (203, 1,  60.25);`

const dataTestsZeroRows: SqlLesson = {
  id: "de-l8-data-tests-zero-rows",
  title: "Data Tests, Unit Tests, and the Grader Behind the Curtain",
  summary:
    "Collapse the four generic tests into one violation list, then build a model against a hand-written fixture the way a unit test does.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "zero-rows-equals-pass",
    "unique / not_null / accepted_values / relationships",
    "UNION ALL violation lists",
    "NOT EXISTS",
    "unit test vs data test",
    "fixtures and expected output",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## You have already written these tests

Level 4's data quality lesson taught the four generic tests and the rule that a test passes at zero rows. Level 5's write-audit-publish lesson taught the gate above them: stage a batch, check freshness, volume, and null rate, publish only on a pass. Neither of those is repeated here. This lesson adds the layer that sits on top, and it starts by telling you something about this course that has been true the whole time.

## The curtain pull

Every workspace exercise you have completed in this course was graded by hidden **assertion queries**. Each one is written to return the rows that are wrong, and it passes when it returns nothing. Here is one, unedited, from the previous lesson:

\`\`\`sql
SELECT customer_id
FROM fct_customer_revenue
GROUP BY customer_id
HAVING COUNT(*) > 1
\`\`\`

That is not a grading trick invented for a learning platform. It is a dbt \`unique\` test, and it is exactly what runs in production every time someone merges a model. A test in this workflow is a \`SELECT\` that returns violating rows, and zero rows means pass. The convention you have been graded against since your first workspace build is the industry convention, which is why it never needed explaining: you were already doing the job.

## Four tests, one violation list

The four generic tests are declared as YAML in a real project, but every one of them compiles down to a query:

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["test", "declared as", "compiles to", "passes when"],
  "rows": [
    ["unique", "unique: payment_id", "GROUP BY payment_id HAVING COUNT(*) > 1", "no key repeats"],
    ["not_null", "not_null: amount_usd", "WHERE amount_usd IS NULL", "no NULLs"],
    ["accepted_values", "values: [card, cash]", "WHERE method NOT IN (...)", "no stray value"],
    ["relationships", "to: ref('orders')", "NOT EXISTS matching parent row", "no orphans"]
  ],
  "highlightCols": ["compiles to"],
  "caption": "Every generic test is a query that returns offending rows. Zero rows returned is a pass."
}
\`\`\`

A test runner does not report four booleans. It reports **which rows failed which test**, because that is the only output an on-call engineer can act on at 3am. So the useful artifact is the four queries stacked into one list of \`(key, violation)\` pairs with \`UNION ALL\`, which is what the Apply builds.

Be careful with the relationships test. \`WHERE order_id NOT IN (SELECT order_id FROM orders)\` looks equivalent to \`NOT EXISTS\` and is not: if the parent table holds a single NULL \`order_id\`, the \`NOT IN\` comparison evaluates to NULL for every row and the test returns nothing at all. It passes silently and forever. \`NOT EXISTS\` has no such hole. The \`orders\` table in this lesson holds exactly one such NULL, so you can watch both versions run and see them disagree.

## Data test versus unit test

dbt 1.8 added **unit tests**, and the distinction is now standard interview vocabulary. It is not a naming quibble, it is two different questions:

- A **data test** runs on real data, on every run, and asks "is today's data sane". It catches a corrupted upstream feed, a new payment method nobody told you about, an orphaned foreign key.
- A **unit test** runs on a **fixed fixture** in CI, before the model ever touches production, and asks "is my SQL logic correct". You hand-write a small input table, hand-write the output you know is correct, and assert your model turns one into the other.

Only the second catches a boundary bug, because clean data passes every data test while your date filter quietly drops the last day of the month. The classic version of that bug is a timestamp column compared against a bare date string: the comparison is still valid SQL, every generic test stays green, and a slice of real rows silently vanishes. This lesson's fixture is built to spring exactly that class of bug, and finding which rows it catches you on is the work.

Two ecosystem names worth one line each: **Great Expectations** is used for validation at the ingestion boundary, and **Soda** for trailing-window anomaly monitoring. Neither replaces the tests above.

**Common mistake:** writing a test that returns a count instead of the offending rows. \`SELECT COUNT(*) FROM stg_payments WHERE amount_usd IS NULL\` always returns exactly one row, so under the zero-rows convention it always fails, and under a "check the number" convention it tells you nothing about which payment to go look at.

**Interview nuance:** "how would you test this pipeline" is a two-layer answer. Data tests on every run for data sanity, unit tests on fixtures in CI for logic, and each layer catches what the other structurally cannot. Candidates who name only data tests have never had correct-looking logic break on data that passed every check.

> **On a real platform this differs.** Here you write the violation query by hand and the fixture is a seeded table. In a real project you declare \`unique\`, \`not_null\`, \`accepted_values\`, and \`relationships\` in a YAML file beside the model, the tool compiles each one into a query, and \`dbt test\` fails the build on any non-zero result. Unit tests are declared with \`given\` and \`expect\` blocks of inline rows, run under \`dbt build\`, and never touch the warehouse's real tables. Severity is configurable per test (\`warn\` versus \`error\`), which is the ledger Level 10 builds.`,
    demoSeedSql: STG_PAYMENTS_SEED,
    demoCode: `-- A unique test, compiled. It returns the offending key, so zero rows means it passed.
SELECT payment_id, COUNT(*) AS copies
FROM stg_payments
GROUP BY payment_id
HAVING COUNT(*) > 1;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l8-data-tests-zero-rows-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every \`stg_payments\` row that violates at least one of the four generic tests, as \`(payment_id, violation)\`, one row per violation, ordered by \`payment_id\` then \`violation\` ascending, over \`stg_payments(payment_id, order_id, method, amount_usd)\` and \`orders(order_id, ...)\`.

Use exactly these four tests and these four violation labels:

- \`'unique_payment_id'\` when a \`payment_id\` appears more than once. Report it once, as one row for that key.
- \`'not_null_amount_usd'\` when \`amount_usd\` is NULL.
- \`'accepted_values_method'\` when \`method\` is not one of \`'card'\`, \`'cash'\`, \`'transfer'\`.
- \`'relationships_order_id'\` when the \`order_id\` has no matching row in \`orders\`.

Alias the columns exactly \`payment_id\` and \`violation\`. Stack the four tests with \`UNION ALL\` rather than \`UNION\`. One payment here breaks two different tests and has to appear under both labels, and one payment is duplicated with the same bad value on both copies, so that finding is reported once per offending row.`,
    starterCode: `-- The four generic tests as one violation list. Zero rows would mean the model is clean.
SELECT payment_id, 'unique_payment_id' AS violation
FROM stg_payments
-- ...

-- UNION ALL the other three tests, then order the whole list by payment_id, violation.
`,
    hints: [
      "The unique test is a grouped query: `GROUP BY payment_id HAVING COUNT(*) > 1`, which reports the repeated key once.",
      "The not_null and accepted_values tests are plain filters over `stg_payments`.",
      "For relationships use `WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_id = p.order_id)` rather than `NOT IN`, which breaks if the parent key is ever NULL.",
      "`UNION ALL` keeps every violation; plain `UNION` would silently collapse two identical findings into one.",
      "Wrap the stacked query in an outer `SELECT ... FROM (...) ORDER BY payment_id, violation`, or put a single `ORDER BY payment_id, violation` after the last branch.",
    ],
    referenceSolution: `SELECT payment_id, 'unique_payment_id' AS violation
FROM stg_payments
GROUP BY payment_id
HAVING COUNT(*) > 1

UNION ALL
SELECT payment_id, 'not_null_amount_usd'
FROM stg_payments
WHERE amount_usd IS NULL

UNION ALL
SELECT payment_id, 'accepted_values_method'
FROM stg_payments
WHERE method NOT IN ('card', 'cash', 'transfer')

UNION ALL
SELECT p.payment_id, 'relationships_order_id'
FROM stg_payments p
WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_id = p.order_id)

ORDER BY payment_id, violation;`,
    singleFile: {
      seedSql: PAYMENTS_TEST_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["payment_id", "violation"],
        rows: [
          [9004, "accepted_values_method"],
          [9004, "accepted_values_method"],
          [9004, "unique_payment_id"],
          [9006, "not_null_amount_usd"],
          [9007, "accepted_values_method"],
          [9008, "relationships_order_id"],
          [9009, "accepted_values_method"],
          [9010, "accepted_values_method"],
          [9010, "relationships_order_id"],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l8-data-tests-zero-rows-practice",
    prompt: `Write a script that builds \`fct_order_totals(customer_id, orders, revenue_usd)\` from \`fixture_orders\` so that it matches \`fixture_expected_order_totals\` exactly, and rebuilds cleanly when the script is run again.

\`fixture_orders\` is a hand-written CI fixture, and \`fixture_expected_order_totals\` is the hand-checked output the model must produce. The model's rule: keep every order placed in June 2026 whose \`status\` is not \`'cancelled'\`, count them per customer as \`orders\`, and sum \`amount_usd\` per customer as \`ROUND(SUM(amount_usd), 2)\`. Refunds carry a negative \`amount_usd\` and zero-value orders carry \`0.00\`; both are real orders and both belong in the totals.

\`ordered_at\` is a full timestamp, so read the fixture's boundary rows carefully before you write the date filter. The hidden assertion is the symmetric difference between your table and the expected fixture, which is precisely what a dbt unit test asserts.`,
    starterCode: `-- Build fct_order_totals from the fixture. The DROP keeps the second run working.
DROP TABLE IF EXISTS fct_order_totals;
CREATE TABLE fct_order_totals AS
SELECT
  customer_id
  -- orders and revenue_usd per customer, over the June 2026 non-cancelled rows
FROM fixture_orders
;`,
    hints: [
      "Group by `customer_id` and alias the aggregates exactly `orders` and `revenue_usd`.",
      "`COUNT(*)` counts every surviving order, including the zero-amount one, which is what the fixture expects.",
      "A refund is a negative amount, so `SUM(amount_usd)` handles it with no special case.",
      "`ordered_at` carries a time component, so check what your upper bound actually compares against before you trust the row count it returns.",
    ],
    seedSql: FIXTURE_SEED,
    checkIdempotency: true,
    idempotencyTables: ["fct_order_totals"],
    assertions: [
      {
        suite: "grain",
        name: "fct_order_totals holds one row per customer",
        sql: `SELECT customer_id FROM fct_order_totals GROUP BY customer_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "unit_test",
        name: "the built table equals the expected fixture exactly",
        sql: `SELECT * FROM (
  SELECT customer_id, orders, revenue_usd FROM fct_order_totals
  EXCEPT
  SELECT customer_id, orders, revenue_usd FROM fixture_expected_order_totals
)
UNION ALL
SELECT * FROM (
  SELECT customer_id, orders, revenue_usd FROM fixture_expected_order_totals
  EXCEPT
  SELECT customer_id, orders, revenue_usd FROM fct_order_totals
)`,
      },
      {
        suite: "boundary",
        name: "the two 2026-06-30 orders were kept, not dropped by the date filter",
        isHidden: true,
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM fct_order_totals WHERE customer_id = 203) <> 1
UNION ALL
SELECT 1 WHERE COALESCE((SELECT orders FROM fct_order_totals WHERE customer_id = 202), -1) <> 2`,
      },
      {
        suite: "boundary",
        name: "the July order was excluded",
        isHidden: true,
        sql: `SELECT 1 WHERE COALESCE((SELECT ROUND(revenue_usd, 2) FROM fct_order_totals WHERE customer_id = 203), -1) <> 60.25`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-data-tests-zero-rows-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns every \`stg_payments\` row whose \`order_id\` has no matching row in \`orders\`, as \`(payment_id, order_id)\`, ordered by \`payment_id\`. Use \`NOT EXISTS\`, which stays correct even when the parent table holds a NULL key.`,
      starterCode: `-- The relationships test on its own.
SELECT p.payment_id, p.order_id
FROM stg_payments p
;`,
      hints: [
        "`WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_id = p.order_id)`.",
        "`NOT IN` over a subquery containing a NULL returns nothing at all, which is why the relationships test is written with `NOT EXISTS`.",
      ],
      referenceSolution: `SELECT p.payment_id, p.order_id
FROM stg_payments p
WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.order_id = p.order_id)
ORDER BY p.payment_id;`,
      singleFile: {
        seedSql: PAYMENTS_TEST_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["payment_id", "order_id"],
          rows: [
            [9008, 9999],
            [9010, 9998],
          ],
        },
      },
    },
    {
      id: "de-l8-data-tests-zero-rows-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every \`method\` in \`stg_payments\` outside the accepted set \`('card', 'cash', 'transfer')\` together with how many rows carry it, as \`(method, row_count)\`, most frequent first. Reporting the frequency is what turns a failing test into a triage decision.`,
      starterCode: `-- Accepted-values test, with the offending value's frequency.
SELECT method
FROM stg_payments
;`,
      hints: [
        "Filter with `WHERE method NOT IN ('card', 'cash', 'transfer')` before grouping.",
        "Group by `method` and count with `COUNT(*) AS row_count`.",
        "`ORDER BY row_count DESC` puts the value worth investigating first.",
      ],
      referenceSolution: `SELECT method, COUNT(*) AS row_count
FROM stg_payments
WHERE method NOT IN ('card', 'cash', 'transfer')
GROUP BY method
ORDER BY row_count DESC;`,
      singleFile: {
        seedSql: STG_PAYMENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["method", "row_count"],
          rows: [
            ["store_credit", 3],
            ["IOU", 2],
          ],
        },
      },
    },
    {
      id: "de-l8-data-tests-zero-rows-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Finance changes the rule: refunded orders no longer count toward customer totals. Write a query that returns the new expected output of the unit test, as \`(customer_id, orders, revenue_usd)\`, ordered by \`customer_id\`, over \`fixture_orders\`. Keep the June 2026 window and keep excluding cancelled orders, and alias \`revenue_usd\` as \`ROUND(SUM(amount_usd), 2)\`. The fixture is the spec, so changing the rule means changing the expected table.`,
      starterCode: `-- The unit test's expected output after refunds are excluded.
SELECT customer_id
FROM fixture_orders
;`,
      hints: [
        "The filter grows one clause: `status NOT IN ('cancelled', 'refunded')`.",
        "Keep the timestamp window `ordered_at >= '2026-06-01 00:00:00' AND ordered_at < '2026-07-01 00:00:00'`.",
        "Group by `customer_id` and alias the aggregates exactly `orders` and `revenue_usd`.",
      ],
      referenceSolution: `SELECT
  customer_id,
  COUNT(*)                    AS orders,
  ROUND(SUM(amount_usd), 2)   AS revenue_usd
FROM fixture_orders
WHERE status NOT IN ('cancelled', 'refunded')
  AND ordered_at >= '2026-06-01 00:00:00'
  AND ordered_at <  '2026-07-01 00:00:00'
GROUP BY customer_id
ORDER BY customer_id;`,
      singleFile: {
        seedSql: FIXTURE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["customer_id", "orders", "revenue_usd"],
          rows: [
            [201, 2, 100],
            [202, 1, 75.5],
            [203, 1, 60.25],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 8.4.3 seeds — the manifest graph grown to eleven edges, the raw sources reseeded
// with the planted violations from 8.4.2, and a run-results log spanning dev and prod.
//
// Two deliberate shapes in this graph. `fct_customer_revenue` is a live model that nothing
// downstream of raw_payments reads, so the Apply's closure is four models rather than seven.
// And `mart_finance_daily` reads BOTH `fct_payments` and `stg_payments` (it reports how many
// payments were staged next to how many reached the fact), so it is reachable from
// raw_payments at two different path lengths. Without that diamond, "report each model at
// its shortest distance" would be a rule the data never exercises.
// ---------------------------------------------------------------------------

const LINEAGE_REFS_SEED = `CREATE TABLE model_refs (
  model     TEXT,
  ref_model TEXT
);
INSERT INTO model_refs (model, ref_model) VALUES
  ('stg_orders',           'raw_orders'),
  ('stg_customers',        'raw_customers'),
  ('stg_payments',         'raw_payments'),
  ('fct_customer_revenue', 'stg_orders'),
  ('fct_customer_revenue', 'stg_customers'),
  ('fct_payments',         'stg_payments'),
  ('fct_payments',         'stg_orders'),
  ('mart_finance_daily',   'fct_payments'),
  ('mart_finance_daily',   'stg_payments'),
  ('mart_exec_kpis',       'fct_payments'),
  ('mart_exec_kpis',       'stg_customers');`

// One row per model build per environment. `built_at` is a full timestamp because the
// promotion question is "is dev ahead of prod", which a bare date cannot answer.
const MODEL_RUNS_SEED = `CREATE TABLE model_runs (
  model    TEXT,
  env      TEXT,   -- dev | prod
  built_at TEXT,
  status   TEXT    -- success | error
);
INSERT INTO model_runs (model, env, built_at, status) VALUES
  ('stg_orders',           'dev',  '2026-06-14 09:00:00', 'success'),
  ('stg_orders',           'prod', '2026-06-14 02:00:00', 'success'),
  ('stg_customers',        'dev',  '2026-06-13 09:05:00', 'success'),
  ('stg_customers',        'prod', '2026-06-14 02:05:00', 'success'),
  ('stg_payments',         'dev',  '2026-06-14 09:10:00', 'success'),
  ('stg_payments',         'prod', '2026-06-14 02:10:00', 'success'),
  ('fct_customer_revenue', 'dev',  '2026-06-14 09:20:00', 'success'),
  ('fct_customer_revenue', 'prod', '2026-06-14 02:20:00', 'error'),
  ('fct_payments',         'dev',  '2026-06-13 09:25:00', 'success'),
  ('fct_payments',         'prod', '2026-06-14 02:25:00', 'success'),
  ('mart_finance_daily',   'dev',  '2026-06-13 09:40:00', 'success'),
  ('mart_finance_daily',   'prod', '2026-06-14 02:40:00', 'success'),
  ('mart_exec_kpis',       'dev',  '2026-06-14 09:45:00', 'success');`

// The capstone's raw layer. raw_payments carries the same four planted violations as 8.4.2,
// plus payment 9013, which passes all four tests and still must not reach the fact because
// its order was cancelled. That is the distinction between a test and a join.
const PROD_RAW_SEED = `CREATE TABLE raw_customers (
  customer_id INTEGER,
  name        TEXT,
  region      TEXT
);
INSERT INTO raw_customers (customer_id, name, region) VALUES
  (101, 'Ada Lovelace',      'us-east'),
  (102, 'Grace Hopper',      'us-west'),
  (103, 'Alan Turing',       'eu-west'),
  (104, 'Katherine Johnson', 'us-east'),
  (105, 'Jean Bartik',       'eu-west');

CREATE TABLE raw_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  status      TEXT,
  amount_usd  REAL,
  ordered_at  TEXT
);
INSERT INTO raw_orders (order_id, customer_id, status, amount_usd, ordered_at) VALUES
  (1001, 101, 'delivered', 120.00, '2026-06-01'),
  (1002, 104, 'shipped',    80.50, '2026-06-03'),
  (1003, 102, 'cancelled',  45.00, '2026-06-03'),
  (1004, 102, 'delivered', 210.25, '2026-06-05'),
  (1005, 103, 'placed',     35.75, '2026-06-06'),
  (1006, 105, 'delivered', 149.00, '2026-06-07'),
  (1007, 104, 'cancelled', 300.00, '2026-06-08'),
  (1008, 103, 'shipped',    60.00, '2026-06-09');

CREATE TABLE raw_payments (
  payment_id INTEGER,
  order_id   INTEGER,
  method     TEXT,
  amount_usd REAL,
  paid_at    TEXT
);
INSERT INTO raw_payments (payment_id, order_id, method, amount_usd, paid_at) VALUES
  (9001, 1001, 'card',     120.00, '2026-06-02'),
  (9002, 1002, 'cash',      80.50, '2026-06-04'),
  (9003, 1004, 'transfer', 210.25, '2026-06-06'),
  (9004, 1005, 'card',      35.75, '2026-06-07'),
  (9004, 1005, 'card',      35.75, '2026-06-07'),
  (9006, 1006, 'card',        NULL, '2026-06-08'),
  (9007, 1008, 'IOU',       60.00, '2026-06-10'),
  (9008, 9999, 'card',      42.00, '2026-06-10'),
  (9009, 1001, 'card',      15.00, '2026-06-11'),
  (9010, 1002, 'transfer',  22.50, '2026-06-11'),
  (9011, 1006, 'cash',      33.25, '2026-06-12'),
  (9012, 1004, 'card',      18.00, '2026-06-12'),
  (9013, 1003, 'card',      45.00, '2026-06-13');`

const lineageDevProd: SqlLesson = {
  id: "de-l8-lineage-dev-prod",
  title: "Lineage, Impact Analysis, and Dev vs Prod",
  summary:
    "Answer what breaks downstream when a source changes, separate dev builds from prod builds, then ship the level capstone unaided.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "lineage and impact analysis",
    "downstream closure",
    "recursive CTE",
    "dev and prod environments",
    "deployment discipline",
    "end-to-end pipeline composition",
    "per-row quarantine",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Lineage is the ref graph read in both directions

The previous lesson walked the graph forwards to decide what to build first. Read the same edges backwards from a changed source and you get **impact analysis**: the set of everything that would break. Same table, same recursive closure, opposite direction, and it is the question every schema-change email should already have answered.

\`\`\`csdiagram
{
  "type": "topology",
  "title": "The manifest graph, and the closure of raw_payments",
  "layout": "lr",
  "nodes": [
    { "id": "raw_orders", "label": "raw_orders", "kind": "db" },
    { "id": "raw_customers", "label": "raw_customers", "kind": "db" },
    { "id": "raw_payments", "label": "raw_payments", "kind": "db" },
    { "id": "stg_orders", "label": "stg_orders", "kind": "service" },
    { "id": "stg_customers", "label": "stg_customers", "kind": "service" },
    { "id": "stg_payments", "label": "stg_payments", "kind": "service" },
    { "id": "fct_customer_revenue", "label": "fct_customer_revenue", "kind": "service" },
    { "id": "fct_payments", "label": "fct_payments", "kind": "service" },
    { "id": "mart_finance_daily", "label": "mart_finance_daily", "kind": "service" },
    { "id": "mart_exec_kpis", "label": "mart_exec_kpis", "kind": "service" }
  ],
  "edges": [
    { "from": "raw_orders", "to": "stg_orders" },
    { "from": "raw_customers", "to": "stg_customers" },
    { "from": "raw_payments", "to": "stg_payments" },
    { "from": "stg_orders", "to": "fct_customer_revenue" },
    { "from": "stg_customers", "to": "fct_customer_revenue" },
    { "from": "stg_payments", "to": "fct_payments" },
    { "from": "stg_orders", "to": "fct_payments" },
    { "from": "fct_payments", "to": "mart_finance_daily" },
    { "from": "stg_payments", "to": "mart_finance_daily" },
    { "from": "fct_payments", "to": "mart_exec_kpis" },
    { "from": "stg_customers", "to": "mart_exec_kpis" }
  ],
  "stages": [
    { "adds": ["raw_orders", "raw_customers", "raw_payments"], "note": "Three sources. Ingestion owns these; the transformation layer only reads them." },
    { "adds": ["stg_orders", "stg_customers", "stg_payments"], "note": "One staging model per source. Depth 1, and the first place a rename can break something." },
    { "adds": ["fct_customer_revenue", "fct_payments"], "note": "Facts join staging models. fct_payments is the only fact that reads stg_payments; watch what the marts do next." },
    { "adds": ["mart_finance_daily", "mart_exec_kpis"], "note": "Change raw_payments and four models are affected, not seven. fct_customer_revenue is untouched." }
  ],
  "caption": "Impact analysis is a reachable set, not the whole project. Naming the wrong set is how a change gets blocked for no reason."
}
\`\`\`

The four models reachable from \`raw_payments\` are \`stg_payments\`, \`fct_payments\`, \`mart_finance_daily\`, and \`mart_exec_kpis\`. \`fct_customer_revenue\` sits in the same project and is not affected at all. That distinction is the entire value of lineage: it turns "we might break something" into a list.

Look closely at \`mart_finance_daily\`. It reads \`fct_payments\`, and it also reads \`stg_payments\` directly, because it reports how many payments were staged next to how many reached the fact. That makes it reachable from \`raw_payments\` by two paths of different lengths, two hops and three, and it is why an impact query has to report each model once at its **shortest** distance rather than once per path. A closure that lists the same mart twice is a closure nobody will read twice.

Lineage is also the fifth of the five observability pillars, alongside freshness, volume, schema, and distribution. Four of them tell you a table is wrong. Lineage tells you who else is now wrong because of it.

## Dev and prod are two targets, not two codebases

The model SQL never changes between environments. What changes is the **target**: a connection profile that says which schema the compiled DDL writes into. On your branch the tool builds into a personal dev schema; on merge, the scheduled production job builds into the prod schema from the same files.

In this lesson that separation is simulated with a \`prod_\` table prefix, and the discipline it encodes is worth stating plainly: you never fix data by editing a production table. You change the model, build it in dev, run the tests there, and promote by merging. A hotfix typed straight into prod is invisible to the next scheduled run, which will overwrite it with the same wrong answer.

\`model_runs\` records what was actually built where and whether it succeeded, which is how you answer two questions no dashboard shows you: which models have never built successfully in prod, and which models are ahead in dev and waiting to be promoted.

## The capstone

The Practice below composes everything in Level 8: build order from the graph, the four data tests, per-row quarantine of the rows that fail them, and a script that survives the grader running it twice. It ships with no scaffold and no hints, only the goal state, because that is the shape of the take-home a junior data engineering loop actually assigns.

One design decision inside it is worth flagging before you start. A payment can pass all four data tests and still be absent from the fact, because its order was cancelled and never reached staging. A test answers "is this row valid". A join answers "does this row belong". Do not try to solve the second with the first, and note that the daily mart is the place that difference becomes visible: one day in the seed has a staged payment and no fact row at all.

**Common mistake:** quarantining into a table that is appended rather than rebuilt. The rejects table grows on every run, the same bad payment appears five times by Friday, and the "new failures today" number is meaningless. Rebuild the rejects table with the rest of the graph.

**Interview nuance:** "a source column is being renamed, what do you do" is answered lineage-first, in this order: enumerate the downstream closure from the graph, fix every model in it, rebuild in dev, run the tests, then promote. Candidates who start with "I would search the codebase for the column name" are describing the manual version of a query the manifest already answers.

> **On a real platform this differs.** Here the graph is a \`model_refs\` table you query yourself. In a real project the tool serves the same closure from its compiled manifest, and \`dbt build --select source:shop.raw_payments+\` builds exactly the models this lesson's Apply returns. A bare \`raw_payments+\` would match nothing, because the default selector method looks at models, seeds, snapshots, and tests, and a source has to be named with the \`source:\` method. dbt Fusion extends the closure to column-level lineage, so it narrows to models that read the specific renamed column rather than the whole table, and an open lineage standard such as OpenLineage, or a catalog such as Microsoft Purview or DataHub, stitches graphs across tools. The idea is identical: an edge list, walked transitively.`,
    demoSeedSql: MODEL_RUNS_SEED,
    demoCode: `-- The run-results log: one row per model build per environment.
-- The same model SQL produced both rows; only the target schema differed.
SELECT model, env, built_at, status
FROM model_runs
ORDER BY env, built_at;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l8-lineage-dev-prod-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every model downstream of \`raw_payments\`, as \`(model, depth)\`, nearest first, over \`model_refs(model, ref_model)\`.

A model that reads \`raw_payments\` directly is at depth 1, a model that reads that model is at depth 2, and so on. Report each model once, at its **shortest** distance from the source. Alias the columns exactly \`model\` and \`depth\`, and break ties within a depth by \`model\` ascending.

This is impact analysis: the exact list you would put in the email before renaming a column in \`raw_payments\`. Models that are not reachable from it must not appear.`,
    starterCode: `-- Everything that breaks if raw_payments changes.
WITH RECURSIVE downstream(model, depth) AS (
  -- anchor: the models that read raw_payments directly
  SELECT
  -- recursive step: follow the edges forward, one level at a time
)
SELECT model, depth
FROM downstream;`,
    hints: [
      "The anchor filters the edge list: `SELECT model, 1 FROM model_refs WHERE ref_model = 'raw_payments'`.",
      "The recursive step joins the working set back to the edges: `SELECT r.model, d.depth + 1 FROM downstream d JOIN model_refs r ON r.ref_model = d.model`.",
      "A model reachable by two paths appears twice, so collapse with `SELECT model, MIN(depth) AS depth ... GROUP BY model` for the shortest distance.",
      "`ORDER BY depth, model` gives nearest first with a deterministic tiebreak.",
    ],
    referenceSolution: `WITH RECURSIVE downstream(model, depth) AS (
  SELECT model, 1
  FROM model_refs
  WHERE ref_model = 'raw_payments'
  UNION ALL
  SELECT r.model, d.depth + 1
  FROM downstream d
  JOIN model_refs r ON r.ref_model = d.model
)
SELECT model, MIN(depth) AS depth
FROM downstream
GROUP BY model
ORDER BY depth, model;`,
    singleFile: {
      seedSql: LINEAGE_REFS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["model", "depth"],
        rows: [
          ["stg_payments", 1],
          ["fct_payments", 2],
          ["mart_finance_daily", 2],
          ["mart_exec_kpis", 3],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l8-lineage-dev-prod-practice",
    prompt: `Write a script that builds the production tables for the payments graph from \`raw_customers\`, \`raw_orders\`, and \`raw_payments\`, publishing only rows that pass the four data tests, quarantining the rest, and surviving a rerun. The grader runs your script twice.

Goal state, seven tables:

- \`prod_stg_orders(order_id, customer_id, status, amount_usd, ordered_at)\`: every non-cancelled \`raw_orders\` row.
- \`prod_stg_customers(customer_id, name, region)\`: every \`raw_customers\` row.
- \`prod_payments_rejects(payment_id, order_id, reason)\`: one row per offending \`payment_id\` and reason, with \`reason\` exactly \`'duplicate_payment_id'\` when the \`payment_id\` repeats, \`'null_amount_usd'\` when \`amount_usd\` is NULL, \`'invalid_method'\` when \`method\` is outside \`('card', 'cash', 'transfer')\`, and \`'missing_order'\` when the \`order_id\` is absent from \`raw_orders\`.
- \`prod_stg_payments(payment_id, order_id, method, amount_usd, paid_at)\`: every \`raw_payments\` row whose \`payment_id\` is not in the rejects.
- \`prod_fct_payments(payment_id, order_id, customer_id, method, amount_usd, paid_at)\`: \`prod_stg_payments\` joined to \`prod_stg_orders\`, carrying the order's \`customer_id\`.
- \`prod_mart_finance_daily(paid_on, staged_payments, payments, revenue_usd)\`: one row per \`paid_at\` value in \`prod_stg_payments\`, where \`staged_payments\` counts the payments staged that day, \`payments\` counts how many of them reached \`prod_fct_payments\`, and \`revenue_usd\` is \`ROUND(SUM(amount_usd), 2)\` over those fact rows. A day on which nothing reached the fact still gets a row, with \`0\` and \`0.0\`.
- \`prod_mart_exec_kpis(region, customers, payments, revenue_usd)\`: one row per region that has at least one row in \`prod_fct_payments\`, joining \`prod_fct_payments\` to \`prod_stg_customers\` for the region, where \`customers\` is \`COUNT(DISTINCT prod_fct_payments.customer_id)\` (customers who actually paid, not customers in the region), \`payments\` is the number of \`prod_fct_payments\` rows, and \`revenue_usd\` is \`ROUND(SUM(amount_usd), 2)\`.

Build them in an order the dependencies allow.`,
    starterCode: `-- Level 8 capstone. Goal state only: build the seven prod_ tables from the three raw
-- sources, publish only rows that pass the four data tests, quarantine the rest with a
-- reason, and make the whole script safe to run twice.
`,
    hints: [],
    seedSql: PROD_RAW_SEED,
    checkIdempotency: true,
    idempotencyTables: [
      "prod_stg_orders",
      "prod_stg_customers",
      "prod_stg_payments",
      "prod_fct_payments",
      "prod_payments_rejects",
      "prod_mart_finance_daily",
      "prod_mart_exec_kpis",
    ],
    assertions: [
      {
        suite: "staging",
        name: "prod_stg_orders holds the six non-cancelled orders",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM prod_stg_orders) <> 6`,
      },
      {
        suite: "staging",
        name: "prod_stg_customers passes all five customers through",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM prod_stg_customers) <> 5`,
      },
      {
        suite: "quarantine",
        name: "prod_payments_rejects holds exactly the four offending payments with the right reasons",
        sql: `WITH expected(payment_id, order_id, reason) AS (
  VALUES (9004, 1005, 'duplicate_payment_id'),
         (9006, 1006, 'null_amount_usd'),
         (9007, 1008, 'invalid_method'),
         (9008, 9999, 'missing_order')
)
SELECT * FROM (
  SELECT payment_id, order_id, reason FROM prod_payments_rejects
  EXCEPT
  SELECT payment_id, order_id, reason FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT payment_id, order_id, reason FROM expected
  EXCEPT
  SELECT payment_id, order_id, reason FROM prod_payments_rejects
)`,
      },
      {
        suite: "quarantine",
        name: "prod_payments_rejects was rebuilt, not appended (exactly four rows after two runs)",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM prod_payments_rejects) <> 4`,
      },
      {
        suite: "publish",
        name: "no quarantined payment leaked into prod_stg_payments",
        sql: `SELECT p.payment_id FROM prod_stg_payments p
WHERE p.payment_id IN (SELECT payment_id FROM prod_payments_rejects)`,
      },
      {
        suite: "publish",
        name: "prod_stg_payments holds the eight surviving payments",
        sql: `SELECT 1 WHERE (SELECT COUNT(*) FROM prod_stg_payments) <> 8`,
      },
      {
        suite: "fact",
        name: "prod_fct_payments matches the published payments joined to live orders",
        isHidden: true,
        sql: `WITH expected(payment_id, order_id, customer_id, method, amount_usd, paid_at) AS (
  VALUES (9001, 1001, 101, 'card',     120.00, '2026-06-02'),
         (9002, 1002, 104, 'cash',      80.50, '2026-06-04'),
         (9003, 1004, 102, 'transfer', 210.25, '2026-06-06'),
         (9009, 1001, 101, 'card',      15.00, '2026-06-11'),
         (9010, 1002, 104, 'transfer',  22.50, '2026-06-11'),
         (9011, 1006, 105, 'cash',      33.25, '2026-06-12'),
         (9012, 1004, 102, 'card',      18.00, '2026-06-12')
)
SELECT * FROM (
  SELECT payment_id, order_id, customer_id, method, amount_usd, paid_at FROM prod_fct_payments
  EXCEPT
  SELECT payment_id, order_id, customer_id, method, amount_usd, paid_at FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT payment_id, order_id, customer_id, method, amount_usd, paid_at FROM expected
  EXCEPT
  SELECT payment_id, order_id, customer_id, method, amount_usd, paid_at FROM prod_fct_payments
)`,
      },
      {
        suite: "fact",
        name: "payment 9013 passed every test but its cancelled order kept it out of the fact",
        sql: `SELECT payment_id FROM prod_fct_payments WHERE payment_id = 9013`,
      },
      {
        suite: "mart",
        name: "prod_mart_finance_daily reconciles staged payments against the fact, day by day",
        isHidden: true,
        sql: `WITH expected(paid_on, staged_payments, payments, revenue_usd) AS (
  VALUES ('2026-06-02', 1, 1, 120.00),
         ('2026-06-04', 1, 1,  80.50),
         ('2026-06-06', 1, 1, 210.25),
         ('2026-06-11', 2, 2,  37.50),
         ('2026-06-12', 2, 2,  51.25),
         ('2026-06-13', 1, 0,   0.00)
)
SELECT * FROM (
  SELECT paid_on, staged_payments, payments, revenue_usd FROM prod_mart_finance_daily
  EXCEPT
  SELECT paid_on, staged_payments, payments, revenue_usd FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT paid_on, staged_payments, payments, revenue_usd FROM expected
  EXCEPT
  SELECT paid_on, staged_payments, payments, revenue_usd FROM prod_mart_finance_daily
)`,
      },
      {
        suite: "mart",
        name: "prod_mart_exec_kpis matches the regional rollup exactly",
        isHidden: true,
        sql: `WITH expected(region, customers, payments, revenue_usd) AS (
  VALUES ('eu-west', 1, 1,  33.25),
         ('us-east', 2, 4, 238.00),
         ('us-west', 1, 2, 228.25)
)
SELECT * FROM (
  SELECT region, customers, payments, revenue_usd FROM prod_mart_exec_kpis
  EXCEPT
  SELECT region, customers, payments, revenue_usd FROM expected
)
UNION ALL
SELECT * FROM (
  SELECT region, customers, payments, revenue_usd FROM expected
  EXCEPT
  SELECT region, customers, payments, revenue_usd FROM prod_mart_exec_kpis
)`,
      },
    ],
  }),
  extraPractice: [
    {
      id: "de-l8-lineage-dev-prod-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every model in \`model_runs\` that has never built successfully in prod, as \`(model)\`, alphabetically. A model with a failed prod run and a model that has never run in prod at all both belong on this list.`,
      starterCode: `-- Models with no successful prod build.
SELECT DISTINCT model
FROM model_runs
;`,
      hints: [
        "Start from every model the log knows about: `SELECT DISTINCT model FROM model_runs`.",
        "Exclude the ones that have a successful prod run with `NOT EXISTS (SELECT 1 FROM model_runs s WHERE s.model = ... AND s.env = 'prod' AND s.status = 'success')`.",
        "An anti-join catches both cases at once: an errored prod run and no prod run at all.",
      ],
      referenceSolution: `SELECT DISTINCT r.model
FROM model_runs r
WHERE NOT EXISTS (
  SELECT 1 FROM model_runs s
  WHERE s.model = r.model AND s.env = 'prod' AND s.status = 'success'
)
ORDER BY r.model;`,
      singleFile: {
        seedSql: MODEL_RUNS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["model"],
          rows: [["fct_customer_revenue"], ["mart_exec_kpis"]],
        },
      },
    },
    {
      id: "de-l8-lineage-dev-prod-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the promotion candidates, the models whose latest dev build is newer than their latest prod build, as \`(model, dev_built_at, prod_built_at)\`, ordered by \`model\`, over \`model_runs\`. A model that has never built in prod is not a promotion candidate, it is an incident.`,
      starterCode: `-- Models where dev is ahead of prod.
SELECT model
FROM model_runs
;`,
      hints: [
        "Reduce each environment to one row per model first: `MAX(built_at)` grouped by `model`, filtered to `env = 'dev'` and to `env = 'prod'`.",
        "Two CTEs joined on `model` puts the two timestamps side by side.",
        "An inner join drops the model with no prod run, which is what the prompt asks for; keep the filter `dev_built_at > prod_built_at`.",
      ],
      referenceSolution: `WITH dev AS (
  SELECT model, MAX(built_at) AS dev_built_at
  FROM model_runs
  WHERE env = 'dev'
  GROUP BY model
),
prod AS (
  SELECT model, MAX(built_at) AS prod_built_at
  FROM model_runs
  WHERE env = 'prod'
  GROUP BY model
)
SELECT d.model, d.dev_built_at, p.prod_built_at
FROM dev d
JOIN prod p ON p.model = d.model
WHERE d.dev_built_at > p.prod_built_at
ORDER BY d.model;`,
      singleFile: {
        seedSql: MODEL_RUNS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["model", "dev_built_at", "prod_built_at"],
          rows: [
            ["fct_customer_revenue", "2026-06-14 09:20:00", "2026-06-14 02:20:00"],
            ["stg_orders", "2026-06-14 09:00:00", "2026-06-14 02:00:00"],
            ["stg_payments", "2026-06-14 09:10:00", "2026-06-14 02:10:00"],
          ],
        },
      },
    },
  ],
}

export const level8Module4: SqlModule = {
  id: "de-l8-transformation-workflow",
  title: "Module 8.4: The Transformation Workflow",
  description:
    "The analytics-engineering workflow behind every dbt line on a job description: models as SELECTs built in ref order, data tests and unit tests as queries that pass at zero rows, lineage as a queryable graph, and a dev-to-prod capstone that survives a rerun.",
  lessons: [modelsInDependencyOrder, dataTestsZeroRows, lineageDevProd],
}
