/**
 * Firestore helper functions for creating and managing user data
 */

import { db } from "./firebase"
import { doc, setDoc, getDoc, collection, query, where, getDocs } from "firebase/firestore"
import { Profile, ProfileQuota } from "./types"
import { PRICING_CONFIG } from "./config"

/**
 * Create or update user profile in Firestore
 */
export async function createOrUpdateProfile(
  userId: string,
  email: string,
  displayName?: string | null,
  photoURL?: string | null
): Promise<Profile> {
  const profileRef = doc(db, "profiles", userId)
  const profileSnap = await getDoc(profileRef)

  const profileData: Profile = {
    id: userId,
    email: email,
    full_name: displayName || undefined,
    avatar_url: photoURL || undefined,
    subscription_tier: "free",
    created_at: profileSnap.exists() 
      ? profileSnap.data().created_at 
      : new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }

  await setDoc(profileRef, profileData, { merge: true })
  return profileData
}

/**
 * Get user profile from Firestore
 * If user has Stripe subscription info but tier is free, sync from Stripe
 */
export async function getUserProfile(userId: string, syncStripe: boolean = true): Promise<Profile | null> {
  const profileRef = doc(db, "profiles", userId)
  const profileSnap = await getDoc(profileRef)

  if (!profileSnap.exists()) {
    return null
  }

  const profile = profileSnap.data() as Profile

  // If user has Stripe IDs but subscription_tier is free, sync from Stripe
  if (syncStripe && profile.subscription_tier === "free" && 
      (profile.stripe_subscription_id || profile.stripe_customer_id)) {
    try {
      const { syncSubscriptionFromStripe } = await import("./stripe-helpers")
      const syncedProfile = await syncSubscriptionFromStripe(userId)
      return syncedProfile || profile
    } catch (syncError) {
      console.error("Error syncing subscription from Stripe:", syncError)
      // Return existing profile if sync fails
      return profile
    }
  }

  return profile
}

/**
 * Initialize user quota for the current month
 */
export async function initializeUserQuota(userId: string, subscriptionTier: "free" | "pro" | "enterprise" = "free"): Promise<ProfileQuota> {
  const now = new Date()
  const periodStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59)

  // Query by user_id only (no composite index needed)
  const quotaQuery = query(
    collection(db, "profile_quota"),
    where("user_id", "==", userId)
  )

  const quotaSnap = await getDocs(quotaQuery)

  // Filter by date range in memory to avoid composite index requirement
  if (!quotaSnap.empty) {
    const currentPeriodQuota = quotaSnap.docs
      .map(doc => doc.data() as ProfileQuota)
      .find(quota => {
        const quotaStart = new Date(quota.period_start)
        return quotaStart >= periodStart && quotaStart <= periodEnd
      })
    
    if (currentPeriodQuota) {
      // Update quota limit if subscription tier changed
      const sessionsLimit = subscriptionTier === "pro" 
        ? PRICING_CONFIG.pro.sessionsPerMonth 
        : PRICING_CONFIG.free.sessionsPerMonth
      
      // If limit changed, update it
      if (currentPeriodQuota.sessions_limit !== sessionsLimit) {
        const quotaRef = quotaSnap.docs.find(doc => {
          const quota = doc.data() as ProfileQuota
          const quotaStart = new Date(quota.period_start)
          return quotaStart >= periodStart && quotaStart <= periodEnd
        })?.ref
        
        if (quotaRef) {
          await setDoc(quotaRef, {
            sessions_limit: sessionsLimit,
            updated_at: new Date().toISOString(),
          }, { merge: true })
          currentPeriodQuota.sessions_limit = sessionsLimit
        }
      }
      
      return currentPeriodQuota
    }
  }

  // Create new quota
  const sessionsLimit = subscriptionTier === "pro" 
    ? PRICING_CONFIG.pro.sessionsPerMonth 
    : PRICING_CONFIG.free.sessionsPerMonth

  const quotaData: ProfileQuota = {
    id: "", // Will be auto-generated by Firestore
    user_id: userId,
    sessions_used: 0,
    sessions_limit: sessionsLimit,
    period_start: periodStart.toISOString(),
    period_end: periodEnd.toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }

  const quotaRef = doc(collection(db, "profile_quota"))
  quotaData.id = quotaRef.id
  await setDoc(quotaRef, quotaData)

  return quotaData
}

/**
 * Check if user has available sessions
 */
export async function checkUsageLimit(userId: string): Promise<{ allowed: boolean; used: number; limit: number }> {
  const profile = await getUserProfile(userId)
  const quota = await initializeUserQuota(userId, profile?.subscription_tier || "free")

  return {
    allowed: quota.sessions_used < quota.sessions_limit,
    used: quota.sessions_used,
    limit: quota.sessions_limit,
  }
}

/**
 * Create a new interview session
 */
export async function createInterviewSession(
  userId: string,
  scenarioTitle: string,
  scenarioType: string,
  difficulty: "easy" | "medium" | "hard"
): Promise<string> {
  const sessionRef = doc(collection(db, "interview_sessions"))
  const sessionData = {
    id: sessionRef.id,
    user_id: userId,
    topic: scenarioTitle,
    type: scenarioType,
    difficulty: difficulty,
    started_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
  
  await setDoc(sessionRef, sessionData)
  return sessionRef.id
}

/**
 * Update interview session on completion
 */
export async function updateInterviewSession(
  sessionId: string,
  performanceScore?: number,
  feedback?: string
): Promise<void> {
  const sessionRef = doc(db, "interview_sessions", sessionId)
  await setDoc(sessionRef, {
    completed_at: new Date().toISOString(),
    performance_score: performanceScore,
    feedback: feedback,
    updated_at: new Date().toISOString(),
  }, { merge: true })
}

/**
 * Increment session usage
 */
export async function incrementSessionUsage(userId: string): Promise<void> {
  const profile = await getUserProfile(userId)
  const quota = await initializeUserQuota(userId, profile?.subscription_tier || "free")

  const quotaQuery = query(
    collection(db, "profile_quota"),
    where("user_id", "==", userId),
    where("id", "==", quota.id)
  )

  const quotaSnap = await getDocs(quotaQuery)
  
  if (!quotaSnap.empty) {
    const quotaRef = quotaSnap.docs[0].ref
    await setDoc(quotaRef, {
      sessions_used: quota.sessions_used + 1,
      updated_at: new Date().toISOString(),
    }, { merge: true })
  }
}

/**
 * Update user quota when subscription tier changes
 * This ensures existing quotas get updated limits
 */
export async function updateQuotaForSubscriptionTier(userId: string, subscriptionTier: "free" | "pro" | "enterprise"): Promise<void> {
  // This will update the quota limit if it exists, or create a new one
  await initializeUserQuota(userId, subscriptionTier)
}

