/**
 * Firestore helper functions for creating and managing user data
 */

import { db } from "./firebase"
import { doc, setDoc, getDoc, collection, query, where, getDocs } from "firebase/firestore"
import { Profile, ProfileQuota } from "./types"
import { PRICING_CONFIG } from "./config"

/**
 * Create or update user profile in Firestore
 */
export async function createOrUpdateProfile(
  userId: string,
  email: string,
  displayName?: string | null,
  photoURL?: string | null
): Promise<Profile> {
  const profileRef = doc(db, "profiles", userId)
  const profileSnap = await getDoc(profileRef)

  const profileData: Profile = {
    id: userId,
    email: email,
    full_name: displayName || undefined,
    avatar_url: photoURL || undefined,
    subscription_tier: "free",
    created_at: profileSnap.exists() 
      ? profileSnap.data().created_at 
      : new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }

  await setDoc(profileRef, profileData, { merge: true })
  return profileData
}

/**
 * Get user profile from Firestore
 */
export async function getUserProfile(userId: string): Promise<Profile | null> {
  const profileRef = doc(db, "profiles", userId)
  const profileSnap = await getDoc(profileRef)

  if (profileSnap.exists()) {
    return profileSnap.data() as Profile
  }
  return null
}

/**
 * Initialize user quota for the current month
 */
export async function initializeUserQuota(userId: string, subscriptionTier: "free" | "pro" | "enterprise" = "free"): Promise<ProfileQuota> {
  const now = new Date()
  const periodStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59)

  // Check if quota already exists for this period
  const quotaQuery = query(
    collection(db, "profile_quota"),
    where("user_id", "==", userId),
    where("period_start", ">=", periodStart.toISOString()),
    where("period_start", "<=", periodEnd.toISOString())
  )

  const quotaSnap = await getDocs(quotaQuery)

  if (!quotaSnap.empty) {
    return quotaSnap.docs[0].data() as ProfileQuota
  }

  // Create new quota
  const sessionsLimit = subscriptionTier === "pro" 
    ? PRICING_CONFIG.pro.sessionsPerMonth 
    : PRICING_CONFIG.free.sessionsPerMonth

  const quotaData: ProfileQuota = {
    id: "", // Will be auto-generated by Firestore
    user_id: userId,
    sessions_used: 0,
    sessions_limit: sessionsLimit,
    period_start: periodStart.toISOString(),
    period_end: periodEnd.toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }

  const quotaRef = doc(collection(db, "profile_quota"))
  quotaData.id = quotaRef.id
  await setDoc(quotaRef, quotaData)

  return quotaData
}

/**
 * Check if user has available sessions
 */
export async function checkUsageLimit(userId: string): Promise<{ allowed: boolean; used: number; limit: number }> {
  const profile = await getUserProfile(userId)
  const quota = await initializeUserQuota(userId, profile?.subscription_tier || "free")

  return {
    allowed: quota.sessions_used < quota.sessions_limit,
    used: quota.sessions_used,
    limit: quota.sessions_limit,
  }
}

/**
 * Increment session usage
 */
export async function incrementSessionUsage(userId: string): Promise<void> {
  const profile = await getUserProfile(userId)
  const quota = await initializeUserQuota(userId, profile?.subscription_tier || "free")

  const quotaQuery = query(
    collection(db, "profile_quota"),
    where("user_id", "==", userId),
    where("id", "==", quota.id)
  )

  const quotaSnap = await getDocs(quotaQuery)
  
  if (!quotaSnap.empty) {
    const quotaRef = quotaSnap.docs[0].ref
    await setDoc(quotaRef, {
      sessions_used: quota.sessions_used + 1,
      updated_at: new Date().toISOString(),
    }, { merge: true })
  }
}

