// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { CompiledWorkbook } from "./types"
import type { SprintPublic, WorkbookSummary } from "@/lib/sprint-labs/types"
import { fixtureDemoWorkbook } from "./fixture-demo/workbook"
import { fixtureDemoSprint01 } from "./fixture-demo/sprints/sprint-01"
import { demo101Ticket } from "./fixture-demo/tickets/DEMO-101"
import { demo102Ticket } from "./fixture-demo/tickets/DEMO-102"

const COMPILED_WORKBOOKS: Record<string, CompiledWorkbook> = {
  "fixture-demo": {
    summary: fixtureDemoWorkbook,
    sprints: [fixtureDemoSprint01],
    ticketsByKey: {
      "DEMO-101": demo101Ticket,
      "DEMO-102": demo102Ticket,
    },
  },
}

export function listWorkbookSummaries(): WorkbookSummary[] {
  return Object.values(COMPILED_WORKBOOKS)
    .map((w) => w.summary)
    .sort((a, b) => a.id.localeCompare(b.id))
}

export function getWorkbookSummary(workbookId: string): WorkbookSummary | undefined {
  return COMPILED_WORKBOOKS[workbookId]?.summary
}

export function getWorkbookSprints(workbookId: string): SprintPublic[] | undefined {
  return COMPILED_WORKBOOKS[workbookId]?.sprints
}

export function getSprint(workbookId: string, sprintNumber: number): SprintPublic | undefined {
  return COMPILED_WORKBOOKS[workbookId]?.sprints.find((s) => s.number === sprintNumber)
}

export function getTicket(workbookId: string, ticketKey: string) {
  return COMPILED_WORKBOOKS[workbookId]?.ticketsByKey[ticketKey]
}

export function workbookIds(): string[] {
  return Object.keys(COMPILED_WORKBOOKS).sort()
}
