// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
/**
 * Sealed sprint-labs registry (SERVER-ONLY). The ONLY loader for per-ticket
 * sealed modules; generalizes lib/scenarios/sealed/registry.server.ts (the
 * bugfix pack precedent) for a two-part (workbookId, ticketKey) key. Import
 * graph enforced by lib/sprint-labs/__tests__/sealing.test.ts.
 */
import type { SealedTicketContent } from "./types"

if (typeof window !== "undefined") {
  throw new Error("Sealed sprint-labs content must never load in the browser.")
}

const SEALED_TICKET_LOADERS: Record<string, () => Promise<{ sealed: SealedTicketContent }>> = {
  "fixture-demo:DEMO-101": () => import("./fixture-demo/DEMO-101.server"),
  "fixture-demo:DEMO-102": () => import("./fixture-demo/DEMO-102.server"),
}

function loaderKey(workbookId: string, ticketKey: string): string {
  return workbookId + ":" + ticketKey
}

export function hasSealedTicket(workbookId: string, ticketKey: string): boolean {
  return Object.prototype.hasOwnProperty.call(
    SEALED_TICKET_LOADERS,
    loaderKey(workbookId, ticketKey)
  )
}

export async function loadSealedTicket(
  workbookId: string,
  ticketKey: string
): Promise<SealedTicketContent | null> {
  const loader = SEALED_TICKET_LOADERS[loaderKey(workbookId, ticketKey)]
  if (!loader) return null
  const mod = await loader()
  return mod.sealed
}

export function sealedTicketRegistryKeys(): string[] {
  return Object.keys(SEALED_TICKET_LOADERS)
}
