/**
 * Data Engineering Level 10, Module 10.4 — Cost & Governance Operations.
 *
 * The level closes on the two things a data platform gets audited for: what it spends and
 * who can see what. RESEARCH.md is specific about both. §3.4 gives the serverless meter
 * ($5.00/TB scanned, 10 MB minimum) plus the documented incident where one team's Athena
 * spend doubled in a quarter with 70% of it repeated scans of the same data; finding 5 makes
 * "convert to Parquet and partition it" simultaneously the most repeated correct exam answer
 * and the top real-world cost lever (~96.7% cited reduction), with the small-files problem
 * (§3.4, target 128 MB-1 GB per file) as the thing that erodes it; §3.7 gives IAM evaluation
 * (roles not keys, explicit deny wins) and the canonical Athena results-bucket Access Denied;
 * §3.1 weights DEA-C01 Domain 4 (Security & Governance) at 18% of the exam.
 *
 * Device: the same simulated-metadata seeds Level 6 proved, named after the real artifacts.
 * `query_history` is the Athena query history, `pipeline_runs` the Glue job metrics,
 * `table_layouts` / `table_partitions` / `parquet_columns` the catalog's own layout metadata,
 * `iam_policies` / `access_log` a policy set beside its CloudTrail trail, and
 * `column_catalog` / `masking_policies` / `query_log` the three governance artifacts. All four
 * lessons are single-file: every deliverable here is a report an auditor reads, not a script
 * that mutates state, so there is nothing for the workspace runner to make idempotent.
 *
 * One seed column is not on the real artifact: `query_history.query_hash`. Athena, BigQuery and
 * Redshift expose the query text, the bytes scanned and the status, but no hash column; Snowflake
 * is the engine that ships one (`QUERY_HASH` / `QUERY_PARAMETERIZED_HASH`). The map asks for the
 * hash and the audit shape is right, so the column stays pre-computed here and 10.4.1's platform
 * callout says out loud that on Athena you normalize and hash the text yourself, or group by it.
 *
 * Deepens, not repeats. L6 taught the serverless cost model as a fact and graded a single
 * scan-cost sum; this module turns it into a recurring audit practice (attribution by user,
 * by hash, by pipeline; the lever quantified; the erosion priced). L7 `de-l7-time-travel-compaction`
 * already grades the compaction PLAN as a file-count-and-average-size candidate list, so 10.4.2
 * never re-emits that shape and prices the same condition in dollars per month instead.
 *
 * Deliberate authoring note, the 10 MB billing minimum. A "ten most expensive queries" ranking
 * can never be moved by a 10 MB floor, so grading the floor there would be decorative: an answer
 * that omitted it would still pass. The floor is therefore made load-bearing in the practice
 * (the `h8f3c2` hash totals $0.0003 with the floor and $0.0001 without) and again in the
 * cost-per-user drill, where `bi_service` runs nothing but sub-10 MB queries.
 *
 * Deliberate map deviation, the live demos for 10.4.1 and 10.4.2. The map asks for "top-10 queries
 * by cost" and "the before/after scan cost computed side by side", and each of those is the
 * lesson's own Apply deliverable verbatim, so shipping them as demos would hand the learner the
 * answer before the exercise. Both demos are therefore re-pointed at the same seeds from a
 * different angle: spend by table for 10.4.1, and the column byte profile with a running
 * percentage for 10.4.2. Each still motivates its exercise without pre-solving it.
 *
 * Deliberate map deviation, 10.4.2's title. The map writes it as "Parquet + Partitioning"; the
 * shipped title spells the "+" as "and" because the title renders as prose in the lesson rail.
 *
 * Deliberate map deviation, 10.4.3's diagram. The map asks for a policy-evaluation flowchart and
 * lib/tutorials/diagrams/schema.ts has no flowchart primitive. IAM evaluation is strictly ordered
 * with no branching back, so it renders as a `pipeline` (default deny, explicit deny, matching
 * allow, decision), which carries exactly the information the map asked that diagram to carry.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed. Content
 * rules: no em dashes in learner prose; every prompt leads with the deliverable; money and
 * percentage columns state an explicit ROUND so grading never depends on summation order.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 10.4.1 seeds — the Athena query history and the Glue job metrics, the two usage
// tables a FinOps review actually opens. The story in the numbers: forty runs of ONE query
// text (one query_hash) refreshing a dashboard off the unpartitioned raw table make up 69%
// of three days of spend, while the ten priciest individual queries add up to a third of it.
// The ranking and the leak disagree, which is the lesson.
//
// `bi_service` exists to make the 10 MB billing minimum load-bearing: all eight of its
// queries scan 2.4 MB and are still billed at 10 MB, so the `h8f3c2` tile totals $0.0003
// with the floor and $0.0001 without it.
//
// The run counts are also spaced so the practice's "at least 5 times" cut is the only cut that
// reproduces its expected set. The repeated hashes run 40, 6, 5, 4, and 3 times, so a learner
// who reads the threshold loosely and writes >= 2, >= 3 or >= 4 picks up `h5a6d4` or `h9e4b1`
// and fails, and >= 6 drops `h8f3c2` and fails. The two near misses are the second dashboard
// tile (`h9e4b1`, 3 runs) and an analyst rerunning one ad-hoc query while iterating
// (`h5a6d4`, 4 runs).
// ---------------------------------------------------------------------------

const QUERY_HISTORY_SEED = `CREATE TABLE query_history (
  query_id      TEXT,
  user_name     TEXT,
  query_hash    TEXT,     -- fingerprint of the normalized SQL text; identical text = identical hash
  table_name    TEXT,
  bytes_scanned INTEGER,  -- bytes the engine actually read; 1 TB = 1,000,000,000,000 bytes here
  started_at    TEXT
);
INSERT INTO query_history (query_id, user_name, query_hash, table_name, bytes_scanned, started_at) VALUES
  ('q-101', 'marco_ds',    'h2a900', 'raw_events_csv',       1120000000000, '2026-03-01 08:12:00'),
  ('q-102', 'dana_ops',    'h3b117', 'raw_events_csv',        950000000000, '2026-03-01 11:47:00'),
  ('q-103', 'priya_de',    'h4c220', 'raw_clickstream_json',  820000000000, '2026-03-01 15:03:00'),
  ('q-104', 'marco_ds',    'h5d331', 'raw_clickstream_json',  710000000000, '2026-03-02 09:26:00'),
  ('q-105', 'dana_ops',    'h6e442', 'raw_events_csv',        620000000000, '2026-03-02 14:11:00'),
  ('q-106', 'priya_de',    'h7f553', 'events_parquet',        540000000000, '2026-03-02 17:58:00'),
  ('q-107', 'marco_ds',    'h8a664', 'events_parquet',        490000000000, '2026-03-03 08:40:00'),
  ('q-108', 'dana_ops',    'h9b775', 'orders_parquet',        450000000000, '2026-03-03 10:22:00'),
  ('q-109', 'priya_de',    'h1c886', 'orders_parquet',        420000000000, '2026-03-03 13:19:00'),
  ('q-110', 'marco_ds',    'h2d997', 'events_parquet',        390000000000, '2026-03-03 16:05:00'),
  ('q-201', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-01 02:00:00'),
  ('q-202', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-01 14:00:00'),
  ('q-203', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-02 02:00:00'),
  ('q-204', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-02 14:00:00'),
  ('q-205', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-03 02:00:00'),
  ('q-206', 'etl_service', 'h4e2b8', 'orders_parquet',         45000000000, '2026-03-03 14:00:00'),
  ('q-301', 'bi_service',  'h8f3c2', 'dim_customer',               2400000, '2026-03-02 06:30:00'),
  ('q-302', 'bi_service',  'h8f3c2', 'dim_customer',               2400000, '2026-03-02 09:30:00'),
  ('q-303', 'bi_service',  'h9e4b1', 'dim_customer',               2400000, '2026-03-02 12:30:00'),
  ('q-304', 'bi_service',  'h8f3c2', 'dim_customer',               2400000, '2026-03-02 15:30:00'),
  ('q-305', 'bi_service',  'h8f3c2', 'dim_customer',               2400000, '2026-03-03 06:30:00'),
  ('q-306', 'bi_service',  'h9e4b1', 'dim_customer',               2400000, '2026-03-03 09:30:00'),
  ('q-307', 'bi_service',  'h8f3c2', 'dim_customer',               2400000, '2026-03-03 12:30:00'),
  ('q-308', 'bi_service',  'h9e4b1', 'dim_customer',               2400000, '2026-03-03 15:30:00'),
  ('q-401', 'analyst_tmp', 'h5a6d4', 'dim_customer',               6100000, '2026-03-03 11:12:00'),
  ('q-402', 'analyst_tmp', 'h3c9e7', 'dim_product',                 900000, '2026-03-03 11:20:00'),
  ('q-403', 'analyst_tmp', 'h5a6d4', 'dim_customer',               6100000, '2026-03-03 11:26:00'),
  ('q-404', 'analyst_tmp', 'h5a6d4', 'dim_customer',               6100000, '2026-03-03 11:41:00'),
  ('q-405', 'analyst_tmp', 'h5a6d4', 'dim_customer',               6100000, '2026-03-03 11:58:00');
-- The revenue dashboard refreshed every 20 minutes from 06:00 to 19:00 on 2026-03-02: forty runs
-- of one query text, so one query_hash, against the unpartitioned raw table, 380 GB every time.
INSERT INTO query_history (query_id, user_name, query_hash, table_name, bytes_scanned, started_at)
WITH RECURSIVE refresh(n) AS (
  SELECT 0 UNION ALL SELECT n + 1 FROM refresh WHERE n < 39
)
SELECT 'q-d' || substr('00' || n, -2), 'bi_dashboard', 'h6d0a1', 'raw_events_csv', 380000000000,
       '2026-03-02 ' || substr('0' || (6 + (n * 20) / 60), -2) || ':' || substr('0' || ((n * 20) % 60), -2) || ':00'
FROM refresh;`

const GLUE_JOB_RUNS_SEED = `CREATE TABLE pipeline_runs (
  pipeline  TEXT,
  run_date  TEXT,
  dpu_hours REAL     -- DPU-hours billed for the run, at $0.44 per DPU-hour
);
INSERT INTO pipeline_runs (pipeline, run_date, dpu_hours) VALUES
  ('events_ingest',       '2026-03-01', 18.4),
  ('events_ingest',       '2026-03-02', 19.1),
  ('events_ingest',       '2026-03-03', 17.8),
  ('clickstream_compact', '2026-03-01',  6.2),
  ('clickstream_compact', '2026-03-02',  6.5),
  ('clickstream_compact', '2026-03-03',  6.0),
  ('dim_refresh',         '2026-03-01',  0.6),
  ('dim_refresh',         '2026-03-02',  0.6),
  ('dim_refresh',         '2026-03-03',  0.7),
  ('ml_feature_build',    '2026-03-01', 11.5),
  ('ml_feature_build',    '2026-03-02', 12.2),
  ('ml_feature_build',    '2026-03-03', 26.9);`

const COST_AUDIT_SEED = QUERY_HISTORY_SEED + "\n" + GLUE_JOB_RUNS_SEED

const costPerQuery: SqlLesson = {
  id: "de-l10-cost-per-query",
  title: "FinOps: Cost per Query, Cost per Pipeline",
  summary:
    "Attribute serverless spend to queries, users, and pipelines from usage metadata, then find the repeated-scan leak that quietly doubles a bill.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "bytes-scanned billing",
    "cost attribution",
    "repeated-scan detection",
    "DPU-hour pipeline cost",
    "GROUP BY rollups",
    "share of total",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The bill is a query you can write

Level 6 taught you the serverless cost model as a fact: a query engine like Athena charges for the bytes it reads, not the rows it returns. FinOps is what happens when that fact becomes a weekly habit. Somebody asks "why did the platform bill jump 40 percent", and the useful answer is not a shrug, it is a result set. Every managed engine writes its own usage metadata, and every usage table has the same two things in it: a unit of work, and a meter reading.

The two meters that cover most of a data platform:

- **Bytes scanned.** Athena bills **$5.00 per TB scanned, with a 10 MB minimum per query**. The minimum is not trivia. It means a query against a two-megabyte dimension table still costs the same as a ten-megabyte one, so a tile that refreshes every thirty seconds against a tiny table is billed thousands of times for bytes it never read.
- **DPU-hours.** A Glue ETL job bills **$0.44 per DPU-hour** (a DPU is 4 vCPU and 16 GB), with a one-minute minimum per run. A job that finishes in eleven seconds still bills a minute, which is why "one Glue job per table" looks cheap in the code review and expensive on the invoice.

Cost per unit of work is then plain SQL: take the meter reading, apply the floor, apply the rate.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["meter", "billed unit", "the audit query", "the usual leak"],
  "rows": [
    ["bytes scanned", "MAX(bytes_scanned, 10 MB) at $5/TB", "cost per query, per user, per table", "one dashboard rescanning raw files"],
    ["DPU-hours", "DPU-hours at $0.44, 1-minute floor", "cost per pipeline per month", "many tiny jobs paying the minimum"],
    ["storage", "GB-month per storage class", "spend by prefix and class", "no lifecycle rule, nothing ages out"],
    ["requests", "GET/PUT per 1,000", "requests per partition", "millions of small files"]
  ],
  "caption": "Four meters, one query shape: reading times rate, grouped by whatever you want to attribute the money to."
}
\`\`\`

## The leak hides from the ranking

Here is the part that catches people. Rank your queries by cost and you get the ten biggest single scans, which are almost always somebody's one-off backfill or an analyst exploring. Those are visible, defensible, and usually not the problem.

The problem is the query nobody notices, run over and over. AWS's own documented case is a team whose Athena spend doubled in a quarter, with about **70 percent of it repeated scans of the same data**. No single run looked alarming. The fingerprint that finds it is a **hash of the normalized SQL text**, carried in this lesson's seed as \`query_hash\`: identical text means an identical hash, so the same query run four hundred times collapses into one row. Group by the hash instead of by the query and the shape of the bill changes completely.

Once you have the hash you also have the fix menu, in order of effort: cache or materialize the dashboard's result so it reads a small table instead of the raw one; convert and partition the source so each run reads a fraction of the bytes (the next lesson prices that); or set a **workgroup bytes-scanned limit**, which is the platform's built-in brake and cancels a query that goes past a byte budget, so you pay only for what it scanned before the cancel instead of for the full runaway scan. Be precise about that last one in an interview: the limit caps the blast radius, it does not zero it. A cancelled query is still billed for the bytes it read on the way to being cancelled, exactly like one you cancel by hand.

## Attribution is the deliverable, not the number

A FinOps finding that stops at "we spent $12,400" changes nothing. The finding that changes something names an owner: this hash, run by this service account, against this table, is 69 percent of the bill. That is why every query in this lesson groups by something a human is responsible for.

**Common mistake:** billing on \`bytes_scanned\` directly and forgetting the minimum. It makes no difference to your top spenders and a very large difference to any account whose workload is thousands of tiny queries, which is exactly the account that shows up asking why a "free" dashboard has a bill.

**Interview nuance:** when you are asked "how would you reduce our warehouse costs", the answer that lands is not a list of tips, it is a method: attribute first (per query, per hash, per user, per pipeline), then fix the biggest attributed line, then put a guardrail on it so it cannot come back. Naming the repeated-scan pattern, and grouping the history by a hash of the normalized query text as the way you would find it, is the detail that separates you from a candidate reciting "use Parquet".

> **On a real platform this differs.** Here you query one small \`query_history\` table in SQLite, and the hash arrives pre-computed. Not every platform hands you one. Snowflake does, as \`QUERY_HASH\` and \`QUERY_PARAMETERIZED_HASH\` on its query history views. Athena, BigQuery and Redshift do not: their history gives you the query text, the bytes scanned and the status, so you normalize the text and hash it yourself, or simply group by the text. That is the only step this seed takes for you. Otherwise the same reasoning runs against \`information_schema\`-style query history, the Cost and Usage Report, or CloudWatch job metrics. On BigQuery the meter is on-demand bytes billed per job in \`INFORMATION_SCHEMA.JOBS\`; on Microsoft Fabric it is capacity units in the metrics app. The rate and the column names move, the query shape does not.`,
    demoSeedSql: QUERY_HISTORY_SEED,
    demoCode: `-- Where the money went, by table: the raw unpartitioned files dominate the bill.
SELECT table_name,
       COUNT(*) AS queries,
       ROUND(SUM(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0), 4) AS spend_usd
FROM query_history
GROUP BY table_name
ORDER BY spend_usd DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-cost-per-query-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the ten most expensive queries, as \`(query_id, user_name, cost_usd)\`, most expensive first, over \`query_history(query_id, user_name, query_hash, table_name, bytes_scanned, started_at)\`.

Bill each query at $5.00 per TB scanned, where 1 TB is 1,000,000,000,000 bytes, with a 10 MB minimum: a query that read fewer than 10,000,000 bytes is still billed for 10,000,000. Round \`cost_usd\` to 4 decimals and break ties on \`query_id\`.`,
    starterCode: `-- The ten priciest queries, billed at $5/TB with a 10 MB floor.
SELECT query_id, user_name
  -- the billed cost of this one query
FROM query_history
;`,
    hints: [
      "`MAX(bytes_scanned, 10000000)` is SQLite's two-argument scalar MAX, which is exactly the billing floor.",
      "The rate is `5.0 * billed_bytes / 1000000000000.0`; wrap it in `ROUND(..., 4)` and alias it `cost_usd`.",
      "`ORDER BY cost_usd DESC, query_id` then `LIMIT 10`.",
    ],
    referenceSolution: `SELECT query_id, user_name,
       ROUND(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0, 4) AS cost_usd
FROM query_history
ORDER BY cost_usd DESC, query_id
LIMIT 10;`,
    singleFile: {
      seedSql: COST_AUDIT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["query_id", "user_name", "cost_usd"],
        rows: [
          ["q-101", "marco_ds", 5.6],
          ["q-102", "dana_ops", 4.75],
          ["q-103", "priya_de", 4.1],
          ["q-104", "marco_ds", 3.55],
          ["q-105", "dana_ops", 3.1],
          ["q-106", "priya_de", 2.7],
          ["q-107", "marco_ds", 2.45],
          ["q-108", "dana_ops", 2.25],
          ["q-109", "priya_de", 2.1],
          ["q-110", "marco_ds", 1.95],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-cost-per-query-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every \`query_hash\` run at least 5 times with its run count, total cost, and share of total spend, as \`(query_hash, runs, total_cost_usd, pct_of_spend)\`, biggest spender first, over the same \`query_history\` table.

Bill every query at $5.00 per TB scanned with the same 10 MB minimum. \`pct_of_spend\` is that hash's total as a percentage of the spend across every row in the table, not just the repeated ones. Round \`total_cost_usd\` to 4 decimals and \`pct_of_spend\` to 2.`,
    starterCode: `-- Repeated query texts: how many runs, how much money, what share of the bill.
SELECT query_hash
  -- runs, total_cost_usd, pct_of_spend
FROM query_history
;`,
    hints: [
      "Compute the per-query billed cost once in a CTE, then group that CTE by `query_hash`.",
      "`HAVING COUNT(*) >= 5` filters after aggregation, and the denominator is a scalar subquery over the same CTE.",
    ],
    singleFile: {
      seedSql: COST_AUDIT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["query_hash", "runs", "total_cost_usd", "pct_of_spend"],
        rows: [
          ["h6d0a1", 40, 76, 69.15],
          ["h4e2b8", 6, 1.35, 1.23],
          ["h8f3c2", 5, 0.0003, 0],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-cost-per-query-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns each pipeline's total compute cost as \`(pipeline, dpu_cost_usd)\`, most expensive first, over \`pipeline_runs(pipeline, run_date, dpu_hours)\`, billing DPU-hours at $0.44 and rounding to 2 decimals.`,
      starterCode: `-- Glue job spend per pipeline at $0.44 per DPU-hour.
SELECT pipeline
FROM pipeline_runs
;`,
      hints: [
        "`SUM(dpu_hours) * 0.44` is the pipeline's bill.",
        "Group by `pipeline`, `ROUND(..., 2)`, and order by the cost descending.",
      ],
      referenceSolution: `SELECT pipeline, ROUND(SUM(dpu_hours) * 0.44, 2) AS dpu_cost_usd
FROM pipeline_runs
GROUP BY pipeline
ORDER BY dpu_cost_usd DESC, pipeline;`,
      singleFile: {
        seedSql: COST_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["pipeline", "dpu_cost_usd"],
          rows: [
            ["events_ingest", 24.33],
            ["ml_feature_build", 22.26],
            ["clickstream_compact", 8.23],
            ["dim_refresh", 0.84],
          ],
        },
      },
    },
    {
      id: "de-l10-cost-per-query-drill-2",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns each user's total query spend as \`(user_name, cost_usd)\`, biggest spender first, over \`query_history\`, at $5.00 per TB with the 10 MB minimum, rounded to 4 decimals.`,
      starterCode: `-- Spend per user, with the 10 MB minimum applied to every query.
SELECT user_name
FROM query_history
;`,
      hints: [
        "Apply the floor per query, inside the SUM: `SUM(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0)`.",
        "`bi_service` only ever scans 2.4 MB, so its total is the floor times its query count.",
      ],
      referenceSolution: `SELECT user_name,
       ROUND(SUM(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0), 4) AS cost_usd
FROM query_history
GROUP BY user_name
ORDER BY cost_usd DESC, user_name;`,
      singleFile: {
        seedSql: COST_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["user_name", "cost_usd"],
          rows: [
            ["bi_dashboard", 76],
            ["marco_ds", 13.55],
            ["dana_ops", 10.1],
            ["priya_de", 8.9],
            ["etl_service", 1.35],
            ["bi_service", 0.0004],
            ["analyst_tmp", 0.0003],
          ],
        },
      },
    },
    {
      id: "de-l10-cost-per-query-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns daily query spend with a running total, as \`(query_date, daily_cost_usd, running_cost_usd)\`, oldest day first, over \`query_history\`, at $5.00 per TB with the 10 MB minimum and both dollar columns rounded to 2 decimals.`,
      starterCode: `-- Spend per day, plus the cumulative spend through that day.
SELECT substr(started_at, 1, 10) AS query_date
FROM query_history
GROUP BY query_date
;`,
      hints: [
        "`substr(started_at, 1, 10)` is the date part of the timestamp.",
        "A window function can sit on top of an aggregate: `SUM(SUM(cost)) OVER (ORDER BY query_date)` is the running total of the daily totals.",
      ],
      referenceSolution: `SELECT substr(started_at, 1, 10) AS query_date,
       ROUND(SUM(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0), 2) AS daily_cost_usd,
       ROUND(SUM(SUM(5.0 * MAX(bytes_scanned, 10000000) / 1000000000000.0))
               OVER (ORDER BY substr(started_at, 1, 10)), 2) AS running_cost_usd
FROM query_history
GROUP BY query_date
ORDER BY query_date;`,
      singleFile: {
        seedSql: COST_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["query_date", "daily_cost_usd", "running_cost_usd"],
          rows: [
            ["2026-03-01", 14.9, 14.9],
            ["2026-03-02", 85.8, 100.7],
            ["2026-03-03", 9.2, 109.9],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 10.4.2 seeds — the same logical table in two layouts, plus the partition catalog and
// the column byte profile that make pruning computable rather than assertable.
//
// `table_partitions` carries the erosion: fifteen partitions written by the batch job hold a
// few hundred healthy files, the last five were written by a streaming sink. 2026-02-23 is the
// near miss: at exactly 16.4 MB average it sits just OUTSIDE the practice's "under 16 MB" cut,
// so an unfiltered answer, or one that widens the cut to catch every streaming-written
// partition, returns a fifth row and fails. The guard is a near miss, not a hairline: the
// largest included partition (2026-02-27) averages 15.36 MB, so any cut from 15.36 MB up to
// 16.4 MB reproduces the expected set. It stops the wrong SHAPE of answer, not an off-by-one.
// ---------------------------------------------------------------------------

const TABLE_LAYOUTS_SEED = `CREATE TABLE table_layouts (
  table_name       TEXT,
  format           TEXT,     -- csv | json | parquet
  total_size_bytes INTEGER,
  partitioned_by   TEXT      -- the partition key, '' when the table is unpartitioned
);
INSERT INTO table_layouts (table_name, format, total_size_bytes, partitioned_by) VALUES
  ('raw_events_csv',       'csv',     4000000000000, ''),
  ('raw_clickstream_json', 'json',    1600000000000, ''),
  ('events_parquet',       'parquet',  800000000000, 'dt'),
  ('orders_parquet',       'parquet',  120000000000, 'dt'),
  ('dim_customer_csv',     'csv',        9000000000, '');`

const TABLE_PARTITIONS_SEED = `CREATE TABLE table_partitions (
  table_name      TEXT,
  partition_value TEXT,      -- the dt= value the files sit under
  size_bytes      INTEGER,
  file_count      INTEGER    -- objects under the partition prefix; one GET request per file per query
);
INSERT INTO table_partitions (table_name, partition_value, size_bytes, file_count) VALUES
  ('events_parquet', '2026-02-08', 38000000000,  320),
  ('events_parquet', '2026-02-09', 42000000000,  350),
  ('events_parquet', '2026-02-10', 36000000000,  300),
  ('events_parquet', '2026-02-11', 44000000000,  366),
  ('events_parquet', '2026-02-12', 39000000000,  325),
  ('events_parquet', '2026-02-13', 41000000000,  342),
  ('events_parquet', '2026-02-14', 37000000000,  308),
  ('events_parquet', '2026-02-15', 43000000000,  358),
  ('events_parquet', '2026-02-16', 35000000000,  292),
  ('events_parquet', '2026-02-17', 45000000000,  375),
  ('events_parquet', '2026-02-18', 38000000000,  317),
  ('events_parquet', '2026-02-19', 42000000000,  350),
  ('events_parquet', '2026-02-20', 40000000000,  333),
  ('events_parquet', '2026-02-21', 40000000000,  334),
  ('events_parquet', '2026-02-22', 39000000000,  326),
  ('events_parquet', '2026-02-23', 41000000000, 2500),
  ('events_parquet', '2026-02-24', 36000000000, 4500),
  ('events_parquet', '2026-02-25', 44000000000, 4000),
  ('events_parquet', '2026-02-26', 37000000000, 2600),
  ('events_parquet', '2026-02-27', 43000000000, 2800);`

const PARQUET_COLUMNS_SEED = `CREATE TABLE parquet_columns (
  column_name  TEXT,
  pct_of_bytes REAL      -- this column's share of the file's bytes; the 20 columns sum to 100
);
INSERT INTO parquet_columns (column_name, pct_of_bytes) VALUES
  ('event_id',     3.0),
  ('event_ts',     4.0),
  ('user_id',      5.0),
  ('session_id',   6.0),
  ('event_type',   2.0),
  ('page_url',    12.0),
  ('referrer_url', 9.0),
  ('user_agent',  11.0),
  ('device_type',  1.5),
  ('os_name',      1.5),
  ('browser',      2.0),
  ('country',      1.0),
  ('region',       1.5),
  ('city',         2.5),
  ('revenue_usd',  1.0),
  ('currency',     0.5),
  ('campaign_id',  3.0),
  ('ab_variant',   0.5),
  ('ingest_batch', 2.0),
  ('raw_payload', 31.0);`

const COMPRESSION_OPTIONS_SEED = `CREATE TABLE compression_options (
  codec      TEXT,
  size_ratio REAL     -- fraction of the uncompressed size this codec leaves behind
);
INSERT INTO compression_options (codec, size_ratio) VALUES
  ('none',   1.0),
  ('snappy', 0.55),
  ('zstd',   0.4),
  ('gzip',   0.35);`

const LAYOUT_SEED =
  TABLE_LAYOUTS_SEED +
  "\n" +
  TABLE_PARTITIONS_SEED +
  "\n" +
  PARQUET_COLUMNS_SEED +
  "\n" +
  COMPRESSION_OPTIONS_SEED

const parquetPartitionLever: SqlLesson = {
  id: "de-l10-parquet-partition-lever",
  title: "Quantifying the Parquet and Partitioning Lever",
  summary:
    "Compute, rather than assert, the dollar gap between scanning raw CSV and partitioned Parquet, then price the small-files problem that erodes it.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "column pruning arithmetic",
    "partition pruning arithmetic",
    "CTAS conversion",
    "small-files problem",
    "target file sizes",
    "request-cost arithmetic",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The most repeated answer in the room

Ask any data engineering interviewer for the exam answer they are tired of hearing and it is "convert it to Parquet and partition it". The reason they still ask is that most candidates can say it and almost none can size it. Saying it is worth nothing. Multiplying it out in front of the interviewer is worth a lot, because the same arithmetic is what you would put in the ticket.

Two independent prunings do the work, and they **multiply**.

- **Column pruning.** Parquet stores each column's values together, so reading three columns of a twenty-column table reads only those three columns' bytes. A wide free-text column can be a third of the file on its own, which is why the share of bytes you skip is usually much larger than the share of columns you skip.
- **Partition pruning.** Hive-style directories (\`dt=2026-02-20/\`) let the engine match your \`WHERE\` clause against the path and never open the other directories. One day out of twenty is one twentieth of the bytes.

Row-oriented CSV can do neither. There are no column boundaries to seek to and no partition directories to skip, so every read is a full read.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["layout", "partition pruning", "column pruning", "bytes for 1 day, 3 of 20 columns"],
  "rows": [
    ["raw CSV, unpartitioned", "none, one flat prefix", "none, rows are interleaved", "the whole table"],
    ["Parquet, unpartitioned", "none", "yes, only the 3 columns' bytes", "3 columns of every day"],
    ["Parquet, partitioned by dt", "yes, 1 directory of 20", "yes", "3 columns of 1 day"],
    ["Parquet + partitioned + compacted", "yes", "yes", "same bytes, far fewer requests"]
  ],
  "highlightCols": ["bytes for 1 day, 3 of 20 columns"],
  "caption": "The two prunings are independent, so they multiply. That product is the whole cost lever."
}
\`\`\`

The published case studies land around a **96.7 percent** cost reduction for a raw-CSV to partitioned-Parquet conversion, and the standard way to perform the conversion is **CTAS**: \`CREATE TABLE events_parquet WITH (format = 'PARQUET', partitioned_by = ARRAY['dt']) AS SELECT ... FROM raw_events_csv\`. One statement, and from then on the same logical question costs a fraction.

## Then it erodes

A converted table does not stay fast on its own. Whatever writes into it decides the file layout, and streaming sinks and small hourly jobs write many small objects. Now every query pays a per-file cost: one GET request per file, plus planning time to list and open them all. The industry target is **128 MB to 1 GB per file**, and the fix is compaction, rewriting the partition's many small files into a few big ones.

Level 7 already had you produce a compaction candidate list from file counts and average sizes. This lesson deliberately does not repeat that. It prices the same condition instead, because "partition 2026-02-24 has 4,500 files averaging 8 MB" is an engineering observation and "the small files in this partition cost us $2 a month in requests alone, before planning time" is the version that survives a FinOps review and gets scheduled.

There is a third lever, and it gets the same treatment. Level 6 taught the codecs: Snappy is fast at a modest ratio, Gzip is smaller and slower, Zstd lands near Gzip's size at near Snappy's speed. That was a storage fact, measured as a shrink ratio. On a bytes-scanned meter it is also a price, because whatever fraction of the bytes the codec leaves behind is a straight multiplier on every query against that table: leave 35 percent of the bytes and you take 65 percent off the cost of every full scan. The hard drill below is exactly that conversion, from a codec's size ratio to dollars.

**Common mistake:** quoting the savings percentage without the denominator. "Ninety-nine percent cheaper" means nothing until you say cheaper than what, on which query. State the baseline scan, the pruned scan, and the query shape you measured, or the number is unfalsifiable.

**Interview nuance:** if you are asked to optimize a slow, expensive table, give the levers in the order they pay: file format first (column pruning applies to every query), then partitioning on the column people actually filter by, then file size. Naming the file-size target out loud, 128 MB to 1 GB, is the detail that says you have operated a lake and not only read about one.

> **On a real platform this differs.** Here you compute the scan from catalog metadata in SQLite. On AWS, Athena reports the actual bytes scanned per query and Glue holds the partition and column statistics; you would sanity-check your estimate against the real reading. BigQuery prunes by clustering and partitioning and shows a dry-run byte estimate before you run; Snowflake prunes on micro-partition min/max metadata instead of directories. The arithmetic of "share of columns times share of partitions" survives all three.`,
    demoSeedSql: PARQUET_COLUMNS_SEED,
    demoCode: `-- The column byte profile: four of twenty columns are 63% of the file, which is why
-- selecting the columns you need is the cheapest optimization in the building.
SELECT column_name,
       pct_of_bytes,
       ROUND(SUM(pct_of_bytes) OVER (ORDER BY pct_of_bytes DESC, column_name), 1) AS running_pct
FROM parquet_columns
ORDER BY pct_of_bytes DESC, column_name;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-parquet-partition-lever-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the bytes scanned and the cost of reading \`user_id\`, \`event_type\`, and \`revenue_usd\` for the single day \`2026-02-20\` from each of the two layouts, as \`(layout, bytes_scanned, cost_usd, savings_pct)\`, biggest scan first.

\`raw_events_csv\` is unpartitioned CSV and prunes nothing, so it reads its whole \`total_size_bytes\` from \`table_layouts\`. \`events_parquet\` reads only that day's \`size_bytes\` from \`table_partitions\`, times the three columns' combined \`pct_of_bytes\` share from \`parquet_columns\`; truncate that byte count with \`CAST(... AS INTEGER)\`. Put the table name in \`layout\`, bill at $5.00 per TB (1 TB = 1,000,000,000,000 bytes) rounded to 4 decimals, and report \`savings_pct\` against the CSV scan rounded to 2 decimals.`,
    starterCode: `-- One day, three columns, two layouts: bytes, dollars, and the saving.
WITH scanned AS (
  SELECT 'raw_events_csv' AS layout, 0 AS bytes_scanned
  -- UNION ALL the events_parquet row
)
SELECT layout, bytes_scanned
FROM scanned;`,
    hints: [
      "Sum `pct_of_bytes` for the three named columns in a CTE, then divide by 100.0 to turn the percentage into a fraction.",
      "Build the two rows with `UNION ALL`: one row carrying the CSV table's `total_size_bytes`, one row carrying the matching `table_partitions` row scaled by that fraction.",
      "`savings_pct` is `100.0 * (csv_bytes - bytes_scanned) / csv_bytes`, so the CSV row lands on 0.",
    ],
    referenceSolution: `WITH picked AS (
  SELECT SUM(pct_of_bytes) AS pct_share
  FROM parquet_columns
  WHERE column_name IN ('user_id', 'event_type', 'revenue_usd')
),
csv_total AS (
  SELECT total_size_bytes AS bytes FROM table_layouts WHERE table_name = 'raw_events_csv'
),
scanned AS (
  SELECT 'raw_events_csv' AS layout, (SELECT bytes FROM csv_total) AS bytes_scanned
  UNION ALL
  SELECT 'events_parquet',
         CAST(p.size_bytes * (SELECT pct_share FROM picked) / 100.0 AS INTEGER)
  FROM table_partitions p
  WHERE p.table_name = 'events_parquet' AND p.partition_value = '2026-02-20'
)
SELECT layout,
       bytes_scanned,
       ROUND(5.0 * bytes_scanned / 1000000000000.0, 4) AS cost_usd,
       ROUND(100.0 * ((SELECT bytes FROM csv_total) - bytes_scanned)
               / (SELECT bytes FROM csv_total), 2) AS savings_pct
FROM scanned
ORDER BY bytes_scanned DESC;`,
    singleFile: {
      seedSql: LAYOUT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["layout", "bytes_scanned", "cost_usd", "savings_pct"],
        rows: [
          ["raw_events_csv", 4000000000000, 20, 0],
          ["events_parquet", 3200000000, 0.016, 99.92],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-parquet-partition-lever-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns what the small-files problem costs per month, for every \`events_parquet\` partition whose average file size is under 16 MB, as \`(partition_value, file_count, monthly_request_cost_usd, compacted_cost_usd, monthly_savings_usd)\`, biggest saving first, over \`table_partitions\`.

Assume 1,200 queries a month, one GET request per file per query, and $0.0004 per 1,000 GET requests. \`compacted_cost_usd\` is that same arithmetic on the file count a 128 MB target would produce, rounded up. Treat 1 MB as 1,000,000 bytes and round every dollar column to 2 decimals.`,
    starterCode: `-- What the tiny files in each partition cost, and what compaction would save.
SELECT partition_value, file_count
FROM table_partitions
WHERE table_name = 'events_parquet'
;`,
    hints: [
      "Average file size is `size_bytes / file_count`, so under 16 MB means under 16000000 bytes.",
      "sql.js has no CEIL, but both columns are integers: `(size_bytes / 1000000 + 127) / 128` is the rounded-up file count at a 128 MB target.",
    ],
    singleFile: {
      seedSql: LAYOUT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: [
          "partition_value",
          "file_count",
          "monthly_request_cost_usd",
          "compacted_cost_usd",
          "monthly_savings_usd",
        ],
        rows: [
          ["2026-02-24", 4500, 2.16, 0.14, 2.02],
          ["2026-02-25", 4000, 1.92, 0.17, 1.75],
          ["2026-02-27", 2800, 1.34, 0.16, 1.18],
          ["2026-02-26", 2600, 1.25, 0.14, 1.11],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-parquet-partition-lever-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many bytes the lake holds in each file format, as \`(format, total_bytes)\`, biggest first, over \`table_layouts\`.`,
      starterCode: `-- Lake footprint by file format.
SELECT format
FROM table_layouts
;`,
      hints: [
        "Group by `format` and `SUM(total_size_bytes)`.",
        "Alias the total exactly `total_bytes` and order it descending.",
      ],
      referenceSolution: `SELECT format, SUM(total_size_bytes) AS total_bytes
FROM table_layouts
GROUP BY format
ORDER BY total_bytes DESC;`,
      singleFile: {
        seedSql: LAYOUT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["format", "total_bytes"],
          rows: [
            ["csv", 4009000000000],
            ["json", 1600000000000],
            ["parquet", 920000000000],
          ],
        },
      },
    },
    {
      id: "de-l10-parquet-partition-lever-drill-2",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the single unpartitioned table that costs the most to scan end to end, as \`(table_name, full_scan_cost_usd)\`, at $5.00 per TB rounded to 2 decimals, over \`table_layouts\`.`,
      starterCode: `-- The priciest full scan in the lake, among the tables that cannot prune.
SELECT table_name
FROM table_layouts
;`,
      hints: [
        "Unpartitioned means `partitioned_by = ''`.",
        "`ORDER BY full_scan_cost_usd DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `SELECT table_name, ROUND(5.0 * total_size_bytes / 1000000000000.0, 2) AS full_scan_cost_usd
FROM table_layouts
WHERE partitioned_by = ''
ORDER BY full_scan_cost_usd DESC, table_name
LIMIT 1;`,
      singleFile: {
        seedSql: LAYOUT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["table_name", "full_scan_cost_usd"],
          rows: [["raw_events_csv", 20]],
        },
      },
    },
    {
      id: "de-l10-parquet-partition-lever-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns, for each codec in \`compression_options(codec, size_ratio)\`, what one full scan of \`raw_events_csv\` would cost after re-encoding at that codec's ratio and how much that saves against the uncompressed scan, as \`(codec, scan_cost_usd, saved_usd)\`, biggest saving first, at $5.00 per TB rounded to 2 decimals.`,
      starterCode: `-- Scan cost per codec, and the dollars each codec saves.
SELECT c.codec
FROM compression_options c
;`,
      hints: [
        "Bring in the one row you need with `CROSS JOIN table_layouts l` plus `WHERE l.table_name = 'raw_events_csv'`.",
        "The compressed scan is `total_size_bytes * size_ratio`; the saving is `total_size_bytes * (1 - size_ratio)`, both at $5 per TB.",
      ],
      referenceSolution: `SELECT c.codec,
       ROUND(5.0 * l.total_size_bytes * c.size_ratio / 1000000000000.0, 2) AS scan_cost_usd,
       ROUND(5.0 * l.total_size_bytes * (1 - c.size_ratio) / 1000000000000.0, 2) AS saved_usd
FROM compression_options c
CROSS JOIN table_layouts l
WHERE l.table_name = 'raw_events_csv'
ORDER BY saved_usd DESC, c.codec;`,
      singleFile: {
        seedSql: LAYOUT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["codec", "scan_cost_usd", "saved_usd"],
          rows: [
            ["gzip", 7, 13],
            ["zstd", 8, 12],
            ["snappy", 11, 9],
            ["none", 20, 0],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 10.4.3 seeds — a policy set beside the trail that shows what was actually called.
// The over-grants are planted in both directions: an action nobody uses (DeleteObject on
// curated), a write into the wrong tier (PutObject on raw), a permission nobody needs
// (ListBucket), and an allow scoped so narrowly it never matches (PutObject on the bi/
// prefix of the results bucket, while Athena writes to query-*/).
//
// The canonical failure is in the log: role/analyst-athena can read the results bucket but
// was never granted PutObject on it, so every query it starts ends in AccessDenied. The Deny
// statements make the effect filter load-bearing, since a Deny has no successful uses either
// and an answer that forgets `effect = 'Allow'` returns them. The p-19 guardrail plus e-026
// make the other half load-bearing: curated-etl tried exactly the write its p-07 over-grant
// permits, the guardrail denied it, and an answer that counts denied attempts as uses drops
// p-07 from the revoke list.
// ---------------------------------------------------------------------------

const IAM_POLICIES_SEED = `CREATE TABLE iam_policies (
  policy_id       TEXT,
  principal       TEXT,     -- the role or user the statement is attached to
  effect          TEXT,     -- Allow | Deny
  action          TEXT,
  resource_prefix TEXT      -- the statement matches any resource starting with this prefix
);
INSERT INTO iam_policies (policy_id, principal, effect, action, resource_prefix) VALUES
  ('p-01', 'role/ingest-etl',     'Allow', 's3:GetObject',              's3://lake/raw/'),
  ('p-02', 'role/ingest-etl',     'Allow', 's3:PutObject',              's3://lake/curated/'),
  ('p-03', 'role/ingest-etl',     'Allow', 's3:DeleteObject',           's3://lake/curated/'),
  ('p-04', 'role/ingest-etl',     'Allow', 'glue:UpdateTable',          'arn:glue:table/'),
  ('p-05', 'role/curated-etl',    'Allow', 's3:GetObject',              's3://lake/curated/'),
  ('p-06', 'role/curated-etl',    'Allow', 's3:PutObject',              's3://lake/published/'),
  ('p-07', 'role/curated-etl',    'Allow', 's3:PutObject',              's3://lake/raw/'),
  ('p-08', 'role/analyst-athena', 'Allow', 's3:GetObject',              's3://lake/published/'),
  ('p-09', 'role/analyst-athena', 'Allow', 'athena:StartQueryExecution','arn:athena:workgroup/analytics'),
  ('p-10', 'role/analyst-athena', 'Allow', 's3:GetObject',              's3://athena-results/'),
  ('p-11', 'role/bi-reader',      'Allow', 's3:GetObject',              's3://lake/published/'),
  ('p-12', 'role/bi-reader',      'Allow', 'athena:StartQueryExecution','arn:athena:workgroup/bi'),
  ('p-13', 'user/contractor-jo',  'Allow', 's3:GetObject',              's3://lake/'),
  ('p-14', 'user/contractor-jo',  'Deny',  's3:GetObject',              's3://lake/raw/pii/'),
  ('p-15', 'role/bi-reader',      'Deny',  's3:GetObject',              's3://lake/published/salary/'),
  ('p-16', 'role/analyst-athena', 'Allow', 's3:ListBucket',             's3://lake/published/'),
  ('p-17', 'role/bi-reader',      'Allow', 's3:PutObject',              's3://athena-results/bi/'),
  ('p-18', 'role/curated-etl',    'Deny',  's3:DeleteObject',           's3://lake/published/'),
  ('p-19', 'role/curated-etl',    'Deny',  's3:PutObject',              's3://lake/raw/');`

const ACCESS_LOG_SEED = `CREATE TABLE access_log (
  event_id   TEXT,
  principal  TEXT,
  action     TEXT,
  resource   TEXT,
  event_time TEXT,
  error_code TEXT     -- NULL when the call succeeded, otherwise the denial reason
);
INSERT INTO access_log (event_id, principal, action, resource, event_time, error_code) VALUES
  ('e-001', 'role/ingest-etl',     's3:GetObject',              's3://lake/raw/events/dt=2026-03-02/part-0000.parquet',        '2026-03-02 03:05:11', NULL),
  ('e-002', 'role/ingest-etl',     's3:GetObject',              's3://lake/raw/events/dt=2026-03-02/part-0001.parquet',        '2026-03-02 03:05:14', NULL),
  ('e-003', 'role/ingest-etl',     's3:GetObject',              's3://lake/raw/orders/dt=2026-03-02/part-0000.parquet',        '2026-03-02 03:06:02', NULL),
  ('e-004', 'role/ingest-etl',     's3:GetObject',              's3://lake/raw/orders/dt=2026-03-02/part-0001.parquet',        '2026-03-02 03:06:05', NULL),
  ('e-005', 'role/ingest-etl',     's3:PutObject',              's3://lake/curated/events/dt=2026-03-02/part-0000.parquet',    '2026-03-02 03:12:40', NULL),
  ('e-006', 'role/ingest-etl',     's3:PutObject',              's3://lake/curated/orders/dt=2026-03-02/part-0000.parquet',    '2026-03-02 03:13:02', NULL),
  ('e-007', 'role/ingest-etl',     's3:PutObject',              's3://lake/curated/orders/dt=2026-03-02/part-0001.parquet',    '2026-03-02 03:13:05', NULL),
  ('e-008', 'role/ingest-etl',     'glue:UpdateTable',          'arn:glue:table/analytics/curated_events',                     '2026-03-02 03:14:00', NULL),
  ('e-009', 'role/curated-etl',    's3:GetObject',              's3://lake/curated/events/dt=2026-03-02/part-0000.parquet',    '2026-03-02 04:01:20', NULL),
  ('e-010', 'role/curated-etl',    's3:PutObject',              's3://lake/published/daily_revenue/dt=2026-03-02/part-0.parquet','2026-03-02 04:09:55', NULL),
  ('e-011', 'role/analyst-athena', 'athena:StartQueryExecution','arn:athena:workgroup/analytics',                              '2026-03-02 10:22:31', NULL),
  ('e-012', 'role/analyst-athena', 's3:GetObject',              's3://lake/published/daily_revenue/dt=2026-03-02/part-0.parquet','2026-03-02 10:22:40', NULL),
  ('e-013', 'role/analyst-athena', 's3:PutObject',              's3://athena-results/query-abc/result.csv',                    '2026-03-02 10:22:45', 'AccessDenied'),
  ('e-014', 'role/analyst-athena', 'athena:StartQueryExecution','arn:athena:workgroup/analytics',                              '2026-03-02 11:04:02', NULL),
  ('e-015', 'role/analyst-athena', 's3:PutObject',              's3://athena-results/query-abd/result.csv',                    '2026-03-02 11:04:09', 'AccessDenied'),
  ('e-016', 'role/analyst-athena', 's3:PutObject',              's3://athena-results/query-abe/result.csv',                    '2026-03-02 14:37:50', 'AccessDenied'),
  ('e-017', 'role/analyst-athena', 's3:GetObject',              's3://athena-results/query-9f0/result.csv',                    '2026-03-02 09:15:00', NULL),
  ('e-018', 'role/bi-reader',      'athena:StartQueryExecution','arn:athena:workgroup/bi',                                     '2026-03-02 09:59:00', NULL),
  ('e-019', 'role/bi-reader',      's3:GetObject',              's3://lake/published/daily_revenue/dt=2026-03-02/part-0.parquet','2026-03-02 10:00:12', NULL),
  ('e-020', 'role/bi-reader',      's3:PutObject',              's3://athena-results/query-def/result.csv',                    '2026-03-02 10:00:20', 'AccessDenied'),
  ('e-021', 'role/bi-reader',      's3:PutObject',              's3://athena-results/query-deg/result.csv',                    '2026-03-02 15:31:44', 'AccessDenied'),
  ('e-022', 'user/contractor-jo',  's3:GetObject',              's3://lake/published/daily_revenue/dt=2026-03-02/part-0.parquet','2026-03-02 13:40:05', NULL),
  ('e-023', 'user/contractor-jo',  's3:GetObject',              's3://lake/raw/pii/customers.csv',                             '2026-03-02 02:14:09', 'AccessDenied'),
  ('e-024', 'user/contractor-jo',  's3:GetObject',              's3://lake/raw/pii/customers.csv',                             '2026-03-02 23:47:31', 'AccessDenied'),
  ('e-025', 'user/contractor-jo',  's3:GetObject',              's3://lake/published/daily_revenue/dt=2026-03-01/part-0.parquet','2026-03-02 22:58:00', NULL),
  ('e-026', 'role/curated-etl',    's3:PutObject',              's3://lake/raw/backfill/part-0000.parquet',                     '2026-03-02 11:15:00', 'AccessDenied');`

const IAM_AUDIT_SEED = IAM_POLICIES_SEED + "\n" + ACCESS_LOG_SEED

const iamLeastPrivilege: SqlLesson = {
  id: "de-l10-iam-least-privilege",
  title: "IAM Least Privilege for a Pipeline, by Audit",
  summary:
    "How IAM actually evaluates a policy set (default deny, explicit deny wins) and why that explains the classic Athena Access Denied error.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "IAM policy evaluation",
    "roles not keys",
    "least privilege",
    "grants versus usage auditing",
    "anti-joins",
    "prefix matching with LIKE",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Roles, not keys

The first thing to get right is what identity a pipeline runs as. A junior instinct is to create an access key, put it in a config file, and move on. Nobody does that in a reviewed system, because a key is a long-lived secret that leaks into a repo, a log, or a laptop. The pattern is a **role**: an identity with permissions attached and a trust policy naming who may assume it. The Glue job, the Lambda, the EMR cluster assume that role and receive short-lived credentials that rotate on their own. Nothing to leak, nothing to rotate by hand.

## How a request is evaluated

Policy evaluation is a fixed order, and interviewers ask for it because it is short and candidates still get it backwards.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Default deny", "note": "no statement, no access" },
    { "label": "Any explicit Deny?", "note": "if yes, denied, full stop" },
    { "label": "Any matching Allow?", "note": "principal + action + resource" },
    { "label": "Decision", "note": "allowed only if an Allow matched and no Deny did" }
  ],
  "highlight": ["Any explicit Deny?"],
  "caption": "Default deny, explicit deny wins, otherwise an Allow must match all three of principal, action, and resource."
}
\`\`\`

Three consequences worth saying out loud:

1. **Adding an Allow can never override a Deny.** If a request is denied and there is an explicit Deny anywhere in the evaluated set, adding permissions does nothing. Find the Deny.
2. **A statement must match all three parts.** A grant of \`s3:GetObject\` on \`s3://lake/raw/\` does nothing for a request to \`s3://lake/curated/\`, and nothing at all for \`s3:PutObject\`.
3. **Resources are prefixes.** \`s3://lake/\` covers everything under it, which is how a well-meaning "just give it read access to the lake" quietly includes the PII prefix.

Least privilege for a pipeline, said concretely: the ingest role needs \`s3:GetObject\` on the raw prefix, \`s3:PutObject\` on the curated prefix, and \`glue:UpdateTable\` on its own tables. Nothing else. Not delete. Not write to raw.

## Least privilege is an audit, not an intention

Everyone agrees with least privilege and almost nobody can prove they have it, because a policy document only tells you what is *permitted*. What was *used* is in the access log (CloudTrail on AWS). Put the two beside each other and least privilege becomes a query with an answer: every allow with no matching successful call in the log is a revoke candidate. That is the audit you run before a security review, and it is an anti-join.

Read the result with judgment before you revoke. A permission a quarterly job needs will look unused in a week of logs, so you widen the window or check the schedule. But "granted three years ago, never once used" is a finding, and the write permission into a tier the job has no business writing to is a finding with a blast radius.

## The canonical Access Denied

The failure every junior meets on AWS: Athena queries fail with **Access Denied**, and the query itself is fine. Athena writes every result set to a results bucket before you can read it, so the role needs \`s3:PutObject\` on that bucket, not only \`s3:GetObject\`. A role that can read results but not write them starts a query, does the work, and dies at the last step. The seed here holds exactly that: one role that can read \`s3://athena-results/\` and was never granted write, and one role whose write grant is scoped to a prefix Athena does not use.

**Common mistake:** treating a denied attempt in the log as evidence that a permission is used. It is evidence of the opposite. When you audit grants against usage, count only the calls that succeeded, or a broken permission will look busy and keep its grant.

**Interview nuance:** asked "how would you secure this pipeline", the strong answer moves from principle to evidence in one breath: roles with short-lived credentials rather than keys, the minimum action set per tier, and then "and I would audit it by joining the policy set to CloudTrail to find grants nobody has used". The second half is what makes the first half credible.

> **On a real platform this differs.** Here you evaluate a small \`iam_policies\` table in SQLite. Real IAM composes identity policies, resource policies, permission boundaries, service control policies (SCPs), resource control policies (RCPs), and session policies, and they do not all combine the same way. Boundaries, SCPs, RCPs, and session policies are filters: they can only subtract, so the effective permission is an intersection with each of them. Identity and resource policies are additive within one account: either one can grant on its own, so a bucket policy naming a principal authorizes it even with no matching identity policy. Across accounts you need both. And any explicit Deny, in any of them, wins over everything. Lake Formation layers column, row, and cell grants on top for the catalog. Azure expresses the same audit as an RBAC role-assignment review against activity logs. The evaluation order and the grants-versus-usage audit transfer unchanged.`,
    demoSeedSql: ACCESS_LOG_SEED,
    demoCode: `-- The trail at a glance: who is calling, and who is bouncing off a missing permission.
SELECT principal,
       COUNT(*) AS events,
       SUM(CASE WHEN error_code = 'AccessDenied' THEN 1 ELSE 0 END) AS denied
FROM access_log
GROUP BY principal
ORDER BY denied DESC, principal;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-iam-least-privilege-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every allow grant the access log shows nobody ever used, as \`(principal, action, resource_prefix)\`, ordered by principal then action, over \`iam_policies(policy_id, principal, effect, action, resource_prefix)\` and \`access_log(event_id, principal, action, resource, event_time, error_code)\`. This is the revoke candidate list.

A grant counts as used when \`access_log\` holds a **successful** event (\`error_code IS NULL\`) for the same principal and the same action on a resource that starts with the grant's \`resource_prefix\`. Deny statements grant nothing, so leave them out.`,
    starterCode: `-- Granted but never used: the revoke candidates.
SELECT p.principal, p.action, p.resource_prefix
FROM iam_policies p
;`,
    hints: [
      "Filter `iam_policies` to `effect = 'Allow'` first; a Deny statement grants nothing and must not appear in a revoke list.",
      "`NOT EXISTS` with a correlated subquery is the anti-join, and the resource test is `a.resource LIKE p.resource_prefix || '%'`.",
      "A denied attempt is not a use, so the subquery also needs `a.error_code IS NULL`.",
    ],
    referenceSolution: `SELECT p.principal, p.action, p.resource_prefix
FROM iam_policies p
WHERE p.effect = 'Allow'
  AND NOT EXISTS (
    SELECT 1 FROM access_log a
    WHERE a.principal = p.principal
      AND a.action = p.action
      AND a.error_code IS NULL
      AND a.resource LIKE p.resource_prefix || '%'
  )
ORDER BY p.principal, p.action;`,
    singleFile: {
      seedSql: IAM_AUDIT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["principal", "action", "resource_prefix"],
        rows: [
          ["role/analyst-athena", "s3:ListBucket", "s3://lake/published/"],
          ["role/bi-reader", "s3:PutObject", "s3://athena-results/bi/"],
          ["role/curated-etl", "s3:PutObject", "s3://lake/raw/"],
          ["role/ingest-etl", "s3:DeleteObject", "s3://lake/curated/"],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-iam-least-privilege-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each principal hitting Access Denied on the Athena results bucket, with how many times and whether any allow could have covered it, as \`(principal, denied_events, has_results_bucket_allow)\`, most denials first, over \`access_log\` and \`iam_policies\`.

Count only events with \`error_code = 'AccessDenied'\` on a resource under \`s3://athena-results/\`. \`has_results_bucket_allow\` is 1 when that principal holds an Allow statement for the **same action** on a \`resource_prefix\` under \`s3://athena-results/\`, otherwise 0. A 1 here does not mean the call should have worked: it means an allow exists but did not match the path Athena wrote to.`,
    starterCode: `-- Who is bouncing off the results bucket, and do they have any write grant on it at all.
SELECT a.principal
FROM access_log a
;`,
    hints: [
      "Group by principal and action so the flag can be correlated to the action that was actually denied.",
      "`CASE WHEN EXISTS (...) THEN 1 ELSE 0 END` produces the flag; match the bucket with `LIKE 's3://athena-results/%'`.",
    ],
    singleFile: {
      seedSql: IAM_AUDIT_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["principal", "denied_events", "has_results_bucket_allow"],
        rows: [
          ["role/analyst-athena", 3, 0],
          ["role/bi-reader", 2, 1],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-iam-least-privilege-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns every principal that called the platform outside business hours, as \`(principal, off_hours_events)\`, most first, over \`access_log\`. Business hours are 09:00 up to but not including 18:00.`,
      starterCode: `-- Activity before 09:00 or from 18:00 onward.
SELECT principal
FROM access_log
;`,
      hints: [
        "`strftime('%H', event_time)` returns the hour as text, so `CAST(... AS INTEGER)` before comparing.",
        "Off hours means the hour is under 9 or 18 and over.",
      ],
      referenceSolution: `SELECT principal, COUNT(*) AS off_hours_events
FROM access_log
WHERE CAST(strftime('%H', event_time) AS INTEGER) < 9
   OR CAST(strftime('%H', event_time) AS INTEGER) >= 18
GROUP BY principal
ORDER BY off_hours_events DESC, principal;`,
      singleFile: {
        seedSql: IAM_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["principal", "off_hours_events"],
          rows: [
            ["role/ingest-etl", 8],
            ["user/contractor-jo", 3],
            ["role/curated-etl", 2],
          ],
        },
      },
    },
    {
      id: "de-l10-iam-least-privilege-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every Deny statement that carves into an Allow on the same principal and action, as \`(principal, action, denied_prefix, allowed_prefix)\`, ordered by principal then denied prefix, over \`iam_policies\`. A Deny carves into an Allow when the denied prefix starts with the allowed prefix, which includes the case where the two prefixes are identical and the Deny cancels the Allow outright.`,
      starterCode: `-- Where an explicit Deny carves a hole out of an Allow on the same principal and action.
SELECT d.principal, d.action
FROM iam_policies d
;`,
      hints: [
        "Self-join `iam_policies` to itself on principal and action, with `d.effect = 'Deny'` and `a.effect = 'Allow'`.",
        "The containment test is `d.resource_prefix LIKE a.resource_prefix || '%'`.",
      ],
      referenceSolution: `SELECT d.principal,
       d.action,
       d.resource_prefix AS denied_prefix,
       a.resource_prefix AS allowed_prefix
FROM iam_policies d
JOIN iam_policies a
  ON a.principal = d.principal
 AND a.action = d.action
 AND a.effect = 'Allow'
 AND d.resource_prefix LIKE a.resource_prefix || '%'
WHERE d.effect = 'Deny'
ORDER BY d.principal, d.resource_prefix;`,
      singleFile: {
        seedSql: IAM_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["principal", "action", "denied_prefix", "allowed_prefix"],
          rows: [
            [
              "role/bi-reader",
              "s3:GetObject",
              "s3://lake/published/salary/",
              "s3://lake/published/",
            ],
            ["role/curated-etl", "s3:PutObject", "s3://lake/raw/", "s3://lake/raw/"],
            ["user/contractor-jo", "s3:GetObject", "s3://lake/raw/pii/", "s3://lake/"],
          ],
        },
      },
    },
    {
      id: "de-l10-iam-least-privilege-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every action granted to \`role/ingest-etl\` with how many successful calls it actually covered, as \`(action, uses)\`, busiest first, over \`iam_policies\` and \`access_log\`. Actions with no successful call must still appear, with a count of 0.`,
      starterCode: `-- What the ingest role is allowed to do, next to what it actually did.
SELECT p.action
FROM iam_policies p
WHERE p.principal = 'role/ingest-etl' AND p.effect = 'Allow'
;`,
      hints: [
        "A `LEFT JOIN` keeps the unused grant; an inner join would drop it, which is the whole point of the drill.",
        "Count the joined side, not the rows: `COUNT(a.event_id)` is 0 when nothing matched.",
      ],
      referenceSolution: `SELECT p.action, COUNT(a.event_id) AS uses
FROM iam_policies p
LEFT JOIN access_log a
  ON a.principal = p.principal
 AND a.action = p.action
 AND a.error_code IS NULL
 AND a.resource LIKE p.resource_prefix || '%'
WHERE p.principal = 'role/ingest-etl' AND p.effect = 'Allow'
GROUP BY p.action
ORDER BY uses DESC, p.action;`,
      singleFile: {
        seedSql: IAM_AUDIT_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["action", "uses"],
          rows: [
            ["s3:GetObject", 4],
            ["s3:PutObject", 3],
            ["glue:UpdateTable", 1],
            ["s3:DeleteObject", 0],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 10.4.4 seeds — the three governance artifacts. The gaps are planted so each audit
// question has a different answer: `support_tickets.requester_email` and `contact_phone` are
// obviously PII and carry no tag at all (the discovery gap, invisible to any query that starts
// from the tags), `customers.phone_number` and the whole `payments` table are tagged with no
// masking policy (the compliance gap), and `query_log` holds reads of both kinds.
//
// `query_log` records reads against the BASE columns, which is what makes the exposure report
// meaningful: a row for a role that is not the policy's unmasked_role means the governed view
// was bypassed. The untagged `requester_email` read is the load-bearing exclusion, since an
// answer that skips the pii_tag test returns it.
// ---------------------------------------------------------------------------

const COLUMN_CATALOG_SEED = `CREATE TABLE column_catalog (
  table_name  TEXT,
  column_name TEXT,
  data_type   TEXT,
  pii_tag     TEXT     -- the governance tag on the column, NULL when nobody has tagged it
);
INSERT INTO column_catalog (table_name, column_name, data_type, pii_tag) VALUES
  ('customers',       'customer_id',     'INTEGER', NULL),
  ('customers',       'full_name',       'TEXT',    'name'),
  ('customers',       'email_address',   'TEXT',    'email'),
  ('customers',       'phone_number',    'TEXT',    'phone'),
  ('customers',       'signup_date',     'TEXT',    NULL),
  ('customers',       'country',         'TEXT',    NULL),
  ('orders',          'order_id',        'INTEGER', NULL),
  ('orders',          'customer_id',     'INTEGER', NULL),
  ('orders',          'amount_usd',      'REAL',    NULL),
  ('orders',          'ship_address',    'TEXT',    'address'),
  ('orders',          'order_ts',        'TEXT',    NULL),
  ('payments',        'payment_id',      'INTEGER', NULL),
  ('payments',        'customer_id',     'INTEGER', NULL),
  ('payments',        'card_last4',      'TEXT',    'card'),
  ('payments',        'billing_zip',     'TEXT',    'address'),
  ('payments',        'paid_at',         'TEXT',    NULL),
  ('support_tickets', 'ticket_id',       'INTEGER', NULL),
  ('support_tickets', 'requester_email', 'TEXT',    NULL),
  ('support_tickets', 'contact_phone',   'TEXT',    NULL),
  ('support_tickets', 'body_text',       'TEXT',    NULL),
  ('support_tickets', 'created_ts',      'TEXT',    NULL),
  ('marketing_leads', 'lead_id',         'INTEGER', NULL),
  ('marketing_leads', 'work_email',      'TEXT',    NULL),
  ('marketing_leads', 'lead_name',       'TEXT',    'name'),
  ('marketing_leads', 'source',          'TEXT',    NULL);`

const MASKING_POLICIES_SEED = `CREATE TABLE masking_policies (
  table_name    TEXT,
  column_name   TEXT,
  policy_name   TEXT,
  unmasked_role TEXT     -- the one role the policy lets read raw values
);
INSERT INTO masking_policies (table_name, column_name, policy_name, unmasked_role) VALUES
  ('customers', 'full_name',     'mask_name_partial', 'role/pii_reader'),
  ('customers', 'email_address', 'mask_email_domain', 'role/pii_reader'),
  ('orders',    'ship_address',  'mask_address_city', 'role/fraud_ops');`

const QUERY_LOG_SEED = `CREATE TABLE query_log (
  user_name   TEXT,
  role        TEXT,
  table_name  TEXT,
  column_name TEXT,     -- one row per base column the query read
  query_time  TEXT
);
INSERT INTO query_log (user_name, role, table_name, column_name, query_time) VALUES
  ('nadia_g',       'role/pii_reader', 'customers',       'country',         '2026-03-02 09:10:00'),
  ('nadia_g',       'role/pii_reader', 'customers',       'full_name',       '2026-03-02 09:14:00'),
  ('nadia_g',       'role/pii_reader', 'customers',       'email_address',   '2026-03-02 09:15:20'),
  ('sam_fraud',     'role/fraud_ops',  'orders',          'ship_address',    '2026-03-02 10:02:11'),
  ('leo_bi',        'role/analyst',    'orders',          'amount_usd',      '2026-03-02 11:00:00'),
  ('leo_bi',        'role/analyst',    'customers',       'email_address',   '2026-03-02 11:31:05'),
  ('leo_bi',        'role/analyst',    'customers',       'phone_number',    '2026-03-02 11:31:40'),
  ('jo_contractor', 'role/contractor', 'support_tickets', 'requester_email', '2026-03-02 13:02:00'),
  ('jo_contractor', 'role/contractor', 'payments',        'card_last4',      '2026-03-02 13:05:12'),
  ('jo_contractor', 'role/contractor', 'payments',        'billing_zip',     '2026-03-02 13:06:44'),
  ('mia_growth',    'role/marketing',  'marketing_leads', 'source',          '2026-03-02 15:20:00'),
  ('mia_growth',    'role/marketing',  'marketing_leads', 'lead_name',       '2026-03-02 15:22:03'),
  ('leo_bi',        'role/analyst',    'orders',          'ship_address',    '2026-03-02 16:48:19'),
  ('sam_fraud',     'role/fraud_ops',  'customers',       'full_name',       '2026-03-02 17:05:00');`

const GOVERNANCE_SEED = COLUMN_CATALOG_SEED + "\n" + MASKING_POLICIES_SEED + "\n" + QUERY_LOG_SEED

const piiMaskingAudit: SqlLesson = {
  id: "de-l10-pii-masking-audit",
  title: "PII Tags, Masking Policies, and the Governance Audit",
  summary:
    "Audit a catalog for untagged and unmasked PII, then produce the exposure report a governance review asks for, unaided.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "PII tagging",
    "column masking policies",
    "role-based unmasking",
    "compliance gap analysis",
    "pattern-based discovery",
    "EXISTS and anti-joins",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Governance is three artifacts

"How do you handle PII in a pipeline" is a governance question with a boringly concrete answer, and the answer is three tables in the catalog. If you can name them and query them, you can hold the whole conversation.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["artifact", "what it declares", "the gap when it is missing", "audit question"],
  "rows": [
    ["pii_tag on a column", "this column holds personal data", "nobody knows it is PII, so nothing protects it", "which columns look like PII but carry no tag?"],
    ["masking policy", "how a tagged column is masked, and for whom", "the tag is a sticky note, values return raw", "which tagged columns have no policy?"],
    ["read log", "who read which column, and when", "no evidence, so no audit is possible", "who read PII a policy did not authorize?"]
  ],
  "highlightCols": ["audit question"],
  "caption": "Tag, policy, evidence. Each artifact answers one audit question, and each missing one is a different kind of gap."
}
\`\`\`

## The audit questions, in order

Run them in this order, because each one assumes the previous one is clean.

1. **Discovery: what is PII and untagged?** You cannot protect what nobody labelled. The cheap version is pattern matching on column names (\`%email%\`, \`%phone%\`, \`%ssn%\`, \`%name%\`), which catches the obvious cases and misses \`col_17\`. The managed version samples the data itself and classifies it, which is what Amazon Macie does. Either way the output is a list of candidates a human confirms, and every untagged column is invisible to every query in the rest of this lesson. That is the point: the discovery pass is first because the audits downstream all start from the tag.
2. **Coverage: which tagged columns have no masking policy?** A tag is metadata, not protection. The policy is what actually rewrites the value on read, and it names one role that sees raw values (a fraud analyst who genuinely needs the shipping address, say). Tagged with no policy is the compliance gap, and it is an anti-join.
3. **Exposure: who read what they should not have?** The read log makes the first two auditable. A read is authorized when a masking policy exists for that column **and** its \`unmasked_role\` matches the reader's role. Everything else is exposure: a tagged column with no policy at all (nothing masked it, so the values came back raw), or a tagged column whose policy names a different role, which means the query went at the base column and around the governed view.

## Masking is a read-time rewrite

Worth being precise, because candidates blur it. A masking policy does not change the stored data. It rewrites the value **as it is returned**, per role: \`a***@example.com\` for most roles, the raw address for \`role/fraud_ops\`. That is why the same query, run by two people, correctly returns two different answers, and why an audit has to know the reader's role and not only the query text.

**Common mistake:** auditing only the tagged columns and calling the platform clean. The tagged set is the set somebody already thought about. The dangerous column is the one in a table nobody governs, holding an email address under a name no policy will ever match. Discovery runs first and runs again on a schedule, because every new table arrives untagged.

**Interview nuance:** the answer that lands on "how do you handle PII" is the three artifacts plus the order of the audit: tag it, mask it per role, and prove it with the read log. Adding "and the discovery pass runs on a schedule because new columns arrive untagged" is the sentence that reads as someone who has been through a real review rather than someone who has read the docs.

> **On a real platform this differs.** Here the three artifacts are three SQLite tables. On AWS, Lake Formation holds the tags and the column, row, and cell grants, Macie does the discovery, and CloudTrail plus Athena query history is the read log. Snowflake spells it \`CREATE MASKING POLICY\` bound to a column with \`CURRENT_ROLE()\` inside it, and \`ACCESS_HISTORY\` is the log. Microsoft Fabric calls it dynamic data masking with column-level security. Three artifacts, three vendors, one audit.`,
    demoSeedSql: COLUMN_CATALOG_SEED,
    demoCode: `-- Tag coverage per table. A table with zero tagged columns is either clean or unexamined,
-- and the catalog cannot tell you which.
SELECT table_name,
       COUNT(*) AS columns_total,
       SUM(CASE WHEN pii_tag IS NOT NULL THEN 1 ELSE 0 END) AS tagged_pii
FROM column_catalog
GROUP BY table_name
ORDER BY tagged_pii DESC, table_name;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-pii-masking-audit-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every PII-tagged column that no masking policy covers, as \`(table_name, column_name)\`, ordered by table then column, over \`column_catalog(table_name, column_name, data_type, pii_tag)\` and \`masking_policies(table_name, column_name, policy_name, unmasked_role)\`. This is the compliance gap list.

A column is PII when \`pii_tag\` is not NULL, and a policy covers a column when \`masking_policies\` holds a row for the same table and column.`,
    starterCode: `-- Tagged as PII, protected by nothing.
SELECT c.table_name, c.column_name
FROM column_catalog c
;`,
    hints: [
      "`WHERE c.pii_tag IS NOT NULL` is the PII filter; `= NULL` never matches anything in SQL.",
      "`NOT EXISTS` over `masking_policies`, correlated on both `table_name` and `column_name`, is the anti-join.",
      "A `LEFT JOIN ... WHERE m.column_name IS NULL` reads the same way; either shape is fine.",
    ],
    referenceSolution: `SELECT c.table_name, c.column_name
FROM column_catalog c
WHERE c.pii_tag IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM masking_policies m
    WHERE m.table_name = c.table_name AND m.column_name = c.column_name
  )
ORDER BY c.table_name, c.column_name;`,
    singleFile: {
      seedSql: GOVERNANCE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "column_name"],
        rows: [
          ["customers", "phone_number"],
          ["marketing_leads", "lead_name"],
          ["payments", "billing_zip"],
          ["payments", "card_last4"],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-pii-masking-audit-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every PII read that no masking policy authorized, as \`(user_name, role, table_name, column_name, query_time)\`, oldest read first, over \`query_log\`, \`column_catalog\`, and \`masking_policies\`.

\`query_log\` records reads against the base columns. A read is authorized only when a masking policy exists for that exact table and column **and** its \`unmasked_role\` equals the reader's \`role\`. Everything else is exposure: a tagged column with no policy at all, or a tagged column whose policy names a different role. Columns carrying no \`pii_tag\` are out of scope for this report.`,
    starterCode: `-- The exposure report.
SELECT
FROM query_log q;`,
    hints: [],
    singleFile: {
      seedSql: GOVERNANCE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["user_name", "role", "table_name", "column_name", "query_time"],
        rows: [
          ["leo_bi", "role/analyst", "customers", "email_address", "2026-03-02 11:31:05"],
          ["leo_bi", "role/analyst", "customers", "phone_number", "2026-03-02 11:31:40"],
          ["jo_contractor", "role/contractor", "payments", "card_last4", "2026-03-02 13:05:12"],
          ["jo_contractor", "role/contractor", "payments", "billing_zip", "2026-03-02 13:06:44"],
          ["mia_growth", "role/marketing", "marketing_leads", "lead_name", "2026-03-02 15:22:03"],
          ["leo_bi", "role/analyst", "orders", "ship_address", "2026-03-02 16:48:19"],
          ["sam_fraud", "role/fraud_ops", "customers", "full_name", "2026-03-02 17:05:00"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-pii-masking-audit-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the single heaviest reader of PII-tagged columns, as \`(user_name, pii_reads)\`, over \`query_log\` joined to \`column_catalog\`.`,
      starterCode: `-- Who touches tagged PII the most.
SELECT q.user_name
FROM query_log q
;`,
      hints: [
        "Join on both `table_name` and `column_name`, then keep only rows where `pii_tag IS NOT NULL`.",
        "`ORDER BY pii_reads DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `SELECT q.user_name, COUNT(*) AS pii_reads
FROM query_log q
JOIN column_catalog c
  ON c.table_name = q.table_name AND c.column_name = q.column_name
WHERE c.pii_tag IS NOT NULL
GROUP BY q.user_name
ORDER BY pii_reads DESC, q.user_name
LIMIT 1;`,
      singleFile: {
        seedSql: GOVERNANCE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["user_name", "pii_reads"],
          rows: [["leo_bi", 3]],
        },
      },
    },
    {
      id: "de-l10-pii-masking-audit-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the discovery candidates: every untagged column whose name looks like personal data, as \`(table_name, column_name, data_type)\`, ordered by table then column, over \`column_catalog\`. Match names containing \`email\`, \`phone\`, \`name\`, or \`ssn\`.`,
      starterCode: `-- Columns that look like PII and carry no tag.
SELECT table_name, column_name, data_type
FROM column_catalog
;`,
      hints: [
        "Untagged is `pii_tag IS NULL`.",
        "Chain the four `column_name LIKE '%...%'` tests with `OR`, and keep them inside one parenthesized group so the tag filter still applies.",
      ],
      referenceSolution: `SELECT table_name, column_name, data_type
FROM column_catalog
WHERE pii_tag IS NULL
  AND (column_name LIKE '%email%'
    OR column_name LIKE '%phone%'
    OR column_name LIKE '%name%'
    OR column_name LIKE '%ssn%')
ORDER BY table_name, column_name;`,
      singleFile: {
        seedSql: GOVERNANCE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["table_name", "column_name", "data_type"],
          rows: [
            ["marketing_leads", "work_email", "TEXT"],
            ["support_tickets", "contact_phone", "TEXT"],
            ["support_tickets", "requester_email", "TEXT"],
          ],
        },
      },
    },
  ],
}

export const level10Module4: SqlModule = {
  id: "de-l10-cost-governance-ops",
  title: "Module 10.4: Cost & Governance Operations",
  description:
    "FinOps and DEA-C01 Domain 4 as audits you run in SQL: attribute spend, quantify the Parquet lever, prove least privilege, and audit PII masking.",
  lessons: [costPerQuery, parquetPartitionLever, iamLeastPrivilege, piiMaskingAudit],
}
