/**
 * Data Engineering Level 10, Module 10.3 — Data Quality & Observability.
 *
 * Where quality results GO, and how production watches a warehouse it cannot open. The module is
 * deliberately narrow, because two earlier levels already own the neighbouring ground: Level 8
 * (`de-l8-data-tests-zero-rows`) owns the dbt vocabulary a check is written in (a test is a query
 * returning violating rows and it passes at zero rows; unit tests fixture-test logic in CI, data
 * tests run every load), and SQL Level 5 (`sql-l5-data-quality-gates`) already grades the blocking
 * write-audit-publish gate. So there is no publish-clean-rows / quarantine workspace here. What this
 * module grades instead is what neither reaches: 10.3.1 builds the append-only `check_results`
 * ledger with warn-vs-error severity and derives the run verdict from severity rather than from a
 * raw failure count; 10.3.2 implements the five observability pillars as always-on monitors over
 * catalog metadata (freshness against an SLA, volume against a trailing baseline, distribution
 * drift); 10.3.3 is the composite capstone, detecting breaking schema drift from two catalog
 * snapshots and then walking lineage upstream with a recursive CTE to find the run that succeeded
 * while writing zero rows.
 *
 * Devices: one workspace script (the ledger write, the only GRADED write in the module, though
 * 10.3.1's demo also writes so the learner sees a ledger row land) and single-file SELECTs
 * everywhere else, all over simulated platform metadata named after the real
 * artifact (`check_results`, `warehouse_tables`, `column_catalog`, `lineage_edges`, `pipeline_runs`).
 *
 * Deliberate deviations from CURRICULUM-MAP.md, each also flagged at its point of use below:
 *  - `check_definitions` names FIVE checks (3 error, 2 warn) rather than four (2 and 2). The apply
 *    needs at least one check that PASSES on the staged data, or `status` can be hardcoded to
 *    'fail' and still grade green; and the practice ledger needs both an all-pass run (to grade the
 *    'passed' verdict branch) and a check that never passes (for the never-passed drill), which four
 *    checks over one run set cannot supply.
 *  - The practice ledger holds FIVE prior runs rather than four, and `orders_amount_non_negative`
 *    only starts appearing on 2026-02-28. A check added mid-history is what lets one run be
 *    all-green while another check has still never recorded a pass.
 *  - 10.3.3's catalog plants TWO dropped and TWO type-changed columns rather than one of each, plus
 *    two added columns. One of each makes a two-row expected set that a `LEFT JOIN ... IS NULL`
 *    with no type comparison can half-satisfy; four changes across four tables also give the
 *    blast-radius drill four distinct downstream counts.
 *  - 10.3.3's `lineage_edges` is FOUR hops deep on the refunds branch rather than the three the map
 *    describes, and the zero-row run sits at the deepest node. At three hops the practice grades
 *    green from a fixed-depth self-join, which defeats the one thing the module boss exists to
 *    prove, so the graph is deeper than any hop count a learner would try by hand.
 *  - 10.3.1's live demo writes TWO checks' ledger rows (map: "two checks writing their ledger rows,
 *    then the status refresh") but cannot also show the status refresh: the teach runner prepares a
 *    SINGLE statement (public/workers/sql-sandbox-worker.js, single-file path) and renders its
 *    result set, so a two-statement script would silently run only the first and return no columns.
 *    The demo therefore writes via `INSERT ... RETURNING`, and the upsert half is shown in full in
 *    the teach markdown instead, `excluded` included.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and the
 * workspace reference was executed against its own assertions including the idempotency double-run.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable; practice
 * never ships a referenceSolution.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"
import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 10.3.1 seeds — one night's staged load with four planted defect families, the customer
// dimension the foreign-key check joins to, and the check registry that decides severity. The
// defect counts are engineered distinct (2 duplicate rows, 3 NULL customers, 4 negative amounts,
// 1 orphan) so a learner who computes the wrong violation set cannot land on the right number by
// accident, and `orders_status_allowed` is seeded to pass so `status` cannot be hardcoded.
//
// The orphan check is the NULL trap: order 9006 points at customer 777, who does not exist, while
// three other rows have a NULL customer_id. A NULL matches nothing, so a bare
// `NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = s.customer_id)` calls all three of
// them orphans and reports 4 instead of 1, double counting rows the not-null check already owns.
// (`NOT IN` happens to land on 1 here only because `NULL NOT IN (...)` is NULL rather than true,
// which is luck, not correctness, and the hints say so.)
// ---------------------------------------------------------------------------

const STAGED_ORDERS_SEED = `CREATE TABLE staged_orders (
  order_id    INTEGER,
  customer_id INTEGER,
  amount      REAL,
  status      TEXT,
  order_date  TEXT
);
INSERT INTO staged_orders (order_id, customer_id, amount, status, order_date) VALUES
  (9001, 501,  120.50, 'paid',    '2026-03-01'),
  (9002, 502,   89.99, 'paid',    '2026-03-01'),
  (9003, 503,   45.00, 'paid',    '2026-03-01'),
  (9003, 503,   45.00, 'paid',    '2026-03-01'),
  (9004, NULL, 210.00, 'paid',    '2026-03-01'),
  (9005, 504,  -35.25, 'refund',  '2026-03-01'),
  (9006, 777,   76.40, 'paid',    '2026-03-02'),
  (9007, 501,   15.00, 'paid',    '2026-03-02'),
  (9008, NULL,  60.00, 'pending', '2026-03-02'),
  (9009, 505,  340.00, 'paid',    '2026-03-02'),
  (9010, 502,  -12.00, 'refund',  '2026-03-02'),
  (9011, 506,   99.00, 'paid',    '2026-03-02'),
  (9012, NULL,  55.75, 'pending', '2026-03-02'),
  (9013, 507,   -8.50, 'refund',  '2026-03-02'),
  (9014, 503,  180.00, 'paid',    '2026-03-02'),
  (9015, 504,  -21.00, 'refund',  '2026-03-02');

CREATE TABLE customers (
  customer_id INTEGER,
  region      TEXT
);
INSERT INTO customers (customer_id, region) VALUES
  (501, 'us-east'),
  (502, 'us-west'),
  (503, 'eu-central'),
  (504, 'us-east'),
  (505, 'apac'),
  (506, 'eu-central'),
  (507, 'us-west');`

// The check registry. Severity lives here, on the DEFINITION, which is why the same failing query
// can be a warn in dev and an error in prod without the query itself changing.
const CHECK_DEFINITIONS_SEED = `CREATE TABLE check_definitions (
  check_name TEXT,
  table_name TEXT,
  severity   TEXT      -- error blocks the load, warn records and lets it through
);
INSERT INTO check_definitions (check_name, table_name, severity) VALUES
  ('orders_unique_order_id',      'staged_orders', 'error'),
  ('orders_customer_id_not_null', 'staged_orders', 'error'),
  ('orders_status_allowed',       'staged_orders', 'error'),
  ('orders_amount_non_negative',  'staged_orders', 'warn'),
  ('orders_customer_fk',          'staged_orders', 'warn');`

const CHECK_SUITE_SEED = `${STAGED_ORDERS_SEED}

${CHECK_DEFINITIONS_SEED}

CREATE TABLE check_results (
  run_id      TEXT,
  check_name  TEXT,
  table_name  TEXT,
  failed_rows INTEGER,  -- how many rows the check's violation query returned
  severity    TEXT,     -- copied from check_definitions at run time
  status      TEXT,     -- pass when failed_rows = 0, otherwise fail
  checked_at  TEXT
);

CREATE TABLE dq_check_status (
  check_name      TEXT PRIMARY KEY,   -- exactly one current row per check, enforced by the schema
  table_name      TEXT,
  severity        TEXT,
  failed_rows     INTEGER,
  status          TEXT,
  last_run_id     TEXT,
  last_checked_at TEXT
);`

// The practice/drill ledger: five nights of history for the same registry. Verdict per run is
// blocked, passed, warn, blocked, blocked reading oldest to newest, so the CASE ladder is exercised
// on all three branches. `orders_amount_non_negative` first appears on 2026-02-28 and has never
// recorded a pass, which is what the never-passed drill finds; the all-green 2026-02-27 run is what
// makes the 'passed' branch reachable at the same time.
//
// The failure counts are deliberately NON-MONOTONE against the verdict, because otherwise a learner
// who ranks runs by raw failure count grades green without ever reading severity: run_2026_02_26 has
// ONE failure and is blocked (the failure is an error), run_2026_02_28 has TWO and is only a warn
// (both failures are warns). No threshold on the raw count can reproduce that pair.
const CHECK_LEDGER_SEED = `${CHECK_DEFINITIONS_SEED}

CREATE TABLE check_results (
  run_id      TEXT,
  check_name  TEXT,
  table_name  TEXT,
  failed_rows INTEGER,  -- how many rows the check's violation query returned
  severity    TEXT,     -- copied from check_definitions at run time
  status      TEXT,     -- pass when failed_rows = 0, otherwise fail
  checked_at  TEXT
);
INSERT INTO check_results (run_id, check_name, table_name, failed_rows, severity, status, checked_at) VALUES
  ('run_2026_02_26', 'orders_unique_order_id',      'staged_orders', 2, 'error', 'fail', '2026-02-26 06:15:00'),
  ('run_2026_02_26', 'orders_customer_id_not_null', 'staged_orders', 0, 'error', 'pass', '2026-02-26 06:15:00'),
  ('run_2026_02_26', 'orders_status_allowed',       'staged_orders', 0, 'error', 'pass', '2026-02-26 06:15:00'),
  ('run_2026_02_26', 'orders_customer_fk',          'staged_orders', 0, 'warn',  'pass', '2026-02-26 06:15:00'),
  ('run_2026_02_27', 'orders_unique_order_id',      'staged_orders', 0, 'error', 'pass', '2026-02-27 06:15:00'),
  ('run_2026_02_27', 'orders_customer_id_not_null', 'staged_orders', 0, 'error', 'pass', '2026-02-27 06:15:00'),
  ('run_2026_02_27', 'orders_status_allowed',       'staged_orders', 0, 'error', 'pass', '2026-02-27 06:15:00'),
  ('run_2026_02_27', 'orders_customer_fk',          'staged_orders', 0, 'warn',  'pass', '2026-02-27 06:15:00'),
  ('run_2026_02_28', 'orders_unique_order_id',      'staged_orders', 0, 'error', 'pass', '2026-02-28 06:15:00'),
  ('run_2026_02_28', 'orders_customer_id_not_null', 'staged_orders', 0, 'error', 'pass', '2026-02-28 06:15:00'),
  ('run_2026_02_28', 'orders_status_allowed',       'staged_orders', 0, 'error', 'pass', '2026-02-28 06:15:00'),
  ('run_2026_02_28', 'orders_customer_fk',          'staged_orders', 3, 'warn',  'fail', '2026-02-28 06:15:00'),
  ('run_2026_02_28', 'orders_amount_non_negative',  'staged_orders', 6, 'warn',  'fail', '2026-02-28 06:15:00'),
  ('run_2026_03_01', 'orders_unique_order_id',      'staged_orders', 4, 'error', 'fail', '2026-03-01 06:15:00'),
  ('run_2026_03_01', 'orders_customer_id_not_null', 'staged_orders', 2, 'error', 'fail', '2026-03-01 06:15:00'),
  ('run_2026_03_01', 'orders_status_allowed',       'staged_orders', 0, 'error', 'pass', '2026-03-01 06:15:00'),
  ('run_2026_03_01', 'orders_customer_fk',          'staged_orders', 0, 'warn',  'pass', '2026-03-01 06:15:00'),
  ('run_2026_03_01', 'orders_amount_non_negative',  'staged_orders', 5, 'warn',  'fail', '2026-03-01 06:15:00'),
  ('run_2026_03_02', 'orders_unique_order_id',      'staged_orders', 2, 'error', 'fail', '2026-03-02 06:15:00'),
  ('run_2026_03_02', 'orders_customer_id_not_null', 'staged_orders', 0, 'error', 'pass', '2026-03-02 06:15:00'),
  ('run_2026_03_02', 'orders_status_allowed',       'staged_orders', 0, 'error', 'pass', '2026-03-02 06:15:00'),
  ('run_2026_03_02', 'orders_customer_fk',          'staged_orders', 1, 'warn',  'fail', '2026-03-02 06:15:00'),
  ('run_2026_03_02', 'orders_amount_non_negative',  'staged_orders', 4, 'warn',  'fail', '2026-03-02 06:15:00');`

// ---------------------------------------------------------------------------
// Lesson 10.3.1 — From One Check to a Severity-Ranked Check Ledger
// ---------------------------------------------------------------------------

const checkSuites: SqlLesson = {
  id: "de-l10-check-suites",
  title: "From One Check to a Severity-Ranked Check Ledger",
  summary:
    "Run a whole check suite in one script, record every result in an append-only check_results ledger with its severity, and derive the run verdict from severity rather than from a raw failure count.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "check suites",
    "check results ledger",
    "warn vs error severity",
    "run verdict",
    "append-only history",
    "multi-statement scripts",
    "scoped idempotency",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## A check whose result is not stored can only answer one question

You already know how to write a check. Level 6 wrote them one query at a time, and Level 8 gave you the vocabulary they are written in: a test is a query that returns the violating rows, and it passes when that query returns zero rows. Both stopped at the moment the query returns.

That is the moment production begins. A check you run and throw away can answer exactly one question, "is this broken right now". It cannot answer any of the questions people actually ask during an incident: has this check ever passed, when did it start failing, is this the third night in a row, did the number of bad rows get worse after the fix. Those need a record.

So a production quality stack has two tables, and only two.

## The ledger and the current-status projection

\`\`\`sql
check_results(run_id, check_name, table_name, failed_rows, severity, status, checked_at)
dq_check_status(check_name, table_name, severity, failed_rows, status, last_run_id, last_checked_at)
\`\`\`

\`check_results\` is **append-only**. Every run of every check adds one row and nothing is ever updated in place. That is what gives you history: every night adds one row per check that actually ran, and every question about the past is a filter over them. Checks get added and retired, so a night's block of rows is not always the same height, and the ledger is the only place that records when a check joined the suite.

\`dq_check_status\` is the **current-status projection**, exactly one row per check, and it is what a dashboard reads so the dashboard never has to compute "latest per check" on every page load. Because it holds one row per check, it is written with an upsert, not an append. Two tables, two write shapes, and the difference between them is the whole lesson:

\`\`\`sql
-- append: one more row per check, every run, forever
INSERT INTO check_results (run_id, check_name, table_name, failed_rows, severity, status, checked_at)
SELECT 'run_2026_03_02', d.check_name, d.table_name, v.failed_rows, d.severity, ... ;

-- upsert: the same check overwrites its own single row
INSERT INTO dq_check_status (check_name, failed_rows, status, last_run_id)
SELECT check_name, failed_rows, status, run_id
FROM check_results
WHERE run_id = 'run_2026_03_02'
ON CONFLICT(check_name) DO UPDATE SET
  failed_rows = excluded.failed_rows,
  status      = excluded.status,
  last_run_id = excluded.last_run_id;
\`\`\`

\`excluded\` is the pseudo-table holding the row the INSERT tried to add and could not, because a row with that \`check_name\` was already there. So \`failed_rows = excluded.failed_rows\` reads "keep the new value". SQL Level 4 introduced this in \`sql-l4-idempotent-merge\` and \`sql-l4-scd-type1\`; here it is pointed at a status table, and it is what makes rerunning tonight's suite harmless.

The demo below runs the append half for real against an empty ledger: two of the five checks, two rows written, and what it returns is exactly what landed in \`check_results\`.

## Severity is a property of the check, not of the query

Here is the half that interviews probe and that no earlier level grades. A failing check is not automatically an emergency. Every check definition carries a **severity**:

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["severity", "what it does to the run", "who hears about it", "typical check"],
  "rows": [
    ["error", "blocks the publish, the load stops", "pages the on-call engineer", "primary key is not unique"],
    ["warn", "load continues, the row still lands in the ledger", "shows up on the dashboard, reviewed next morning", "a few negative amounts"],
    ["error in prod, warn in dev", "same query, different consequence", "environment decides, not the SQL", "referential integrity"]
  ],
  "highlightCols": ["severity"],
  "caption": "Severity is attached to the check definition, so the same violating-rows query can block one environment and merely annotate another."
}
\`\`\`

The last row is the point. The query that finds orphaned foreign keys is byte for byte the same in dev and in prod. What differs is what the platform does when it returns rows. That is why severity lives in \`check_definitions\` next to the check name, and why your script must **read** severity from that table rather than typing \`'error'\` into the INSERT. A hardcoded severity is a check you cannot re-tune without a code deploy.

What "blocks the load" actually looks like in SQL is the write-audit-publish gate: stage into a temporary table, run the audit, publish only on a clean pass. SQL Level 5 (\`sql-l5-data-quality-gates\`) grades exactly that, so this lesson points at it and stays on the ledger and the verdict.

## The verdict is derived from severity, not from a count

Once results carry severity, the run verdict falls out of them:

- any error-severity check failed, the verdict is **blocked** and nothing publishes
- no errors failed but at least one warn did, the verdict is **warn** and the load goes through with a note
- nothing failed, the verdict is **passed**

Notice what this makes irrelevant: the raw number of failures. A run with six warn failures publishes. A run with one error failure does not. A pipeline that alerts on "failure count above zero" wakes people up for negative refund amounts and is muted within a month, which is how a team ends up with no alerting at all.

**Common mistake:** treating the ledger as the current state and updating rows in place. The instant you \`UPDATE check_results SET status = ...\`, you have thrown away the history that made the table worth having. Append to the ledger, upsert the projection.

**Interview nuance:** "how do you know your data is correct" has two halves, and most candidates answer only the first. The first half is the check families (uniqueness, not-null, referential integrity, accepted values, freshness). The second half is where the results land, what severity each check carries, and who gets woken up. Candidates who stop at "I write tests" get the follow-up "and then what happens", so answer both halves unprompted.

> **On a real platform this differs.** dbt writes this ledger to \`run_results.json\` after every invocation and teams load that artifact into a warehouse table with this exact shape; dbt also expresses severity directly on the test (\`severity: warn\` or \`error\`, with \`warn_if\` and \`error_if\` thresholds). Great Expectations stores validation results in a results store, Soda keeps a check-history table, and Monte Carlo keeps the same shape behind a UI. Four products, one pair of tables: an append-only result history and a one-row-per-check current status.`,
    demoSeedSql: CHECK_SUITE_SEED,
    demoCode: `-- Two of the five checks, actually writing their ledger rows. This is a WRITE: check_results
-- starts empty above and holds these two rows afterwards. RETURNING shows what landed, and what
-- each severity means for tonight's load.
WITH violations(check_name, failed_rows) AS (
  SELECT 'orders_unique_order_id',
         (SELECT COUNT(*) FROM staged_orders s
          WHERE (SELECT COUNT(*) FROM staged_orders t WHERE t.order_id = s.order_id) > 1)
  UNION ALL
  SELECT 'orders_amount_non_negative',
         (SELECT COUNT(*) FROM staged_orders WHERE amount < 0)
)
INSERT INTO check_results (run_id, check_name, table_name, failed_rows, severity, status, checked_at)
SELECT 'run_2026_03_02', d.check_name, d.table_name, v.failed_rows, d.severity,
       CASE WHEN v.failed_rows = 0 THEN 'pass' ELSE 'fail' END,
       '2026-03-02 06:15:00'
FROM check_definitions d
JOIN violations v ON v.check_name = d.check_name
RETURNING check_name,
          severity,
          failed_rows,
          status,
          CASE
            WHEN status = 'pass' THEN 'nothing to escalate, but the pass is recorded anyway'
            WHEN severity = 'error' THEN 'blocks the publish, pages the on-call'
            ELSE 'load continues, the warning lands in the ledger'
          END AS consequence;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "de-l10-check-suites-apply",
    prompt: `Write a script that runs all five checks in \`check_definitions\` against \`staged_orders\`, appends one \`check_results\` row per check for run \`'run_2026_03_02'\`, and then refreshes \`dq_check_status\` so it holds exactly one current row per check.

Each ledger row carries the check's \`failed_rows\` (how many rows its violation query returns), the \`severity\` and \`table_name\` read from \`check_definitions\`, a \`status\` of \`'pass'\` when \`failed_rows\` is 0 and \`'fail'\` otherwise, and \`checked_at\` set to \`'2026-03-02 06:15:00'\`.

The five checks are:

- \`orders_unique_order_id\`: rows whose \`order_id\` appears more than once
- \`orders_customer_id_not_null\`: rows with a NULL \`customer_id\`
- \`orders_status_allowed\`: rows whose \`status\` is not one of \`'paid'\`, \`'pending'\`, \`'refund'\`
- \`orders_amount_non_negative\`: rows with a negative \`amount\`
- \`orders_customer_fk\`: rows whose \`customer_id\` is not NULL and has no matching row in \`customers\`

\`check_results\` is append-only and grows on every run, which is expected. \`dq_check_status\` is keyed on \`check_name\`, so it must still hold one row per check after the script runs twice.`,
    starterCode: `-- Step 1: append one check_results row per check for run_2026_03_02.
-- Compute each check's violating-row count, then join check_definitions for severity and table_name.

-- Step 2: refresh dq_check_status so it holds exactly one current row per check.
-- The table is keyed on check_name, so this is an upsert, not an append.
`,
    hints: [
      "A `WITH violations(check_name, failed_rows) AS (...)` block of five `SELECT '<name>', (SELECT COUNT(*) ...)` branches joined with `UNION ALL` gives you one row per check, which you then join to `check_definitions` on `check_name`. SQLite allows a CTE in front of an INSERT.",
      "The uniqueness check counts ROWS, not keys: `SELECT COUNT(*) FROM staged_orders s WHERE (SELECT COUNT(*) FROM staged_orders t WHERE t.order_id = s.order_id) > 1` returns every row that shares its order_id with another.",
      "The foreign-key check must skip the NULL customer_id rows, because the not-null check already owns those and counting them twice inflates both numbers. A bare `NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = s.customer_id)` calls every NULL an orphan, since a NULL matches no customer, so add `s.customer_id IS NOT NULL` alongside it. `NOT IN` reaches the same answer here for a different reason (`NULL NOT IN (...)` evaluates to NULL, not true, so those rows silently drop out), and that reason stops holding the day a NULL appears inside `customers`.",
      "Read `severity` and `table_name` from `check_definitions` in the SELECT you insert from. Typing the severity literal into the INSERT means retuning a check needs a code change.",
      "Step 2 is `INSERT INTO dq_check_status (...) SELECT ... FROM check_results WHERE run_id = 'run_2026_03_02' ON CONFLICT(check_name) DO UPDATE SET failed_rows = excluded.failed_rows, ...`. The upsert is what survives the rerun: the ledger will hold two identical rows per check by then, and every one of them writes the same values.",
    ],
    referenceSolution: `WITH violations(check_name, failed_rows) AS (
  SELECT 'orders_unique_order_id',
         (SELECT COUNT(*) FROM staged_orders s
          WHERE (SELECT COUNT(*) FROM staged_orders t WHERE t.order_id = s.order_id) > 1)
  UNION ALL
  SELECT 'orders_customer_id_not_null',
         (SELECT COUNT(*) FROM staged_orders WHERE customer_id IS NULL)
  UNION ALL
  SELECT 'orders_status_allowed',
         (SELECT COUNT(*) FROM staged_orders WHERE status NOT IN ('paid', 'pending', 'refund'))
  UNION ALL
  SELECT 'orders_amount_non_negative',
         (SELECT COUNT(*) FROM staged_orders WHERE amount < 0)
  UNION ALL
  SELECT 'orders_customer_fk',
         (SELECT COUNT(*) FROM staged_orders s
          WHERE s.customer_id IS NOT NULL
            AND NOT EXISTS (SELECT 1 FROM customers c WHERE c.customer_id = s.customer_id))
)
INSERT INTO check_results (run_id, check_name, table_name, failed_rows, severity, status, checked_at)
SELECT 'run_2026_03_02', d.check_name, d.table_name, v.failed_rows, d.severity,
       CASE WHEN v.failed_rows = 0 THEN 'pass' ELSE 'fail' END,
       '2026-03-02 06:15:00'
FROM check_definitions d
JOIN violations v ON v.check_name = d.check_name;

INSERT INTO dq_check_status (check_name, table_name, severity, failed_rows, status, last_run_id, last_checked_at)
SELECT check_name, table_name, severity, failed_rows, status, run_id, checked_at
FROM check_results
WHERE run_id = 'run_2026_03_02'
ON CONFLICT(check_name) DO UPDATE SET
  table_name      = excluded.table_name,
  severity        = excluded.severity,
  failed_rows     = excluded.failed_rows,
  status          = excluded.status,
  last_run_id     = excluded.last_run_id,
  last_checked_at = excluded.last_checked_at;`,
    seedSql: CHECK_SUITE_SEED,
    // `check_results` is an append-only ledger that grows by design on every run, so a bare
    // checkIdempotency (which compares whole-workspace state) would fail every correct solution.
    // Only the current-status projection is required to be byte-stable across the double run.
    checkIdempotency: true,
    idempotencyTables: ["dq_check_status"],
    assertions: [
      {
        suite: "ledger",
        name: "every check recorded its own failed_rows, severity, and status",
        sql: `WITH expected(check_name, failed_rows, severity, status) AS (
  VALUES ('orders_unique_order_id', 2, 'error', 'fail'),
         ('orders_customer_id_not_null', 3, 'error', 'fail'),
         ('orders_status_allowed', 0, 'error', 'pass'),
         ('orders_amount_non_negative', 4, 'warn', 'fail'),
         ('orders_customer_fk', 1, 'warn', 'fail')
),
got AS (
  SELECT DISTINCT check_name, failed_rows, severity, status
  FROM check_results
  WHERE run_id = 'run_2026_03_02'
)
SELECT * FROM (SELECT * FROM got EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT * FROM got)`,
      },
      {
        suite: "ledger",
        name: "the run recorded one result for every defined check",
        sql: `SELECT 1
WHERE (SELECT COUNT(DISTINCT check_name) FROM check_results WHERE run_id = 'run_2026_03_02')
      <> (SELECT COUNT(*) FROM check_definitions)`,
      },
      {
        suite: "ledger",
        name: "severity and table_name agree with check_definitions",
        isHidden: true,
        sql: `SELECT r.check_name
FROM check_results r
LEFT JOIN check_definitions d
  ON d.check_name = r.check_name
 AND d.severity = r.severity
 AND d.table_name = r.table_name
WHERE d.check_name IS NULL`,
      },
      {
        suite: "ledger",
        name: "the foreign-key check ignored the NULL customer_id rows",
        isHidden: true,
        sql: `SELECT 1
WHERE (SELECT DISTINCT failed_rows FROM check_results
       WHERE run_id = 'run_2026_03_02' AND check_name = 'orders_customer_fk') <> 1`,
      },
      {
        suite: "ledger",
        name: "checked_at was stamped on every ledger row",
        isHidden: true,
        sql: `SELECT run_id FROM check_results WHERE checked_at <> '2026-03-02 06:15:00'`,
      },
      {
        suite: "status",
        name: "dq_check_status holds exactly one current row per check",
        sql: `SELECT check_name FROM dq_check_status GROUP BY check_name HAVING COUNT(*) > 1
UNION ALL
SELECT 'row_count_mismatch'
WHERE (SELECT COUNT(*) FROM dq_check_status) <> (SELECT COUNT(*) FROM check_definitions)`,
      },
      {
        suite: "status",
        name: "the current status matches this run's ledger rows",
        isHidden: true,
        sql: `SELECT s.check_name
FROM dq_check_status s
LEFT JOIN (
  SELECT DISTINCT check_name, table_name, severity, failed_rows, status, run_id, checked_at
  FROM check_results
  WHERE run_id = 'run_2026_03_02'
) r
  ON r.check_name = s.check_name
 AND r.table_name = s.table_name
 AND r.severity = s.severity
 AND r.failed_rows = s.failed_rows
 AND r.status = s.status
 AND r.run_id = s.last_run_id
 AND r.checked_at = s.last_checked_at
WHERE r.check_name IS NULL`,
      },
      {
        suite: "status",
        name: "the check that found nothing is recorded as a pass, not skipped",
        isHidden: true,
        sql: `SELECT 1
WHERE NOT EXISTS (
  SELECT 1 FROM dq_check_status
  WHERE check_name = 'orders_status_allowed' AND status = 'pass' AND failed_rows = 0
)`,
      },
    ],
  }),
  practice: {
    id: "de-l10-check-suites-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the verdict for each run in the ledger, as \`(run_id, error_failures, warn_failures, verdict)\`, newest run first, over \`check_results(run_id, check_name, table_name, failed_rows, severity, status, checked_at)\`.

\`error_failures\` counts the failing checks whose severity is \`'error'\`, \`warn_failures\` counts the failing checks whose severity is \`'warn'\`, and \`verdict\` is \`'blocked'\` when any error-severity check failed, \`'warn'\` when only warn-severity checks failed, and \`'passed'\` otherwise. Alias every column exactly, and sort by \`run_id\` descending.`,
    starterCode: `-- One row per run: how many errors failed, how many warns failed, and what that means.
SELECT
FROM check_results
GROUP BY run_id;`,
    hints: [
      "Conditional aggregation gives you both counts in one pass: `SUM(CASE WHEN severity = 'error' AND status = 'fail' THEN 1 ELSE 0 END)`.",
      "The verdict is a CASE ladder over those same two sums, and order matters: test the error branch first, because a run with both kinds of failure is blocked, not warned.",
      "Not every run recorded every check, so count what is in the ledger for that run rather than assuming five rows per run.",
    ],
    singleFile: {
      seedSql: CHECK_LEDGER_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["run_id", "error_failures", "warn_failures", "verdict"],
        rows: [
          ["run_2026_03_02", 1, 2, "blocked"],
          ["run_2026_03_01", 2, 1, "blocked"],
          ["run_2026_02_28", 0, 2, "warn"],
          ["run_2026_02_27", 0, 0, "passed"],
          ["run_2026_02_26", 1, 0, "blocked"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-check-suites-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many checks the registry defines at each severity, as \`(severity, check_count)\`, most checks first, over \`check_definitions(check_name, table_name, severity)\`.

Alias the counted column exactly \`check_count\`.`,
      starterCode: `-- How much of the suite can actually block a load?
SELECT
FROM check_definitions;`,
      hints: [
        "Group by `severity` and count the rows in each group.",
        "`ORDER BY check_count DESC` puts the larger severity band first.",
      ],
      referenceSolution: `SELECT severity, COUNT(*) AS check_count
FROM check_definitions
GROUP BY severity
ORDER BY check_count DESC;`,
      singleFile: {
        seedSql: CHECK_DEFINITIONS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["severity", "check_count"],
          rows: [
            ["error", 3],
            ["warn", 2],
          ],
        },
      },
    },
    {
      id: "de-l10-check-suites-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every check that has never recorded a pass anywhere in the ledger, as \`(check_name, severity, runs_recorded, total_failed_rows)\`, alphabetically by check name, over \`check_results\`.

\`runs_recorded\` is how many runs the check appears in, and \`total_failed_rows\` is its summed \`failed_rows\` across those runs. Alias every column exactly.`,
      starterCode: `-- A check that has never once gone green is either genuinely broken data or a broken check.
SELECT
FROM check_results r
GROUP BY r.check_name, r.severity;`,
      hints: [
        "\"Never passed\" is an anti-join, not a filter: `NOT EXISTS (SELECT 1 FROM check_results p WHERE p.check_name = r.check_name AND p.status = 'pass')`.",
        "Filtering with `WHERE status <> 'pass'` before grouping is the trap: that keeps every check that has ever failed, including the ones that also passed on other nights.",
      ],
      referenceSolution: `SELECT r.check_name,
       r.severity,
       COUNT(*) AS runs_recorded,
       SUM(r.failed_rows) AS total_failed_rows
FROM check_results r
WHERE NOT EXISTS (
        SELECT 1 FROM check_results p
        WHERE p.check_name = r.check_name AND p.status = 'pass'
      )
GROUP BY r.check_name, r.severity
ORDER BY r.check_name;`,
      singleFile: {
        seedSql: CHECK_LEDGER_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["check_name", "severity", "runs_recorded", "total_failed_rows"],
          rows: [["orders_amount_non_negative", "warn", 3, 15]],
        },
      },
    },
    {
      id: "de-l10-check-suites-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns each check currently in a failing streak, as \`(check_name, severity, failing_since_run, consecutive_failures)\`, longest streak first, over \`check_results\`.

A check is in a streak when its most recent result is a fail. \`consecutive_failures\` counts the runs it has failed since its last pass (all of them when it has never passed), and \`failing_since_run\` is the earliest \`run_id\` in that streak. Alias every column exactly and break ties by \`check_name\`.`,
      starterCode: `-- "Is this the third night in a row?" is the question the ledger exists to answer.
SELECT
FROM check_results;`,
      hints: [
        "A window function carries each check's last passing run onto every one of its rows: `MAX(CASE WHEN status = 'pass' THEN run_id END) OVER (PARTITION BY check_name)`.",
        "Keep only the failing rows that come after that run, and remember the never-passed case leaves the window value NULL, so guard it with `last_pass_run IS NULL OR run_id > last_pass_run`.",
        "A check whose latest run passed has no failing rows after its last pass, so it drops out of the result on its own with no extra filter.",
      ],
      referenceSolution: `WITH marked AS (
  SELECT check_name, severity, run_id, status,
         MAX(CASE WHEN status = 'pass' THEN run_id END) OVER (PARTITION BY check_name) AS last_pass_run
  FROM check_results
)
SELECT check_name,
       severity,
       MIN(run_id) AS failing_since_run,
       COUNT(*) AS consecutive_failures
FROM marked
WHERE status = 'fail'
  AND (last_pass_run IS NULL OR run_id > last_pass_run)
GROUP BY check_name, severity
ORDER BY consecutive_failures DESC, check_name;`,
      singleFile: {
        seedSql: CHECK_LEDGER_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["check_name", "severity", "failing_since_run", "consecutive_failures"],
          rows: [
            ["orders_amount_non_negative", "warn", "run_2026_02_28", 3],
            ["orders_unique_order_id", "error", "run_2026_03_01", 2],
            ["orders_customer_fk", "warn", "run_2026_03_02", 1],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 10.3.2 seeds — the catalog side of observability. `warehouse_tables` is the metadata a
// warehouse keeps about its own tables (owner, last write, agreed SLA); `table_snapshots` is the
// daily profile a monitoring job records so volume and distribution have a baseline to compare to.
//
// Boundary rows are deliberate. `dim_channel` is stale by EXACTLY its SLA (180 minutes at the fixed
// 09:00 evaluation time), so a `>=` predicate reports a breach that is not one. In the snapshot
// history, one table collapses (fct_web_events, 902k to 81k) and one spikes (stg_clickstream, 50k
// to 98k), so a one-sided `row_count < avg` monitor misses half the anomalies; fct_orders drifts on
// null rate only, which is the distribution pillar firing while volume stays flat.
// ---------------------------------------------------------------------------

const WAREHOUSE_TABLES_SEED = `CREATE TABLE warehouse_tables (
  table_name            TEXT,
  owner                 TEXT,
  last_loaded_at        TEXT,     -- catalog metadata: when the table last received a write
  freshness_sla_minutes INTEGER   -- how stale the table is allowed to get before it breaches
);
INSERT INTO warehouse_tables (table_name, owner, last_loaded_at, freshness_sla_minutes) VALUES
  ('fct_orders',           'analytics', '2026-03-02 08:45:00',   60),
  ('dim_customer',         'analytics', '2026-03-02 06:30:00',  180),
  ('fct_web_events',       'growth',    '2026-03-02 02:10:00',  120),
  ('stg_clickstream',      'growth',    '2026-03-02 08:10:00',   30),
  ('mart_marketing_spend', 'growth',    '2026-03-02 04:45:00',  240),
  ('dim_channel',          'growth',    '2026-03-02 06:00:00',  180),
  ('mart_daily_revenue',   'finance',   '2026-03-01 23:00:00',  480),
  ('fct_payments',         'finance',   '2026-03-01 18:20:00',  360),
  ('dim_product',          'merch',     '2026-03-02 07:55:00',   90),
  ('dim_store',            'merch',     '2026-02-28 21:00:00', 1440);`

const TABLE_SNAPSHOTS_SEED = `CREATE TABLE table_snapshots (
  table_name         TEXT,
  snapshot_date      TEXT,
  row_count          INTEGER,  -- rows the table held after that day's load
  null_user_id_rate  REAL      -- share of rows with a NULL user_id, the distribution monitor's input
);
INSERT INTO table_snapshots (table_name, snapshot_date, row_count, null_user_id_rate) VALUES
  ('fct_orders',      '2026-02-21',  12000, 0.010),
  ('fct_orders',      '2026-02-22',  12140, 0.011),
  ('fct_orders',      '2026-02-23',  11980, 0.012),
  ('fct_orders',      '2026-02-24',  12310, 0.010),
  ('fct_orders',      '2026-02-25',  12250, 0.013),
  ('fct_orders',      '2026-02-26',  11890, 0.011),
  ('fct_orders',      '2026-02-27',  12020, 0.012),
  ('fct_orders',      '2026-02-28',  12180, 0.010),
  ('fct_orders',      '2026-03-01',  12090, 0.011),
  ('fct_orders',      '2026-03-02',  11960, 0.058),
  ('fct_web_events',  '2026-02-21', 880000, 0.002),
  ('fct_web_events',  '2026-02-22', 905000, 0.002),
  ('fct_web_events',  '2026-02-23', 912000, 0.002),
  ('fct_web_events',  '2026-02-24', 898000, 0.002),
  ('fct_web_events',  '2026-02-25', 921000, 0.002),
  ('fct_web_events',  '2026-02-26', 907000, 0.002),
  ('fct_web_events',  '2026-02-27', 894000, 0.002),
  ('fct_web_events',  '2026-02-28', 916000, 0.002),
  ('fct_web_events',  '2026-03-01', 902000, 0.002),
  ('fct_web_events',  '2026-03-02',  81000, 0.002),
  ('stg_clickstream', '2026-02-21',  50000, 0.040),
  ('stg_clickstream', '2026-02-22',  51200, 0.042),
  ('stg_clickstream', '2026-02-23',  49800, 0.038),
  ('stg_clickstream', '2026-02-24',  50600, 0.041),
  ('stg_clickstream', '2026-02-25',  52100, 0.039),
  ('stg_clickstream', '2026-02-26',  49500, 0.043),
  ('stg_clickstream', '2026-02-27',  50900, 0.040),
  ('stg_clickstream', '2026-02-28',  51400, 0.042),
  ('stg_clickstream', '2026-03-01',  50300, 0.039),
  ('stg_clickstream', '2026-03-02',  97800, 0.096),
  ('dim_customer',    '2026-02-21',   4000, 0.001),
  ('dim_customer',    '2026-02-22',   4020, 0.001),
  ('dim_customer',    '2026-02-23',   4035, 0.001),
  ('dim_customer',    '2026-02-24',   4048, 0.001),
  ('dim_customer',    '2026-02-25',   4060, 0.001),
  ('dim_customer',    '2026-02-26',   4075, 0.001),
  ('dim_customer',    '2026-02-27',   4088, 0.001),
  ('dim_customer',    '2026-02-28',   4101, 0.001),
  ('dim_customer',    '2026-03-01',   4115, 0.001),
  ('dim_customer',    '2026-03-02',   4130, 0.001);`

// ---------------------------------------------------------------------------
// Lesson 10.3.2 — The Five Pillars: Freshness and Volume Monitors in SQL
// ---------------------------------------------------------------------------

const observabilityPillars: SqlLesson = {
  id: "de-l10-observability-pillars",
  title: "The Five Pillars: Freshness and Volume Monitors in SQL",
  summary:
    "Name the five observability pillars, then implement the freshness, volume, and distribution monitors as ordinary SQL over table metadata rather than over the data itself.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "five observability pillars",
    "freshness SLA breach detection",
    "trailing-window baselines",
    "volume anomaly detection",
    "distribution drift",
    "window functions",
    "date arithmetic",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Five pillars, and why they are five

Data observability is usually framed as five pillars, and the framing is worth memorizing because interviewers use it as a checklist:

1. **Freshness.** Is the data recent enough? A table that stopped loading at 2 a.m. looks perfectly correct and is completely wrong.
2. **Volume.** Did the expected amount of data arrive? Half a load is the failure people notice last.
3. **Schema.** Did the shape change? A dropped or retyped column breaks consumers that never touched the pipeline.
4. **Distribution.** Are the values still shaped the way they were? A null rate that jumps from 1% to 6% is a broken join upstream.
5. **Lineage.** What is upstream and downstream of this table? Without it you cannot answer "what else is affected".

The metric all five exist to shrink is **data downtime**: the total time your data was wrong, late, or missing. Framing your monitoring answer around reducing data downtime rather than around "adding alerts" is what separates an engineer from someone who has installed a tool.

## Monitors read metadata, not data

Here is the design decision that makes always-on monitoring affordable. A monitor does not scan the table it watches. It reads the **metadata** a warehouse already keeps about that table: when it was last written, how many rows it holds, what its columns are. Scanning a billion-row fact table every fifteen minutes to ask "is it fresh" would cost more than the pipeline that built it.

So the monitors below run over two metadata tables. \`warehouse_tables\` is the catalog's own record of each table (owner, last write, agreed SLA). \`table_snapshots\` is the daily profile a monitoring job appends: row count and null rate per table per day. Both are tiny, and both can be queried every few minutes forever.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["pillar", "what breaks when it fails", "the SQL shape"],
  "rows": [
    ["freshness", "the dashboard shows yesterday and nobody notices", "age from last_loaded_at compared to an SLA in minutes"],
    ["volume", "half the rows arrived and the totals quietly drop", "latest row_count against a trailing-window AVG, with a deviation threshold"],
    ["schema", "a dropped or retyped column breaks every consumer", "two catalog snapshots diffed with a self-join"],
    ["distribution", "a broken join fills a column with NULLs", "latest null rate or category share against its own trailing average"],
    ["lineage", "you cannot answer what else is affected", "an edges table walked with a recursive CTE"]
  ],
  "highlightCols": ["pillar"],
  "caption": "Each pillar is one query shape over metadata. Schema and lineage are the next lesson; freshness, volume, and distribution are this one."
}
\`\`\`

## Freshness: age against an SLA

Freshness is subtraction. Take the evaluation time, subtract \`last_loaded_at\`, convert to minutes, and compare to the table's agreed \`freshness_sla_minutes\`. In SQLite that is \`strftime('%s', ...)\` on both sides, which gives epoch seconds:

\`\`\`sql
(strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60
\`\`\`

Two details decide whether the monitor is trustworthy. First, an SLA is per table, not global: a streaming staging table is late after 30 minutes, a slowly changing dimension is fine for a day. Second, a table sitting at exactly its SLA is not yet breaching, so the comparison is strictly greater than. Getting that wrong is how a monitor starts paging on healthy tables and gets muted.

**This is not the same freshness Level 9 measured.** \`de-l9-freshness-slas\` measures the age of the DATA: how far behind real time the newest event in the table is, derived from event timestamps. That is the pipeline-side question and it needs the table's contents. This lesson measures the age of the WRITE: how long since anything landed, read from catalog metadata. A table can be freshly written and still full of stale events (the source stopped producing), and it can hold very recent events while the write itself is hours late. Interviewers ask which one you mean, so say it: catalog freshness is the cheap always-on watcher, event-time freshness is the accurate one that costs a scan.

## Volume: today against its own history

A row count means nothing on its own. It means something against a baseline, and the standard baseline is the same table's trailing window. A window function gives you it directly:

\`\`\`sql
AVG(row_count) OVER (
  PARTITION BY table_name ORDER BY snapshot_date
  ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING
)
\`\`\`

\`1 PRECEDING\` as the upper bound is the part people get wrong. Including today in its own baseline drags the average toward the anomaly and hides small breaks. Then compare with a percentage deviation and a threshold, and make the comparison two-sided: a load that doubles is as suspicious as a load that halves, and duplicate-producing bugs are at least as common as missing-data bugs.

## Distribution: the same query on a different column

Once you have the trailing-window shape you get the distribution pillar almost free. Swap \`row_count\` for \`null_user_id_rate\` and you are monitoring whether a column's null rate suddenly doubled, which is what a silently broken join looks like from the outside. The same shape monitors a category's share of rows, an average order value, or a percentage of negative amounts.

**Common mistake:** including the current day inside its own trailing baseline. With a 7-day window that pulls the average about 12% toward whatever today did, which is exactly the direction that hides a real anomaly. Bound the window at \`1 PRECEDING\`.

**Interview nuance:** "how would you monitor this pipeline in production" is scored on two things: naming the five pillars without hesitating, and being able to sketch the freshness and volume queries on a whiteboard. Freshness and volume are the pair an intern is expected to implement, and they catch most real incidents. Mentioning that the monitors read metadata rather than the tables themselves is the detail that shows you have thought about the cost.

> **On a real platform this differs.** Monte Carlo, Soda, and Bigeye ship these monitors as configuration rather than SQL, and they learn the thresholds from history instead of taking a hardcoded 50%. dbt has \`dbt source freshness\` for the freshness pillar specifically, with \`warn_after\` and \`error_after\` in the source config. The metadata is also already there in real warehouses: Snowflake's \`INFORMATION_SCHEMA.TABLES\` carries \`LAST_ALTERED\` and \`ROW_COUNT\`, BigQuery's \`__TABLES__\` carries \`last_modified_time\` and \`row_count\`, and Glue keeps partition-level metadata. The queries you are about to write are the ones those products run for you.`,
    demoSeedSql: WAREHOUSE_TABLES_SEED,
    demoCode: `-- The freshness monitor, evaluated at a fixed 2026-03-02 09:00. Note dim_channel: stale by
-- exactly its SLA, and therefore not yet breaching.
SELECT table_name,
       owner,
       (strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60 AS minutes_stale,
       freshness_sla_minutes,
       CASE
         WHEN (strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60 > freshness_sla_minutes
           THEN 'BREACHED'
         ELSE 'fresh'
       END AS freshness_status
FROM warehouse_tables
ORDER BY minutes_stale DESC;`,
    showDemoInput: true,
  },
  apply: {
    id: "de-l10-observability-pillars-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every table breaching its freshness SLA as of \`'2026-03-02 09:00:00'\`, as \`(table_name, minutes_late)\`, most late first, over \`warehouse_tables(table_name, owner, last_loaded_at, freshness_sla_minutes)\`.

A table breaches when its age in minutes is strictly greater than \`freshness_sla_minutes\`, and \`minutes_late\` is how many minutes past the SLA it is. Take the age from epoch seconds, the way the demo does, so whole minutes come from integer division rather than from rounding. Alias the computed column exactly \`minutes_late\`.`,
    starterCode: `-- The always-on freshness monitor, evaluated at a fixed point in time.
-- age in whole minutes = (strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60
SELECT
  -- one row per breaching table, with how far past its SLA it has drifted
FROM warehouse_tables;`,
    hints: [
      "`strftime('%s', ...)` converts a timestamp to epoch seconds, so `(strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60` is the age in whole minutes.",
      "`minutes_late` is that age minus `freshness_sla_minutes`, and the WHERE clause keeps only rows where the age exceeds the SLA.",
      "Use a strict `>` in the filter. One table is stale by exactly its SLA and must not appear.",
    ],
    referenceSolution: `SELECT table_name,
       CAST((strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60
            - freshness_sla_minutes AS INTEGER) AS minutes_late
FROM warehouse_tables
WHERE (strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60
      > freshness_sla_minutes
ORDER BY minutes_late DESC;`,
    singleFile: {
      seedSql: WAREHOUSE_TABLES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "minutes_late"],
        rows: [
          ["dim_store", 720],
          ["fct_payments", 520],
          ["fct_web_events", 290],
          ["mart_daily_revenue", 120],
          ["stg_clickstream", 20],
          ["mart_marketing_spend", 15],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-observability-pillars-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every table whose latest row count deviates by more than 50% from its trailing 7-day average, as \`(table_name, latest_rows, trailing_avg, deviation_pct)\`, biggest absolute deviation first, over \`table_snapshots(table_name, snapshot_date, row_count, null_user_id_rate)\`.

The trailing average covers the 7 snapshot days before the latest one and must not include the latest day itself. \`deviation_pct\` is the signed percentage difference from that average, so a collapsed load comes back negative and a doubled load comes back positive. Round \`trailing_avg\` and \`deviation_pct\` to 1 decimal place and alias every column exactly.`,
    starterCode: `-- The volume monitor: today's row count only means something next to this table's own history.
SELECT
FROM table_snapshots;`,
    hints: [
      "`AVG(row_count) OVER (PARTITION BY table_name ORDER BY snapshot_date ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING)` is the trailing baseline that excludes the current row.",
      "`ROW_NUMBER() OVER (PARTITION BY table_name ORDER BY snapshot_date DESC) = 1` picks each table's latest snapshot after the window has been computed over the full history.",
      "The threshold is on the absolute deviation, because a load that doubles is as much of an anomaly as a load that halves.",
    ],
    singleFile: {
      seedSql: TABLE_SNAPSHOTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "latest_rows", "trailing_avg", "deviation_pct"],
        rows: [
          ["stg_clickstream", 97800, 50657.1, 93.1],
          ["fct_web_events", 81000, 907142.9, -91.1],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-observability-pillars-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the stalest table owned by each team as of \`'2026-03-02 09:00:00'\`, as \`(owner, table_name, minutes_stale)\`, stalest first, over \`warehouse_tables\`.

\`minutes_stale\` is the whole-minute age since \`last_loaded_at\`, regardless of the SLA, taken from epoch seconds exactly as the Apply exercise took it. Alias every column exactly.`,
      starterCode: `-- The morning triage list, one row per owning team.
-- age in whole minutes = (strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60
SELECT
FROM warehouse_tables;`,
      hints: [
        "Compute the age once in a CTE so both the SELECT and the per-owner maximum can reuse it.",
        "A correlated subquery picking `MAX(minutes_stale)` for the same owner keeps this to one pass of thinking.",
      ],
      referenceSolution: `WITH aged AS (
  SELECT owner, table_name,
         CAST((strftime('%s', '2026-03-02 09:00:00') - strftime('%s', last_loaded_at)) / 60 AS INTEGER) AS minutes_stale
  FROM warehouse_tables
)
SELECT owner, table_name, minutes_stale
FROM aged a
WHERE minutes_stale = (SELECT MAX(minutes_stale) FROM aged b WHERE b.owner = a.owner)
ORDER BY minutes_stale DESC;`,
      singleFile: {
        seedSql: WAREHOUSE_TABLES_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["owner", "table_name", "minutes_stale"],
          rows: [
            ["merch", "dim_store", 2160],
            ["finance", "fct_payments", 880],
            ["growth", "fct_web_events", 410],
            ["analytics", "dim_customer", 150],
          ],
        },
      },
    },
    {
      id: "de-l10-observability-pillars-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the day-over-day row-count change for every snapshot that has a previous day, as \`(table_name, snapshot_date, row_count, prev_row_count, pct_change)\`, ordered by table name then date, over \`table_snapshots\`.

\`pct_change\` is the percentage change from the previous day, rounded to 2 decimal places. Drop each table's first snapshot, which has nothing to compare to. Alias every column exactly.`,
      starterCode: `-- The simplest volume signal there is: what changed since yesterday, per table.
SELECT
FROM table_snapshots;`,
      hints: [
        "`LAG(row_count) OVER (PARTITION BY table_name ORDER BY snapshot_date)` is the previous day's count.",
        "Compute the LAG in a CTE, then filter `prev_row_count IS NOT NULL` in the outer query. A window function cannot be used in the WHERE clause of the same SELECT that computes it.",
        "Multiply by `100.0`, not `100`, or integer division truncates every small change to zero.",
      ],
      referenceSolution: `WITH stepped AS (
  SELECT table_name, snapshot_date, row_count,
         LAG(row_count) OVER (PARTITION BY table_name ORDER BY snapshot_date) AS prev_row_count
  FROM table_snapshots
)
SELECT table_name, snapshot_date, row_count, prev_row_count,
       ROUND((row_count - prev_row_count) * 100.0 / prev_row_count, 2) AS pct_change
FROM stepped
WHERE prev_row_count IS NOT NULL
ORDER BY table_name, snapshot_date;`,
      singleFile: {
        seedSql: TABLE_SNAPSHOTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["table_name", "snapshot_date", "row_count", "prev_row_count", "pct_change"],
          rows: [
            ["dim_customer", "2026-02-22", 4020, 4000, 0.5],
            ["dim_customer", "2026-02-23", 4035, 4020, 0.37],
            ["dim_customer", "2026-02-24", 4048, 4035, 0.32],
            ["dim_customer", "2026-02-25", 4060, 4048, 0.3],
            ["dim_customer", "2026-02-26", 4075, 4060, 0.37],
            ["dim_customer", "2026-02-27", 4088, 4075, 0.32],
            ["dim_customer", "2026-02-28", 4101, 4088, 0.32],
            ["dim_customer", "2026-03-01", 4115, 4101, 0.34],
            ["dim_customer", "2026-03-02", 4130, 4115, 0.36],
            ["fct_orders", "2026-02-22", 12140, 12000, 1.17],
            ["fct_orders", "2026-02-23", 11980, 12140, -1.32],
            ["fct_orders", "2026-02-24", 12310, 11980, 2.75],
            ["fct_orders", "2026-02-25", 12250, 12310, -0.49],
            ["fct_orders", "2026-02-26", 11890, 12250, -2.94],
            ["fct_orders", "2026-02-27", 12020, 11890, 1.09],
            ["fct_orders", "2026-02-28", 12180, 12020, 1.33],
            ["fct_orders", "2026-03-01", 12090, 12180, -0.74],
            ["fct_orders", "2026-03-02", 11960, 12090, -1.08],
            ["fct_web_events", "2026-02-22", 905000, 880000, 2.84],
            ["fct_web_events", "2026-02-23", 912000, 905000, 0.77],
            ["fct_web_events", "2026-02-24", 898000, 912000, -1.54],
            ["fct_web_events", "2026-02-25", 921000, 898000, 2.56],
            ["fct_web_events", "2026-02-26", 907000, 921000, -1.52],
            ["fct_web_events", "2026-02-27", 894000, 907000, -1.43],
            ["fct_web_events", "2026-02-28", 916000, 894000, 2.46],
            ["fct_web_events", "2026-03-01", 902000, 916000, -1.53],
            ["fct_web_events", "2026-03-02", 81000, 902000, -91.02],
            ["stg_clickstream", "2026-02-22", 51200, 50000, 2.4],
            ["stg_clickstream", "2026-02-23", 49800, 51200, -2.73],
            ["stg_clickstream", "2026-02-24", 50600, 49800, 1.61],
            ["stg_clickstream", "2026-02-25", 52100, 50600, 2.96],
            ["stg_clickstream", "2026-02-26", 49500, 52100, -4.99],
            ["stg_clickstream", "2026-02-27", 50900, 49500, 2.83],
            ["stg_clickstream", "2026-02-28", 51400, 50900, 0.98],
            ["stg_clickstream", "2026-03-01", 50300, 51400, -2.14],
            ["stg_clickstream", "2026-03-02", 97800, 50300, 94.43],
          ],
        },
      },
    },
    {
      id: "de-l10-observability-pillars-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every table whose latest null rate is more than double its trailing 7-day average, as \`(table_name, latest_null_rate, trailing_avg_null_rate, rate_ratio)\`, biggest ratio first, over \`table_snapshots\`.

\`rate_ratio\` is the latest rate divided by the trailing average. Round the two rate columns to 4 decimal places and \`rate_ratio\` to 2, and alias every column exactly.`,
      starterCode: `-- The distribution pillar: the same trailing-window shape, pointed at a rate instead of a count.
SELECT
FROM table_snapshots;`,
      hints: [
        "This is the volume monitor with `null_user_id_rate` swapped in for `row_count`, which is the point of the drill.",
        "Keep the trailing window bounded at `ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING` so a drifting day cannot flatten its own baseline.",
        "The threshold is `latest > 2 * trailing_avg`, applied before rounding so a value sitting near the boundary is judged on its real magnitude.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT table_name, snapshot_date, null_user_id_rate,
         AVG(null_user_id_rate) OVER (
           PARTITION BY table_name ORDER BY snapshot_date
           ROWS BETWEEN 7 PRECEDING AND 1 PRECEDING
         ) AS trailing_avg,
         ROW_NUMBER() OVER (PARTITION BY table_name ORDER BY snapshot_date DESC) AS recency
  FROM table_snapshots
)
SELECT table_name,
       ROUND(null_user_id_rate, 4) AS latest_null_rate,
       ROUND(trailing_avg, 4) AS trailing_avg_null_rate,
       ROUND(null_user_id_rate / trailing_avg, 2) AS rate_ratio
FROM ranked
WHERE recency = 1
  AND null_user_id_rate > 2 * trailing_avg
ORDER BY rate_ratio DESC;`,
      singleFile: {
        seedSql: TABLE_SNAPSHOTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["table_name", "latest_null_rate", "trailing_avg_null_rate", "rate_ratio"],
          rows: [
            ["fct_orders", 0.058, 0.0113, 5.14],
            ["stg_clickstream", 0.096, 0.0403, 2.38],
          ],
        },
      },
    },
  ],
}

// ---------------------------------------------------------------------------
// Lesson 10.3.3 seeds — the composite capstone. Two catalog snapshots one day apart, the lineage
// graph as an edges table, and a run log in which literally every row says 'success'.
//
// The refunds branch is FOUR hops upstream of revenue_dashboard on purpose
// (raw_refunds -> stg_refunds -> agg_refunds_daily -> fct_revenue -> revenue_dashboard) and the
// zero-row run sits at its deepest node. A fixed-depth self-join of `lineage_edges`, at any depth a
// learner would try before reaching for recursion, returns nothing, so the practice cannot be
// graded green without actually walking the graph. `raw_chargebacks` is the second input to
// `stg_refunds`, which is what keeps the emptiness from cascading: stg_refunds still wrote 210 rows
// (chargebacks only), so `raw_refunds` is the single green-and-empty node in the chain and the
// answer stays one row.
//
// Three planted decoys make the graded predicates load-bearing:
//  - `settlement_id` and `refund_usd` are ADDED on 2026-03-02, so a drift query that only diffs
//    column presence in one direction reports them as changes.
//  - `raw_orders` wrote 0 rows on 2026-03-01 but 97,200 on 2026-03-02, so a triage query that
//    forgets "latest run" finds a table that is already fixed.
//  - `stg_clicks` and `marketing_dashboard` wrote 0 rows on the latest run and are green, but they
//    are on a branch that never reaches revenue_dashboard, so a query that skips lineage entirely
//    returns three tables instead of one.
// ---------------------------------------------------------------------------

const COLUMN_CATALOG_SEED = `CREATE TABLE column_catalog (
  snapshot_date TEXT,   -- the day the catalog was captured
  table_name    TEXT,
  column_name   TEXT,
  data_type     TEXT
);
INSERT INTO column_catalog (snapshot_date, table_name, column_name, data_type) VALUES
  ('2026-03-01', 'raw_payments',      'payment_id',     'INTEGER'),
  ('2026-03-01', 'raw_payments',      'order_id',       'INTEGER'),
  ('2026-03-01', 'raw_payments',      'amount_usd',     'REAL'),
  ('2026-03-01', 'raw_payments',      'payment_method', 'TEXT'),
  ('2026-03-01', 'raw_payments',      'paid_at',        'TEXT'),
  ('2026-03-01', 'stg_payments',      'payment_id',     'INTEGER'),
  ('2026-03-01', 'stg_payments',      'order_id',       'INTEGER'),
  ('2026-03-01', 'stg_payments',      'amount_usd',     'REAL'),
  ('2026-03-01', 'stg_payments',      'paid_at',        'TEXT'),
  ('2026-03-01', 'stg_orders',        'order_id',       'INTEGER'),
  ('2026-03-01', 'stg_orders',        'customer_id',    'INTEGER'),
  ('2026-03-01', 'stg_orders',        'promo_code',     'TEXT'),
  ('2026-03-01', 'stg_orders',        'order_date',     'TEXT'),
  ('2026-03-01', 'fct_revenue',       'revenue_date',   'TEXT'),
  ('2026-03-01', 'fct_revenue',       'amount_usd',     'REAL'),
  ('2026-03-01', 'fct_revenue',       'order_count',    'INTEGER'),
  ('2026-03-01', 'revenue_dashboard', 'revenue_date',   'TEXT'),
  ('2026-03-01', 'revenue_dashboard', 'amount_usd',     'REAL'),
  ('2026-03-02', 'raw_payments',      'payment_id',     'INTEGER'),
  ('2026-03-02', 'raw_payments',      'order_id',       'INTEGER'),
  ('2026-03-02', 'raw_payments',      'amount_usd',     'REAL'),
  ('2026-03-02', 'raw_payments',      'paid_at',        'TEXT'),
  ('2026-03-02', 'raw_payments',      'settlement_id',  'TEXT'),
  ('2026-03-02', 'stg_payments',      'payment_id',     'INTEGER'),
  ('2026-03-02', 'stg_payments',      'order_id',       'INTEGER'),
  ('2026-03-02', 'stg_payments',      'amount_usd',     'REAL'),
  ('2026-03-02', 'stg_payments',      'paid_at',        'INTEGER'),
  ('2026-03-02', 'stg_orders',        'order_id',       'INTEGER'),
  ('2026-03-02', 'stg_orders',        'customer_id',    'INTEGER'),
  ('2026-03-02', 'stg_orders',        'order_date',     'TEXT'),
  ('2026-03-02', 'fct_revenue',       'revenue_date',   'TEXT'),
  ('2026-03-02', 'fct_revenue',       'amount_usd',     'TEXT'),
  ('2026-03-02', 'fct_revenue',       'order_count',    'INTEGER'),
  ('2026-03-02', 'fct_revenue',       'refund_usd',     'REAL'),
  ('2026-03-02', 'revenue_dashboard', 'revenue_date',   'TEXT'),
  ('2026-03-02', 'revenue_dashboard', 'amount_usd',     'REAL');`

const LINEAGE_EDGES_SEED = `CREATE TABLE lineage_edges (
  upstream_table   TEXT,
  downstream_table TEXT   -- one row per "downstream_table is built from upstream_table"
);
INSERT INTO lineage_edges (upstream_table, downstream_table) VALUES
  ('raw_payments',      'stg_payments'),
  ('raw_refunds',       'stg_refunds'),
  ('raw_chargebacks',   'stg_refunds'),
  ('raw_orders',        'stg_orders'),
  ('stg_payments',      'fct_revenue'),
  ('stg_refunds',       'agg_refunds_daily'),
  ('agg_refunds_daily', 'fct_revenue'),
  ('stg_orders',        'fct_revenue'),
  ('fct_revenue',       'revenue_dashboard'),
  ('fct_revenue',       'finance_extract'),
  ('raw_clicks',        'stg_clicks'),
  ('stg_clicks',        'marketing_dashboard');`

const PIPELINE_RUNS_SEED = `CREATE TABLE pipeline_runs (
  run_id       TEXT,
  table_name   TEXT,
  run_date     TEXT,
  status       TEXT,     -- every row here is 'success', which is the whole problem
  rows_written INTEGER,
  finished_at  TEXT
);
INSERT INTO pipeline_runs (run_id, table_name, run_date, status, rows_written, finished_at) VALUES
  ('r1001', 'raw_payments',       '2026-03-01', 'success', 128400, '2026-03-01 02:12:00'),
  ('r1002', 'stg_payments',       '2026-03-01', 'success', 128400, '2026-03-01 02:40:00'),
  ('r1003', 'raw_refunds',        '2026-03-01', 'success',   4120, '2026-03-01 02:15:00'),
  ('r1004', 'raw_chargebacks',    '2026-03-01', 'success',    260, '2026-03-01 02:16:00'),
  ('r1005', 'stg_refunds',        '2026-03-01', 'success',   4380, '2026-03-01 02:44:00'),
  ('r1006', 'agg_refunds_daily',  '2026-03-01', 'success',     90, '2026-03-01 02:58:00'),
  ('r1007', 'raw_orders',         '2026-03-01', 'success',      0, '2026-03-01 02:18:00'),
  ('r1008', 'stg_orders',         '2026-03-01', 'success',  96500, '2026-03-01 02:47:00'),
  ('r1009', 'fct_revenue',        '2026-03-01', 'success',   3100, '2026-03-01 03:05:00'),
  ('r1010', 'revenue_dashboard',  '2026-03-01', 'success',   3100, '2026-03-01 03:20:00'),
  ('r1011', 'raw_clicks',         '2026-03-01', 'success', 501000, '2026-03-01 02:22:00'),
  ('r1012', 'stg_clicks',         '2026-03-01', 'success', 498300, '2026-03-01 02:51:00'),
  ('r1013', 'finance_extract',    '2026-03-01', 'success',   3100, '2026-03-01 03:35:00'),
  ('r1014', 'marketing_dashboard','2026-03-01', 'success', 498300, '2026-03-01 03:40:00'),
  ('r1101', 'raw_payments',       '2026-03-02', 'success', 131900, '2026-03-02 02:11:00'),
  ('r1102', 'stg_payments',       '2026-03-02', 'success', 131900, '2026-03-02 02:39:00'),
  ('r1103', 'raw_refunds',        '2026-03-02', 'success',      0, '2026-03-02 02:14:00'),
  ('r1104', 'raw_chargebacks',    '2026-03-02', 'success',    210, '2026-03-02 02:16:00'),
  ('r1105', 'stg_refunds',        '2026-03-02', 'success',    210, '2026-03-02 02:43:00'),
  ('r1106', 'agg_refunds_daily',  '2026-03-02', 'success',     30, '2026-03-02 02:57:00'),
  ('r1107', 'raw_orders',         '2026-03-02', 'success',  97200, '2026-03-02 02:17:00'),
  ('r1108', 'stg_orders',         '2026-03-02', 'success',  97800, '2026-03-02 02:46:00'),
  ('r1109', 'fct_revenue',        '2026-03-02', 'success',   2870, '2026-03-02 03:04:00'),
  ('r1110', 'revenue_dashboard',  '2026-03-02', 'success',   2870, '2026-03-02 03:19:00'),
  ('r1111', 'raw_clicks',         '2026-03-02', 'success', 512400, '2026-03-02 02:21:00'),
  ('r1112', 'stg_clicks',         '2026-03-02', 'success',      0, '2026-03-02 02:50:00'),
  ('r1113', 'finance_extract',    '2026-03-02', 'success',   2870, '2026-03-02 03:34:00'),
  ('r1114', 'marketing_dashboard','2026-03-02', 'success',      0, '2026-03-02 03:39:00');`

const TRIAGE_SEED = `${COLUMN_CATALOG_SEED}

${LINEAGE_EDGES_SEED}

${PIPELINE_RUNS_SEED}`

// ---------------------------------------------------------------------------
// Lesson 10.3.3 — Schema Drift, Lineage, and the Incident Walk
// ---------------------------------------------------------------------------

const schemaDriftLineageTriage: SqlLesson = {
  id: "de-l10-schema-drift-lineage-triage",
  title: "Schema Drift, Lineage, and the Incident Walk",
  summary:
    "Detect breaking schema drift by diffing two catalog snapshots, then triage a silent-success incident by walking lineage upstream with a recursive CTE until you find the run that succeeded and wrote nothing.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "schema drift detection",
    "breaking vs additive changes",
    "lineage graphs",
    "recursive CTEs",
    "silent success failure",
    "incident triage method",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Schema drift is a diff between two catalog snapshots

The schema pillar has no clever machinery behind it. Capture the column catalog every day, and drift is the difference between yesterday's snapshot and today's. Every warehouse can give you this catalog, and once it is a table, the monitor is a self-join.

What matters is that the three kinds of change are not equally dangerous:

- **Added columns are usually safe.** Nothing downstream selects a column that did not exist, so an addition is additive and consumers keep working. This is the same logic as the backward-compatible schema rules from the streaming level: add fields with defaults and old readers are fine.
- **Dropped columns break consumers.** Every query naming that column now errors, and you will not find out from the pipeline that dropped it. You find out from the dashboard.
- **Type changes break consumers quietly.** A \`REAL\` that becomes \`TEXT\` does not error immediately. It errors at the first \`SUM\`, or worse, it sorts \`'9'\` above \`'10'\` and returns a wrong number with no complaint at all.

So the drift monitor reports drops and type changes and stays quiet about additions. That single decision is the difference between a monitor people read and a monitor people mute.

## Lineage is an edges table, and a recursive CTE walks it

The lineage pillar is one narrow table:

\`\`\`sql
lineage_edges(upstream_table, downstream_table)
\`\`\`

One row per "this is built from that". Every question you want to ask is a walk over it. Upstream of a broken table, downstream of a broken table, everything within two hops. In SQL that walk is a recursive CTE: an anchor query that finds the first ring of neighbours, then a recursive part that keeps joining the edges table to what you have found so far.

\`\`\`sql
WITH RECURSIVE upstream(table_name) AS (
  SELECT upstream_table FROM lineage_edges WHERE downstream_table = 'revenue_dashboard'
  UNION
  SELECT e.upstream_table
  FROM lineage_edges e
  JOIN upstream u ON e.downstream_table = u.table_name
)
SELECT * FROM upstream;
\`\`\`

Use \`UNION\`, not \`UNION ALL\`. \`UNION\` deduplicates, which is what stops the walk when a table is reachable by two paths, and in a graph with a cycle it is the difference between a result and an infinite loop.

## The failure mode nobody tests for: green but empty

Here is the incident. At 09:00 someone says the revenue dashboard shows a number that is far too low. You open the orchestrator. Every task is green. Every run says \`success\`. There is no alert, no retry, no failed task, nothing to look at.

\`\`\`csdiagram
{
  "type": "topology",
  "title": "The chain behind revenue_dashboard",
  "layout": "lr",
  "nodes": [
    { "id": "raw_payments", "label": "raw_payments", "kind": "db" },
    { "id": "raw_refunds", "label": "raw_refunds (0 rows, green)", "kind": "db" },
    { "id": "raw_chargebacks", "label": "raw_chargebacks", "kind": "db" },
    { "id": "raw_orders", "label": "raw_orders", "kind": "db" },
    { "id": "stg_payments", "label": "stg_payments", "kind": "db" },
    { "id": "stg_refunds", "label": "stg_refunds", "kind": "db" },
    { "id": "stg_orders", "label": "stg_orders", "kind": "db" },
    { "id": "agg_refunds_daily", "label": "agg_refunds_daily", "kind": "db" },
    { "id": "fct_revenue", "label": "fct_revenue", "kind": "service" },
    { "id": "revenue_dashboard", "label": "revenue_dashboard", "kind": "external" }
  ],
  "edges": [
    { "from": "raw_payments", "to": "stg_payments" },
    { "from": "raw_refunds", "to": "stg_refunds" },
    { "from": "raw_chargebacks", "to": "stg_refunds" },
    { "from": "raw_orders", "to": "stg_orders" },
    { "from": "stg_payments", "to": "fct_revenue" },
    { "from": "stg_refunds", "to": "agg_refunds_daily" },
    { "from": "agg_refunds_daily", "to": "fct_revenue" },
    { "from": "stg_orders", "to": "fct_revenue" },
    { "from": "fct_revenue", "to": "revenue_dashboard" }
  ],
  "stages": [
    { "adds": ["raw_payments", "raw_refunds", "raw_chargebacks", "raw_orders"], "note": "The raw landing tables. All four ran, all four are green, and one of them pulled nothing at all." },
    { "adds": ["stg_payments", "stg_refunds", "stg_orders"], "note": "The staging layer. stg_refunds unions refunds with chargebacks, so it still wrote rows and still looks alive even though half its input never arrived." },
    { "adds": ["agg_refunds_daily"], "note": "The daily refund rollup. It wrote 30 rows instead of 90, which is a volume anomaly rather than an empty table, so the status column has nothing to say here either." },
    { "adds": ["fct_revenue", "revenue_dashboard"], "note": "The fact joins the rollup, so missing refund days drop out of the total and the dashboard is where a human finally notices." }
  ],
  "caption": "Walking upstream from the complaint. The break is four hops up, which is why the walk is a query rather than a glance at a diagram."
}
\`\`\`

A run status answers "did the code finish without throwing". It does not answer "did the code do anything". A job that reads an empty source, transforms nothing, and writes zero rows completes perfectly. This is the most-missed production failure, and it is missed because every monitoring dashboard is built on the status column.

**This is not the same zero-row success Level 9 counted.** \`de-l9-freshness-slas\` already names silent success and grades a \`silent_success_runs\` column, but it counts them one pipeline at a time, in a report you open when you already know which pipeline you are worried about. Here you do not know. The complaint is a number on a dashboard, every table in the log is green, and three separate tables wrote zero rows on their latest run. Lineage is the half that is new: it is what narrows a list of anomalies to the one node that can explain this number, and it is what tells you the other two sit on a pipeline the revenue dashboard never reads.

## The triage method

The method is short enough to say in an interview:

1. **Start from the complaint.** The broken asset is \`revenue_dashboard\`, so that is the root of the walk.
2. **Walk lineage upstream.** Collect every table the broken asset depends on, at any depth. Do not guess which one it is, and do not guess how far up it is either: a two-hop or three-hop join is an assumption about the shape of a graph you have not read, and real chains are longer than the sketch you drew from memory.
3. **For each node check three things, not one.** The latest run's \`status\`, its \`rows_written\`, and its freshness. Status alone is what let this incident happen.
4. **The break is the deepest node that is green and empty.** Anything below it is fine, anything above it is a victim.
5. **Then check the schema pillar**, because a dropped or retyped upstream column is a common cause of a filter that suddenly matches nothing.

**Common mistake:** scanning the whole run log for zero-row successes instead of walking lineage first. In this seed that returns three tables, two of which belong to a completely different pipeline that nothing on the revenue dashboard reads. Lineage is what turns a list of anomalies into one root cause, and it is exactly the step Level 9's per-pipeline report never had to take.

**Interview nuance:** "the pipeline is green but the dashboard is empty, walk me through it" is a standard scenario, and there are two graded moments in it. The first is saying out loud that a success status does not mean rows were written, which is the insight most candidates miss. The second is triaging by lineage rather than by guessing, because that is what makes the method work on a pipeline you have never seen. Naming rows_written, freshness, and schema drift as the three things you check at each node is the answer.

> **On a real platform this differs.** dbt, Airflow's asset graph, OpenLineage, and the warehouse catalogs all maintain the edges table for you, so you query lineage rather than record it: dbt's \`ref()\` calls build it at compile time, and \`dbt run --select fct_revenue+\` selects the same downstream set the recursive CTE computes here. Column-level lineage tools take this one step further and tell you which downstream COLUMNS a dropped column breaks, which is the version that makes the blast-radius drill exact rather than conservative. The failure itself is unchanged: every one of those platforms will show you a green run that wrote nothing.`,
    demoSeedSql: TRIAGE_SEED,
    demoCode: `-- The triage walk, live. Every status says success. One node is lying by omission.
WITH RECURSIVE upstream(table_name, depth) AS (
  SELECT upstream_table, 1 FROM lineage_edges WHERE downstream_table = 'revenue_dashboard'
  UNION
  SELECT e.upstream_table, u.depth + 1
  FROM lineage_edges e
  JOIN upstream u ON e.downstream_table = u.table_name
)
SELECT u.table_name,
       u.depth AS hops_upstream,
       r.run_date,
       r.status,
       r.rows_written,
       CASE WHEN r.status = 'success' AND r.rows_written = 0
            THEN 'GREEN BUT EMPTY' ELSE 'ok' END AS triage_flag
FROM upstream u
JOIN pipeline_runs r ON r.table_name = u.table_name
WHERE r.run_date = (SELECT MAX(r2.run_date) FROM pipeline_runs r2 WHERE r2.table_name = u.table_name)
ORDER BY u.depth, u.table_name;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-schema-drift-lineage-triage-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every breaking schema change between the \`'2026-03-01'\` and \`'2026-03-02'\` snapshots, as \`(table_name, column_name, change)\`, ordered by table name then column name, over \`column_catalog(snapshot_date, table_name, column_name, data_type)\`.

\`change\` is \`'dropped'\` when a column present on 2026-03-01 is gone on 2026-03-02, and \`'type_changed'\` when it is still there under a different \`data_type\`. Columns that only appear in the newer snapshot are additive and must not be reported. Alias the computed column exactly \`change\`.`,
    starterCode: `-- Schema drift is a diff of the catalog with itself, one snapshot against the other.
SELECT
  -- one row per breaking change, additions excluded
FROM column_catalog a;`,
    hints: [
      "Join the catalog to itself: alias `a` for the 2026-03-01 rows and LEFT JOIN alias `b` for the 2026-03-02 rows on `table_name` and `column_name`.",
      "Put the snapshot filter for `b` in the JOIN condition, not in the WHERE clause. A LEFT JOIN filtered in WHERE turns back into an inner join and the dropped columns disappear.",
      "A NULL `b.column_name` means dropped, and a non-NULL one with a different `data_type` means type_changed, which is one CASE expression.",
      "Driving the query from the older snapshot is what excludes the added columns for free, because they have no 2026-03-01 row to be found by.",
    ],
    referenceSolution: `SELECT a.table_name,
       a.column_name,
       CASE WHEN b.column_name IS NULL THEN 'dropped' ELSE 'type_changed' END AS change
FROM column_catalog a
LEFT JOIN column_catalog b
  ON b.snapshot_date = '2026-03-02'
 AND b.table_name = a.table_name
 AND b.column_name = a.column_name
WHERE a.snapshot_date = '2026-03-01'
  AND (b.column_name IS NULL OR b.data_type <> a.data_type)
ORDER BY a.table_name, a.column_name;`,
    singleFile: {
      seedSql: TRIAGE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "column_name", "change"],
        rows: [
          ["fct_revenue", "amount_usd", "type_changed"],
          ["raw_payments", "payment_method", "dropped"],
          ["stg_orders", "promo_code", "dropped"],
          ["stg_payments", "paid_at", "type_changed"],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-schema-drift-lineage-triage-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the upstream table that broke \`revenue_dashboard\`, as \`(table_name, run_date, rows_written)\`, over \`lineage_edges(upstream_table, downstream_table)\` and \`pipeline_runs(run_id, table_name, run_date, status, rows_written, finished_at)\`.

The dashboard is empty this morning and every run in the log reports \`'success'\`. The table you are looking for is the one in \`revenue_dashboard\`'s upstream chain, at any depth, whose most recent run succeeded and wrote zero rows. Alias every column exactly.`,
    starterCode: `-- Every run is green. The dashboard is empty. Find the node that is both.
`,
    hints: [
      "There are three conditions and all three are load-bearing: the table must be upstream of revenue_dashboard, it must be its LATEST run you look at, and that run must be a success with zero rows written. Upstream means at any depth, and this chain is longer than the first branch you look at, so walk it recursively rather than joining `lineage_edges` to itself a fixed number of times.",
    ],
    singleFile: {
      seedSql: TRIAGE_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["table_name", "run_date", "rows_written"],
        rows: [["raw_refunds", "2026-03-02", 0]],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-schema-drift-lineage-triage-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the direct upstream tables of \`fct_revenue\`, as \`(upstream_table)\`, alphabetically, over \`lineage_edges\`.

Direct means one hop only, so no recursion is needed here.`,
      starterCode: `-- The first ring of the lineage walk, which is also the anchor of any recursive version.
SELECT
FROM lineage_edges;`,
      hints: [
        "One hop upstream is a plain filter on `downstream_table`.",
        "This exact query is the anchor member a recursive CTE starts from.",
      ],
      referenceSolution: `SELECT upstream_table
FROM lineage_edges
WHERE downstream_table = 'fct_revenue'
ORDER BY upstream_table;`,
      singleFile: {
        seedSql: TRIAGE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["upstream_table"],
          rows: [["agg_refunds_daily"], ["stg_orders"], ["stg_payments"]],
        },
      },
    },
    {
      id: "de-l10-schema-drift-lineage-triage-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns each breaking schema change together with how many tables sit downstream of it, as \`(table_name, column_name, change, downstream_tables)\`, biggest blast radius first, over \`column_catalog\` and \`lineage_edges\`.

Reuse the drift definition from the Apply exercise (dropped and type-changed columns between the \`'2026-03-01'\` and \`'2026-03-02'\` snapshots). \`downstream_tables\` counts every distinct table reachable downstream at any depth, not just the direct children. Break ties by table name then column name, and alias every column exactly.`,
      starterCode: `-- "One column changed" is not a severity. "One column changed and four tables read it" is.
SELECT
FROM column_catalog;`,
      hints: [
        "Two CTEs: one holding the breaking changes, one recursive CTE that carries `(root_table, table_name)` so every descendant remembers which change it belongs to.",
        "The recursive member joins `lineage_edges` to the descendants found so far on `e.upstream_table = d.table_name`, and `UNION` keeps a table reachable by two paths from being counted twice.",
        "SQLite wants `WITH RECURSIVE` at the top even when the first CTE in the list is not the recursive one.",
      ],
      referenceSolution: `WITH RECURSIVE breaking AS (
  SELECT a.table_name,
         a.column_name,
         CASE WHEN b.column_name IS NULL THEN 'dropped' ELSE 'type_changed' END AS change
  FROM column_catalog a
  LEFT JOIN column_catalog b
    ON b.snapshot_date = '2026-03-02'
   AND b.table_name = a.table_name
   AND b.column_name = a.column_name
  WHERE a.snapshot_date = '2026-03-01'
    AND (b.column_name IS NULL OR b.data_type <> a.data_type)
),
descendants(root_table, table_name) AS (
  SELECT b.table_name, e.downstream_table
  FROM breaking b
  JOIN lineage_edges e ON e.upstream_table = b.table_name
  UNION
  SELECT d.root_table, e.downstream_table
  FROM descendants d
  JOIN lineage_edges e ON e.upstream_table = d.table_name
)
SELECT b.table_name,
       b.column_name,
       b.change,
       (SELECT COUNT(*) FROM descendants d WHERE d.root_table = b.table_name) AS downstream_tables
FROM breaking b
ORDER BY downstream_tables DESC, b.table_name, b.column_name;`,
      singleFile: {
        seedSql: TRIAGE_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["table_name", "column_name", "change", "downstream_tables"],
          rows: [
            ["raw_payments", "payment_method", "dropped", 4],
            ["stg_orders", "promo_code", "dropped", 3],
            ["stg_payments", "paid_at", "type_changed", 3],
            ["fct_revenue", "amount_usd", "type_changed", 2],
          ],
        },
      },
    },
  ],
}

export const level10Module3: SqlModule = {
  id: "de-l10-quality-observability",
  title: "Module 10.3: Data Quality & Observability",
  description:
    "Where quality results go and how production watches them: the append-only check_results ledger with warn-versus-error severity and a run verdict derived from severity rather than from a failure count, the five observability pillars implemented as always-on monitors over catalog metadata, and the composite incident walk that diffs schema snapshots and follows lineage upstream to the run that succeeded while writing zero rows.",
  lessons: [checkSuites, observabilityPillars, schemaDriftLineageTriage],
}
