/**
 * Data Engineering curriculum Level 10, Module 10.1 — Spark's Execution Model.
 *
 * The vocabulary every Spark conversation presupposes, taught the way a junior loop actually
 * probes it: the driver/executor split and the OOM fork that follows from it, lazy evaluation
 * and the transformation-versus-action line, and the full job to stage to task decomposition of
 * a run the learner has never seen.
 *
 * Device: the Level 6 device, unchanged. Nothing here starts a JVM. Every lesson teaches the
 * concept in `teach`, then grades ordinary SQL over a simulated copy of the Spark UI, which is
 * metadata a real cluster already exposes: `spark_executors` and `spark_tasks` are the Executors
 * and Tasks tabs, `query_plan_ops` is the printed output of `.explain()`, `notebook_commands`
 * plus `spark_jobs` are a notebook's command history sitting next to the Jobs tab, and
 * `spark_stages` is the Stages tab. RESEARCH.md §5.8 is the grounding: Spark is in 38.7-41.1% of
 * DE postings but juniors are tested on conceptual literacy plus metric-based diagnosis, never
 * live cluster coding, and Databricks' own Spark UI Simulator (30+ pre-recorded experiments, no
 * cluster) proves this exact cluster-free pedagogy.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed. Content
 * rules: no em dashes in learner prose; every prompt leads with the deliverable;
 * `referenceSolution` ships on apply and drills, never on practice.
 *
 * Six deliberate deviations from CURRICULUM-MAP.md:
 *  - 10.1.3's demo is the map's three-table rollup (tasks up to stages up to jobs) but reported at
 *    stage grain rather than one row per job. At job grain the demo would be the apply's answer
 *    sitting above the apply. Stage grain still shows the only route from a task row to its job,
 *    and it shows the write side and the read side of one shuffle reconciling, which is the
 *    section the demo sits under.
 *  - 10.1.1's `spark_executors` carries a `driver` row. The real Executors tab lists the driver
 *    beside the executors, and its zero tasks are the fastest proof of the lesson's own claim
 *    that the driver runs no work. Every graded prompt therefore says which rows to keep, so the
 *    row teaches rather than traps.
 *  - 10.1.1's `exec-3` has 2 cores rather than the uniform 4 the other executors get. With a
 *    uniform 4 the tasks-per-core drill tied `exec-3` against `exec-4` at exactly 1.0 and the
 *    ordering stopped being determined by the graded quantity.
 *  - 10.1.2 seeds a fourth plan and one `spark.read.option("inferSchema", "true").csv(...)`
 *    command that DOES submit a job. Without it, `WHERE command_type = 'transformation'`
 *    reproduced the practice expected set exactly, so the anti-join the lesson exists to teach
 *    was not actually load-bearing. The gotcha is also real: schema inference on CSV and JSON
 *    scans the file, which is why a read can appear in the Jobs tab before any action runs.
 *  - 10.1.3 seeds a THIRD job the map does not list. The map's own hard drill is a missing-
 *    producer sanity check, and a stage whose shuffle read has no upstream producer cannot exist
 *    inside a single coherent run. Job 2 is a truncated event-log capture (the stage that wrote
 *    the shuffle is missing from the log), which is what that anomaly looks like in production.
 *  - `spark_tasks` appears in 10.1.1 and 10.1.3 with different columns. Each lesson is a separate
 *    simulated UI capture and each keeps only the columns its own tab shows: the Executors-tab
 *    capture carries memory and failure columns, the Stages-tab capture carries records and
 *    shuffle bytes. The seed constants are separate, so the two never meet in one database.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 10.1.1 seeds — the Executors and Tasks tabs of one EMR run.
//
// Five executors plus the driver. `exec-4` is the over-packed one: 8 cores sharing the same 8 GB
// heap every other executor gives to 4, which is the textbook executor-OOM setup and the reason
// its three OutOfMemoryError failures are not a coincidence. `exec-5` died outright, so all three
// of its tasks failed on OOM and it carries the highest peak memory in the run. FetchFailedException
// is the control: a shuffle-fetch failure and NOT a memory problem. `exec-2` fails twice on it and
// `exec-4` once, which is what keeps the OOM share in the practice load-bearing, because a solution
// that counts every failure as an OOM gets both of those executors wrong. Every failure class the
// seed uses is one the teach explains, so nothing is graded on an unexplained exception name.
// ---------------------------------------------------------------------------

const SPARK_EXECUTORS_SEED = `CREATE TABLE spark_executors (
  executor_id TEXT,
  host        TEXT,
  cores       INTEGER,  -- task slots: one task occupies one core for its whole duration
  memory_mb   INTEGER,  -- heap for the WHOLE process, shared by every core on it
  status      TEXT      -- ACTIVE | LOST (LOST = the JVM died and the cluster manager noticed)
);
INSERT INTO spark_executors (executor_id, host, cores, memory_mb, status) VALUES
  ('driver', 'ip-10-0-4-10', 2, 4096, 'ACTIVE'),
  ('exec-1', 'ip-10-0-4-21', 4, 8192, 'ACTIVE'),
  ('exec-2', 'ip-10-0-4-22', 4, 8192, 'ACTIVE'),
  ('exec-3', 'ip-10-0-4-23', 2, 8192, 'ACTIVE'),
  ('exec-4', 'ip-10-0-4-24', 8, 8192, 'ACTIVE'),
  ('exec-5', 'ip-10-0-4-25', 4, 8192, 'LOST');`

const SPARK_TASKS_SEED = `CREATE TABLE spark_tasks (
  task_id        TEXT,
  stage_id       INTEGER,
  executor_id    TEXT,
  duration_ms    INTEGER,
  peak_memory_mb INTEGER,  -- the most heap this one task held at once
  status         TEXT,     -- SUCCESS | FAILED
  error          TEXT      -- the exception class when it failed; NULL when it succeeded
);
INSERT INTO spark_tasks (task_id, stage_id, executor_id, duration_ms, peak_memory_mb, status, error) VALUES
  ('t-001', 0, 'exec-1',   4200, 1800, 'SUCCESS', NULL),
  ('t-002', 0, 'exec-1',   4600, 1900, 'SUCCESS', NULL),
  ('t-003', 0, 'exec-1',   4100, 1750, 'SUCCESS', NULL),
  ('t-004', 1, 'exec-1',   9100, 3100, 'SUCCESS', NULL),
  ('t-005', 1, 'exec-1',   8800, 3050, 'SUCCESS', NULL),
  ('t-006', 1, 'exec-1',   9400, 3200, 'SUCCESS', NULL),
  ('t-007', 0, 'exec-2',   4300, 1820, 'SUCCESS', NULL),
  ('t-008', 0, 'exec-2',   4500, 1860, 'SUCCESS', NULL),
  ('t-009', 1, 'exec-2',   9000, 3080, 'SUCCESS', NULL),
  ('t-010', 1, 'exec-2',  15200, 3400, 'FAILED',  'FetchFailedException'),
  ('t-011', 1, 'exec-2',  15800, 3450, 'FAILED',  'FetchFailedException'),
  ('t-012', 0, 'exec-3',   4400, 1840, 'SUCCESS', NULL),
  ('t-013', 0, 'exec-3',   4250, 1790, 'SUCCESS', NULL),
  ('t-014', 1, 'exec-3',   8900, 3020, 'SUCCESS', NULL),
  ('t-015', 1, 'exec-3',   9200, 3150, 'SUCCESS', NULL),
  ('t-016', 0, 'exec-4',   5100, 2100, 'SUCCESS', NULL),
  ('t-017', 0, 'exec-4',   5300, 2200, 'SUCCESS', NULL),
  ('t-018', 0, 'exec-4',   5000, 2050, 'SUCCESS', NULL),
  ('t-019', 1, 'exec-4',  12400, 7800, 'SUCCESS', NULL),
  ('t-020', 1, 'exec-4',  18600, 7950, 'FAILED',  'OutOfMemoryError'),
  ('t-021', 1, 'exec-4',  19100, 7900, 'FAILED',  'OutOfMemoryError'),
  ('t-022', 1, 'exec-4',  17800, 7880, 'FAILED',  'OutOfMemoryError'),
  ('t-023', 1, 'exec-4',  16200, 5400, 'FAILED',  'FetchFailedException'),
  ('t-024', 1, 'exec-5',  21000, 8140, 'FAILED',  'OutOfMemoryError'),
  ('t-025', 1, 'exec-5',  20400, 8100, 'FAILED',  'OutOfMemoryError'),
  ('t-026', 1, 'exec-5',  19800, 8050, 'FAILED',  'OutOfMemoryError');`

const EXECUTORS_AND_TASKS_SEED = SPARK_EXECUTORS_SEED + "\n" + SPARK_TASKS_SEED

// ---------------------------------------------------------------------------
// Lesson 10.1.2 seeds — one `.explain()` capture per query, plus a notebook's command history
// next to the Jobs tab.
//
// Four plans with deliberately different shuffle counts: `plan_lookup_filter` has none at all
// (a scan, a filter, a project, one stage), `plan_daily_active` and `plan_dedupe` have one each,
// and `plan_order_join` has three (two sides of a sort-merge join, then the group-by). The
// zero-Exchange plan is what forces the graded arithmetic to be exchanges + 1 rather than a plain
// count of stage-boundary rows.
//
// The notebook log's load-bearing row is command 8. It is classified as a transformation, but
// CSV schema inference scans the file, so it submitted a job of its own. Without it,
// `command_type = 'transformation'` reproduced the practice expected set and the anti-join the
// lesson teaches was decoration.
// ---------------------------------------------------------------------------

const QUERY_PLAN_OPS_SEED = `CREATE TABLE query_plan_ops (
  plan_id  TEXT,
  step     INTEGER,  -- execution order: the printed plan read from the bottom up, so step 1 is the
                    -- scan, which .explain() prints LAST
  operator TEXT,     -- the physical operator Spark chose
  detail   TEXT      -- the operator's arguments, trimmed to what fits
);
INSERT INTO query_plan_ops (plan_id, step, operator, detail) VALUES
  ('plan_daily_active',  1, 'Scan parquet',   'events[user_id,event_ts,country] PushedFilters: [IsNotNull(user_id)]'),
  ('plan_daily_active',  2, 'Filter',         'isnotnull(user_id)'),
  ('plan_daily_active',  3, 'Project',        '[user_id, country]'),
  ('plan_daily_active',  4, 'HashAggregate',  'keys=[country], functions=[partial_count(user_id)]'),
  ('plan_daily_active',  5, 'Exchange',       'hashpartitioning(country, 200)'),
  ('plan_daily_active',  6, 'HashAggregate',  'keys=[country], functions=[count(user_id)]'),
  ('plan_dedupe',        1, 'Scan parquet',   'sessions[session_id,user_id,started_at]'),
  ('plan_dedupe',        2, 'HashAggregate',  'keys=[session_id], functions=[]'),
  ('plan_dedupe',        3, 'Exchange',       'hashpartitioning(session_id, 200)'),
  ('plan_dedupe',        4, 'HashAggregate',  'keys=[session_id], functions=[]'),
  ('plan_lookup_filter', 1, 'Scan parquet',   'products[product_id,name,price] PushedFilters: [GreaterThan(price,100)]'),
  ('plan_lookup_filter', 2, 'Filter',         'price > 100.0'),
  ('plan_lookup_filter', 3, 'Project',        '[product_id, name]'),
  ('plan_order_join',    1, 'Scan parquet',   'orders[order_id,user_id,amount]'),
  ('plan_order_join',    2, 'Scan parquet',   'users[user_id,segment]'),
  ('plan_order_join',    3, 'Exchange',       'hashpartitioning(user_id, 200)'),
  ('plan_order_join',    4, 'Exchange',       'hashpartitioning(user_id, 200)'),
  ('plan_order_join',    5, 'SortMergeJoin',  '[user_id], [user_id], Inner'),
  ('plan_order_join',    6, 'HashAggregate',  'keys=[segment], functions=[partial_sum(amount)]'),
  ('plan_order_join',    7, 'Exchange',       'hashpartitioning(segment, 200)'),
  ('plan_order_join',    8, 'HashAggregate',  'keys=[segment], functions=[sum(amount)]');`

const NOTEBOOK_COMMANDS_SEED = `CREATE TABLE notebook_commands (
  command_id   INTEGER,
  code_snippet TEXT,
  command_type TEXT   -- transformation | action, as the DataFrame API classifies the call
);
INSERT INTO notebook_commands (command_id, code_snippet, command_type) VALUES
  (1,  'df = spark.read.parquet("s3://lake/raw/events/")',                        'transformation'),
  (2,  'df2 = df.filter(df.country == "US")',                                     'transformation'),
  (3,  'df3 = df2.select("user_id", "event_ts")',                                 'transformation'),
  (4,  'df3.count()',                                                             'action'),
  (5,  'agg = df3.groupBy("user_id").count()',                                    'transformation'),
  (6,  'agg.show(20)',                                                            'action'),
  (7,  'joined = agg.join(users, "user_id")',                                     'transformation'),
  (8,  'raw = spark.read.option("inferSchema", "true").csv("s3://lake/drops/")',  'transformation'),
  (9,  'joined.write.parquet("s3://lake/curated/joined/")',                        'action'),
  (10, 'cached = joined.cache()',                                                 'transformation'),
  (11, 'joined.collect()',                                                        'action');`

const SPARK_JOBS_LOG_SEED = `CREATE TABLE spark_jobs (
  job_id     INTEGER,
  command_id INTEGER,  -- the notebook command that submitted this job
  action     TEXT,     -- the call the scheduler recorded as the trigger
  duration_s REAL
);
INSERT INTO spark_jobs (job_id, command_id, action, duration_s) VALUES
  (0,  4, 'count',   12.4),
  (1,  6, 'show',     3.1),
  (2,  8, 'read',     6.8),
  (3,  9, 'write',   96.2),
  (4,  9, 'write',   18.5),
  (5, 11, 'collect', 41.7);`

const NOTEBOOK_AND_JOBS_SEED = NOTEBOOK_COMMANDS_SEED + "\n" + SPARK_JOBS_LOG_SEED

// ---------------------------------------------------------------------------
// Lesson 10.1.3 seeds — the Jobs, Stages and Tasks tabs of one EMR run, plus one truncated
// capture.
//
// Jobs 0 and 1 are coherent: every stage's `shuffle_write_mb` is exactly the sum of its tasks'
// shuffle writes, and stage 4 reads back exactly what stages 2 and 3 wrote (640 + 25 = 665). That
// is what lets the same number be reached from either the stage rollup or the task rollup, so the
// apply has one right answer and not two.
//
// Job 2 is the anomaly the hard drill hunts: its only recorded stage reads 900 MB of shuffle that
// no stage in the job wrote, because the stage that produced it is missing from the event log.
//
// Stage 4 also carries the straggler the rest of this level is built on: five tasks around 22
// seconds and one at 198 seconds, the max-versus-median gap that Module 10.2 turns into a skew
// diagnosis.
// ---------------------------------------------------------------------------

const SPARK_RUN_JOBS_SEED = `CREATE TABLE spark_jobs (
  job_id     INTEGER,
  action     TEXT,     -- the action call that submitted the job
  duration_s INTEGER   -- wall clock for the whole job, always more than its stages add up to
);
INSERT INTO spark_jobs (job_id, action, duration_s) VALUES
  (0, 'count',  25),
  (1, 'write', 265),
  (2, 'write', 130);`

const SPARK_STAGES_SEED = `CREATE TABLE spark_stages (
  stage_id         INTEGER,
  job_id           INTEGER,
  name             TEXT,
  num_tasks        INTEGER,
  shuffle_read_mb  INTEGER,  -- bytes this stage pulled from the previous stage's shuffle files
  shuffle_write_mb INTEGER,  -- bytes this stage wrote for the NEXT stage to read
  duration_s       INTEGER
);
INSERT INTO spark_stages (stage_id, job_id, name, num_tasks, shuffle_read_mb, shuffle_write_mb, duration_s) VALUES
  (0, 0, 'Scan parquet events + partial HashAggregate', 4,   0, 120,  18),
  (1, 0, 'HashAggregate (final)',                       4, 120,   0,   6),
  (2, 1, 'Scan parquet events',                         6,   0, 640,  40),
  (3, 1, 'Scan parquet users',                          2,   0,  25,   8),
  (4, 1, 'SortMergeJoin + write parquet',               6, 665,   0, 210),
  (5, 2, 'HashAggregate (final) + write parquet',       4, 900,   0, 120);`

const SPARK_RUN_TASKS_SEED = `CREATE TABLE spark_tasks (
  task_id          INTEGER,
  stage_id         INTEGER,
  duration_ms      INTEGER,
  input_records    INTEGER,
  shuffle_write_mb INTEGER   -- this one task's share of its stage's shuffle write
);
INSERT INTO spark_tasks (task_id, stage_id, duration_ms, input_records, shuffle_write_mb) VALUES
  ( 1, 0,   4400,  2500000,  30),
  ( 2, 0,   4600,  2510000,  30),
  ( 3, 0,   4300,  2480000,  30),
  ( 4, 0,   4700,  2520000,  30),
  ( 5, 1,   1400,      800,   0),
  ( 6, 1,   1500,      810,   0),
  ( 7, 1,   1550,      795,   0),
  ( 8, 1,   1450,      805,   0),
  ( 9, 2,   6200,  3000000, 105),
  (10, 2,   6400,  3050000, 108),
  (11, 2,   6100,  2980000, 104),
  (12, 2,   6600,  3100000, 112),
  (13, 2,   6300,  3020000, 106),
  (14, 2,   6500,  3060000, 105),
  (15, 3,   1800,   120000,  12),
  (16, 3,   1900,   118000,  13),
  (17, 4,  22000,  4100000,   0),
  (18, 4,  23500,  4150000,   0),
  (19, 4,  21800,  4050000,   0),
  (20, 4,  24100,  4200000,   0),
  (21, 4,  22600,  4120000,   0),
  (22, 4, 198000, 41000000,   0),
  (23, 5,  28000,  5000000,   0),
  (24, 5,  29500,  5100000,   0),
  (25, 5,  27400,  4950000,   0),
  (26, 5,  30100,  5200000,   0);`

const SPARK_RUN_SEED = SPARK_RUN_JOBS_SEED + "\n" + SPARK_STAGES_SEED + "\n" + SPARK_RUN_TASKS_SEED

// ---------------------------------------------------------------------------
// Module 10.1 — Spark's Execution Model
// ---------------------------------------------------------------------------

const driverAndExecutors: SqlLesson = {
  id: "de-l10-driver-and-executors",
  title: "The Driver, the Executors, and One Task per Core",
  summary:
    "Why a Spark out-of-memory error on the driver needs a different fix than one on an executor, and how the metrics tell you which you hit.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "Spark driver vs executors",
    "task scheduling",
    "one partition equals one task",
    "driver vs executor OOM",
    "JOIN",
    "GROUP BY",
    "conditional aggregation",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## One driver, many executors

A Spark application is two kinds of process, and almost every Spark question you will be asked resolves to knowing which one you are talking about.

The **driver** is the single process that runs your \`main()\`. It builds the logical plan, hands it to the optimizer, cuts the physical plan into stages, decides which task goes to which machine, and collects results that you explicitly ask to bring back. There is exactly one driver per application and you cannot scale it out. On EMR or Glue it is one JVM on one machine, and if it dies the whole application dies with it.

The **executors** are the worker processes. Each one is a JVM that holds partitions of your data in its heap, runs the tasks the driver assigns, caches what you tell it to cache, and writes shuffle files for the next stage to read. You scale out by adding executors, and you scale each one up by giving it more cores or more memory.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["the question", "driver (exactly one)", "executor (as many as you buy)"],
  "rows": [
    ["runs what?", "your main(), the optimizer, the scheduler", "the tasks the driver sends it"],
    ["holds what?", "the plan, plus anything you collect() back", "partitions of the data, cached blocks, shuffle files"],
    ["scales how?", "it does not, there is only ever one", "add executors, or cores and memory per executor"],
    ["dies how?", "collect() or toPandas() on a big result set", "too few partitions, or too many cores sharing one heap"],
    ["the knob", "spark.driver.memory", "spark.executor.memory, spark.executor.cores"]
  ],
  "highlightCols": ["driver (exactly one)"],
  "caption": "The split that every Spark answer hangs on. Work happens on executors; decisions and returned results happen on the driver."
}
\`\`\`

## One partition, one task, one core slot

The unit of parallel work is the **task**, and the rule is mechanical: one partition of the data becomes one task, and one task occupies one **core** on one executor for its entire duration. So a cluster with four executors of four cores each has 16 slots and can run 16 tasks at once. A stage with 200 partitions runs 200 tasks through those 16 slots in waves, and the stage is not finished until the last wave is.

That arithmetic is why the two numbers on an executor are not independent. Cores decide how many tasks run on it at once. Memory is the heap those tasks **share**. Doubling the cores on an executor without doubling its memory halves the memory each concurrent task can use, which is not a tuning win, it is a way to convert a working job into a failing one.

## The OOM fork

"My Spark job ran out of memory" is not a diagnosis. There are two completely different failures behind it, and the interviewer is checking whether you know to ask which.

- **Driver OOM.** Something pulled the dataset back to the single driver process. \`collect()\`, \`toPandas()\`, or an unbounded \`take()\` on a large result. The fix is not more driver memory, it is not collecting: write the result to storage, or aggregate first and collect the small answer.
- **Executor OOM.** A single task tried to hold more than its share of one executor's heap. The usual causes are too few partitions (so each one is enormous), too many cores per executor sharing the same heap, or a skewed key that dumps a huge group into one task. The fix is more partitions, fewer cores per executor, or dealing with the skew.

The metrics tell you which. If the driver process died and the last thing in the log was a \`collect()\`, that is the first branch. If individual tasks failed with \`OutOfMemoryError\` while their executor's peak memory sat right up against its ceiling, that is the second, and the Executors tab will usually show that executor marked \`LOST\`.

**Common mistake:** reading a \`FetchFailedException\` as a memory problem. It is a shuffle-fetch failure: a task could not read the shuffle files it needed, usually because the executor that wrote them has since died. It is a symptom of something else, often an executor OOM one stage earlier, so counting every failed task as an OOM overstates the memory story and sends you tuning the wrong knob.

**Interview nuance:** "explain the driver and executor model" and "your job OOMed, what do you check first" are asked at every level, and Databricks asks them of interns. The answer that scores is the fork, not the definitions: name driver OOM as a \`collect()\` problem and executor OOM as a partitioning or cores-per-executor problem, and say which metric you would look at to tell them apart.

> **On a real platform this differs.** Here you query two small tables. In production the same rows come from the Spark UI's Executors and Tasks tabs (served live on port 4040, archived to the history server afterwards, and on EMR reachable through the persistent application UI). On AWS Glue you do not size executors directly: you buy DPUs, where one standard DPU is 4 vCPU and 16 GB billed at 0.44 USD per DPU-hour with a one-minute minimum, and Glue derives the executor layout from that. The reasoning is unchanged, only the knob has a different name.`,
    demoSeedSql: EXECUTORS_AND_TASKS_SEED,
    demoCode: `-- The Executors tab. Note the driver row: it schedules everything and runs nothing.
SELECT e.executor_id,
       e.cores,
       e.status,
       COUNT(t.task_id) AS tasks_run,
       SUM(CASE WHEN t.status = 'FAILED' THEN 1 ELSE 0 END) AS tasks_failed
FROM spark_executors e
LEFT JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.cores, e.status
ORDER BY tasks_run DESC, e.executor_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-driver-and-executors-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every executor that ran at least one task, with its core count, its task count, and its average task duration, as \`(executor_id, cores, task_count, avg_duration_ms)\`, busiest first, over \`spark_executors(executor_id, host, cores, memory_mb, status)\` and \`spark_tasks(task_id, stage_id, executor_id, duration_ms, peak_memory_mb, status, error)\`.

Join the two tables on \`executor_id\`, which drops the \`driver\` row on its own because the driver runs no tasks. Round \`avg_duration_ms\` to 1 decimal, and order by \`task_count\` descending.`,
    starterCode: `-- Load distribution across the executors: how many tasks each ran and how long they took.
SELECT e.executor_id, e.cores
  -- per executor: the number of tasks it ran and their average duration
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id;`,
    hints: [
      "An inner `JOIN` on `executor_id` keeps only executors that actually appear in `spark_tasks`.",
      "`COUNT(*) AS task_count` and `ROUND(AVG(t.duration_ms), 1) AS avg_duration_ms` after grouping.",
      "Group by `e.executor_id, e.cores` so the core count survives the aggregation, then `ORDER BY task_count DESC`.",
    ],
    referenceSolution: `SELECT e.executor_id,
       e.cores,
       COUNT(*) AS task_count,
       ROUND(AVG(t.duration_ms), 1) AS avg_duration_ms
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.cores
ORDER BY task_count DESC;`,
    singleFile: {
      seedSql: EXECUTORS_AND_TASKS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["executor_id", "cores", "task_count", "avg_duration_ms"],
        rows: [
          ["exec-4", 8, 8, 12437.5],
          ["exec-1", 4, 6, 6700],
          ["exec-2", 4, 5, 9760],
          ["exec-3", 2, 4, 6687.5],
          ["exec-5", 4, 3, 20400],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-driver-and-executors-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every executor that failed at least one task, with its failed-task count and the share of those failures caused by an \`OutOfMemoryError\`, as \`(executor_id, failed_tasks, oom_pct)\`, most failures first, over the same \`spark_tasks\` table.

Count only rows whose \`status\` is \`'FAILED'\`. \`oom_pct\` is the percentage of that executor's failures whose \`error\` is exactly \`'OutOfMemoryError'\`, rounded to 1 decimal. Not every failure is a memory failure, so the percentage has to be computed and not assumed. Order by \`failed_tasks\` descending.`,
    starterCode: `-- Failures per executor, and how much of each executor's failure story is memory.
SELECT executor_id
  -- how many tasks failed here, and what share of them were OutOfMemoryError
FROM spark_tasks
WHERE status = 'FAILED';`,
    hints: [
      "Filter to `status = 'FAILED'` first, then `GROUP BY executor_id`.",
      "`COUNT(*)` is the failure count; a conditional sum `SUM(CASE WHEN error = 'OutOfMemoryError' THEN 1 ELSE 0 END)` is the OOM subset.",
      "`ROUND(100.0 * <oom count> / COUNT(*), 1)` gives the share; the `100.0` keeps it out of integer division.",
    ],
    singleFile: {
      seedSql: EXECUTORS_AND_TASKS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["executor_id", "failed_tasks", "oom_pct"],
        rows: [
          ["exec-4", 4, 75],
          ["exec-5", 3, 100],
          ["exec-2", 2, 0],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-driver-and-executors-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the total number of task slots the cluster still has, as \`(total_cores)\`, over \`spark_executors\`. Count only rows whose \`status\` is \`'ACTIVE'\` and whose \`executor_id\` is not \`'driver'\`, because the driver runs no tasks and a lost executor runs no more.`,
      starterCode: `-- Total task slots across the executors that are still alive.
SELECT
FROM spark_executors;`,
      hints: [
        "`SUM(cores)` over the filtered rows.",
        "The filter is `status = 'ACTIVE' AND executor_id <> 'driver'`.",
      ],
      referenceSolution: `SELECT SUM(cores) AS total_cores
FROM spark_executors
WHERE status = 'ACTIVE' AND executor_id <> 'driver';`,
      singleFile: {
        seedSql: EXECUTORS_AND_TASKS_SEED,
        expected: { columns: ["total_cores"], rows: [[18]] },
      },
    },
    {
      id: "de-l10-driver-and-executors-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns how many tasks each executor ran per core slot, as \`(executor_id, cores, task_count, tasks_per_core)\`, highest ratio first, over \`spark_executors\` joined to \`spark_tasks\`. Round \`tasks_per_core\` to 2 decimals. The ratio counts how many waves of tasks each executor worked through, so a high number means it was fed a lot of work and a low one means it was not. It is not a measure of memory pressure, and the executor at the top of this list is not the one at risk.`,
      starterCode: `-- Tasks run per available core slot, per executor.
SELECT e.executor_id, e.cores, COUNT(*) AS task_count
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.cores
;`,
      hints: [
        "The ratio is `COUNT(*) * 1.0 / e.cores`, so the division is not integer division.",
        "`ROUND(..., 2) AS tasks_per_core`, then `ORDER BY tasks_per_core DESC`.",
      ],
      referenceSolution: `SELECT e.executor_id,
       e.cores,
       COUNT(*) AS task_count,
       ROUND(COUNT(*) * 1.0 / e.cores, 2) AS tasks_per_core
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.cores
ORDER BY tasks_per_core DESC;`,
      singleFile: {
        seedSql: EXECUTORS_AND_TASKS_SEED,
        orderMatters: true,
        expected: {
          columns: ["executor_id", "cores", "task_count", "tasks_per_core"],
          rows: [
            ["exec-3", 2, 4, 2],
            ["exec-1", 4, 6, 1.5],
            ["exec-2", 4, 5, 1.25],
            ["exec-4", 8, 8, 1],
            ["exec-5", 4, 3, 0.75],
          ],
        },
      },
    },
    {
      id: "de-l10-driver-and-executors-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the one executor whose heaviest task came closest to filling its heap, as \`(executor_id, max_peak_memory_mb, memory_mb, peak_pct)\`, over \`spark_executors\` joined to \`spark_tasks\`. \`peak_pct\` is the executor's largest \`peak_memory_mb\` as a percentage of its \`memory_mb\`, rounded to 2 decimals, and only the top row is wanted.`,
      starterCode: `-- The executor that came closest to its memory ceiling.
SELECT e.executor_id, MAX(t.peak_memory_mb) AS max_peak_memory_mb, e.memory_mb
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.memory_mb
;`,
      hints: [
        "`MAX(t.peak_memory_mb)` is the executor's high-water mark across its tasks.",
        "`ROUND(100.0 * MAX(t.peak_memory_mb) / e.memory_mb, 2) AS peak_pct`.",
        "`ORDER BY peak_pct DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `SELECT e.executor_id,
       MAX(t.peak_memory_mb) AS max_peak_memory_mb,
       e.memory_mb,
       ROUND(100.0 * MAX(t.peak_memory_mb) / e.memory_mb, 2) AS peak_pct
FROM spark_executors e
JOIN spark_tasks t ON t.executor_id = e.executor_id
GROUP BY e.executor_id, e.memory_mb
ORDER BY peak_pct DESC
LIMIT 1;`,
      singleFile: {
        seedSql: EXECUTORS_AND_TASKS_SEED,
        orderMatters: true,
        expected: {
          columns: ["executor_id", "max_peak_memory_mb", "memory_mb", "peak_pct"],
          rows: [["exec-5", 8140, 8192, 99.37]],
        },
      },
    },
  ],
}

const lazyEvaluation: SqlLesson = {
  id: "de-l10-lazy-evaluation",
  title: "Lazy Evaluation: Transformations Plan, Actions Execute",
  summary:
    "Why Spark does no work until an action asks for a result, and how to count a job's stages by counting Exchange operators in its plan.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "lazy evaluation",
    "transformations vs actions",
    "whole-plan optimization",
    "reading .explain()",
    "Exchange equals shuffle",
    "anti-join",
    "conditional aggregation",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Nothing happens until you ask for something

Write \`df.filter(...).select(...).join(...)\` in a notebook and Spark does no work at all. Those calls are **transformations**: each one returns a new DataFrame that records what you asked for, and the recording is all that happens. Work starts only when you call an **action**: \`count()\`, \`collect()\`, \`show()\`, \`write()\`, \`take()\`, \`foreach()\`. An action submits a **job**, and one action is at least one job in the Jobs tab, usually exactly one. A write is the common exception: the data write and the commit of the written files can be scheduled as separate jobs, so one \`write.parquet\` often shows up as two rows.

The tell is the return type, and it is worth saying out loud in an interview because it is exact. A transformation returns another DataFrame. An action returns something that is not a DataFrame: a number, a list of rows, or nothing at all because it wrote to storage.

That rule settles the gotcha juniors get caught on most. \`df.count()\` returns a number, so it is an action and it submits a job. \`df.groupBy("x").count()\` returns a DataFrame, so it is a transformation and it submits nothing. Same method name, opposite answer, and the return type is what tells you which one you are looking at.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["call", "kind", "returns", "submits a job?"],
  "rows": [
    ["filter, select, withColumn", "transformation", "a DataFrame", "no"],
    ["join, groupBy().agg()", "transformation", "a DataFrame", "no"],
    ["groupBy().count()", "transformation", "a DataFrame", "no, despite the name"],
    ["cache, persist", "transformation", "a DataFrame", "no, it only marks the plan"],
    ["df.count(), collect, take", "action", "a number or rows", "yes"],
    ["show", "action", "nothing, it prints", "yes"],
    ["write.parquet", "action", "nothing, it writes", "yes, sometimes more than one"]
  ],
  "highlightCols": ["submits a job?"],
  "caption": "The line every Spark question hangs on. Transformations record intent and return a DataFrame. Actions return a result and submit a job."
}
\`\`\`

## Why laziness is a feature, not a delay

If Spark ran each transformation the moment you typed it, it would read the whole table for the filter, write the result, read it back for the select, and so on. Because it waits, the optimizer gets to see the **entire** chain before a single byte is read, and it can rewrite the chain:

- **Column pruning.** You select three columns out of forty, so it reads three columns from the Parquet files.
- **Predicate pushdown.** Your filter becomes a \`PushedFilters\` entry on the scan, so row groups that cannot match are skipped in the file reader rather than loaded and discarded.
- **Operator fusion.** Consecutive narrow steps run in one pass over each partition instead of materializing between them.

None of that is possible if each step executes on arrival. This is also why laziness makes debugging feel strange: your typo in a join condition does not raise anything until the \`count()\` twenty lines later, because that is the first moment Spark actually looks.

## Reading a physical plan at the only level you need

\`df.explain()\` prints the physical plan, and it prints it root first: the last operator to run is the top line, each \`+-\` below it is that operator's input, and the file scan is at the bottom. So you read an explain output from the bottom up, and the tables in this lesson number the steps in that reading order, with the scan as step 1.

You are not expected to parse all of it in a junior interview. You are expected to recognize one operator: **\`Exchange\`**. An \`Exchange\` is a shuffle, a shuffle is where data moves across the network to co-locate by key, and every shuffle is a **stage boundary**. That gives you an arithmetic you can do at a glance:

\`\`\`
stages = Exchange operators + 1
\`\`\`

A plan with no \`Exchange\` runs in one stage: scan, filter, project, done, no data ever moves between machines. A sort-merge join shows an \`Exchange\` on each side, and a group-by after it shows a third, so that plan runs in four stages. Counting them is the fastest read of "how expensive is this query" available to you.

The operator you count is the plain shuffle \`Exchange\`. Plans also print \`BroadcastExchange\`, which you will meet in the next module: it ships one small side of a join to every executor instead of repartitioning both sides by key, so it does not cut the plan into stages the same way and the arithmetic above does not apply to it.

**Common mistake:** believing that only actions ever submit jobs. Almost true, and the exception is worth knowing: reading CSV or JSON with schema inference scans the file to work out the types, and that scan shows up as a job in the UI before you have called any action. Reading Parquet does not, because the schema is in the file footer. That is why the Jobs tab of a fresh notebook sometimes has a job in it and nobody can find the action that caused it.

**Interview nuance:** "why is Spark lazy" is a Tier A question and a one-sentence answer scores: because deferring execution lets the optimizer see the whole plan and prune columns and push filters down before reading any data. If you are then asked about \`.explain()\`, do not try to narrate the tree. Say that you look for \`Exchange\` operators, because each one is a shuffle and a stage boundary, and that tells you where the cost is.

> **On a real platform this differs.** Here you query a saved copy of the plan and a saved copy of the Jobs tab. In production you call \`df.explain(True)\` for the parsed, analyzed, optimized and physical plans, or read the SQL tab of the Spark UI, which draws the same plan as a graph with per-operator row counts. The Python course makes this executable a different way: a roughly 100-line pure-Python MiniSpark, where \`.map\` and \`.filter\` build a plan, \`.collect()\` runs it, and \`.explain()\` prints the stages with \`Exchange\` markers, so you can watch laziness happen instead of reading about it. One currency note: Spark 4.0 shipped in mid-2025 and is generally available on EMR, and it turns ANSI mode on by default, so a divide by zero or a bad cast now fails fast instead of quietly returning NULL. Answers built on the old silent-null behavior are out of date.`,
    demoSeedSql: QUERY_PLAN_OPS_SEED,
    demoCode: `-- One physical plan in execution order, which is bottom-up in a real .explain() printout.
-- Every Exchange is a shuffle and a stage boundary.
SELECT step,
       operator,
       detail,
       CASE WHEN operator = 'Exchange' THEN '<-- shuffle, new stage starts here' ELSE '' END AS boundary
FROM query_plan_ops
WHERE plan_id = 'plan_order_join'
ORDER BY step;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-lazy-evaluation-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each query plan with the number of shuffles it contains and the number of stages it will therefore run in, as \`(plan_id, exchange_count, stage_count)\`, in \`plan_id\` order, over \`query_plan_ops(plan_id, step, operator, detail)\`.

An \`Exchange\` operator is a shuffle, and a shuffle is a stage boundary, so \`stage_count\` is \`exchange_count + 1\`. One of these plans has no \`Exchange\` at all and still runs in one stage, so count the operators rather than the rows.`,
    starterCode: `-- Shuffles and stages per plan. Exchange = shuffle = stage boundary.
SELECT plan_id
  -- how many Exchange operators, and the stage count that follows from them
FROM query_plan_ops
GROUP BY plan_id
ORDER BY plan_id;`,
    hints: [
      "A conditional count: `SUM(CASE WHEN operator = 'Exchange' THEN 1 ELSE 0 END) AS exchange_count`.",
      "`COUNT(*)` would count every operator in the plan, not just the shuffles.",
      "The same conditional sum plus 1 is `stage_count`, so a plan with zero Exchanges still reports 1.",
    ],
    referenceSolution: `SELECT plan_id,
       SUM(CASE WHEN operator = 'Exchange' THEN 1 ELSE 0 END) AS exchange_count,
       SUM(CASE WHEN operator = 'Exchange' THEN 1 ELSE 0 END) + 1 AS stage_count
FROM query_plan_ops
GROUP BY plan_id
ORDER BY plan_id;`,
    singleFile: {
      seedSql: QUERY_PLAN_OPS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["plan_id", "exchange_count", "stage_count"],
        rows: [
          ["plan_daily_active", 1, 2],
          ["plan_dedupe", 1, 2],
          ["plan_lookup_filter", 0, 1],
          ["plan_order_join", 3, 4],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-lazy-evaluation-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every notebook command that submitted no job at all, as \`(command_id, command_type)\`, in \`command_id\` order, over \`notebook_commands(command_id, code_snippet, command_type)\` and \`spark_jobs(job_id, command_id, action, duration_s)\`.

This is an anti-join: keep the commands that have no matching row in \`spark_jobs\`. Do not filter on \`command_type\` instead. One command in this log is classified as a transformation and still submitted a job, and finding it is the point of the exercise.`,
    starterCode: `-- Commands that never made Spark do anything: no matching row in the Jobs tab.
SELECT command_id, command_type
FROM notebook_commands
;`,
    hints: [
      "`WHERE NOT EXISTS (SELECT 1 FROM spark_jobs j WHERE j.command_id = notebook_commands.command_id)` is the anti-join.",
      "A `LEFT JOIN spark_jobs` with `WHERE spark_jobs.job_id IS NULL` does the same thing.",
      "`NOT IN` also works here, but only because no `command_id` in `spark_jobs` is NULL.",
    ],
    singleFile: {
      seedSql: NOTEBOOK_AND_JOBS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["command_id", "command_type"],
        rows: [
          [1, "transformation"],
          [2, "transformation"],
          [3, "transformation"],
          [5, "transformation"],
          [7, "transformation"],
          [10, "transformation"],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-lazy-evaluation-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many commands of each kind the notebook log holds, as \`(command_type, command_count)\`, in \`command_type\` order, over \`notebook_commands\`.`,
      starterCode: `-- Actions against transformations in the command log.
SELECT command_type
FROM notebook_commands
;`,
      hints: [
        "`GROUP BY command_type` with `COUNT(*) AS command_count`.",
        "Order by `command_type` so actions come before transformations.",
      ],
      referenceSolution: `SELECT command_type, COUNT(*) AS command_count
FROM notebook_commands
GROUP BY command_type
ORDER BY command_type;`,
      singleFile: {
        seedSql: NOTEBOOK_AND_JOBS_SEED,
        orderMatters: true,
        expected: {
          columns: ["command_type", "command_count"],
          rows: [
            ["action", 4],
            ["transformation", 7],
          ],
        },
      },
    },
    {
      id: "de-l10-lazy-evaluation-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the single plan with the most shuffles in it, as \`(plan_id, exchange_count)\`, over \`query_plan_ops\`.`,
      starterCode: `-- The plan that shuffles the most.
SELECT plan_id, SUM(CASE WHEN operator = 'Exchange' THEN 1 ELSE 0 END) AS exchange_count
FROM query_plan_ops
GROUP BY plan_id
;`,
      hints: [
        "Order the grouped result by `exchange_count` descending.",
        "`LIMIT 1` keeps only the worst plan.",
      ],
      referenceSolution: `SELECT plan_id, SUM(CASE WHEN operator = 'Exchange' THEN 1 ELSE 0 END) AS exchange_count
FROM query_plan_ops
GROUP BY plan_id
ORDER BY exchange_count DESC, plan_id
LIMIT 1;`,
      singleFile: {
        seedSql: QUERY_PLAN_OPS_SEED,
        orderMatters: true,
        expected: {
          columns: ["plan_id", "exchange_count"],
          rows: [["plan_order_join", 3]],
        },
      },
    },
    {
      id: "de-l10-lazy-evaluation-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns how many jobs each recorded trigger submitted and how long they took in total, as \`(action, job_count, total_duration_s)\`, slowest total first, over \`spark_jobs\`. Round \`total_duration_s\` to 1 decimal. The \`action\` column is whatever the scheduler credited with the job, so \`read\` appears there even though a read is a transformation.`,
      starterCode: `-- Job count and total runtime, grouped by the trigger the scheduler recorded.
SELECT action
FROM spark_jobs
GROUP BY action
;`,
      hints: [
        "`COUNT(*) AS job_count` and `ROUND(SUM(duration_s), 1) AS total_duration_s`.",
        "`ORDER BY total_duration_s DESC` puts the expensive action first.",
      ],
      referenceSolution: `SELECT action,
       COUNT(*) AS job_count,
       ROUND(SUM(duration_s), 1) AS total_duration_s
FROM spark_jobs
GROUP BY action
ORDER BY total_duration_s DESC;`,
      singleFile: {
        seedSql: NOTEBOOK_AND_JOBS_SEED,
        orderMatters: true,
        expected: {
          columns: ["action", "job_count", "total_duration_s"],
          rows: [
            ["write", 2, 114.7],
            ["collect", 1, 41.7],
            ["count", 1, 12.4],
            ["read", 1, 6.8],
            ["show", 1, 3.1],
          ],
        },
      },
    },
  ],
}

const jobsStagesTasks: SqlLesson = {
  id: "de-l10-jobs-stages-tasks",
  title: "Job, Stage, Task: Decomposing a Run You Have Never Seen",
  summary:
    "Rebuild the job to stage to task hierarchy of an unfamiliar run from its metrics alone, then name where the time actually went.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "job stage task hierarchy",
    "stages cut at shuffle boundaries",
    "shuffle write attribution",
    "multi-table JOIN",
    "CTEs",
    "window functions",
    "share-of-total analysis",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## The whole decomposition, in three sentences

An **action** submits a **job**. The planner cuts that job into **stages**, one cut at every shuffle. Each stage runs one **task** per partition, and those tasks run in parallel across the executors' core slots.

Everything else follows from those three sentences. A job with three stages had two shuffles in its plan. A stage with 200 tasks was reading 200 partitions. A stage cannot start until every task of the stage feeding it has finished, which is why one slow task can hold up an entire cluster.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Action", "note": "write() submits one job" },
    { "label": "Stage 2: scan events", "note": "6 tasks, writes 640 MB of shuffle" },
    { "label": "Stage 3: scan users", "note": "2 tasks, writes 25 MB of shuffle" },
    { "label": "Stage 4: join + write", "note": "6 tasks, reads 665 MB back, 210 s" },
    { "label": "Job done", "note": "265 s wall clock" }
  ],
  "highlight": ["Stage 4: join + write"],
  "caption": "One action, one job, three stages. The two scan stages write the shuffle; the join stage reads it back and dominates the runtime."
}
\`\`\`

## Shuffle write belongs to the stage that produced it

Level 6 stated the attribution rule; here it becomes a diagnostic. A shuffle has a write side and a read side, and they sit in **different stages**. The stage upstream of the boundary writes the shuffle files. The stage downstream reads them back. So a stage whose own transformations are all narrow can still show hundreds of megabytes of \`shuffle_write\`, purely because it sits at the boundary and produced the data the next stage needs.

Read it in pairs. Stage 2 writes 640 MB, stage 3 writes 25 MB, stage 4 reads 665 MB: those three numbers are one shuffle seen from both sides. When they do not reconcile, something is missing from your picture, and that is a real diagnostic, not a curiosity.

## The walk an interviewer is listening for

Given an unfamiliar slow run, there is a standard order to work in, and following it out loud is most of the answer:

1. **Which job.** Total the runtime per job and find the one that owns the time. Do not tune a 12-second job.
2. **Which stage.** Inside that job, find the stage with the largest share of the job's duration. That is where the fix has to be.
3. **Which task.** Inside that stage, look at how the task durations are distributed. Five tasks around 22 seconds and one at 198 seconds is not a slow stage, it is a skewed one, and the fix is completely different from "add more executors".

Step 3 is where the next module lives. This lesson gets you through steps 1 and 2, which is the part that has to be automatic.

**Common mistake:** expecting a job's \`duration_s\` to equal the sum of its stage durations. It never does. Stages of the same job can overlap when neither depends on the other (the two scan stages of a join run at the same time), and the job also carries scheduling and commit overhead outside any stage. Treat the job duration as the denominator when you compute a stage's share, and never as a total to reconcile.

**Interview nuance:** "walk me through what happens when you run \`df.groupBy("x").count()\`" is the Amazon and TikTok phrasing of this whole lesson. The answer they want is the chain: the \`count()\` is the action so it submits one job, the \`groupBy\` is wide so the planner cuts the job at that shuffle into two stages, stage one scans and pre-aggregates locally and writes shuffle files, stage two reads them back keyed by \`x\` and finishes the aggregation, and each stage runs one task per partition. Saying "it counts the rows in each group" answers a different question than the one asked.

> **On a real platform this differs.** These three tables are the Spark UI's Jobs, Stages and Tasks tabs, trimmed to the columns that carry the lesson. The real Stages tab adds input and output bytes, spill to memory and disk, GC time, and a task-duration percentile summary; the real Tasks tab has roughly thirty columns. On EMR the same data survives the cluster in the persistent application UI, and on AWS Glue each job run links to its own Spark UI archived to S3. The event log behind all of it is newline-delimited JSON, which means teams commonly load a directory of event logs into a warehouse and run exactly the queries you are about to write across every job the platform has ever run.`,
    demoSeedSql: SPARK_RUN_SEED,
    demoCode: `-- The hierarchy reassembled: tasks join up to their stage, stages join up to their job.
-- A task row carries no job_id, so the only way to reach the job is through spark_stages.
-- The stage's own shuffle_write_mb and the sum of its tasks' shuffle writes are the same number
-- seen from both sides, which is what makes these metrics worth trusting.
SELECT j.job_id,
       j.action,
       s.stage_id,
       s.name,
       COUNT(t.task_id) AS tasks_counted,
       SUM(t.input_records) AS input_records,
       s.shuffle_write_mb AS stage_shuffle_write_mb,
       SUM(t.shuffle_write_mb) AS task_shuffle_write_mb
FROM spark_jobs j
JOIN spark_stages s ON s.job_id = j.job_id
JOIN spark_tasks t ON t.stage_id = s.stage_id
GROUP BY j.job_id, j.action, s.stage_id, s.name, s.shuffle_write_mb
ORDER BY j.job_id, s.stage_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l10-jobs-stages-tasks-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each job with its stage count, its total task count, the shuffle megabytes its stages wrote, and the input records its tasks read, as \`(job_id, stages, tasks, shuffle_write_mb, input_records)\`, in job order, over \`spark_jobs(job_id, action, duration_s)\`, \`spark_stages(stage_id, job_id, name, num_tasks, shuffle_read_mb, shuffle_write_mb, duration_s)\` and \`spark_tasks(task_id, stage_id, duration_ms, input_records, shuffle_write_mb)\`.

A task row carries no \`job_id\`, so both task columns have to travel up through \`spark_stages\` to reach the job they belong to. Roll the stages up and the tasks up separately before joining them to \`spark_jobs\`, or a single flat join will repeat each stage row once per task it ran and inflate \`shuffle_write_mb\`.`,
    starterCode: `-- Rebuild the hierarchy: stages and tasks per job, the shuffle those stages wrote,
-- and the records those tasks read.
WITH stage_rollup AS (
  -- one row per job: how many stages, and how much shuffle they wrote
  SELECT job_id
  FROM spark_stages
  GROUP BY job_id
)
SELECT j.job_id
FROM spark_jobs j
ORDER BY j.job_id;`,
    hints: [
      "One CTE over `spark_stages` grouped by `job_id` gives `COUNT(*) AS stages` and `SUM(shuffle_write_mb)`.",
      "A second CTE joins `spark_tasks` to `spark_stages` on `stage_id` and groups by `s.job_id` for `COUNT(*) AS tasks` and `SUM(t.input_records)`.",
      "Join both rollups back to `spark_jobs` on `job_id` and order by it.",
    ],
    referenceSolution: `WITH stage_rollup AS (
  SELECT job_id,
         COUNT(*) AS stages,
         SUM(shuffle_write_mb) AS shuffle_write_mb
  FROM spark_stages
  GROUP BY job_id
),
task_rollup AS (
  SELECT s.job_id,
         COUNT(*) AS tasks,
         SUM(t.input_records) AS input_records
  FROM spark_tasks t
  JOIN spark_stages s ON s.stage_id = t.stage_id
  GROUP BY s.job_id
)
SELECT j.job_id,
       sr.stages,
       tr.tasks,
       sr.shuffle_write_mb,
       tr.input_records
FROM spark_jobs j
JOIN stage_rollup sr ON sr.job_id = j.job_id
JOIN task_rollup tr ON tr.job_id = j.job_id
ORDER BY j.job_id;`,
    singleFile: {
      seedSql: SPARK_RUN_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["job_id", "stages", "tasks", "shuffle_write_mb", "input_records"],
        rows: [
          [0, 2, 8, 120, 10013210],
          [1, 3, 14, 665, 80068000],
          [2, 1, 4, 0, 20250000],
        ],
      },
    },
  },
  practice: {
    id: "de-l10-jobs-stages-tasks-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the stage that dominates each job's runtime and the share of the job it took, as \`(job_id, stage_id, stage_share_pct)\`, one row per job, in job order, over \`spark_stages\` and \`spark_jobs\`.

The dominant stage is the one with the largest \`duration_s\` in its job. \`stage_share_pct\` is that stage's \`duration_s\` as a percentage of the job's own \`duration_s\`, rounded to 1 decimal. Use a window function or a correlated subquery, whichever you find clearer.`,
    starterCode: `-- Step two of every slow-job walk: which stage owns the job's time.
SELECT
FROM spark_stages
;`,
    hints: [
      "Two ways to find the per-job maximum: `MAX(duration_s) OVER (PARTITION BY job_id)` in a CTE and then keep the rows that equal it, or a correlated `WHERE s.duration_s = (SELECT MAX(s2.duration_s) FROM spark_stages s2 WHERE s2.job_id = s.job_id)`.",
      "The share is `ROUND(100.0 * s.duration_s / j.duration_s, 1)`, so the job duration has to come from `spark_jobs`, not from summing the stages.",
    ],
    singleFile: {
      seedSql: SPARK_RUN_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["job_id", "stage_id", "stage_share_pct"],
        rows: [
          [0, 0, 72],
          [1, 4, 79.2],
          [2, 5, 92.3],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l10-jobs-stages-tasks-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the average task duration of each stage, as \`(stage_id, avg_duration_ms)\`, in stage order, over \`spark_tasks\`. Round \`avg_duration_ms\` to 1 decimal.`,
      starterCode: `-- Typical task duration, per stage.
SELECT stage_id
FROM spark_tasks
GROUP BY stage_id
ORDER BY stage_id;`,
      hints: ["`ROUND(AVG(duration_ms), 1) AS avg_duration_ms`.", "Group and order by `stage_id`."],
      referenceSolution: `SELECT stage_id, ROUND(AVG(duration_ms), 1) AS avg_duration_ms
FROM spark_tasks
GROUP BY stage_id
ORDER BY stage_id;`,
      singleFile: {
        seedSql: SPARK_RUN_SEED,
        orderMatters: true,
        expected: {
          columns: ["stage_id", "avg_duration_ms"],
          rows: [
            [0, 4500],
            [1, 1475],
            [2, 6350],
            [3, 1850],
            [4, 52000],
            [5, 28750],
          ],
        },
      },
    },
    {
      id: "de-l10-jobs-stages-tasks-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every stage that reads back more shuffle data than its whole job ever wrote, as \`(job_id, stage_id, shuffle_read_mb, job_shuffle_write_mb)\`, in job then stage order, over \`spark_stages\`. A stage cannot read shuffle files nobody produced, so any row this returns means the producing stage is missing from the captured event log.`,
      starterCode: `-- Sanity check: shuffle read with no producer behind it.
SELECT s.job_id, s.stage_id, s.shuffle_read_mb
FROM spark_stages s
;`,
      hints: [
        "Build the per-job total first: `SELECT job_id, SUM(shuffle_write_mb) AS job_shuffle_write_mb FROM spark_stages GROUP BY job_id`.",
        "Join that back to `spark_stages` on `job_id` and keep rows where `shuffle_read_mb` is greater than the job total.",
        "Order by `job_id`, then `stage_id`.",
      ],
      referenceSolution: `WITH job_writes AS (
  SELECT job_id, SUM(shuffle_write_mb) AS job_shuffle_write_mb
  FROM spark_stages
  GROUP BY job_id
)
SELECT s.job_id,
       s.stage_id,
       s.shuffle_read_mb,
       w.job_shuffle_write_mb
FROM spark_stages s
JOIN job_writes w ON w.job_id = s.job_id
WHERE s.shuffle_read_mb > w.job_shuffle_write_mb
ORDER BY s.job_id, s.stage_id;`,
      singleFile: {
        seedSql: SPARK_RUN_SEED,
        orderMatters: true,
        expected: {
          columns: ["job_id", "stage_id", "shuffle_read_mb", "job_shuffle_write_mb"],
          rows: [[2, 5, 900, 0]],
        },
      },
    },
  ],
}

export const level10Module1: SqlModule = {
  id: "de-l10-spark-execution-model",
  title: "Module 10.1: Spark's Execution Model",
  description:
    "The vocabulary and mechanics every Spark conversation presupposes, taught by querying the simulated Spark UI: driver and executors, lazy evaluation, and the job to stage to task decomposition.",
  lessons: [driverAndExecutors, lazyEvaluation, jobsStagesTasks],
}
