// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { CompiledTicket } from "@/lib/sprint-labs/content/types"

export const mer801Ticket: CompiledTicket = {
  ticket: {
    key: "MER-801",
    title: 'Extraction has no way to say "I don\'t know"',
    points: 5,
    labels: ["ai-engineering", "llm"],
    aiPolicy: "assisted",
    objectives: [
      {
        id: "llm-replayable-seam-typed-abstention",
        label: "Replayable LLM seam",
        canDo:
          "I can put an LLM behind a replayable seam so the entire extraction path runs in CI with no network and no provider key, and a model or prompt change shows up as a diff instead of a surprise.",
      },
    ],
    bodyMd:
      'The extractor currently always returns a full set of fields for every\nclaim, because the regex-based pipeline it started life as had no other\noption: if a field didn\'t match, it fell back to a default rather than\nadmitting it found nothing. Whatever replaces it needs to be honest about\nthe difference between "I read the deductible and it\'s $500" and "I could\nnot find a deductible on this document," because right now those two cases\nare indistinguishable downstream.\n\nThis also has to run somewhere other than production. Right now, testing\nanything about extraction means burning real provider tokens against a real\nAPI on every test run, with no way to pin a specific model response and\nreplay it later. A prompt change or model swap should show up as a\nreviewable diff, not a surprise discovered days later on live claims.',
    acceptanceCriteria: [
      "The extraction path can run entirely in CI with no network call and no provider key, replaying a fixed recorded exchange.",
      'A claim where a field cannot be found returns a distinct, typed "not found" outcome rather than a fabricated default value.',
      "A change to the prompt or the model produces a visible diff against what CI already has recorded, rather than passing silently.",
      'Nothing downstream of extraction treats "not found" the same way it treats a real extracted value.',
    ],
    adversaryPresent: false,
    playable: false,
  },
  setupDiff: null,
  visibleTestFiles: [],
  hiddenTests: [],
}
