// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { CompiledTicket } from "@/lib/sprint-labs/content/types"

export const mer902Ticket: CompiledTicket = {
  ticket: {
    key: "MER-902",
    title: "Review: prompt v2 (+1.3% accuracy), ok to ship?",
    points: 5,
    labels: ["ai-engineering", "evals", "code-review"],
    aiPolicy: "review-only",
    objectives: [
      {
        id: "block-regressing-model-change-review",
        label: "Blocking a regressing model change",
        canDo:
          "I can block a prompt or model change that improves the headline metric while regressing a named subpopulation, using a baseline pinned to a dataset revision, and review an agent-authored PR that is green on every existing test by stating a verdict with evidence and writing the test that turns it red.",
      },
    ],
    bodyMd:
      'The extraction prompt rewrite is up for sign-off. The headline number is\ngood: aggregate accuracy is up 1.3% against the eval set the last ticket\nbuilt. Whoever ran the comparison is treating that as the whole story and\nwants to ship today.\n\nRunning the per-slice breakdown that now exists turns up something the\naggregate number hides: on 10 of 120 cases, the new prompt\'s instruction to\n"populate every field with your best guess" has replaced what should have\nbeen an honest "not found" outcome with a fabricated value. In at least one\nof those cases, a genuinely missing deductible got filled in as $0, which\nis not a null value and is not distinguishable downstream from an actual $0\ndeductible.\n\nAn aggregate improvement sitting on top of a newly broken subpopulation is\nnot a clean ship.',
    acceptanceCriteria: [
      "The review reports the per-slice breakdown, not just the aggregate accuracy delta.",
      'The review identifies that the new prompt regresses the "not found" outcome for a specific, named subpopulation.',
      "The verdict is block, approve, or approve-with-changes, backed by the per-slice evidence rather than the aggregate number alone.",
    ],
    adversaryPresent: false,
    playable: false,
  },
  setupDiff: null,
  visibleTestFiles: [],
  hiddenTests: [],
}
