// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { CompiledTicket } from "@/lib/sprint-labs/content/types"

export const mer405Ticket: CompiledTicket = {
  ticket: {
    key: "MER-405",
    title: "CLM-9001 shows as paid, then under_review, and delivery p95 is 40 minutes",
    points: 5,
    labels: ["delivery", "ordering"],
    aiPolicy: "assisted",
    objectives: [
      {
        id: "per-claim-ordering-guarantee",
        label: "Per-claim ordering guarantees",
        canDo:
          "I can state an ordering guarantee as per-claim rather than global, enforce it with lanes, and demonstrate that one dead destination cannot delay an unrelated tenant's deliveries.",
      },
    ],
    bodyMd:
      'Northwind\'s system briefly showed CLM-9001 as paid and then as under_review a few minutes later, the reverse of what actually happened to the claim. Separately, webhook delivery p95 has crept up to 40 minutes.\n\nFrom the support thread:\n\n> Their side received the two webhooks out of order. We definitely sent the correct one first. Also somebody flagged that delivery times have gotten a lot worse this week, might be related, might not.\n\nThere is currently no stated guarantee about delivery order at all, within a claim or across claims, and one very slow or unreachable destination appears to be able to hold up delivery for everyone else sharing whatever drains the backlog.\n\nAmbiguous ask from the PM: "can we just guarantee global ordering so this never happens again?"',
    acceptanceCriteria: [
      "Two webhooks for the same claim are always delivered in the order they were produced, even if an earlier attempt had to be retried.",
      "The ordering guarantee is stated as per-claim, not global; two different claims' deliveries have no required order relative to each other.",
      "One destination that is slow or completely unreachable does not delay delivery of an unrelated tenant's or an unrelated claim's webhooks.",
      "Delivery p95 returns to its prior baseline once one slow destination can no longer hold up an unrelated lane.",
    ],
    adversaryPresent: false,
    playable: false,
  },
  setupDiff: null,
  visibleTestFiles: [],
  hiddenTests: [],
}
