// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { CompiledTicket } from "@/lib/sprint-labs/content/types"

export const mer802Ticket: CompiledTicket = {
  ticket: {
    key: "MER-802",
    title: "Use the model (Northwind churn risk)",
    points: 8,
    labels: ["ai-engineering", "llm", "schema"],
    aiPolicy: "assisted",
    objectives: [
      {
        id: "constrained-json-output-typed-errors",
        label: "Constrained output and typed failures",
        canDo:
          "I can constrain model output with a JSON Schema generated from the same source the code validates against, and handle schema-invalid, timed-out, and rate-limited responses as three distinct typed outcomes rather than one catch block.",
      },
    ],
    bodyMd:
      "Northwind's contract renewal is coming up and their lead adjuster has said,\nmore than once, that the regex extractor misses fields a human reader would\ncatch immediately. Product wants the actual model call live before that\nrenewal conversation, replacing the regex pass entirely rather than running\nalongside it.\n\nThe model needs to return something the rest of the system can trust the\nshape of. A raw text completion that mostly looks like the right JSON is\nnot good enough when the fallback path for a malformed response has, so\nfar, been to just retry until something parses. Timeouts and rate limits\nfrom the provider are also going to happen in production and need to be\ntold apart from a response that came back but didn't match the schema,\nbecause the right response to each is different.",
    acceptanceCriteria: [
      "Model output is validated against a JSON Schema generated from the same source the rest of the code already validates against.",
      "A schema-invalid response, a timed-out request, and a rate-limited request are three distinct, typed outcomes, not one generic failure.",
      "No response is accepted downstream until it has passed schema validation.",
      "A field the model is not confident about is represented as such, not silently coerced to a default.",
    ],
    adversaryPresent: false,
    playable: false,
  },
  setupDiff: null,
  visibleTestFiles: [],
  hiddenTests: [],
}
