// GENERATED by scripts/compile-packs.mjs — edit packs/<id>/ and recompile.
/**
 * Sealed-pack registry (SERVER-ONLY). The ONLY loader for per-pack sealed modules;
 * imported ONLY by the phase-2 release endpoint, the pack advance endpoint, and the
 * debrief path (enforced by the sealing import-graph test). The window guard is the
 * runtime seal (this repo has no server-only package).
 */
import type { SealedPackContent } from "@/lib/bugfix/packs/types"

if (typeof window !== "undefined") {
  throw new Error("Sealed pack content must never load in the browser.")
}

const SEALED_PACK_LOADERS: Record<string, () => Promise<{ sealed: SealedPackContent }>> = {
  "datadog-endpoint-latency-peak": () => import("./datadog-endpoint-latency-peak.server"),
  "datadog-metric-window-rollup": () => import("./datadog-metric-window-rollup.server"),
  "datadog-monitor-empty-series": () => import("./datadog-monitor-empty-series.server"),
  "generic-cache-eviction-mutation": () => import("./generic-cache-eviction-mutation.server"),
  "generic-log-error-rollup": () => import("./generic-log-error-rollup.server"),
  "palantir-entity-resolution-merge": () => import("./palantir-entity-resolution-merge.server"),
  "palantir-foundry-usage-rollup": () => import("./palantir-foundry-usage-rollup.server"),
  "palantir-ontology-link-rollup": () => import("./palantir-ontology-link-rollup.server"),
  "palantir-pipeline-order-dependence": () => import("./palantir-pipeline-order-dependence.server"),
  "stripe-ledger-double-post": () => import("./stripe-ledger-double-post.server"),
  "stripe-payout-batch-mutation": () => import("./stripe-payout-batch-mutation.server"),
  "stripe-webhook-idempotency": () => import("./stripe-webhook-idempotency.server"),
}

export function hasSealedPack(packId: string): boolean {
  return Object.prototype.hasOwnProperty.call(SEALED_PACK_LOADERS, packId)
}

export async function loadSealedPack(packId: string): Promise<SealedPackContent | null> {
  const loader = SEALED_PACK_LOADERS[packId]
  if (!loader) return null
  const mod = await loader()
  return mod.sealed
}

export function sealedPackIds(): string[] {
  return Object.keys(SEALED_PACK_LOADERS)
}
