/**
 * SQL curriculum Level 6 — Cloud & Data Engineering Foundations.
 *
 * The beginner infrastructure-literacy layer that L1-L5 leave out. L1-L5 teach SQL query
 * skill; L6 teaches the PLATFORM the SQL runs on, the way an intern/junior DE interview
 * probes it: object storage, columnar file formats, partitioning, distributed execution,
 * and pipelines. Every lesson teaches the concept deeply in `teach`, then grades a real
 * "query the platform's own metadata" SQL exercise over a simulated catalog (an S3
 * inventory, a Glue catalog, Parquet column stats, a partition catalog, Spark task
 * metrics, a pipeline run log) so the existing routing/registry/test guards cover it with
 * no new wiring. See docs/sql-curriculum/cloud/PLAN.md and the four source-verified
 * research facts-sheets beside it.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through
 * the SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never
 * hand-typed, and re-checked by single-file-reference-solutions.test.ts. Content rules
 * (constitution + memory): no em dashes in learner prose; every Apply/Practice prompt
 * leads with the deliverable.
 */
import type { SqlLevel } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Shared simulated-catalog seeds for Module 6.1. Named after the real thing so a learner
// who later queries the actual metadata recognizes the shape.
// ---------------------------------------------------------------------------

const PLATFORM_SEED = `CREATE TABLE platform_services (
  service          TEXT,
  layer            TEXT,     -- storage | catalog | compute | orchestration | serving
  monthly_cost_usd INTEGER
);
INSERT INTO platform_services (service, layer, monthly_cost_usd) VALUES
  ('S3 data lake',        'storage',       1200),
  ('Glue Data Catalog',   'catalog',        150),
  ('Athena',              'compute',        900),
  ('EMR Spark cluster',   'compute',       2600),
  ('Redshift warehouse',  'compute',       3100),
  ('Airflow (MWAA)',      'orchestration',  400),
  ('QuickSight BI',       'serving',        350),
  ('API cache (Redis)',   'serving',        220);`

const S3_INVENTORY_SEED = `CREATE TABLE s3_inventory (
  object_key       TEXT,
  size_bytes       INTEGER,
  storage_class    TEXT,
  last_access_days INTEGER   -- days since the object was last read
);
INSERT INTO s3_inventory (object_key, size_bytes, storage_class, last_access_days) VALUES
  ('raw/events/2026-01-02/part-0.parquet',    300000000000, 'STANDARD',      1),
  ('raw/events/2025-08-01/part-0.parquet',    300000000000, 'STANDARD',    150),
  ('raw/logs/2025-11-15/app.log',             400000000000, 'STANDARD',    210),
  ('curated/daily_active/2026-01-01.parquet',  90000000000, 'STANDARD',      1),
  ('raw/logs/2025-10-01/app.log',             600000000000, 'STANDARD_IA', 260),
  ('archive/2024/full.tar',                  1000000000000, 'GLACIER_DEEP',800),
  ('exports/report-2026-01.csv',              50000000000, 'STANDARD',      5);`

const STORAGE_PRICING_SEED = `CREATE TABLE storage_pricing (
  storage_class   TEXT,
  usd_per_gb_month REAL   -- illustrative US price; 1 GB = 1,000,000,000 bytes here
);
INSERT INTO storage_pricing (storage_class, usd_per_gb_month) VALUES
  ('STANDARD',     0.023),
  ('STANDARD_IA',  0.0125),
  ('GLACIER_IR',   0.004),
  ('GLACIER_DEEP', 0.00099);`

const INVENTORY_AND_PRICING_SEED = S3_INVENTORY_SEED + "\n" + STORAGE_PRICING_SEED

const GLUE_CATALOG_SEED = `CREATE TABLE glue_catalog (
  db_name        TEXT,
  table_name     TEXT,
  location       TEXT,     -- the S3 prefix the files live under
  file_format    TEXT,     -- parquet | json | csv
  partition_keys TEXT      -- comma-separated, '' when the table is unpartitioned
);
INSERT INTO glue_catalog (db_name, table_name, location, file_format, partition_keys) VALUES
  ('analytics', 'events',       's3://lake/raw/events/',   'parquet', 'dt'),
  ('analytics', 'daily_active', 's3://lake/curated/dau/',  'parquet', 'dt'),
  ('analytics', 'app_logs',     's3://lake/raw/logs/',     'json',    ''),
  ('finance',   'invoices',     's3://lake/raw/invoices/', 'csv',     ''),
  ('finance',   'fx_rates',     's3://lake/ref/fx/',       'parquet', ''),
  ('ml',        'features',     's3://lake/ml/features/',  'parquet', 'dt');`

// ---------------------------------------------------------------------------
// Module 6.1 — The Cloud Data Platform
// ---------------------------------------------------------------------------

const cloudAndTheDeStack: SqlLesson = {
  id: "sql-l6-cloud-and-the-de-stack",
  title: "What the Cloud Is, and the Shape of a Data Platform",
  summary:
    "Regions, availability zones, and managed services, then the five decoupled layers every data platform is built from: storage, catalog, compute, orchestration, serving.",
  estimatedMinutes: 24,
  difficulty: "easy",
  skills: [
    "cloud fundamentals",
    "regions and availability zones",
    "managed services",
    "data platform architecture",
    "GROUP BY",
    "SUM",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## What "the cloud" really is

The cloud is renting other people's computers and services over the internet, billed by usage, instead of buying and racking your own hardware. For a data engineer that reframes cost as a design choice: you pay for bytes stored, bytes a query scans, requests made, and data moved, so the cheapest query is the one that reads the fewest bytes. That single idea drives everything in this level.

Two words you will hear on day one:

- A **Region** is a geographic area where a cloud provider clusters data centers (for example \`us-east-1\` in North Virginia). Regions are fully independent, and data in a Region stays in that Region unless you copy it out.
- An **Availability Zone (AZ)** is one or more discrete data centers inside a Region, each with its own power and networking. Every Region has at least three AZs, physically separated but linked by fast private networking. One AZ can fail, so spreading data and compute across several is how a platform stays up.

A **managed service** is the other half of the mental model. Instead of running the server yourself, you consume a capability through an API and the provider handles the machines, patching, scaling, and failover. Object storage (Amazon S3), serverless SQL (Amazon Athena), and a warehouse (Amazon Redshift) are all managed: you rent the capability, not the box.

## The shape of a data platform

Almost every cloud data platform is the same five layers, and knowing the layers is how you place any new tool you meet.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Storage", "note": "files on object storage (S3)" },
    { "label": "Catalog", "note": "schema for those files (Glue)" },
    { "label": "Compute", "note": "runs the SQL (Athena, Spark)" },
    { "label": "Orchestration", "note": "schedules the jobs (Airflow)" },
    { "label": "Serving", "note": "dashboards, APIs, cache" }
  ],
  "caption": "The five decoupled layers of a cloud data platform. Storage is just files; compute is rented per query."
}
\`\`\`

1. **Storage** holds the raw and processed data as files, cheaply and at any scale (the data lake on object storage).
2. **Catalog** records what those files mean: table names, columns, types, and where the files live. Without it, a folder of files is just bytes.
3. **Compute** is the engine that reads the files and runs your SQL or jobs (Athena, Spark, a warehouse). Compute is separate from storage, so you can scale them independently and point many engines at the same data.
4. **Orchestration** schedules the jobs and wires their dependencies into a pipeline that runs on time.
5. **Serving** is where cleaned results land for people and apps: dashboards, an API, a cache.

The defining feature of the modern platform is that these layers are **decoupled**. Storage is just files, the catalog gives them a schema, and compute is rented by the query. That separation is why "run SQL over a folder of files" is a normal sentence, and it is the backdrop for the rest of this level.

## Reading the platform with SQL

You do not just build these layers, you operate them, and operating them means asking questions: what does each layer cost, which services are compute versus storage, where is the money going. Those questions are answered by querying a catalog of the platform itself. The exercises in this level do exactly that: you query a stand-in for each layer's own metadata, which is a real data-engineering skill (teams query cost-and-usage reports, storage inventories, and job logs with SQL every day).

**Interview nuance:** when an interviewer asks you to "describe a data platform," the five-layer storage / catalog / compute / orchestration / serving spine is a clean, senior-sounding answer, and naming the decoupling of storage from compute is the detail that signals you actually understand cloud economics.

> **On a real platform this differs.** Here you query one small \`platform_services\` table in SQLite. On AWS the same reasoning runs against the Cost and Usage Report (queried in Athena or loaded into a warehouse), where each row is a service, usage type, and cost. The query shape (group by a layer or service, sum the cost, sort) is identical.`,
    demoSeedSql: PLATFORM_SEED,
    demoCode: `-- The platform catalog: one row per service, tagged by the layer it belongs to.
SELECT service, layer, monthly_cost_usd
FROM platform_services
ORDER BY monthly_cost_usd DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-cloud-and-the-de-stack-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total monthly cost of each platform layer, as \`(layer, monthly_cost)\`, most expensive layer first, over \`platform_services(service, layer, monthly_cost_usd)\`.

Group the services by their \`layer\` and sum \`monthly_cost_usd\`. Alias the summed column exactly \`monthly_cost\`, ordered descending.`,
    starterCode: `-- Total monthly cost per platform layer, most expensive first.
SELECT
  -- group the services by layer and sum their cost
FROM platform_services;`,
    hints: [
      "Group by `layer` so each layer collapses to one row.",
      "`SUM(monthly_cost_usd) AS monthly_cost` is the per-layer total.",
      "Add `ORDER BY monthly_cost DESC` so the most expensive layer is first.",
    ],
    referenceSolution: `SELECT layer, SUM(monthly_cost_usd) AS monthly_cost
FROM platform_services
GROUP BY layer
ORDER BY monthly_cost DESC;`,
    singleFile: {
      seedSql: PLATFORM_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["layer", "monthly_cost"],
        rows: [
          ["compute", 6600],
          ["storage", 1200],
          ["serving", 570],
          ["orchestration", 400],
          ["catalog", 150],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-cloud-and-the-de-stack-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each platform layer running more than one service, with its service count and total monthly cost, as \`(layer, service_count, monthly_cost)\`, most expensive first, over the same \`platform_services\` table.

Keep only layers with more than one service. Alias the columns exactly \`service_count\` and \`monthly_cost\`, ordered by \`monthly_cost\` descending.`,
    starterCode: `-- Layers running more than one service: layer, service_count, monthly_cost.
SELECT
  -- group by layer, count services, sum cost, keep groups with COUNT(*) > 1
FROM platform_services;`,
    hints: [
      "Group by `layer`, then `COUNT(*) AS service_count` and `SUM(monthly_cost_usd) AS monthly_cost`.",
      "`HAVING COUNT(*) > 1` filters groups after aggregation (a plain `WHERE` cannot see the count).",
      "Order by `monthly_cost` descending.",
    ],
    singleFile: {
      seedSql: PLATFORM_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["layer", "service_count", "monthly_cost"],
        rows: [
          ["compute", 3, 6600],
          ["serving", 2, 570],
        ],
      },
    },
  },
}

const objectVsBlockStorage: SqlLesson = {
  id: "sql-l6-object-vs-block-storage",
  title: "Object vs Block vs File Storage, and Why the Lake Lives on S3",
  summary:
    "The three storage shapes every cloud offers (S3, EBS, EFS), the immutable-blob-over-HTTP object model, eleven-nines durability, and why a data lake is files in a bucket.",
  estimatedMinutes: 26,
  difficulty: "easy",
  skills: [
    "object storage",
    "block storage",
    "S3 durability vs availability",
    "data lake",
    "string functions",
    "GROUP BY",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Three ways to store bytes

Before you can reason about a data lake you need the three storage shapes every cloud offers, because interviewers ask for them by name and juniors mix them up constantly.

- **Block storage** is a raw virtual disk. You attach it to one machine, format a filesystem on it, and read or write any block in place, exactly like the SSD in a laptop. On AWS this is **Amazon EBS**. It is what a boot disk and a transactional database's files sit on, because a database needs to update a few kilobytes in the middle of a file, in place, with sub-millisecond latency.
- **File storage** is a shared folder many machines mount over a network protocol (NFS). On AWS this is **Amazon EFS**. Reach for it when many servers must read and write the same files at once.
- **Object storage** is a giant key-value store of whole files, reached over HTTP. On AWS this is **Amazon S3**, and it is where data lakes live.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["dimension", "block (EBS)", "object (S3)", "file (EFS)"],
  "rows": [
    ["access unit", "blocks of a raw disk", "whole object + key", "files in a folder"],
    ["addressed by", "device + offset", "key over HTTP", "path over NFS"],
    ["mutability", "edit any block in place", "replace the whole object", "edit files in place"],
    ["shared by", "one instance", "any number of readers", "many instances at once"],
    ["use it for", "boot disk, a database's files", "data lake, backups, logs", "shared files across machines"]
  ],
  "highlightCols": ["object (S3)"],
  "caption": "Block is a raw disk you format; file is a shared mount; object is whole files over HTTP. Lakes use object storage."
}
\`\`\`

## Why the lake lives on object storage

An object is a file plus its metadata, addressed by a **key** inside a **bucket**, for example the key \`raw/events/2026-01-02/part-0.parquet\`. You reach it with an HTTP GET or PUT, and every object has a URL. Three properties make this the natural home for a data lake:

- **It scales without limit and costs little.** A bucket holds any number of objects, and a single object can be up to 5 TB. You pay only for what you store, with no capacity to provision.
- **It is extremely durable.** S3 is designed to provide **eleven nines** of durability (99.999999999%) by storing every object redundantly across at least three Availability Zones. That is a design target for not losing data, and it is a different number from availability (99.99%, the chance you can reach it at a given moment). Mixing up durability and availability is the single most common junior mistake here.
- **Any engine can read the files.** Because objects are just files behind an HTTP key, Athena, Spark, and a warehouse can all read the same bucket. Storage is decoupled from compute.

The trade is that object storage is **not** a disk. You cannot edit an object in place: a write replaces the whole object (or, with versioning on, adds a new version). There is no "change these 8 bytes." That is fine for a lake, where you write files once and read them many times, and it is exactly why a live transactional database wants EBS, not S3.

One more property worth stating plainly: S3's namespace is **flat**. The slashes in a key only look like folders. \`raw/events/2026-01-02/\` is a **prefix** of the key, not a real directory, and console "folders" are a convenience the UI draws. This matters in the partitioning module, where a layout like \`dt=2026-01-02/\` is just a key prefix that a query engine filters on.

**Interview nuance:** "object versus block versus file, give an AWS example of each" is a near-guaranteed junior question. Answer with the access unit and mutability: block is a raw disk you format (EBS), file is a shared mount (EFS), object is whole files over HTTP that you replace rather than edit (S3), and the lake uses object storage for cheap, unlimited, engine-agnostic capacity.

> **On a real platform this differs.** Real S3 inventory comes from an S3 Inventory report (a daily or weekly file listing every object with its size, storage class, and last-modified date) that you query in Athena. The \`s3_inventory\` table you query here is a small stand-in with the same columns, so the query you write is the query you would run for real.`,
    demoSeedSql: S3_INVENTORY_SEED,
    demoCode: `-- The inventory: each object's size in GB and whether it has gone cold.
SELECT object_key,
       ROUND(size_bytes / 1000000000.0, 0) AS size_gb,
       CASE WHEN last_access_days > 90 THEN 'cold' ELSE 'hot' END AS access_state
FROM s3_inventory
ORDER BY size_bytes DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-object-vs-block-storage-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total bytes stored under each top-level prefix, as \`(prefix, total_bytes)\`, largest first, over \`s3_inventory(object_key, size_bytes, storage_class, last_access_days)\`.

The top-level prefix is the part of \`object_key\` before the first slash (for \`raw/events/...\` it is \`raw\`). Group by that prefix and sum \`size_bytes\`. Alias the columns exactly \`prefix\` and \`total_bytes\`, most bytes first.`,
    starterCode: `-- Total bytes per top-level key prefix, largest first.
SELECT
  -- the prefix is everything before the first '/'; group by it and sum size_bytes
FROM s3_inventory;`,
    hints: [
      "`instr(object_key, '/')` gives the position of the first slash; `substr(object_key, 1, instr(object_key, '/') - 1)` is the text before it.",
      "Group by that prefix expression and `SUM(size_bytes) AS total_bytes`.",
      "Order by `total_bytes` descending.",
    ],
    referenceSolution: `SELECT substr(object_key, 1, instr(object_key, '/') - 1) AS prefix,
       SUM(size_bytes) AS total_bytes
FROM s3_inventory
GROUP BY prefix
ORDER BY total_bytes DESC;`,
    singleFile: {
      seedSql: S3_INVENTORY_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["prefix", "total_bytes"],
        rows: [
          ["raw", 1600000000000],
          ["archive", 1000000000000],
          ["curated", 90000000000],
          ["exports", 50000000000],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-object-vs-block-storage-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every object not accessed in the last 90 days, as \`(object_key, size_bytes, last_access_days)\`, largest first, over the same \`s3_inventory\` table.

These are the cold objects a lifecycle policy would move to a cheaper storage class. Keep only rows where \`last_access_days\` is greater than 90, ordered by \`size_bytes\` descending.`,
    starterCode: `-- Cold objects (not accessed in over 90 days), largest first.
SELECT object_key, size_bytes, last_access_days
FROM s3_inventory
-- keep only objects older than 90 days and sort by size
;`,
    hints: [
      "Filter with `WHERE last_access_days > 90`.",
      "Order by `size_bytes DESC` so the biggest cold object (the best move candidate) is first.",
    ],
    singleFile: {
      seedSql: S3_INVENTORY_SEED,
      orderMatters: true,
      expected: {
        columns: ["object_key", "size_bytes", "last_access_days"],
        rows: [
          ["archive/2024/full.tar", 1000000000000, 800],
          ["raw/logs/2025-10-01/app.log", 600000000000, 260],
          ["raw/logs/2025-11-15/app.log", 400000000000, 210],
          ["raw/events/2025-08-01/part-0.parquet", 300000000000, 150],
        ],
      },
    },
  },
}

const storageClassesLifecycle: SqlLesson = {
  id: "sql-l6-storage-classes-lifecycle",
  title: "Storage Classes and Lifecycle: Paying Less for Colder Data",
  summary:
    "Hot, warm, cold, and archive tiers, the retrieval-latency and minimum-duration trade, lifecycle policies, and computing the bill (and the saving from a transition) with a join.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "S3 storage classes",
    "lifecycle policies",
    "cost modeling",
    "JOIN",
    "aggregation",
    "ROUND",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Hot, warm, cold, and archive

Not all data is read equally. Yesterday's events are queried constantly; last year's are touched once a quarter for a compliance check. Object storage gives you **storage classes** so you can pay less for colder data, trading away instant, free retrieval as the data gets colder. Every class is designed for the same eleven nines of durability. What changes is the price per gigabyte, the retrieval latency, and a minimum billing duration.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["storage class", "$/GB-month", "retrieval", "min duration", "use for"],
  "rows": [
    ["S3 Standard", "0.023", "instant (ms)", "none", "hot, active tables"],
    ["Standard-IA", "0.0125", "instant (ms)", "30 days", "rarely read, needs instant"],
    ["Glacier Instant Retrieval", "0.004", "instant (ms)", "90 days", "archive, rare but instant"],
    ["Glacier Deep Archive", "0.00099", "hours", "180 days", "once-a-year compliance"]
  ],
  "highlightCols": ["$/GB-month"],
  "caption": "Colder classes cost less per GB but add retrieval latency and a minimum billing duration. Illustrative US prices."
}
\`\`\`

The pattern to internalize:

- **S3 Standard** is for hot, frequently read data (your active lake and warehouse tables): highest per-GB price, instant retrieval, no minimum.
- **Standard-Infrequent Access (Standard-IA)** is for data you still need instantly but read rarely (backups, older-but-live tables): cheaper per GB, but it bills a **30-day minimum** and adds a per-GB retrieval fee.
- **Glacier Instant Retrieval** is archive priced, still milliseconds to read, with a **90-day minimum**.
- **Glacier Flexible Retrieval** and **Glacier Deep Archive** are the cheapest, but reads take minutes to hours, with **90-** and **180-day** minimums. Deep Archive is the "look at it once a year" compliance tier.

## Lifecycle policies do this for you

You do not move objects between classes by hand. An **S3 Lifecycle policy** is a set of rules that transition objects to a colder class after N days (Standard to Standard-IA at 30 days, to Glacier at 365) and eventually **expire** (delete) them. It is how a data engineer automates hot to cold to archive to gone without a cron job.

There is a real trap here, and it is a favorite interview follow-up: **moving cold data to a cheaper class does not always save money.** The infrequent and archive classes have minimum storage durations and per-GB retrieval fees, so transitioning tiny or short-lived objects, or objects you will actually read often, can cost more than leaving them in Standard. The saving is real only for large objects that genuinely sit cold.

## Doing the math with SQL

Cost is just arithmetic over the inventory: size in gigabytes times a per-GB price, summed. That is a join between the object inventory and a small price list, and it is exactly the kind of query a DE writes to justify a lifecycle change. The exercises here compute the current bill per class and the saving from a proposed transition.

**Interview nuance:** asked "you have 10 TB of logs you rarely read but must keep seven years, how do you store it cheaply," the answer is a lifecycle policy that transitions to Glacier Flexible or Deep Archive, and the senior detail is naming the retrieval-latency and minimum-duration trade rather than just saying "use Glacier."

> **On a real platform this differs.** Real per-GB prices vary by Region and change over time, and AWS bills a "GB" as a specific byte count. The \`storage_pricing\` table here uses round, illustrative US prices and treats 1 GB as 1,000,000,000 bytes so the arithmetic stays clean. The query shape (join inventory to price, sum, compare) is the real one.`,
    demoSeedSql: INVENTORY_AND_PRICING_SEED,
    demoCode: `-- Each object's own monthly storage cost: size in GB times its class price.
SELECT i.object_key, i.storage_class,
       ROUND(i.size_bytes / 1000000000.0, 0) AS size_gb,
       ROUND(i.size_bytes * p.usd_per_gb_month / 1000000000.0, 2) AS monthly_cost_usd
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class
ORDER BY monthly_cost_usd DESC;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l6-storage-classes-lifecycle-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total gigabytes and total monthly cost of each storage class, as \`(storage_class, total_gb, monthly_cost_usd)\`, most expensive first, over \`s3_inventory\` joined to \`storage_pricing(storage_class, usd_per_gb_month)\`.

Treat 1 GB as 1,000,000,000 bytes. Round \`total_gb\` and \`monthly_cost_usd\` to 2 decimals, and order by \`monthly_cost_usd\` descending.`,
    starterCode: `-- Total GB and monthly cost per storage class, most expensive first.
SELECT
  -- join inventory to pricing, group by storage class, sum GB and cost
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class;`,
    hints: [
      "Join `s3_inventory` to `storage_pricing` on `storage_class`.",
      "`SUM(size_bytes) / 1000000000.0` is total GB; `SUM(size_bytes * usd_per_gb_month) / 1000000000.0` is the cost (price stays inside the SUM so it is a per-object cost you then total).",
      "Group by `i.storage_class`, wrap both totals in `ROUND(..., 2)`, and order by `monthly_cost_usd DESC`.",
    ],
    referenceSolution: `SELECT i.storage_class,
       ROUND(SUM(i.size_bytes) / 1000000000.0, 2) AS total_gb,
       ROUND(SUM(i.size_bytes * p.usd_per_gb_month) / 1000000000.0, 2) AS monthly_cost_usd
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class
GROUP BY i.storage_class
ORDER BY monthly_cost_usd DESC;`,
    singleFile: {
      seedSql: INVENTORY_AND_PRICING_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["storage_class", "total_gb", "monthly_cost_usd"],
        rows: [
          ["STANDARD", 1140, 26.22],
          ["STANDARD_IA", 600, 7.5],
          ["GLACIER_DEEP", 1000, 0.99],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-storage-classes-lifecycle-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each cold STANDARD object, the monthly saving from moving it to Standard-IA, as \`(object_key, current_cost_usd, ia_cost_usd, monthly_saving_usd)\`, largest saving first, over the same \`s3_inventory\` table.

A cold object is in the \`STANDARD\` class with \`last_access_days\` greater than 90. Standard costs 0.023 per GB-month and Standard-IA costs 0.0125 per GB-month (1 GB = 1,000,000,000 bytes). Round every dollar column to 2 decimals, ordered by \`monthly_saving_usd\` descending.`,
    starterCode: `-- Saving from moving each cold STANDARD object to Standard-IA, largest first.
SELECT object_key
  -- current cost at 0.023/GB, IA cost at 0.0125/GB, and the difference
FROM s3_inventory
-- only STANDARD objects gone cold (> 90 days)
;`,
    hints: [
      "Filter with `WHERE storage_class = 'STANDARD' AND last_access_days > 90`.",
      "`size_bytes / 1000000000.0 * 0.023` is the current cost; swap 0.023 for 0.0125 for the IA cost.",
      "The saving is `size_bytes / 1000000000.0 * (0.023 - 0.0125)`; wrap each in `ROUND(..., 2)` and order by the saving descending.",
    ],
    singleFile: {
      seedSql: INVENTORY_AND_PRICING_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["object_key", "current_cost_usd", "ia_cost_usd", "monthly_saving_usd"],
        rows: [
          ["raw/logs/2025-11-15/app.log", 9.2, 5, 4.2],
          ["raw/events/2025-08-01/part-0.parquet", 6.9, 3.75, 3.15],
        ],
      },
    },
  },
}

const lakeWarehouseCatalog: SqlLesson = {
  id: "sql-l6-lake-warehouse-catalog",
  title: "Files Plus a Catalog Equals a Table: Lake, Warehouse, Lakehouse",
  summary:
    "How a pile of files in a bucket becomes a queryable table (the Hive metastore / Glue catalog), the lake vs warehouse vs lakehouse split, and auditing the catalog with SQL.",
  estimatedMinutes: 24,
  difficulty: "easy",
  skills: [
    "data catalog",
    "Hive metastore / Glue",
    "data lake vs warehouse vs lakehouse",
    "schema-on-read",
    "filtering",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Files in a bucket are not a table, yet

A folder of Parquet files in S3, say \`s3://lake/raw/events/\`, is just bytes. Nothing there knows it is an "events table," what columns it has, or their types. Two more pieces turn a pile of files into something you can run SQL against.

The first is a **catalog** (also called a metastore). It records, for each table, the column names and types, the partition columns, the file format, and the S3 location of the files. Add a catalog entry and the same pile of files becomes a queryable **table**. The two names to know are the **Hive metastore** (the original open-source standard) and the **AWS Glue Data Catalog** (AWS's managed, Hive-compatible version). A Glue **crawler** can even infer the schema from the files and fill the catalog in for you.

The second is a **query engine** that reads the catalog, then reads the files: **Amazon Athena** (serverless SQL), **Apache Spark**, or **Trino**. The engine looks up the table to learn "this prefix of Parquet files has these columns," then scans only the files it needs.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Files in S3", "note": "raw Parquet bytes" },
    { "label": "Catalog entry", "note": "columns, types, location" },
    { "label": "Query engine", "note": "Athena / Spark / Trino" },
    { "label": "SQL table", "note": "you can now SELECT from it" }
  ],
  "caption": "A pile of files plus a catalog entry becomes a table an engine can read. Storage, catalog, and compute stay separate."
}
\`\`\`

So the defining equation of the lake is: **a pile of files in a bucket, plus a catalog entry that gives them a schema, equals a table.**

## Lake, warehouse, lakehouse

Those files-plus-catalog tables make up a **data lake**: raw data in its native format on cheap object storage, structured only when you query it (schema-on-read). Cheap and flexible, but on its own a lake has no transactions and no easy row-level updates.

A **data warehouse** is the other end: a curated, structured, columnar, SQL-first store that you load conformed data into (schema-on-write). Amazon Redshift, Snowflake, and Google BigQuery are the three names to know. Warehouses are fast for BI and governed, at the cost of loading into their system.

A **lakehouse** is the newer middle: it layers warehouse features (ACID transactions, schema enforcement, time travel) onto open files on object storage, using an **open table format**. Apache Iceberg, Delta Lake, and Apache Hudi are the ones to recognize. The point is one copy of the data on the lake, with warehouse-grade guarantees on top.

## Auditing the catalog with SQL

The catalog is itself a set of tables you can query, and auditing it is real work: which tables are still stored as slow CSV instead of Parquet, which tables have no partitions and will full-scan, which database owns the most tables. The exercises here query a stand-in \`glue_catalog\` to answer exactly those questions.

**Interview nuance:** "how would you query a bunch of Parquet files in S3 with SQL, and where does the schema come from" is a direct junior question. The answer is Athena (or Spark or Trino) reading the file locations and column types from the Glue Data Catalog or a Hive metastore. "A table equals files plus a catalog entry" is the sentence that lands it.

> **On a real platform this differs.** The real Glue Data Catalog exposes this metadata through an API and through queryable \`information_schema\` views, with far more columns (serde, compression, per-column stats). The \`glue_catalog\` table here keeps the few columns that carry the lesson: database, table, location, format, and partition keys.`,
    demoSeedSql: GLUE_CATALOG_SEED,
    demoCode: `-- The catalog: each table's format and whether it declares partition keys.
SELECT db_name, table_name, file_format,
       CASE WHEN partition_keys = '' THEN 'no' ELSE 'yes' END AS partitioned
FROM glue_catalog
ORDER BY db_name, table_name;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-lake-warehouse-catalog-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every catalog table not stored as Parquet, as \`(db_name, table_name, file_format)\`, ordered by \`db_name\` then \`table_name\`, over \`glue_catalog(db_name, table_name, location, file_format, partition_keys)\`.

These are the tables a migration would convert to Parquet for cheaper, faster scans. Keep only rows whose \`file_format\` is not \`parquet\`.`,
    starterCode: `-- Catalog tables not yet stored as Parquet.
SELECT db_name, table_name, file_format
FROM glue_catalog
-- keep only non-parquet tables, ordered by db then table
;`,
    hints: [
      "Filter with `WHERE file_format <> 'parquet'`.",
      "Order by `db_name, table_name` so the list is stable.",
    ],
    referenceSolution: `SELECT db_name, table_name, file_format
FROM glue_catalog
WHERE file_format <> 'parquet'
ORDER BY db_name, table_name;`,
    singleFile: {
      seedSql: GLUE_CATALOG_SEED,
      orderMatters: true,
      expected: {
        columns: ["db_name", "table_name", "file_format"],
        rows: [
          ["analytics", "app_logs", "json"],
          ["finance", "invoices", "csv"],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-lake-warehouse-catalog-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every Parquet table that declares no partition keys, as \`(db_name, table_name)\`, ordered by \`db_name\` then \`table_name\`, over the same \`glue_catalog\` table.

A Parquet table with an empty \`partition_keys\` gets scanned in full by every query, so these are the tables to consider partitioning. Keep only rows where \`file_format\` is \`parquet\` and \`partition_keys\` is the empty string.`,
    starterCode: `-- Parquet tables with no partition keys (full-scan risk).
SELECT db_name, table_name
FROM glue_catalog
-- keep parquet tables whose partition_keys is empty
;`,
    hints: [
      "Two conditions joined with AND: `file_format = 'parquet'` and `partition_keys = ''`.",
      "Order by `db_name, table_name`.",
    ],
    singleFile: {
      seedSql: GLUE_CATALOG_SEED,
      orderMatters: true,
      expected: {
        columns: ["db_name", "table_name"],
        rows: [["finance", "fx_rates"]],
      },
    },
  },
}

// ---------------------------------------------------------------------------
// Shared simulated-catalog seeds for Module 6.2. `parquet_column_stats` = one row per
// column of a Parquet file with its uncompressed/compressed size; `row_group_stats` = one
// row per row group with its min/max of the sort column, the raw material of pushdown.
// ---------------------------------------------------------------------------

const PARQUET_COLUMN_STATS_SEED = `CREATE TABLE parquet_column_stats (
  column_name        TEXT,
  data_type          TEXT,
  uncompressed_bytes INTEGER,
  compressed_bytes   INTEGER
);
INSERT INTO parquet_column_stats (column_name, data_type, uncompressed_bytes, compressed_bytes) VALUES
  ('event_id',   'INT64',   80000000,  20000000),
  ('user_id',    'INT64',   80000000,  24000000),
  ('event_type', 'STRING',  200000000,  8000000),   -- low-cardinality, dictionary-encodes tiny
  ('country',    'STRING',  120000000,  3000000),   -- very low cardinality
  ('url',        'STRING',  500000000, 180000000),  -- high-cardinality, compresses poorly
  ('device',     'STRING',  100000000,  5000000),
  ('revenue',    'DOUBLE',   80000000, 40000000),
  ('ts',         'INT64',    80000000, 16000000);`

const ROW_GROUP_STATS_SEED = `CREATE TABLE row_group_stats (
  rg_id            INTEGER,
  row_count        INTEGER,
  min_order_id     INTEGER,   -- the file is sorted by order_id, so each row group
  max_order_id     INTEGER,   -- covers a tight, non-overlapping range
  compressed_bytes INTEGER
);
INSERT INTO row_group_stats (rg_id, row_count, min_order_id, max_order_id, compressed_bytes) VALUES
  (0, 100000,      1, 100000, 52000000),
  (1, 100000, 100001, 200000, 53000000),
  (2, 100000, 200001, 300000, 51000000),
  (3, 100000, 300001, 400000, 54000000),
  (4,  60000, 400001, 460000, 31000000);`

// ---------------------------------------------------------------------------
// Module 6.2 — File Formats: Why Columnar Wins
// ---------------------------------------------------------------------------

const rowsVsColumns: SqlLesson = {
  id: "sql-l6-rows-vs-columns",
  title: "Rows vs Columns on Disk, and Column Projection",
  summary:
    "Why a CSV is row-oriented and Parquet is column-oriented, and the first thing columnar buys you: a query reads only the columns it selects, not every byte of every row.",
  estimatedMinutes: 24,
  difficulty: "medium",
  skills: [
    "columnar storage",
    "Parquet",
    "column projection",
    "conditional aggregation",
    "bytes scanned",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## The same table, two ways on disk

A CSV or a JSON file is **row-oriented**: it writes all of row 1, then all of row 2, and so on. That is perfect when you want a whole row at a time, which is what an application database does. Analytics is the opposite. You scan millions of rows but touch only a few columns ("total revenue by country last month" reads 2 columns out of 40), so the row-oriented order forces you to read the whole table to answer a two-column question.

**Parquet** is **column-oriented**: it writes all of column A's values together, then all of column B's, and so on. Apache Parquet is the default file format of the data lake, and its columnar layout is the entire reason.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["aspect", "row store (CSV/JSON)", "column store (Parquet)"],
  "rows": [
    ["on-disk order", "all of row 1, then all of row 2", "all of column A, then all of column B"],
    ["a 2-of-8-column SELECT reads", "every column of every row", "only those 2 column chunks"],
    ["compression", "mixed types per row, compresses poorly", "like values together, compresses far better"],
    ["good for", "writing and fetching whole rows", "scanning a few columns over many rows"]
  ],
  "highlightCols": ["column store (Parquet)"],
  "caption": "Columnar stores each column together, so an analytic query reads only the columns it needs and compresses each one hard."
}
\`\`\`

## What columnar buys you (part 1: column projection)

The first and biggest win is **column projection** (also called column pruning). Because each column is stored as its own contiguous chunk, a query for two columns reads only those two chunks and physically skips the rest of the bytes. On a wide table this is enormous: selecting 2 columns out of 8 might read a few percent of the file, not all of it.

This is why \`SELECT *\` is a code smell on a lake. On a row store it costs the same as naming your columns; on a columnar store every extra column you select is more bytes read, and more money on an engine that charges by bytes scanned. Name the columns you need.

Parquet also stores the **schema and types inside the file** (in a footer), so a reader never has to guess whether a column is an integer or a string the way it must with CSV. You get typed, self-describing files for free.

## Measuring it with SQL

A Parquet file records, per column, how many bytes that column occupies. Reading those column statistics is how you predict what a query will scan and prove that projection pays off. The exercises here query a \`parquet_column_stats\` table (one row per column with its compressed size) and compute exactly how many bytes a two-column query reads versus the whole row.

**Interview nuance:** "why is Parquet faster than CSV for analytics" has two halves, and column projection is the first: a columnar file lets a query read only the columns it selects instead of every byte of every row. (The second half, compression, is the next lesson.) Saying both, and adding "and predicate pushdown skips row groups too," is a complete junior answer.

> **On a real platform this differs.** A real Parquet reader gets these per-column sizes from the file footer, and an engine like Athena reports "data scanned" per query. The \`parquet_column_stats\` table here is a small stand-in with one row per column, so the projection math you do is the math the engine does.`,
    demoSeedSql: PARQUET_COLUMN_STATS_SEED,
    demoCode: `-- Each column's footprint. Notice how few bytes the low-cardinality strings take.
SELECT column_name, data_type,
       ROUND(uncompressed_bytes / 1000000.0, 0) AS uncompressed_mb,
       ROUND(compressed_bytes / 1000000.0, 0) AS compressed_mb
FROM parquet_column_stats
ORDER BY compressed_bytes DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-rows-vs-columns-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns how many compressed bytes a \`SELECT event_type, country\` query reads and what percentage of the whole-row bytes that is, as \`(bytes_read, pct_of_full)\`, over \`parquet_column_stats(column_name, data_type, uncompressed_bytes, compressed_bytes)\`.

Sum \`compressed_bytes\` for just those two columns for \`bytes_read\`, and divide it by the sum over all columns for the percentage. Round \`pct_of_full\` to 2 decimals.`,
    starterCode: `-- Bytes a 2-column query reads, and its share of the full-row bytes.
SELECT
  -- sum compressed_bytes for event_type + country, and as a percent of the total
FROM parquet_column_stats;`,
    hints: [
      "`SUM(CASE WHEN column_name IN ('event_type','country') THEN compressed_bytes ELSE 0 END)` totals just the two projected columns.",
      "Divide that same conditional sum by `SUM(compressed_bytes)` (all columns) and multiply by 100.0 for the percentage.",
      "Alias the two output columns exactly `bytes_read` and `pct_of_full`, and wrap the percentage in `ROUND(..., 2)`.",
    ],
    referenceSolution: `SELECT
  SUM(CASE WHEN column_name IN ('event_type','country') THEN compressed_bytes ELSE 0 END) AS bytes_read,
  ROUND(100.0 * SUM(CASE WHEN column_name IN ('event_type','country') THEN compressed_bytes ELSE 0 END)
        / SUM(compressed_bytes), 2) AS pct_of_full
FROM parquet_column_stats;`,
    singleFile: {
      seedSql: PARQUET_COLUMN_STATS_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["bytes_read", "pct_of_full"],
        rows: [[11000000, 3.72]],
      },
    },
  },
  practice: {
    id: "sql-l6-rows-vs-columns-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each column's compressed size in MB and its share of the whole file, as \`(column_name, compressed_mb, pct_of_file)\`, largest share first, over the same \`parquet_column_stats\` table.

Treat 1 MB as 1,000,000 bytes. Round \`compressed_mb\` and \`pct_of_file\` to 2 decimals, ordered by \`pct_of_file\` descending.`,
    starterCode: `-- Each column's compressed MB and its percentage of the whole file.
SELECT column_name
  -- compressed_mb, and its share of the file total
FROM parquet_column_stats
ORDER BY pct_of_file DESC;`,
    hints: [
      "`compressed_bytes / 1000000.0` is the size in MB.",
      "The file total is a scalar subquery: `(SELECT SUM(compressed_bytes) FROM parquet_column_stats)`.",
      "`100.0 * compressed_bytes / (that subquery)` is the share; wrap both computed columns in `ROUND(..., 2)`.",
    ],
    singleFile: {
      seedSql: PARQUET_COLUMN_STATS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["column_name", "compressed_mb", "pct_of_file"],
        rows: [
          ["url", 180, 60.81],
          ["revenue", 40, 13.51],
          ["user_id", 24, 8.11],
          ["event_id", 20, 6.76],
          ["ts", 16, 5.41],
          ["event_type", 8, 2.7],
          ["device", 5, 1.69],
          ["country", 3, 1.01],
        ],
      },
    },
  },
}

const compressionEncoding: SqlLesson = {
  id: "sql-l6-compression-encoding",
  title: "Compression and Encoding: Why Columnar Shrinks So Much",
  summary:
    "Dictionary, run-length, delta, and bit-packing encodings plus a codec (Snappy, Zstd, Gzip) shrink a column far more than a row-interleaved CSV, and you can measure the ratio in SQL.",
  estimatedMinutes: 24,
  difficulty: "medium",
  skills: [
    "compression",
    "dictionary / RLE encoding",
    "Snappy / Zstd / Gzip",
    "aggregation",
    "cost reduction",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Why columnar compresses so much better

Storing a column together does more than let you skip columns: it makes the data **compress far better**, because a compressor works best on similar values sitting next to each other. A row store interleaves an integer id, a string country, and a float price on every row, so a general compressor sees noise. A column store hands the compressor a million \`country\` values in a row, and those are extremely repetitive.

Two layers of shrinking happen, in order.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["encoding", "what it does", "great for"],
  "rows": [
    ["dictionary", "store each distinct value once, rows point to it by id", "low-cardinality strings (country, event_type)"],
    ["run-length (RLE)", "store a repeated value once with a count", "long runs of one value (sorted or sparse columns)"],
    ["delta", "store the difference between consecutive values", "sorted numbers, timestamps, ids"],
    ["bit-packing", "use only as many bits as the values need", "small integers and dictionary ids"]
  ],
  "caption": "Column-local encodings shrink data first; a general codec (Snappy, Zstd, Gzip) then compresses the result further."
}
\`\`\`

First, Parquet applies **column-local encodings** that exploit structure:

- **Dictionary encoding** stores each distinct value once and replaces every row with a small integer id. A \`country\` column with 200 distinct values becomes a tiny dictionary plus a column of ids. This is why low-cardinality strings compress dramatically.
- **Run-length encoding (RLE)** stores a repeated value once with a count, which crushes sorted or sparse columns.
- **Delta encoding** stores the difference between consecutive values, ideal for sorted ids and timestamps.
- **Bit-packing** uses only as many bits as the values actually need.

Then, on top of the encoded column, Parquet applies a general **compression codec**. The three to know:

- **Snappy** is fast with a modest ratio, and it is the default in Spark, pandas, and PyArrow. (State this precisely: the Parquet Java library itself defaults to *uncompressed*; it is those engines that default to Snappy.)
- **Gzip** compresses smaller but slower.
- **Zstd** is the modern balance, often near Gzip's size at near Snappy's speed, and is increasingly the default choice.

The result is that data that would be a large CSV becomes a much smaller Parquet file, and because both storage and bytes-scanned cost money, that shrink is a direct cost saving.

## Measuring the shrink with SQL

Each column in \`parquet_column_stats\` records both its **uncompressed** and its **compressed** size, so the compression ratio is just one divided by the other. The exercises compute the ratio per column (watch the low-cardinality strings win and the high-cardinality URL lose) and the whole file's overall shrink.

**Interview nuance:** the second half of "why is Parquet faster and cheaper than CSV" is compression: columnar data groups like values, so dictionary and run-length encoding plus a codec like Snappy or Zstd shrink it far more than a row-interleaved CSV could. Naming an encoding (dictionary encoding for low-cardinality strings) is the detail that shows you understand *why*.

> **On a real platform this differs.** Real compression ratios depend on the data, the encodings the writer chose, and the codec. The \`parquet_column_stats\` numbers here are illustrative but shaped like reality: a low-cardinality \`country\` string compresses far harder than a high-cardinality \`url\`. The ratio query is the real one.`,
    demoSeedSql: PARQUET_COLUMN_STATS_SEED,
    demoCode: `-- Average compression ratio by data type: strings win because they dictionary-encode.
SELECT data_type,
       ROUND(SUM(uncompressed_bytes) * 1.0 / SUM(compressed_bytes), 2) AS ratio_by_type
FROM parquet_column_stats
GROUP BY data_type
ORDER BY ratio_by_type DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-compression-encoding-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each column's compression ratio (uncompressed divided by compressed), as \`(column_name, data_type, compression_ratio)\`, best-compressing first, over \`parquet_column_stats(column_name, data_type, uncompressed_bytes, compressed_bytes)\`.

Round \`compression_ratio\` to 2 decimals, ordered by it descending, so the columns that compress best are on top.`,
    starterCode: `-- Compression ratio per column, best first.
SELECT column_name, data_type
  -- uncompressed_bytes divided by compressed_bytes
FROM parquet_column_stats
ORDER BY compression_ratio DESC;`,
    hints: [
      "The ratio is `uncompressed_bytes * 1.0 / compressed_bytes` (the `* 1.0` forces real division, not integer).",
      "Alias it exactly `compression_ratio` and wrap it in `ROUND(..., 2)`.",
      "Order by `compression_ratio DESC`.",
    ],
    referenceSolution: `SELECT column_name, data_type,
       ROUND(uncompressed_bytes * 1.0 / compressed_bytes, 2) AS compression_ratio
FROM parquet_column_stats
ORDER BY compression_ratio DESC;`,
    singleFile: {
      seedSql: PARQUET_COLUMN_STATS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["column_name", "data_type", "compression_ratio"],
        rows: [
          ["country", "STRING", 40],
          ["event_type", "STRING", 25],
          ["device", "STRING", 20],
          ["ts", "INT64", 5],
          ["event_id", "INT64", 4],
          ["user_id", "INT64", 3.33],
          ["url", "STRING", 2.78],
          ["revenue", "DOUBLE", 2],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-compression-encoding-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the whole table's total uncompressed and compressed size in MB and its overall compression ratio, as \`(uncompressed_mb, compressed_mb, overall_ratio)\`, over the same \`parquet_column_stats\` table.

Treat 1 MB as 1,000,000 bytes. The overall ratio is total uncompressed divided by total compressed. Round every column to 2 decimals.`,
    starterCode: `-- Whole-file totals: uncompressed MB, compressed MB, and the overall shrink.
SELECT
  -- SUM the two byte columns into MB, and divide for the ratio
FROM parquet_column_stats;`,
    hints: [
      "`SUM(uncompressed_bytes) / 1000000.0` and `SUM(compressed_bytes) / 1000000.0` are the two totals in MB.",
      "The overall ratio is `SUM(uncompressed_bytes) * 1.0 / SUM(compressed_bytes)`.",
      "Alias the columns exactly `uncompressed_mb`, `compressed_mb`, `overall_ratio`, each wrapped in `ROUND(..., 2)`.",
    ],
    singleFile: {
      seedSql: PARQUET_COLUMN_STATS_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["uncompressed_mb", "compressed_mb", "overall_ratio"],
        rows: [[1240, 296, 4.19]],
      },
    },
  },
}

const rowGroupsPushdown: SqlLesson = {
  id: "sql-l6-row-groups-pushdown",
  title: "Row Groups and Predicate Pushdown, plus Parquet vs ORC vs Avro",
  summary:
    "Inside a Parquet file: row groups, the footer, and the min/max stats that let a filter skip whole row groups without reading them. Then when a row format (Avro) is the right call.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "row groups",
    "predicate pushdown",
    "min/max statistics",
    "Parquet vs ORC vs Avro",
    "conditional aggregation",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Inside a Parquet file: row groups and the footer

A Parquet file is not one undifferentiated blob. It is split into **row groups**, each holding a horizontal slice of the rows (a common default row-group size is 128 MB in the Parquet Java library, though the Apache docs recommend 512 MB to 1 GB, and engines tune it). Inside a row group, each column's values for those rows are stored together as a **column chunk**, and each chunk is split into **pages**. At the very end of the file sits the **footer**: the schema, and for every row group and every column, statistics including the **minimum, maximum, and null count**.

A reader opens the **footer first**, because the footer is the map. That map is what makes the next trick possible.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Open footer", "note": "schema + per-row-group stats" },
    { "label": "Check min/max", "note": "does this row group overlap the filter?" },
    { "label": "Skip non-overlapping", "note": "read none of its bytes" },
    { "label": "Read matching chunks", "note": "only the needed columns" }
  ],
  "caption": "A Parquet reader opens the footer, uses per-row-group min/max stats to skip whole groups, then reads only the needed column chunks."
}
\`\`\`

## What columnar buys you (part 3: predicate pushdown)

Because the footer records each row group's **min and max** for a column, a filter can skip entire row groups without reading their data. If a query says \`WHERE order_id BETWEEN 150000 AND 250000\` and a row group's stored range is 1 to 100000, its maximum (100000) is below the filter's floor, so the reader knows nothing in it can match and skips all of its bytes. This is **predicate pushdown**, and combined with partition pruning (the next module) it is how a query over a huge table reads only a sliver.

Pushdown works best when the data is **sorted or clustered** on the filter column, so each row group covers a tight, non-overlapping range. If every row group spans the whole range of values, no group can be skipped and the min/max stats buy you nothing.

## Parquet, ORC, and Avro

Parquet is not the only format, and interviews like to check that you know when a row format is right.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["format", "layout", "best for"],
  "rows": [
    ["Parquet", "columnar", "analytics scans, the lake default"],
    ["ORC", "columnar", "analytics in the Hive/Trino world, strong compression"],
    ["Avro", "row-oriented", "streaming/Kafka, row-by-row writes, schema evolution"]
  ],
  "highlightCols": ["format"],
  "caption": "Columnar (Parquet, ORC) for scan-heavy analytics; row-oriented (Avro) for streaming ingestion and whole-row writes."
}
\`\`\`

**Parquet** and **ORC** are both columnar and both great for analytics (ORC is strong in the Hive and Trino world). **Avro** is **row-oriented**: it stores whole records together, which is the wrong shape for scanning a few columns but the right shape for streaming ingestion, row-by-row writes, and schema evolution. A very common pipeline ingests events as Avro (cheap to append record by record from Kafka) and then **compacts** them into Parquet for the analysts to scan.

## Measuring pushdown with SQL

A row group's min and max are just columns you can filter on. The exercises query a \`row_group_stats\` table and compute how many row groups (and bytes) a range filter must read versus the whole file, which is exactly what predicate pushdown does under the hood.

**Interview nuance:** "how does a query skip data it does not need" is answered at two levels: **partition pruning** skips whole directories by the partition key, and **predicate pushdown** skips row groups inside a file by their min/max stats. Adding "and column projection skips columns you did not select" gives the complete picture of why a columnar lake query is cheap.

> **On a real platform this differs.** Real engines read these min/max stats from the Parquet footer (and per-page indexes) and decide row-group skipping automatically; you never write the skip logic. The \`row_group_stats\` table here exposes those stats as rows so you can compute the skip yourself and see what the engine sees.`,
    demoSeedSql: ROW_GROUP_STATS_SEED,
    demoCode: `-- For WHERE order_id BETWEEN 150000 AND 250000, which row groups does pushdown read?
SELECT rg_id, min_order_id, max_order_id,
       ROUND(compressed_bytes / 1000000.0, 0) AS mb,
       CASE WHEN max_order_id >= 150000 AND min_order_id <= 250000 THEN 'read' ELSE 'skip' END AS pushdown
FROM row_group_stats
ORDER BY rg_id;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-row-groups-pushdown-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns how many row groups a \`WHERE order_id BETWEEN 150000 AND 250000\` filter must read and their total compressed MB, as \`(row_groups_read, mb_read)\`, over \`row_group_stats(rg_id, row_count, min_order_id, max_order_id, compressed_bytes)\`.

A row group must be read when its stored \`[min_order_id, max_order_id]\` range overlaps \`[150000, 250000]\`. Treat 1 MB as 1,000,000 bytes and round \`mb_read\` to 2 decimals.`,
    starterCode: `-- Row groups (and MB) a range filter must read after pushdown.
SELECT
  -- count the overlapping row groups and sum their MB
FROM row_group_stats
-- a row group overlaps when its max is at or above the floor AND its min is at or below the ceiling
;`,
    hints: [
      "Two ranges [a,b] and [c,d] overlap when `b >= c AND a <= d`. Here: `max_order_id >= 150000 AND min_order_id <= 250000`.",
      "`COUNT(*)` over the filtered rows is `row_groups_read`.",
      "`ROUND(SUM(compressed_bytes) / 1000000.0, 2)` is `mb_read`.",
    ],
    referenceSolution: `SELECT COUNT(*) AS row_groups_read,
       ROUND(SUM(compressed_bytes) / 1000000.0, 2) AS mb_read
FROM row_group_stats
WHERE max_order_id >= 150000 AND min_order_id <= 250000;`,
    singleFile: {
      seedSql: ROW_GROUP_STATS_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["row_groups_read", "mb_read"],
        rows: [[2, 104]],
      },
    },
  },
  practice: {
    id: "sql-l6-row-groups-pushdown-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for the same \`order_id BETWEEN 150000 AND 250000\` filter, the compressed MB a pushdown-aware reader reads, the whole file's MB, and the percentage of bytes skipped, as \`(mb_read, mb_total, pct_skipped)\`, over the same \`row_group_stats\` table.

Read a row group only when its range overlaps the filter. Treat 1 MB as 1,000,000 bytes and round every column to 2 decimals.`,
    starterCode: `-- Pushdown savings: MB read vs total, and the percentage skipped.
SELECT
  -- conditional SUM for the overlapping row groups, plain SUM for the total, and the skipped percentage
FROM row_group_stats;`,
    hints: [
      "`SUM(CASE WHEN max_order_id >= 150000 AND min_order_id <= 250000 THEN compressed_bytes ELSE 0 END)` is the bytes read.",
      "`SUM(compressed_bytes)` is the file total; divide each by 1000000.0 for MB.",
      "`pct_skipped = 100.0 * (1 - bytes_read / total)`; build it from the same two sums and round to 2 decimals.",
    ],
    singleFile: {
      seedSql: ROW_GROUP_STATS_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["mb_read", "mb_total", "pct_skipped"],
        rows: [[104, 241, 56.85]],
      },
    },
  },
}

// ---------------------------------------------------------------------------
// Shared simulated-catalog seeds for Module 6.3. `partition_catalog` = one row per date
// partition (the raw material of pruning math); `partition_files` = file count + bytes per
// partition (the small-files problem); `user_buckets` = a hash-bucketed layout (skew).
// ---------------------------------------------------------------------------

const PARTITION_CATALOG_SEED = `CREATE TABLE partition_catalog (
  dt         TEXT,      -- the partition key value, folder dt=YYYY-MM-DD
  file_count INTEGER,
  size_bytes INTEGER,
  row_count  INTEGER
);
INSERT INTO partition_catalog (dt, file_count, size_bytes, row_count) VALUES
  ('2026-01-01', 4, 520000000, 5200000),
  ('2026-01-02', 4, 540000000, 5400000),
  ('2026-01-03', 5, 610000000, 6100000),
  ('2026-01-04', 4, 500000000, 5000000),
  ('2026-01-05', 6, 700000000, 7000000),
  ('2026-01-06', 4, 480000000, 4800000),
  ('2026-01-07', 5, 590000000, 5900000);`

const PARTITION_FILES_SEED = `CREATE TABLE partition_files (
  partition_key TEXT,
  file_count    INTEGER,
  total_bytes   INTEGER
);
INSERT INTO partition_files (partition_key, file_count, total_bytes) VALUES
  ('dt=2026-01-01', 4,   520000000),   -- 130 MB avg file, healthy
  ('dt=2026-01-02', 4,   540000000),   -- 135 MB avg file, healthy
  ('dt=2026-01-03', 40,   80000000),   -- 2 MB avg file, small-files problem
  ('dt=2026-01-04', 200, 100000000),   -- 0.5 MB avg file, severe small-files
  ('dt=2026-01-05', 3,   450000000);   -- 150 MB avg file, healthy`

const USER_BUCKETS_SEED = `CREATE TABLE user_buckets (
  bucket_id  INTEGER,   -- hash(user_id) % 8
  user_count INTEGER,
  size_bytes INTEGER
);
INSERT INTO user_buckets (bucket_id, user_count, size_bytes) VALUES
  (0, 125000,  310000000),
  (1, 130000,  320000000),
  (2, 120000,  305000000),
  (3, 128000,  315000000),
  (4, 122000,  300000000),
  (5, 131000,  322000000),
  (6, 119000,  298000000),
  (7, 900000, 1400000000);   -- a mega-user hashes here and skews the bucket`

// ---------------------------------------------------------------------------
// Module 6.3 — Partitioning a Large Table
// ---------------------------------------------------------------------------

const whatIsAPartition: SqlLesson = {
  id: "sql-l6-what-is-a-partition",
  title: "What a Partition Is, and Why Pruning Makes a Big Table Cheap",
  summary:
    "Hive-style dt=value folders put the partition key in the path, so a filter on it reads only the matching folders (pruning) and scans a fraction of the bytes, which on a pay-per-scan engine is directly cheaper.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "partitioning",
    "partition pruning",
    "bytes scanned",
    "conditional aggregation",
    "cost reduction",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## What a partition actually is

Partitioning splits one logical table into many folders, one per value of a **partition key**, and puts each folder's rows in its own files. The classic key is a date. On a lake the layout is literally directories named \`key=value\`:

\`\`\`text
s3://lake/events/
  dt=2026-01-01/   part-0.parquet  part-1.parquet
  dt=2026-01-02/   part-0.parquet  part-1.parquet
  dt=2026-01-03/   part-0.parquet  part-1.parquet  part-2.parquet
\`\`\`

The partition value lives in the **path**, not inside every row. A query engine reads the folder names from the catalog, so it knows which folders hold which dates before it opens a single file.

## Partition pruning: the whole point

When a query filters on the partition key, the engine reads only the matching folders and skips the rest. This is **partition pruning**. A \`WHERE dt = '2026-01-03'\` over a year of daily partitions opens 1 folder out of 365 and ignores the other 364. Because serverless engines charge by **bytes scanned** (Amazon Athena bills about 5 dollars per terabyte scanned), reading one partition instead of the whole table is not just faster, it is directly cheaper.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["partition", "size", "WHERE dt = '2026-01-03'"],
  "rows": [
    ["dt=2026-01-01", "520 MB", "skip"],
    ["dt=2026-01-02", "540 MB", "skip"],
    ["dt=2026-01-03", "610 MB", "read"],
    ["dt=2026-01-04", "500 MB", "skip"]
  ],
  "highlightCols": ["WHERE dt = '2026-01-03'"],
  "caption": "A filter on the partition key reads only the matching folder. The engine skips the rest without opening them."
}
\`\`\`

## Why you partition a large table

Four reasons, in order of how often they come up:

1. **Scan less data.** Prune to the partitions a query needs and read a fraction of the table. This is the big one.
2. **Match the common filter.** Almost every query on an events table filters by date, so partitioning by date makes almost every query cheap.
3. **Manage the lifecycle.** Dropping or expiring old data is a whole-folder operation: delete the \`dt=2025-01-01/\` partition, with no row-by-row delete.
4. **Parallelism.** Independent partitions are natural units of parallel work.

## Measuring pruning with SQL

A partition catalog records, per partition, its size and row count, so you can compute exactly how many bytes a pruning query scans versus a full scan. The exercises query a \`partition_catalog\` and compute the savings from filtering to one day and to a date range.

**Interview nuance:** asked "why would you partition this table," lead with pruning and cost: partitioning by the column you filter on most (usually date) lets the engine skip the partitions a query does not need, so it scans fewer bytes, runs faster, and on a pay-per-scan engine costs less.

> **On a real platform this differs.** A real engine prunes by reading partition metadata from the catalog (Glue) and never lists the skipped folders. The \`partition_catalog\` here exposes one row per partition so you can compute the pruned scan yourself; the arithmetic (sum the matching partitions, compare to the total) is what the engine's cost estimate does.`,
    demoSeedSql: PARTITION_CATALOG_SEED,
    demoCode: `-- For WHERE dt = '2026-01-03', which partitions does the engine scan vs prune?
SELECT dt, file_count,
       ROUND(size_bytes / 1000000.0, 0) AS size_mb,
       CASE WHEN dt = '2026-01-03' THEN 'scan' ELSE 'prune' END AS single_day_query
FROM partition_catalog
ORDER BY dt;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-what-is-a-partition-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the bytes a single-day query scans versus a full scan, and the percentage of bytes saved, as \`(partition_bytes, full_scan_bytes, pct_saved)\`, for \`dt = '2026-01-03'\` over \`partition_catalog(dt, file_count, size_bytes, row_count)\`.

\`partition_bytes\` is the size of just that day's partition; \`full_scan_bytes\` is the whole table. Round \`pct_saved\` to 2 decimals.`,
    starterCode: `-- Pruned single-day scan vs full scan, and the percentage saved.
SELECT
  -- bytes for dt = '2026-01-03', total bytes, and the percent saved
FROM partition_catalog;`,
    hints: [
      "`SUM(CASE WHEN dt = '2026-01-03' THEN size_bytes ELSE 0 END)` is the single partition's bytes.",
      "`SUM(size_bytes)` is the full-scan bytes.",
      "`pct_saved = 100.0 * (1 - partition_bytes / full_scan_bytes)`; build it from the same two sums and round to 2 decimals.",
    ],
    referenceSolution: `SELECT
  SUM(CASE WHEN dt = '2026-01-03' THEN size_bytes ELSE 0 END) AS partition_bytes,
  SUM(size_bytes) AS full_scan_bytes,
  ROUND(100.0 * (1 - 1.0 * SUM(CASE WHEN dt = '2026-01-03' THEN size_bytes ELSE 0 END) / SUM(size_bytes)), 2) AS pct_saved
FROM partition_catalog;`,
    singleFile: {
      seedSql: PARTITION_CATALOG_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["partition_bytes", "full_scan_bytes", "pct_saved"],
        rows: [[610000000, 3940000000, 84.52]],
      },
    },
  },
  practice: {
    id: "sql-l6-what-is-a-partition-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns how many partitions and bytes a \`WHERE dt BETWEEN '2026-01-02' AND '2026-01-04'\` query scans, and the percentage of the table it skips, as \`(partitions_scanned, bytes_scanned, pct_skipped)\`, over the same \`partition_catalog\` table.

Count and sum only the partitions in the date range, and compare their bytes to the whole table. Round \`pct_skipped\` to 2 decimals.`,
    starterCode: `-- A 3-day range scan: partitions read, bytes read, and percent skipped.
SELECT
  -- COUNT and SUM the in-range partitions; compare to the table total for pct_skipped
FROM partition_catalog
-- keep only the partitions in the date range
;`,
    hints: [
      "Filter with `WHERE dt BETWEEN '2026-01-02' AND '2026-01-04'` (string dates compare correctly in YYYY-MM-DD form).",
      "`COUNT(*)` and `SUM(size_bytes)` over the filtered rows are `partitions_scanned` and `bytes_scanned`.",
      "For `pct_skipped`, divide the scanned bytes by the whole-table total from a subquery: `(SELECT SUM(size_bytes) FROM partition_catalog)`.",
    ],
    singleFile: {
      seedSql: PARTITION_CATALOG_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["partitions_scanned", "bytes_scanned", "pct_skipped"],
        rows: [[3, 1650000000, 58.12]],
      },
    },
  },
}

const choosingPartitionKey: SqlLesson = {
  id: "sql-l6-choosing-partition-key",
  title: "Choosing a Partition Key, and the Small-Files Problem",
  summary:
    "Partition on the low-cardinality column you filter on (usually date). Partition on a high-cardinality key and you shred the table into millions of tiny files, where per-file overhead dominates.",
  estimatedMinutes: 25,
  difficulty: "medium",
  skills: [
    "partition key selection",
    "cardinality",
    "small-files problem",
    "over-partitioning",
    "conditional aggregation",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Choosing the partition key is the real skill

Partitioning is easy to do and easy to do badly. The interview question is never "can you partition," it is "what would you partition on, and what goes wrong if you choose wrong." Three rules cover most of it.

**Rule 1: partition on the column you filter by, at low-to-moderate cardinality.** The whole payoff is pruning, and you only prune on the partition key, so partition on what queries actually filter on. That is almost always a **date** (\`dt\`), sometimes a region or a category. A date has naturally low cardinality (365 values a year) and matches how analysts slice data.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["candidate key", "cardinality", "result"],
  "rows": [
    ["dt (date)", "low (365 per year)", "great: matches the common filter, healthy file sizes"],
    ["country", "low", "good: prunes region queries"],
    ["user_id", "very high", "bad: millions of tiny partitions, small-files problem"],
    ["event_id", "unique", "terrible: one partition per row"]
  ],
  "highlightCols": ["result"],
  "caption": "Partition on a low-cardinality column you filter on. High-cardinality keys shred the table into tiny files."
}
\`\`\`

**Rule 2: avoid the small-files problem.** Partition on a high-cardinality column like \`user_id\` and you get a huge number of tiny partitions, each with tiny files. This is pathological, because every file carries fixed overhead: the engine opens it, reads its footer, and tracks its metadata, and object stores start refusing requests when you hammer them (S3 returns "please reduce your request rate"). AWS measured reading 100,000 small files taking 11.5 seconds against 4.3 seconds for the same data in one file. The rule of thumb is to aim for files around **128 MB**, not kilobytes. Many small files are slower than a few big ones, even for the same total bytes.

**Rule 3: do not over-partition.** Partitioning on a column you rarely filter on, or one with thousands of values, multiplies partition metadata and shreds your files without buying any pruning. If a would-be key is high cardinality, partition coarser (by month instead of day, or by a bucket of the value) or bucket it instead (next lesson).

## Spotting the problem with SQL

A partition catalog that records each partition's file count and total bytes lets you compute the average file size and flag the partitions suffering the small-files problem. The exercises do exactly that: find the partitions whose average file is far below the 128 MB target, and measure how many excess tiny files they add.

**Interview nuance:** "you have millions of tiny files and queries are slow, what happened" is a classic. The answer is over-partitioning on a high-cardinality key: too many partitions means too many tiny files, and per-file overhead plus metadata dominate. The fix is a coarser partition key (or bucketing) and compaction into roughly 128 MB files.

> **On a real platform this differs.** Real engines expose file counts and sizes through catalog stats or a storage inventory, and compaction jobs (or Iceberg and Delta "optimize") merge small files for you. The \`partition_files\` table here gives you the file count and bytes per partition so you can compute the average file size the same way an audit query would.`,
    demoSeedSql: PARTITION_FILES_SEED,
    demoCode: `-- A one-row overview: how many partitions, and how many have the small-files problem.
SELECT COUNT(*) AS partitions,
       SUM(CASE WHEN total_bytes * 1.0 / file_count < 128000000 THEN 1 ELSE 0 END) AS small_file_partitions,
       SUM(file_count) AS total_files
FROM partition_files;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l6-choosing-partition-key-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each partition's average file size in MB and a health flag, as \`(partition_key, file_count, avg_file_mb, health)\`, worst (smallest average file) first, over \`partition_files(partition_key, file_count, total_bytes)\`.

The average file size is total bytes divided by file count (treat 1 MB as 1,000,000 bytes). \`health\` is \`'small-files'\` when the average file is under 128 MB and \`'ok'\` otherwise. Round \`avg_file_mb\` to 2 decimals, ordered by it ascending.`,
    starterCode: `-- Average file size per partition, flagging the small-files problem.
SELECT partition_key, file_count
  -- avg file size in MB, and a 'small-files' / 'ok' health flag
FROM partition_files
ORDER BY avg_file_mb ASC;`,
    hints: [
      "Average file size in bytes is `total_bytes * 1.0 / file_count`; divide by 1000000.0 for MB.",
      "`CASE WHEN total_bytes * 1.0 / file_count < 128000000 THEN 'small-files' ELSE 'ok' END AS health`.",
      "Alias the size column `avg_file_mb`, round it to 2 decimals, and order by it ascending so the worst is first.",
    ],
    referenceSolution: `SELECT partition_key, file_count,
       ROUND(total_bytes * 1.0 / file_count / 1000000.0, 2) AS avg_file_mb,
       CASE WHEN total_bytes * 1.0 / file_count < 128000000 THEN 'small-files' ELSE 'ok' END AS health
FROM partition_files
ORDER BY avg_file_mb ASC;`,
    singleFile: {
      seedSql: PARTITION_FILES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["partition_key", "file_count", "avg_file_mb", "health"],
        rows: [
          ["dt=2026-01-04", 200, 0.5, "small-files"],
          ["dt=2026-01-03", 40, 2, "small-files"],
          ["dt=2026-01-01", 4, 130, "ok"],
          ["dt=2026-01-02", 4, 135, "ok"],
          ["dt=2026-01-05", 3, 150, "ok"],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-choosing-partition-key-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns only the partitions suffering the small-files problem, with how many files they carry beyond a healthy 4-file target, as \`(partition_key, file_count, excess_files)\`, most excess first, over the same \`partition_files\` table.

A partition has the problem when its average file (total bytes divided by file count) is under 128 MB. \`excess_files\` is its file count minus 4. Order by \`excess_files\` descending.`,
    starterCode: `-- Small-files partitions and how many excess files each carries over a 4-file target.
SELECT partition_key, file_count
  -- excess_files = file_count - 4
FROM partition_files
-- keep only partitions whose average file is under 128 MB
ORDER BY excess_files DESC;`,
    hints: [
      "Filter with `WHERE total_bytes * 1.0 / file_count < 128000000`.",
      "`file_count - 4 AS excess_files`.",
      "Order by `excess_files DESC`.",
    ],
    singleFile: {
      seedSql: PARTITION_FILES_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["partition_key", "file_count", "excess_files"],
        rows: [
          ["dt=2026-01-04", 200, 196],
          ["dt=2026-01-03", 40, 36],
        ],
      },
    },
  },
}

const bucketingAndFullScanTrap: SqlLesson = {
  id: "sql-l6-bucketing-and-the-full-scan-trap",
  title: "Bucketing vs Partitioning, and the Full-Scan Trap",
  summary:
    "Bucket (or cluster) a high-cardinality join column into a fixed number of files instead of partitioning it, and keep the partition key bare in a filter so the engine can actually prune.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "bucketing / clustering",
    "partition vs bucket",
    "data skew",
    "sargable predicates",
    "full-scan trap",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Bucketing: partitioning's high-cardinality cousin

Some columns you want to organize by are exactly the ones you must not partition on: \`user_id\`, \`session_id\`, a hash. They are high cardinality, so partitioning explodes into tiny files. **Bucketing** (Spark and Hive) or **clustering** (Snowflake, BigQuery) solves this. Instead of one folder per value, you hash the column into a **fixed** number of buckets, say 8 or 256, and every row lands in one bucket by its hash. You get organization for joins and aggregations without the file explosion, because the number of files is capped no matter how many distinct values there are.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["technique", "key type", "how many files", "use for"],
  "rows": [
    ["partitioning", "low-cardinality (dt)", "one folder per value", "the column you filter on"],
    ["bucketing / clustering", "high-cardinality (user_id)", "a fixed number of buckets", "the column you join or group on"]
  ],
  "highlightCols": ["technique"],
  "caption": "Partition by the low-cardinality column you filter on; bucket by the high-cardinality column you join on. A table can do both."
}
\`\`\`

The teaching rule: **partition by the low-cardinality column you filter on; bucket (or cluster) by the high-cardinality column you join or group on.** A table can do both: partition by \`dt\`, bucket by \`user_id\`.

Bucketing only helps when the hash spreads evenly. A single mega-key (one user with a huge share of the rows) hashes entirely into one bucket and makes it far larger than the others, which reintroduces the skew you were trying to avoid. The exercises measure exactly this by comparing the largest bucket to the average.

## The full-scan trap

Pruning only happens when the engine can match your filter to the partition key, and it is easy to accidentally defeat it. Two classic mistakes:

- **Filtering on a non-partition column.** If the table is partitioned by \`dt\` but you filter only on \`user_id\`, nothing prunes and the engine scans every partition.
- **Wrapping the partition key in a function.** Comparing a **bare partition column to a constant** (\`WHERE dt = '2026-01-05'\`) prunes. Transforming the column first (a computed or dynamic expression on \`dt\`) can stop the engine from pruning, so it reads the whole table. The portable rule is to keep the partition column bare on one side and a constant on the other.

The cost of the trap is total: a query that should read one partition ends up reading all of them. The exercises put a number on it by comparing a pruning query's bytes to a full scan.

**Interview nuance:** "you partitioned by date but the query still scans everything, why" almost always means the filter did not land on the bare partition key: it filtered a different column, or wrapped \`dt\` in a function. Keep the partition column bare and compared to a constant.

> **On a real platform this differs.** Modern table formats reduce these traps: Apache Iceberg supports **hidden partitioning** (you query \`event_time\` and Iceberg derives the \`day(event_time)\` partition for you) and **partition evolution** (change the scheme as a metadata-only operation, with no data rewrite). The bucketing and pruning arithmetic you compute here is the same reasoning those systems automate.`,
    demoSeedSql: USER_BUCKETS_SEED,
    demoCode: `-- The bucket layout, largest first. A balanced hash keeps buckets close in size.
SELECT bucket_id, user_count,
       ROUND(size_bytes / 1000000.0, 0) AS size_mb
FROM user_buckets
ORDER BY size_bytes DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-bucketing-and-the-full-scan-trap-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns how balanced a bucketed layout is, as \`(bucket_count, avg_mb, max_mb, skew_ratio)\`, over \`user_buckets(bucket_id, user_count, size_bytes)\`.

\`skew_ratio\` is the largest bucket size divided by the average bucket size (a balanced hash gives a ratio near 1; a mega-key pushes it up). Treat 1 MB as 1,000,000 bytes and round \`avg_mb\`, \`max_mb\`, and \`skew_ratio\` to 2 decimals.`,
    starterCode: `-- How balanced are the buckets? count, average MB, largest MB, and the skew ratio.
SELECT
  -- COUNT the buckets, AVG and MAX their size, and divide MAX by AVG for the skew
FROM user_buckets;`,
    hints: [
      "`COUNT(*)` is `bucket_count`; `AVG(size_bytes)` and `MAX(size_bytes)` are the average and largest bucket in bytes.",
      "Divide each by 1000000.0 for MB.",
      "`skew_ratio = MAX(size_bytes) * 1.0 / AVG(size_bytes)`; round every computed column to 2 decimals.",
    ],
    referenceSolution: `SELECT COUNT(*) AS bucket_count,
       ROUND(AVG(size_bytes) / 1000000.0, 2) AS avg_mb,
       ROUND(MAX(size_bytes) / 1000000.0, 2) AS max_mb,
       ROUND(MAX(size_bytes) * 1.0 / AVG(size_bytes), 2) AS skew_ratio
FROM user_buckets;`,
    singleFile: {
      seedSql: USER_BUCKETS_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["bucket_count", "avg_mb", "max_mb", "skew_ratio"],
        rows: [[8, 446.25, 1400, 3.14]],
      },
    },
  },
  practice: {
    id: "sql-l6-bucketing-and-the-full-scan-trap-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the bytes a partition-pruning query scans when it filters \`dt = '2026-01-05'\`, versus a query that cannot prune and scans the whole table, and how many times more bytes the full scan reads, as \`(pruned_bytes, full_scan_bytes, scan_multiplier)\`, over \`partition_catalog(dt, file_count, size_bytes, row_count)\`.

\`pruned_bytes\` is that one day's partition; \`full_scan_bytes\` is the whole table; \`scan_multiplier\` is full divided by pruned. Round \`scan_multiplier\` to 2 decimals.`,
    starterCode: `-- The cost of the full-scan trap: pruned bytes vs a whole-table scan.
SELECT
  -- bytes for dt = '2026-01-05', total bytes, and full / pruned
FROM partition_catalog;`,
    hints: [
      "`SUM(CASE WHEN dt = '2026-01-05' THEN size_bytes ELSE 0 END)` is the pruned bytes; `SUM(size_bytes)` is the full scan.",
      "`scan_multiplier = SUM(size_bytes) * 1.0 / pruned_bytes` (full divided by pruned).",
      "Round `scan_multiplier` to 2 decimals.",
    ],
    singleFile: {
      seedSql: PARTITION_CATALOG_SEED,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["pruned_bytes", "full_scan_bytes", "scan_multiplier"],
        rows: [[700000000, 3940000000, 5.63]],
      },
    },
  },
}

export const sqlLevel6: SqlLevel = {
  id: 6,
  slug: "cloud-data-foundations",
  title: "Level 6: Cloud & Data Engineering Foundations",
  tagline:
    "Learn the platform your SQL runs on: object storage, columnar files, partitioning, and distributed pipelines, the way a DE interview asks about them.",
  defaultExecutionMode: "single-file",
  estimatedHours: 7,
  modules: [
    {
      id: "sql-l6-cloud-platform",
      title: "Module 6.1: The Cloud Data Platform",
      description:
        "What the cloud is and how a data platform is shaped: regions and managed services, object vs block vs file storage, storage classes and lifecycle, and the files-plus-catalog-equals-a-table idea, all queried as platform metadata.",
      lessons: [
        cloudAndTheDeStack,
        objectVsBlockStorage,
        storageClassesLifecycle,
        lakeWarehouseCatalog,
      ],
    },
    {
      id: "sql-l6-file-formats",
      title: "Module 6.2: File Formats — Why Columnar Wins",
      description:
        "Why Parquet beats CSV for analytics: column projection reads only the columns you select, columnar compression and encodings shrink each column hard, and row-group min/max stats let predicate pushdown skip data unread. Plus when a row format (Avro) is the right call.",
      lessons: [rowsVsColumns, compressionEncoding, rowGroupsPushdown],
    },
    {
      id: "sql-l6-partitioning",
      title: "Module 6.3: Partitioning a Large Table",
      description:
        "The single most-asked 'make a big table fast and cheap' topic: how dt=value partition folders let a filter prune to a fraction of the data, how to choose the partition key without shredding the table into tiny files, and how bucketing and the full-scan trap fit in.",
      lessons: [whatIsAPartition, choosingPartitionKey, bucketingAndFullScanTrap],
    },
  ],
}
