/**
 * SQL curriculum Level 5 — Advanced & Company-Specific SQL for DE Interviews.
 *
 * The Pareto ~8h capstone on top of L1-L4, structured as the four rounds of a Data Engineering
 * interview loop: the live SQL power screen (5.1), the warehouse/modeling round (5.2), the
 * streaming/pipeline round (5.3), and the system-design round (5.4). See
 * docs/sql-curriculum/expand-sql-de.md for the full plan and the interview-level triage
 * (Module 5.1 = intern-core; 5.2 mixed; 5.3/5.4 junior-to-senior).
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * sql.js (SQLite 3.49.1) WASM the app ships, never hand-typed. Warehouse-only constructs
 * (QUALIFY, MERGE, LATERAL FLATTEN, ...) are taught in a callout and emulated with the SQLite
 * feature that stands in for them, so every lesson is a real graded exercise.
 */
import type { SqlLevel } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Module 5.1 — Round 1: The Advanced SQL Power Round (all Intern-core)
// ---------------------------------------------------------------------------

const gapsAndIslands: SqlLesson = {
  id: "sql-l5-gaps-and-islands",
  title: "Gaps and Islands: Consecutive Streaks and Run Detection",
  summary:
    "The most-failed pattern on the live SQL screen: find consecutive runs and the breaks between them with the row-number-difference template.",
  estimatedMinutes: 42,
  difficulty: "hard",
  skills: [
    "product-analytics",
    "ROW_NUMBER",
    "gaps-and-islands",
    "streak detection",
    "date arithmetic",
    "GROUP BY on a derived key",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## The most-failed pattern on the SQL screen

Gaps and islands is repeatedly named the single most-failed pattern on a live Data Engineering SQL screen. The task always has the same shape: find the consecutive runs (the "islands") in a sequence and the breaks (the "gaps") between them. Longest login streak, consecutive days a metric held, unbroken spans where a price never moved, back-to-back on-call shifts: all one technique. Learn this one template and you have handled a large slice of the analytics questions an interviewer can hand you.

## The four-step template

Work on \`daily_logins(user_id, login_date)\`. The whole trick is to build a key that stays **constant across a run** and **changes the moment the run breaks**, then group on it.

1. **Number each user's rows in date order.** \`ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date)\` gives 1, 2, 3, ... down each user's logins.
2. **Subtract the row number from the date.** Inside a run of consecutive days the date climbs by one each row and so does the row number, so \`date minus row_number\` lands on the **same anchor date** for every row in that run. A gap makes the date jump ahead of the row number, so the anchor shifts to a new value. In SQLite: \`date(login_date, '-' || rn || ' days')\`.
3. **Group by user and anchor.** Each \`(user_id, anchor)\` pair is exactly one island. \`MIN(login_date)\` is its start, \`MAX(login_date)\` its end, and \`COUNT(*)\` its length.
4. **Aggregate the islands.** \`MAX(length)\` per user is the longest streak; a filter on the run start or length answers "which spans".

The demo below (turn on the input panel) materializes the anchor next to each date so you can watch it hold steady inside a run and jump right after the gap.

## The LAG variant

The same islands fall out of \`LAG\`: a new island starts wherever the previous row is **not** the day before. Flag a boundary with \`prev_date IS NULL OR prev_date < date(login_date, '-1 day')\`, then take a running \`SUM\` of that flag as the island id. Both forms are correct. The row-number-difference form is shorter to write under pressure; the LAG form reads more obviously to a reviewer.

## Where this shows up

Streaks, consecutive purchases, unchanged-price spans, subscription-state runs, uptime windows: whenever the prompt says "consecutive", "in a row", "unbroken", or "back to back", reach for this template.

**Interview nuance:** the row-number-difference trick assumes one row per unit (one row per day here). If a user can appear twice on the same day, deduplicate to distinct dates first with \`SELECT DISTINCT user_id, login_date\`, or the doubled row numbers will fracture a real run into false gaps.

> **In the warehouse this differs.** The shape is identical everywhere; only the date math changes. SQLite uses \`date(d, '+1 day')\` and \`julianday()\` differences, while Snowflake and BigQuery use \`DATEADD\`/\`DATE_ADD\` and \`DATEDIFF\`/\`DATE_DIFF\`. In Snowflake, BigQuery, and Databricks you can also wrap the final streak filter in a \`QUALIFY\` clause instead of a subquery; SQLite has no \`QUALIFY\`, so you filter in an outer query.`,
    demoSeedSql: `CREATE TABLE daily_logins (user_id INTEGER, login_date TEXT);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'),
  (1, '2026-03-02'),
  (1, '2026-03-03'),   -- run of three
  (1, '2026-03-05'),   -- gap on 03-04 starts a new run
  (1, '2026-03-06');`,
    demoCode: `-- The anchor stays constant inside a run and jumps after the gap.
SELECT user_id, login_date, rn,
       date(login_date, '-' || rn || ' days') AS island_anchor
FROM (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
ORDER BY user_id, login_date;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-gaps-and-islands-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each user's **longest consecutive-day login streak** as \`(user_id, streak_length)\`, over \`daily_logins(user_id, login_date)\`.

Use the row-number-difference template: number each user's logins in date order, subtract the row number from the date to get a per-run anchor, group by \`(user_id, anchor)\` to size each run, then keep the longest run per user. Alias the columns exactly \`user_id\` and \`streak_length\`.`,
    starterCode: `-- Longest consecutive-day login streak per user.
WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
SELECT
  -- group by the (user_id, anchor) run, size it, then take the max per user
FROM numbered;`,
    hints: [
      "The anchor is `date(login_date, '-' || rn || ' days')`. Every row in one consecutive run collapses to the same anchor date.",
      "Group by `user_id` and the anchor, and `COUNT(*)` is that run's length. Do this in a CTE.",
      "Then `SELECT user_id, MAX(run_length) AS streak_length ... GROUP BY user_id` over that CTE.",
    ],
    referenceSolution: `WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
),
islands AS (
  SELECT user_id,
         date(login_date, '-' || rn || ' days') AS anchor,
         COUNT(*) AS streak_length
  FROM numbered
  GROUP BY user_id, anchor
)
SELECT user_id, MAX(streak_length) AS streak_length
FROM islands
GROUP BY user_id;`,
    singleFile: {
      seedSql: `CREATE TABLE daily_logins (
  user_id    INTEGER,
  login_date TEXT      -- 'YYYY-MM-DD'
);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'), (1, '2026-03-02'), (1, '2026-03-03'), (1, '2026-03-05'), (1, '2026-03-06'),
  (2, '2026-03-01'), (2, '2026-03-02'), (2, '2026-03-04'), (2, '2026-03-05'), (2, '2026-03-06'), (2, '2026-03-07'),
  (3, '2026-03-10');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["user_id", "streak_length"],
        rows: [
          [1, 3],
          [2, 4],
          [3, 1],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-gaps-and-islands-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each product, the date ranges during which its price stayed **unchanged**, as \`(product_id, price, valid_from, valid_to)\`, over \`price_history(product_id, price, effective_date)\`.

Each row is one contiguous span at a single price. If a product returns to an earlier price after changing away and back, that is a **separate** span. Alias the columns exactly \`product_id\`, \`price\`, \`valid_from\`, \`valid_to\`.`,
    starterCode: `-- One row per unbroken price span: product_id, price, valid_from, valid_to.
WITH numbered AS (
  SELECT product_id, price, effective_date,
         ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY effective_date) AS rn_all,
         ROW_NUMBER() OVER (PARTITION BY product_id, price ORDER BY effective_date) AS rn_price
  FROM price_history
)
SELECT
  -- group each contiguous same-price run and take its first/last effective_date
FROM numbered;`,
    hints: [
      "Two row numbers: one over all of a product's rows in date order, one restarted per price. Their difference is constant inside a same-price run.",
      "Group by `product_id`, `price`, and `(rn_all - rn_price)`. That third key separates a price that recurs later into its own span.",
      "`MIN(effective_date)` is `valid_from`, `MAX(effective_date)` is `valid_to` within each group.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE price_history (
  product_id     INTEGER,
  price          INTEGER,
  effective_date TEXT
);
INSERT INTO price_history (product_id, price, effective_date) VALUES
  (10, 100, '2026-01-01'), (10, 100, '2026-01-02'), (10, 100, '2026-01-03'),
  (10, 120, '2026-01-04'), (10, 120, '2026-01-05'),
  (20,  50, '2026-01-01'), (20,  60, '2026-01-02'), (20,  50, '2026-01-03');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["product_id", "price", "valid_from", "valid_to"],
        rows: [
          [10, 100, "2026-01-01", "2026-01-03"],
          [10, 120, "2026-01-04", "2026-01-05"],
          [20, 50, "2026-01-01", "2026-01-01"],
          [20, 60, "2026-01-02", "2026-01-02"],
          [20, 50, "2026-01-03", "2026-01-03"],
        ],
      },
    },
  },
}

const sessionization: SqlLesson = {
  id: "sql-l5-sessionization",
  title: "Sessionization: Grouping Events with an Inactivity Timeout",
  summary:
    "Stamp each event with the session it belongs to: LAG the gap, flag a new session past the timeout, running-sum the flag into a session id.",
  estimatedMinutes: 36,
  difficulty: "hard",
  skills: [
    "streaming",
    "LAG",
    "cumulative-sum flag",
    "event-time windowing",
    "sessionization",
    "session_id assignment",
  ],
  teach: {
    estimatedMinutes: 11,
    markdown: `## What a session is, and why you build one

Raw event logs have no notion of a "visit". You get a stream of \`(user_id, event_ts)\` rows, and the analytics questions all assume sessions: how long is a typical visit, how many events happen per session, where inside a session do people drop off. A **session** is a run of one user's events with no gap longer than an inactivity timeout, and 30 minutes is the common default. Sessionization is the query that stamps each event with the session it belongs to, and it is one of the most common streaming-flavored questions on a DE screen.

## The three-step build

Work on \`events(user_id, event_ts)\`. The spirit is the same as gaps-and-islands: find where a run breaks, then number the runs.

1. **Look back one event.** \`LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts)\` hands each event the previous event's timestamp for that user, and \`NULL\` for the user's first event.
2. **Flag a new session on a long gap.** A user's first event and any event more than 30 minutes after the previous one open a fresh session: \`prev_ts IS NULL OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30\`. \`julianday\` returns days, so multiplying the difference by 1440 converts it to minutes.
3. **Running-sum the flag into a session number.** \`SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts)\` counts how many sessions have started up to and including this event, so every event inside one session shares the same number. Concatenate it with the user id for a stable id: \`user_id || '-' || session_seq\`.

The demo below shows every intermediate column (the previous timestamp, the gap in minutes, the new-session flag, and the running session number) so you can watch the 80-minute gap flip the flag and bump the number.

## The ambiguity interviewers probe

"Thirty minutes of inactivity" almost always means **since the previous event**, which is exactly what the LAG gap measures and what we use here. A few teams instead mean 30 minutes since the session **started**, a fixed-length window. The two disagree: a steady trickle every 20 minutes is one endless session under the first rule and a series of capped windows under the second. State which one you are implementing, because the interviewer is often checking that you noticed the fork.

**Interview nuance:** this is the batch-SQL form of a streaming session window. It is exact over a bounded table, but a live stream needs a watermark to decide when a session is closed and safe to emit, since a late event could still extend it.

> **In the warehouse this differs.** Flink and Spark Structured Streaming have a native session window (\`SESSION(event_time, INTERVAL '30' MINUTE)\`) where a watermark bounds late data, and Snowflake exposes \`CONDITIONAL_TRUE_EVENT\` and \`MATCH_RECOGNIZE\`. The gap math changes as well (\`TIMESTAMPDIFF\` or \`DATE_DIFF\` instead of \`julianday() * 1440\`). The LAG-plus-running-sum pattern is what you write over a bounded batch table, and it is the answer an interviewer wants.`,
    demoSeedSql: `CREATE TABLE events (event_id INTEGER PRIMARY KEY, user_id INTEGER, event_ts TEXT);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 10:30:00'),   -- 80 min gap starts a new session
  (4, 1, '2026-03-01 10:45:00');`,
    demoCode: `-- Every intermediate column: prev_ts gap, the new-session flag, the running session number.
WITH with_prev AS (
  SELECT event_id, event_ts,
         LAG(event_ts) OVER (ORDER BY event_ts) AS prev_ts
  FROM events
),
flagged AS (
  SELECT event_id, event_ts, prev_ts,
         ROUND((julianday(event_ts) - julianday(prev_ts)) * 1440) AS gap_minutes,
         CASE WHEN prev_ts IS NULL OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30
              THEN 1 ELSE 0 END AS new_session
  FROM with_prev
)
SELECT event_id, event_ts, gap_minutes, new_session,
       SUM(new_session) OVER (ORDER BY event_ts) AS session_seq
FROM flagged
ORDER BY event_ts;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-sessionization-apply",
    executionMode: "single-file",
    prompt: `Write a query that assigns a \`session_id\` to each event, starting a new session after **30 minutes** of user inactivity, and returns \`(event_id, user_id, event_ts, session_id)\` over \`events(event_id, user_id, event_ts)\`.

Measure the gap to the previous event per user with \`LAG\`, flag a new session when that gap exceeds 30 minutes (or the event is the user's first), running-sum the flag per user into a session number, and build \`session_id\` as \`user_id || '-' || session_number\`. Alias the columns exactly \`event_id\`, \`user_id\`, \`event_ts\`, \`session_id\`.`,
    starterCode: `-- Stamp each event with its session_id (new session after a 30-minute gap).
WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
)
SELECT
  -- flag a new session on a > 30 min gap, running-sum it, then build session_id
FROM with_prev;`,
    hints: [
      "Minutes between two timestamps: `(julianday(event_ts) - julianday(prev_ts)) * 1440`.",
      "New-session flag: `prev_ts IS NULL OR that_gap > 30` as a `CASE ... THEN 1 ELSE 0 END`.",
      "Running-sum the flag with `SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts)`, then `user_id || '-' || that_sum`.",
    ],
    referenceSolution: `WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
),
flagged AS (
  SELECT event_id, user_id, event_ts,
         CASE WHEN prev_ts IS NULL
                   OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30
              THEN 1 ELSE 0 END AS new_session
  FROM with_prev
),
sessioned AS (
  SELECT event_id, user_id, event_ts,
         SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts) AS session_seq
  FROM flagged
)
SELECT event_id, user_id, event_ts,
       user_id || '-' || session_seq AS session_id
FROM sessioned;`,
    singleFile: {
      seedSql: `CREATE TABLE events (
  event_id INTEGER PRIMARY KEY,
  user_id  INTEGER,
  event_ts TEXT      -- 'YYYY-MM-DD HH:MM:SS'
);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 09:20:00'),
  (4, 1, '2026-03-01 10:30:00'),
  (5, 1, '2026-03-01 10:35:00'),
  (6, 2, '2026-03-01 14:00:00'),
  (7, 2, '2026-03-01 14:05:00'),
  (8, 2, '2026-03-01 15:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["event_id", "user_id", "event_ts", "session_id"],
        rows: [
          [1, 1, "2026-03-01 09:00:00", "1-1"],
          [2, 1, "2026-03-01 09:10:00", "1-1"],
          [3, 1, "2026-03-01 09:20:00", "1-1"],
          [4, 1, "2026-03-01 10:30:00", "1-2"],
          [5, 1, "2026-03-01 10:35:00", "1-2"],
          [6, 2, "2026-03-01 14:00:00", "2-1"],
          [7, 2, "2026-03-01 14:05:00", "2-1"],
          [8, 2, "2026-03-01 15:00:00", "2-2"],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-sessionization-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns **one row per session** as \`(session_id, start_ts, end_ts, event_count, duration_minutes)\`, over the same \`events(event_id, user_id, event_ts)\` table with the 30-minute inactivity rule.

Assign sessions as before, then aggregate per session: the earliest event timestamp as \`start_ts\`, the latest as \`end_ts\`, the number of events, and the whole-minute duration between the first and last event. Alias the columns exactly as named.`,
    starterCode: `-- One row per session: session_id, start_ts, end_ts, event_count, duration_minutes.
WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
)
SELECT
  -- assign sessions, then GROUP BY the session and aggregate
FROM with_prev;`,
    hints: [
      "Reuse the apply pipeline (flag, running-sum) to get a session number per event, then `GROUP BY user_id, session_seq`.",
      "`MIN(event_ts)` is `start_ts`, `MAX(event_ts)` is `end_ts`, `COUNT(*)` is `event_count`.",
      "Whole-minute duration: `CAST(ROUND((julianday(MAX(event_ts)) - julianday(MIN(event_ts))) * 1440) AS INTEGER)`.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE events (
  event_id INTEGER PRIMARY KEY,
  user_id  INTEGER,
  event_ts TEXT
);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 09:20:00'),
  (4, 1, '2026-03-01 10:30:00'),
  (5, 1, '2026-03-01 10:35:00'),
  (6, 2, '2026-03-01 14:00:00'),
  (7, 2, '2026-03-01 14:05:00'),
  (8, 2, '2026-03-01 15:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["session_id", "start_ts", "end_ts", "event_count", "duration_minutes"],
        rows: [
          ["1-1", "2026-03-01 09:00:00", "2026-03-01 09:20:00", 3, 20],
          ["1-2", "2026-03-01 10:30:00", "2026-03-01 10:35:00", 2, 5],
          ["2-1", "2026-03-01 14:00:00", "2026-03-01 14:05:00", 2, 5],
          ["2-2", "2026-03-01 15:00:00", "2026-03-01 15:00:00", 1, 0],
        ],
      },
    },
  },
}

export const sqlLevel5: SqlLevel = {
  id: 5,
  slug: "advanced-company-sql",
  title: "Level 5: Advanced & Company-Specific SQL for DE Interviews",
  tagline:
    "Rehearse the four rounds of a Data Engineering loop as graded SQL: the power screen, the modeling round, the pipeline round, and the system-design round.",
  defaultExecutionMode: "single-file",
  estimatedHours: 8,
  modules: [
    {
      id: "sql-l5-power-round",
      title: "Module 5.1: The Advanced SQL Power Round",
      description:
        "The live SQL screen an intern actually sits: gaps-and-islands, sessionization, cohort retention, funnels, and advanced window frames.",
      lessons: [gapsAndIslands, sessionization],
    },
  ],
}
