/**
 * SQL curriculum Level 5 — Advanced & Company-Specific SQL for DE Interviews.
 *
 * The Pareto ~8h capstone on top of L1-L4, structured as the four rounds of a Data Engineering
 * interview loop: the live SQL power screen (5.1), the warehouse/modeling round (5.2), the
 * streaming/pipeline round (5.3), and the system-design round (5.4). See
 * docs/sql-curriculum/expand-sql-de.md for the full plan and the interview-level triage
 * (Module 5.1 = intern-core; 5.2 mixed; 5.3/5.4 junior-to-senior).
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * sql.js (SQLite 3.49.1) WASM the app ships, never hand-typed. Warehouse-only constructs
 * (QUALIFY, MERGE, LATERAL FLATTEN, ...) are taught in a callout and emulated with the SQLite
 * feature that stands in for them, so every lesson is a real graded exercise.
 */
import type { SqlLevel } from "@/lib/tutorials/types"
import { scriptExercise } from "./script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Module 5.1 — Round 1: The Advanced SQL Power Round (all Intern-core)
// ---------------------------------------------------------------------------

const gapsAndIslands: SqlLesson = {
  id: "sql-l5-gaps-and-islands",
  title: "Gaps and Islands: Consecutive Streaks and Run Detection",
  summary:
    "The most-failed pattern on the live SQL screen: find consecutive runs and the breaks between them with the row-number-difference template.",
  estimatedMinutes: 42,
  difficulty: "hard",
  skills: [
    "product-analytics",
    "ROW_NUMBER",
    "gaps-and-islands",
    "streak detection",
    "date arithmetic",
    "GROUP BY on a derived key",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## The most-failed pattern on the SQL screen

Gaps and islands is repeatedly named the single most-failed pattern on a live Data Engineering SQL screen. The task always has the same shape: find the consecutive runs (the "islands") in a sequence and the breaks (the "gaps") between them. Longest login streak, consecutive days a metric held, unbroken spans where a price never moved, back-to-back on-call shifts: all one technique. Learn this one template and you have handled a large slice of the analytics questions an interviewer can hand you.

## The four-step template

Work on \`daily_logins(user_id, login_date)\`. The whole trick is to build a key that stays **constant across a run** and **changes the moment the run breaks**, then group on it.

1. **Number each user's rows in date order.** \`ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date)\` gives 1, 2, 3, ... down each user's logins.
2. **Subtract the row number from the date.** Inside a run of consecutive days the date climbs by one each row and so does the row number, so \`date minus row_number\` lands on the **same anchor date** for every row in that run. A gap makes the date jump ahead of the row number, so the anchor shifts to a new value. In SQLite: \`date(login_date, '-' || rn || ' days')\`.
3. **Group by user and anchor.** Each \`(user_id, anchor)\` pair is exactly one island. \`MIN(login_date)\` is its start, \`MAX(login_date)\` its end, and \`COUNT(*)\` its length.
4. **Aggregate the islands.** \`MAX(length)\` per user is the longest streak; a filter on the run start or length answers "which spans".

The demo below (turn on the input panel) materializes the anchor next to each date so you can watch it hold steady inside a run and jump right after the gap.

## The LAG variant

The same islands fall out of \`LAG\`: a new island starts wherever the previous row is **not** the day before. Flag a boundary with \`prev_date IS NULL OR prev_date < date(login_date, '-1 day')\`, then take a running \`SUM\` of that flag as the island id. Both forms are correct. The row-number-difference form is shorter to write under pressure; the LAG form reads more obviously to a reviewer.

## Where this shows up

Streaks, consecutive purchases, unchanged-price spans, subscription-state runs, uptime windows: whenever the prompt says "consecutive", "in a row", "unbroken", or "back to back", reach for this template.

**Interview nuance:** the row-number-difference trick assumes one row per unit (one row per day here). If a user can appear twice on the same day, deduplicate to distinct dates first with \`SELECT DISTINCT user_id, login_date\`, or the doubled row numbers will fracture a real run into false gaps.

> **In the warehouse this differs.** The shape is identical everywhere; only the date math changes. SQLite uses \`date(d, '+1 day')\` and \`julianday()\` differences, while Snowflake and BigQuery use \`DATEADD\`/\`DATE_ADD\` and \`DATEDIFF\`/\`DATE_DIFF\`. In Snowflake, BigQuery, and Databricks you can also wrap the final streak filter in a \`QUALIFY\` clause instead of a subquery; SQLite has no \`QUALIFY\`, so you filter in an outer query.`,
    demoSeedSql: `CREATE TABLE daily_logins (user_id INTEGER, login_date TEXT);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'),
  (1, '2026-03-02'),
  (1, '2026-03-03'),   -- run of three
  (1, '2026-03-05'),   -- gap on 03-04 starts a new run
  (1, '2026-03-06');`,
    demoCode: `-- The anchor stays constant inside a run and jumps after the gap.
SELECT user_id, login_date, rn,
       date(login_date, '-' || rn || ' days') AS island_anchor
FROM (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
ORDER BY user_id, login_date;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-gaps-and-islands-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each user's **longest consecutive-day login streak** as \`(user_id, streak_length)\`, over \`daily_logins(user_id, login_date)\`.

Use the row-number-difference template: number each user's logins in date order, subtract the row number from the date to get a per-run anchor, group by \`(user_id, anchor)\` to size each run, then keep the longest run per user. Alias the columns exactly \`user_id\` and \`streak_length\`.`,
    starterCode: `-- Longest consecutive-day login streak per user.
WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
SELECT
  -- group by the (user_id, anchor) run, size it, then take the max per user
FROM numbered;`,
    hints: [
      "The anchor is `date(login_date, '-' || rn || ' days')`. Every row in one consecutive run collapses to the same anchor date.",
      "Group by `user_id` and the anchor, and `COUNT(*)` is that run's length. Do this in a CTE.",
      "Then `SELECT user_id, MAX(run_length) AS streak_length ... GROUP BY user_id` over that CTE.",
    ],
    referenceSolution: `WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
),
islands AS (
  SELECT user_id,
         date(login_date, '-' || rn || ' days') AS anchor,
         COUNT(*) AS streak_length
  FROM numbered
  GROUP BY user_id, anchor
)
SELECT user_id, MAX(streak_length) AS streak_length
FROM islands
GROUP BY user_id;`,
    singleFile: {
      seedSql: `CREATE TABLE daily_logins (
  user_id    INTEGER,
  login_date TEXT      -- 'YYYY-MM-DD'
);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'), (1, '2026-03-02'), (1, '2026-03-03'), (1, '2026-03-05'), (1, '2026-03-06'),
  (2, '2026-03-01'), (2, '2026-03-02'), (2, '2026-03-04'), (2, '2026-03-05'), (2, '2026-03-06'), (2, '2026-03-07'),
  (3, '2026-03-10');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["user_id", "streak_length"],
        rows: [
          [1, 3],
          [2, 4],
          [3, 1],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-gaps-and-islands-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each product, the date ranges during which its price stayed **unchanged**, as \`(product_id, price, valid_from, valid_to)\`, over \`price_history(product_id, price, effective_date)\`.

Each row is one contiguous span at a single price. If a product returns to an earlier price after changing away and back, that is a **separate** span. Alias the columns exactly \`product_id\`, \`price\`, \`valid_from\`, \`valid_to\`.`,
    starterCode: `-- One row per unbroken price span: product_id, price, valid_from, valid_to.
WITH numbered AS (
  SELECT product_id, price, effective_date,
         ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY effective_date) AS rn_all,
         ROW_NUMBER() OVER (PARTITION BY product_id, price ORDER BY effective_date) AS rn_price
  FROM price_history
)
SELECT
  -- group each contiguous same-price run and take its first/last effective_date
FROM numbered;`,
    hints: [
      "Two row numbers: one over all of a product's rows in date order, one restarted per price. Their difference is constant inside a same-price run.",
      "Group by `product_id`, `price`, and `(rn_all - rn_price)`. That third key separates a price that recurs later into its own span.",
      "`MIN(effective_date)` is `valid_from`, `MAX(effective_date)` is `valid_to` within each group.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE price_history (
  product_id     INTEGER,
  price          INTEGER,
  effective_date TEXT
);
INSERT INTO price_history (product_id, price, effective_date) VALUES
  (10, 100, '2026-01-01'), (10, 100, '2026-01-02'), (10, 100, '2026-01-03'),
  (10, 120, '2026-01-04'), (10, 120, '2026-01-05'),
  (20,  50, '2026-01-01'), (20,  60, '2026-01-02'), (20,  50, '2026-01-03');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["product_id", "price", "valid_from", "valid_to"],
        rows: [
          [10, 100, "2026-01-01", "2026-01-03"],
          [10, 120, "2026-01-04", "2026-01-05"],
          [20, 50, "2026-01-01", "2026-01-01"],
          [20, 60, "2026-01-02", "2026-01-02"],
          [20, 50, "2026-01-03", "2026-01-03"],
        ],
      },
    },
  },
}

const sessionization: SqlLesson = {
  id: "sql-l5-sessionization",
  title: "Sessionization: Grouping Events with an Inactivity Timeout",
  summary:
    "Stamp each event with the session it belongs to: LAG the gap, flag a new session past the timeout, running-sum the flag into a session id.",
  estimatedMinutes: 36,
  difficulty: "hard",
  skills: [
    "streaming",
    "LAG",
    "cumulative-sum flag",
    "event-time windowing",
    "sessionization",
    "session_id assignment",
  ],
  teach: {
    estimatedMinutes: 11,
    markdown: `## What a session is, and why you build one

Raw event logs have no notion of a "visit". You get a stream of \`(user_id, event_ts)\` rows, and the analytics questions all assume sessions: how long is a typical visit, how many events happen per session, where inside a session do people drop off. A **session** is a run of one user's events with no gap longer than an inactivity timeout, and 30 minutes is the common default. Sessionization is the query that stamps each event with the session it belongs to, and it is one of the most common streaming-flavored questions on a DE screen.

## The three-step build

Work on \`events(user_id, event_ts)\`. The spirit is the same as gaps-and-islands: find where a run breaks, then number the runs.

1. **Look back one event.** \`LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts)\` hands each event the previous event's timestamp for that user, and \`NULL\` for the user's first event.
2. **Flag a new session on a long gap.** A user's first event and any event more than 30 minutes after the previous one open a fresh session: \`prev_ts IS NULL OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30\`. \`julianday\` returns days, so multiplying the difference by 1440 converts it to minutes.
3. **Running-sum the flag into a session number.** \`SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts)\` counts how many sessions have started up to and including this event, so every event inside one session shares the same number. Concatenate it with the user id for a stable id: \`user_id || '-' || session_seq\`.

The demo below shows every intermediate column (the previous timestamp, the gap in minutes, the new-session flag, and the running session number) so you can watch the 80-minute gap flip the flag and bump the number.

## The ambiguity interviewers probe

"Thirty minutes of inactivity" almost always means **since the previous event**, which is exactly what the LAG gap measures and what we use here. A few teams instead mean 30 minutes since the session **started**, a fixed-length window. The two disagree: a steady trickle every 20 minutes is one endless session under the first rule and a series of capped windows under the second. State which one you are implementing, because the interviewer is often checking that you noticed the fork.

**Interview nuance:** this is the batch-SQL form of a streaming session window. It is exact over a bounded table, but a live stream needs a watermark to decide when a session is closed and safe to emit, since a late event could still extend it.

> **In the warehouse this differs.** Flink and Spark Structured Streaming have a native session window (\`SESSION(event_time, INTERVAL '30' MINUTE)\`) where a watermark bounds late data, and Snowflake exposes \`CONDITIONAL_TRUE_EVENT\` and \`MATCH_RECOGNIZE\`. The gap math changes as well (\`TIMESTAMPDIFF\` or \`DATE_DIFF\` instead of \`julianday() * 1440\`). The LAG-plus-running-sum pattern is what you write over a bounded batch table, and it is the answer an interviewer wants.`,
    demoSeedSql: `CREATE TABLE events (event_id INTEGER PRIMARY KEY, user_id INTEGER, event_ts TEXT);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 10:30:00'),   -- 80 min gap starts a new session
  (4, 1, '2026-03-01 10:45:00');`,
    demoCode: `-- Every intermediate column: prev_ts gap, the new-session flag, the running session number.
WITH with_prev AS (
  SELECT event_id, event_ts,
         LAG(event_ts) OVER (ORDER BY event_ts) AS prev_ts
  FROM events
),
flagged AS (
  SELECT event_id, event_ts, prev_ts,
         ROUND((julianday(event_ts) - julianday(prev_ts)) * 1440) AS gap_minutes,
         CASE WHEN prev_ts IS NULL OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30
              THEN 1 ELSE 0 END AS new_session
  FROM with_prev
)
SELECT event_id, event_ts, gap_minutes, new_session,
       SUM(new_session) OVER (ORDER BY event_ts) AS session_seq
FROM flagged
ORDER BY event_ts;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-sessionization-apply",
    executionMode: "single-file",
    prompt: `Write a query that assigns a \`session_id\` to each event, starting a new session after **30 minutes** of user inactivity, and returns \`(event_id, user_id, event_ts, session_id)\` over \`events(event_id, user_id, event_ts)\`.

Measure the gap to the previous event per user with \`LAG\`, flag a new session when that gap exceeds 30 minutes (or the event is the user's first), running-sum the flag per user into a session number, and build \`session_id\` as \`user_id || '-' || session_number\`. Alias the columns exactly \`event_id\`, \`user_id\`, \`event_ts\`, \`session_id\`.`,
    starterCode: `-- Stamp each event with its session_id (new session after a 30-minute gap).
WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
)
SELECT
  -- flag a new session on a > 30 min gap, running-sum it, then build session_id
FROM with_prev;`,
    hints: [
      "Minutes between two timestamps: `(julianday(event_ts) - julianday(prev_ts)) * 1440`.",
      "New-session flag: `prev_ts IS NULL OR that_gap > 30` as a `CASE ... THEN 1 ELSE 0 END`.",
      "Running-sum the flag with `SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts)`, then `user_id || '-' || that_sum`.",
    ],
    referenceSolution: `WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
),
flagged AS (
  SELECT event_id, user_id, event_ts,
         CASE WHEN prev_ts IS NULL
                   OR (julianday(event_ts) - julianday(prev_ts)) * 1440 > 30
              THEN 1 ELSE 0 END AS new_session
  FROM with_prev
),
sessioned AS (
  SELECT event_id, user_id, event_ts,
         SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_ts) AS session_seq
  FROM flagged
)
SELECT event_id, user_id, event_ts,
       user_id || '-' || session_seq AS session_id
FROM sessioned;`,
    singleFile: {
      seedSql: `CREATE TABLE events (
  event_id INTEGER PRIMARY KEY,
  user_id  INTEGER,
  event_ts TEXT      -- 'YYYY-MM-DD HH:MM:SS'
);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 09:20:00'),
  (4, 1, '2026-03-01 10:30:00'),
  (5, 1, '2026-03-01 10:35:00'),
  (6, 2, '2026-03-01 14:00:00'),
  (7, 2, '2026-03-01 14:05:00'),
  (8, 2, '2026-03-01 15:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["event_id", "user_id", "event_ts", "session_id"],
        rows: [
          [1, 1, "2026-03-01 09:00:00", "1-1"],
          [2, 1, "2026-03-01 09:10:00", "1-1"],
          [3, 1, "2026-03-01 09:20:00", "1-1"],
          [4, 1, "2026-03-01 10:30:00", "1-2"],
          [5, 1, "2026-03-01 10:35:00", "1-2"],
          [6, 2, "2026-03-01 14:00:00", "2-1"],
          [7, 2, "2026-03-01 14:05:00", "2-1"],
          [8, 2, "2026-03-01 15:00:00", "2-2"],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-sessionization-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns **one row per session** as \`(session_id, start_ts, end_ts, event_count, duration_minutes)\`, over the same \`events(event_id, user_id, event_ts)\` table with the 30-minute inactivity rule.

Assign sessions as before, then aggregate per session: the earliest event timestamp as \`start_ts\`, the latest as \`end_ts\`, the number of events, and the whole-minute duration between the first and last event. Alias the columns exactly as named.`,
    starterCode: `-- One row per session: session_id, start_ts, end_ts, event_count, duration_minutes.
WITH with_prev AS (
  SELECT event_id, user_id, event_ts,
         LAG(event_ts) OVER (PARTITION BY user_id ORDER BY event_ts) AS prev_ts
  FROM events
)
SELECT
  -- assign sessions, then GROUP BY the session and aggregate
FROM with_prev;`,
    hints: [
      "Reuse the apply pipeline (flag, running-sum) to get a session number per event, then `GROUP BY user_id, session_seq`.",
      "`MIN(event_ts)` is `start_ts`, `MAX(event_ts)` is `end_ts`, `COUNT(*)` is `event_count`.",
      "Whole-minute duration: `CAST(ROUND((julianday(MAX(event_ts)) - julianday(MIN(event_ts))) * 1440) AS INTEGER)`.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE events (
  event_id INTEGER PRIMARY KEY,
  user_id  INTEGER,
  event_ts TEXT
);
INSERT INTO events (event_id, user_id, event_ts) VALUES
  (1, 1, '2026-03-01 09:00:00'),
  (2, 1, '2026-03-01 09:10:00'),
  (3, 1, '2026-03-01 09:20:00'),
  (4, 1, '2026-03-01 10:30:00'),
  (5, 1, '2026-03-01 10:35:00'),
  (6, 2, '2026-03-01 14:00:00'),
  (7, 2, '2026-03-01 14:05:00'),
  (8, 2, '2026-03-01 15:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["session_id", "start_ts", "end_ts", "event_count", "duration_minutes"],
        rows: [
          ["1-1", "2026-03-01 09:00:00", "2026-03-01 09:20:00", 3, 20],
          ["1-2", "2026-03-01 10:30:00", "2026-03-01 10:35:00", 2, 5],
          ["2-1", "2026-03-01 14:00:00", "2026-03-01 14:05:00", 2, 5],
          ["2-2", "2026-03-01 15:00:00", "2026-03-01 15:00:00", 1, 0],
        ],
      },
    },
  },
}

const cohortRetention: SqlLesson = {
  id: "sql-l5-cohort-retention",
  title: "Cohort Retention and the Denominator Trap",
  summary:
    "Anchor cohorts on first activity, pin one definition of retained, and keep the FULL cohort as the denominator with a LEFT JOIN.",
  estimatedMinutes: 38,
  difficulty: "hard",
  skills: [
    "product-analytics",
    "cohort analysis",
    "Day-N retention",
    "LEFT JOIN denominator",
    "COUNT(DISTINCT)",
    "date arithmetic",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Retention is where candidates corrupt the denominator

Cohort retention answers "of the users who started in a given week, what fraction came back later". It is one of the highest-signal analytics questions on a DE screen, and it has a famous failure mode: fewer than a third of candidates get the denominator right. The mistake is always the same. They join the cohort to the return activity with an INNER JOIN (or filter on the return event in the \`WHERE\`), which silently drops every user who did NOT come back, so the denominator shrinks to exactly the retained users and the rate reads 100%. Retention is a full-cohort fraction, so the denominator must stay the whole cohort.

## Building it correctly

Work on \`events(user_id, event_date)\`.

1. **Anchor each user's cohort on their first activity.** Use \`MIN(event_date)\` per user, not a \`signup_date\` column, which can be stale or backfilled. Bucket that first date into a cohort, here the ISO week with \`strftime('%Y-%W', first_date)\`.
2. **Define "retained" and pin it.** There are three common readings: active exactly on day N, active within N days, or active during the day-N window. They give different numbers, so commit to one out loud. We use **active exactly 7 days after the first event**: \`event_date = date(first_date, '+7 days')\`.
3. **Keep the full cohort as the denominator.** LEFT JOIN the cohort to the day-7 activity, never INNER. \`COUNT(*)\` over the cohort is the denominator, \`COUNT(matched_user)\` is the numerator, and their ratio is the rate. Cast to a float first with \`1.0 * ...\` or SQLite does integer division and every rate collapses to 0.

The demo shows the trap directly: the same cohort, with the denominator computed both ways, so you watch the INNER-join version report 100% while the full-cohort version reports the real 67%.

**Interview nuance:** use \`COUNT(DISTINCT user_id)\`, not \`COUNT(*)\`, on both sides. A user with two events on day 7 would otherwise count twice in the numerator and push the rate above 100%, which is the tell that the grain slipped.

> **In the warehouse this differs.** The date math is \`date(first_date, '+7 days')\` here versus \`DATE_ADD\` or \`first_date + INTERVAL '7 days'\` in Snowflake and BigQuery, and the week bucket is \`DATE_TRUNC('week', first_date)\` rather than \`strftime\`. The discipline being tested (anchor on first activity, pin one definition, keep the full-cohort denominator) is identical in every dialect.`,
    demoSeedSql: `CREATE TABLE events (user_id INTEGER, event_date TEXT);
INSERT INTO events (user_id, event_date) VALUES
  (1, '2026-03-02'), (1, '2026-03-09'),   -- retained on day 7
  (2, '2026-03-02'),                       -- not retained (no day-7 event)
  (3, '2026-03-03'), (3, '2026-03-10');    -- retained on day 7`,
    demoCode: `-- Same cohort, two denominators. INNER JOIN keeps only retained users, so the rate is always 100%.
WITH firsts AS (SELECT user_id, MIN(event_date) AS first_date FROM events GROUP BY user_id),
cohort AS (SELECT user_id, date(first_date, '+7 days') AS day7 FROM firsts),
day7_activity AS (
  SELECT DISTINCT c.user_id FROM cohort c JOIN events e ON e.user_id = c.user_id AND e.event_date = c.day7
)
SELECT
  COUNT(*)                                            AS full_cohort,
  COUNT(a.user_id)                                    AS retained,
  ROUND(1.0 * COUNT(a.user_id) / COUNT(a.user_id), 4) AS wrong_rate_inner_denominator,
  ROUND(1.0 * COUNT(a.user_id) / COUNT(*), 4)         AS correct_rate_full_cohort
FROM cohort c
LEFT JOIN day7_activity a ON a.user_id = c.user_id;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-cohort-retention-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the **Day-7 retention rate per weekly signup cohort** as \`(cohort_week, cohort_size, retained_day7, retention_rate)\`, over \`events(user_id, event_date)\`, keeping the full cohort in the denominator.

Anchor each user's cohort on the ISO week of their first event (\`strftime('%Y-%W', MIN(event_date))\`). Count a user as retained if they have an event exactly 7 days after their first event. Keep every cohort member in \`cohort_size\` with a LEFT JOIN, and compute \`retention_rate\` as \`retained_day7 / cohort_size\` rounded to 4 places. Alias the columns exactly as named.`,
    starterCode: `-- Day-7 retention per weekly cohort, full-cohort denominator.
WITH firsts AS (
  SELECT user_id, MIN(event_date) AS first_date FROM events GROUP BY user_id
)
SELECT
  -- bucket into cohort weeks, LEFT JOIN to day-7 activity, count both sides
FROM firsts;`,
    hints: [
      "Per user: `cohort_week = strftime('%Y-%W', first_date)` and `day7 = date(first_date, '+7 days')`.",
      "Build a `day7_activity` set of users who have an event on their `day7`, then LEFT JOIN the cohort to it so non-returners survive.",
      "`cohort_size = COUNT(*)`, `retained_day7 = COUNT(matched_user)`, `retention_rate = ROUND(1.0 * retained_day7 / cohort_size, 4)`.",
    ],
    referenceSolution: `WITH firsts AS (
  SELECT user_id, MIN(event_date) AS first_date FROM events GROUP BY user_id
),
cohort AS (
  SELECT user_id,
         strftime('%Y-%W', first_date) AS cohort_week,
         date(first_date, '+7 days')    AS day7
  FROM firsts
),
day7_activity AS (
  SELECT DISTINCT c.user_id
  FROM cohort c
  JOIN events e ON e.user_id = c.user_id AND e.event_date = c.day7
)
SELECT c.cohort_week,
       COUNT(*)          AS cohort_size,
       COUNT(a.user_id)  AS retained_day7,
       ROUND(1.0 * COUNT(a.user_id) / COUNT(*), 4) AS retention_rate
FROM cohort c
LEFT JOIN day7_activity a ON a.user_id = c.user_id
GROUP BY c.cohort_week
ORDER BY c.cohort_week;`,
    singleFile: {
      seedSql: `CREATE TABLE events (
  user_id    INTEGER,
  event_date TEXT
);
INSERT INTO events (user_id, event_date) VALUES
  (1, '2026-03-02'), (1, '2026-03-09'),
  (2, '2026-03-03'), (2, '2026-03-05'),
  (3, '2026-03-04'), (3, '2026-03-11'),
  (4, '2026-03-09'), (4, '2026-03-16'),
  (5, '2026-03-10');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["cohort_week", "cohort_size", "retained_day7", "retention_rate"],
        rows: [
          ["2026-09", 3, 2, 0.6667],
          ["2026-10", 2, 1, 0.5],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-cohort-retention-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns a **cohort retention triangle** as \`(cohort_week, weeks_since_signup, retained_users)\` for weeks 0 through 4, over the same \`events(user_id, event_date)\` table.

Bucket each user by the ISO week of their first event, compute how many whole weeks after that first event each of their events falls, and count the **distinct** retained users per \`(cohort_week, weeks_since_signup)\`. Keep only week offsets 0 through 4. Alias the columns exactly as named.`,
    starterCode: `-- Retention triangle: distinct users active N whole weeks after their cohort's signup week.
WITH firsts AS (
  SELECT user_id, MIN(event_date) AS first_date FROM events GROUP BY user_id
)
SELECT
  -- cohort_week, week offset per event, COUNT(DISTINCT user_id)
FROM firsts;`,
    hints: [
      "Join each event back to its user's `first_date`, then `cohort_week = strftime('%Y-%W', first_date)`.",
      "Whole weeks since signup: `CAST((julianday(event_date) - julianday(first_date)) / 7 AS INTEGER)`.",
      "`GROUP BY cohort_week, weeks_since_signup` with `COUNT(DISTINCT user_id)`, filtered to offsets `BETWEEN 0 AND 4`.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE events (
  user_id    INTEGER,
  event_date TEXT
);
INSERT INTO events (user_id, event_date) VALUES
  (1, '2026-03-02'), (1, '2026-03-09'),
  (2, '2026-03-03'), (2, '2026-03-05'),
  (3, '2026-03-04'), (3, '2026-03-11'),
  (4, '2026-03-09'), (4, '2026-03-16'),
  (5, '2026-03-10');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["cohort_week", "weeks_since_signup", "retained_users"],
        rows: [
          ["2026-09", 0, 3],
          ["2026-09", 1, 2],
          ["2026-10", 0, 2],
          ["2026-10", 1, 1],
        ],
      },
    },
  },
}

const funnelConversion: SqlLesson = {
  id: "sql-l5-funnel-conversion",
  title: "Funnel and Conversion Analysis",
  summary:
    "Collapse an event log to one row per user with MAX(CASE) step flags, enforce step order with timestamps, and read conversion between steps.",
  estimatedMinutes: 28,
  difficulty: "medium",
  skills: [
    "product-analytics",
    "conditional aggregation",
    "MAX(CASE)",
    "funnel step flags",
    "step ordering",
    "conversion rate",
  ],
  teach: {
    estimatedMinutes: 9,
    markdown: `## A funnel is one row per user, one flag per step

A funnel question asks how many users made it through an ordered sequence of steps (view, then add to cart, then purchase) and where they dropped off. The portable answer is conditional aggregation: collapse the event log to one row per user with a flag per step, then count the flags. No self-joins and no window functions, just \`MIN(CASE ...)\` per step.

## The build

Work on \`events(user_id, step, event_ts)\`.

1. **First timestamp per step, per user.** \`MIN(CASE WHEN step = 'view' THEN event_ts END)\` gives each user the time they first hit that step, or \`NULL\` if they never did. One \`GROUP BY\` over the user produces \`t_view\`, \`t_cart\`, and \`t_purchase\`.
2. **Enforce order with the timestamps.** A step counts only if it happened at or after the previous step. Reaching the cart means \`t_view IS NOT NULL AND t_cart IS NOT NULL AND t_cart >= t_view\`. An add-to-cart that precedes the view is a real event but not a real funnel step, so it must not count. Chain the same condition through to purchase.
3. **Count the flags and divide.** \`SUM(reached_step)\` is the users at each step, and the conversion from the prior step is this step's count over the previous step's count.

The base population matters: everyone who entered the funnel stays in the denominator, so a drop-off lowers the rate instead of vanishing. The demo shows three users (one in order, one who stops early, one whose cart precedes the view) and the reached flags each one earns.

**Interview nuance:** the ordering guard is the whole difference between a naive funnel and a correct one. Without it, any user with both a cart event and a view event counts as converted even if they added to cart first and viewed later, which quietly inflates every downstream rate.

> **In the warehouse this differs.** The SQL is unchanged in every dialect. Some engines add helpers (Snowflake \`MATCH_RECOGNIZE\`, or product-analytics funnel primitives that take a step list and a time window), but the conditional-flag-plus-timestamp-ordering approach is the portable answer an interviewer expects, and it is the one that survives when the helper is not available.`,
    demoSeedSql: `CREATE TABLE events (user_id INTEGER, step TEXT, event_ts TEXT);
INSERT INTO events (user_id, step, event_ts) VALUES
  (1, 'view', '2026-03-01 10:00:00'), (1, 'add_to_cart', '2026-03-01 10:05:00'), (1, 'purchase', '2026-03-01 10:10:00'),
  (2, 'view', '2026-03-01 11:00:00'), (2, 'add_to_cart', '2026-03-01 11:05:00'),
  (4, 'add_to_cart', '2026-03-01 09:00:00'), (4, 'view', '2026-03-01 09:05:00');`,
    demoCode: `-- reached_cart is 0 for user 4: the cart event precedes the view, so it is not a real funnel step.
WITH per_user AS (
  SELECT user_id,
    MIN(CASE WHEN step = 'view'        THEN event_ts END) AS t_view,
    MIN(CASE WHEN step = 'add_to_cart' THEN event_ts END) AS t_cart,
    MIN(CASE WHEN step = 'purchase'    THEN event_ts END) AS t_purchase
  FROM events GROUP BY user_id
)
SELECT user_id, t_view, t_cart, t_purchase,
  CASE WHEN t_view IS NOT NULL THEN 1 ELSE 0 END AS reached_view,
  CASE WHEN t_view IS NOT NULL AND t_cart IS NOT NULL AND t_cart >= t_view THEN 1 ELSE 0 END AS reached_cart
FROM per_user ORDER BY user_id;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-funnel-conversion-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each funnel step (\`view\`, then \`add_to_cart\`, then \`purchase\`), the count of users who reached it and the conversion rate from the prior step, as \`(step, users_reached, conversion_from_prior)\`, over \`events(user_id, step, event_ts)\`.

A user reaches a step only if they reached the previous step and this step's first timestamp is at or after the previous step's. The first step (\`view\`) has no prior step, so its \`conversion_from_prior\` is \`NULL\`; each later step's rate is its count divided by the prior step's count, rounded to 4 places. Alias the columns exactly as named.`,
    starterCode: `-- Funnel step counts + conversion from the prior step.
WITH per_user AS (
  SELECT user_id,
    MIN(CASE WHEN step = 'view'        THEN event_ts END) AS t_view,
    MIN(CASE WHEN step = 'add_to_cart' THEN event_ts END) AS t_cart,
    MIN(CASE WHEN step = 'purchase'    THEN event_ts END) AS t_purchase
  FROM events GROUP BY user_id
)
SELECT
  -- reached flags with the >= ordering guard, summed, then one row per step
FROM per_user;`,
    hints: [
      "Reached-cart flag: `t_view IS NOT NULL AND t_cart IS NOT NULL AND t_cart >= t_view`; extend the same chain for purchase.",
      "Sum the three flags in a `totals` CTE to get `n_view`, `n_cart`, `n_purchase`.",
      "Emit one row per step with `UNION ALL`; `view` gets `NULL` conversion, later steps get `ROUND(1.0 * this / prior, 4)`.",
    ],
    referenceSolution: `WITH per_user AS (
  SELECT user_id,
    MIN(CASE WHEN step = 'view'        THEN event_ts END) AS t_view,
    MIN(CASE WHEN step = 'add_to_cart' THEN event_ts END) AS t_cart,
    MIN(CASE WHEN step = 'purchase'    THEN event_ts END) AS t_purchase
  FROM events GROUP BY user_id
),
flags AS (
  SELECT
    CASE WHEN t_view IS NOT NULL THEN 1 ELSE 0 END AS r_view,
    CASE WHEN t_view IS NOT NULL AND t_cart IS NOT NULL AND t_cart >= t_view THEN 1 ELSE 0 END AS r_cart,
    CASE WHEN t_view IS NOT NULL AND t_cart IS NOT NULL AND t_cart >= t_view
              AND t_purchase IS NOT NULL AND t_purchase >= t_cart THEN 1 ELSE 0 END AS r_purchase
  FROM per_user
),
totals AS (
  SELECT SUM(r_view) AS n_view, SUM(r_cart) AS n_cart, SUM(r_purchase) AS n_purchase FROM flags
)
SELECT 'view' AS step, n_view AS users_reached, NULL AS conversion_from_prior FROM totals
UNION ALL
SELECT 'add_to_cart', n_cart, ROUND(1.0 * n_cart / n_view, 4) FROM totals
UNION ALL
SELECT 'purchase', n_purchase, ROUND(1.0 * n_purchase / n_cart, 4) FROM totals;`,
    singleFile: {
      seedSql: `CREATE TABLE events (
  user_id  INTEGER,
  step     TEXT,
  event_ts TEXT
);
INSERT INTO events (user_id, step, event_ts) VALUES
  (1, 'view',        '2026-03-01 10:00:00'),
  (1, 'add_to_cart', '2026-03-01 10:05:00'),
  (1, 'purchase',    '2026-03-01 10:10:00'),
  (2, 'view',        '2026-03-01 11:00:00'),
  (2, 'add_to_cart', '2026-03-01 11:05:00'),
  (3, 'view',        '2026-03-01 12:00:00'),
  (4, 'add_to_cart', '2026-03-01 09:00:00'),
  (4, 'view',        '2026-03-01 09:05:00'),
  (5, 'purchase',    '2026-03-01 08:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["step", "users_reached", "conversion_from_prior"],
        rows: [
          ["view", 4, null],
          ["add_to_cart", 2, 0.5],
          ["purchase", 1, 0.5],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-funnel-conversion-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the **step-to-step conversion rate** for each transition in the funnel as \`(from_step, to_step, conversion_rate)\`, over the same \`events(user_id, step, event_ts)\` table.

Compute two transitions, \`view\` to \`add_to_cart\` and \`add_to_cart\` to \`purchase\`, where each rate is the users who reached the later step divided by the users who reached the earlier step (applying the same at-or-after ordering guard), rounded to 4 places. Alias the columns exactly as named.`,
    starterCode: `-- Step-to-step conversion for each funnel transition.
WITH per_user AS (
  SELECT user_id,
    MIN(CASE WHEN step = 'view'        THEN event_ts END) AS t_view,
    MIN(CASE WHEN step = 'add_to_cart' THEN event_ts END) AS t_cart,
    MIN(CASE WHEN step = 'purchase'    THEN event_ts END) AS t_purchase
  FROM events GROUP BY user_id
)
SELECT
  -- one row per transition: from_step, to_step, reached_later / reached_earlier
FROM per_user;`,
    hints: [
      "Reuse the reached-flag chain to get `n_view`, `n_cart`, `n_purchase` in a `totals` CTE.",
      "Emit two rows with `UNION ALL`: one per transition.",
      "Each `conversion_rate` is `ROUND(1.0 * later_count / earlier_count, 4)`.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE events (
  user_id  INTEGER,
  step     TEXT,
  event_ts TEXT
);
INSERT INTO events (user_id, step, event_ts) VALUES
  (1, 'view',        '2026-03-01 10:00:00'),
  (1, 'add_to_cart', '2026-03-01 10:05:00'),
  (1, 'purchase',    '2026-03-01 10:10:00'),
  (2, 'view',        '2026-03-01 11:00:00'),
  (2, 'add_to_cart', '2026-03-01 11:05:00'),
  (3, 'view',        '2026-03-01 12:00:00'),
  (4, 'add_to_cart', '2026-03-01 09:00:00'),
  (4, 'view',        '2026-03-01 09:05:00'),
  (5, 'purchase',    '2026-03-01 08:00:00');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["from_step", "to_step", "conversion_rate"],
        rows: [
          ["view", "add_to_cart", 0.5],
          ["add_to_cart", "purchase", 0.5],
        ],
      },
    },
  },
}

const windowFramesAndQualify: SqlLesson = {
  id: "sql-l5-window-frames-and-qualify",
  title: "Advanced Window Frames and the QUALIFY Rewrite",
  summary:
    "The LAST_VALUE default-frame trap, ROWS vs RANGE on ties, why a window cannot go in WHERE, NTILE, and the QUALIFY rewrite.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "product-analytics",
    "ROWS vs RANGE",
    "LAST_VALUE frame trap",
    "NTILE",
    "named WINDOW",
    "subquery filter",
    "top-N-per-group",
  ],
  teach: {
    estimatedMinutes: 11,
    markdown: `## Three window-frame traps interviewers love

Window functions are L4 material, but the *frame* underneath them is where the senior-flavored questions live. Three things trip people up, and all three are fair game on a screen.

## Trap 1: LAST_VALUE returns the current row, not the last row

\`LAST_VALUE(amount) OVER (PARTITION BY region ORDER BY sale_date)\` looks like it returns each region's final sale amount. It does not. The default frame, once you supply an \`ORDER BY\`, is \`RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\`, so the window ends at the current row and "last value in the frame" is just the current row's own value. To get the true partition final, widen the frame:

\`\`\`sql
LAST_VALUE(amount) OVER (
  PARTITION BY region ORDER BY sale_date
  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
)
\`\`\`

\`FIRST_VALUE\` does not have this problem, because the default frame already starts at the partition beginning. \`LAST_VALUE\` is the one that bites.

## Trap 2: ROWS and RANGE differ on ties

\`ROWS\` counts physical rows; \`RANGE\` groups rows that are tied on the \`ORDER BY\` key into one step. On two sales that share a date, a running \`SUM\` under \`RANGE\` gives both tied rows the same total (it includes every peer), while \`ROWS\` gives them different running totals, one physical row at a time. When a running total looks too high on duplicate keys, an unintended \`RANGE\` default is usually why. The demo puts the two side by side on a tied date.

## Trap 3: a window function cannot go in WHERE

\`WHERE\` runs before window functions are evaluated, so \`WHERE ROW_NUMBER() OVER (...) = 1\` is an error. Compute the window in a subquery or CTE, then filter the derived column in the outer query. This is the standard top-N-per-group and keep-latest shape:

\`\`\`sql
SELECT region, sale_date, amount FROM (
  SELECT region, sale_date, amount,
         ROW_NUMBER() OVER (PARTITION BY region ORDER BY sale_date DESC) AS rn
  FROM sales
) WHERE rn = 1;
\`\`\`

**Interview nuance:** \`NTILE(n)\` splits a partition into n as-equal-as-possible buckets, which is how you cut customers into spend quartiles or latency deciles. When the earlier buckets come out one row larger than the later ones, that is NTILE distributing the remainder, not a bug.

> **In the warehouse this differs.** Snowflake, BigQuery, and Databricks collapse the subquery-then-filter into one line with \`QUALIFY\`: \`... QUALIFY ROW_NUMBER() OVER (...) = 1\`. QUALIFY is to window functions what \`HAVING\` is to aggregates. SQLite has no \`QUALIFY\`, so the subquery form is what you write here, and it is the portable answer QUALIFY desugars to. The frame semantics (ROWS vs RANGE, the LAST_VALUE default-frame trap) are ANSI standard and identical across every dialect.`,
    demoSeedSql: `CREATE TABLE sales (region TEXT, sale_date TEXT, amount INTEGER);
INSERT INTO sales (region, sale_date, amount) VALUES
  ('east', '2026-01-01', 100),
  ('east', '2026-01-02', 200),
  ('east', '2026-01-02', 50),    -- tied date with the row above
  ('east', '2026-01-03', 300);`,
    demoCode: `-- last_value_wrong drifts row to row; last_value_right is the true partition final (300).
-- On the tied date, running_sum_range lumps both peers (350) while running_sum_rows does not.
SELECT sale_date, amount,
  LAST_VALUE(amount) OVER (ORDER BY sale_date) AS last_value_wrong,
  LAST_VALUE(amount) OVER (ORDER BY sale_date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_value_right,
  SUM(amount) OVER (ORDER BY sale_date ROWS  BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_sum_rows,
  SUM(amount) OVER (ORDER BY sale_date RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_sum_range
FROM sales
ORDER BY sale_date, amount DESC;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-window-frames-and-qualify-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every sale with the final sale amount in its region, as \`(region, sale_date, amount, region_final_amount)\`, over \`sales(region, sale_date, amount)\`.

\`region_final_amount\` is the amount of the region's latest sale by date, and it must appear on **every** row of the region, not only the last one. Use \`LAST_VALUE\` with a frame that spans the whole partition (the default frame gives you the current row instead). Alias the columns exactly as named.`,
    starterCode: `-- Every sale plus its region's true final amount (mind the LAST_VALUE frame).
SELECT region, sale_date, amount,
  -- LAST_VALUE with an explicit full-partition frame
  AS region_final_amount
FROM sales;`,
    hints: [
      "The default frame ends at the current row, so a bare `LAST_VALUE(amount) OVER (PARTITION BY region ORDER BY sale_date)` just echoes `amount`.",
      "Widen the frame: `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING`.",
      "Partition by `region` and order by `sale_date` so the final row of each region is the latest date.",
    ],
    referenceSolution: `SELECT region, sale_date, amount,
       LAST_VALUE(amount) OVER (
         PARTITION BY region ORDER BY sale_date
         ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
       ) AS region_final_amount
FROM sales;`,
    singleFile: {
      seedSql: `CREATE TABLE sales (
  region    TEXT,
  sale_date TEXT,
  amount    INTEGER
);
INSERT INTO sales (region, sale_date, amount) VALUES
  ('east', '2026-01-01', 100),
  ('east', '2026-01-02', 200),
  ('east', '2026-01-03', 150),
  ('west', '2026-01-01', 300),
  ('west', '2026-01-02', 250);`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["region", "sale_date", "amount", "region_final_amount"],
        rows: [
          ["east", "2026-01-01", 100, 150],
          ["east", "2026-01-02", 200, 150],
          ["east", "2026-01-03", 150, 150],
          ["west", "2026-01-01", 300, 250],
          ["west", "2026-01-02", 250, 250],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-window-frames-and-qualify-practice",
    executionMode: "single-file",
    prompt: `Write a query that splits customers into 4 spend quartiles with \`NTILE(4)\` and returns the min and max spend per quartile, as \`(quartile, min_spend, max_spend)\`, over \`customers(customer_id, total_spend)\`.

Order the quartiles 1 through 4, and reuse one named \`WINDOW\` for the \`NTILE\` call rather than inlining the \`OVER (...)\`. Alias the columns exactly as named.`,
    starterCode: `-- 4 spend quartiles with NTILE, min/max per quartile, using a named WINDOW.
WITH q AS (
  SELECT customer_id, total_spend,
         NTILE(4) OVER w AS quartile
  FROM customers
  WINDOW w AS (ORDER BY total_spend)
)
SELECT
  -- group by quartile, min and max spend
FROM q;`,
    hints: [
      "Define the window once with a `WINDOW w AS (ORDER BY total_spend)` clause and reference it as `NTILE(4) OVER w`.",
      "In the outer query, `GROUP BY quartile`.",
      "`MIN(total_spend) AS min_spend`, `MAX(total_spend) AS max_spend`, ordered by `quartile`.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE customers (
  customer_id INTEGER,
  total_spend INTEGER
);
INSERT INTO customers (customer_id, total_spend) VALUES
  (1, 100), (2, 200), (3, 300), (4, 400),
  (5, 500), (6, 600), (7, 700), (8, 800);`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["quartile", "min_spend", "max_spend"],
        rows: [
          [1, 100, 200],
          [2, 300, 400],
          [3, 500, 600],
          [4, 700, 800],
        ],
      },
    },
  },
}

// ---------------------------------------------------------------------------
// Module 5.2 — Round 2: The Warehouse and Modeling Round
// ---------------------------------------------------------------------------

const jsonVariantFlatten: SqlLesson = {
  id: "sql-l5-json-variant-flatten",
  title: "Semi-Structured Data: JSON/VARIANT Extraction and Array Flattening",
  summary:
    "Shred JSON into typed columns with the path operator, explode nested arrays with json_each, and avoid the double-count trap.",
  estimatedMinutes: 36,
  difficulty: "hard",
  skills: [
    "snowflake-warehouse",
    "json_extract",
    "->> operator",
    "json_each",
    "array fan-out",
    "double-count trap",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Semi-structured data lands as JSON, and you shred it in SQL

Modern pipelines ingest a lot of JSON: event payloads, API responses, webhook bodies. It arrives in one text (or VARIANT) column, and your job is to shred it into typed columns and to explode its nested arrays into rows. Two operations cover almost every question: scalar extraction and array fan-out.

## Scalar extraction

On \`raw_events(id, payload)\`, pull a scalar with the path operator. \`payload ->> '$.user.country'\` returns the value at that path as text, and \`NULL\` when the key is absent, so a missing field never errors, it simply goes null. Because SQLite is loosely typed, wrap numeric fields in \`CAST(... AS REAL)\` or \`CAST(... AS INTEGER)\` so downstream math behaves. (\`json_extract(payload, '$.user.country')\` is the function form of the same thing; \`->>\` is the operator sugar for it.)

## Array fan-out

A nested array becomes one row per element with \`json_each\`. Writing \`FROM raw_events r, json_each(r.payload, '$.items') je\` joins each parent row to its array elements, which is a LATERAL join, and \`je.value ->> '$.sku'\` reads a field out of each element. Now you can group and aggregate the exploded rows.

## The double-count trap

The moment you explode an array, the parent's scalar columns repeat once per element. If \`order_total\` is a parent field and you write \`SUM(order_total)\` in the same query that fans out a two-item array, you count the total twice. The demo shows \`naive_sum_doubles\` reporting 200 for a true total of 100. Fix it by exploding in an isolated CTE or subquery, or by aggregating the parent before you fan out. Keep the two grains apart.

**Interview nuance:** always ask what grain the answer should be at. "Revenue per order" stays at the order grain, so you never explode line items to get it; "units per sku" needs the item grain, so you must explode. Mixing the two grains is the classic semi-structured bug.

> **In the warehouse this differs.** Snowflake stores this as a \`VARIANT\` column and writes \`LATERAL FLATTEN(input => payload:items)\`, reading \`value:sku::string\`. BigQuery uses \`UNNEST\` over a \`REPEATED\` field with \`JSON_VALUE\`. Databricks and Spark use \`explode()\` and \`from_json\`. \`json_each\` is the same lateral fan-out, and the double-count trap is identical in all four.`,
    demoSeedSql: `CREATE TABLE raw_events (id INTEGER PRIMARY KEY, payload TEXT);
INSERT INTO raw_events (id, payload) VALUES
  (1, '{"order_total":100,"items":[{"sku":"A","qty":2},{"sku":"B","qty":1}]}');`,
    demoCode: `-- order_total is a parent scalar. Summing it across exploded item rows doubles it.
SELECT
  (SELECT payload ->> '$.order_total' FROM raw_events) AS true_order_total,
  SUM(CAST(r.payload ->> '$.order_total' AS INTEGER))  AS naive_sum_doubles,
  SUM(CAST(je.value ->> '$.qty' AS INTEGER))           AS total_qty
FROM raw_events r, json_each(r.payload, '$.items') je;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-json-variant-flatten-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each event, its \`id\`, the user's country, and the amount, as \`(id, country, amount)\`, over \`raw_events(id, payload)\` where \`payload\` is JSON.

Read \`country\` from the path \`$.user.country\` as text, and \`amount\` from \`$.amount\` cast to \`REAL\`. Rows whose payload is missing a key must return \`NULL\` for that column, not error. Alias the columns exactly as named.`,
    starterCode: `-- Shred scalar fields out of each JSON payload; missing keys become NULL.
SELECT id,
  -- country from $.user.country, amount from $.amount cast to REAL
FROM raw_events;`,
    hints: [
      "The path operator `payload ->> '$.user.country'` returns text and yields NULL for a missing key.",
      "Wrap the amount in `CAST(payload ->> '$.amount' AS REAL)` so it is numeric.",
      "No CASE or COALESCE is needed; a missing key already returns NULL.",
    ],
    referenceSolution: `SELECT id,
       payload ->> '$.user.country' AS country,
       CAST(payload ->> '$.amount' AS REAL) AS amount
FROM raw_events;`,
    singleFile: {
      seedSql: `CREATE TABLE raw_events (id INTEGER PRIMARY KEY, payload TEXT);
INSERT INTO raw_events (id, payload) VALUES
  (1, '{"user":{"id":7,"country":"US"},"amount":"120.50","items":[{"sku":"A","qty":2},{"sku":"B","qty":1}]}'),
  (2, '{"user":{"id":8},"amount":"50","items":[{"sku":"A","qty":3}]}'),
  (3, '{"user":{"id":9,"country":"CA"},"items":[{"sku":"C","qty":5}]}');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["id", "country", "amount"],
        rows: [
          [1, "US", 120.5],
          [2, null, 50],
          [3, "CA", null],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-json-variant-flatten-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the total quantity sold per sku from the nested \`items\` array, as \`(sku, total_qty)\`, over the same \`raw_events(id, payload)\` table.

Explode the \`$.items\` array so each item becomes a row, read \`sku\` and \`qty\` from each element, and sum \`qty\` per \`sku\`. Explode in isolation so no parent scalar is double-counted. Alias the columns exactly as named.`,
    starterCode: `-- Total quantity per sku, exploding the items array with json_each.
SELECT
  -- sku and SUM(qty) from the exploded $.items elements
FROM raw_events r, json_each(r.payload, '$.items') je
GROUP BY sku;`,
    hints: [
      "`json_each(r.payload, '$.items')` yields one row per array element; each element is in `je.value`.",
      "Read fields from an element with `je.value ->> '$.sku'` and `je.value ->> '$.qty'`.",
      "`SUM(CAST(je.value ->> '$.qty' AS INTEGER))` grouped by the sku.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE raw_events (id INTEGER PRIMARY KEY, payload TEXT);
INSERT INTO raw_events (id, payload) VALUES
  (1, '{"user":{"id":7,"country":"US"},"amount":"120.50","items":[{"sku":"A","qty":2},{"sku":"B","qty":1}]}'),
  (2, '{"user":{"id":8},"amount":"50","items":[{"sku":"A","qty":3}]}'),
  (3, '{"user":{"id":9,"country":"CA"},"items":[{"sku":"C","qty":5}]}');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["sku", "total_qty"],
        rows: [
          ["A", 5],
          ["B", 1],
          ["C", 5],
        ],
      },
    },
  },
}

const factGrainsAccumulatingSnapshot: SqlLesson = {
  id: "sql-l5-fact-grains-accumulating-snapshot",
  title: "Fact Grains: The Accumulating Snapshot and UPDATE-in-Place",
  summary:
    "The three fact grains, and the one that mutates: build an accumulating-snapshot fact with NULLable milestone dates, computed lags, and an idempotent rebuild.",
  estimatedMinutes: 32,
  difficulty: "hard",
  skills: [
    "snowflake-warehouse",
    "fact-table grains",
    "accumulating snapshot",
    "UPDATE-in-place",
    "milestone lag durations",
    "idempotent rebuild",
  ],
  teach: {
    estimatedMinutes: 10,
    markdown: `## Three fact grains, and the one that updates in place

A fact table's grain is the answer to "what does one row mean". Three grains cover most of dimensional modeling, and interviewers ask you to tell them apart:

| Grain | One row per | Changes after insert? |
|---|---|---|
| Transaction | event (an order, a click, a payment) | No, append only |
| Periodic snapshot | entity per period (account per day) | No, one new row each period |
| Accumulating snapshot | process instance (an order's lifecycle) | Yes, updated in place as it advances |

The **accumulating snapshot** is the one that updates. It models a process with a known set of milestones (order, picked, shipped, delivered) as one row per instance, with a NULLable date column per milestone and computed lag columns between them. As each milestone lands you fill in its date and recompute the lags. It is the most-asked advanced-fact modeling question because it is the only grain where a row is mutable.

## Building it

Two ways, and both come up in an interview:

- **UPDATE in place.** Open a row when the order is placed (later milestone dates NULL), then \`UPDATE\` it as each milestone arrives.
- **Rebuild from source.** Pivot the milestone event log into one row per order with \`MIN(CASE WHEN milestone = 'shipped' THEN event_ts END)\` per milestone, and \`DELETE\` then \`INSERT\` the whole table each run.

The rebuild is naturally idempotent (run it twice, same table), which is why column-store warehouses prefer it. The lag columns are date differences: \`days_order_to_ship = julianday(shipped_ts) - julianday(order_ts)\`, left \`NULL\` while the later milestone has not happened.

**Interview nuance:** a not-yet-reached milestone is \`NULL\`, and its lag is \`NULL\`, never zero. An order that shipped but has not been delivered has a real \`days_order_to_ship\` and a \`NULL\` \`days_ship_to_deliver\`. Coalescing those NULLs to 0 would silently claim instant delivery.

> **In the warehouse this differs.** The \`UPDATE\` becomes a \`MERGE\` in Snowflake and BigQuery, and column-store warehouses often rebuild the whole table from source each run rather than mutate rows, because a row-level \`UPDATE\` is expensive on columnar storage. The grain and milestone-lag reasoning is identical.`,
    demoSeedSql: `CREATE TABLE raw_order_events (order_id INTEGER, milestone TEXT, event_ts TEXT);
INSERT INTO raw_order_events VALUES
  (1, 'order', '2026-03-01'), (1, 'picked', '2026-03-02'), (1, 'shipped', '2026-03-03'), (1, 'delivered', '2026-03-06'),
  (2, 'order', '2026-03-02'), (2, 'shipped', '2026-03-05');   -- order 2 not delivered yet`,
    demoCode: `-- Pivot the event log into the accumulating-snapshot row. Order 2's delivered_ts and lag stay NULL.
SELECT order_id,
  MIN(CASE WHEN milestone = 'order'     THEN event_ts END) AS order_ts,
  MIN(CASE WHEN milestone = 'shipped'   THEN event_ts END) AS shipped_ts,
  MIN(CASE WHEN milestone = 'delivered' THEN event_ts END) AS delivered_ts,
  CAST(julianday(MIN(CASE WHEN milestone = 'delivered' THEN event_ts END))
     - julianday(MIN(CASE WHEN milestone = 'shipped'   THEN event_ts END)) AS INTEGER) AS days_ship_to_deliver
FROM raw_order_events
GROUP BY order_id;`,
    showDemoInput: true,
  },
  apply: scriptExercise({
    id: "sql-l5-fact-grains-accumulating-snapshot-apply",
    prompt: `Write a script that rebuilds \`fct_order_pipeline\` as an accumulating-snapshot fact, one row per order, from the \`raw_order_events(order_id, milestone, event_ts)\` log.

Pivot each order's milestones into the NULLable columns \`order_ts\`, \`picked_ts\`, \`shipped_ts\`, \`delivered_ts\`, and compute the lag columns \`days_order_to_ship\` and \`days_ship_to_deliver\` as whole-day differences (left NULL while the later milestone has not happened). Lead with \`DELETE FROM fct_order_pipeline;\` so re-running the script rebuilds instead of duplicating.`,
    starterCode: `-- Rebuild the accumulating-snapshot fact: one row per order, milestone columns + lag columns.
DELETE FROM fct_order_pipeline;

INSERT INTO fct_order_pipeline
  (order_id, order_ts, picked_ts, shipped_ts, delivered_ts, days_order_to_ship, days_ship_to_deliver)
SELECT
  order_id,
  -- MIN(CASE WHEN milestone = '...' THEN event_ts END) for each of the four milestones,
  -- then the two lag columns as CAST(julianday(later) - julianday(earlier) AS INTEGER)
FROM raw_order_events
GROUP BY order_id;`,
    hints: [
      "Pivot with `MIN(CASE WHEN milestone = 'shipped' THEN event_ts END)`; a milestone that has not happened yields NULL automatically.",
      "Lag columns are `CAST(julianday(shipped_ts) - julianday(order_ts) AS INTEGER)`, and stay NULL when either milestone is NULL.",
      "The leading `DELETE FROM fct_order_pipeline;` is what makes the rebuild idempotent (run twice, same rows).",
    ],
    referenceSolution: `DELETE FROM fct_order_pipeline;

INSERT INTO fct_order_pipeline
  (order_id, order_ts, picked_ts, shipped_ts, delivered_ts, days_order_to_ship, days_ship_to_deliver)
SELECT
  order_id,
  MIN(CASE WHEN milestone = 'order'     THEN event_ts END),
  MIN(CASE WHEN milestone = 'picked'    THEN event_ts END),
  MIN(CASE WHEN milestone = 'shipped'   THEN event_ts END),
  MIN(CASE WHEN milestone = 'delivered' THEN event_ts END),
  CAST(julianday(MIN(CASE WHEN milestone = 'shipped'   THEN event_ts END))
     - julianday(MIN(CASE WHEN milestone = 'order'     THEN event_ts END)) AS INTEGER),
  CAST(julianday(MIN(CASE WHEN milestone = 'delivered' THEN event_ts END))
     - julianday(MIN(CASE WHEN milestone = 'shipped'   THEN event_ts END)) AS INTEGER)
FROM raw_order_events
GROUP BY order_id;`,
    seedSql: `CREATE TABLE raw_order_events (
  order_id  INTEGER,
  milestone TEXT,
  event_ts  TEXT
);
INSERT INTO raw_order_events (order_id, milestone, event_ts) VALUES
  (1, 'order', '2026-03-01'), (1, 'picked', '2026-03-02'), (1, 'shipped', '2026-03-03'), (1, 'delivered', '2026-03-06'),
  (2, 'order', '2026-03-02'), (2, 'picked', '2026-03-03'), (2, 'shipped', '2026-03-05'),
  (3, 'order', '2026-03-04');

CREATE TABLE fct_order_pipeline (
  order_id             INTEGER PRIMARY KEY,
  order_ts             TEXT,
  picked_ts            TEXT,
  shipped_ts           TEXT,
  delivered_ts         TEXT,
  days_order_to_ship   INTEGER,
  days_ship_to_deliver INTEGER
);`,
    assertions: [
      {
        suite: "grain",
        name: "grain_one_row_per_order",
        sql: `SELECT order_id FROM fct_order_pipeline GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "completeness",
        name: "every_order_present",
        sql: `SELECT DISTINCT order_id FROM raw_order_events WHERE order_id NOT IN (SELECT order_id FROM fct_order_pipeline)`,
      },
      {
        suite: "lag",
        name: "no_negative_delivered_lag",
        sql: `SELECT order_id FROM fct_order_pipeline WHERE days_ship_to_deliver < 0`,
      },
    ],
    checkIdempotency: true,
    idempotencyTables: ["fct_order_pipeline"],
  }),
  practice: scriptExercise({
    id: "sql-l5-fact-grains-accumulating-snapshot-practice",
    prompt: `Write a script that backfills a late-arriving \`delivered_ts\` into an already-built \`fct_order_pipeline\` and recomputes the delivery lag, without changing the grain.

The \`late_deliveries(order_id, delivered_ts)\` table holds deliveries that landed after the fact was built. For each, set \`delivered_ts\` on the matching pipeline row and recompute \`days_ship_to_deliver\` from the new \`delivered_ts\` and the existing \`shipped_ts\`. Touch only those orders, and keep exactly one row per order.`,
    starterCode: `-- Backfill the late delivered_ts and recompute the delivery lag; grain stays one row per order.
UPDATE fct_order_pipeline
SET
  -- delivered_ts from late_deliveries, and days_ship_to_deliver recomputed from it and shipped_ts
WHERE order_id IN (SELECT order_id FROM late_deliveries);`,
    hints: [
      "Pull the value with a correlated subquery: `delivered_ts = (SELECT l.delivered_ts FROM late_deliveries l WHERE l.order_id = fct_order_pipeline.order_id)`.",
      "Recompute the lag in the same `SET`: `CAST(julianday(new delivered_ts) - julianday(shipped_ts) AS INTEGER)`.",
      "Scope the update with `WHERE order_id IN (SELECT order_id FROM late_deliveries)` so untouched orders and the grain stay intact.",
    ],
    seedSql: `CREATE TABLE fct_order_pipeline (
  order_id             INTEGER PRIMARY KEY,
  order_ts             TEXT,
  picked_ts            TEXT,
  shipped_ts           TEXT,
  delivered_ts         TEXT,
  days_order_to_ship   INTEGER,
  days_ship_to_deliver INTEGER
);
INSERT INTO fct_order_pipeline VALUES
  (1, '2026-03-01', '2026-03-02', '2026-03-03', '2026-03-06', 2, 3),
  (2, '2026-03-02', '2026-03-03', '2026-03-05', NULL, 3, NULL);

CREATE TABLE late_deliveries (order_id INTEGER, delivered_ts TEXT);
INSERT INTO late_deliveries VALUES (2, '2026-03-08');`,
    assertions: [
      {
        suite: "grain",
        name: "grain_one_row_per_order",
        sql: `SELECT order_id FROM fct_order_pipeline GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "backfill",
        name: "late_delivery_backfilled",
        sql: `SELECT l.order_id FROM late_deliveries l JOIN fct_order_pipeline f ON f.order_id = l.order_id WHERE f.delivered_ts IS NULL`,
      },
      {
        suite: "lag",
        name: "no_negative_delivered_lag",
        sql: `SELECT order_id FROM fct_order_pipeline WHERE days_ship_to_deliver < 0`,
      },
    ],
    checkIdempotency: true,
    idempotencyTables: ["fct_order_pipeline"],
  }),
}

export const sqlLevel5: SqlLevel = {
  id: 5,
  slug: "advanced-company-sql",
  title: "Level 5: Advanced & Company-Specific SQL for DE Interviews",
  tagline:
    "Rehearse the four rounds of a Data Engineering loop as graded SQL: the power screen, the modeling round, the pipeline round, and the system-design round.",
  defaultExecutionMode: "single-file",
  estimatedHours: 8,
  modules: [
    {
      id: "sql-l5-power-round",
      title: "Module 5.1: The Advanced SQL Power Round",
      description:
        "The live SQL screen an intern actually sits: gaps-and-islands, sessionization, cohort retention, funnels, and advanced window frames.",
      lessons: [
        gapsAndIslands,
        sessionization,
        cohortRetention,
        funnelConversion,
        windowFramesAndQualify,
      ],
    },
    {
      id: "sql-l5-modeling-round",
      title: "Module 5.2: The Warehouse and Modeling Round",
      description:
        "Modeling-round asks on a Snowflake, BigQuery, or Databricks-shaped stack: semi-structured JSON extraction, advanced fact grains, as-of joins, and join fan-out.",
      lessons: [jsonVariantFlatten, factGrainsAccumulatingSnapshot],
    },
  ],
}
