/**
 * SQL curriculum Level 6 — Cloud & Data Engineering Foundations.
 *
 * The beginner infrastructure-literacy layer that L1-L5 leave out. L1-L5 teach SQL query
 * skill; L6 teaches the PLATFORM the SQL runs on, the way an intern/junior DE interview
 * probes it: object storage, columnar file formats, partitioning, distributed execution,
 * and pipelines. Every lesson teaches the concept deeply in `teach`, then grades a real
 * "query the platform's own metadata" SQL exercise over a simulated catalog (an S3
 * inventory, a Glue catalog, Parquet column stats, a partition catalog, Spark task
 * metrics, a pipeline run log) so the existing routing/registry/test guards cover it with
 * no new wiring. See docs/sql-curriculum/cloud/PLAN.md and the four source-verified
 * research facts-sheets beside it.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through
 * the SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never
 * hand-typed, and re-checked by single-file-reference-solutions.test.ts. Content rules
 * (constitution + memory): no em dashes in learner prose; every Apply/Practice prompt
 * leads with the deliverable.
 */
import type { SqlLevel } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Shared simulated-catalog seeds for Module 6.1. Named after the real thing so a learner
// who later queries the actual metadata recognizes the shape.
// ---------------------------------------------------------------------------

const PLATFORM_SEED = `CREATE TABLE platform_services (
  service          TEXT,
  layer            TEXT,     -- storage | catalog | compute | orchestration | serving
  monthly_cost_usd INTEGER
);
INSERT INTO platform_services (service, layer, monthly_cost_usd) VALUES
  ('S3 data lake',        'storage',       1200),
  ('Glue Data Catalog',   'catalog',        150),
  ('Athena',              'compute',        900),
  ('EMR Spark cluster',   'compute',       2600),
  ('Redshift warehouse',  'compute',       3100),
  ('Airflow (MWAA)',      'orchestration',  400),
  ('QuickSight BI',       'serving',        350),
  ('API cache (Redis)',   'serving',        220);`

const S3_INVENTORY_SEED = `CREATE TABLE s3_inventory (
  object_key       TEXT,
  size_bytes       INTEGER,
  storage_class    TEXT,
  last_access_days INTEGER   -- days since the object was last read
);
INSERT INTO s3_inventory (object_key, size_bytes, storage_class, last_access_days) VALUES
  ('raw/events/2026-01-02/part-0.parquet',    300000000000, 'STANDARD',      1),
  ('raw/events/2025-08-01/part-0.parquet',    300000000000, 'STANDARD',    150),
  ('raw/logs/2025-11-15/app.log',             400000000000, 'STANDARD',    210),
  ('curated/daily_active/2026-01-01.parquet',  90000000000, 'STANDARD',      1),
  ('raw/logs/2025-10-01/app.log',             600000000000, 'STANDARD_IA', 260),
  ('archive/2024/full.tar',                  1000000000000, 'GLACIER_DEEP',800),
  ('exports/report-2026-01.csv',              50000000000, 'STANDARD',      5);`

const STORAGE_PRICING_SEED = `CREATE TABLE storage_pricing (
  storage_class   TEXT,
  usd_per_gb_month REAL   -- illustrative US price; 1 GB = 1,000,000,000 bytes here
);
INSERT INTO storage_pricing (storage_class, usd_per_gb_month) VALUES
  ('STANDARD',     0.023),
  ('STANDARD_IA',  0.0125),
  ('GLACIER_IR',   0.004),
  ('GLACIER_DEEP', 0.00099);`

const INVENTORY_AND_PRICING_SEED = S3_INVENTORY_SEED + "\n" + STORAGE_PRICING_SEED

const GLUE_CATALOG_SEED = `CREATE TABLE glue_catalog (
  db_name        TEXT,
  table_name     TEXT,
  location       TEXT,     -- the S3 prefix the files live under
  file_format    TEXT,     -- parquet | json | csv
  partition_keys TEXT      -- comma-separated, '' when the table is unpartitioned
);
INSERT INTO glue_catalog (db_name, table_name, location, file_format, partition_keys) VALUES
  ('analytics', 'events',       's3://lake/raw/events/',   'parquet', 'dt'),
  ('analytics', 'daily_active', 's3://lake/curated/dau/',  'parquet', 'dt'),
  ('analytics', 'app_logs',     's3://lake/raw/logs/',     'json',    ''),
  ('finance',   'invoices',     's3://lake/raw/invoices/', 'csv',     ''),
  ('finance',   'fx_rates',     's3://lake/ref/fx/',       'parquet', ''),
  ('ml',        'features',     's3://lake/ml/features/',  'parquet', 'dt');`

// ---------------------------------------------------------------------------
// Module 6.1 — The Cloud Data Platform
// ---------------------------------------------------------------------------

const cloudAndTheDeStack: SqlLesson = {
  id: "sql-l6-cloud-and-the-de-stack",
  title: "What the Cloud Is, and the Shape of a Data Platform",
  summary:
    "Regions, availability zones, and managed services, then the five decoupled layers every data platform is built from: storage, catalog, compute, orchestration, serving.",
  estimatedMinutes: 24,
  difficulty: "easy",
  skills: [
    "cloud fundamentals",
    "regions and availability zones",
    "managed services",
    "data platform architecture",
    "GROUP BY",
    "SUM",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## What "the cloud" really is

The cloud is renting other people's computers and services over the internet, billed by usage, instead of buying and racking your own hardware. For a data engineer that reframes cost as a design choice: you pay for bytes stored, bytes a query scans, requests made, and data moved, so the cheapest query is the one that reads the fewest bytes. That single idea drives everything in this level.

Two words you will hear on day one:

- A **Region** is a geographic area where a cloud provider clusters data centers (for example \`us-east-1\` in North Virginia). Regions are fully independent, and data in a Region stays in that Region unless you copy it out.
- An **Availability Zone (AZ)** is one or more discrete data centers inside a Region, each with its own power and networking. Every Region has at least three AZs, physically separated but linked by fast private networking. One AZ can fail, so spreading data and compute across several is how a platform stays up.

A **managed service** is the other half of the mental model. Instead of running the server yourself, you consume a capability through an API and the provider handles the machines, patching, scaling, and failover. Object storage (Amazon S3), serverless SQL (Amazon Athena), and a warehouse (Amazon Redshift) are all managed: you rent the capability, not the box.

## The shape of a data platform

Almost every cloud data platform is the same five layers, and knowing the layers is how you place any new tool you meet.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Storage", "note": "files on object storage (S3)" },
    { "label": "Catalog", "note": "schema for those files (Glue)" },
    { "label": "Compute", "note": "runs the SQL (Athena, Spark)" },
    { "label": "Orchestration", "note": "schedules the jobs (Airflow)" },
    { "label": "Serving", "note": "dashboards, APIs, cache" }
  ],
  "caption": "The five decoupled layers of a cloud data platform. Storage is just files; compute is rented per query."
}
\`\`\`

1. **Storage** holds the raw and processed data as files, cheaply and at any scale (the data lake on object storage).
2. **Catalog** records what those files mean: table names, columns, types, and where the files live. Without it, a folder of files is just bytes.
3. **Compute** is the engine that reads the files and runs your SQL or jobs (Athena, Spark, a warehouse). Compute is separate from storage, so you can scale them independently and point many engines at the same data.
4. **Orchestration** schedules the jobs and wires their dependencies into a pipeline that runs on time.
5. **Serving** is where cleaned results land for people and apps: dashboards, an API, a cache.

The defining feature of the modern platform is that these layers are **decoupled**. Storage is just files, the catalog gives them a schema, and compute is rented by the query. That separation is why "run SQL over a folder of files" is a normal sentence, and it is the backdrop for the rest of this level.

## Reading the platform with SQL

You do not just build these layers, you operate them, and operating them means asking questions: what does each layer cost, which services are compute versus storage, where is the money going. Those questions are answered by querying a catalog of the platform itself. The exercises in this level do exactly that: you query a stand-in for each layer's own metadata, which is a real data-engineering skill (teams query cost-and-usage reports, storage inventories, and job logs with SQL every day).

**Interview nuance:** when an interviewer asks you to "describe a data platform," the five-layer storage / catalog / compute / orchestration / serving spine is a clean, senior-sounding answer, and naming the decoupling of storage from compute is the detail that signals you actually understand cloud economics.

> **On a real platform this differs.** Here you query one small \`platform_services\` table in SQLite. On AWS the same reasoning runs against the Cost and Usage Report (queried in Athena or loaded into a warehouse), where each row is a service, usage type, and cost. The query shape (group by a layer or service, sum the cost, sort) is identical.`,
    demoSeedSql: PLATFORM_SEED,
    demoCode: `-- The platform catalog: one row per service, tagged by the layer it belongs to.
SELECT service, layer, monthly_cost_usd
FROM platform_services
ORDER BY monthly_cost_usd DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-cloud-and-the-de-stack-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total monthly cost of each platform layer, as \`(layer, monthly_cost)\`, most expensive layer first, over \`platform_services(service, layer, monthly_cost_usd)\`.

Group the services by their \`layer\` and sum \`monthly_cost_usd\`. Alias the summed column exactly \`monthly_cost\`, ordered descending.`,
    starterCode: `-- Total monthly cost per platform layer, most expensive first.
SELECT
  -- group the services by layer and sum their cost
FROM platform_services;`,
    hints: [
      "Group by `layer` so each layer collapses to one row.",
      "`SUM(monthly_cost_usd) AS monthly_cost` is the per-layer total.",
      "Add `ORDER BY monthly_cost DESC` so the most expensive layer is first.",
    ],
    referenceSolution: `SELECT layer, SUM(monthly_cost_usd) AS monthly_cost
FROM platform_services
GROUP BY layer
ORDER BY monthly_cost DESC;`,
    singleFile: {
      seedSql: PLATFORM_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["layer", "monthly_cost"],
        rows: [
          ["compute", 6600],
          ["storage", 1200],
          ["serving", 570],
          ["orchestration", 400],
          ["catalog", 150],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-cloud-and-the-de-stack-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each platform layer running more than one service, with its service count and total monthly cost, as \`(layer, service_count, monthly_cost)\`, most expensive first, over the same \`platform_services\` table.

Keep only layers with more than one service. Alias the columns exactly \`service_count\` and \`monthly_cost\`, ordered by \`monthly_cost\` descending.`,
    starterCode: `-- Layers running more than one service: layer, service_count, monthly_cost.
SELECT
  -- group by layer, count services, sum cost, keep groups with COUNT(*) > 1
FROM platform_services;`,
    hints: [
      "Group by `layer`, then `COUNT(*) AS service_count` and `SUM(monthly_cost_usd) AS monthly_cost`.",
      "`HAVING COUNT(*) > 1` filters groups after aggregation (a plain `WHERE` cannot see the count).",
      "Order by `monthly_cost` descending.",
    ],
    singleFile: {
      seedSql: PLATFORM_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["layer", "service_count", "monthly_cost"],
        rows: [
          ["compute", 3, 6600],
          ["serving", 2, 570],
        ],
      },
    },
  },
}

const objectVsBlockStorage: SqlLesson = {
  id: "sql-l6-object-vs-block-storage",
  title: "Object vs Block vs File Storage, and Why the Lake Lives on S3",
  summary:
    "The three storage shapes every cloud offers (S3, EBS, EFS), the immutable-blob-over-HTTP object model, eleven-nines durability, and why a data lake is files in a bucket.",
  estimatedMinutes: 26,
  difficulty: "easy",
  skills: [
    "object storage",
    "block storage",
    "S3 durability vs availability",
    "data lake",
    "string functions",
    "GROUP BY",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Three ways to store bytes

Before you can reason about a data lake you need the three storage shapes every cloud offers, because interviewers ask for them by name and juniors mix them up constantly.

- **Block storage** is a raw virtual disk. You attach it to one machine, format a filesystem on it, and read or write any block in place, exactly like the SSD in a laptop. On AWS this is **Amazon EBS**. It is what a boot disk and a transactional database's files sit on, because a database needs to update a few kilobytes in the middle of a file, in place, with sub-millisecond latency.
- **File storage** is a shared folder many machines mount over a network protocol (NFS). On AWS this is **Amazon EFS**. Reach for it when many servers must read and write the same files at once.
- **Object storage** is a giant key-value store of whole files, reached over HTTP. On AWS this is **Amazon S3**, and it is where data lakes live.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["dimension", "block (EBS)", "object (S3)", "file (EFS)"],
  "rows": [
    ["access unit", "blocks of a raw disk", "whole object + key", "files in a folder"],
    ["addressed by", "device + offset", "key over HTTP", "path over NFS"],
    ["mutability", "edit any block in place", "replace the whole object", "edit files in place"],
    ["shared by", "one instance", "any number of readers", "many instances at once"],
    ["use it for", "boot disk, a database's files", "data lake, backups, logs", "shared files across machines"]
  ],
  "highlightCols": ["object (S3)"],
  "caption": "Block is a raw disk you format; file is a shared mount; object is whole files over HTTP. Lakes use object storage."
}
\`\`\`

## Why the lake lives on object storage

An object is a file plus its metadata, addressed by a **key** inside a **bucket**, for example the key \`raw/events/2026-01-02/part-0.parquet\`. You reach it with an HTTP GET or PUT, and every object has a URL. Three properties make this the natural home for a data lake:

- **It scales without limit and costs little.** A bucket holds any number of objects, and a single object can be up to 5 TB. You pay only for what you store, with no capacity to provision.
- **It is extremely durable.** S3 is designed to provide **eleven nines** of durability (99.999999999%) by storing every object redundantly across at least three Availability Zones. That is a design target for not losing data, and it is a different number from availability (99.99%, the chance you can reach it at a given moment). Mixing up durability and availability is the single most common junior mistake here.
- **Any engine can read the files.** Because objects are just files behind an HTTP key, Athena, Spark, and a warehouse can all read the same bucket. Storage is decoupled from compute.

The trade is that object storage is **not** a disk. You cannot edit an object in place: a write replaces the whole object (or, with versioning on, adds a new version). There is no "change these 8 bytes." That is fine for a lake, where you write files once and read them many times, and it is exactly why a live transactional database wants EBS, not S3.

One more property worth stating plainly: S3's namespace is **flat**. The slashes in a key only look like folders. \`raw/events/2026-01-02/\` is a **prefix** of the key, not a real directory, and console "folders" are a convenience the UI draws. This matters in the partitioning module, where a layout like \`dt=2026-01-02/\` is just a key prefix that a query engine filters on.

**Interview nuance:** "object versus block versus file, give an AWS example of each" is a near-guaranteed junior question. Answer with the access unit and mutability: block is a raw disk you format (EBS), file is a shared mount (EFS), object is whole files over HTTP that you replace rather than edit (S3), and the lake uses object storage for cheap, unlimited, engine-agnostic capacity.

> **On a real platform this differs.** Real S3 inventory comes from an S3 Inventory report (a daily or weekly file listing every object with its size, storage class, and last-modified date) that you query in Athena. The \`s3_inventory\` table you query here is a small stand-in with the same columns, so the query you write is the query you would run for real.`,
    demoSeedSql: S3_INVENTORY_SEED,
    demoCode: `-- The inventory: each object's size in GB and whether it has gone cold.
SELECT object_key,
       ROUND(size_bytes / 1000000000.0, 0) AS size_gb,
       CASE WHEN last_access_days > 90 THEN 'cold' ELSE 'hot' END AS access_state
FROM s3_inventory
ORDER BY size_bytes DESC;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-object-vs-block-storage-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total bytes stored under each top-level prefix, as \`(prefix, total_bytes)\`, largest first, over \`s3_inventory(object_key, size_bytes, storage_class, last_access_days)\`.

The top-level prefix is the part of \`object_key\` before the first slash (for \`raw/events/...\` it is \`raw\`). Group by that prefix and sum \`size_bytes\`. Alias the columns exactly \`prefix\` and \`total_bytes\`, most bytes first.`,
    starterCode: `-- Total bytes per top-level key prefix, largest first.
SELECT
  -- the prefix is everything before the first '/'; group by it and sum size_bytes
FROM s3_inventory;`,
    hints: [
      "`instr(object_key, '/')` gives the position of the first slash; `substr(object_key, 1, instr(object_key, '/') - 1)` is the text before it.",
      "Group by that prefix expression and `SUM(size_bytes) AS total_bytes`.",
      "Order by `total_bytes` descending.",
    ],
    referenceSolution: `SELECT substr(object_key, 1, instr(object_key, '/') - 1) AS prefix,
       SUM(size_bytes) AS total_bytes
FROM s3_inventory
GROUP BY prefix
ORDER BY total_bytes DESC;`,
    singleFile: {
      seedSql: S3_INVENTORY_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["prefix", "total_bytes"],
        rows: [
          ["raw", 1600000000000],
          ["archive", 1000000000000],
          ["curated", 90000000000],
          ["exports", 50000000000],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-object-vs-block-storage-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every object not accessed in the last 90 days, as \`(object_key, size_bytes, last_access_days)\`, largest first, over the same \`s3_inventory\` table.

These are the cold objects a lifecycle policy would move to a cheaper storage class. Keep only rows where \`last_access_days\` is greater than 90, ordered by \`size_bytes\` descending.`,
    starterCode: `-- Cold objects (not accessed in over 90 days), largest first.
SELECT object_key, size_bytes, last_access_days
FROM s3_inventory
-- keep only objects older than 90 days and sort by size
;`,
    hints: [
      "Filter with `WHERE last_access_days > 90`.",
      "Order by `size_bytes DESC` so the biggest cold object (the best move candidate) is first.",
    ],
    singleFile: {
      seedSql: S3_INVENTORY_SEED,
      orderMatters: true,
      expected: {
        columns: ["object_key", "size_bytes", "last_access_days"],
        rows: [
          ["archive/2024/full.tar", 1000000000000, 800],
          ["raw/logs/2025-10-01/app.log", 600000000000, 260],
          ["raw/logs/2025-11-15/app.log", 400000000000, 210],
          ["raw/events/2025-08-01/part-0.parquet", 300000000000, 150],
        ],
      },
    },
  },
}

const storageClassesLifecycle: SqlLesson = {
  id: "sql-l6-storage-classes-lifecycle",
  title: "Storage Classes and Lifecycle: Paying Less for Colder Data",
  summary:
    "Hot, warm, cold, and archive tiers, the retrieval-latency and minimum-duration trade, lifecycle policies, and computing the bill (and the saving from a transition) with a join.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "S3 storage classes",
    "lifecycle policies",
    "cost modeling",
    "JOIN",
    "aggregation",
    "ROUND",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Hot, warm, cold, and archive

Not all data is read equally. Yesterday's events are queried constantly; last year's are touched once a quarter for a compliance check. Object storage gives you **storage classes** so you can pay less for colder data, trading away instant, free retrieval as the data gets colder. Every class is designed for the same eleven nines of durability. What changes is the price per gigabyte, the retrieval latency, and a minimum billing duration.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["storage class", "$/GB-month", "retrieval", "min duration", "use for"],
  "rows": [
    ["S3 Standard", "0.023", "instant (ms)", "none", "hot, active tables"],
    ["Standard-IA", "0.0125", "instant (ms)", "30 days", "rarely read, needs instant"],
    ["Glacier Instant Retrieval", "0.004", "instant (ms)", "90 days", "archive, rare but instant"],
    ["Glacier Deep Archive", "0.00099", "hours", "180 days", "once-a-year compliance"]
  ],
  "highlightCols": ["$/GB-month"],
  "caption": "Colder classes cost less per GB but add retrieval latency and a minimum billing duration. Illustrative US prices."
}
\`\`\`

The pattern to internalize:

- **S3 Standard** is for hot, frequently read data (your active lake and warehouse tables): highest per-GB price, instant retrieval, no minimum.
- **Standard-Infrequent Access (Standard-IA)** is for data you still need instantly but read rarely (backups, older-but-live tables): cheaper per GB, but it bills a **30-day minimum** and adds a per-GB retrieval fee.
- **Glacier Instant Retrieval** is archive priced, still milliseconds to read, with a **90-day minimum**.
- **Glacier Flexible Retrieval** and **Glacier Deep Archive** are the cheapest, but reads take minutes to hours, with **90-** and **180-day** minimums. Deep Archive is the "look at it once a year" compliance tier.

## Lifecycle policies do this for you

You do not move objects between classes by hand. An **S3 Lifecycle policy** is a set of rules that transition objects to a colder class after N days (Standard to Standard-IA at 30 days, to Glacier at 365) and eventually **expire** (delete) them. It is how a data engineer automates hot to cold to archive to gone without a cron job.

There is a real trap here, and it is a favorite interview follow-up: **moving cold data to a cheaper class does not always save money.** The infrequent and archive classes have minimum storage durations and per-GB retrieval fees, so transitioning tiny or short-lived objects, or objects you will actually read often, can cost more than leaving them in Standard. The saving is real only for large objects that genuinely sit cold.

## Doing the math with SQL

Cost is just arithmetic over the inventory: size in gigabytes times a per-GB price, summed. That is a join between the object inventory and a small price list, and it is exactly the kind of query a DE writes to justify a lifecycle change. The exercises here compute the current bill per class and the saving from a proposed transition.

**Interview nuance:** asked "you have 10 TB of logs you rarely read but must keep seven years, how do you store it cheaply," the answer is a lifecycle policy that transitions to Glacier Flexible or Deep Archive, and the senior detail is naming the retrieval-latency and minimum-duration trade rather than just saying "use Glacier."

> **On a real platform this differs.** Real per-GB prices vary by Region and change over time, and AWS bills a "GB" as a specific byte count. The \`storage_pricing\` table here uses round, illustrative US prices and treats 1 GB as 1,000,000,000 bytes so the arithmetic stays clean. The query shape (join inventory to price, sum, compare) is the real one.`,
    demoSeedSql: INVENTORY_AND_PRICING_SEED,
    demoCode: `-- Each object's own monthly storage cost: size in GB times its class price.
SELECT i.object_key, i.storage_class,
       ROUND(i.size_bytes / 1000000000.0, 0) AS size_gb,
       ROUND(i.size_bytes * p.usd_per_gb_month / 1000000000.0, 2) AS monthly_cost_usd
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class
ORDER BY monthly_cost_usd DESC;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l6-storage-classes-lifecycle-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the total gigabytes and total monthly cost of each storage class, as \`(storage_class, total_gb, monthly_cost_usd)\`, most expensive first, over \`s3_inventory\` joined to \`storage_pricing(storage_class, usd_per_gb_month)\`.

Treat 1 GB as 1,000,000,000 bytes. Round \`total_gb\` and \`monthly_cost_usd\` to 2 decimals, and order by \`monthly_cost_usd\` descending.`,
    starterCode: `-- Total GB and monthly cost per storage class, most expensive first.
SELECT
  -- join inventory to pricing, group by storage class, sum GB and cost
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class;`,
    hints: [
      "Join `s3_inventory` to `storage_pricing` on `storage_class`.",
      "`SUM(size_bytes) / 1000000000.0` is total GB; `SUM(size_bytes * usd_per_gb_month) / 1000000000.0` is the cost (price stays inside the SUM so it is a per-object cost you then total).",
      "Group by `i.storage_class`, wrap both totals in `ROUND(..., 2)`, and order by `monthly_cost_usd DESC`.",
    ],
    referenceSolution: `SELECT i.storage_class,
       ROUND(SUM(i.size_bytes) / 1000000000.0, 2) AS total_gb,
       ROUND(SUM(i.size_bytes * p.usd_per_gb_month) / 1000000000.0, 2) AS monthly_cost_usd
FROM s3_inventory i
JOIN storage_pricing p ON p.storage_class = i.storage_class
GROUP BY i.storage_class
ORDER BY monthly_cost_usd DESC;`,
    singleFile: {
      seedSql: INVENTORY_AND_PRICING_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["storage_class", "total_gb", "monthly_cost_usd"],
        rows: [
          ["STANDARD", 1140, 26.22],
          ["STANDARD_IA", 600, 7.5],
          ["GLACIER_DEEP", 1000, 0.99],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-storage-classes-lifecycle-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each cold STANDARD object, the monthly saving from moving it to Standard-IA, as \`(object_key, current_cost_usd, ia_cost_usd, monthly_saving_usd)\`, largest saving first, over the same \`s3_inventory\` table.

A cold object is in the \`STANDARD\` class with \`last_access_days\` greater than 90. Standard costs 0.023 per GB-month and Standard-IA costs 0.0125 per GB-month (1 GB = 1,000,000,000 bytes). Round every dollar column to 2 decimals, ordered by \`monthly_saving_usd\` descending.`,
    starterCode: `-- Saving from moving each cold STANDARD object to Standard-IA, largest first.
SELECT object_key
  -- current cost at 0.023/GB, IA cost at 0.0125/GB, and the difference
FROM s3_inventory
-- only STANDARD objects gone cold (> 90 days)
;`,
    hints: [
      "Filter with `WHERE storage_class = 'STANDARD' AND last_access_days > 90`.",
      "`size_bytes / 1000000000.0 * 0.023` is the current cost; swap 0.023 for 0.0125 for the IA cost.",
      "The saving is `size_bytes / 1000000000.0 * (0.023 - 0.0125)`; wrap each in `ROUND(..., 2)` and order by the saving descending.",
    ],
    singleFile: {
      seedSql: INVENTORY_AND_PRICING_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["object_key", "current_cost_usd", "ia_cost_usd", "monthly_saving_usd"],
        rows: [
          ["raw/logs/2025-11-15/app.log", 9.2, 5, 4.2],
          ["raw/events/2025-08-01/part-0.parquet", 6.9, 3.75, 3.15],
        ],
      },
    },
  },
}

const lakeWarehouseCatalog: SqlLesson = {
  id: "sql-l6-lake-warehouse-catalog",
  title: "Files Plus a Catalog Equals a Table: Lake, Warehouse, Lakehouse",
  summary:
    "How a pile of files in a bucket becomes a queryable table (the Hive metastore / Glue catalog), the lake vs warehouse vs lakehouse split, and auditing the catalog with SQL.",
  estimatedMinutes: 24,
  difficulty: "easy",
  skills: [
    "data catalog",
    "Hive metastore / Glue",
    "data lake vs warehouse vs lakehouse",
    "schema-on-read",
    "filtering",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Files in a bucket are not a table, yet

A folder of Parquet files in S3, say \`s3://lake/raw/events/\`, is just bytes. Nothing there knows it is an "events table," what columns it has, or their types. Two more pieces turn a pile of files into something you can run SQL against.

The first is a **catalog** (also called a metastore). It records, for each table, the column names and types, the partition columns, the file format, and the S3 location of the files. Add a catalog entry and the same pile of files becomes a queryable **table**. The two names to know are the **Hive metastore** (the original open-source standard) and the **AWS Glue Data Catalog** (AWS's managed, Hive-compatible version). A Glue **crawler** can even infer the schema from the files and fill the catalog in for you.

The second is a **query engine** that reads the catalog, then reads the files: **Amazon Athena** (serverless SQL), **Apache Spark**, or **Trino**. The engine looks up the table to learn "this prefix of Parquet files has these columns," then scans only the files it needs.

\`\`\`csdiagram
{
  "type": "pipeline",
  "stages": [
    { "label": "Files in S3", "note": "raw Parquet bytes" },
    { "label": "Catalog entry", "note": "columns, types, location" },
    { "label": "Query engine", "note": "Athena / Spark / Trino" },
    { "label": "SQL table", "note": "you can now SELECT from it" }
  ],
  "caption": "A pile of files plus a catalog entry becomes a table an engine can read. Storage, catalog, and compute stay separate."
}
\`\`\`

So the defining equation of the lake is: **a pile of files in a bucket, plus a catalog entry that gives them a schema, equals a table.**

## Lake, warehouse, lakehouse

Those files-plus-catalog tables make up a **data lake**: raw data in its native format on cheap object storage, structured only when you query it (schema-on-read). Cheap and flexible, but on its own a lake has no transactions and no easy row-level updates.

A **data warehouse** is the other end: a curated, structured, columnar, SQL-first store that you load conformed data into (schema-on-write). Amazon Redshift, Snowflake, and Google BigQuery are the three names to know. Warehouses are fast for BI and governed, at the cost of loading into their system.

A **lakehouse** is the newer middle: it layers warehouse features (ACID transactions, schema enforcement, time travel) onto open files on object storage, using an **open table format**. Apache Iceberg, Delta Lake, and Apache Hudi are the ones to recognize. The point is one copy of the data on the lake, with warehouse-grade guarantees on top.

## Auditing the catalog with SQL

The catalog is itself a set of tables you can query, and auditing it is real work: which tables are still stored as slow CSV instead of Parquet, which tables have no partitions and will full-scan, which database owns the most tables. The exercises here query a stand-in \`glue_catalog\` to answer exactly those questions.

**Interview nuance:** "how would you query a bunch of Parquet files in S3 with SQL, and where does the schema come from" is a direct junior question. The answer is Athena (or Spark or Trino) reading the file locations and column types from the Glue Data Catalog or a Hive metastore. "A table equals files plus a catalog entry" is the sentence that lands it.

> **On a real platform this differs.** The real Glue Data Catalog exposes this metadata through an API and through queryable \`information_schema\` views, with far more columns (serde, compression, per-column stats). The \`glue_catalog\` table here keeps the few columns that carry the lesson: database, table, location, format, and partition keys.`,
    demoSeedSql: GLUE_CATALOG_SEED,
    demoCode: `-- The catalog: each table's format and whether it declares partition keys.
SELECT db_name, table_name, file_format,
       CASE WHEN partition_keys = '' THEN 'no' ELSE 'yes' END AS partitioned
FROM glue_catalog
ORDER BY db_name, table_name;`,
    showDemoInput: false,
  },
  apply: {
    id: "sql-l6-lake-warehouse-catalog-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every catalog table not stored as Parquet, as \`(db_name, table_name, file_format)\`, ordered by \`db_name\` then \`table_name\`, over \`glue_catalog(db_name, table_name, location, file_format, partition_keys)\`.

These are the tables a migration would convert to Parquet for cheaper, faster scans. Keep only rows whose \`file_format\` is not \`parquet\`.`,
    starterCode: `-- Catalog tables not yet stored as Parquet.
SELECT db_name, table_name, file_format
FROM glue_catalog
-- keep only non-parquet tables, ordered by db then table
;`,
    hints: [
      "Filter with `WHERE file_format <> 'parquet'`.",
      "Order by `db_name, table_name` so the list is stable.",
    ],
    referenceSolution: `SELECT db_name, table_name, file_format
FROM glue_catalog
WHERE file_format <> 'parquet'
ORDER BY db_name, table_name;`,
    singleFile: {
      seedSql: GLUE_CATALOG_SEED,
      orderMatters: true,
      expected: {
        columns: ["db_name", "table_name", "file_format"],
        rows: [
          ["analytics", "app_logs", "json"],
          ["finance", "invoices", "csv"],
        ],
      },
    },
  },
  practice: {
    id: "sql-l6-lake-warehouse-catalog-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every Parquet table that declares no partition keys, as \`(db_name, table_name)\`, ordered by \`db_name\` then \`table_name\`, over the same \`glue_catalog\` table.

A Parquet table with an empty \`partition_keys\` gets scanned in full by every query, so these are the tables to consider partitioning. Keep only rows where \`file_format\` is \`parquet\` and \`partition_keys\` is the empty string.`,
    starterCode: `-- Parquet tables with no partition keys (full-scan risk).
SELECT db_name, table_name
FROM glue_catalog
-- keep parquet tables whose partition_keys is empty
;`,
    hints: [
      "Two conditions joined with AND: `file_format = 'parquet'` and `partition_keys = ''`.",
      "Order by `db_name, table_name`.",
    ],
    singleFile: {
      seedSql: GLUE_CATALOG_SEED,
      orderMatters: true,
      expected: {
        columns: ["db_name", "table_name"],
        rows: [["finance", "fx_rates"]],
      },
    },
  },
}

export const sqlLevel6: SqlLevel = {
  id: 6,
  slug: "cloud-data-foundations",
  title: "Level 6: Cloud & Data Engineering Foundations",
  tagline:
    "Learn the platform your SQL runs on: object storage, columnar files, partitioning, and distributed pipelines, the way a DE interview asks about them.",
  defaultExecutionMode: "single-file",
  estimatedHours: 7,
  modules: [
    {
      id: "sql-l6-cloud-platform",
      title: "Module 6.1: The Cloud Data Platform",
      description:
        "What the cloud is and how a data platform is shaped: regions and managed services, object vs block vs file storage, storage classes and lifecycle, and the files-plus-catalog-equals-a-table idea, all queried as platform metadata.",
      lessons: [
        cloudAndTheDeStack,
        objectVsBlockStorage,
        storageClassesLifecycle,
        lakeWarehouseCatalog,
      ],
    },
  ],
}
