/**
 * SQL curriculum Level 5 — Advanced & Company-Specific SQL for DE Interviews.
 *
 * The Pareto ~8h capstone on top of L1-L4, structured as the four rounds of a Data Engineering
 * interview loop: the live SQL power screen (5.1), the warehouse/modeling round (5.2), the
 * streaming/pipeline round (5.3), and the system-design round (5.4). See
 * docs/sql-curriculum/expand-sql-de.md for the full plan and the interview-level triage
 * (Module 5.1 = intern-core; 5.2 mixed; 5.3/5.4 junior-to-senior).
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * sql.js (SQLite 3.49.1) WASM the app ships, never hand-typed. Warehouse-only constructs
 * (QUALIFY, MERGE, LATERAL FLATTEN, ...) are taught in a callout and emulated with the SQLite
 * feature that stands in for them, so every lesson is a real graded exercise.
 */
import type { SqlLevel } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Module 5.1 — Round 1: The Advanced SQL Power Round (all Intern-core)
// ---------------------------------------------------------------------------

const gapsAndIslands: SqlLesson = {
  id: "sql-l5-gaps-and-islands",
  title: "Gaps and Islands: Consecutive Streaks and Run Detection",
  summary:
    "The most-failed pattern on the live SQL screen: find consecutive runs and the breaks between them with the row-number-difference template.",
  estimatedMinutes: 42,
  difficulty: "hard",
  skills: [
    "product-analytics",
    "ROW_NUMBER",
    "gaps-and-islands",
    "streak detection",
    "date arithmetic",
    "GROUP BY on a derived key",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## The most-failed pattern on the SQL screen

Gaps and islands is repeatedly named the single most-failed pattern on a live Data Engineering SQL screen. The task always has the same shape: find the consecutive runs (the "islands") in a sequence and the breaks (the "gaps") between them. Longest login streak, consecutive days a metric held, unbroken spans where a price never moved, back-to-back on-call shifts: all one technique. Learn this one template and you have handled a large slice of the analytics questions an interviewer can hand you.

## The four-step template

Work on \`daily_logins(user_id, login_date)\`. The whole trick is to build a key that stays **constant across a run** and **changes the moment the run breaks**, then group on it.

1. **Number each user's rows in date order.** \`ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date)\` gives 1, 2, 3, ... down each user's logins.
2. **Subtract the row number from the date.** Inside a run of consecutive days the date climbs by one each row and so does the row number, so \`date minus row_number\` lands on the **same anchor date** for every row in that run. A gap makes the date jump ahead of the row number, so the anchor shifts to a new value. In SQLite: \`date(login_date, '-' || rn || ' days')\`.
3. **Group by user and anchor.** Each \`(user_id, anchor)\` pair is exactly one island. \`MIN(login_date)\` is its start, \`MAX(login_date)\` its end, and \`COUNT(*)\` its length.
4. **Aggregate the islands.** \`MAX(length)\` per user is the longest streak; a filter on the run start or length answers "which spans".

The demo below (turn on the input panel) materializes the anchor next to each date so you can watch it hold steady inside a run and jump right after the gap.

## The LAG variant

The same islands fall out of \`LAG\`: a new island starts wherever the previous row is **not** the day before. Flag a boundary with \`prev_date IS NULL OR prev_date < date(login_date, '-1 day')\`, then take a running \`SUM\` of that flag as the island id. Both forms are correct. The row-number-difference form is shorter to write under pressure; the LAG form reads more obviously to a reviewer.

## Where this shows up

Streaks, consecutive purchases, unchanged-price spans, subscription-state runs, uptime windows: whenever the prompt says "consecutive", "in a row", "unbroken", or "back to back", reach for this template.

**Interview nuance:** the row-number-difference trick assumes one row per unit (one row per day here). If a user can appear twice on the same day, deduplicate to distinct dates first with \`SELECT DISTINCT user_id, login_date\`, or the doubled row numbers will fracture a real run into false gaps.

> **In the warehouse this differs.** The shape is identical everywhere; only the date math changes. SQLite uses \`date(d, '+1 day')\` and \`julianday()\` differences, while Snowflake and BigQuery use \`DATEADD\`/\`DATE_ADD\` and \`DATEDIFF\`/\`DATE_DIFF\`. In Snowflake, BigQuery, and Databricks you can also wrap the final streak filter in a \`QUALIFY\` clause instead of a subquery; SQLite has no \`QUALIFY\`, so you filter in an outer query.`,
    demoSeedSql: `CREATE TABLE daily_logins (user_id INTEGER, login_date TEXT);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'),
  (1, '2026-03-02'),
  (1, '2026-03-03'),   -- run of three
  (1, '2026-03-05'),   -- gap on 03-04 starts a new run
  (1, '2026-03-06');`,
    demoCode: `-- The anchor stays constant inside a run and jumps after the gap.
SELECT user_id, login_date, rn,
       date(login_date, '-' || rn || ' days') AS island_anchor
FROM (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
ORDER BY user_id, login_date;`,
    showDemoInput: true,
  },
  apply: {
    id: "sql-l5-gaps-and-islands-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each user's **longest consecutive-day login streak** as \`(user_id, streak_length)\`, over \`daily_logins(user_id, login_date)\`.

Use the row-number-difference template: number each user's logins in date order, subtract the row number from the date to get a per-run anchor, group by \`(user_id, anchor)\` to size each run, then keep the longest run per user. Alias the columns exactly \`user_id\` and \`streak_length\`.`,
    starterCode: `-- Longest consecutive-day login streak per user.
WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
)
SELECT
  -- group by the (user_id, anchor) run, size it, then take the max per user
FROM numbered;`,
    hints: [
      "The anchor is `date(login_date, '-' || rn || ' days')`. Every row in one consecutive run collapses to the same anchor date.",
      "Group by `user_id` and the anchor, and `COUNT(*)` is that run's length. Do this in a CTE.",
      "Then `SELECT user_id, MAX(run_length) AS streak_length ... GROUP BY user_id` over that CTE.",
    ],
    referenceSolution: `WITH numbered AS (
  SELECT user_id, login_date,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn
  FROM daily_logins
),
islands AS (
  SELECT user_id,
         date(login_date, '-' || rn || ' days') AS anchor,
         COUNT(*) AS streak_length
  FROM numbered
  GROUP BY user_id, anchor
)
SELECT user_id, MAX(streak_length) AS streak_length
FROM islands
GROUP BY user_id;`,
    singleFile: {
      seedSql: `CREATE TABLE daily_logins (
  user_id    INTEGER,
  login_date TEXT      -- 'YYYY-MM-DD'
);
INSERT INTO daily_logins (user_id, login_date) VALUES
  (1, '2026-03-01'), (1, '2026-03-02'), (1, '2026-03-03'), (1, '2026-03-05'), (1, '2026-03-06'),
  (2, '2026-03-01'), (2, '2026-03-02'), (2, '2026-03-04'), (2, '2026-03-05'), (2, '2026-03-06'), (2, '2026-03-07'),
  (3, '2026-03-10');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["user_id", "streak_length"],
        rows: [
          [1, 3],
          [2, 4],
          [3, 1],
        ],
      },
    },
  },
  practice: {
    id: "sql-l5-gaps-and-islands-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns, for each product, the date ranges during which its price stayed **unchanged**, as \`(product_id, price, valid_from, valid_to)\`, over \`price_history(product_id, price, effective_date)\`.

Each row is one contiguous span at a single price. If a product returns to an earlier price after changing away and back, that is a **separate** span. Alias the columns exactly \`product_id\`, \`price\`, \`valid_from\`, \`valid_to\`.`,
    starterCode: `-- One row per unbroken price span: product_id, price, valid_from, valid_to.
WITH numbered AS (
  SELECT product_id, price, effective_date,
         ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY effective_date) AS rn_all,
         ROW_NUMBER() OVER (PARTITION BY product_id, price ORDER BY effective_date) AS rn_price
  FROM price_history
)
SELECT
  -- group each contiguous same-price run and take its first/last effective_date
FROM numbered;`,
    hints: [
      "Two row numbers: one over all of a product's rows in date order, one restarted per price. Their difference is constant inside a same-price run.",
      "Group by `product_id`, `price`, and `(rn_all - rn_price)`. That third key separates a price that recurs later into its own span.",
      "`MIN(effective_date)` is `valid_from`, `MAX(effective_date)` is `valid_to` within each group.",
    ],
    singleFile: {
      seedSql: `CREATE TABLE price_history (
  product_id     INTEGER,
  price          INTEGER,
  effective_date TEXT
);
INSERT INTO price_history (product_id, price, effective_date) VALUES
  (10, 100, '2026-01-01'), (10, 100, '2026-01-02'), (10, 100, '2026-01-03'),
  (10, 120, '2026-01-04'), (10, 120, '2026-01-05'),
  (20,  50, '2026-01-01'), (20,  60, '2026-01-02'), (20,  50, '2026-01-03');`,
      orderMatters: false,
      assertColumnNames: true,
      expected: {
        columns: ["product_id", "price", "valid_from", "valid_to"],
        rows: [
          [10, 100, "2026-01-01", "2026-01-03"],
          [10, 120, "2026-01-04", "2026-01-05"],
          [20, 50, "2026-01-01", "2026-01-01"],
          [20, 60, "2026-01-02", "2026-01-02"],
          [20, 50, "2026-01-03", "2026-01-03"],
        ],
      },
    },
  },
}

export const sqlLevel5: SqlLevel = {
  id: 5,
  slug: "advanced-company-sql",
  title: "Level 5: Advanced & Company-Specific SQL for DE Interviews",
  tagline:
    "Rehearse the four rounds of a Data Engineering loop as graded SQL: the power screen, the modeling round, the pipeline round, and the system-design round.",
  defaultExecutionMode: "single-file",
  estimatedHours: 8,
  modules: [
    {
      id: "sql-l5-power-round",
      title: "Module 5.1: The Advanced SQL Power Round",
      description:
        "The live SQL screen an intern actually sits: gaps-and-islands, sessionization, cohort retention, funnels, and advanced window frames.",
      lessons: [gapsAndIslands],
    },
  ],
}
