#!/usr/bin/env node
/**
 * Compile bugfix pack authoring sources (packs/<id>/) into runtime TS modules
 * (generate-pack.md Step 4). For each pack it emits a client-safe scenario module and
 * a sealed server module, then regenerates the pack registry + the sealed loader map.
 *
 * Authoring layout per pack:
 *   packs/<id>/manifest.json   task.md   solution.md   sealed.json
 *   packs/<id>/src/*           packs/<id>/fixtures/*
 *
 * All string content is embedded with JSON.stringify, so pack source can contain any
 * characters (backticks, ${}, backslashes) without hand-escaping. Run: node
 * scripts/compile-packs.mjs   (then pnpm typecheck && pnpm test).
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const PACKS_DIR = join(ROOT, "packs")
const CLIENT_DIR = join(ROOT, "lib/scenarios/real-world/bugfix/packs")
const SEALED_DIR = join(ROOT, "lib/scenarios/sealed")

const GENERATED = "// GENERATED by scripts/compile-packs.mjs — edit packs/<id>/ and recompile."

function camel(kebab) {
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

function readDirFiles(dir) {
  let entries
  try {
    entries = readdirSync(dir)
  } catch {
    return []
  }
  return entries
    .filter((name) => statSync(join(dir, name)).isFile() && !name.startsWith("."))
    .sort()
    .map((name) => ({ name, content: readFileSync(join(dir, name), "utf8") }))
}

function hasFile(dir, rel) {
  try {
    return statSync(join(dir, rel)).isFile()
  } catch {
    return false
  }
}

function listPackIds() {
  return readdirSync(PACKS_DIR)
    .filter((name) => {
      if (name.startsWith(".")) return false
      const dir = join(PACKS_DIR, name)
      // A complete pack has all six authoring inputs. Skip in-progress dirs (e.g. a
      // pack still being authored) rather than crashing the whole compile.
      const complete =
        hasFile(dir, "manifest.json") &&
        hasFile(dir, "sealed.json") &&
        hasFile(dir, "task.md") &&
        hasFile(dir, "solution.md")
      if (hasFile(dir, "manifest.json") && !complete) {
        console.warn(`skipping incomplete pack: ${name}`)
      }
      return complete
    })
    .sort()
}

function loadPack(id) {
  const dir = join(PACKS_DIR, id)
  const manifest = JSON.parse(readFileSync(join(dir, "manifest.json"), "utf8"))
  const sealed = JSON.parse(readFileSync(join(dir, "sealed.json"), "utf8"))
  const taskMd = readFileSync(join(dir, "task.md"), "utf8")
  const solutionMd = readFileSync(join(dir, "solution.md"), "utf8")
  const srcFiles = readDirFiles(join(dir, "src")).map((f) => ({
    path: `src/${f.name}`,
    content: f.content,
  }))
  const fixtures = readDirFiles(join(dir, "fixtures")).map((f) => ({
    path: `fixtures/${f.name}`,
    content: f.content,
  }))
  return { id, manifest, sealed, taskMd, solutionMd, srcFiles, fixtures }
}

function clientModule(pack) {
  const { manifest } = pack
  const obj = {
    id: manifest.id,
    title: manifest.title,
    summary: manifest.summary,
    company: {
      tag: manifest.company.tag,
      roundName: manifest.company.round_name,
      confidence: manifest.company.confidence,
      notes: manifest.company.notes,
    },
    companies: manifest.companies,
    domain: manifest.domain,
    language: manifest.language,
    difficulty: manifest.difficulty,
    estMinutes: manifest.est_minutes,
    bugClass: manifest.bug_class,
    taskMd: pack.taskMd,
    srcFiles: pack.srcFiles,
    fixtures: pack.fixtures,
    runCmd: manifest.run_cmd,
    expectedOutput: manifest.expected_output,
  }
  const name = camel(pack.id)
  return `${GENERATED}
import type { BugfixPack } from "@/lib/bugfix/packs/types"
import { packToScenario } from "@/lib/bugfix/packs/scenario"

export const ${name}Pack: BugfixPack = ${JSON.stringify(obj, null, 2)}

export const ${name}Scenario = packToScenario(${name}Pack)
`
}

function sealedModule(pack) {
  const { manifest, sealed } = pack
  const obj = {
    packId: manifest.id,
    solutionMd: pack.solutionMd,
    bugLocation: sealed.bugLocation,
    bugSummary: sealed.bugSummary,
    minimalFix: sealed.minimalFix,
    survivalStory: sealed.survivalStory,
    redHerrings: sealed.redHerrings,
    complexityAnswer: sealed.complexityAnswer,
    phase2: {
      specPatch: manifest.phase2.spec_patch,
      fixturePatch: manifest.phase2.fixture_patch,
      expectedOutputV2: manifest.phase2.expected_output_v2,
    },
    buggyOutput: manifest.buggy_output,
    debriefRubric: sealed.debriefRubric,
  }
  return `${GENERATED}
import type { SealedPackContent } from "@/lib/bugfix/packs/types"

if (typeof window !== "undefined") {
  throw new Error("Sealed pack content must never load in the browser.")
}

export const sealed: SealedPackContent = ${JSON.stringify(obj, null, 2)}
`
}

function packIndexModule(ids) {
  const imports = ids
    .map((id) => `import { ${camel(id)}Pack, ${camel(id)}Scenario } from "./${id}"`)
    .join("\n")
  const scenarioList = ids.map((id) => `  ${camel(id)}Scenario,`).join("\n")
  const packList = ids.map((id) => `  ${camel(id)}Pack,`).join("\n")
  return `${GENERATED}
/**
 * Bugfix PACK registry (stdout-oracle, sealed variant). Kept OUT of the locked
 * legacy-10 bank (realWorldBugFixScenarios); resolves by id through the async lazy
 * loader in lib/scenarios/index.ts.
 */
import type { BugFixScenario } from "../../../types"
import type { BugfixPack } from "@/lib/bugfix/packs/types"
${imports}

export const bugfixPackScenarios: BugFixScenario[] = [
${scenarioList}
]

/** Raw client-safe pack contracts (parallel to bugfixPackScenarios), for validation. */
export const bugfixPacks: BugfixPack[] = [
${packList}
]

export default bugfixPackScenarios
`
}

function sealedRegistryModule(ids) {
  const loaders = ids
    .map((id) => `  "${id}": () => import("./${id}.server"),`)
    .join("\n")
  return `${GENERATED}
/**
 * Sealed-pack registry (SERVER-ONLY). The ONLY loader for per-pack sealed modules;
 * imported ONLY by the phase-2 release endpoint, the pack advance endpoint, and the
 * debrief path (enforced by the sealing import-graph test). The window guard is the
 * runtime seal (this repo has no server-only package).
 */
import type { SealedPackContent } from "@/lib/bugfix/packs/types"

if (typeof window !== "undefined") {
  throw new Error("Sealed pack content must never load in the browser.")
}

const SEALED_PACK_LOADERS: Record<string, () => Promise<{ sealed: SealedPackContent }>> = {
${loaders}
}

export function hasSealedPack(packId: string): boolean {
  return Object.prototype.hasOwnProperty.call(SEALED_PACK_LOADERS, packId)
}

export async function loadSealedPack(packId: string): Promise<SealedPackContent | null> {
  const loader = SEALED_PACK_LOADERS[packId]
  if (!loader) return null
  const mod = await loader()
  return mod.sealed
}

export function sealedPackIds(): string[] {
  return Object.keys(SEALED_PACK_LOADERS)
}
`
}

function main() {
  const ids = listPackIds()
  if (ids.length === 0) {
    console.error("No packs found under packs/*/manifest.json")
    process.exit(1)
  }
  for (const id of ids) {
    const pack = loadPack(id)
    writeFileSync(join(CLIENT_DIR, `${id}.ts`), clientModule(pack))
    writeFileSync(join(SEALED_DIR, `${id}.server.ts`), sealedModule(pack))
    console.log(`compiled ${id}`)
  }
  writeFileSync(join(CLIENT_DIR, "index.ts"), packIndexModule(ids))
  writeFileSync(join(SEALED_DIR, "registry.server.ts"), sealedRegistryModule(ids))
  console.log(`regenerated pack index + sealed registry (${ids.length} pack(s))`)
}

main()
