/**
 * Data Engineering Level 9, Module 9.3 — Stream Processing in SQL.
 *
 * The windowing half of streaming, taught with nothing but epoch arithmetic and window functions so
 * every mechanism a stream engine hides inside an operator is visible as a query the learner writes.
 * 9.3.1 implements tumbling windows (integer division as the flooring device) and hopping windows
 * (a join against an enumerated window table, which is literally the shape of the operator's state).
 * 9.3.2 splits the two clocks apart, applies a watermark, and quantifies what late arrivals do to a
 * window that was already emitted. 9.3.3 is a timed re-drill, not a new teach: sql-l5-sessionization
 * owns the LAG -> flag -> running-SUM ladder AND the vendor callout, so this lesson supplies only the
 * per-key operator state, the emit condition (watermark >= last_event_time + gap), and the clock,
 * then grades the goal state.
 *
 * Device: every exercise is a single-file SELECT over a simulated event stream. There is no workspace
 * script in this module because nothing here writes state; the sink-side write lessons live in 9.2.
 *
 * Deliberate deviations from CURRICULUM-MAP.md, all recorded at the point of use below:
 *  - 9.3.1 and 9.3.2 share ONE `stream_events` column shape (event_time_ms AND processing_time_ms)
 *    rather than two different shapes under one table name. One name must not mean two shapes inside
 *    one module, and carrying the second clock from the start sets up 9.3.2's reveal.
 *  - 9.3.2 seeds 5 events strictly past the 10-minute watermark plus three deliberately near-boundary
 *    arrivals (one at exactly 600000 ms of lateness). The map's "late by 2 to 25 minutes" range would
 *    otherwise make the watermark predicate untested by the data.
 *  - 9.3.3 seeds 29 page views rather than 28, still forming 7 sessions, so the average-events-per-
 *    session drill grades 4.1 instead of a suspiciously round 28/7 = 4.0.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and re-checked
 * by single-file-reference-solutions.test.ts. Content rules: no em dashes in learner prose; every
 * prompt leads with the deliverable; practice never ships a referenceSolution.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 9.3.1 seeds — a 30-minute slice of a clickstream, plus the window table a hopping
// operator keeps in state. Epoch milliseconds because that is what every stream payload actually
// carries (Kafka record timestamps, Kinesis ApproximateArrivalTimestamp, and a JSON `event_time_ms`
// field are all integers, not formatted strings). The slice starts at 1767286800000, which is
// 2026-01-01 17:00:00 UTC and is deliberately aligned to both 5 and 10 minutes so bucket boundaries
// are readable. `processing_time_ms` rides along unused in this lesson and becomes the whole subject
// of the next one.
//
// Tumbling 5-minute counts by design: 5, 9, 3, 12, 7, 4 (40 events, no two windows tied). Event 7018
// sits EXACTLY on the 15-minute boundary (1767287700000), which is one hopping window's exclusive
// end and the next one's inclusive start. It is the row that punishes a BETWEEN range join: half-open
// bounds put it in two windows, BETWEEN puts it in three.
// ---------------------------------------------------------------------------

const STREAM_EVENTS_SEED = `CREATE TABLE stream_events (
  event_id           INTEGER,
  user_id            INTEGER,
  event_type         TEXT,
  event_time_ms      INTEGER,  -- when the event HAPPENED, stamped by the client
  processing_time_ms INTEGER   -- when the pipeline SAW it; ignored until the next lesson
);
INSERT INTO stream_events (event_id, user_id, event_type, event_time_ms, processing_time_ms) VALUES
  (7001, 101,     'page_view', 1767286812000, 1767286816000),
  (7002, 102,        'search', 1767286847000, 1767286853000),
  (7003, 101,  'product_view', 1767286930000, 1767286933000),
  (7004, 103,     'page_view', 1767287001000, 1767287010000),
  (7005, 102,   'add_to_cart', 1767287088000, 1767287093000),
  (7006, 104,     'page_view', 1767287105000, 1767287109000),
  (7007, 104,        'search', 1767287122000, 1767287129000),
  (7008, 105,     'page_view', 1767287160000, 1767287165000),
  (7009, 104,  'product_view', 1767287201000, 1767287207000),
  (7010, 104,   'add_to_cart', 1767287215000, 1767287223000),
  (7011, 106,     'page_view', 1767287270000, 1767287273000),
  (7012, 101,      'checkout', 1767287301000, 1767287312000),
  (7013, 103,        'search', 1767287340000, 1767287344000),
  (7014, 105,  'product_view', 1767287388000, 1767287394000),
  (7015, 101,     'page_view', 1767287440000, 1767287445000),
  (7016, 106,        'search', 1767287515000, 1767287523000),
  (7017, 104,      'checkout', 1767287660000, 1767287664000),
  (7018, 102,     'page_view', 1767287700000, 1767287706000),
  (7019, 103,  'product_view', 1767287718000, 1767287721000),
  (7020, 104,     'page_view', 1767287735000, 1767287742000),
  (7021, 105,        'search', 1767287760000, 1767287765000),
  (7022, 101,   'add_to_cart', 1767287788000, 1767287797000),
  (7023, 106,  'product_view', 1767287810000, 1767287814000),
  (7024, 102,        'search', 1767287844000, 1767287850000),
  (7025, 104,     'page_view', 1767287871000, 1767287874000),
  (7026, 103,      'checkout', 1767287899000, 1767287911000),
  (7027, 105,   'add_to_cart', 1767287920000, 1767287925000),
  (7028, 101,     'page_view', 1767287955000, 1767287959000),
  (7029, 106,      'checkout', 1767287990000, 1767287998000),
  (7030, 104,        'search', 1767288003000, 1767288008000),
  (7031, 102,  'product_view', 1767288050000, 1767288057000),
  (7032, 101,      'checkout', 1767288101000, 1767288111000),
  (7033, 105,     'page_view', 1767288155000, 1767288159000),
  (7034, 104,   'add_to_cart', 1767288200000, 1767288206000),
  (7035, 103,     'page_view', 1767288242000, 1767288245000),
  (7036, 106,        'search', 1767288290000, 1767288299000),
  (7037, 105,      'checkout', 1767288310000, 1767288321000),
  (7038, 104,     'page_view', 1767288402000, 1767288407000),
  (7039, 102,     'page_view', 1767288500000, 1767288504000),
  (7040, 101,        'search', 1767288595000, 1767288602000);`

// The hopping operator's window table: 10-minute windows sliding every 5 minutes. It reaches one hop
// BEFORE the first event and one hop past the last so every event in the slice lands in exactly two
// windows, which is the whole point of the hop.
const HOP_WINDOWS_SEED = `CREATE TABLE hop_windows (
  window_start_ms INTEGER,  -- inclusive
  window_end_ms   INTEGER   -- exclusive: the half-open bound every stream engine uses
);
INSERT INTO hop_windows (window_start_ms, window_end_ms) VALUES
  (1767286500000, 1767287100000),
  (1767286800000, 1767287400000),
  (1767287100000, 1767287700000),
  (1767287400000, 1767288000000),
  (1767287700000, 1767288300000),
  (1767288000000, 1767288600000),
  (1767288300000, 1767288900000);`

const WINDOWS_SEED = `${STREAM_EVENTS_SEED}

${HOP_WINDOWS_SEED}`

// ---------------------------------------------------------------------------
// Lesson 9.3.2 seeds — the same table shape, a different 30-minute slice, and the second clock now
// carrying real signal. Five events land strictly past a 10-minute watermark (12, 15, 18, 21, and 25
// minutes of lateness), three more are elevated but on time (8 minutes, 9.5 minutes, and one at
// EXACTLY 600000 ms so a `>=` predicate fails and a `>` predicate passes), and the remaining 28
// arrive within 5 to 31 seconds. The five late events land in three different 5-minute windows
// (three, one, and one) so the changed-window practice returns three rows and the biggest-gain drill
// has a unique winner.
// ---------------------------------------------------------------------------

const LATE_EVENTS_SEED = `CREATE TABLE stream_events (
  event_id           INTEGER,
  user_id            INTEGER,
  event_type         TEXT,
  event_time_ms      INTEGER,  -- when the event HAPPENED (the client's clock)
  processing_time_ms INTEGER   -- when the pipeline SAW it (the platform's clock)
);
INSERT INTO stream_events (event_id, user_id, event_type, event_time_ms, processing_time_ms) VALUES
  (8001, 201,     'page_view', 1767286820000, 1767286828000),
  (8002, 202,        'search', 1767286865000, 1767286879000),
  (8003, 203,     'page_view', 1767286920000, 1767286926000),
  (8004, 204,   'add_to_cart', 1767286990000, 1767287470000),
  (8005, 201,  'product_view', 1767287040000, 1767287049000),
  (8006, 205,     'page_view', 1767287085000, 1767287107000),
  (8007, 206,     'page_view', 1767287110000, 1767287121000),
  (8008, 202,        'search', 1767287150000, 1767287870000),
  (8009, 201,  'product_view', 1767287195000, 1767287202000),
  (8010, 205,      'checkout', 1767287240000, 1767288320000),
  (8011, 203,     'page_view', 1767287280000, 1767287296000),
  (8012, 204,        'search', 1767287325000, 1767287337000),
  (8013, 202,   'add_to_cart', 1767287370000, 1767288870000),
  (8014, 206,     'page_view', 1767287415000, 1767287434000),
  (8015, 201,        'search', 1767287480000, 1767287485000),
  (8016, 203,  'product_view', 1767287540000, 1767288140000),
  (8017, 205,     'page_view', 1767287600000, 1767287627000),
  (8018, 202,      'checkout', 1767287670000, 1767287683000),
  (8019, 204,     'page_view', 1767287705000, 1767287715000),
  (8020, 201,        'search', 1767287740000, 1767287764000),
  (8021, 206,  'product_view', 1767287785000, 1767287791000),
  (8022, 203,   'add_to_cart', 1767287820000, 1767288720000),
  (8023, 205,     'page_view', 1767287860000, 1767287891000),
  (8024, 202,        'search', 1767287900000, 1767287909000),
  (8025, 204,      'checkout', 1767287940000, 1767287957000),
  (8026, 201,     'page_view', 1767287985000, 1767287997000),
  (8027, 205,        'search', 1767288010000, 1767288017000),
  (8028, 203,     'page_view', 1767288060000, 1767288080000),
  (8029, 206,   'add_to_cart', 1767288110000, 1767289370000),
  (8030, 202,  'product_view', 1767288170000, 1767288185000),
  (8031, 204,     'page_view', 1767288220000, 1767288228000),
  (8032, 201,      'checkout', 1767288280000, 1767288309000),
  (8033, 205,     'page_view', 1767288320000, 1767288890000),
  (8034, 203,        'search', 1767288400000, 1767288411000),
  (8035, 206,     'page_view', 1767288490000, 1767288508000),
  (8036, 202,     'page_view', 1767288580000, 1767288586000);`

// ---------------------------------------------------------------------------
// Lesson 9.3.3 seeds — 29 page views from 3 users forming exactly 7 sessions under a 30-minute
// inactivity rule, starting at 1767250800000 (2026-01-01 07:00:00 UTC). Three cases are planted on
// purpose: users 501 and 503 each have a gap of EXACTLY 30 minutes inside a session (which must NOT
// split, because the rule is "exceeds 30 minutes"), and user 501's last session holds a single event,
// so the per-session rollup has to survive a zero-minute duration. Session durations are 60, 47, 45,
// 42, 26, 12, and 0 minutes: all distinct, so the longest-first ordering is unambiguous. The 45 is
// 503's first session and it exists to probe drill-2's `> 45` threshold: a `>=` there returns a third
// row, so the strict comparison is graded rather than merely asserted.
// ---------------------------------------------------------------------------

const PAGE_VIEW_EVENTS_SEED = `CREATE TABLE page_view_events (
  user_id       INTEGER,
  event_time_ms INTEGER,  -- epoch milliseconds; 30 minutes is 1800000
  page          TEXT
);
INSERT INTO page_view_events (user_id, event_time_ms, page) VALUES
  (501, 1767250800000,     'home'),
  (501, 1767251040000,   'search'),
  (501, 1767251340000,  'product'),
  (501, 1767251580000,  'product'),
  (501, 1767251880000,     'cart'),
  (501, 1767252360000, 'checkout'),
  (501, 1767256200000,     'home'),
  (501, 1767256500000,   'search'),
  (501, 1767258000000,  'product'),
  (501, 1767259800000,     'cart'),
  (501, 1767262800000,     'home'),
  (502, 1767251100000,     'home'),
  (502, 1767251520000,   'search'),
  (502, 1767252000000,  'product'),
  (502, 1767252780000,  'product'),
  (502, 1767253620000,     'cart'),
  (502, 1767256080000,     'home'),
  (502, 1767256560000,   'search'),
  (502, 1767256980000,  'product'),
  (502, 1767257400000,     'cart'),
  (502, 1767257940000, 'checkout'),
  (502, 1767258900000,     'home'),
  (503, 1767251400000,     'home'),
  (503, 1767252300000,   'search'),
  (503, 1767254100000,  'product'),
  (503, 1767259200000,     'home'),
  (503, 1767259380000,  'product'),
  (503, 1767259680000,     'cart'),
  (503, 1767259920000, 'checkout');`

// ---------------------------------------------------------------------------
// Module 9.3 — Stream Processing in SQL
// ---------------------------------------------------------------------------

const tumblingHoppingWindows: SqlLesson = {
  id: "de-l9-tumbling-hopping-windows",
  title: "Tumbling and Hopping Windows",
  summary:
    "Bucket an event stream into tumbling windows with epoch arithmetic, then into overlapping hopping windows with a join against a window table.",
  seoDescription:
    "A tumbling window puts every event in exactly one bucket. A hopping window has a size and a smaller hop, so windows overlap and events land in several.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "tumbling windows",
    "hopping windows",
    "event-time bucketing",
    "epoch arithmetic",
    "GROUP BY",
    "range joins",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Why a stream needs windows at all

A stream has no end, so no aggregate over it can ever finish. "How many checkouts happened" has no answer against an infinite log; "how many checkouts happened between 17:05 and 17:10" has exactly one. A **window** is the device that turns an unbounded stream into a sequence of finite groups you can actually aggregate, and every stream engine ships the same three kinds: tumbling, hopping, and session.

Deepen-not-repeat note: \`sql-l5-system-design-round-reasoning\` introduced the word "tumbling window" as vocabulary. What is new here is implementing one, the half-open bound that keeps events from being double counted, and hopping windows, which that lesson never touched.

## Tumbling: fixed size, no overlap

A tumbling window has a size and nothing else. Windows sit end to end, they never overlap, and every event belongs to **exactly one** of them. That property is what makes tumbling windows safe for anything you sum, because no event is counted twice.

You do not need a window table to build them. Integer division floors an event time down onto the window it belongs to:

\`\`\`sql
(event_time_ms / 300000) * 300000
\`\`\`

Read it left to right. \`event_time_ms / 300000\` in SQLite is integer division when both operands are integers, so it throws away the remainder and tells you how many whole 5-minute windows have elapsed since the epoch. Multiplying back by 300000 turns that window index into the window's start time. Change 300000 to 60000 and you have 1-minute windows; change it to 3600000 and you have hourly ones. This one expression is the whole mechanism.

The bounds are **half-open**: a window covers \`[start, start + size)\`, start inclusive and end exclusive. An event landing exactly on a boundary belongs to the window it opens, never to the one that just closed.

## Hopping: fixed size, fixed hop, deliberate overlap

A hopping window (Flink and Spark call this a **sliding** window; be careful, because in Azure Stream Analytics and the Fabric Eventstreams built on it, Sliding is a distinct window type that emits only when an event enters or leaves it, and Hopping is the one with the fixed hop) has two numbers: a size and a hop. Size 10 minutes with a hop of 5 minutes means a new window opens every 5 minutes and each one covers 10 minutes, so consecutive windows overlap by half and every event falls into **two** of them. That is the point: hopping windows smooth a metric, which is why "10-minute rolling error rate, refreshed every minute" is a hopping window and not a tumbling one.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["event (min:sec into the slice)", "tumbling 5 min", "hopping window A", "hopping window B"],
  "rows": [
    ["00:12", "[00, 05)", "[-05, 05)", "[00, 10)"],
    ["05:05", "[05, 10)", "[00, 10)", "[05, 15)"],
    ["10:40", "[10, 15)", "[05, 15)", "[10, 20)"],
    ["15:00", "[15, 20)", "[10, 20)", "[15, 25)"],
    ["29:55", "[25, 30)", "[20, 30)", "[25, 35)"]
  ],
  "highlightCols": ["tumbling 5 min"],
  "caption": "One timeline sliced twice. Tumbling puts each event in exactly one bucket; hopping (size 10, hop 5) puts each event in two, so the hopping counts sum to twice the event total."
}
\`\`\`

No single \`GROUP BY\` expression can put one row into two groups, so hopping windows are built differently: you enumerate the windows in a table and **join** the events against it on a range.

\`\`\`sql
FROM hop_windows w
JOIN stream_events e
  ON e.event_time_ms >= w.window_start_ms
 AND e.event_time_ms <  w.window_end_ms
\`\`\`

That join is not a workaround. It is the same shape the engine's operator keeps in memory: a set of open windows, each accumulating the events that fall inside it, each closing on its own schedule.

Look again at the 15:00 row of the diagram. That event lands exactly on a boundary, and the seed you are about to query contains one just like it.

**Common mistake:** writing the range join with \`BETWEEN\`. \`BETWEEN\` is inclusive on both ends, so an event landing exactly on \`window_end_ms\` gets counted in the window that just closed AND in the two it genuinely belongs to, and your hopping totals quietly exceed twice the event count. Half-open bounds (\`>= start AND < end\`) are the convention every engine uses, and matching them is the difference between a correct answer and one that is off by a rounding error nobody notices for a month.

**Interview nuance:** "tumbling versus hopping versus session" is a standard vocabulary check, and the answer that lands is the one that names the invariant rather than the shape. Tumbling: every event in exactly one window, safe to sum. Hopping: overlapping, so an event contributes to several windows and totals across windows are intentionally larger than the event count. Session: data-driven boundaries, covered in the closing lesson of this module. If the loop is a cloud-specific one, check whose vocabulary you are speaking: "sliding" is the overlapping fixed-hop window in Flink and Spark, but a separate event-triggered window type in Azure Stream Analytics and Fabric.

> **On a real platform this differs.** Older Flink SQL writes these as group windows, \`TUMBLE(event_time, INTERVAL '5' MINUTE)\` and \`HOP(event_time, INTERVAL '5' MINUTE, INTERVAL '10' MINUTE)\`; current Flink uses the windowing table-valued functions instead, \`TUMBLE(TABLE t, DESCRIPTOR(event_time), INTERVAL '5' MINUTE)\` and \`HOP(TABLE t, DESCRIPTOR(event_time), INTERVAL '5' MINUTE, INTERVAL '10' MINUTE)\`, with the group-window form deprecated from 1.20 onward. Spark Structured Streaming writes \`window(event_time, "10 minutes", "5 minutes")\`, and Microsoft Fabric Eventstreams offers tumbling, hopping, and session windows in its query editor alongside two of its own. All of them are doing the bucketing you are about to write by hand, holding the open windows as operator state and emitting each one when a watermark says it is safe. The arithmetic is identical; the engine just owns the state.`,
    demoSeedSql: STREAM_EVENTS_SEED,
    demoCode: `-- The tumbling bucket expression next to the raw event time. Watch the first five events
-- collapse onto one window start, and the sixth open the next window.
SELECT event_id,
       event_time_ms,
       (event_time_ms / 300000) * 300000 AS window_start_ms,
       event_time_ms - (event_time_ms / 300000) * 300000 AS ms_into_window
FROM stream_events
ORDER BY event_time_ms
LIMIT 8;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-tumbling-hopping-windows-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns the 5-minute tumbling window counts of the stream, as \`(window_start_ms, event_count)\`, oldest window first, over \`stream_events(event_id, user_id, event_type, event_time_ms, processing_time_ms)\`.

Bucket each event by its \`event_time_ms\` into a 5-minute window (300000 ms) and count the events per window. Alias the columns exactly \`window_start_ms\` and \`event_count\`.`,
    starterCode: `-- 5-minute tumbling window counts, oldest window first.
SELECT
  -- one row per 5-minute window, holding that window's event count
FROM stream_events;`,
    hints: [
      "Integer division floors: `event_time_ms / 300000` is the window index, and multiplying it back by 300000 gives the window start.",
      "Group by that expression, then `COUNT(*) AS event_count`.",
      "`ORDER BY window_start_ms` puts the oldest window first.",
    ],
    referenceSolution: `SELECT (event_time_ms / 300000) * 300000 AS window_start_ms,
       COUNT(*) AS event_count
FROM stream_events
GROUP BY window_start_ms
ORDER BY window_start_ms;`,
    singleFile: {
      seedSql: STREAM_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["window_start_ms", "event_count"],
        rows: [
          [1767286800000, 5],
          [1767287100000, 9],
          [1767287400000, 3],
          [1767287700000, 12],
          [1767288000000, 7],
          [1767288300000, 4],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-tumbling-hopping-windows-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the event count in every hopping window, as \`(window_start_ms, window_end_ms, event_count)\`, oldest window first, over \`stream_events\` and \`hop_windows(window_start_ms, window_end_ms)\`.

\`hop_windows\` already enumerates the 10-minute windows that open every 5 minutes, so an event belongs to two of them and the counts across windows add up to more than the number of events. Treat each window as half-open: an event counts when its \`event_time_ms\` is at or after \`window_start_ms\` and strictly before \`window_end_ms\`. Alias the count exactly \`event_count\`.`,
    starterCode: `-- Event count in every 10-minute hopping window (hop 5 minutes), oldest first.
SELECT
  -- one row per enumerated window, holding the events that fall inside it
FROM hop_windows w;`,
    hints: [
      "Join the events to the windows on a range rather than an equality: `e.event_time_ms >= w.window_start_ms AND e.event_time_ms < w.window_end_ms`.",
      "Group by both window columns so each enumerated window keeps its own row.",
    ],
    singleFile: {
      seedSql: WINDOWS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["window_start_ms", "window_end_ms", "event_count"],
        rows: [
          [1767286500000, 1767287100000, 5],
          [1767286800000, 1767287400000, 14],
          [1767287100000, 1767287700000, 12],
          [1767287400000, 1767288000000, 15],
          [1767287700000, 1767288300000, 19],
          [1767288000000, 1767288600000, 11],
          [1767288300000, 1767288900000, 4],
        ],
      },
    },
  },
  extraPractice: [
    // Reviewed and accepted 2026-08-02: bucketing this drill on processing_time_ms instead of
    // event_time_ms yields a different 7-window distribution but the SAME busiest window
    // (1767287700000, 12), so LIMIT 1 hides the wrong clock here. Left as is deliberately. The clock
    // cannot be graded by a processing-time nudge: window 1767287700000 leads by 3 on the processing
    // clock too, and closing that gap would need four events arriving minutes late, which is exactly
    // the reveal 9.3.2 owns and this seed's comment promises not to spend early. The Apply and drills
    // 2 and 3 all reject processing-time bucketing, so the clock is graded three times in this lesson.
    {
      id: "de-l9-tumbling-hopping-windows-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the busiest 5-minute tumbling window as \`(window_start_ms, event_count)\`, over \`stream_events\`.`,
      starterCode: `-- The single busiest 5-minute tumbling window.
SELECT
FROM stream_events;`,
      hints: [
        "Build the same tumbling counts as the Apply, then order by the count descending.",
        "`LIMIT 1` keeps only the top window.",
      ],
      referenceSolution: `SELECT (event_time_ms / 300000) * 300000 AS window_start_ms,
       COUNT(*) AS event_count
FROM stream_events
GROUP BY window_start_ms
ORDER BY event_count DESC, window_start_ms
LIMIT 1;`,
      singleFile: {
        seedSql: STREAM_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["window_start_ms", "event_count"], rows: [[1767287700000, 12]] },
      },
    },
    {
      id: "de-l9-tumbling-hopping-windows-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the number of distinct users active in each 5-minute tumbling window, as \`(window_start_ms, distinct_users)\`, oldest window first, over \`stream_events\`.`,
      starterCode: `-- Distinct users per 5-minute tumbling window.
SELECT
FROM stream_events;`,
      hints: [
        "`COUNT(DISTINCT user_id)` counts each user once per window no matter how many events they fired.",
        "Alias it exactly `distinct_users`.",
      ],
      referenceSolution: `SELECT (event_time_ms / 300000) * 300000 AS window_start_ms,
       COUNT(DISTINCT user_id) AS distinct_users
FROM stream_events
GROUP BY window_start_ms
ORDER BY window_start_ms;`,
      singleFile: {
        seedSql: STREAM_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["window_start_ms", "distinct_users"],
          rows: [
            [1767286800000, 3],
            [1767287100000, 5],
            [1767287400000, 3],
            [1767287700000, 6],
            [1767288000000, 6],
            [1767288300000, 4],
          ],
        },
      },
    },
    {
      id: "de-l9-tumbling-hopping-windows-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns user 104's activity in 1-minute tumbling windows, as \`(window_start_ms, event_count)\`, oldest window first, over \`stream_events\`. Only windows in which user 104 fired at least one event should appear.`,
      starterCode: `-- User 104's events bucketed into 1-minute tumbling windows.
SELECT
FROM stream_events;`,
      hints: [
        "A 1-minute window is 60000 ms, so the bucket expression becomes `(event_time_ms / 60000) * 60000`.",
        "Filter to user 104 in a `WHERE` clause before grouping, so empty windows never appear.",
      ],
      referenceSolution: `SELECT (event_time_ms / 60000) * 60000 AS window_start_ms,
       COUNT(*) AS event_count
FROM stream_events
WHERE user_id = 104
GROUP BY window_start_ms
ORDER BY window_start_ms;`,
      singleFile: {
        seedSql: STREAM_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["window_start_ms", "event_count"],
          rows: [
            [1767287100000, 2],
            [1767287160000, 2],
            [1767287640000, 1],
            [1767287700000, 1],
            [1767287820000, 1],
            [1767288000000, 1],
            [1767288180000, 1],
            [1767288360000, 1],
          ],
        },
      },
    },
  ],
}

const watermarksAndLateEvents: SqlLesson = {
  id: "de-l9-watermarks-late-events",
  title: "Event Time, Watermarks, and Late Events",
  summary:
    "Separate event time from processing time, apply a watermark to decide what counts as late, and measure what stragglers do to an already-emitted window.",
  estimatedMinutes: 28,
  difficulty: "hard",
  skills: [
    "event time vs processing time",
    "watermarks",
    "allowed lateness",
    "late-event policy",
    "conditional aggregation",
    "CASE",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## Two clocks, and why they drift apart

Every event carries two timestamps. **Event time** is when the thing happened, stamped by whatever produced it. **Processing time** is when your pipeline saw it. In the previous lesson you bucketed on \`event_time_ms\` and ignored \`processing_time_ms\` entirely; this lesson is about the gap between them.

The gap is never zero and it is rarely small. A phone goes through a tunnel and buffers 20 minutes of taps. A retry queue drains after an outage. A partition rebalances and a consumer pauses. A client's clock is simply wrong. Every one of those makes an event arrive long after it happened, and the difference is the event's **lateness**:

\`\`\`sql
processing_time_ms - event_time_ms
\`\`\`

Windowing on processing time makes lateness invisible and the numbers wrong: a tunnel full of 17:05 taps lands at 17:25 and inflates the 17:25 window while the 17:05 window under-reports forever. Windowing on event time puts every event in the bucket where it belongs, which is correct but raises a new question with no free answer: when is a window done?

## A watermark is a promise about completeness

A **watermark** is the engine's assertion that all events with an event time at or before time \`t\` have arrived. It advances behind the largest event time observed, trailing it by a **bounded out-of-orderness** you choose. Flink names that setting \`forBoundedOutOfOrderness\`, and its SQL form is the \`- INTERVAL '10' MINUTE\` inside a \`WATERMARK\` clause. With a 10-minute watermark, an event whose lateness exceeds 10 minutes arrives after the engine already declared its window complete, so the engine calls it **late**.

Do not confuse that trailing interval with **allowed lateness**, which is a different knob covered below. Bounded out-of-orderness decides when a window is declared complete; allowed lateness decides how long its state survives afterwards.

That single number is the completeness-versus-latency knob, and it has no correct setting. Set it to 1 minute and dashboards update fast but drop stragglers. Set it to an hour and almost nothing is missed but every window emits an hour behind. Interviewers ask what you would pick precisely because there is no right answer, only a tradeoff you can defend.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["event_id", "event time", "processing time", "lateness", "10-minute watermark"],
  "rows": [
    [8003, "17:02:00", "17:02:06", "6 s", "on time"],
    [8004, "17:03:10", "17:11:10", "8 min", "on time"],
    [8016, "17:12:20", "17:22:20", "10 min exactly", "on time, the boundary"],
    [8008, "17:05:50", "17:17:50", "12 min", "LATE"],
    [8013, "17:09:30", "17:34:30", "25 min", "LATE"]
  ],
  "highlightCols": ["lateness"],
  "caption": "The watermark is a line sweeping through processing time. Lateness is measured against event time, so the verdict depends on the gap, not on when the event happened."
}
\`\`\`

Note the boundary row. The watermark asserts "everything at or before t has arrived", so an event exactly at the allowed lateness is still inside the promise. Late means strictly greater. Writing \`>=\` instead of \`>\` misclassifies exactly the events that sit on the line, which is exactly where a grader looks.

One thing to notice before you write the queries: they test \`processing_time_ms - event_time_ms > 600000\` rather than comparing an event time against a moving watermark line. That substitution is only valid because the on-time events in this seed arrive within seconds, so the largest event time observed tracks the wall clock and the watermark sits a flat 10 minutes behind both. On a real stream the watermark lags the maximum event time rather than the clock, and the two come apart the moment a source goes idle and stops advancing it.

## Where late events go

This is asked openly and word for word, and there are four canonical answers. Naming all four with a tradeoff each is the strong response.

1. **Drop them.** Simplest, cheapest, and the right call when the metric tolerates a small undercount. It is also silent, so nobody notices the loss.
2. **Allowed lateness updates.** Keep the window's state alive past its emission and re-emit a corrected result when a straggler shows up. This is the second knob: allowed lateness is the grace period that begins AFTER the watermark has already passed the window, during which the window's state is retained so a straggler can trigger a restatement instead of being dropped. Correct, but every downstream consumer must accept a restatement of a number it already read.
3. **Side-output to a dead-letter queue.** Route late events to a separate stream or table with the record, the reason, and a timestamp, then alert on the volume. Nothing is lost, and someone gets to decide what to do about it.
4. **Append-only storage plus a windowed reprocess.** Land every event raw, then recompute a bounded rolling window (the last few days) on a schedule so late arrivals self-heal without any streaming state at all. This is the pattern most batch-leaning teams actually ship.

## Flink, in two words a junior needs

Awareness level, not implementation. **Checkpointing** is Flink's periodic consistent snapshot of operator state: barriers flow through the stream alongside the records, and on failure the job restarts from the last completed checkpoint. That mechanism is what makes its exactly-once state claim true, and it is the reason a Flink job's recovery story is "resume from a snapshot" rather than "reprocess from the beginning". **Backpressure** is a slow operator forcing the stages upstream of it to throttle so buffers do not blow up; from outside the job it looks like consumer lag climbing steadily with no error in the log. Say those two words correctly and stop there. Tuning either one is senior scope. On AWS, stateful Flink jobs run on Amazon Managed Service for Apache Flink, which was renamed from Kinesis Data Analytics in 2023; the old name still circulates in prep material and should not be the one you say out loud.

**Common mistake:** subtracting in the wrong direction and getting negative lateness, then filtering it away. Lateness is \`processing_time_ms - event_time_ms\`, arrival minus occurrence, and it is positive by construction unless a client clock is ahead of the platform's, which is itself a real finding worth reporting rather than hiding.

**Interview nuance:** event time versus processing time is the single most transferable streaming concept, and the way to prove you own it is with the incident story rather than the definition. "Yesterday's number changed overnight" is almost always a window that was emitted before its late events arrived, and the fix is stated as a policy choice from the four options above, not as a bug.

> **On a real platform this differs.** Flink declares a watermark strategy on the source (\`WATERMARK FOR event_time AS event_time - INTERVAL '10' MINUTE\`) and tracks it per partition, taking the minimum across partitions so one idle partition can stall the whole job. Spark Structured Streaming spells the same idea \`withWatermark("event_time", "10 minutes")\` and uses it to decide when state can be dropped. Here the watermark is a constant in a predicate, which makes the arithmetic visible; on a platform it is a moving line the engine maintains for you, and the thing you actually configure is the out-of-orderness budget, with allowed lateness configured separately on the window.`,
    demoSeedSql: LATE_EVENTS_SEED,
    demoCode: `-- The two clocks side by side, worst arrivals first. Everything above 600000 ms of lateness
-- is past a 10-minute watermark.
SELECT event_id,
       event_time_ms,
       processing_time_ms,
       (processing_time_ms - event_time_ms) / 1000 AS lateness_seconds,
       CASE WHEN processing_time_ms - event_time_ms > 600000 THEN 'late' ELSE 'on time' END AS verdict
FROM stream_events
ORDER BY lateness_seconds DESC
LIMIT 8;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-watermarks-late-events-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every event a 10-minute watermark would treat as late, as \`(event_id, event_time_ms, late_by_seconds)\`, latest-arriving first, over \`stream_events(event_id, user_id, event_type, event_time_ms, processing_time_ms)\`.

An event is late when its lateness is strictly more than 10 minutes (600000 ms); an event exactly on the boundary is still on time. Report \`late_by_seconds\` in whole seconds, and order by processing time descending so the last arrival is at the top.`,
    starterCode: `-- Events past a 10-minute watermark, latest-arriving first.
SELECT
  -- event_id, event_time_ms, and how many seconds late the event was
FROM stream_events;`,
    hints: [
      "Lateness is `processing_time_ms - event_time_ms`; keep the rows where that is greater than 600000.",
      "Divide the same difference by 1000 for whole seconds, and order by `processing_time_ms DESC`.",
    ],
    referenceSolution: `SELECT event_id,
       event_time_ms,
       (processing_time_ms - event_time_ms) / 1000 AS late_by_seconds
FROM stream_events
WHERE processing_time_ms - event_time_ms > 600000
ORDER BY processing_time_ms DESC;`,
    singleFile: {
      seedSql: LATE_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["event_id", "event_time_ms", "late_by_seconds"],
        rows: [
          [8029, 1767288110000, 1260],
          [8013, 1767287370000, 1500],
          [8022, 1767287820000, 900],
          [8010, 1767287240000, 1080],
          [8008, 1767287150000, 720],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-watermarks-late-events-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns every 5-minute tumbling window whose final count differs from the count it would have reported at watermark time, as \`(window_start_ms, on_time_count, final_count)\`, oldest window first, over the same \`stream_events\` table.

Bucket on \`event_time_ms\` into 5-minute windows (300000 ms). \`on_time_count\` counts only the events whose lateness is at most 10 minutes (600000 ms), which is what the window held when the watermark closed it. \`final_count\` counts everything that eventually landed in the window. Keep only the windows where the two disagree, and alias the columns exactly as named.`,
    starterCode: `-- 5-minute windows whose count changed after the watermark closed them.
SELECT
  -- window_start_ms, the count at watermark time, and the count after the stragglers landed
FROM stream_events;`,
    hints: [
      "Two counts over the same group: `COUNT(*)` for the final number, and a `SUM(CASE WHEN ... THEN 1 ELSE 0 END)` for the on-time one.",
    ],
    singleFile: {
      seedSql: LATE_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["window_start_ms", "on_time_count", "final_count"],
        rows: [
          [1767287100000, 4, 7],
          [1767287700000, 7, 8],
          [1767288000000, 5, 6],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-watermarks-late-events-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the worst lateness anywhere in the stream, in whole minutes, as \`(max_lateness_minutes)\`, over \`stream_events\`.`,
      starterCode: `-- The single worst lateness observed, in whole minutes.
SELECT
FROM stream_events;`,
      hints: [
        "Take `MAX(processing_time_ms - event_time_ms)` first, then convert.",
        "One minute is 60000 ms.",
      ],
      referenceSolution: `SELECT MAX(processing_time_ms - event_time_ms) / 60000 AS max_lateness_minutes
FROM stream_events;`,
      singleFile: {
        seedSql: LATE_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["max_lateness_minutes"], rows: [[25]] },
      },
    },
    {
      id: "de-l9-watermarks-late-events-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns each user who produced at least one late event under a 10-minute watermark, with how many, as \`(user_id, late_events)\`, most late events first and then by \`user_id\`, over \`stream_events\`.`,
      starterCode: `-- Users who produced late events, worst offender first.
SELECT
FROM stream_events;`,
      hints: [
        "Filter to the late rows first, then group by `user_id`.",
        "Users with no late events must not appear, which a `WHERE` before the grouping gives you for free.",
      ],
      referenceSolution: `SELECT user_id,
       COUNT(*) AS late_events
FROM stream_events
WHERE processing_time_ms - event_time_ms > 600000
GROUP BY user_id
ORDER BY late_events DESC, user_id;`,
      singleFile: {
        seedSql: LATE_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["user_id", "late_events"],
          rows: [
            [202, 2],
            [203, 1],
            [205, 1],
            [206, 1],
          ],
        },
      },
    },
    {
      id: "de-l9-watermarks-late-events-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every 5-minute tumbling window that gained at least one event from late arrivals, with how many it gained, as \`(window_start_ms, late_events)\`, biggest gain first and then oldest window first, over \`stream_events\` with the same 10-minute watermark. The window at the top of the result is the one that gained the most.`,
      starterCode: `-- Every 5-minute window that gained events after its watermark passed, biggest gain first.
SELECT
FROM stream_events;`,
      hints: [
        "Group by the tumbling bucket, then count only the late rows inside each group with a conditional `SUM`.",
        "Windows that gained nothing must not appear, so filter the groups on that count being above zero.",
        "Order by the gain descending and then by `window_start_ms` so ties read oldest first.",
      ],
      // The HAVING is what makes the strict boundary gradeable. Under `>` this returns 3 rows; under
      // `>=` event 8016 (lateness exactly 600000) adds a 4th, so a wrong comparison fails. The
      // earlier LIMIT 1 form did not: the top window held 3 either way and LIMIT 1 discarded the
      // whole difference, which contradicted the teach's promise about `>=` versus `>`.
      referenceSolution: `SELECT (event_time_ms / 300000) * 300000 AS window_start_ms,
       SUM(CASE WHEN processing_time_ms - event_time_ms > 600000 THEN 1 ELSE 0 END) AS late_events
FROM stream_events
GROUP BY window_start_ms
HAVING late_events > 0
ORDER BY late_events DESC, window_start_ms;`,
      singleFile: {
        seedSql: LATE_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["window_start_ms", "late_events"],
          rows: [
            [1767287100000, 3],
            [1767287700000, 1],
            [1767288000000, 1],
          ],
        },
      },
    },
  ],
}

const sessionization: SqlLesson = {
  id: "de-l9-sessionization",
  title: "Session Windows: The Interview-Speed Sessionization Re-Drill",
  summary:
    "Rebuild the sessionization query unscaffolded against a 15-minute clock, and map it onto the stream engine's session-window operator.",
  estimatedMinutes: 18,
  difficulty: "hard",
  skills: [
    "session windows",
    "gaps and islands",
    "LAG",
    "running SUM",
    "per-session aggregation",
    "timeboxing",
  ],
  teach: {
    estimatedMinutes: 6,
    markdown: `## One drill, two payoffs

Nothing here is new SQL. \`sql-l5-sessionization\` already taught the ladder: \`LAG\` the previous event time, flag a new session when the gap exceeds the timeout, running-sum the flag into a session number. Go back and read it if the shape is not in your fingers yet, because this lesson does not repeat it.

What is worth saying once, because the research says to say it: this exact pattern is a top-cited SQL interview question in its own right (gaps and islands, on every canonical pattern list) **and** it is precisely how a stream engine's session-window operator works. One drill pays twice, which is why it earns a slot in a streaming module rather than being left in the SQL section.

## The operator mapping, which is the new part

The third window type has no fixed size. A **session window** is defined by the data: it opens on an event, extends for as long as the gap to the next event stays under an inactivity timeout, and closes when the timeout elapses with nothing arriving. The engine keeps per-key state, which is nothing more than the last event time it saw for that key, and each arriving event either extends the open window or starts a new one.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["user 501 event", "gap from previous", "operator state transition"],
  "rows": [
    ["08:30", "(first after a long silence)", "open a session"],
    ["08:35", "5 min", "extend"],
    ["09:00", "25 min", "extend"],
    ["09:30", "30 min exactly", "extend, because 30 does not exceed 30"],
    ["10:20", "50 min", "close the session, open a new one"]
  ],
  "highlightCols": ["gap from previous"],
  "caption": "The session-window operator holds one number per key, the last event time, and every arrival either extends the window or closes it. A gap exactly equal to the timeout extends."
}
\`\`\`

There is one thing the operator can do that a batch query never has to think about: **emit**. A session cannot be published the moment its last event lands, because a later event could still extend it. The engine may only close and emit a session once the previous lesson's watermark has passed the last event time plus the gap timeout. That makes session windows the one window type that cannot exist without watermarks, and it is the connection between this lesson and the last one.

**Common mistake:** treating the timeout as inclusive. "A new session starts when the gap exceeds 30 minutes" means strictly greater than 30 minutes; a gap of exactly 30 minutes extends the current session. The seed below contains that case deliberately, and a \`>=\` produces a plausible-looking answer with one session too many.

**Interview nuance:** state which rule you are implementing before you write it. "Thirty minutes of inactivity" almost always means thirty minutes since the previous event, which is what \`LAG\` measures, but some teams mean thirty minutes since the session started, which is a fixed-length window and gives different answers on a steady trickle. Saying that out loud in the first thirty seconds is free signal.

## The clock

The readiness bar for this pattern is narrating and writing it in 12 to 15 minutes. Set a 15-minute timer before you open the Apply. There are no hints on the Apply or the Practice and no starter skeleton, on purpose: the goal state is the grade. The optional drills below keep their hints.

> **On a real platform this differs.** \`sql-l5-sessionization\` already names the native operators and the vendor equivalents, so the one thing to add here is the emit condition: a session may only be published once the watermark has reached \`last_event_time + gap\`. That is a concrete inequality rather than a vague "wait a while", and it is why session windows are the one window type that cannot exist without a watermark. The operator call is also version-sensitive: older Flink SQL writes the group-window form \`SESSION(event_time, INTERVAL '30' MINUTE)\`, while current Flink uses the windowing table-valued function \`SESSION(TABLE t PARTITION BY user_id, DESCRIPTOR(event_time), INTERVAL '30' MINUTE)\`, which makes the per-key state explicit in the syntax. The LAG-plus-running-sum form you are about to write is the batch answer, it is exact over a bounded table, and it is the one an interviewer is asking for.`,
    demoSeedSql: PAGE_VIEW_EVENTS_SEED,
    demoCode: `-- The raw stream, nothing computed. Read the data before you start the timer.
SELECT user_id, event_time_ms, page
FROM page_view_events
ORDER BY user_id, event_time_ms
LIMIT 12;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-sessionization-apply",
    executionMode: "single-file",
    prompt: `Set a 15-minute timer, then write a query that returns each event with the session it belongs to, as \`(user_id, event_time_ms, session_number)\`, ordered by \`user_id\` then \`event_time_ms\`, over \`page_view_events(user_id, event_time_ms, page)\`.

Sessions are per user. A new session starts on a user's first event and whenever the gap from that user's previous event **exceeds** 30 minutes (1800000 ms); a gap of exactly 30 minutes stays in the same session. Number each user's sessions from 1 in time order, and alias the columns exactly as named.`,
    starterCode: `-- Session number per user, 30-minute inactivity rule. 15 minutes on the clock.
`,
    hints: [],
    referenceSolution: `WITH gapped AS (
  SELECT user_id,
         event_time_ms,
         LAG(event_time_ms) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS prev_time_ms
  FROM page_view_events
),
flagged AS (
  SELECT user_id,
         event_time_ms,
         CASE WHEN prev_time_ms IS NULL OR event_time_ms - prev_time_ms > 1800000
              THEN 1 ELSE 0 END AS new_session
  FROM gapped
)
SELECT user_id,
       event_time_ms,
       SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS session_number
FROM flagged
ORDER BY user_id, event_time_ms;`,
    singleFile: {
      seedSql: PAGE_VIEW_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["user_id", "event_time_ms", "session_number"],
        rows: [
          [501, 1767250800000, 1],
          [501, 1767251040000, 1],
          [501, 1767251340000, 1],
          [501, 1767251580000, 1],
          [501, 1767251880000, 1],
          [501, 1767252360000, 1],
          [501, 1767256200000, 2],
          [501, 1767256500000, 2],
          [501, 1767258000000, 2],
          [501, 1767259800000, 2],
          [501, 1767262800000, 3],
          [502, 1767251100000, 1],
          [502, 1767251520000, 1],
          [502, 1767252000000, 1],
          [502, 1767252780000, 1],
          [502, 1767253620000, 1],
          [502, 1767256080000, 2],
          [502, 1767256560000, 2],
          [502, 1767256980000, 2],
          [502, 1767257400000, 2],
          [502, 1767257940000, 2],
          [502, 1767258900000, 2],
          [503, 1767251400000, 1],
          [503, 1767252300000, 1],
          [503, 1767254100000, 1],
          [503, 1767259200000, 2],
          [503, 1767259380000, 2],
          [503, 1767259680000, 2],
          [503, 1767259920000, 2],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-sessionization-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns one row per session, as \`(user_id, session_number, session_start_ms, session_end_ms, events_in_session, duration_minutes)\`, longest duration first and then by \`user_id\` and \`session_number\`, over the same \`page_view_events\` table and the same 30-minute inactivity rule.

\`session_start_ms\` and \`session_end_ms\` are the first and last event times in the session, \`events_in_session\` is how many events it holds, and \`duration_minutes\` is the whole minutes between start and end. A single-event session is a real session with a duration of zero. Alias the columns exactly as named.`,
    starterCode: `-- One row per session: start, end, event count, duration in whole minutes.
`,
    hints: [],
    singleFile: {
      seedSql: PAGE_VIEW_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: [
          "user_id",
          "session_number",
          "session_start_ms",
          "session_end_ms",
          "events_in_session",
          "duration_minutes",
        ],
        rows: [
          [501, 2, 1767256200000, 1767259800000, 4, 60],
          [502, 2, 1767256080000, 1767258900000, 6, 47],
          [503, 1, 1767251400000, 1767254100000, 3, 45],
          [502, 1, 1767251100000, 1767253620000, 5, 42],
          [501, 1, 1767250800000, 1767252360000, 6, 26],
          [503, 2, 1767259200000, 1767259920000, 4, 12],
          [501, 3, 1767262800000, 1767262800000, 1, 0],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-sessionization-drill-1",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the average number of events per session across all users, rounded to 1 decimal, as \`(avg_events_per_session)\`, over \`page_view_events\` with the same 30-minute rule.`,
      starterCode: `-- Average events per session across every user, to 1 decimal.
`,
      hints: [
        "Build the sessions first, collapse them to one row each with a count, then average those counts.",
        "`ROUND(AVG(...), 1)` gives the decimal; multiply by 1.0 if you need to force real division.",
      ],
      referenceSolution: `WITH gapped AS (
  SELECT user_id,
         event_time_ms,
         LAG(event_time_ms) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS prev_time_ms
  FROM page_view_events
),
flagged AS (
  SELECT user_id,
         event_time_ms,
         CASE WHEN prev_time_ms IS NULL OR event_time_ms - prev_time_ms > 1800000
              THEN 1 ELSE 0 END AS new_session
  FROM gapped
),
sessioned AS (
  SELECT user_id,
         SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS session_number
  FROM flagged
),
per_session AS (
  SELECT user_id, session_number, COUNT(*) AS events_in_session
  FROM sessioned
  GROUP BY user_id, session_number
)
SELECT ROUND(AVG(events_in_session * 1.0), 1) AS avg_events_per_session
FROM per_session;`,
      singleFile: {
        seedSql: PAGE_VIEW_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: { columns: ["avg_events_per_session"], rows: [[4.1]] },
      },
    },
    {
      id: "de-l9-sessionization-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns every user whose longest session runs more than 45 minutes, with that length, as \`(user_id, longest_session_minutes)\`, longest first, over \`page_view_events\` with the same 30-minute rule.`,
      starterCode: `-- Users with a session longer than 45 minutes, and how long it ran.
`,
      hints: [
        "Roll the events up to one row per session with its duration, then take the maximum duration per user.",
        "`HAVING` filters the per-user groups after the maximum is computed.",
      ],
      referenceSolution: `WITH gapped AS (
  SELECT user_id,
         event_time_ms,
         LAG(event_time_ms) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS prev_time_ms
  FROM page_view_events
),
flagged AS (
  SELECT user_id,
         event_time_ms,
         CASE WHEN prev_time_ms IS NULL OR event_time_ms - prev_time_ms > 1800000
              THEN 1 ELSE 0 END AS new_session
  FROM gapped
),
sessioned AS (
  SELECT user_id,
         event_time_ms,
         SUM(new_session) OVER (PARTITION BY user_id ORDER BY event_time_ms) AS session_number
  FROM flagged
),
per_session AS (
  SELECT user_id,
         session_number,
         (MAX(event_time_ms) - MIN(event_time_ms)) / 60000 AS duration_minutes
  FROM sessioned
  GROUP BY user_id, session_number
)
SELECT user_id,
       MAX(duration_minutes) AS longest_session_minutes
FROM per_session
GROUP BY user_id
HAVING MAX(duration_minutes) > 45
ORDER BY longest_session_minutes DESC, user_id;`,
      singleFile: {
        seedSql: PAGE_VIEW_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["user_id", "longest_session_minutes"],
          rows: [
            [501, 60],
            [502, 47],
          ],
        },
      },
    },
  ],
}

export const level9Module3: SqlModule = {
  id: "de-l9-stream-processing-sql",
  title: "Module 9.3: Stream Processing in SQL",
  description:
    "The windowing half of streaming, written by hand so nothing stays hidden inside an operator: tumbling windows from integer division and hopping windows from a range join, then the split between event time and processing time with a watermark deciding what counts as late and what a straggler does to a window that already published a number, and finally the session-window drill at interview speed.",
  lessons: [tumblingHoppingWindows, watermarksAndLateEvents, sessionization],
}
