/**
 * Data Engineering Level 9, Module 9.2 — Change Data Capture.
 *
 * The platform's single debut of the Debezium envelope (RESEARCH.md §5.4). Three lessons take a
 * changelog from "what are these columns" to "apply it to a warehouse exactly once and know where
 * the dedup belongs": read the flattened envelope (op c/u/d, before/after images, lsn), apply an
 * lsn-ordered checkpoint-bounded upsert that survives shuffled arrival and a rerun, then choose
 * between absorbing redelivery at the write or at the read.
 *
 * The device is the same one the whole DE course uses: a simulated sink table named after the real
 * artifact. `cdc_events` is what a Debezium connector actually lands after the envelope is
 * flattened into columns, `apply_watermark` is the consumer checkpoint, and `raw_events` is the
 * at-least-once landing zone. Nothing here needs Kafka; everything here is the SQL a CDC consumer
 * runs.
 *
 * Runtime constraint (binding): grading runs on sql.js SQLite, which has no `MERGE` keyword. Merge
 * semantics are graded as `INSERT ... ON CONFLICT(key) DO UPDATE` plus a keyed `DELETE` for the
 * tombstone branch; real `MERGE INTO` appears in prose callouts only. Idempotency is graded
 * literally, by running the learner's script twice with `checkIdempotency` and `idempotencyTables`
 * naming exactly what must be byte-stable.
 *
 * Deliberately NOT a reteach, and the closest prior art is `sql-l5-cdc-changelog-apply`, not the L8
 * lessons: that lesson already graded the whole three-move apply (reduce to the latest version per
 * key, `ON CONFLICT` upsert, keyed tombstone delete, idempotent rerun) on a changelog ordered by a
 * plain version number. `de-l8-change-batch-merge` (the map calls it de-l8-upsert-merge-semantics;
 * the shipped id is the one used here) graded upsert mechanics on a plain redelivered batch, and
 * `de-l8-append-dedup-at-read` graded the materialize-and-rerun clean-table build. So the genuinely
 * new content in 9.2.2 is the log position as the order authority (a partition key you do not
 * control, LAG inversion detection) and the checkpoint that bounds the apply and resumes it, and
 * the teach says so to the learner rather than letting it read as a repeat. 9.2.3 grades the CHOICE
 * plus the poison-data audit rather than rebuilding an identical script.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the SAME
 * self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed, and every
 * workspace reference was executed against its own hidden assertions including the idempotency
 * double-run. Content rules: no em dashes in learner prose; every prompt leads with the deliverable.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"
import { scriptExercise } from "../script-exercise"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 9.2.1 seeds — a Debezium sink for a `customers` source table, flattened into columns that
// keep BOTH images. That two-image shape is a sink choice, not what the stock unwrap SMT
// (ExtractNewRecordState) produces; that transform keeps the after image plus metadata columns
// only, which is why the teach names it for what it actually does rather than for this table.
// 14 events over 6 customers: two deletes, and customer 101 living a full
// create -> update -> update -> delete life so one key alone tells the whole envelope story.
// ---------------------------------------------------------------------------

const CDC_CUSTOMERS_SEED = `CREATE TABLE cdc_events (
  lsn          INTEGER,  -- log sequence number: the source WAL position, the only true order
  ts_ms        INTEGER,  -- when the source COMMITTED the change, not when the sink saw it
  source_table TEXT,
  op           TEXT,     -- 'c' create, 'u' update, 'd' delete
  customer_id  INTEGER,
  before_email TEXT,     -- NULL on 'c': there was no prior row to photograph
  after_email  TEXT,     -- NULL on 'd': a delete event carries the before image only
  before_tier  TEXT,
  after_tier   TEXT
);
-- Note the two updates that move only the tier (lsn 4107 and 4112): a change event is emitted for
-- any column change, so "the row changed" and "the email changed" are different questions.
-- Customer 106's update (lsn 4114) carries an EARLIER ts_ms than its create (lsn 4111): the source
-- clock was corrected backwards between the two commits. It is deliberate. It makes a reduce
-- ordered by ts_ms return the wrong row for that key, which is the mistake the lesson names.
INSERT INTO cdc_events (lsn, ts_ms, source_table, op, customer_id, before_email, after_email, before_tier, after_tier) VALUES
  (4101, 1767225600000, 'customers', 'c', 101, NULL,                   'grace@northwind.io',   NULL,     'bronze'),
  (4102, 1767225780000, 'customers', 'c', 102, NULL,                   'ada@lovelace.dev',     NULL,     'silver'),
  (4103, 1767225960000, 'customers', 'c', 103, NULL,                   'katherine@nasa.gov',   NULL,     'bronze'),
  (4104, 1767226140000, 'customers', 'u', 101, 'grace@northwind.io',   'ghopper@northwind.io', 'bronze', 'bronze'),
  (4105, 1767226320000, 'customers', 'c', 104, NULL,                   'annie@easley.io',      NULL,     'bronze'),
  (4106, 1767226500000, 'customers', 'u', 103, 'katherine@nasa.gov',   'kjohnson@nasa.gov',    'bronze', 'silver'),
  (4107, 1767226680000, 'customers', 'u', 101, 'ghopper@northwind.io', 'ghopper@northwind.io', 'bronze', 'gold'),
  (4108, 1767226860000, 'customers', 'c', 105, NULL,                   'radia@perlman.net',    NULL,     'silver'),
  (4109, 1767227040000, 'customers', 'u', 102, 'ada@lovelace.dev',     'ada@analytical.dev',   'silver', 'gold'),
  (4110, 1767227220000, 'customers', 'd', 104, 'annie@easley.io',      NULL,                   'bronze', NULL),
  (4111, 1767227400000, 'customers', 'c', 106, NULL,                   'margaret@hamilton.io', NULL,     'bronze'),
  (4112, 1767227580000, 'customers', 'u', 105, 'radia@perlman.net',    'radia@perlman.net',    'silver', 'gold'),
  (4113, 1767227760000, 'customers', 'd', 101, 'ghopper@northwind.io', NULL,                   'gold',   NULL),
  (4114, 1767226000000, 'customers', 'u', 106, 'margaret@hamilton.io', 'mhamilton@nasa.gov',   'bronze', 'silver');`

// ---------------------------------------------------------------------------
// Lesson 9.2.2 seeds — an `orders` source captured into the SAME `cdc_events` sink shape, but keyed
// (wrongly) by warehouse_id upstream, so arrival order and log order disagree for three keys. The
// checkpoint slice is lsn <= 1210, which deliberately contains the delete (order 1041) and the
// brand-new order first seen mid-stream (order 1045), so the practice exercises both branches.
// ---------------------------------------------------------------------------

const CDC_ORDERS_SEED = `CREATE TABLE cdc_events (
  lsn          INTEGER,  -- source log position: the true order of the changes
  arrival_seq  INTEGER,  -- the order the SINK received them; an accident of partitioning
  ts_ms        INTEGER,
  op           TEXT,     -- 'c' create, 'u' update, 'd' delete
  order_id     INTEGER,
  after_status TEXT      -- NULL on 'd'
);
-- Order 1042's 'shipped' (lsn 1207) lands at arrival_seq 3, before its 'packed' (lsn 1201) at
-- arrival_seq 5. Orders 1044 and 1045 invert once each too. Every other key arrived in log order.
--
-- Two deliberate anti-coincidences, so the lesson's graded claim ("the bound is on the log
-- position, not on time and not on arrival order") is actually gradeable:
--   * lsn 1210 arrives at seq 12 and lsn 1215 at seq 10, so the checkpoint slice lsn <= 1210 is NOT
--     the same set as arrival_seq <= 10. Bounding on arrival leaves 1043 at 'packed' and applies
--     1045's 'picked' early, and the practice's assertions catch both.
--   * lsn 1214 shares a commit millisecond with lsn 1210, so no ts_ms bound can name the slice
--     either: an inclusive one drags 1214 in and an exclusive one drops 1210.
INSERT INTO cdc_events (lsn, arrival_seq, ts_ms, op, order_id, after_status) VALUES
  (1195,  1, 1767290000000, 'u', 1040, 'picked'),
  (1198,  2, 1767290090000, 'u', 1043, 'packed'),
  (1207,  3, 1767290360000, 'u', 1042, 'shipped'),
  (1202,  4, 1767290210000, 'u', 1044, 'picked'),
  (1201,  5, 1767290180000, 'u', 1042, 'packed'),
  (1203,  6, 1767290240000, 'u', 1041, 'packed'),
  (1206,  7, 1767290330000, 'd', 1041, NULL),
  (1208,  8, 1767290390000, 'u', 1040, 'shipped'),
  (1209,  9, 1767290420000, 'c', 1045, 'placed'),
  (1215, 10, 1767290600000, 'u', 1045, 'picked'),
  (1225, 11, 1767290900000, 'u', 1042, 'returned'),
  (1210, 12, 1767290450000, 'u', 1043, 'shipped'),
  (1221, 13, 1767290780000, 'u', 1044, 'shipped'),
  (1214, 14, 1767290450000, 'u', 1044, 'packed'),
  (1218, 15, 1767290690000, 'u', 1040, 'delivered'),
  (1220, 16, 1767290750000, 'u', 1043, 'delivered'),
  (1228, 17, 1767290990000, 'u', 1045, 'shipped'),
  (1226, 18, 1767290930000, 'u', 1044, 'delivered'),
  (1217, 19, 1767290660000, 'u', 1042, 'delivered'),
  (1223, 20, 1767290840000, 'u', 1045, 'packed');`

/** The warehouse target before any of the changelog has been applied. 1039 is not in the stream at
 *  all, so a correct apply has to leave it exactly where it is, and 1045 is absent because the
 *  order did not exist yet when this table was last loaded. */
const ORDERS_TARGET_SEED = `CREATE TABLE orders (
  order_id INTEGER PRIMARY KEY,
  status   TEXT
);
INSERT INTO orders (order_id, status) VALUES
  (1039, 'delivered'),
  (1040, 'placed'),
  (1041, 'placed'),
  (1042, 'placed'),
  (1043, 'placed'),
  (1044, 'placed');

CREATE TABLE apply_watermark (
  last_lsn INTEGER   -- the highest lsn this consumer has applied; empty before the first run
);`

/** The same warehouse AFTER the lsn <= 1210 checkpoint landed, with the watermark recorded. This is
 *  where the resume drill picks up: 1041 is gone, 1045 exists, and 1044 is still at 'picked'. */
const ORDERS_RESUMED_SEED = `CREATE TABLE orders (
  order_id INTEGER PRIMARY KEY,
  status   TEXT
);
INSERT INTO orders (order_id, status) VALUES
  (1039, 'delivered'),
  (1040, 'shipped'),
  (1042, 'shipped'),
  (1043, 'shipped'),
  (1044, 'picked'),
  (1045, 'placed');

CREATE TABLE apply_watermark (
  last_lsn INTEGER
);
INSERT INTO apply_watermark (last_lsn) VALUES (1210);`

// ---------------------------------------------------------------------------
// Lesson 9.2.3 seeds — the at-least-once landing zone. 32 rows over 25 distinct event_ids: four
// event_ids redelivered with byte-identical payloads (E-9007 three times, the rest twice), and two
// event_ids whose redeliveries DISAGREE on amount_cents. Those two are the poison rows the practice
// hunts, and they are the reason a silent rn = 1 is an audit failure rather than a cleanup.
//
// MAP DEVIATION: the map specifies 30 rows. E-9007 is delivered a third time so the "distinct
// duplicated event_ids" and "surplus rows" counts differ (6 vs 7). At 30 rows both numbers are 6
// and the easy drill would pass on a coin flip.
//
// User 505 exists for one reason: almost all of its revenue is one event that was redelivered, so
// its percentage inflation is the largest in the data while its absolute inflation stays small.
// Without it the biggest absolute inflation and the biggest percentage inflation land on the same
// user and drill 3 grades nothing. Its second, tiny, cleanly delivered event (E-9025) exists so
// that percentage is 94.29 rather than a round 100, which is what makes drill 3's "rounded to 2
// decimals" a graded requirement instead of a decoration. User 503 is the mirror control: every one
// of its events arrived exactly once.
// ---------------------------------------------------------------------------

const RAW_EVENTS_SEED = `CREATE TABLE raw_events (
  ingest_seq    INTEGER,  -- the order the sink landed the row; decides which copy is "first"
  event_id      TEXT,     -- the producer's idempotency key; a redelivery repeats it
  user_id       INTEGER,
  amount_cents  INTEGER,
  event_time_ms INTEGER   -- when it happened at the SOURCE; identical across redeliveries
);
-- ingest_seq 1..25 is the clean first pass. Everything from 26 on is a redelivery.
INSERT INTO raw_events (ingest_seq, event_id, user_id, amount_cents, event_time_ms) VALUES
  ( 1, 'E-9001', 501, 1200, 1767290000000),
  ( 2, 'E-9002', 502, 3450, 1767290045000),
  ( 3, 'E-9003', 501,  800, 1767290090000),
  ( 4, 'E-9004', 503, 2100, 1767290135000),
  ( 5, 'E-9005', 502, 1750, 1767290180000),
  ( 6, 'E-9006', 501,  990, 1767290225000),
  ( 7, 'E-9007', 504, 5600, 1767290270000),
  ( 8, 'E-9008', 503, 1300, 1767290315000),
  ( 9, 'E-9009', 502, 2400, 1767290360000),
  (10, 'E-9010', 501, 1500, 1767290405000),
  (11, 'E-9011', 504,  700, 1767290450000),
  (12, 'E-9012', 505, 3300, 1767290495000),
  (13, 'E-9013', 502, 1100, 1767290540000),
  (14, 'E-9014', 501, 2750, 1767290585000),
  (15, 'E-9015', 504, 1900, 1767290630000),
  (16, 'E-9016', 503,  850, 1767290675000),
  (17, 'E-9017', 502, 4200, 1767290720000),
  (18, 'E-9018', 501,  640, 1767290765000),
  (19, 'E-9019', 504, 2600, 1767290810000),
  (20, 'E-9020', 503, 1450, 1767290855000),
  (21, 'E-9021', 502,  980, 1767290900000),
  (22, 'E-9022', 501, 3100, 1767290945000),
  (23, 'E-9023', 504, 1250, 1767290990000),
  (24, 'E-9024', 503, 2050, 1767291035000),
  (25, 'E-9025', 505,  200, 1767291080000),
  (26, 'E-9002', 502, 3450, 1767290045000),
  (27, 'E-9005', 502, 1795, 1767290180000),
  (28, 'E-9007', 504, 5600, 1767290270000),
  (29, 'E-9012', 505, 3300, 1767290495000),
  (30, 'E-9014', 501, 2700, 1767290585000),
  (31, 'E-9018', 501,  640, 1767290765000),
  (32, 'E-9007', 504, 5600, 1767290270000);`

// ---------------------------------------------------------------------------
// Module 9.2 — Change Data Capture
// ---------------------------------------------------------------------------

const changelogAnatomy: SqlLesson = {
  id: "de-l9-changelog-anatomy",
  title: "Anatomy of a Change Event",
  summary:
    "Read a Debezium-shaped changelog, tell log-based capture from query-based polling, and rebuild current state from the events alone.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "change data capture",
    "Debezium envelope",
    "log-based vs query-based capture",
    "delete events and tombstones",
    "ROW_NUMBER",
    "NULL semantics",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## Two ways to notice that a row changed

A warehouse needs to know when the operational database changed. There are exactly two families of answer, and interviewers ask you to compare them by name.

**Query-based capture** polls the source: \`SELECT * FROM customers WHERE updated_at > :last_seen\`. It is simple, it needs no special permissions, and it works on any database with a decent timestamp column. It also has three problems that get worse as the table grows. It loads the source with a scan on every poll, it only sees the LATEST state of a row (two edits between polls collapse into one), and, the fatal one, **it misses deletes entirely**. A deleted row does not have an \`updated_at\` any more. It simply is not there, and a polling query cannot see an absence.

**Log-based capture** reads the database's own write-ahead log: the Postgres WAL, the MySQL binlog, the SQL Server transaction log. Every committed change is already in there in commit order, because that is how the database itself guarantees durability. A connector (Debezium is the standard one) tails that log and emits one event per change. Cost to the source is near zero, deletes are captured like anything else, and you get every intermediate state instead of a sampled one. The price is operational: you need replication privileges, a slot that will fill your disk if the consumer stalls, and a plan for schema changes.

## The envelope

Debezium emits a structured record per change, an envelope of \`{op, before, after, ts_ms, source}\`. Flattened into a sink table that keeps both images, which is the shape this module grades, it is this:

- \`op\` is the operation: \`'c'\` create, \`'u'\` update, \`'d'\` delete. (Snapshots also emit \`'r'\` for read, which you will meet the first time a connector backfills a table.)
- The **before image** holds the row as it was. It is NULL on a create, because there was no row.
- The **after image** holds the row as it now is. It is NULL on a delete, so the before image is the only address you have left for a row that is gone. Capturing a delete at all is the entire reason log-based capture beats polling.
- \`ts_ms\` is when the source committed the change.
- \`lsn\` is the log sequence number, the position in the write-ahead log. It is the only field that defines true order, and the next lesson is built on that fact.

**A delete event is not a tombstone, and a CDC round will check that you know it.** The delete event is the record above: \`op = 'd'\`, before image present, after image null. Debezium then emits a **tombstone** right after it, a separate record carrying the same key and a null VALUE, whose only job is to let Kafka log compaction drop that key from the topic entirely. It is controlled by \`tombstones.on.delete\`, which defaults to true. The warehouse-side \`DELETE\` that the next lesson writes is still worth calling the tombstone branch, and that shorthand is fine, as long as you can say what the tombstone record itself is.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["lsn", "op", "before_email", "after_email", "what the source did"],
  "rows": [
    [4101, "c", null, "grace@northwind.io", "INSERT: no before image exists"],
    [4104, "u", "grace@northwind.io", "ghopper@northwind.io", "UPDATE: both images present"],
    [4113, "d", "ghopper@northwind.io", null, "DELETE: after image is NULL"]
  ],
  "highlightCols": ["op", "before_email", "after_email"],
  "caption": "One row's whole life as change events. Which image is NULL tells you the operation even before you read op."
}
\`\`\`

## Rebuilding state from events

The changelog is the truth, but nobody queries a changelog to answer "what tier is customer 103 on right now". You reduce it: for each key, keep the event with the highest \`lsn\`, then read its after image. That is \`ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY lsn DESC)\` and keep \`rn = 1\`, and it is the first half of every changelog consumer ever written. If that winning event has \`op = 'd'\`, the key does not exist any more, and the second half of the consumer deletes it rather than writing a row full of NULLs.

**Common mistake:** ordering the reduce by \`ts_ms\` instead of \`lsn\`. Source timestamps have millisecond resolution and a busy table commits several changes inside one millisecond, so \`ts_ms\` ties and the tie is broken arbitrarily. Worse, a timestamp comes from a clock, and a clock can be stepped backwards by a correction, so \`ts_ms\` can disagree with commit order outright. Customer 106 in this changelog is that case: its update carries an earlier \`ts_ms\` than its create, so a reduce ordered by \`ts_ms\` hands you the email and tier the customer no longer has. The log position never ties and never goes backwards, because it is a position in a file that only ever grows.

**Interview nuance:** the question is usually phrased "CDC versus dual writes". Dual writes means the application writes to the database and then also publishes an event, and it is wrong for a reason worth being able to say out loud: those two writes are not one transaction, so a crash between them leaves the database and the stream permanently disagreeing. Log-based CDC has no such window, because the log IS the transaction. Follow that with "and the hardest part of a CDC pipeline is schema evolution", which appears close to verbatim in 2026 question banks, and you have covered both halves of the answer.

> **On a real platform this differs.** Here the envelope is nine plain columns in SQLite. Debezium emits it as Avro or JSON onto a Kafka topic with the before and after images as nested structs and a \`source\` block carrying the database, table, and log coordinates. The stock unwrap Single Message Transform, \`ExtractNewRecordState\`, flattens that envelope to the AFTER image plus optional metadata columns such as \`__op\` and \`__source_ts_ms\`, and under it a delete carries no before image at all. Keeping both images, as this sink table does, is a deliberate choice you make when the consumer needs the departed row. AWS DMS produces the same idea with its own column names, Microsoft Fabric mirroring hides it behind a managed replica, and Apache Hudi holds the streaming-CDC niche among the table formats. The reasoning is identical in all of them: op tells you the branch, the after image tells you the value, and the log position tells you the order.`,
    demoSeedSql: CDC_CUSTOMERS_SEED,
    demoCode: `-- Customer 101, birth to deletion. Read the NULLs: they are the operation, not missing data.
SELECT lsn, op, before_email, after_email, before_tier, after_tier
FROM cdc_events
WHERE customer_id = 101
ORDER BY lsn;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-changelog-anatomy-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every delete event in the changelog, as \`(lsn, customer_id, before_email)\`, oldest first, over \`cdc_events(lsn, ts_ms, source_table, op, customer_id, before_email, after_email, before_tier, after_tier)\`.

A delete carries \`op = 'd'\` and a NULL after image, so the only address you have for the departed customer is its before image. These are precisely the events a polling pipeline would never have seen.`,
    starterCode: `-- Every delete event in the changelog, oldest first.
SELECT lsn, customer_id, before_email
FROM cdc_events
;`,
    hints: [
      "Filter with `WHERE op = 'd'`.",
      "The email of a deleted customer lives in `before_email`; `after_email` is NULL by construction.",
      "Oldest first means `ORDER BY lsn`, because the log position is the order.",
    ],
    referenceSolution: `SELECT lsn, customer_id, before_email
FROM cdc_events
WHERE op = 'd'
ORDER BY lsn;`,
    singleFile: {
      seedSql: CDC_CUSTOMERS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["lsn", "customer_id", "before_email"],
        rows: [
          [4110, 104, "annie@easley.io"],
          [4113, 101, "ghopper@northwind.io"],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-changelog-anatomy-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns each customer's latest change event, as \`(customer_id, op, after_email, after_tier)\`, over the same \`cdc_events\` table.

Latest means highest \`lsn\`, not highest \`ts_ms\`. Return customers that still exist first, then the deleted ones, and inside each of those two blocks order by \`customer_id\` ascending. A deleted customer's row comes back with a NULL after image, which is the signal the next lesson turns into a \`DELETE\` statement.`,
    starterCode: `-- One row per customer: its newest change event, in log order.
SELECT customer_id, op, after_email, after_tier
FROM cdc_events
;`,
    hints: [
      "Number the events per key with `ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY lsn DESC)` inside a subquery or CTE, then keep the rows numbered 1.",
      "You cannot filter on a window function in the same `SELECT` that computes it, so the ranking needs its own subquery.",
      "\"Existing first, then deleted\" is a sort key: `ORDER BY CASE WHEN op = 'd' THEN 1 ELSE 0 END, customer_id`.",
    ],
    singleFile: {
      seedSql: CDC_CUSTOMERS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["customer_id", "op", "after_email", "after_tier"],
        rows: [
          [102, "u", "ada@analytical.dev", "gold"],
          [103, "u", "kjohnson@nasa.gov", "silver"],
          [105, "u", "radia@perlman.net", "gold"],
          [106, "u", "mhamilton@nasa.gov", "silver"],
          [101, "d", null, null],
          [104, "d", null, null],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-changelog-anatomy-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many events of each operation the changelog holds, as \`(op, event_count)\`, in alphabetical \`op\` order, over \`cdc_events\`.`,
      starterCode: `-- Event counts per operation, alphabetically by op.
SELECT op
FROM cdc_events
;`,
      hints: ["`GROUP BY op` and `COUNT(*) AS event_count`.", "`ORDER BY op` sorts c, d, u."],
      referenceSolution: `SELECT op, COUNT(*) AS event_count
FROM cdc_events
GROUP BY op
ORDER BY op;`,
      singleFile: {
        seedSql: CDC_CUSTOMERS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["op", "event_count"],
          rows: [
            ["c", 6],
            ["d", 2],
            ["u", 6],
          ],
        },
      },
    },
    {
      id: "de-l9-changelog-anatomy-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns every update event that actually changed the email address, as \`(lsn, customer_id, before_email, after_email)\`, oldest first, over \`cdc_events\`.

Two of the updates in this log move only the tier. A change event fires for any column change, so "the row changed" and "the email changed" are different questions.`,
      starterCode: `-- Updates where the before and after emails disagree.
SELECT lsn, customer_id, before_email, after_email
FROM cdc_events
;`,
      hints: [
        "Restrict to `op = 'u'` first: creates and deletes have a NULL on one side by construction.",
        "Compare the two images with `before_email <> after_email`.",
      ],
      referenceSolution: `SELECT lsn, customer_id, before_email, after_email
FROM cdc_events
WHERE op = 'u' AND before_email <> after_email
ORDER BY lsn;`,
      singleFile: {
        seedSql: CDC_CUSTOMERS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["lsn", "customer_id", "before_email", "after_email"],
          rows: [
            [4104, 101, "grace@northwind.io", "ghopper@northwind.io"],
            [4106, 103, "katherine@nasa.gov", "kjohnson@nasa.gov"],
            [4109, 102, "ada@lovelace.dev", "ada@analytical.dev"],
            [4114, 106, "margaret@hamilton.io", "mhamilton@nasa.gov"],
          ],
        },
      },
    },
    {
      id: "de-l9-changelog-anatomy-drill-3",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns the busiest customer in the changelog with the span of log positions it covers, as \`(customer_id, event_count, first_lsn, last_lsn)\`, over \`cdc_events\`.

Busiest means the most change events. Return one row.`,
      starterCode: `-- The customer with the most change events, plus its first and last log positions.
SELECT customer_id
FROM cdc_events
;`,
      hints: [
        "`GROUP BY customer_id` with `COUNT(*)`, `MIN(lsn)`, and `MAX(lsn)`.",
        "`ORDER BY event_count DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `SELECT customer_id,
       COUNT(*) AS event_count,
       MIN(lsn) AS first_lsn,
       MAX(lsn) AS last_lsn
FROM cdc_events
GROUP BY customer_id
ORDER BY event_count DESC, customer_id
LIMIT 1;`,
      singleFile: {
        seedSql: CDC_CUSTOMERS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["customer_id", "event_count", "first_lsn", "last_lsn"],
          rows: [[101, 4, 4101, 4113]],
        },
      },
    },
  ],
}

const orderingGuarantees: SqlLesson = {
  id: "de-l9-ordering-guarantees",
  title: "Ordering and Checkpoints: Out-of-Order Arrival and the Bounded Apply",
  summary:
    "State what Kafka does and does not promise about order, catch inverted arrivals with LAG, and write the lsn-ordered, checkpoint-bounded apply that survives shuffled input and a rerun.",
  estimatedMinutes: 32,
  difficulty: "hard",
  skills: [
    "per-partition ordering",
    "partition key choice",
    "out-of-order detection",
    "LAG",
    "log-position apply",
    "INSERT ... ON CONFLICT DO UPDATE",
    "tombstone delete",
    "apply watermark checkpoint",
  ],
  teach: {
    estimatedMinutes: 14,
    markdown: `## What the log actually promises

Kafka guarantees order **within a partition**. That is the whole promise. There is no global ordering across a topic, and there never will be, because partitions are the unit of parallelism and a total order across them would mean a single consumer.

So ordering is a consequence of the partition key you choose. Key the change events by the row's primary key and every change for that row hashes to the same partition and arrives in log order, forever. Key them by anything else, and the events for one row scatter across partitions whose consumers run at different speeds. Then a later change can be applied before an earlier one, and the row ends up holding a stale value with no error anywhere.

The changelog in this lesson came off a connector keyed by \`warehouse_id\`. Orders move between warehouses, so one order's events landed on different partitions, and three keys arrived inverted.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["arrival_seq", "order_id", "lsn", "after_status", "reading"],
  "rows": [
    [3, 1042, 1207, "shipped", "arrived first"],
    [5, 1042, 1201, "packed", "OUT OF ORDER: lower lsn arrived later"],
    [12, 1043, 1210, "shipped", "checkpoint line: apply stops here, and it arrived 12th"],
    [19, 1042, 1217, "delivered", "beyond the checkpoint, next run's work"]
  ],
  "highlightCols": ["lsn", "reading"],
  "caption": "Arrival order is an accident of partitioning. The lsn column is the truth, and the checkpoint is a line drawn on it, not on arrival_seq."
}
\`\`\`

## Detecting it before it bites

Walk each key in arrival order and compare each event's \`lsn\` to the previous one's. \`LAG(lsn) OVER (PARTITION BY order_id ORDER BY arrival_seq)\` gives you that previous value; wherever the current \`lsn\` is SMALLER, the stream handed you the past after it handed you the future. That query is worth keeping as a monitor, because it is the only cheap way to notice a bad partition key before someone notices a wrong dashboard.

The fix at the sink is never "hope". Sort by \`lsn\` at apply time. Arrival order is an accident; the log position is a fact.

## The apply, in three moves

You have built these three before, in \`sql-l5-cdc-changelog-apply\`, on a changelog ordered by a plain version number. They are recalled here as a component, not retaught: what is new in this lesson is that the order comes from a log position you do not control, and that the apply is bounded by a checkpoint it has to record and resume from.

1. **Reduce.** Keep one event per key, the one with the highest \`lsn\`. Same \`ROW_NUMBER\` reduce as the previous lesson.
2. **Delete.** Keys whose winning event is \`op = 'd'\` are gone. Remove them from the target.
3. **Upsert.** Every other key writes its after image, inserting when the key is new and updating when it already exists.

Interviewers call this whole thing a MERGE, and on Snowflake, BigQuery, and Athena-on-Iceberg you would literally write \`MERGE INTO target USING source ON ... WHEN MATCHED THEN UPDATE ... WHEN NOT MATCHED THEN INSERT ...\`. SQLite has no \`MERGE\` keyword, so you write the same semantics as \`INSERT ... ON CONFLICT(order_id) DO UPDATE SET status = excluded.status\` plus a keyed \`DELETE\` for the tombstone branch. That is not a workaround to apologize for in an interview. **A merge is an upsert plus a delete branch**, and being able to say that sentence is the understanding the question is testing. You have already graded the upsert mechanics in \`de-l8-change-batch-merge\`; here they are a component, not the lesson.

One parser detail that costs people ten minutes: when the rows you insert come from a \`SELECT\` rather than a \`VALUES\` list, SQLite cannot tell the \`ON\` of \`ON CONFLICT\` from the \`ON\` of a join, and it reports \`near "DO": syntax error\`. The fix is in SQLite's own documentation: give the \`SELECT\` a \`WHERE\` clause, even a trivial \`WHERE true\`, so the parser has something between the source and the conflict clause. A reduce that already filters \`WHERE rn = 1\` satisfies this without you noticing.

## The checkpoint

A consumer that runs forever does not exist. Yours will be restarted, redeployed, and rerun, so it needs to remember how far it got. That memory is a **watermark**: after applying every event with \`lsn <= C\`, record \`C\` in a small control table, and next run start from there.

Two properties matter and both are graded here.

- The bound is on the log position, not on time and not on arrival order. \`lsn <= 1210\` describes a slice that means the same thing on every rerun, on every replay, and on any consumer. The other two bounds cannot even name this slice: \`lsn 1210\` is the twelfth arrival, not the tenth, and it shares a commit millisecond with \`lsn 1214\`, so a timestamp bound either drags 1214 in or drops 1210.
- The apply must be **idempotent**, because at-least-once delivery guarantees you will be handed the same slice twice. Running the script a second time has to leave \`orders\` and \`apply_watermark\` exactly as the first run left them. The grader checks this literally, by running your script twice.

That second property is why the watermark is never written with a bare insert: a bare insert stacks a second row on the rerun and the checkpoint stops being a single number. Which write is right depends on whether the row exists yet. An \`UPDATE\` is the natural rerun-safe write, but it only rewrites a row that is already there, so it does nothing at all on a control table that starts empty, and the practice's \`apply_watermark\` starts empty. A \`DELETE\` followed by an \`INSERT\` is the shape that is correct on the first run and on every run after it.

**Common mistake:** applying in arrival order because the events "usually" arrive in order. They usually do. The one time they do not, order 1042 ends at \`packed\` when the source says \`shipped\`, nothing errors, and the discrepancy is found weeks later by a human who noticed a stuck order.

**Interview nuance:** "How do you guarantee ordering in Kafka" has a two-word core answer, **partition key**, and the correct qualifier that order holds within a partition only. The follow-up is always "and what if it is already shuffled by the time you get it", and the answer is that you order on the log position at the sink, because the sink is the last place that can still be made correct.

> **On a real platform this differs.** Here the watermark is a one-row SQLite table you write yourself. A real consumer commits Kafka offsets back to the broker, a Flink job checkpoints its state to durable storage, and a warehouse-side merge job keeps its high-water mark in a control table that looks very much like this one. Delta Lake, Iceberg, and Hudi all give you an atomic \`MERGE\` so the delete branch and the upsert branch commit together; in SQLite they are two statements you would wrap in a transaction. The reduce-by-log-position step is identical everywhere, including in Flink, where it is the job's keyed state rather than a SQL window.`,
    demoSeedSql: CDC_ORDERS_SEED,
    demoCode: `-- Walk two keys in ARRIVAL order and compare each lsn to the previous one for that key.
SELECT arrival_seq,
       order_id,
       lsn,
       LAG(lsn) OVER (PARTITION BY order_id ORDER BY arrival_seq) AS prev_lsn_for_key,
       CASE
         WHEN lsn < LAG(lsn) OVER (PARTITION BY order_id ORDER BY arrival_seq)
         THEN 'out of order'
         ELSE ''
       END AS flag
FROM cdc_events
WHERE order_id IN (1042, 1045)
ORDER BY arrival_seq;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-ordering-guarantees-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns every event that arrived out of log order for its key, as \`(order_id, lsn, arrival_seq)\`, in arrival order, over \`cdc_events(lsn, arrival_seq, ts_ms, op, order_id, after_status)\`.

An event arrived out of order when the previous event the sink received **for that same order** carried a HIGHER \`lsn\`. The first arrival for a key can never be out of order, because there is nothing before it to compare against.`,
    starterCode: `-- Events whose lsn is lower than the previous arrival for the same order.
SELECT order_id, lsn, arrival_seq
FROM cdc_events
;`,
    hints: [
      "`LAG(lsn) OVER (PARTITION BY order_id ORDER BY arrival_seq)` is the lsn of the previous arrival for that key.",
      "Compute it in a subquery, then filter the outer query where the current `lsn` is less than that value.",
      "The first arrival for a key has a NULL previous lsn, and `NULL` comparisons are never true, so it drops out on its own.",
    ],
    referenceSolution: `SELECT order_id, lsn, arrival_seq
FROM (
  SELECT order_id,
         lsn,
         arrival_seq,
         LAG(lsn) OVER (PARTITION BY order_id ORDER BY arrival_seq) AS prev_lsn
  FROM cdc_events
)
WHERE lsn < prev_lsn
ORDER BY arrival_seq;`,
    singleFile: {
      seedSql: CDC_ORDERS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["order_id", "lsn", "arrival_seq"],
        rows: [
          [1042, 1201, 5],
          [1044, 1214, 14],
          [1042, 1217, 19],
          [1045, 1223, 20],
        ],
      },
    },
  },
  practice: scriptExercise({
    id: "de-l9-ordering-guarantees-practice",
    prompt: `Write a script that applies the changelog up to the checkpoint \`lsn <= 1210\` to \`orders\`, then records the checkpoint in \`apply_watermark\`, over \`cdc_events(lsn, arrival_seq, ts_ms, op, order_id, after_status)\`, \`orders(order_id PRIMARY KEY, status)\`, and the empty \`apply_watermark(last_lsn)\`.

Within that slice, the newest event per order in **log order** wins. If that winning event is \`op = 'd'\` the order is removed from \`orders\`; otherwise its \`after_status\` is written, inserting the order when it is new and updating it when it already exists. Leave \`apply_watermark\` holding exactly one row: the highest \`lsn\` you applied.

Nothing outside the slice may be touched, and nothing that the changelog never mentions may be touched. Your script will be run twice against the same seed, and the second run must leave \`orders\` and \`apply_watermark\` exactly as the first run left them.`,
    starterCode: `-- Apply cdc_events with lsn <= 1210 to orders, then record the checkpoint in apply_watermark.
`,
    hints: [],
    seedSql: CDC_ORDERS_SEED + "\n\n" + ORDERS_TARGET_SEED,
    assertions: [
      {
        suite: "apply",
        name: "orders_match_the_checkpointed_state",
        sql: `WITH expected(order_id, status) AS (VALUES
  (1039, 'delivered'),
  (1040, 'shipped'),
  (1042, 'shipped'),
  (1043, 'shipped'),
  (1044, 'picked'),
  (1045, 'placed')),
actual AS (SELECT order_id, status FROM orders)
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT * FROM actual)`,
      },
      {
        suite: "apply",
        name: "tombstoned_order_is_gone",
        sql: `SELECT order_id FROM orders WHERE order_id = 1041`,
      },
      {
        suite: "apply",
        name: "one_row_per_order",
        sql: `SELECT order_id FROM orders GROUP BY order_id HAVING COUNT(*) > 1`,
      },
      {
        suite: "checkpoint",
        name: "watermark_holds_exactly_one_row_at_1210",
        sql: `SELECT row_count, high_lsn FROM (
  SELECT COUNT(*) AS row_count, MAX(last_lsn) AS high_lsn FROM apply_watermark
) WHERE row_count <> 1 OR high_lsn <> 1210`,
      },
    ],
    checkIdempotency: true,
    // Neither table grows by design, but naming the graded tables keeps a learner's scratch or
    // staging table from perturbing the double-run comparison.
    idempotencyTables: ["orders", "apply_watermark"],
  }),
  extraPractice: [
    // MAP DEVIATION: the map specifies a drill, and every other drill in L7 to L9 is single-file.
    // This one is a workspace script because the task IS multi-statement (delete branch, upsert
    // branch, watermark write) and carries its own idempotency contract, which a single SELECT
    // cannot express. Both gates already cover the shape: extra-practice.test.ts has a workspace
    // branch that runs a drill's referenceSolution against its assertions, and
    // SqlLessonPlayer.renderExercise dispatches drills on executionMode, so the player renders it.
    scriptExercise({
      id: "de-l9-ordering-guarantees-drill-1",
      prompt: `**Hard.** Write a script that resumes the apply from the recorded watermark and finishes the changelog, over \`cdc_events\`, \`orders\`, and \`apply_watermark(last_lsn)\`, which already holds the checkpoint the previous run recorded.

Read the resume point out of \`apply_watermark\`, apply every event with a HIGHER \`lsn\` by the same rules as before (newest per order in log order wins, \`op = 'd'\` deletes, everything else upserts), and leave \`apply_watermark\` holding the highest \`lsn\` in the changelog. The finished state must equal what a single apply of the whole changelog would have produced, and rerunning your script must change nothing.`,
      starterCode: `-- Resume from apply_watermark.last_lsn and apply the rest of the changelog.
`,
      hints: [
        "`(SELECT last_lsn FROM apply_watermark)` is a scalar subquery you can drop straight into the `WHERE lsn > ...` filter of both statements.",
        "Update the watermark LAST. The delete and the upsert both read it, so moving it first empties the slice they were supposed to process.",
        "`UPDATE apply_watermark SET last_lsn = (SELECT MAX(lsn) FROM cdc_events)` keeps the table at one row, which a second `INSERT` would not.",
      ],
      referenceSolution: `DELETE FROM orders
WHERE order_id IN (
  SELECT order_id FROM (
    SELECT order_id,
           op,
           ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY lsn DESC) AS rn
    FROM cdc_events
    WHERE lsn > (SELECT last_lsn FROM apply_watermark)
  )
  WHERE rn = 1 AND op = 'd'
);

INSERT INTO orders (order_id, status)
SELECT order_id, after_status
FROM (
  SELECT order_id,
         op,
         after_status,
         ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY lsn DESC) AS rn
  FROM cdc_events
  WHERE lsn > (SELECT last_lsn FROM apply_watermark)
)
WHERE rn = 1 AND op <> 'd'
ON CONFLICT(order_id) DO UPDATE SET status = excluded.status;

UPDATE apply_watermark SET last_lsn = (SELECT MAX(lsn) FROM cdc_events);`,
      seedSql: CDC_ORDERS_SEED + "\n\n" + ORDERS_RESUMED_SEED,
      assertions: [
        {
          suite: "resume",
          name: "final_state_equals_a_single_full_apply",
          sql: `WITH expected(order_id, status) AS (VALUES
  (1039, 'delivered'),
  (1040, 'delivered'),
  (1042, 'returned'),
  (1043, 'delivered'),
  (1044, 'delivered'),
  (1045, 'shipped')),
actual AS (SELECT order_id, status FROM orders)
SELECT * FROM (SELECT * FROM actual EXCEPT SELECT * FROM expected)
UNION ALL
SELECT * FROM (SELECT * FROM expected EXCEPT SELECT * FROM actual)`,
        },
        {
          suite: "resume",
          name: "cancelled_order_stays_deleted",
          sql: `SELECT order_id FROM orders WHERE order_id = 1041`,
        },
        {
          suite: "checkpoint",
          name: "watermark_advanced_to_the_end_of_the_log",
          sql: `SELECT row_count, high_lsn FROM (
  SELECT COUNT(*) AS row_count, MAX(last_lsn) AS high_lsn FROM apply_watermark
) WHERE row_count <> 1 OR high_lsn <> 1228`,
        },
      ],
      checkIdempotency: true,
      idempotencyTables: ["orders", "apply_watermark"],
    }),
    {
      id: "de-l9-ordering-guarantees-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the orders whose final status would be wrong if the whole changelog were applied in arrival order, as \`(order_id, wrong_status, right_status)\`, ascending by \`order_id\`, over \`cdc_events\`.

\`wrong_status\` is the after image of the LAST event to arrive for that order; \`right_status\` is the after image of its HIGHEST \`lsn\`. Return only the orders where those two disagree. The cancelled order ends at NULL under both rules, so it is not a disagreement.`,
      starterCode: `-- Orders where last-by-arrival and last-by-lsn pick different final statuses.
SELECT order_id
FROM cdc_events
;`,
      hints: [
        "Rank the events twice in two CTEs: once with `ORDER BY arrival_seq DESC`, once with `ORDER BY lsn DESC`, keeping `rn = 1` from each.",
        "Join the two winners on `order_id`.",
        "`a.after_status IS NOT l.after_status` is the NULL-safe inequality; a plain `<>` silently drops the pair where both sides are NULL and would also drop a real NULL-versus-value disagreement.",
      ],
      referenceSolution: `WITH by_arrival AS (
  SELECT order_id,
         after_status,
         ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY arrival_seq DESC) AS rn
  FROM cdc_events
),
by_lsn AS (
  SELECT order_id,
         after_status,
         ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY lsn DESC) AS rn
  FROM cdc_events
)
SELECT a.order_id,
       a.after_status AS wrong_status,
       l.after_status AS right_status
FROM by_arrival a
JOIN by_lsn l ON l.order_id = a.order_id AND l.rn = 1
WHERE a.rn = 1 AND a.after_status IS NOT l.after_status
ORDER BY a.order_id;`,
      singleFile: {
        seedSql: CDC_ORDERS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["order_id", "wrong_status", "right_status"],
          rows: [
            [1042, "delivered", "returned"],
            [1045, "packed", "shipped"],
          ],
        },
      },
    },
  ],
}

const dedupAtRead: SqlLesson = {
  id: "de-l9-dedup-at-read",
  title: "Where Dedup Lives: Write-Side versus Read-Side",
  summary:
    "Pick between absorbing redelivery at the write and absorbing it at the read, price what absorbing it nowhere costs, and probe for redeliveries that disagree.",
  estimatedMinutes: 24,
  difficulty: "medium",
  skills: [
    "at-least-once duplicates",
    "write-side vs read-side dedup",
    "ROW_NUMBER keep-one-per-key",
    "duplicate cost auditing",
    "poison-data detection",
  ],
  teach: {
    estimatedMinutes: 11,
    markdown: `## Two places to absorb a duplicate

Module 9.1 established that at-least-once delivery manufactures duplicates and that nothing you configure removes them. You have now graded both ways of absorbing them.

**Dedup at write.** The previous lesson's apply reduced the changelog to one event per key and upserted it. The target holds one row per key at all times, any consumer can query it directly, and a redelivery just rewrites the same value. What you give up is history: after the upsert lands, the intermediate states are gone, and if the logic that produced them was wrong you cannot recompute, because the input is not there any more.

**Dedup at read.** \`de-l8-append-dedup-at-read\` appended every delivery to a raw table exactly as it arrived and pushed the correctness into a view: \`ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq)\` and keep \`rn = 1\`. Raw stays immutable and auditable, you can replay it after a bug fix, and you can prove what you received. What you give up is convenience: every consumer must remember to dedup, and the one that forgets reports inflated numbers with a straight face.

\`\`\`csdiagram
{
  "type": "topology",
  "layout": "lr",
  "nodes": [
    { "id": "stream", "label": "at-least-once stream", "kind": "queue" },
    { "id": "upsert", "label": "upsert by key", "kind": "service" },
    { "id": "serving", "label": "serving table (state only)", "kind": "db" },
    { "id": "raw", "label": "raw landing (append-only)", "kind": "db" },
    { "id": "dedupread", "label": "rn = 1 in the read", "kind": "service" },
    { "id": "report", "label": "the number that must be right", "kind": "external" }
  ],
  "edges": [
    { "from": "stream", "to": "upsert", "kind": "async" },
    { "from": "upsert", "to": "serving", "kind": "sync" },
    { "from": "stream", "to": "raw", "kind": "async" },
    { "from": "raw", "to": "dedupread", "kind": "sync" },
    { "from": "serving", "to": "report", "kind": "sync" },
    { "from": "dedupread", "to": "report", "kind": "sync" }
  ],
  "stages": [
    { "adds": ["stream"], "note": "One stream, redelivering. Neither branch can prevent that." },
    { "adds": ["upsert", "serving"], "note": "Dedup at write: state converges immediately, history is discarded." },
    { "adds": ["raw", "dedupread"], "note": "Dedup at read: raw is immutable and replayable, every reader owes a rn = 1." },
    { "adds": ["report"], "note": "Both branches can produce the right number. They fail differently." }
  ],
  "caption": "The same duplicated stream into both absorbers. The choice is about what you need to keep, not about which query is cleverer."
}
\`\`\`

## Choosing, out loud

- Need replay, audit, or the ability to recompute after a logic bug? **Dedup at read.** Regulated finance and anything with a "prove what you received" requirement lands here by default.
- Need a table other tools hit directly, with no shared view discipline to enforce? **Dedup at write.** A dimension a BI tool joins to is the archetype.
- The common production answer is **both**: append raw for the audit trail, and curate a served table from it with an upsert. That costs one more table and buys both properties, which is why so many platforms end up with a bronze and a silver layer.

What is never an option is neither. Absorbing duplicates nowhere does not fail loudly; it inflates every additive measure you have, silently, in proportion to how often the producer retried.

## The trap: duplicates that disagree

Here is the part that separates people who have cleaned a real stream from people who memorized \`ROW_NUMBER\`.

A redelivery of the same \`event_id\` with a **byte-identical payload** is a duplicate. Collapsing it loses nothing, and \`rn = 1\` is exactly right.

A redelivery of the same \`event_id\` with a **different payload** is not a duplicate. It is two different claims wearing one identity, which means either the producer has a bug, a key collided, or something upstream mutated a record it had already published. A silent \`rn = 1\` picks one of the two claims by sort order and throws the other away, and you never learn that a decision was made at all.

So the order of operations is: **audit for disagreement first, collapse second.** The probe is small. Group by the key, and flag any key whose payload values are not all equal. In this lesson two of the twenty five events are corrupted that way, and the practice is to find them before anything collapses them.

**Common mistake:** treating "duplicate rate" as a data-quality metric on its own. A 20% duplicate rate with byte-identical payloads is a producer that retries, which is normal and healthy. A 0.1% duplicate rate where the payloads disagree is a correctness incident. The rate does not tell you which one you have; the payload comparison does.

**Interview nuance:** "How do you handle duplicate events" is answered in three beats. Name both absorbers, pick one with a reason tied to the requirement, then raise the disagreeing-duplicate case before you are asked. That last beat is the unprompted failure mode that reads as production experience.

> **On a real platform this differs.** Here the audit is one \`GROUP BY\` over 32 rows in SQLite. On a real platform the raw table is an Iceberg or Delta table holding billions of rows, the deduped read is a materialized view or a dbt model with a \`unique\` test on the key, and the disagreement probe runs as a scheduled data test that pages someone. The disagreeing rows themselves usually go to a dead letter queue with the record, the error, and a timestamp, alerting past roughly a five percent rate, rather than halting the pipeline. The SQL shape is the one you just wrote.`,
    demoSeedSql: RAW_EVENTS_SEED,
    demoCode: `-- The same landing table read two ways. One of these numbers is a lie.
SELECT 'naive SUM over raw' AS reading,
       ROUND(SUM(amount_cents) / 100.0, 2) AS revenue_usd
FROM raw_events
UNION ALL
SELECT 'first delivery per event_id',
       ROUND(SUM(amount_cents) / 100.0, 2)
FROM (
  SELECT amount_cents,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq) AS rn
  FROM raw_events
)
WHERE rn = 1;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-dedup-at-read-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns, per user, what a naive sum reports next to the true revenue and the gap between them, as \`(user_id, naive_cents, true_cents, inflation_cents)\`, biggest inflation first, over \`raw_events(ingest_seq, event_id, user_id, amount_cents, event_time_ms)\`.

\`naive_cents\` sums every landed row. \`true_cents\` keeps only the FIRST delivery of each \`event_id\`, where first means the lowest \`ingest_seq\`. \`inflation_cents\` is the difference. This is the cost of absorbing duplicates nowhere, priced per user.`,
    starterCode: `-- Naive revenue, deduped revenue, and the gap, per user.
SELECT user_id
FROM raw_events
;`,
    hints: [
      "Number the deliveries of each event first: `ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq) AS rn` inside a CTE.",
      "Both totals come out of one `GROUP BY user_id` over that CTE: `SUM(amount_cents)` for naive, and `SUM(CASE WHEN rn = 1 THEN amount_cents ELSE 0 END)` for true.",
      "Alias the columns exactly `naive_cents`, `true_cents`, and `inflation_cents`, then `ORDER BY inflation_cents DESC`.",
    ],
    referenceSolution: `WITH ranked AS (
  SELECT user_id,
         amount_cents,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq) AS rn
  FROM raw_events
)
SELECT user_id,
       SUM(amount_cents) AS naive_cents,
       SUM(CASE WHEN rn = 1 THEN amount_cents ELSE 0 END) AS true_cents,
       SUM(amount_cents) - SUM(CASE WHEN rn = 1 THEN amount_cents ELSE 0 END) AS inflation_cents
FROM ranked
GROUP BY user_id
ORDER BY inflation_cents DESC;`,
    singleFile: {
      seedSql: RAW_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["user_id", "naive_cents", "true_cents", "inflation_cents"],
        rows: [
          [504, 23250, 12050, 11200],
          [502, 19125, 13880, 5245],
          [501, 14320, 10980, 3340],
          [505, 6800, 3500, 3300],
          [503, 7750, 7750, 0],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-dedup-at-read-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the events whose deliveries disagree on \`amount_cents\`, as \`(event_id, delivery_count, min_cents, max_cents)\`, ascending by \`event_id\`, over the same \`raw_events\` table.

Most of the redeliveries in this landing zone carry byte-identical payloads and are safe to collapse. A handful do not. Those are the ones to surface before anything runs \`rn = 1\` over them.`,
    starterCode: `-- Events whose deliveries do not agree on the amount.
SELECT event_id
FROM raw_events
;`,
    hints: [],
    singleFile: {
      seedSql: RAW_EVENTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["event_id", "delivery_count", "min_cents", "max_cents"],
        rows: [
          ["E-9005", 2, 1750, 1795],
          ["E-9014", 2, 2700, 2750],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-dedup-at-read-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns how many events were delivered more than once and how many surplus rows they added, as \`(duplicated_events, surplus_rows)\`, over \`raw_events\`.

A surplus row is any delivery of an event beyond its first, so an event delivered three times contributes two.`,
      starterCode: `-- Count the redelivered events and the extra rows they cost.
SELECT
FROM raw_events;`,
      hints: [
        "Start with a subquery: `SELECT event_id, COUNT(*) AS delivery_count FROM raw_events GROUP BY event_id HAVING COUNT(*) > 1`.",
        "Then `COUNT(*)` those groups for `duplicated_events` and `SUM(delivery_count - 1)` for `surplus_rows`.",
      ],
      referenceSolution: `SELECT COUNT(*) AS duplicated_events,
       SUM(delivery_count - 1) AS surplus_rows
FROM (
  SELECT event_id, COUNT(*) AS delivery_count
  FROM raw_events
  GROUP BY event_id
  HAVING COUNT(*) > 1
);`,
      singleFile: {
        seedSql: RAW_EVENTS_SEED,
        assertColumnNames: true,
        expected: { columns: ["duplicated_events", "surplus_rows"], rows: [[6, 7]] },
      },
    },
    {
      id: "de-l9-dedup-at-read-drill-2",
      executionMode: "single-file",
      prompt: `**Medium.** Write a query that returns, for every event whose deliveries disagree, the amount a first-delivery-wins rule would have kept and the amount it would have discarded, as \`(event_id, kept_cents, discarded_cents)\`, ascending by \`event_id\`, over \`raw_events\`.

This is the number nobody sees when \`rn = 1\` runs without an audit in front of it.`,
      starterCode: `-- What first-delivery-wins keeps, and what it silently throws away.
SELECT event_id
FROM raw_events
;`,
      hints: [
        "Rank the deliveries per event with `ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq)`.",
        "A disagreeing event is one where `MIN(amount_cents) <> MAX(amount_cents)` across its deliveries.",
        "Pivot the ranked rows with `MAX(CASE WHEN rn = 1 THEN amount_cents END)` and `MAX(CASE WHEN rn > 1 THEN amount_cents END)`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT event_id,
         amount_cents,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq) AS rn
  FROM raw_events
),
disagreeing AS (
  SELECT event_id
  FROM raw_events
  GROUP BY event_id
  HAVING MIN(amount_cents) <> MAX(amount_cents)
)
SELECT r.event_id,
       MAX(CASE WHEN r.rn = 1 THEN r.amount_cents END) AS kept_cents,
       MAX(CASE WHEN r.rn > 1 THEN r.amount_cents END) AS discarded_cents
FROM ranked r
JOIN disagreeing d ON d.event_id = r.event_id
GROUP BY r.event_id
ORDER BY r.event_id;`,
      singleFile: {
        seedSql: RAW_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["event_id", "kept_cents", "discarded_cents"],
          rows: [
            ["E-9005", 1750, 1795],
            ["E-9014", 2750, 2700],
          ],
        },
      },
    },
    {
      id: "de-l9-dedup-at-read-drill-3",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the single user whose naive revenue is inflated by the largest percentage, as \`(user_id, naive_cents, true_cents, inflation_pct)\`, over \`raw_events\`.

\`inflation_pct\` is the inflation as a percentage of the true revenue, rounded to 2 decimals. Return one row. The user with the biggest absolute inflation and the user with the biggest percentage inflation are different people in this data, which is exactly why a duplicate audit reports both numbers.`,
      starterCode: `-- The user whose revenue is inflated by the largest percentage.
SELECT user_id
FROM raw_events
;`,
      hints: [
        "Reuse the apply's two totals per user, then divide.",
        "Force real division somewhere in the expression: `100.0 * (naive_cents - true_cents) / true_cents`. All-integer arithmetic loses the decimals the prompt asks for, and if the multiply by 100 lands after the divide instead of before it, the ratio floors to 0 first and every user reports 0.",
        "`ORDER BY inflation_pct DESC` then `LIMIT 1`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT user_id,
         amount_cents,
         ROW_NUMBER() OVER (PARTITION BY event_id ORDER BY ingest_seq) AS rn
  FROM raw_events
),
totals AS (
  SELECT user_id,
         SUM(amount_cents) AS naive_cents,
         SUM(CASE WHEN rn = 1 THEN amount_cents ELSE 0 END) AS true_cents
  FROM ranked
  GROUP BY user_id
)
SELECT user_id,
       naive_cents,
       true_cents,
       ROUND(100.0 * (naive_cents - true_cents) / true_cents, 2) AS inflation_pct
FROM totals
ORDER BY inflation_pct DESC, user_id
LIMIT 1;`,
      singleFile: {
        seedSql: RAW_EVENTS_SEED,
        orderMatters: true,
        assertColumnNames: true,
        expected: {
          columns: ["user_id", "naive_cents", "true_cents", "inflation_pct"],
          rows: [[505, 6800, 3500, 94.29]],
        },
      },
    },
  ],
}

export const level9Module2: SqlModule = {
  id: "de-l9-change-data-capture",
  title: "Change Data Capture",
  description:
    "Debezium-shaped change events as a changelog table, and the discipline of applying one to a warehouse: log-order apply with upserts and tombstones, lsn-bounded checkpoints, and choosing where dedup lives, graded by running the script twice.",
  lessons: [changelogAnatomy, orderingGuarantees, dedupAtRead],
}
