/**
 * Data Engineering Level 9, Module 9.4 — Choosing Batch vs Streaming.
 *
 * The level closes on the decision, not the technology. RESEARCH.md §5.5 is blunt about it:
 * batch vs streaming is a decision framework, not a survey, and the framework is one
 * question, "what decision consumes this data and what latency does that decision
 * require?". Micro-batch is the entry juniors skip and the one that covers most of what
 * gets called real-time; "defaulting to streaming because it sounds impressive" is a named
 * junior mistake and this module grades the cost of making it. The second lesson then
 * enforces the decision: a freshness SLA is a contract on the age of the DATA, measured
 * from run metadata, and §5.7's most-missed production failure (silent success, pipeline
 * green but zero rows written) is exactly what that measurement catches.
 *
 * Device: the same simulated-metadata seeds Level 6 proved. `data_products` is the
 * architecture-review spreadsheet every platform team keeps, made queryable, and
 * `stream_pipeline_runs` / `freshness_slas` are the run log and the SLA table an
 * observability tool reads. Both lessons are single-file: the deliverables are reports,
 * not scripts, so there is nothing for the workspace runner to make idempotent.
 *
 * Deepens, not repeats. Level 6's pipeline-run lesson asked "did the job run"; this module
 * asks "how old is the data the job landed, and who promised what". The trap that separates
 * them is baked into the seed: two pipelines whose newest run FAILED while still recording
 * the watermark it was attempting, so MAX(max_event_time_ms) across all runs reports data
 * that was never committed and a latest-successful-run pick (ROW_NUMBER) is required. MAX
 * over the SUCCESSFUL runs happens to agree on this seed because every pipeline's successful
 * watermarks are monotonic; the teach says that out loud and explains what separates the two
 * (a reprocess landing an older window), rather than claiming a uniqueness the seed does not
 * enforce. L6 and L8 both graded a freshness/task SLA using run DURATION as an admitted
 * proxy, so 9.4.2's teach names both and retires the proxy in its opening paragraphs.
 *
 * Deliberate map deviation, 9.4.1's live demo. The map specifies a demo CASE that classifies
 * each product's recommended pipeline type; written that way the demo IS the graded Apply
 * answer. The demo here keeps the CASE but classifies urgency in human words over different
 * boundaries, so the technique is shown and the 5/60-minute ladder is still the learner's to
 * apply.
 *
 * Deliberate map deviation, both diagrams. The map asks for a decision tree in 9.4.1 and a
 * run timeline in 9.4.2, and lib/tutorials/diagrams/schema.ts has neither primitive. The
 * freshness decision renders as `ladder` (log scale, the boundaries as bands, cost and
 * complexity in each band's note) and ml_features' run history as a highlighted `table`.
 * Both types are precedented in this course (level7/module4 uses ladder; table runs across
 * L7-L9) and both carry the information the map asked those diagrams to carry.
 *
 * Every single-file `expected` set is generated by running the reference SELECT through the
 * SAME self-hosted sql.js WASM the app ships (scratchpad sqlgen/gen.mjs), never hand-typed.
 * Content rules: no em dashes in learner prose; every prompt leads with the deliverable;
 * money and percentage columns state an explicit ROUND so grading never depends on
 * summation order.
 */
import type { SqlLevel, SqlModule } from "@/lib/tutorials/types"

type SqlLesson = SqlLevel["modules"][number]["lessons"][number]

// ---------------------------------------------------------------------------
// Lesson 9.4.1 seed — the architecture-review portfolio. One row per data product, each
// carrying the decision that consumes it, the freshness that decision needs, the pipeline
// shape actually running, and what that pipeline costs. Freshness values are all distinct
// so "strictest first" is a total order with no tiebreak to argue about.
//
// The mismatches are planted in BOTH directions on purpose. Three products (ml_features,
// marketing_attribution, exec_dashboard) run stricter than their requirement needs and are
// the practice's answer. support_routing runs LOOSER than it needs (batch against a
// 15-minute requirement), which is the under-provisioned case: it makes the practice's
// comparison directional, so `pipeline_type <> recommended_type` no longer passes.
// ---------------------------------------------------------------------------

const DATA_PRODUCTS_SEED = `CREATE TABLE data_products (
  product                    TEXT,
  consuming_decision         TEXT,     -- the decision this data exists to support
  required_freshness_minutes INTEGER,  -- how old the data may be when that decision is made
  pipeline_type              TEXT,     -- batch | micro-batch | streaming (what runs today)
  monthly_cost_usd           INTEGER
);
INSERT INTO data_products (product, consuming_decision, required_freshness_minutes, pipeline_type, monthly_cost_usd) VALUES
  ('fraud_scoring',         'block a card transaction before it settles',   1,     'streaming',   4800),
  ('ops_alerting',          'page on-call when ingestion stalls',           2,     'streaming',   2100),
  ('inventory_sync',        'hide an item the storefront just sold out of', 10,    'micro-batch',  900),
  ('support_routing',       'send a new ticket to the right agent queue',   15,    'batch',        800),
  ('ml_features',           'refresh the churn model feature table',        60,    'streaming',   3400),
  ('marketing_attribution', 'reallocate channel spend for tomorrow',        720,   'micro-batch', 1500),
  ('exec_dashboard',        'the Monday morning revenue review',            1440,  'streaming',   6200),
  ('finance_close',         'the month-end ledger reconciliation',          2880,  'batch',        700),
  ('partner_catalog',       'the weekly partner product feed',              10080, 'batch',        260);`

// ---------------------------------------------------------------------------
// Lesson 9.4.2 seeds — the run log an observability tool reads, plus the per-pipeline
// freshness contract. `max_event_time_ms` is the high-water mark of the data a run landed,
// which is a different number from `completed_ms` and the whole point of the lesson.
//
// Three shapes are planted on purpose:
//   * inventory_sync and exec_dashboard end on a FAILED run that still recorded the
//     watermark it was attempting, so MAX over every run reports data that was never
//     committed and only the latest SUCCESSFUL run is a legal answer.
//   * ml_features ends on two silent successes (green, zero rows, watermark frozen), which
//     is why its data is 70 minutes old against a 60-minute SLA.
//   * exec_dashboard's newest committed data is 4 hours old and that is fine, because its
//     SLA is a day. Old is not the same as breaching.
//   * support_routing carries a failed run (sup-1289) in the MIDDLE of its history, so
//     "has a failed run" and "is sitting on a failed run" are different sets and drill-1
//     cannot be passed with a plain `WHERE status = 'failed'`. Its newest run also lands a
//     7.5-minute lag, the one fractional lag in the seed, so drill-2's integer-division
//     warning is enforced instead of merely stated.
// That puts the run count at 23, one above the 22 the curriculum map sketches.
// Now is fixed at 1767290400000 ms (2026-01-01T18:00:00Z) in every prompt.
// ---------------------------------------------------------------------------

const PIPELINE_RUNS_SEED = `CREATE TABLE stream_pipeline_runs (
  pipeline          TEXT,
  run_id            TEXT,
  completed_ms      INTEGER,  -- when the run finished (processing time)
  max_event_time_ms INTEGER,  -- newest event time in the data this run landed (event time)
  status            TEXT,     -- success | failed
  rows_written      INTEGER
);
INSERT INTO stream_pipeline_runs (pipeline, run_id, completed_ms, max_event_time_ms, status, rows_written) VALUES
  ('fraud_scoring',   'fs-2041',   1767289080000, 1767289020000, 'success',  4110),
  ('fraud_scoring',   'fs-2042',   1767289380000, 1767289020000, 'success',     0),
  ('fraud_scoring',   'fs-2043',   1767289680000, 1767289620000, 'success',  4260),
  ('fraud_scoring',   'fs-2044',   1767289980000, 1767289920000, 'success',  3890),
  ('fraud_scoring',   'fs-2045',   1767290280000, 1767290220000, 'success',  4120),
  ('inventory_sync',  'inv-770',   1767287700000, 1767287520000, 'success',   610),
  ('inventory_sync',  'inv-771',   1767288600000, 1767288420000, 'success',   655),
  ('inventory_sync',  'inv-772',   1767289380000, 1767289200000, 'success',   700),
  ('inventory_sync',  'inv-773',   1767290220000, 1767290100000, 'failed',      0),
  ('exec_dashboard',  'exec-311',  1767189900000, 1767189600000, 'success', 51200),
  ('exec_dashboard',  'exec-312',  1767218700000, 1767218400000, 'success', 49800),
  ('exec_dashboard',  'exec-313',  1767247500000, 1767247200000, 'success', 50400),
  ('exec_dashboard',  'exec-314',  1767276300000, 1767276000000, 'success', 48500),
  ('exec_dashboard',  'exec-315',  1767288600000, 1767288300000, 'failed',      0),
  ('ml_features',     'mlf-508',   1767279300000, 1767279000000, 'success', 12400),
  ('ml_features',     'mlf-509',   1767282900000, 1767279000000, 'success',     0),
  ('ml_features',     'mlf-510',   1767286500000, 1767286200000, 'success', 12380),
  ('ml_features',     'mlf-511',   1767290100000, 1767286200000, 'success',     0),
  ('support_routing', 'sup-1289',  1767283200000, 1767282900000, 'failed',      0),
  ('support_routing', 'sup-1290',  1767285000000, 1767284700000, 'success',   340),
  ('support_routing', 'sup-1291',  1767286800000, 1767286500000, 'success',   355),
  ('support_routing', 'sup-1292',  1767288600000, 1767288300000, 'success',   362),
  ('support_routing', 'sup-1293',  1767290010000, 1767289560000, 'success',   371);`

const FRESHNESS_SLAS_SEED = `CREATE TABLE freshness_slas (
  pipeline        TEXT,
  max_age_minutes INTEGER   -- the oldest this pipeline's data is allowed to be
);
INSERT INTO freshness_slas (pipeline, max_age_minutes) VALUES
  ('fraud_scoring',    5),
  ('inventory_sync',  15),
  ('support_routing', 30),
  ('ml_features',     60),
  ('exec_dashboard', 1440);`

const FRESHNESS_SEED = PIPELINE_RUNS_SEED + "\n\n" + FRESHNESS_SLAS_SEED

// ---------------------------------------------------------------------------
// Module 9.4 — Choosing Batch vs Streaming
// ---------------------------------------------------------------------------

const batchVsStreamingDecision: SqlLesson = {
  id: "de-l9-batch-vs-streaming-decision",
  title: "Batch, Micro-Batch, or Streaming: The Decision",
  summary:
    "Pick the pipeline shape from the latency the consuming decision requires, then find the over-engineered products in a portfolio and price the mistake.",
  estimatedMinutes: 26,
  difficulty: "medium",
  skills: [
    "batch vs streaming tradeoffs",
    "freshness requirements",
    "micro-batch",
    "cost and complexity reasoning",
    "CASE ladders",
    "portfolio analysis",
  ],
  teach: {
    estimatedMinutes: 12,
    markdown: `## One question decides it

Every good batch-versus-streaming answer starts from the same question, and it is not a question about technology:

> **What decision consumes this data, and what latency does that decision require?**

The consuming decision sets the clock. The clock picks the pipeline. Run the question on three products and it answers itself:

- A fraud model that has to block a card transaction *before it settles* has seconds. That is streaming, and the cost is earned.
- A storefront that has to stop showing an item that just sold out has minutes. Minutes is not streaming. Minutes is a job that runs every few minutes.
- A revenue review that happens Monday morning has a day. That is one scheduled run, and anything fancier is money spent on nothing.

Notice what the question is not. It is not "is streaming better", it is not "what does the team already run", and it is not "what sounds modern". Interviewers ask this because production teams ask it, and because the wrong answer is expensive in both dollars and pager volume.

## The three shapes, and what each one costs you

**Batch** runs on a schedule, reads a bounded window of data, writes its output, and exits. One process, one input, one output, a clean success or failure, and a rerun you can reason about. Backfilling is just running it again with a different date parameter. It is the cheapest thing to build, the cheapest thing to run, and the easiest thing to debug at 3am.

**Micro-batch** is batch with a short period. The same bounded job runs every few minutes over whatever arrived since the last run. This is the entry juniors skip, and it is the most useful one on the list: it collects nearly all of streaming's perceived benefit at nearly none of streaming's cost. Most systems described as "real-time" in a product meeting are micro-batch underneath.

**Streaming** is a process that never exits. It reads an unbounded log, keeps state, emits results continuously, and has to answer questions the other two never face. When is a window complete. What happens to an event that arrives late. How does the job rebuild its state after a crash. Who gets paged when consumer lag climbs. Streaming is not a faster batch job, it is a different operational contract, and you sign that contract for the whole life of the pipeline.

## Two clocks, and the ladder only reads one

Two numbers get mixed up constantly in this conversation, and separating them is most of what makes an answer sound senior.

**Required freshness** is the consumer's number: how old the data is allowed to be at the moment the decision is made. **Run period** is the pipeline's number: how often the job wakes up. The ladder below sets its boundaries on required freshness, because that is the number the consuming decision hands you, and it is the only one you cannot negotiate.

Run period is then a design choice underneath that boundary, and it has one rule: a job's period has to sit comfortably under the freshness it serves, because a job that runs every ten minutes can hand you data ten minutes stale on a bad day and cannot promise better. A job on a five to ten minute schedule serves a thirty-minute requirement with room for a retry. The same job cannot serve a three-minute requirement, which is why the ladder pushes anything under five minutes into streaming even though micro-batch periods that short exist.

If an earlier level left you with "micro-batch runs tiny batches every few seconds", replace it with the sentence above. A period measured in seconds is streaming's operational contract wearing a batch costume: at that cadence you are already paying for always-on infrastructure, state, and someone on call. Micro-batch worth the name is a scheduled job on a period of a few minutes, and that is what the 5-to-60-minute band is built for.

\`\`\`csdiagram
{
  "type": "ladder",
  "title": "Required freshness picks the pipeline",
  "scale": "log",
  "bands": [
    {
      "label": "Under 5 minutes: streaming",
      "value": 1,
      "display": "~1 min",
      "note": "A log plus a stream processor, always on. Highest cost, highest complexity: state, watermarks, replay, and an on-call rotation. Justified by fraud, real-time personalization, and operational systems."
    },
    {
      "label": "5 to 60 minutes: micro-batch",
      "value": 30,
      "display": "~30 min",
      "note": "The same bounded job on a short schedule, typically a run every few minutes, comfortably inside the freshness it is serving. Moderate cost, ordinary orchestration, reruns are trivial. Covers almost everything a stakeholder calls real-time."
    },
    {
      "label": "Over 60 minutes: batch",
      "value": 1440,
      "display": "1 day",
      "note": "One scheduled run over a bounded window. Cheapest to build and run, easiest to backfill, easiest to reason about when it breaks."
    }
  ],
  "caption": "The bands are required freshness, not run period. Read the ladder downward from the decision, never upward from the technology. If batch satisfies the requirement, batch is the right answer."
}
\`\`\`

## The ladder is a CASE expression

The nice thing about a decision framework with numeric boundaries is that it is a query. A portfolio of data products, each with the freshness its consumer needs, classifies itself:

\`\`\`sql
CASE
  WHEN required_freshness_minutes < 5  THEN 'streaming'
  WHEN required_freshness_minutes <= 60 THEN 'micro-batch'
  ELSE                                       'batch'
END
\`\`\`

The order of the branches is the whole trick. A \`CASE\` ladder stops at the first branch that matches, so writing the loosest condition first collapses every product into one bucket. Write the boundaries strictest to loosest and each branch only has to state its own upper limit.

Once the recommendation is a column, the gap between what a product *needs* and what it *runs* is a comparison, and the cost of that gap is already sitting in the next column. That comparison is the exact argument a junior engineer makes in an architecture review, and it is the graded work in this lesson.

**Common mistake:** defaulting to streaming because it sounds impressive. Interviewers name this one directly, and it is the single most reliable junior tell in a design round. Streaming buys latency and charges for it in state management, replay complexity, late-data handling, and on-call load, so proposing it for a dashboard that a human reads on Monday morning tells the interviewer you have never carried the pager for one.

**Interview nuance:** when a design prompt says "build a real-time pipeline", the strong-candidate move is to ask what decision consumes the output and how fresh it has to be *before* proposing an architecture. That single question separates candidates who have shipped pipelines from candidates who have read about them, and it is a cheap signal to send: it costs one sentence.

Two words worth having ready for the architecture round. **Lambda architecture** runs a batch layer and a speed layer in parallel and merges them at read time, which means two implementations of the same business logic and two chances to disagree. **Kappa architecture** keeps a single streaming path and rebuilds history by replaying the log, which is simpler to reason about but pushes everything into the streaming operational contract. Naming both, and naming the code-duplication cost of Lambda, is enough at the junior bar.

> **On a real platform this differs.** Here the portfolio is one small table. On a real platform the same table exists as an architecture-review spreadsheet, a service catalog, or a set of tags on the pipelines themselves, and the cost column is joined in from a cloud billing export. The reasoning is identical and so is the query: classify by required freshness, compare against what is running, and sort the disagreements by money.`,
    demoSeedSql: DATA_PRODUCTS_SEED,
    demoCode: `-- The architecture-review portfolio, strictest requirement first. The urgency column is a
-- plain CASE over required_freshness_minutes, phrased the way a stakeholder would say it.
SELECT product,
       consuming_decision,
       required_freshness_minutes,
       CASE
         WHEN required_freshness_minutes <= 2 THEN 'within a couple of minutes'
         WHEN required_freshness_minutes <= 60 THEN 'within the hour'
         WHEN required_freshness_minutes <= 1440 THEN 'within the day'
         ELSE 'a few days is fine'
       END AS urgency,
       pipeline_type,
       monthly_cost_usd
FROM data_products
ORDER BY required_freshness_minutes;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-batch-vs-streaming-decision-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each data product with its recommended pipeline type, as \`(product, required_freshness_minutes, recommended_type)\`, strictest requirement first, over \`data_products(product, consuming_decision, required_freshness_minutes, pipeline_type, monthly_cost_usd)\`.

Use the framework's boundaries: under 5 minutes is \`streaming\`, 5 to 60 minutes inclusive is \`micro-batch\`, and over 60 minutes is \`batch\`. Alias the classified column exactly \`recommended_type\`, ordered by \`required_freshness_minutes\` ascending. Ignore the \`pipeline_type\` that is running today, this is the recommendation from first principles.`,
    starterCode: `-- Recommended pipeline type per product, strictest freshness requirement first.
SELECT product,
       required_freshness_minutes,
       -- a CASE ladder over required_freshness_minutes, strictest branch first
FROM data_products;`,
    hints: [
      "A `CASE` ladder stops at the first branch that matches, so put the strictest boundary first: `WHEN required_freshness_minutes < 5 THEN 'streaming'`.",
      "The second branch only needs its own upper limit, `WHEN required_freshness_minutes <= 60 THEN 'micro-batch'`, because anything under 5 already left the ladder.",
      "`ELSE 'batch'` catches everything over 60, and `ORDER BY required_freshness_minutes` puts the strictest requirement on top.",
    ],
    referenceSolution: `SELECT product,
       required_freshness_minutes,
       CASE
         WHEN required_freshness_minutes < 5 THEN 'streaming'
         WHEN required_freshness_minutes <= 60 THEN 'micro-batch'
         ELSE 'batch'
       END AS recommended_type
FROM data_products
ORDER BY required_freshness_minutes;`,
    singleFile: {
      seedSql: DATA_PRODUCTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["product", "required_freshness_minutes", "recommended_type"],
        rows: [
          ["fraud_scoring", 1, "streaming"],
          ["ops_alerting", 2, "streaming"],
          ["inventory_sync", 10, "micro-batch"],
          ["support_routing", 15, "micro-batch"],
          ["ml_features", 60, "micro-batch"],
          ["marketing_attribution", 720, "batch"],
          ["exec_dashboard", 1440, "batch"],
          ["finance_close", 2880, "batch"],
          ["partner_catalog", 10080, "batch"],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-batch-vs-streaming-decision-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the products whose running pipeline is stricter than their requirement needs, with the monthly cost of that mismatch, as \`(product, pipeline_type, recommended_type, monthly_cost_usd)\`, most expensive first, over the same \`data_products\` table.

Strictness runs \`streaming\` above \`micro-batch\` above \`batch\`. Keep a product only when its running \`pipeline_type\` sits higher on that scale than the \`recommended_type\` the freshness boundaries give it. Use the same boundaries as the Apply: under 5 minutes streaming, 5 to 60 micro-batch, over 60 batch.`,
    starterCode: `-- Products running a stricter pipeline than their freshness requirement needs,
-- most expensive mismatch first.
SELECT
  -- product, what runs today, what the requirement calls for, and what the gap costs
FROM data_products;`,
    hints: [
      "Classify first: a CTE that adds `recommended_type` with the same CASE ladder keeps the comparison readable.",
      "Turn both type names into a number so they can be compared: `CASE pipeline_type WHEN 'streaming' THEN 3 WHEN 'micro-batch' THEN 2 ELSE 1 END`, and the same for `recommended_type`.",
      "Keep the rows where the running rank is strictly greater than the needed rank, then `ORDER BY monthly_cost_usd DESC`.",
    ],
    singleFile: {
      seedSql: DATA_PRODUCTS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["product", "pipeline_type", "recommended_type", "monthly_cost_usd"],
        rows: [
          ["exec_dashboard", "streaming", "batch", 6200],
          ["ml_features", "streaming", "micro-batch", 3400],
          ["marketing_attribution", "micro-batch", "batch", 1500],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-batch-vs-streaming-decision-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns total monthly spend by pipeline shape, as \`(pipeline_type, monthly_cost)\`, most expensive first, over \`data_products\`.`,
      starterCode: `-- One row per pipeline_type with that shape's combined monthly cost.
SELECT
FROM data_products;`,
      hints: [
        "Group by `pipeline_type` so each shape collapses to one row.",
        "`SUM(monthly_cost_usd) AS monthly_cost`, then `ORDER BY monthly_cost DESC`.",
      ],
      referenceSolution: `SELECT pipeline_type, SUM(monthly_cost_usd) AS monthly_cost
FROM data_products
GROUP BY pipeline_type
ORDER BY monthly_cost DESC;`,
      singleFile: {
        seedSql: DATA_PRODUCTS_SEED,
        orderMatters: true,
        expected: {
          columns: ["pipeline_type", "monthly_cost"],
          rows: [
            ["streaming", 16500],
            ["micro-batch", 2400],
            ["batch", 1760],
          ],
        },
      },
    },
    {
      id: "de-l9-batch-vs-streaming-decision-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns the share of total portfolio cost going to over-engineered streaming as \`(overbuilt_streaming_pct)\`, rounded to 2 decimals, over \`data_products\`.

Over-engineered streaming means the product runs \`streaming\` while its required freshness is 5 minutes or more, so the framework would not have recommended it.`,
      starterCode: `-- Percent of the whole portfolio's monthly cost spent on streaming that the
-- freshness requirement did not call for.
SELECT
FROM data_products;`,
      hints: [
        "A conditional sum isolates the numerator: `SUM(CASE WHEN pipeline_type = 'streaming' AND required_freshness_minutes >= 5 THEN monthly_cost_usd ELSE 0 END)`.",
        "Divide by `SUM(monthly_cost_usd)` over the whole table, multiply by 100.0, and wrap it in `ROUND(..., 2)`.",
      ],
      referenceSolution: `SELECT ROUND(
         100.0 * SUM(CASE WHEN pipeline_type = 'streaming' AND required_freshness_minutes >= 5
                          THEN monthly_cost_usd ELSE 0 END)
         / SUM(monthly_cost_usd), 2) AS overbuilt_streaming_pct
FROM data_products;`,
      singleFile: {
        seedSql: DATA_PRODUCTS_SEED,
        expected: { columns: ["overbuilt_streaming_pct"], rows: [[46.47]] },
      },
    },
  ],
}

const freshnessSlas: SqlLesson = {
  id: "de-l9-freshness-slas",
  title: "Freshness SLAs over Run Metadata",
  summary:
    "Measure the age of the data, not the health of the job, against a per-pipeline freshness contract, and catch the green run that wrote nothing.",
  estimatedMinutes: 30,
  difficulty: "hard",
  skills: [
    "freshness SLAs",
    "data age",
    "run metadata analysis",
    "silent success detection",
    "ROW_NUMBER latest-run selection",
    "JOIN",
    "report shaping",
  ],
  teach: {
    estimatedMinutes: 13,
    markdown: `## Freshness is a property of the data, not the job

The previous lesson made a promise: this product needs data no older than fifteen minutes. This lesson measures whether the promise is being kept, and the measurement is not the one most people reach for first.

You have met a freshness SLA twice already, and both times through a stand-in. Level 6 graded whether a run finished inside its SLA minutes and flagged in the prose that run duration was only a proxy for freshness. Level 8 measured a task SLA the same way and made the same admission, that a task can succeed and still miss. This lesson retires the proxy and measures the thing itself, because run duration cannot see the one failure it most needs to catch: a job that ran on schedule, exited green, and wrote nothing at all.

A green run tells you the process exited zero. It does not tell you the data is current. A pipeline can succeed every five minutes for an hour while writing nothing, because the upstream topic went quiet, a filter was tightened, or a credential expired in a way the job swallowed. That failure has a name and it is the one production teams miss most often: **silent success, pipeline green but zero rows written**. Nobody gets paged, because there is nothing to page on. The dashboard just stops moving.

So the measurement is on the data:

\`\`\`text
data age = now - (newest event time actually landed by the latest SUCCESSFUL run)
\`\`\`

Two words in that line are load-bearing.

**Event time, not completion time.** \`completed_ms\` says when the process finished. \`max_event_time_ms\` says how new the newest record it committed actually was. A run that finishes at 18:00 having processed events up to 14:00 has landed four-hour-old data, and it is the second number the consumer feels.

**Latest successful, not latest.** A failed run still writes a row to the run log, and in this seed it also records the watermark it was *attempting* when it died. Take \`MAX(max_event_time_ms)\` across every run and you will report data that was never committed. The pick you want is the newest run whose status is \`success\`, which is a per-pipeline top-1 and therefore \`ROW_NUMBER\`.

A fair objection: why not \`MAX(max_event_time_ms)\` over just the *successful* runs, grouped by pipeline, and skip the window function? On data like this it returns the same numbers, and it has to, because every pipeline's successful watermarks climb. The two answers come apart the first time a reprocess lands an older window, which backfills do routinely. \`MAX\` then answers "the highest watermark this pipeline ever committed", while \`ROW_NUMBER\` answers "where the run that committed last actually got to". The second is the question your on-call is asking, so write the query that keeps meaning what you meant when the data stops being tidy.

## The SLA turns a number into a verdict

Data age on its own is a number, not a problem. A freshness SLA is the per-pipeline contract that makes it a verdict: \`max_age_minutes\` per pipeline, joined onto the age, compared. This is what makes "we stream this one" and "hourly is fine for that one" the same measurable thing, and it is how the previous lesson's decision stops being a slide and starts being enforced.

The corollary catches people out in review: **old is not the same as breaching**. A dashboard pipeline whose newest data is four hours old is perfectly healthy when its SLA is a day. A fraud pipeline whose newest data is six minutes old is on fire when its SLA is five. Age without the contract beside it is a number nobody can act on.

\`\`\`csdiagram
{
  "type": "table",
  "columns": ["run", "finished (min ago)", "high-water mark (min ago)", "rows_written", "status"],
  "rows": [
    ["mlf-508", 185, 190, 12400, "success"],
    ["mlf-509", 125, 190, 0, "success"],
    ["mlf-510", 65, 70, 12380, "success"],
    ["mlf-511", 5, 70, 0, "success"]
  ],
  "highlightCols": ["high-water mark (min ago)", "rows_written"],
  "caption": "ml_features against a 60-minute SLA. Every run is green and the newest one finished 5 minutes ago, but the high-water mark has not moved in 70 minutes because two runs wrote zero rows. Job health says fine, data age says breach."
}
\`\`\`

## Picking the latest successful run

\`ROW_NUMBER\` partitioned by pipeline and ordered by \`completed_ms\` descending numbers each pipeline's runs from newest to oldest; filtering to \`rn = 1\` keeps exactly one row per pipeline. Filter to successful runs *before* the numbering, inside the CTE, so a failed newest run drops out instead of winning the partition.

This is the same top-N-per-group shape as picking a customer's latest order, and it is worth recognizing on sight because it appears in almost every SQL round.

**Common mistake:** computing age from \`completed_ms\` instead of \`max_event_time_ms\`. It reports every pipeline as fresh the moment a job finishes, which is exactly the blind spot that lets a silent success sit undetected for a day. If your freshness query cannot fail while every job is green, it is measuring the job, not the data.

**Interview nuance:** "how would you know your pipeline is actually delivering fresh data" is the operations follow-up to every pipeline-design answer, and the complete reply is three parts: age measured on event time, a per-pipeline SLA to compare it against, and a row-count check so a green run that wrote nothing cannot hide behind a healthy-looking job. Freshness is also the first of the five data-observability pillars, ahead of volume, schema, distribution, and lineage, so naming it first is naming the list in the order the field uses.

> **On a real platform this differs.** The run log here is one table you can query. In production the same numbers come from your orchestrator's run history joined to a per-table watermark, from dbt's source freshness check (which compares a loaded-at column against warn and error thresholds you declare in YAML), or from an observability tool such as Monte Carlo that tracks freshness as its first pillar and alerts on the deviation rather than on a fixed number. What does not change is the arithmetic: now minus the newest event time actually committed, compared against a contract somebody signed.`,
    demoSeedSql: FRESHNESS_SEED,
    demoCode: `-- The latest SUCCESSFUL run per pipeline. Filtering to success inside the CTE is what
-- keeps a failed newest run from winning its partition.
WITH ranked AS (
  SELECT pipeline, run_id, completed_ms, max_event_time_ms, rows_written,
         ROW_NUMBER() OVER (PARTITION BY pipeline ORDER BY completed_ms DESC) AS rn
  FROM stream_pipeline_runs
  WHERE status = 'success'
)
SELECT pipeline, run_id, completed_ms, max_event_time_ms, rows_written
FROM ranked
WHERE rn = 1
ORDER BY pipeline;`,
    showDemoInput: false,
  },
  apply: {
    id: "de-l9-freshness-slas-apply",
    executionMode: "single-file",
    prompt: `Write a query that returns each pipeline's current data age in minutes and whether it breaches its SLA, as \`(pipeline, data_age_minutes, max_age_minutes, in_breach)\`, oldest data first, over \`stream_pipeline_runs(pipeline, run_id, completed_ms, max_event_time_ms, status, rows_written)\` and \`freshness_slas(pipeline, max_age_minutes)\`.

Use each pipeline's latest successful run and now = 1767290400000. Data age is \`(now - max_event_time_ms) / 60000\` in whole minutes. Set \`in_breach\` to 1 when the age is strictly greater than \`max_age_minutes\` and 0 otherwise, ordered by \`data_age_minutes\` descending.`,
    starterCode: `-- Current data age per pipeline against its freshness SLA, oldest data first.
-- now = 1767290400000
SELECT
  -- one row per pipeline: age from its latest successful run, its SLA, and the verdict
FROM stream_pipeline_runs;`,
    hints: [
      "Pick the latest successful run first: a CTE that filters `WHERE status = 'success'` and adds `ROW_NUMBER() OVER (PARTITION BY pipeline ORDER BY completed_ms DESC) AS rn`, then keep `rn = 1`.",
      "Age comes from event time, not completion time: `(1767290400000 - max_event_time_ms) / 60000`. Both operands are integers, so SQLite gives you whole minutes.",
      "Join `freshness_slas` on `pipeline`, then `CASE WHEN age > max_age_minutes THEN 1 ELSE 0 END AS in_breach` and `ORDER BY data_age_minutes DESC`.",
    ],
    referenceSolution: `WITH latest_success AS (
  SELECT pipeline,
         max_event_time_ms,
         ROW_NUMBER() OVER (PARTITION BY pipeline ORDER BY completed_ms DESC) AS rn
  FROM stream_pipeline_runs
  WHERE status = 'success'
)
SELECT l.pipeline,
       (1767290400000 - l.max_event_time_ms) / 60000 AS data_age_minutes,
       s.max_age_minutes,
       CASE WHEN (1767290400000 - l.max_event_time_ms) / 60000 > s.max_age_minutes
            THEN 1 ELSE 0 END AS in_breach
FROM latest_success l
JOIN freshness_slas s ON s.pipeline = l.pipeline
WHERE l.rn = 1
ORDER BY data_age_minutes DESC;`,
    singleFile: {
      seedSql: FRESHNESS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: ["pipeline", "data_age_minutes", "max_age_minutes", "in_breach"],
        rows: [
          ["exec_dashboard", 240, 1440, 0],
          ["ml_features", 70, 60, 1],
          ["inventory_sync", 20, 15, 1],
          ["support_routing", 14, 30, 0],
          ["fraud_scoring", 3, 5, 0],
        ],
      },
    },
  },
  practice: {
    id: "de-l9-freshness-slas-practice",
    executionMode: "single-file",
    prompt: `Write a query that returns the on-call freshness report, as \`(pipeline, max_age_minutes, data_age_minutes, in_breach, silent_success_runs)\`, breaching pipelines first and oldest data first within each group, over \`stream_pipeline_runs\` and \`freshness_slas\`.

Every pipeline in \`freshness_slas\` appears exactly once. Data age uses each pipeline's latest successful run and now = 1767290400000, in whole minutes. \`in_breach\` is 1 when the age is strictly greater than \`max_age_minutes\`. \`silent_success_runs\` counts that pipeline's runs with status \`success\` and zero rows written, across its whole history, and is 0 when there are none.`,
    starterCode: `-- The on-call freshness report. now = 1767290400000
`,
    hints: [],
    singleFile: {
      seedSql: FRESHNESS_SEED,
      orderMatters: true,
      assertColumnNames: true,
      expected: {
        columns: [
          "pipeline",
          "max_age_minutes",
          "data_age_minutes",
          "in_breach",
          "silent_success_runs",
        ],
        rows: [
          ["ml_features", 60, 70, 1, 2],
          ["inventory_sync", 15, 20, 1, 0],
          ["exec_dashboard", 1440, 240, 0, 0],
          ["support_routing", 30, 14, 0, 0],
          ["fraud_scoring", 5, 3, 0, 1],
        ],
      },
    },
  },
  extraPractice: [
    {
      id: "de-l9-freshness-slas-drill-1",
      executionMode: "single-file",
      prompt: `**Easy.** Write a query that returns the pipelines whose most recent run failed outright, as \`(pipeline, run_id)\`, by pipeline name, over \`stream_pipeline_runs\`.`,
      starterCode: `-- Pipelines sitting on a failed newest run.
SELECT pipeline, run_id
FROM stream_pipeline_runs
;`,
      hints: [
        "Number every run per pipeline with `ROW_NUMBER() OVER (PARTITION BY pipeline ORDER BY completed_ms DESC)`, without filtering on status this time.",
        "Keep the rows where the number is 1 and the status is `failed`, then `ORDER BY pipeline`.",
      ],
      referenceSolution: `WITH ranked AS (
  SELECT pipeline, run_id, status,
         ROW_NUMBER() OVER (PARTITION BY pipeline ORDER BY completed_ms DESC) AS rn
  FROM stream_pipeline_runs
)
SELECT pipeline, run_id
FROM ranked
WHERE rn = 1 AND status = 'failed'
ORDER BY pipeline;`,
      singleFile: {
        seedSql: PIPELINE_RUNS_SEED,
        orderMatters: true,
        expected: {
          columns: ["pipeline", "run_id"],
          rows: [
            ["exec_dashboard", "exec-315"],
            ["inventory_sync", "inv-773"],
          ],
        },
      },
    },
    {
      id: "de-l9-freshness-slas-drill-2",
      executionMode: "single-file",
      prompt: `**Hard.** Write a query that returns each pipeline's average landed-data age over its successful runs, as \`(pipeline, avg_landed_age_minutes)\`, rounded to 1 decimal, oldest first, over \`stream_pipeline_runs\`.

A single run's landed-data age is how old its newest record already was when the run finished: \`(completed_ms - max_event_time_ms)\` in minutes.`,
      starterCode: `-- Average lag between a run finishing and the newest event it landed, per pipeline.
SELECT pipeline
FROM stream_pipeline_runs
;`,
      hints: [
        "Keep only `status = 'success'`, since a failed run committed nothing to be old.",
        "Divide by `60000.0`, not `60000`, or integer division truncates each run's lag before the average sees it.",
        "`ROUND(AVG(...), 1) AS avg_landed_age_minutes`, grouped by pipeline, ordered descending.",
      ],
      referenceSolution: `SELECT pipeline,
       ROUND(AVG((completed_ms - max_event_time_ms) / 60000.0), 1) AS avg_landed_age_minutes
FROM stream_pipeline_runs
WHERE status = 'success'
GROUP BY pipeline
ORDER BY avg_landed_age_minutes DESC;`,
      singleFile: {
        seedSql: PIPELINE_RUNS_SEED,
        orderMatters: true,
        expected: {
          columns: ["pipeline", "avg_landed_age_minutes"],
          rows: [
            ["ml_features", 35],
            ["support_routing", 5.6],
            ["exec_dashboard", 5],
            ["inventory_sync", 3],
            ["fraud_scoring", 2],
          ],
        },
      },
    },
  ],
}

export const level9Module4: SqlModule = {
  id: "de-l9-batch-vs-streaming",
  title: "Choosing Batch vs Streaming",
  description:
    "The decision framework interviewers actually reward, then freshness measured as an SLA over run metadata, closing the level with an unscaffolded SLA report.",
  lessons: [batchVsStreamingDecision, freshnessSlas],
}
