// GENERATED by scripts/compile-packs.mjs — edit packs/<id>/ and recompile.
/**
 * Bugfix PACK registry (stdout-oracle, sealed variant). Kept OUT of the locked
 * legacy-10 bank (realWorldBugFixScenarios); resolves by id through the async lazy
 * loader in lib/scenarios/index.ts.
 */
import type { BugFixScenario } from "../../../types"
import type { BugfixPack } from "@/lib/bugfix/packs/types"
import {
  datadogMetricWindowRollupPack,
  datadogMetricWindowRollupScenario,
} from "./datadog-metric-window-rollup"
import {
  palantirFoundryUsageRollupPack,
  palantirFoundryUsageRollupScenario,
} from "./palantir-foundry-usage-rollup"
import {
  palantirOntologyLinkRollupPack,
  palantirOntologyLinkRollupScenario,
} from "./palantir-ontology-link-rollup"
import {
  stripeWebhookIdempotencyPack,
  stripeWebhookIdempotencyScenario,
} from "./stripe-webhook-idempotency"

export const bugfixPackScenarios: BugFixScenario[] = [
  datadogMetricWindowRollupScenario,
  palantirFoundryUsageRollupScenario,
  palantirOntologyLinkRollupScenario,
  stripeWebhookIdempotencyScenario,
]

/** Raw client-safe pack contracts (parallel to bugfixPackScenarios), for validation. */
export const bugfixPacks: BugfixPack[] = [
  datadogMetricWindowRollupPack,
  palantirFoundryUsageRollupPack,
  palantirOntologyLinkRollupPack,
  stripeWebhookIdempotencyPack,
]

export default bugfixPackScenarios
