// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { SprintPublic } from "@/lib/sprint-labs/types"

export const meridianSprint06: SprintPublic = {
  number: 6,
  title: "Ship it",
  goal: "Get Meridian off long-lived AWS keys and out of the upload path: presigned uploads, a real SQS consumer, two scoped IAM roles, secrets in a rotation-safe provider, and a blue/green release with a rollback you have actually executed, and then read the bill your own week of work generated.",
  standupQuote:
    "Northwind's 41 MB PDF 504s every single time and the api pod OOMKilled twice tonight; also while I was in there, the key that uploads it is a 412-day-old AKIA in the task definition and it can write any bucket in the account.",
  archMapDelta: {
    added: [
      "Presigned S3 upload flow for document intake, off the request path",
      "A real SQS consumer driving extraction, with a dead-letter queue",
      "Two scoped IAM roles (API, extraction worker) provisioned via Terraform",
      "Secrets loaded from a rotation-safe provider instead of the environment",
      "A blue/green ECS release with an executed rollback",
    ],
    changed: ["Document upload no longer streams bytes through the API's own request handler"],
    broke: ["AWS spend went from $180/mo to $4,900 in the first nine days of this sprint's work"],
    invariants: [
      "No long-lived AWS access key exists in any task definition, image, or repository",
      "Every IAM policy grants only the actions and resource ARNs its own service actually calls, never a wildcard",
    ],
  },
  objectives: [
    {
      id: "presigned-s3-upload-scoped",
      label: "Scoped presigned uploads",
      canDo:
        "I can move an upload out of my API's request path with a presigned S3 upload scoped to one tenant, one key, one content type, and one size ceiling, verified server-side before it counts as received.",
    },
    {
      id: "least-privilege-iam-secrets-rotation",
      label: "Least-privilege IAM and secret rotation",
      canDo:
        "I can write an IAM policy from the application's actual call sites with no wildcard actions and no wildcard resource ARNs, prove it with a policy-simulation test in CI, and get every secret out of the environment and the image into a cached, rotation-safe provider.",
    },
    {
      id: "sqs-consumer-at-least-once-delivery",
      label: "At-least-once SQS consumers",
      canDo:
        "I can operate a long-lived SQS consumer correctly under at-least-once delivery: visibility timeout matched to p99, heartbeat extension with a ceiling, partial batch deletes, DLQ redrive, and a SIGTERM drain that releases in-flight work.",
    },
    {
      id: "blue-green-rollback-review",
      label: "Blue/green rollback review",
      canDo:
        "I can ship a blue/green release with an expand-then-contract migration, execute the rollback under live traffic, and review an agent-authored version of that change for the failure modes a rollback cannot fix.",
    },
    {
      id: "cloud-cost-attribution",
      label: "Cloud cost attribution",
      canDo:
        "I can read an AWS cost-and-usage export and attribute a large bill increase to specific lines of my own code, then bring it down without deleting the observability.",
    },
  ],
  topic: "Cloud & deployment (AWS)",
  ticketCount: 5,
  points: 28,
}
