// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { SprintPublic } from "@/lib/sprint-labs/types"

export const meridianSprint08: SprintPublic = {
  number: 8,
  title: "The model",
  goal: "Replace the regex extractor with a model call you can constrain, retrieve against, cap, cache and stream, without letting one claim be paid on a number the system cannot explain, cannot reproduce, or cannot afford.",
  standupQuote:
    "the total-loss Camry came back at $0.00 and your webhook says completed, so we paid it. How many of the other 900 are like that?",
  archMapDelta: {
    added: [
      "LLM-backed extraction behind a replayable seam (no network, no provider key, in CI)",
      "JSON-Schema-constrained model output with three distinct typed failure outcomes",
      "Tenant-scoped policy retrieval, exposed to the extractor as a callable tool, with citations",
      "A local result cache plus a provider prompt-prefix cache with a documented two-column taxonomy",
    ],
    changed: ["The regex extractor is replaced entirely by a model call"],
    broke: [
      "A total-loss claim was paid on a fabricated $0.00 deductible the extractor could not actually find",
    ],
    invariants: [
      "Extraction always returns one of a fixed set of typed outcomes, never a bare guess standing in for one",
      "Retrieval's tenant and document scope is bound at the call site from the job envelope's tenant, never from anything the model's own output supplies",
    ],
  },
  objectives: [
    {
      id: "llm-replayable-seam-typed-abstention",
      label: "Replayable LLM seam",
      canDo:
        "I can put an LLM behind a replayable seam so the entire extraction path runs in CI with no network and no provider key, and a model or prompt change shows up as a diff instead of a surprise.",
    },
    {
      id: "constrained-json-output-typed-errors",
      label: "Constrained output and typed failures",
      canDo:
        "I can constrain model output with a JSON Schema generated from the same source the code validates against, and handle schema-invalid, timed-out, and rate-limited responses as three distinct typed outcomes rather than one catch block.",
    },
    {
      id: "tenant-scoped-policy-retrieval",
      label: "Tenant-scoped policy retrieval",
      canDo:
        "I can build tenant-scoped retrieval over policy documents that cites the chunks it used and resolves the revision in force on the loss date, not the newest one.",
    },
    {
      id: "cost-ceiling-cache-key-design",
      label: "Cost ceilings and cache keys",
      canDo:
        "I can enforce a hard cost-per-claim ceiling before the spend happens, accounting for tokens burned on repair turns and cache hits, and derive a cache key from everything the answer depends on so a semantic near-match is never mistaken for an extraction match.",
    },
    {
      id: "review-streaming-pr-hidden-regressions",
      label: "Reviewing a streaming PR",
      canDo:
        "I can review a streaming PR that is green, fast, and wrong, and name which of its changes produce a wrong payout, a silent bill, and an SLO alert that will never fire again.",
    },
  ],
  sizingNotes:
    "Points are unchanged from SPRINT-PLAN.md (5/8/8/8/5 = 34), per AUTHORING-RULES.md §3 ('Sprint 8's sizingNotes records the no-breather concern; points unchanged'). Flagging the concern rather than resizing: MER-802, MER-803, and MER-804 are three consecutive 8-point tickets with no lighter ticket between them, unlike every other sprint in the workbook, which alternates weight. Whoever schedules learner pacing for this sprint should expect no natural breather between the second and fourth ticket.",
  topic: "AI engineering in production",
  ticketCount: 5,
  points: 34,
}
