// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { SprintPublic } from "@/lib/sprint-labs/types"

export const meridianSprint07: SprintPublic = {
  number: 7,
  title: "When It Breaks",
  goal: "Make Meridian explain itself under load: request-scoped structured logs, trace context that survives the queue boundary, an honest latency signal, an SLO with alerts that fire once, and close the 14:05 incident with a review that would actually prevent it.",
  standupQuote:
    "p99 on POST /claims went 380ms → 2.1s at 14:05 and it has not come back. Rico grabbed one trace before the tab died: it's a single 2.1s span called POST /claims with nothing inside it. Logs for that minute are 40-line pretty-printed blobs with no claim id. Nobody can tell me if this is us or Postgres.",
  archMapDelta: {
    added: [
      "Request-scoped structured logging carrying trace, tenant, and claim identity",
      "W3C trace context propagated across the outbox and SQS boundary",
      "A written SLI and multi-window burn-rate alerts for the claims API",
    ],
    changed: ["Log lines are single structured records instead of multi-line pretty-printed blobs"],
    broke: [
      "p99 on POST /claims regressed from 380ms to 2.1s at 14:05 with no diagnosis available",
    ],
    invariants: [
      "Every request-scoped log line carries trace, tenant, and claim identity without leaking across concurrent requests",
      "A trace started by an API request continues through the outbox row, the queued message, and the delivery worker as one trace",
    ],
  },
  objectives: [
    {
      id: "request-scoped-structured-logging",
      label: "Request-scoped structured logs",
      canDo:
        "I can instrument a service with request-scoped structured logs carrying trace, tenant, and claim identity, without leaking PII or letting one request's context bleed into another's under concurrency.",
    },
    {
      id: "distributed-trace-context-propagation",
      label: "Trace context across async boundaries",
      canDo:
        "I can propagate W3C trace context across an asynchronous boundary, from an HTTP request to an outbox row to a queue message to a delivery worker, so a claim and its retried webhooks read as one causal story.",
    },
    {
      id: "latency-regression-diagnosis-wait-vs-service-time",
      label: "Latency regression diagnosis",
      canDo:
        "I can read a distributed trace to locate a p99 regression that lives in the gaps between spans, separate wait time from service time including event-loop delay, and prove the diagnosis with a test that is red before the fix and green after.",
    },
    {
      id: "slo-error-budget-burn-rate-alerts",
      label: "SLOs and burn-rate alerts",
      canDo:
        "I can turn an uptime promise into a written SLI, an error budget, and multi-window burn-rate alerts, then replay those alerts against real incident data to show they fire for the incident and not for the quiet week.",
    },
    {
      id: "review-postmortem-systemic-causes",
      label: "Reviewing a postmortem",
      canDo:
        "I can review an AI-drafted postmortem and rewrite it so it names systemic causes rather than a person or a trigger, with every action item attached to a test or a named owner.",
    },
  ],
  sizingNotes:
    "SPRINT-PLAN.md's own sizing table under-points this sprint at 19 (§'Fixes to apply' item 8: 'Sprint 7 is under-pointed... 25-point work wearing a 19-point label,' citing five new source files plus AsyncLocalStorage-based context propagation). Per AUTHORING-RULES.md §3 ('Sprint 7 re-points to match its real weight, ~24-25 pts across the same 5 tickets'), tickets are re-pointed from the original 3/5/5/3/3 to 5/6/6/5/3, summing to 25 across the same five tickets. MER-702 (trace propagation across the outbox/SQS boundary) and MER-703 (unassisted regression diagnosis) absorb the largest increases, matching where the extra source files and the AsyncLocalStorage work actually land.",
  topic: "Observability & operations",
  ticketCount: 5,
  points: 25,
}
