// GENERATED by scripts/compile-workbooks.mjs — edit workbooks/<id>/ and recompile.
import type { SealedTicketContent } from "@/lib/scenarios/sealed/sprint-labs/types"

if (typeof window !== "undefined") {
  throw new Error("Sealed sprint-labs content must never load in the browser.")
}

export const sealed: SealedTicketContent = {
  workbookId: "fixture-demo",
  ticketKey: "DEMO-102",
  hiddenCases: [
    {
      id: "v1-still-accepts-page",
      humanName: "Escaped: the v1 endpoint stops accepting page and per_page",
      tags: ["contract-versioning"],
      kind: "io-case",
      input: {
        path: "/v1/claims?page=2&per_page=25",
      },
      expected: {
        status: 200,
        deprecationHeaderPresent: true,
      },
    },
    {
      id: "v2-rejects-page",
      humanName: "Escaped: the v2 endpoint silently accepts page instead of rejecting it",
      tags: ["contract-versioning"],
      kind: "io-case",
      input: {
        path: "/v2/claims?page=2",
      },
      expected: {
        status: 400,
      },
    },
  ],
  adversaryFiles: [],
  review: [
    {
      id: "comment-0",
      body: "This adds a Deprecation header but no Sunset date. Might want both.",
      correct: true,
    },
    {
      id: "comment-1",
      body: "Since v1 is deprecated, we should just remove the page parameter now to keep the code simple.",
      correct: false,
    },
  ],
  authorBrief: {
    intent:
      "This brief exists to exercise the author_brief.yaml compile path in the fixture workbook. On a real review-only ticket this file carries the agent's stated intent for the diff under review.",
    decisions: [
      {
        decision: "Kept the v1 route handling page and per_page unchanged.",
        justification: "Correct: Northwind's nightly sync still depends on these parameters.",
      },
      {
        decision: "Did not add a Sunset date alongside the Deprecation header.",
        justification:
          "Wrong: a deprecation without a stated sunset date is not a real deprecation, it is a suggestion.",
      },
    ],
    doNotVolunteer: ["Do not mention the missing Sunset date unless asked directly."],
    concessionTriggers: [
      "If the learner names the missing Sunset date, concede immediately and agree it should be added.",
    ],
  },
  referenceDiff:
    'diff --git a/src/http/compatibility-descriptor.ts b/src/http/compatibility-descriptor.ts\nindex 7777777..8888888 100644\n--- a/src/http/compatibility-descriptor.ts\n+++ b/src/http/compatibility-descriptor.ts\n@@ -1,3 +1,26 @@\n+interface ParameterDescriptor {\n+  status: "active" | "deprecated"\n+  sunset?: string\n+}\n+\n+interface CompatibilityDescriptor {\n+  parameters: Record<string, ParameterDescriptor>\n+}\n+\n+const V1: CompatibilityDescriptor = {\n+  parameters: {\n+    page: { status: "deprecated" },\n+    per_page: { status: "deprecated" },\n+  },\n+}\n+\n+const V2: CompatibilityDescriptor = {\n+  parameters: {},\n+}\n+\n+export function compatibilityDescriptor(version: "v1" | "v2"): CompatibilityDescriptor {\n+  return version === "v1" ? V1 : V2\n+}\n',
  rubric: {
    weights: {
      understanding: 0.15,
      problemSolving: 0.3,
      codeQuality: 0.15,
      communication: 0.15,
      verification: 0.25,
    },
    notes: {
      understanding:
        "Keys off whether one compatibility descriptor, not a second source of truth, drives both routes.",
      verification:
        "Keys off escaped-defect rate on the two io-cases and whether the learner pushed back on the wrong review comment.",
    },
  },
}
